### ISSUE TITLE
Welcome to the Standard Notes discussion forum

### ISSUE THREAD

**Issue by moughxyz** [standardnotes/forum#1]
We'll be using GitHub issues for discussions. Previously, we had a custom installation of forum software Flarum, however, using GitHub instead will make it easier to maintain in the future, as well as making it easier for more people to participate.

I'll need to port over previous discussions at some point, but for now, we'll start with a blank slate.

Please feel free to post any questions, comments, feedback, concerns, conversations about random topics, privacy, security, software, etc.

**Comment by bepolymathe** [comment]
Hi,

Nice ! 
Bepolymathe
