### ISSUE TITLE
How can I delete my database?

### ISSUE THREAD

**Issue by fcqueiroz** [standardnotes/forum#100]
How can I delete my database?

I tried to import the notes from evernote, but for some reason the first import only brought half my notes, and they are not tagged, so it's really difficult to sort them and discover which notes are mising. I tried to import again using html files, but this time it was even worse. Now I got all the notes, but they have all those html codes inside... And my database is full of duplicates now. It's a big mess. Since I couldn't find a wayto delete multiple notes (really? What is the point of selecting more than one note if there is no action to be done on more than on note at a time?) I am wanting to delete my whole database and start again from scratch. It seems easier to not import anything from evernote...

**Comment by mobitar** [comment]
Hey Fernanda, sorry about the trouble. I know these things are private but
if you’d like to share an anonymized part of your import file I can debug
what went wrong. Totally up to you.

You can wipe your notes via Account -> Advanced -> Data Dashboard ->
Advanced -> Destroy all data.

**Comment by fcqueiroz** [comment]
Thanks for the quick answer! I succeeded in wiping my notes and now will manually put in this app only what I really need to synchronize

**Comment by mobitar** [comment]
Update: You can now use the Batch Manager extension for this.

Extensions -> Batch Manager -> Open.

(Only on web as of 2/28/18, coming to desktop soon.)
