### ISSUE TITLE
[Help Wanted]Can't enter Extensions Password

### ISSUE THREAD

**Issue by simob2020** [standardnotes/forum#1005]
**Describe the issue**
My Extensions subscription lapsed but I have now renewed. I attempted to enter the new password but it is refused with '_Invalid authentication. Please try again._' message
This happens in both desktop and web.

**To Reproduce**
1. Go to 'Extensions (bottom left)'
2. Click on '_Please enter your account password_'
3. See error message

**Expected behavior**
Hoping for new 5 year subscription to be acknowledged

**Screenshots**
![grab23](https://user-images.githubusercontent.com/66622847/84027232-8e84c880-a986-11ea-94ae-505893fbe666.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Firefox
 - Version 77.0.1

**Additional context**
Best advice from Help File appears to be:

_**Option 2: Force reset**_
    
_1. Using the web or desktop application, click Extensions in the lower left corner._
_2. Scroll to Repository, then press Options._
_3. Click Delete and confirm._

But pop up (in screenshot) is all that's visible, no obvious way to access Repository

**Comment by JaspalSuri** [comment]
Hi, I'm so sorry that you're running into this issue. I've assigned our Desktop and Web dev to look into it.

One Firefox, can you click on the Hamburger menu > **Web Developer** > **Web Console**, and paste any error messages that you see here after expanding everything and stripping out any personal info. 

Thanks so much!

**Comment by simob2020** [comment]
> Hi, I'm so sorry that you're running into this issue. I've assigned our Desktop and Web dev to look into it.
> 
> One Firefox, can you click on the Hamburger menu > **Web Developer** > **Web Console**, and paste any error messages that you see here after expanding everything and stripping out any personal info.
> 
> Thanks so much!

Thanks @JaspalSuri currently emailing with Jeff. In response to your comment above, this happens in the desktop app as well as the browser so I doubt that it's a Firefox issue.

**Comment by simob2020** [comment]
@baptiste-grob This screenshot might help:

![grab25](https://user-images.githubusercontent.com/66622847/84135660-27c4e500-aa42-11ea-97bd-96f246a2c953.jpg)

**Comment by simob2020** [comment]
Sorry, new to Github, didn't actually mean to close...

**Comment by JaspalSuri** [comment]
Do you happen to have access to the old password? If so, please try entering that to see if it works.

**Comment by simob2020** [comment]
It might be just me, but the instructions are misleading...The email says to copy the code into the _Extensions_ menu but the popup I saw was not asking for the code, it was asking for the Account Password. When I entered the password, everything worked.

![grab26](https://user-images.githubusercontent.com/66622847/84239346-44b9f080-aaf4-11ea-82dc-13c3c3c33d8a.jpg)

**Comment by JaspalSuri** [comment]
Oh, I understand now! We wouldn't have known about this if you had not reported it to us! 

To access your extensions, you have to enter in your account's password or a local passcode (if set). These settings can be changed by going to Settings > Manage Privileges.

I'm sorry about all of the inconvenience this has caused. I will assign this to our designer to review for the 4.0 update.
