### ISSUE TITLE
Convert Tool Progress Notification

### ISSUE THREAD

**Issue by mzaremba** [standardnotes/forum#1006]
Hello. Attempting to make the switch from Google Keep to standard notes. Using https://dashboard.standardnotes.org/tools to convert my notes, or at least I've been trying to. Have ~325 notes and every time I choose them the browser appears to freeze (get the wait/kill message). 

If I try and convert a single note, /tools works well. But doing a bunch seems to break. I could see potential users giving up. Would be nice to have some sort of progress notification to prevent users from being discouraged.

**Comment by JaspalSuri** [comment]
Hi, can I have some details regarding the size of your notes and what format the files of the notes are in?

**Comment by mzaremba** [comment]
Sure. There were a total of 342 .html files. All together they came to ~19mb. 

I was eventually able to get the files converted. It took a few hours though.

**Comment by JaspalSuri** [comment]
Thanks so much for that information! It'll help when the team revisits the importer to improve it in the future (since they're currently working on refactoring a lot of things). It's kind of you to think about other users as well.

**Comment by myreli** [comment]
The new built-in converter offers more feedback, hopefully addressing this issue: https://standardnotes.com/help/35/how-can-i-import-my-notes-from-google-keep
