### ISSUE TITLE
Feature Request: Unobtrusive editing - Flickering sync animation is distracting

### ISSUE THREAD

**Issue by mbigras** [standardnotes/forum#1007]
When writing I enjoy getting into the flow of writing, since you've taken the time to create an excellent web based note-taking app I'm sure you feel the same! Thoughts coming and going, ideas edited and brought to life!

The ethos of standard notes is great: a secure place to write in a plain editor that stays our of your way. The editor is overall excellent and clean and I don't want to take anything away from it...except the flickering "All changes saved" wording in the upper right hand corner (the same for the mobile client if possible).

I find this flickering animation very distracting, every time anything is typed, if you pause for even a moment then the flickering animation will happen.

I would love to be able to switch that animation off by default, in the name of clean, distraction-free writing that is private and secure!

<img width="1308" alt="Screen Shot 2020-06-05 at 11 56 05 PM" src="https://user-images.githubusercontent.com/5590632/83938448-25843180-a789-11ea-8391-a6b2d7e9fe6c.png">

I tried forking and searching for the string 'All changes saved' (I had done this in the past and found the string in the: `app/assets/javascripts/controllers/editor.js` file) but it looks like it was actually removed from the status in this commit:

8c898b51beb820cf6d90fd9f2aa4c543adaaadb8

Can we remove that flickering status update by default or add an option to do so?

Edit:

Nevermind! I didn't see the `All changes saved` message when grepping for it because of the minified javascript. I've put together a first cut PR:

https://github.com/standardnotes/web/pull/411

**Comment by baptiste-grob** [comment]
If you're interested in distraction-free writing you could give the _No Distration_ theme a try. After installation you can toggle it on/off using the button in the bottom-right corner of the app 👍

**Comment by mbigras** [comment]
I played a bit with the demo at: https://standardnotes.org/demo

It's true that the _No Distraction_ theme turns off the flickering `All changes saved` message; however it also hides all the other notes and the side panel which I think are very useful, it's just the flickering that I find distracting.

I see the extension is at: https://github.com/sn-extensions/no-distraction-theme I'll take a look and see about implementing my own extension.

**Comment by mbigras** [comment]
One workaround I've found is to update the html style on the `save-status` div and set the display property to none. You can do this by right-clicking on the `All changes saved...` text and choose `Inspect` then edit the save-status div by double clicking on that and typing in: `style="display: none;"`. The result html will look something like this:

```
<div id="save-status" style="display: none;">
```

<img width="554" alt="Screen Shot 2020-06-12 at 9 24 20 AM" src="https://user-images.githubusercontent.com/5590632/84524455-db221980-ac8e-11ea-9408-b18246adcfc0.png">


This works great for me because I don't often close the Standard Notes tab and the web app isn't updating the html as I switch notes.

**Comment by JaspalSuri** [comment]
That's great to hear! I haven't used it yet but the Stylus extension might allow you to save changes that you've made to the page in case you restart your browser, etc.

**Comment by mbigras** [comment]
Looks like this feature was completed—thanks very much! You can disable the saving icon through Settings > General > Tools > toggle _Show note saving status while editing_—see screenshot.
![Screenshot_2022-11-12_22-39-05](https://user-images.githubusercontent.com/5590632/201509375-016ffbcf-691b-4ebf-b5d6-d7949dc84af8.png)

**Comment by cnanney** [comment]
I appreciate the option to turn off the save status entirely, but I think there is a middle ground to be had here. The current indicator is essentially a flashing green dot while you're typing - very distracting:

![rtwert](https://user-images.githubusercontent.com/195134/205368698-8f5d7c97-9256-4a2f-9774-3e3911cb4af8.gif)

The old version that remained a muted color through its state change was mush less abrasive and easier to ignore while still providing the benefit of being able to look up and see your changes have been saved.

I hope further enhancements can be made to have that feature more delicately integrated into the UI.
