### ISSUE TITLE
Markdown Pro Code Block Overflow

### ISSUE THREAD

**Issue by joshcsullivan** [standardnotes/forum#1008]
**Describe the bug**
Any text in a code block that extends past the editor width over flows when in Preview mode.

**To Reproduce**
1. Create a note with the Markdown Pro editor.
2. Create a code block with a sentence.
3. View note in preview mode and see the text over flows.

**Expected behavior**
In the current version (v2.10.1) of the [Easy Markdown Editor](https://github.com/Ionaru/easy-markdown-editor) the code block is placed in a scroll bar block.

**Screenshots**
Markdown Pro in SN:
![image](https://user-images.githubusercontent.com/5774100/84177112-6bbee680-aa50-11ea-93d8-cc92583c3260.png)

Easy Markdown Editor [Preview Page](https://easymde.tk/):
![image](https://user-images.githubusercontent.com/5774100/84177237-93ae4a00-aa50-11ea-886c-109f3d820749.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A
 - Version 3.4.2-beta1

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 13.5.1
 - Version 3.0.21

**Additional context**
I am aware this is a derived editor, but from [this repo](https://github.com/standardnotes/advanced-markdown-editor) it does look like it is built (packaged, however you say it) as an extension by Standard Notes. Therefore, I'm wondering if this extension can be updated to the [newest version](https://github.com/Ionaru/easy-markdown-editor/releases/tag/2.10.1) of EasyMDE.

Cheers,
Josh

**Comment by JaspalSuri** [comment]
I'm afraid that I wasn't able to reproduce this issue. Could you include the code block in your post so I can copy it over to my note? 

That said, since there's an update to EasyMDE, I'll have someone look into it, review the changes, and see what can be implemented into Markdown Pro. Thanks so much for bringing it to our attention!

**Comment by joshcsullivan** [comment]
Here is the text from my code block:

```
Enable-RemoteMailbox -Identity "USERNAME@domain.com" -RemoteRoutingAddress "USERNAME@domain.mail.onmicrosoft.com" -PrimarySMTPAddress "USERNAME@domain.com" -alias "USERNAME"
```

Depending on your screen size, that may not be long enough, so you can just paste it twice into the block.

**Comment by JaspalSuri** [comment]
Thanks so much for sharing that! 

I've look at how the render previews on Windows, macOS, and iOS (since you've listed your phone) and still wasn't able to reproduce it, despite pasting it several times. 

Can you try reinstalling the editor to see if that helps? If not, please let me know so I can report it over.

**Comment by joshcsullivan** [comment]
I tried uninstalling in the desktop app, Brave, and Firefox all on Windows.

Here is a video of the uninstall/re-install process I took and how the issue persists even after re-install: https://www.loom.com/share/46251351fd1e4cf5b505a0b3b3495071

**Comment by JaspalSuri** [comment]
Thank you so much for doing all of that and thank you for the video! Hopefully the team will be able discover the root of the issue. I've reinstalled it on my end but still haven't been able to reproduce it. :(

**Comment by TheodoreChu** [comment]
I was able to reproduce the issue on Windows Firefox: 
![image](https://user-images.githubusercontent.com/22967798/84556972-cae45b80-acdb-11ea-9058-a16b7619ad8d.png)

**Comment by TheodoreChu** [comment]
We need to update the styling for the Markdown Pro editor with this:
```
.editor-preview pre {
    overflow-x: auto;
  }
```
As a temporary workaround, you can add this code snippet directly into your note. 
```
<style>
.editor-preview pre {
    overflow-x: auto;
  }
</style>
```

**Comment by joshcsullivan** [comment]
Thanks @TheodoreChu.

Added that CSS change to the Stylus extension instead of individual notes, and it is working correctly, at least until the editor can be updated.

Cheers,
Josh
