### ISSUE TITLE
[Help Wanted] Sandbox not found

### ISSUE THREAD

**Issue by dbrunker** [standardnotes/forum#1010]
**Describe the issue**
[15247:0610/102901.603707:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_StandaEaSjuy/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

**To Reproduce**
dave@debian-7579:~$ mv ~/Downloads/Standard-Notes-3.4.1.AppImage ~/Standard-Notes-3.4.1.AppImage
dave@debian-7579:~$ cd ~
dave@debian-7579:~$ chmod a+x Standard-Notes-3.4.1.AppImage
dave@debian-7579:~$ ./Standard-Notes-3.4.1.AppImage

**Expected behavior**
Standard Notes starts

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster
 - Browser "Firefox 68.9.0esr (64 bit)", "Chromium Version 80.0.3987.162 (Developer Build) built on Debian 10.3, running on Debian 10.4 (64-bit)", "Web 3.36.2"
 - Version Standard-Notes-3.4.1

**Additional context**
'/tmp/.mount_StandaEaSjuy/chrome-sandbox': No such file or directory
'/tmp/.mount_StandaEaSjuy/': No such file or directory

**Comment by JaspalSuri** [comment]
Hi, since you said that you prefer to not use the app without the sandbox, I've assigned this issue to our desktop and web app dev to look into. Have you tried our [Snap](https://snapcraft.io/standard-notes)?

**Comment by baptiste-grob** [comment]
Hey @dbrunker, it looks like this is a recurring issue on debian machines. You might want to look into this => https://github.com/standardnotes/forum/issues/690#issuecomment-531802728

**Comment by dbrunker** [comment]
Thank you, both.  I'm no fool when it comes to computers but I'm also not as sharp as I used to be.  What does sandbox do and what happens if I don't use it?

**Comment by baptiste-grob** [comment]
This sandbox is a Chromium-specific thing. Chromium is the web engine we use (via Electron) to display the web application in a desktop environment. I'm not knowledgeable enough about it to give you a TL;DR but here's the FAQ on it: https://chromium.googlesource.com/chromium/src/+/master/docs/design/sandbox_faq.md

**Comment by baptiste-grob** [comment]
Generally sandboxing is a security feature, to make sure no program accesses resources it wasn't originally designed to work with. I would recommend considering other options before disabling it, like trying the snap packages for example.

**Comment by baptiste-grob** [comment]
We try not to trust ourselves but your vote of confidence is appreciated nonetheless 😄 Have you tried this solution? https://github.com/standardnotes/forum/issues/690#issuecomment-531802728
