### ISSUE TITLE
[Help Wanted] Way to Disable URL automatic shortening?

### ISSUE THREAD

**Issue by dienluong** [standardnotes/forum#1011]
**Describe the issue**
Hi, I'm using the Web app. When entering an URL, pressing ENTER will automatically shorten the URL to only the site name and domain.

Is there a way to disable this?  With this behavior, all links to the same site look the same.

Thanks.

**To Reproduce**
1. Type an URL
2. Press ENTER

Example:
"https://standardnotes.org/help" would become "standardnotes.org"

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: any
 - Browser: Chrome, Firefox
 - Version: any

**Smartphone (please complete the following information):**
N/A

**Additional context**
Using Plus Editor.

**Comment by JaspalSuri** [comment]
I'm sorry that issue with the Plus Editor exists. I will forward this feedback over to the team!

**Comment by ningsongshen** [comment]
@dienluong thanks for bringing this to our attention! I am able to reproduce this issue and I agree that the full link would be more useful.

The latest release of summernote includes an option to disable this behaviour, and we are currently working on updating that here: https://github.com/standardnotes/plus-editor/pull/29

To fix this I'll explicitly set the option in our implementation, but changes will have to wait until the packages and summernote are updated.

**Comment by dienluong** [comment]
Thank you!
