### ISSUE TITLE
Search function inside a note

### ISSUE THREAD

**Issue by MrMonopol** [standardnotes/forum#1019]
Hi,

I thought, wouldn't it be nice, to have a search function inside notes?
I know, in the web application one can use ``` CRTL + F ```, but in the desktop app, in my opinion, this function is missing. I think it's not intuitive to use the overall searchbar to look for specific content in a note.
e.g. It feels odd to write in Markdown, everything is keyboard based, but to search in the note I am currently editing, I have to use the mouse to activate the searchbar.

Kind regards,

Lukas

**Comment by cyb3rz3us** [comment]
Can you clarify what you mean here?  At present, I am able to search for content that exists within a note so I think you must be looking for a different behavior...

**Comment by JaspalSuri** [comment]
Hi Mr. Monopol, 

In-note search is something we'd like to add in future updates. Currently the Markdown Minimist editor supports this.

**Comment by cyb3rz3us** [comment]
Hi @JaspalSuri 

_"not have to use the global search function to search for content within their note"_ 

So functionally, I guess this is just about limiting the search scope then, correct?  If so, hopefully this could be achieved by keeping the same search window and just adding a drop-down to select the desired scope.

**Comment by JaspalSuri** [comment]
> So functionally, I guess this is just about limiting the search scope then, correct? 

That's correct, however it depends on if the user already has the note open or is using the global search feature and wants to narrow down the results.

I'll keep your feedback in mind!

**Comment by MrMonopol** [comment]
> So functionally, I guess this is just about limiting the search scope then, correct? 

Yeah, correctly! (Sorry, I wasn't in town)
The case I am thinking of is:

```GIVEN``` I am currently editing a note
```WHEN``` I am looking for "*"
```AND``` I cannot find it
```THEN``` I am using the to the current note limited search function.

**Comment by danyusf** [comment]
+1 to this request.

**Comment by solvire** [comment]
Inner note searching is super helpful if the note is really long.  I'm on Linux so IDK If it's the same on others. Searching just gets me to the note itself. 

For instance I have my recipe notes open. I know their is a cake recipe in there but I need to jump to that section of the note instead of scrolling down until I see it. 

Highlighting and a map on the right like an IDE would be cool but just wishful thinking.

**Comment by JaspalSuri** [comment]
Currently it's not possible to search for text within a note, but it's part of our long-term feature roadmap!

**Comment by whongzhuang** [comment]
+1,I am a new user of standard notes,and I really like this,it help me a lot,thanks for your job.

search something in note would be a very usefull function , look forward to come soon

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/1770

**Comment by thetroublemaker** [comment]
In addition this, it would nice, within both the app and web interface to be able to use the global search, say search for "dog", and then when you click on one of the notes in the result set of the search, within the note itself, you get some kind fo marker on the side as to where exactly the term is; a good example is Sublime text, where your search for a term and has small markers on the edge to show you where the word is.

In general, LOVE the SN app, use it every day!
