### ISSUE TITLE
(Feature Request) Reveal Folder Contents Easier

### ISSUE THREAD

**Issue by starryAri** [standardnotes/forum#1024]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**'
Yup

**Is your feature request related to a problem? Please describe.**
Trying to reveal a View or Tag folder's contents is pretty frustrating, especially when you're not able to use a mouse. You can only do it by pressing the tiny circle next to the folder name, as shown [here](https://imgur.com/a/D7RXEQt). To make it easier to use folders, and keep the interface interaction consistent with any other file manager, I think there should be two additions:
1 Double clicking anywhere in the whole row reveals folder contents
2 Pressing spacebar or enter on a highlighted folder reveals its contents

**Comment by JaspalSuri** [comment]
I can see how this can be helpful and passed it along to the team for review!
