### ISSUE TITLE
(Feature Request) Renaming of Folders for Views and Tags

### ISSUE THREAD

**Issue by starryAri** [standardnotes/forum#1025]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yup

**Is your feature request related to a problem? Please describe.**
I use smart tags and folders often to help organize my notes. As you may expect, smart tags are pretty long and annoying to re-do. I often find myself having to delete several nested folders just to change the smart tag of a parent folder- a long and cumbersome process of copy and pasting. This makes using folders and smart tags hardly usable past 1 level of nestedness for long-term note-taking. 
![image](https://user-images.githubusercontent.com/62635784/86071792-fe8de800-ba34-11ea-8782-232da82dae70.png)
The ability to rename a View/Tag's Folder would solve this.

**Comment by JaspalSuri** [comment]
Thanks for the feedback; I'll pass this along to the team as well!

**Comment by mobitar** [comment]
You can definitely rename folders/tags by first clicking it to select it, then clicking it again. But you can't yet rename Smart Tags.
