### ISSUE TITLE
S3 support for FileSafe

### ISSUE THREAD

**Issue by nuke807** [standardnotes/forum#1026]
My preferred cloud storage provider is Backblaze B2, and they recently implemented S3 (credentials?) into their buckets. I have fooled around with trying to link my File Safe to Backblaze through the AWS S3 connection, but have not been successful in getting that accomplished.

Is anybody aware of how to make that work? Or am I only able to use AWS for that particular solution?

With Backblaze I have the same type of keys that AWS has (Account ID & Application Key) plus the S3 domain: 

![image](https://user-images.githubusercontent.com/51008268/86181022-7bc76480-baea-11ea-9501-0d873826c0cd.png)

Any help would be appreciated.

Thanks,

**Comment by mobitar** [comment]
I haven't heard of anyone yet pulling this off with FileSafe. But I can't be sure as to how many attempts there were. What was the result when you gave it a try?

**Comment by nuke807** [comment]
The end result was an error code, saying "ERROR UPLOADING FILE"
Here are the screenshots of the process I followed, I couldn't get a screenshot of the final error in time:

![#1](https://user-images.githubusercontent.com/51008268/86290807-48004380-bbab-11ea-944f-64e4975fc387.PNG)
![#2](https://user-images.githubusercontent.com/51008268/86290812-4b93ca80-bbab-11ea-9e6f-4d86ef860f6d.PNG)
![#3](https://user-images.githubusercontent.com/51008268/86290819-4df62480-bbab-11ea-9740-edc6268a3f3d.PNG)

So the system allows me to link B2, but there is just something about the connection that isn't working.

**Comment by mobitar** [comment]
Hmm yeah in that case it's probably not going to work out. The relay server uses the AWS S3 API directly, so the two are likely not compatible.

**Comment by nuke807** [comment]
Thanks for the insight mobitar, I was just hoping that I could get them linked.

**Comment by myreli** [comment]
Since [FileSafe is deprecated](https://standardnotes.com/blog/deprecation-notice-filesafe) and this issue is unlikely to receive more interaction I'm closing it. [Files are now a native](https://standardnotes.com/blog/introducing-encrypted-file-storage-with-automated-backups) feature through encrypted storage. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
