### ISSUE TITLE
Extension panel is empty

### ISSUE THREAD

**Issue by austil** [standardnotes/forum#1030]
Hi, I think I found a bug: 

![image](https://user-images.githubusercontent.com/3978482/86888509-91481a00-c0fa-11ea-8a4d-37c40a55ece8.png)

**To Reproduce**

1. Click on the extension tabs on the left bottom side on the screen

**Desktop:**
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Firefox 78.0.1 AND Google Chrome 83.0.4103.116

**Additional context**

The following message pops up in the dev console **on both browser**  : 

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://app.standardnotes.org')
does not match the recipient window's origin ('https://sn-extensions.standardnotes.org').
```

Looks like some "fun" cross origin issue.

**Comment by JaspalSuri** [comment]
Thanks so much for taking the time to make a report! It should be fixed (as of ~40 minutes ago)!

Please let us know if you're running into any other issues! We're aware of the issue with the CloudLink extension.

**Comment by austil** [comment]
Hey, fix confirmed (but I had to hard refresh the app with CTRL+F5 to get it).

**Comment by JaspalSuri** [comment]
Thanks for that info; it'll be useful in future cases. I'm glad that it's working now!
