### ISSUE TITLE
Facing sync errors on Desktop App

### ISSUE THREAD

**Issue by jiggneshhgohel** [standardnotes/forum#1031]
On the Desktop application I am experiencing the following error

> There was an error syncing. Please try again. If all else fails, try signing out and signing back in.

I tried signing out and signing back in but it didn't helped. I originally faced this issue with `standard-notes-3.0.8-x86_64.AppImage` today when I accessed my Desktop app after a few days gap. So I thought may be updating the app could help so I downloaded the latest version **3.4.1** but unfortunately the error persists.

**Steps to Reproduce**

1. Open the desktop app.

2. Switch to a different app and then come back again to the desktop app or stay on the desktop app itself and notice that **Account** menu color at some interval changes to red and then automatically changes to blue. While it was red I tried to take a screenshot but in the meantime it switched to blue so I lost the error. But luckily made to capture the screenshots as shown below.

**Screenshots**

![Screenshot from 2020-07-09 20-29-28](https://user-images.githubusercontent.com/10440841/87056342-1c243400-c223-11ea-87ea-ef4f19ae04b4.png)
![Screenshot from 2020-07-09 20-29-43](https://user-images.githubusercontent.com/10440841/87056344-1cbcca80-c223-11ea-9e7c-f5537063d184.png)

**Desktop:**
 - OS: Ubuntu 18.04.4 LTS

Thanks.

**Comment by wazlecracker** [comment]
I am also encountering the exact same issue on Manjaro on the 5.7.0-3 kernel.

**Comment by JimmyUX** [comment]
I am having the same issue on Windows 10 x64 1909 18363.900

**Comment by mobitar** [comment]
We're actively working on this and posting live updates in our [Slack group](https://standardnotes.org/slack).

**Comment by JaspalSuri** [comment]
This should be resolved; please let us know if any of you are still running into any issues!

**Comment by myreli** [comment]
[Resolved.](https://github.com/standardnotes/forum/issues/1031#issuecomment-656450071)

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
