### ISSUE TITLE
"Your session has expired"

### ISSUE THREAD

**Issue by karan** [standardnotes/forum#1033]
**Describe the bug**
I open SN in Brave browser (web app) latest every day. For the last few days, I see "Your session has expired. New changes will not be pulled in. Please sign out and sign back in to refresh your session." every time. The solution is to sign out, and sign back in (and clear all local data).

**To Reproduce**

I don't know how you can reproduce this. Just open SN in Brave I guess?

**Expected behavior**
I don't need to sign out every day.

**Screenshots**

In the console:

![image](https://user-images.githubusercontent.com/3261985/87212903-f1df7e80-c2d5-11ea-81ac-45d39be4bc21.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.15.5
 - Browser: Brave
 - Version: 1.10.97

**Comment by JaspalSuri** [comment]
I can't reproduce this in Brave (at the moment). What browser extensions are you using? Also, can you email help@standardnotes.org so that someone from the team can look to see if there are any particular technical issues with your account? Thanks so much in advance!

**Comment by karan** [comment]
Extensions: Bitwarden, Instapaper, uBlock

Sent the email

**Comment by mobitar** [comment]
This is most likely to do with our recent infrastructure upgrades that caused turbulence for a short period of time. Please let me know if you continue to see this issue.

**Comment by karan** [comment]
I'll report back if I see the issue reoccur.

**Comment by nedsir** [comment]
I started having this exact same error message spamming me every few seconds on the Desktop app on Windows today, for no apparent reason. Any idea what could be happening?

**Comment by mobitar** [comment]
Sorry, just posted this to Slack:

> Hey all, we had a major server release this morning that went successfully, but didn’t account for one minor detail. Because of that, some users may see an “invalid session” alert. We’re applying a fix to this now, so if you hang tight for a couple minutes, this alert should go away on its own, and you do not need to sign out and back in.

> (If you did end up signing out and back in as a result of that alert, please note that in a few minutes, you will see the invalid session alert again. At this point, please hang on for up to an hour until we resolve that issue.)

**Comment by nedsir** [comment]
"Thanks for the answer, I just figured this was a server issue when even the website gives a `403 Forbidden` . Good luck!

**Comment by stephencross** [comment]
This error has not gone away for me yet.  I'm using an AppImage un Ubuntu.

**Comment by mobitar** [comment]
Sorry, I had updated the status in Slack but forgot to update this thread. If you ended up signing out the first time, the permanent fix on our end will require you to sign out again once more. This should fix it for good. Really sorry for the inconvenience here. Not something we're expecting to happen again.
