### ISSUE TITLE
markup shows when changing from BOLD to other editors

### ISSUE THREAD

**Issue by mwcarlsn** [standardnotes/forum#1039]
I want to change from "BOLD" editor to the "TASK" editor.   However, when I do that all the html markup from the bold editor stay in the note.   the markup is also there if I change to the "PLAIN" editor.  Is there a way to change editors without having all the markup show up?

This is on Win10 running Standard Notes v3.4.1

Thank-U

**Comment by ningsongshen** [comment]
Hey @mwcarlsn! The Bold Editor does convert your note to HTML to save the formatting. A possible workaround could be to copy the text from the Bold Editor's editor view and paste it into the Plain Editor. This way, there would be no formatting.

The team will definitely look into it but I can't guarantee that there will be a fix, as we derive the Bold Editor from a third-party.

**Comment by mwcarlsn** [comment]
Thank-you @ningsongshen - that makes sense.  Unfortunately it makes it a little hard to change editors on different devices or needs, but that should be an infrequent use case.  TY and have a great day
