### ISSUE TITLE
Attach files to notes via API

### ISSUE THREAD

**Issue by yozamacs** [standardnotes/forum#1043]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

**Is your feature request related to a problem? Please describe.**
I can't tell from the docs if there's a way to attach files to notes via the API or some other way. I know from the instructions that you have to drag the file into the bold editor. It seems that there would be some other way.

**Describe the solution you'd like**
I would like to be able to add files to notes via an API or command line.

**Describe alternatives you've considered**

**Additional context**

**Comment by mobitar** [comment]
The files architecture is kind of long-winded right now and has plans of being redesigned to be far simpler and more native. There would be no easy way to go about attaching via an API right now.

**Comment by yozamacs** [comment]
Okay, do you have an idea of a timeline for when it becomes simpler? So right now, there's no other way to attach files, other than click/drag?

**Comment by mobitar** [comment]
It will be part of our v4 focus, so it's not a "hold your breath" type situation. But as of now yes the easiest/only way to attach files is through the app UI.

**Comment by yozamacs** [comment]
okay, thanks!
