### ISSUE TITLE
Folders extension not working anymore

### ISSUE THREAD

**Issue by tontontony** [standardnotes/forum#1045]
**Describe the bug**
I probably have several issues combined, I let you judge and will describe the whole situation:
I couldn't launch standard notes on window 10 anymore (launched it 3 days ago just fine). I downloaded it again and it launched, but they were tags conflict (just 1 duplicate but still, it is pretty scary) and the "folders" extension wasn't working, disabling access to any tag on the sidebar.
I uninstalled every extension and reinstalled them. Folders is still not working, you can see the screenshot below for more details.

**To Reproduce**
1. Go to the extension menu over the window 10 app
2. Try to install the extension "folders" by clicking on the "install" button
3. See the warning message and try to activate the extension anyway
4. The button display successively "activate" and "deactivate" and the side menu with the tags shows and hide 
5. Press the button "uninstall" see an error pop up and the request window to activate the extension

**Screenshots**
![1](https://user-images.githubusercontent.com/10525855/88400688-fb361400-cdc8-11ea-90d6-2650f83492f5.jpg)
![2](https://user-images.githubusercontent.com/10525855/88400692-fbceaa80-cdc8-11ea-9fcd-b68994c6af23.jpg)
![3](https://user-images.githubusercontent.com/10525855/88400695-fcffd780-cdc8-11ea-9376-6c605f2bbc59.jpg)
![Settings](https://user-images.githubusercontent.com/10525855/88400697-fcffd780-cdc8-11ea-8e6a-f1b0c8bd62ea.jpg)

**Comment by YoshK** [comment]
IT IS FIXED
I already fixed the duplicate and tried restarting the app.
I decide to give it one last try and it seems to work just fine now... No idea what happened.

**Comment by JaspalSuri** [comment]
Thanks for the detailed report and for letting us know that the issue has been fixed! I'll close this thread, but feel free to reopen it or ask additional questions. :)
