### ISSUE TITLE
Quick tag combined with folders overflow

### ISSUE THREAD

**Issue by tontontony** [standardnotes/forum#1046]
While entering a tag with the "quick tag" extension and the "folders" extension enabled, all the hierarchy of tags is automatically added not just the one entered.
This does fill the tag line quickly (even more frustrating with the current bug only displaying the first line and half of tags) and may not even fit with people organization.
Could we have the option to disable this automation somewhere?

**Comment by JaspalSuri** [comment]
Hi, we're aware of [this](https://github.com/sn-extensions/autocomplete-tags/issues/10), but I've brought it up with the team again. Thanks for the feedback!

**Comment by myreli** [comment]
Since tags are [now native](https://standardnotes.com/blog/folders-from-extension-to-native) and this issue is unlikely to receive more interaction I'm closing it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
