### ISSUE TITLE
having a #notag tag

### ISSUE THREAD

**Issue by YoshK** [standardnotes/forum#1048]
It would be great to have a dedicated tag that displays notes that haven't been tagged.

I rely a lot on tags to find my notes and came to an issue some time. When I add a note quickly and don't have the time to tag it properly, it might get buried before I have a chance to do so and I end up losing it.

**Comment by mobitar** [comment]
You can do this :) https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters

**Comment by YoshK** [comment]
Amazing <3
