### ISSUE TITLE
Not able to delete notes

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#105]
Hi,

I can't find the delete option. How can I delete a note?

Three or four days ago I had this app, and to delete a note I would hold down a note for a sec and it would appear the delete option. I've reinstalled it yesterday and I can't find the option, so how can I do that?

**Comment by mobitar** [comment]
Hi, I'm assuming you're talking about the mobile app? You can delete a note by pressing on the note, then pressing the button in the top right corner.

**Comment by Spetzatin31** [comment]
Ow, 
Now I've tried both on the mobile app and my computer, and it works.
Thank you!
