### ISSUE TITLE
[Help Wanted] Markdown Basic Editor: Supported Code Block Languages

### ISSUE THREAD

**Issue by StuartMorrisAU** [standardnotes/forum#1053]
Hi there,

What language strings are supported in the Markdown Basic editor fenced code blocks?

e.g.

<pre>
```some-language
If x = true Then
  y = 1
End If
```
</pre>

Thanks!

**Comment by JaspalSuri** [comment]
Hi Stuart, I've assigned this issue to members of the team who would know more about this. Once we get an answer, I'll ping our technical writer to update some the relevant parts of our documentation.

**Comment by mobitar** [comment]
The editor uses highlight.js. The list of languages can be found here: https://highlightjs.org/static/demo/

**Comment by StuartMorrisAU** [comment]
Awesome, thanks @mobitar.
