### ISSUE TITLE
Website rendering broken

### ISSUE THREAD

**Issue by alexandermerritt** [standardnotes/forum#1054]
**Describe the bug**

Website rendering is broken with www prefix and other places.

**To Reproduce**

Go to www.standardnotes.org see that page does not render well.

Seen also on:
https://www.standardnotes.org/privacy
https://www.standardnotes.org/extensions

Go to https://standardnotes.org (remove www) and see the page render appropriately (sometimes).

**Expected behavior**

Page renders not as just plain text, with icons, etc.

**Screenshots**

<img width="857" alt="Screen Shot 2020-07-28 at 10 08 09 AM" src="https://user-images.githubusercontent.com/3632069/88698171-8f022b80-d0ba-11ea-97dd-413f96b1c0d0.png">

**Desktop (please complete the following information):**

Tried with

macOS 10.15.5 Safari, Firefox
With and without VPN service, USA and non-USA end-points, no improvement.

**Smartphone (please complete the following information):**

not used

**Additional context**

**Comment by mobitar** [comment]
On it thanks!

**Comment by mobitar** [comment]
Should be fixed now 👍
