### ISSUE TITLE
Folders: Parent tag not applied automatically when creating a new note (bug)

### ISSUE THREAD

**Issue by kslstn** [standardnotes/forum#1055]
When I create a new note in 'All notes', then apply a tag (e.g. 'Banana') nested inside a folder (e.g. 'Fruit'), the parent tag ('Fruit') is applied to the note. To me that is desirable behavior.

When a note with a nested tag ('Banana') is open and I create a new note, the nested tag is applied automatically, but the parent tag ('Fruit') is not. This behavior is inconsistent—I expect the parent's tag (in fact: all ancestor's tags) to be applied too.

**Comment by JaspalSuri** [comment]
This is also interesting in the case that a user might want to see all notes with the tags contained in a folder. 

Thanks for the feedback; I'll pass it along to the team for review!

**Comment by joshcsullivan** [comment]
+1 for inheriting all ancestor tags wherever you are in the tag structure.

**Comment by mobitar** [comment]
The Folders component has some inherent limitations, including this one. This is why in v4, we will be moving towards a more native approach to folders (or "nested tags"), so that folders are not just a superficial layer on top of tags.

**Comment by myreli** [comment]
Since tags/ folders are [now native](https://standardnotes.com/blog/folders-from-extension-to-native) and this issue is unlikely to receive more interaction I'm closing it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
