### ISSUE TITLE
[Help Wanted] What happens when you press the circle beside a tag with the Folders extension enabled?

### ISSUE THREAD

**Issue by kslstn** [standardnotes/forum#1056]
I installed the Folders extension. Now each tag has a colored circle. When I click it, the fill of the circle is made transparent. It doesn't seem to do anything else. What's the purpose of that? This doesn't happen on the demo page, that has the default theme and a square instead of a circle for each tag.

<img width="100" alt="Screenshot 2020-07-29 at 12 28 14" src="https://user-images.githubusercontent.com/5889799/88789488-13c27780-d197-11ea-9cb5-0580bc183eef.png">

**Comment by IceFire23** [comment]
From my experience what it does is expand/collapse any nested subfolders. I don't think it affects the view of the notes list, I think it just changes the notes shown in the tag list.

**Comment by JaspalSuri** [comment]
> From my experience what it does is expand/collapse any nested subfolders.

IceFire23 is correct. The visual change is still made even if there aren't any subtags/subfolders underneath the "collapsed" tag. 

> I don't think it affects the view of the notes list, I think it just changes the notes shown in the tag list.

That's correct as well, it should only affect the tag pane and what notes are accessible via the tag pane.

> This doesn't happen on the demo page, that has the default theme and a square instead of a circle for each tag.

The demo might not have the extension at the moment (the team is working on fixing things like this).

**Comment by myreli** [comment]
Since tags/ folders are [now native](https://standardnotes.com/blog/folders-from-extension-to-native) and this issue is unlikely to receive more interaction I'm closing it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
