### ISSUE TITLE
Unable to save note changes (Mac & iPhone)

### ISSUE THREAD

**Issue by pinneau** [standardnotes/forum#106]
~6:00am EDT
Neither my Mac Standard Notes(v 2.0.1) nor iPhone app (via wifi or Verizon cell connections) will save note changes.
Both give: "Oops -- There was an error saving your data to the server. ..."
& say I am "offline".
Is YOUR server having trouble this morning?

**Comment by mobitar** [comment]
Hey, looking into this now. In the mean time, please upgrade to the new app available here: https://standardnotes.org/download/ios. Others have reported this works for them.

**Comment by pinneau** [comment]
Thanks for reminder on iOS upgrade.
That has NOT (so far) helped my iPhone to save changes to server 
(or, of course, helped my the MacOS version save changes to server)

**Comment by mobitar** [comment]
This is really strange. Can you hop on Slack so we can figure out what's going on in real time? https://standardnotes.org/slack.

**Comment by mobitar** [comment]
I just pushed out a server update that *may* fix this issue. Can you try saving again and see if it works?

**Comment by pinneau** [comment]
Well, I'm just checking back here because everything is SAVING properly now.
So hopefully your server update was the needed magic.
Who can say why *I* was (perhaps) the only one affected...
But i *REALLY* appreciate your persistent attention to just ONE user's issue!
Awesome!

**Comment by mobitar** [comment]
Great! Glad it's working now :)
