### ISSUE TITLE
[Help Wanted] Markdown Math

### ISSUE THREAD

**Issue by StuartMorrisAU** [standardnotes/forum#1061]
I'm attempting to migrate some math I have in OneNote to SN using the Markdown Math editor. I've never used LaTeX before, although it looks straightforward enough once you get used to the conventions. What does the Markdown Math editor support? The [repo](https://github.com/sn-extensions/math-editor) says it's based upon Upmath, but there's [some](https://github.com/sn-extensions/math-editor/issues/10) [issues](https://github.com/standardnotes/forum/issues/957) that seem to indicate this is no longer the case?

There's nothing available on the [SN help](https://standardnotes.org/help) and the [extension page](https://standardnotes.org/extensions/markdown-math) only mentions it's derived from Upmath. Does that mean it has identical features (sans remote server calls), or only a subset?

Specifically, I tried the plot on the [Upmath](https://upmath.me/) homepage, but it fails to render. I have some basic charts in OneNote I'm hoping I can bring across.

```
$$\usetikzlibrary
\begin{tikzpicture}[scale=1.0544]\small
\begin{axis}[axis line style=green,
	samples=120,
	width=9.0cm,height=6.4cm,
	xmin=-1.5, xmax=1.5,
	ymin=0, ymax=1.8,
	restrict y to domain=-0.2:2,
	ytick={1},
	xtick={-1,1},
	axis equal,
	axis x line=center,
	axis y line=center,
	xlabel=$x$,ylabel=$y$]
\addplot[red,domain=-2:1,semithick]{exp(x)};
\addplot[black]{x+1};
\addplot[] coordinates {(1,1.5)} node{$y=x+1$};
\addplot[red] coordinates {(-1,0.6)} node{$y=e^x$};
\path (axis cs:0,0) node [anchor=north west,yshift=-0.07cm] {0};
\end{axis}
\end{tikzpicture}$$
```

It'd be useful for the extension to mimic the Markdown Basic display: Edit (no preview), Split (edit and preview), or Preview (no edit). Especially on mobile, having only a split editor takes up valuable real estate.

Thanks.

**Comment by JaspalSuri** [comment]
Hi Stuart,

According to @mobitar (in the issue that you've linked):
> So we use a variant of Upmath that relies on local rendering using KaTeX. So the results wont be exactly identical to Upmath. 

If what you've written doesn't work in Upmath, then it's possible that it's less likely to work in the Markdown Math Editor since the rendering is done locally. I'll assign @TheodoreChu to this to see if he can help shed some insight.  

> It'd be useful for the extension to mimic the Markdown Basic display: Edit (no preview), Split (edit and preview), or Preview (no edit). Especially on mobile, having only a split editor takes up valuable real estate.

I'll pass this along; thanks for the feedback!

**Comment by TheodoreChu** [comment]
I think Jaspal is right to say that if a code snippet does not render on Upmath.me or on the [KaTeX demo](https://katex.org/#demo), then it it is unlikely to work in the Markdown Math editor. There is likely an error in your code. I'm not familiar with TikZ, so I don't know where the error is. 😅 

The examples from the [Overleaf TikZ tutorial](https://www.overleaf.com/learn/latex/TikZ_package) work on Upmath.me, but they don't work on the KaTeX demo. It is possible that KaTeX does not yet support TikZ. The Markdown Math editor renders with the math locally with KaTeX, so if a code snippet doesn't work in the demo, it probably won't work in Markdown Math

**Comment by StuartMorrisAU** [comment]
@TheodoreChu I copied the working example from the Upmath.me homepage to a SN note. To confirm so I understand the dependency chain, Markdown Math renders locally with KaTeX, but the editor itself is built on Upmath?

**Comment by TheodoreChu** [comment]
That sounds right. The editor was first built from Upmath with server-side LaTeX rendering. Then the rendering was switched to KaTeX as discussed in https://github.com/sn-extensions/math-editor/issues/10
