### ISSUE TITLE
Some notes do not show up on Android client

### ISSUE THREAD

**Issue by jmahone** [standardnotes/forum#1068]
I can see all of my notes on the macOS client, but some do not appear on the Android client side. Has anyone seen this?

**Comment by JaspalSuri** [comment]
What version of macOS and Android are you using? Does it affect all notes, regardless of what editor they are using? Have you tried making a backup (on both devices), signing out of your devices, and then signing back in?

**Comment by jmahone** [comment]
Good questions; usually I'm more thorough when reporting an issue, so here goes:

macOS: 10.12.6 Sierra ( And I'm using the desktop app)
Android: 10

The notes I see that are missing are using:
 - code editor
 - plus editor

I typically use the plus editor for most notes.

Everything looks fine in the desktop app on my mac.
It's just the client on Android that is giving me issues.

I wasn't sure about backing up the devices. Not sure I've done that before. I think I have autobackup turned on? And what does it mean to sign out of the device and sign back in?

**Comment by JaspalSuri** [comment]
No worries, thanks for the info! I apologize for the confusion. To keep things simple, I would suggest the following for now:

Open the Android app, tap on the hamburger menu (the one with three bars) located at the top, tap on the floating gear icon at the bottom, in the `Export Data` section, tap `Encrypted` and save the backup somewhere. Feel free to save the Decrypted backup somewhere that you think it will be safe as well, if you'd like to. Once the backups have been stored, revisit the settings page of the app and tap `Sign out (yourEmail@emailProvider.com)`. Then sign back in with your email and password and see if the missing notes reappear. 

To manually back up notes from the macOS app, you can click on `Backups` in the menu bar to access recently saved backups or click on the `Account` button and select a type of backup to export.

**Comment by jmahone** [comment]
Thank you! Logging out and back in worked. I was concerned that since the notes were out of sync, the blank notes would somehow become the new content if I messed with anything without the consult.

It all looks good, thanks!

**Comment by jmahone** [comment]
Thanks for the help. Logging out of the Android client did the trick.

**Comment by JaspalSuri** [comment]
You're welcome! I'm glad that everything worked out as expected! Thanks for taking the time to try that out and get back to me!
