### ISSUE TITLE
Windows desktop app no longer persistent?

### ISSUE THREAD

**Issue by JPL1** [standardnotes/forum#107]
With 2.0.1 I've noticed the app doesn't appear to install anywhere (Win 10).

Previously I could just run 'standardnotes' from the Windows search box. Now, each time I have to use the Standard-notes-setup-2.0.1.exe file which installs Standardnotes and boots me straight into my account. On restarting my machine I have to do this again (start using the setup exe). Apparently the installation is not persistent. 

Is this a feature or a bug?

**Comment by mobitar** [comment]
A few users who have reported a similar issue say that completely deleting any traces of the app, then re-installing it, fixes this issue for them.

I tried reproducing it myself but could not :/

**Comment by JPL1** [comment]
OK - I ran Control Panel | Add or remove programs and uninstalled. Seems to be working now - at least there's an exe in C:\program files. I'll report back if it happens again. Thanks

**Comment by technotherion** [comment]
I am aware that this is an extremely old issue but I am experiencing this as well.

Every time I wanted to open Standard Notes, I needed to run the installer. 

I uninstalled Standard Notes and reinstalled it and now it works.

It's very strange but would be willing to give more information if this is not an isolated problem.

Windows 10 x64

**Comment by mobitar** [comment]
Hmm..so after the reinstall the issue does not appear anymore? These kinds of transient issues are hard to debug. But if it does reappear after some time, let me know. Could have something to do with autoupdates.
