### ISSUE TITLE
Notes are not showing in Linux desktop app

### ISSUE THREAD

**Issue by aysunrhn** [standardnotes/forum#1070]
Hi,

The contents of my notes are no longer showing in the Linux app when I open it. 

![image](https://user-images.githubusercontent.com/25639243/90249279-71fb8580-de3a-11ea-9873-c8233c87df41.png)

I am using Ubuntu 18.04 and the AppImage version 3.4.2 but I had the same problem with version 3.4.1 as well.

**Comment by mobitar** [comment]
It looks like none of your extensions are working, including editors. Can you try restarting the app? As a workaround for accessing your notes while we figure out why your extensions aren't working, switch your notes to use the Plain Editor, and disable the Folders extension (so you can access your tags).

**Comment by aysunrhn** [comment]
> It looks like none of your extensions are working, including editors. Can you try restarting the app? As a workaround for accessing your notes while we figure out why your extensions aren't working, switch your notes to use the Plain Editor, and disable the Folders extension (so you can access your tags).

I had tried restarting several times, as well as reverting to an older version. I was able to access all extensions as usual on the web app.

Now that I tried using the desktop again it seems to be working? I remember I had errors when backing up to google drive as well so maybe once in a while, there are some issues with extensions in general.
