### ISSUE TITLE
Specify centered max-width typing area (also, Linux panel icon)

### ISSUE THREAD

**Issue by X1SDNA** [standardnotes/forum#1075]
Hi

Just discovered Standard Notes. After searching for an alternative to OneNote and trying many things, I think this could be the one. Looks awesome so far.

So, I have the free account ATM, but will not hesitate to upgrade once I've checked that it fundamentally has what I need.

Two quick and simple questions:

1. Very important: In the Plus Editor, in No Distractions mode, full screen, I need to be able to set a centered work area (or margins), so that I'm not writing a document at 100% width on a big wide screen. I just need to be able to set margins (or better yet, specify the max width of the typing area and have it centered) so that the typing area is centered and constrained by a max width. The Help section on the website doesn't have a search function, and I couldn't locate a mention of margins or max-width. Can someone please run me through how to set up notes with a max-width constrained typing/work area?

Setting a specific max-content width which is centered is preferable to margins, as I don't want the centered content area to change according to screen size, unless the screen size is less than my specified content area, in which case it would be 100%. So basically, how can I make the content area work like a responsive website via max-width?

2. On Linux Mint, can someone possibly tell me how to get the Standard Notes icon in the panel/taskbar? I currently need to go to the Home folder and click on the generic program cogwheel.

Thank you.

**Comment by JaspalSuri** [comment]
Hi, thanks for checking out Standard Notes and thank you for the kind words!

For #1, I've passed that along as a feature request for review! :) 

For #2, when the program is running, you should be able to right-click its icon on the taskbar and select an option to pin or favorite it. Which desktop environment are you running in Linux Mint?

**Comment by JaspalSuri** [comment]
>Thanks Jaspal, and apologies for not providing the Linux install method. I used the AppImage.

You're welcome! No need to apologize. I apologize for asking you to install another program, but I would suggest installing [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) and then reinstalling the [AppImage](https://standardnotes.org/extensions?downloaded=linux) with it. 

>In the Extended version, can I set a global font, or, better yet, set a specific system font for a specific note/page, or editor in which I'm working?

Currently this isn't possible, but we have taken note of similar requests. 

>When I search, the search results display the note in which the result is found, but doesn't allow me to go directly to the result. If the note is quite long, it can be a needle in a haystack...Just wondering if I am using the search function incorrectly, or whether this is something that may be refined in a future release?

You're correct that it would be something we'd have to try to refine in future releases. 

Thanks for your questions! I'm sorry that we currently don't have those features at the moment (and there isn't an ETA for them, as we don't want to overpromise anything).

**Comment by X1SDNA** [comment]
Thank you. I'll try the Linux method you mentioned.

Regarding the font - on the demo with one of the rich text editors, I discovered it actually lets me select from a list of fonts, which I can choose for that note.

Last question: For Extended, all the available editors work with all the available themes? It had some difficulty on the live demo, but perhaps because everyone does everything with it....

**Comment by myreli** [comment]
Since this issue was opened the UI changed quite a bit, including an update that centres the focus mode: 

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/17554234/219045412-ffb23af8-0d1e-4d0e-b766-8c323e9d4bc0.png">

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
