### ISSUE TITLE
Cannot change note title in spreadsheet editor

### ISSUE THREAD

**Issue by J-McNamara** [standardnotes/forum#1078]
**Describe the bug**
If editing a spreadsheet that contains an arithmetic formula, I go to change the note title and the cursor jumps to overwrite a cell.

**To Reproduce**
1. Open a note in the secure spreadsheets editor using the midnight theme in the Mac app
2. Enter two numbers in two different cells and have a third cell calculate their sum (=sum(cell1,cell2).
3. Highlight the note title and begin typing a new title
4. After typing the first character, the cursor will jump to a cell in the spreadsheet and enter subsequent keystrokes there
5. If the title characters are typed very quickly (>15 / sec), the cursor does not move and behaves normally.

**Expected behavior**
The cursor should not move from the note title to the cells when typing

**System**
- OS: macOS Catalina
 - Standard Notes 3.4.2

**Comment by JaspalSuri** [comment]
I can reproduce this; thanks so much for letting us know and for providing a detailed report!

**Comment by effieeee** [comment]
No longer occurs
