### ISSUE TITLE
Listed 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by nablagodel** [standardnotes/forum#1079]
![image](https://user-images.githubusercontent.com/523055/91184874-d00b5100-e6f5-11ea-9228-3b9d1c211ec3.png)

![image](https://user-images.githubusercontent.com/523055/91184947-e5807b00-e6f5-11ea-9415-763592962b5e.png)

**Comment by nablagodel** [comment]
![image](https://user-images.githubusercontent.com/523055/91185269-4445f480-e6f6-11ea-9ee9-f8d62494ade3.png)

**Comment by mobitar** [comment]
We’re upgrading Listed’s infrastructure to make custom domains easier to set up. There will be some downtime (starting now), and we’re hoping it won’t be for too long.
