### ISSUE TITLE
Need to re-start program in order edit name of tags & notes

### ISSUE THREAD

**Issue by X1SDNA** [standardnotes/forum#1080]
Hi - I just purchased extended. On Windows 10, it seems to have trouble with allowing me to re-name notes and tags. I need to close the program and re-open it and then it allows me to edit/re-name them again.

Also, how do I specify the order of a tag? It seems that dragging the tag up or down in the list only nests it in another tag, rather than changing the order and keeping them on the same level, only a different order. Could this be related to my tag/note title editing issues?

**To Reproduce**
It seems random - I can't provide a sequence of steps. Just stops working during editing. Can no longer type anything, basically. Once, when it was having issues, I was able to delete a note name, by I couldn't type anything to replace it. Re-started, and it was fine again. Upon further editing, the function seizes up again, and I repeat the process in order to re-name/edit tags or note titles.

**Expected behavior**
The ability to edit note names and tags.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 Windows 10, desktop, latest version.

**Additional context**
I will update this ticket if I notice a pattern. Perhaps it is after a specific other change has occurred (likely) - I just can't be sure what that is. All I know ATM is that sometimes it works, sometimes it doesn't; and when it doesn't, re-starting the program will get it going again.

**Comment by X1SDNA** [comment]
UPDATE: I can confirm that this happens after a note is moved via changing the tag.

Example:

A note is tagged like so:
Tag1

I notice it is wrong place, so I change the tag to:
TagA.Tag1

This moves it to the desired 'subfolder'. However, now neither the name of the note or the tag can be edited without re-starting the program.

Hope this helps.

**Comment by X1SDNA** [comment]
UPDATE 2: I think I need to allow it to refresh, or manually press refresh in order for such changes to sync before re-naming anything. Let me see how that goes and I'll close this thread if that's all it is (unless you can just confirm that yes, that is the case). Thanks.

**Comment by X1SDNA** [comment]
Yes it seems to be a refresh issue. I'll keep that in mind and close this thread. Thanks.

**Comment by JaspalSuri** [comment]
>Hi - I just purchased extended.

Thanks again for supporting us with Extended. I'm so sorry that you ran into issues with basic features right off the bat, but am glad to hear that they were resolved. Regardless of that, this shouldn't have happened and I will pass it along to the dev team for review. This particular issue might be difficult to reproduce, so hopefully it'll be fixed once the dev team has completed rewriting all of the apps. Your support is greatly appreciated!

> Also, how do I specify the order of a tag? It seems that dragging the tag up or down in the list only nests it in another tag, rather than changing the order and keeping them on the same level, only a different order. Could this be related to my tag/note title editing issues?

Currently the order of the tags can't be set manually, but I will add this to our current list of requests for this ability.

**Comment by X1SDNA** [comment]
Thanks Jaspal.

Just an addendum to this - it's actually not a simple case of hitting 'refresh'. There seems to be a background process that takes sometime after the renaming of tag, before I can again edit anything related to it (tag, title, content). Not a dealbreaker, just some feedback. It's not like I'll be changing tag names every 5 minutes of every day.

**Comment by JaspalSuri** [comment]
Are you still able to reproduce this issue? If so, can you try signing out of the desktop app, signing into the [web app](app.standardnotes.org), and then signing back into the desktop app? You can sign out of the web app afterwards. 

If the issue persists, please click on the hamburger menu at the top right and then click on `View` > `Toggle Developer Tools` and for any lines that are highlighted red, expand them fully, then copy/paste the text or a screenshot of it here (but be sure to remove any personal information that appears in it).

**Comment by X1SDNA** [comment]
Hi Jaspal.

Yes, it is the default behavior when I rename a note or edit the tag associated with it.

I will try your suggestion soon. However, I get reluctant to try signing in and out because sometimes I have to set up my extensions again, or at least reconfigure them, when closing one and moving to another. They're nice and settled at the moment, but I guess it's better to try it at this early stage.

I'll be setting up OneDrive and email backups soon, and FileSafe too, so I guess I'll be playing around with a lot of stuff anyway.

**Comment by JaspalSuri** [comment]
> Yes, it is the default behavior when I rename a note or edit the tag associated with it. 

I'm sorry to hear that; thanks for letting us know. If you could try repeating this once more and then send us the logs that appear in red by accessing the developer console (via `View` > `Toggle Developer Tools`), that might be helpful even if you haven't logged out. Hopefully with the next major version of the app, this issue will be resolved as a result. In any case, I've made a report for it.

> I get reluctant to try signing in and out because sometimes I have to set up my extensions again, or at least reconfigure them, when closing one and moving to another. 

Hmm, that shouldn't happen either, unless you're referring to setting the default editor, which in some cases isn't set again (but should). Please let me know what else needs to be set up again if it's more than just the editors.
