### ISSUE TITLE
[Help Wanted] Is there a way to hide dates?

### ISSUE THREAD

**Issue by X1SDNA** [standardnotes/forum#1081]
Hi - just purchased Extended.

Is there a way to hide dates from a note? For most of my notes, I don't want to see the date the note was created. It's irrelevant when I use the note on a daily basis. 'Date Updated' is useful, 'Date Created' not so (unless it is a journal entry, which you say is more of an Extension suggestion). Can I change this somewhere? (ie. have a choice to display date created, or date updated, or no date)?

Thanks.

**Comment by bryvin** [comment]
I don't believe there is a way to select which date is displayed in the Notes list. However you can certainly remove the dates from being listed. At the top of the Notes list there is an "Options" panel which has a "Display" section to change a few settings for that Notes list.

![Screenshot from 2020-08-27 17-23-18](https://user-images.githubusercontent.com/5969300/91500894-0a0d5c00-e88a-11ea-8952-79cb409592d8.png)

**Comment by X1SDNA** [comment]
Thanks for that - that helped. Didn't see those options before, sorry.

Can I suggest that these options are configurable by tag (or at least by parent tag), instead of globally only? Eg. the 'sort by' setting will differ wildly depending on the sort of content housed by a certain tag compared to another tag....

Also, just confirming that there is currently no manual drag-and-drop sort order? Thanks again.

**Comment by bryvin** [comment]
No problem, easy to miss that panel.

I'm not apart of the SN team so I'll let them comment further but currently no drag and drop behavior is present no.

**Comment by X1SDNA** [comment]
OK thanks again.

**Comment by JaspalSuri** [comment]
>Hi - just purchased Extended.

Thanks so much for supporting us by subscribing to Extended!

>Can I suggest that these options are configurable by tag (or at least by parent tag), instead of globally only? Eg. the 'sort by' setting will differ wildly depending on the sort of content housed by a certain tag compared to another tag....

Thanks for the suggestion! I'll pass along this feedback to the dev team for review! 

(Thanks for all of the help, Bryan! It's good to hear from you. :)
