### ISSUE TITLE
Multiple Listed.to blogs ?[Help Wanted]

### ISSUE THREAD

**Issue by timconsidine** [standardnotes/forum#1089]
I saw another post here which referred to having TWO listed.to blogs, arising from having the Extension added twice.
While the original post was about a problem, it made me think this could be a really great FEATURE.

Is there more documentation about how to do this on purpose?
I could create different standardnotes accounts but that's messy.
And as an Extended subscriber, I would not be overly keen on doubling up the subscription  ... great though SN is ! ;-)

**Comment by mobitar** [comment]
You can easily add multiple Listed accounts by just installing additional ones the same you installed the first one :) First rename the existing account by opening Extensions, finding Listed, and pressing the three dots button (...) on the extension. Then import the second author account and rename it to distinguish it.

**Comment by johnny243** [comment]
@timconsidine keep in mind that you will not be able to post the same Note on multiple blogs, if that's something you are looking forward to :)

**Comment by timconsidine** [comment]
> @timconsidine keep in mind that you will not be able to post the same Note on multiple blogs, if that's something you are looking forward to :)

OK, thank you.  No, it's not what I was planning to do, so no problem.
