### ISSUE TITLE
[Help Wanted] GitHub Push token scopes

### ISSUE THREAD

**Issue by ryanpcmcquen** [standardnotes/forum#1091]
**Describe the issue**
What are the expected scopes for the GitHub Push token?

**Comment by ryanpcmcquen** [comment]
https://docs.github.com/en/developers/apps/scopes-for-oauth-apps

**Comment by JaspalSuri** [comment]
Hi Ryan, I'll get in touch with the team for a list and get back to you as soon as I hear back! 

If you've run into any issues, can you let us know what options you've selected when generating a token? You might have issues with the web app, but it should work as expected in the desktop app.

**Comment by mobitar** [comment]
Probably just repo read/write access.

**Comment by ryanpcmcquen** [comment]
That sounds good, I did some testing of my own and verified that this will work for public:
![2020_09_11_1599810508__firefox_5fEBXN48lg](https://user-images.githubusercontent.com/772937/92886567-9a8a8700-f3c8-11ea-9560-b1956eecdf4b.png)
And this will work for private:
![2020_09_11_1599810521__firefox_R7OrUbsJC2](https://user-images.githubusercontent.com/772937/92886571-9bbbb400-f3c8-11ea-86d8-713f0041a5ba.png)

**Comment by ryanpcmcquen** [comment]
I have a PR up to document this:
https://github.com/standardnotes/docs/pull/12

**Comment by JaspalSuri** [comment]
Thanks! I've assigned someone to review the PR.

**Comment by ryanpcmcquen** [comment]
Closed by: https://github.com/standardnotes/docs/pull/12
