### ISSUE TITLE
Change fonts and settings?

### ISSUE THREAD

**Issue by Riftr** [standardnotes/forum#1096]
There doesn't appear to be any way to change the size/type of font that the program uses. The default font is small and pretty ugly. The best I seem to be able to do is "zoom in" which sort of achieves what I want but I don't want to zoom everything. The fonts also get even uglier when you zoom.

I'm on Linux using the appimage. I'd happily use a native package or a snap/flatpak which would respect my systems font settings instead if it were available.

**Comment by JaspalSuri** [comment]
Hi @Riifta,

This feature currently isn't supported by the desktop app, but you're free to download our Snap from [the app's releases page](https://github.com/standardnotes/desktop/releases).

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
