### ISSUE TITLE
Difficulty installing AppImage on Linux Mint 20

### ISSUE THREAD

**Issue by Acadexce** [standardnotes/forum#1098]
I recently decided to move away from snap apps and switch to AppImage instead. I've had good luck, but have hit a road block installing SN. 

No trouble downloading the AppImage and based on comments here checked "Allow executing files of program" under permissions. 

From there I have not had much luck, getting "No such file or directory" for every command like I enter on the SN website.

Ex. " mv ~/Downloads/standard-notes-3.4.4-linux-x86_64.AppImage ~/standard-notes-3.4.4-linux-x86_64.AppImage
mv: cannot stat '/home/computer/Downloads/standard-notes-3.4.4-linux-x86_64.AppImage': No such file or directory" 

I have used the site https://www.addictivetips.com/ubuntu-linux-tips/how-to-install-the-standardnotes-client-on-linux/ in the past ti install SN on Linux with some luck, but cannot seem to get it to work. I did managed to activate SN at one point, but was not able to get the GUI working. 

I apologize in advance for such a vague explanation of events. It's likely a combination of my newness with Linux and my inability to locate by issue. 

Any suggestions would be appreciated. 

Thanks

**Comment by Acadexce** [comment]
Update: I was able to execute "./standard-notes-3.4.4-linux-x86_64.AppImage" after executing "~/AppImages$" using instructions from the other web page, but once again I cannot seem to generate the GUI and if I close the command line at this point I will lose access to SN. The result of my last command if it helps: 

~/AppImages$ ./standard-notes-3.4.4-linux-x86_64.AppImage
extServer: Server started at http://127.0.0.1:45653/
14:00:08.725 › Checking for update
14:00:09.769 › Checking for update (already in progress)
14:00:10.593 › Update for version 3.4.4 is not available (latest version: 3.4.4, downgrade is disallowed).
PackageManager: received sync event for: Minimal Markdown Editor (1.3.5) (deleted: false), Plus Editor (1.4.3) (deleted: false), 2FA Manager (1.2.2) (deleted: false), Plus Editor (1.4.3) (deleted: false), Simple Task Editor (1.3.5) (deleted: false), Simple Task Editor (1.3.5) (deleted: false), Plus Editor (1.4.2) (deleted: false), Batch Manager (undefined) (deleted: false), Extensions (undefined) (deleted: false)
PackageManager: Tried to install a component with no download url: Batch Manager
PackageManager: Tried to install a component with no download url: Extensions
PackageManager: Checking for update for 2FA Manager
Latest: 1.2.2 | Installed: 1.2.2
PackageManager: Checking for update for Plus Editor
Latest: 1.4.3 | Installed: 1.4.3
PackageManager: Checking for update for Simple Task Editor
Latest: 1.3.5 | Installed: 1.3.5
PackageManager: Checking for update for Minimal Markdown Editor
Latest: 1.3.5 | Installed: 1.3.5
PackageManager: Checking for update for Simple Task Editor
Latest: 1.3.5 | Installed: 1.3.5
PackageManager: Checking for update for Plus Editor
Latest: 1.4.3 | Installed: 1.4.3
PackageManager: Checking for update for Plus Editor
Latest: 1.4.3 | Installed: 1.4.3
archiveManager: Data backup successfully saved: 2020-09-16T21-00-43.057Z.txt

**Comment by JaspalSuri** [comment]
Hi @Acadexce,

I'm sorry that you've run into a roadblock in the process of installing the AppImage. 

I would recommend installing the AppImage with AppImageLauncher. [Here are the instructions](https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian) on how to install AppImageLauncher.

Please let me know if you run into any other issues or if you have any other questions. We are considering potential alternatives to make the installation experience for Linux users smoother, but there's nothing set yet. 🙂

**Comment by Acadexce** [comment]
Thanks JaspalSuri, that did the trick!

SN now up and running.

**Comment by JaspalSuri** [comment]
You're welcome! Feel free to reach out to us if you have any other questions in the future. 🙂
