### ISSUE TITLE
[Help Wanted] How to install and run the app on Debian 10 testing? I get errors.

### ISSUE THREAD

**Issue by easthvan** [standardnotes/forum#1099]
UPDATED BELOW! 

Hello Linux Gurus, 

I am totally new on Linux, installed Ubuntu v20 a few days ago and uninstalled my Win10 and I loved Standard Notes on my Android and on Ubuntu. Switched to Debian 10 testing today and it was a perfect wonder until I tried to install this AppImage version Standard Notes. All I get are various errors and not working commands from the internet. Error popups and alien language error messages in terminal. 

Please help! I love this app. It is better than MS OneNote. 

Thanks! I am hoping that some of you speaks the language of this system. 

**To Reproduce**
Steps to reproduce the behavior on Debian 10 tetsing, commands as root:

1. wget https://github.com/standardnotes/desktop/releases/download/v3.4.4/standard-notes-3.4.4-linux-x86_64.AppImage
2. chmod a+x standard-notes-3.4.4-linux-x86_64.AppImage
3. ./standard-notes-3.4.4-linux-x86_64.AppImage
4. See error in popup window and in terminal:

QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
Qt: Session management error: None of the authentication protocols specified are supported
Failed to connect to bus: Operation not permitted
Failed to connect to bus: Operation not permitted
^C

![Screenshot from 2020-09-19 00-40-10](https://user-images.githubusercontent.com/71530894/93651273-393e6580-fa11-11ea-8e4c-06f0d7ee9ed5.png)

![Screenshot from 2020-09-19 00-43-01](https://user-images.githubusercontent.com/71530894/93651280-40657380-fa11-11ea-9e15-7e1f41f9e629.png)

![Screenshot from 2020-09-19 00-41-14](https://user-images.githubusercontent.com/71530894/93651277-3cd1ec80-fa11-11ea-9595-ef7034dd68e3.png)

Expected behavior:
The app shall receive a shortcut and run as it does on Ubuntu 20 from its store. 

OS: Debian GNU/Linux 10 (buster)

**Comment by easthvan** [comment]
UPDATE!

Now I see that it is actually kinda working I think! 

Despite all the errors etc above the shortcut is there and one of them is working, opens the app! 
The second shortcut is not working but fires the same error as above. Somehow I installed the app it seems so but twice... now I must figure out how to remove the second shortcut and clean up the mess somewhere in the folder that I might have caused... Removing shortcut is not working, says its root created so I cannot as user.

**Comment by omicron-b** [comment]
You should not have downloaded and attempted to run the app as root. You are right, not you have to clean this mess.
Now delete those files as root:
First:
`ls -la <file or directory>`
Be totally sure it's the one you want to delete, and second:
`sudo rm -rf <file or directory>`

"Shortcuts" are usually in `~/.local/share/applications/`

**Comment by mobitar** [comment]
This reddit guide published recently seems related: https://www.reddit.com/r/StandardNotes/comments/iwy1v8/integrating_standard_notes_into_linux_guide/

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
