### ISSUE TITLE
Notes display blank on the mobile app

### ISSUE THREAD

**Issue by johnnycase** [standardnotes/forum#11]
Hello!
After I recently updated to the latest version of the desktop and mobile apps, the most recent notes I have created in the desktop app are showing as blank in the mobile app. They show up fine in the desktop and web app, but show up as blank notes on mobile. Thank you!

**Comment by mobitar** [comment]
Hey John, can you try signing out then signing back in on the mobile
apps? (And making sure they are the latest versions)

**Comment by johnnycase** [comment]
Hi Mo,

I signed out and then updated to the latest version of the mobile app and
it's working now! Thank you for your help!

**Comment by johnnycase** [comment]
after signing out and updating the mobile app to version 1.3 my notes are all visible.

**Comment by mobitar** [comment]
Great!
