### ISSUE TITLE
Cursor does not appear on empty line in minimal markdown editor web view

### ISSUE THREAD

**Issue by plmrry** [standardnotes/forum#110]
When using the app in a browser, and using the Minimal Markdown editor, the cursor does not appear before you start typing on an empty line.

Here's an example where I hit `enter` after the first line:

![giphy 3](https://user-images.githubusercontent.com/688617/32138243-31c8fd7e-bbfd-11e7-9f07-883809a41590.gif)

**Comment by mobitar** [comment]
Strange, I'm not seeing this issue. I tested with Chrome. What browser are you using?

**Comment by plmrry** [comment]
Ah, it turns out it only happens at certain zoom levels (i.e. when you zoom the entire page to 80%, so it's probably more like a Chrome bug
