### ISSUE TITLE
Standard Notes Login Issues

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#1104]
Is Standard Notes has some issues with it's servers? 
Because i can't login to my account or it because i denied entry to my account?

**Comment by JaspalSuri** [comment]
Hi @docd3514, 

I'm sorry to hear that. I'm afraid that everything is currently working as expected for me. Can you provide me with more details as to what error messages you're receiving? Have you changed your password recently? If so, can you try logging in with your old password (in case there was in issue earlier)? 

What OS and/or web browser are you running Standard Notes on?

**Comment by JaspalSuri** [comment]
Update: The issue should have been temporary, due to a certain event. I will provide more details when I hear more from the team (it's nothing scary; I just don't want to provide any inaccurate info)!

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
