### ISSUE TITLE
Snap install, can't type anything (no keyboard input)

### ISSUE THREAD

**Issue by pfctdayelise** [standardnotes/forum#1105]
I installed the app on Ubuntu Linux 20.04.1, version 3.4.4 from https://snapcraft.io/standard-notes.

I can use the mouse to select various menu items but I can't type anything, neither in the main menu nor the account sign in. I am not trying to type CJK, just regular ascii.

I had previously installed the app as an AppImage, but I hadn't used it for many months due to https://github.com/standardnotes/forum/issues/690 / the hassle of making a menu shortcut. Could that somehow be interfering?

**Comment by pfctdayelise** [comment]
For comparison I installed GitKracken via Snap, I was able to use keyboard input in that application.

**Comment by JaspalSuri** [comment]
I'm afraid that I wasn't able to reproduce this issue. Can you try uninstalling both the Snap and AppImage and then reinstall the Snap? For some reason I'll run into issues with installing the Snap if the AppImage is installed. 

Given the issues that users have experienced with the Snap, I often suggest the [AppImage](https://standardnotes.org/extensions?downloaded=linux) with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/). 

[Here are the instructions](https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian) on how to install AppImageLauncher.

**Comment by bvdlingen** [comment]
I have the same issue with the latest snap package on solus linux.

Tried to remove the package and installed the beta and edge channel, no luck.
Also tried to reinstall with classic confinement.

AppImage does work as a work around - but I prefer a snap or flatpak package for desktop integration.

**Comment by JaspalSuri** [comment]
Thanks for the additional feedback; I'll add it to my report! I'm glad that the AppImage is working for you; we're currently looking into the feasibility of properly maintaining a Flatpak as well. 🙂
