### ISSUE TITLE
Auto-suggest tags and enable tab completion for tags

### ISSUE THREAD

**Issue by equasman** [standardnotes/forum#1106]
Hi,

You can implement autosuggestion feature for tags.
Standard Notes can auto-suggest tags right after typing the first letter of the tag. It should suggest all the tags that start with that letter. It can refine the suggestion after typing the second letter and so on. This will make life easy for every one of us.

Our life would be easier if we can select the tag using the keyboard along with the mouse.
We can use the up and down keys to go up or down the suggestion list and select the tag/s with Tab key or Enter key, whichever suits better.

You guys are doing a great work.
Thank you.

**Comment by equasman** [comment]
Got it.
Do you have any plan of integrating this feature in the basic Standard Notes?

**Comment by JaspalSuri** [comment]
I'm currently not aware of any plans of integrating it by default at the moment.

**Comment by equasman** [comment]
I meant, implementing this feature for the basic (free) users.

**Comment by myreli** [comment]
Since tags are [now native](https://standardnotes.com/blog/folders-from-extension-to-native) and this issue is unlikely to receive more interaction I'm closing it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
