### ISSUE TITLE
Suggest tags while searching notes

### ISSUE THREAD

**Issue by equasman** [standardnotes/forum#1107]
If an user searches a word, and that matched a tag, then Standard Notes can show the tags in the search results along with the notes. But obviously, tags and notes will be shown separately in the search results.

**Comment by JaspalSuri** [comment]
Hi @equasman,

Thank you for the feedback. I've passed it along to the dev team for review when they start building version 4 of the desktop and web apps. Currently they are working on several crucial improvements for version 3.5 to help improve syncing and performance.

**Comment by equasman** [comment]
Please make it available for the basic Standard Notes users.

**Comment by myreli** [comment]
Since tags are [now native](https://standardnotes.com/blog/folders-from-extension-to-native) and this issue is unlikely to receive more interaction I'm closing it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
