### ISSUE TITLE
Tags were automatically removed while syncing

### ISSUE THREAD

**Issue by equasman** [standardnotes/forum#1109]
I use Standard Notes web version from Windows and Ubuntu, and Android app from my smartphone.

The last time I used Standard Notes from Windows was a couple of days ago. Today I again logged into Standard Notes web version from Windows. Before that I used Standard Notes web version from Ubuntu and from my smartphone. Platform might not be an issue here since I'm using the web version in either case.

While syncing in Windows, Standard Notes automatically removed some tags from some of my notes. The tags were there in the left panel. But besides some of the tags, the number of notes were showing zero.

I faced the same issue of losing tags from notes a week or so ago. I didn't mind back then. But this is the second time it happened.

Reliable and seamless syncing should be the main priority as we're putting our life's info in Standard Notes.

**Comment by equasman** [comment]
> Were any of the notes or tags involved marked as conflicted?

No.

> Does it match up with what you're seeing in your primary browser session?

Yes.

> When adding the tag via your mobile device, do you ensure that that you give the app enough time to sync your changes?

I always do. In fact, the notes which lost tags weren't recently created. I created/modified them earlier. After their creations, I've accessed Standard Notes several times (>20) from Firefox on Ubuntu and Android app.

> Which part of the world are you in? And do you experience any network shakiness?

My internet speed is 4 Mbps. I think that's sufficient for syncing.

> If it's not a UI issue, the only other explanation is that your tag changes never got synced in the first place, and remained a local change on the device you made the change from.

I disagree. It synced properly. But I faced the problem as soon as I went to Standard Notes web from Firefox on Windows. I had the credentials saved. So as soon as I typed the URL and pressed enter, Standard Notes loaded instantly. I could see the notes were syncing. But after the notes were completely synced, I noticed the counter besides some of the tags were zero. I clicked on them and saw they didn't show any notes.

If I have to guess, after my last login to Firefox on Windows, I've created and modified hundreds of notes. Now when Standard Notes tried to sync with the already saved (cached) local copy of the notes, it messed up.

**Comment by mobitar** [comment]
Do you know when the last time you had access that Firefox session was?

**Comment by equasman** [comment]
I don't remember exactly. But it'd have to be a week or so ago.

**Comment by myreli** [comment]
Since tags are [now native](https://standardnotes.com/blog/folders-from-extension-to-native) and this issue is unlikely to receive more interaction I'm closing it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
