### ISSUE TITLE
Example password, master key and authentication key for authentication?

### ISSUE THREAD

**Issue by ddddavidmartin** [standardnotes/forum#111]
Good day,

I'm trying to put together a Python implementation to sync notes. I have been going through the [Client Development Guide](https://github.com/standardnotes/doc/blob/master/Client%20Development%20Guide.md) and [Standard File spec](http://standardfile.org/). Unfortunately I'm already getting stuck at the authentication step.

I have set up a test account and these are the auth params I am getting for my email:
`{'pw_salt': '0a6ac9f407f227238d10d84009c66dd487380bac', 'pw_cost': 5000, 'version': '002', 'pw_func': 'pbkdf2', 'pw_alg': 'sha512', 'pw_key_size': 512}`

What would be the correct password, master key and auth key for example for password `whatever` for authentication with the server?

I think I'm getting something wrong in the calculations as I'm getting a `"error":{"message":"Invalid email or password.","status":401}` response and I can log in fine through the web interface.

Thanks!

**Comment by mobitar** [comment]
Hey David, you might want to check out these existing clients:

https://github.com/matze/python-standardfile
https://github.com/tannercollin/standardnotes-fs

**Comment by ddddavidmartin** [comment]
Ah, I was hoping that someone would have put in the work already but couldn't find anything. Thanks very much for pointing those out Mo, I'll give them a try!
