### ISSUE TITLE
Passcode protection disappeared after forced device restart

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/forum#1110]
My computer froze due to a power supply issue and I had to hard-restart (power it off manually). Standard Notes had a passcode on, which it normally required whenever the application was started. The app was open and unlocked at the time of the incident.

After the system rebooted, I opened Standard Notes and was surprised to see that notes appeared without requesting any passcode. I could go on view and edit anything without providing a passcode. In the Account window, Passcode Lock was now switched off. I closed the app properly and opened again to make sure it's a not a one-time glitch, and it isn't, local protection was removed as a product of the incident.

How was this possible? I believe this indicates some security gaps.

I was on Windows, using desktop (Electron) version 3.4.2. I took a screenshot of my error console right after the app first loaded without the passcode lock, see it below.

![4285](https://user-images.githubusercontent.com/7106231/94994052-a959f900-0584-11eb-8929-cf407845cb87.png)

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
