### ISSUE TITLE
Searchable Tags

### ISSUE THREAD

**Issue by dunnaaron** [standardnotes/forum#1111]
Now that I have a lot of tags, it would be nice to be able to search by tag or by combination of tags. For example, if I have a note that has the tags "to-do" and "grocery", it would be nice to be able to go to the search bar and type `#to-do #grocery` and have any notes with those tags filtered.

**Comment by JaspalSuri** [comment]
Hi Aaron,

I've added your +1 to this request. I'm going to close this thread since there's a similar one (#1107), but have added this to the report regarding this enhancement. 🙂 

Thanks for the feedback!
