### ISSUE TITLE
[Help Wanted] A server error occurred while trying to sign in. Please try again - LINUX

### ISSUE THREAD

**Issue by Jonnycash225** [standardnotes/forum#1112]
I have updated my Ubuntu from 18.04 to 20.04. Standard notes was working fine on the previous version, however with the new version, i can not log in. I keep getting the error message "A server error occurred while trying to sign in. Please try again". I am logged onto the internet and everything else works fine.

Please help!

**Comment by JaspalSuri** [comment]
Hi @Jonnycash225,

Is this for the desktop, [web app](https://app.standardnotes.org), or both? 

If you're using the desktop app, are you using the Snap or the AppImage?

Finally, can you click on the hamburger menu in the top right corner > click `View` > click `Toggle Developer Tools` and then share everything that is highlighted in red here? Make sure to (a) expand all of the contents and (b) obscure any personal information.

**Comment by Jonnycash225** [comment]
> Hi @Jonnycash225,
> 
> Is this for the desktop, [web app](https://app.standardnotes.org), or both?
> 
> If you're using the desktop app, are you using the Snap or the AppImage?
> 
> Finally, can you click on the hamburger menu in the top right corner > click `View` > click `Toggle Developer Tools` and then share everything that is highlighted in red here? Make sure to (a) expand all of the contents and (b) obscure any personal information.

Hi Jaspal,
  This is for the desktop app that i downloaded from the software store in UBUNTU. (VERSION 3.4.6). I am not sure what Snap or AppImage is! How would i find this out? 

Also, i have accessed developer tools, however there are different menus such as elements, consoles, sources, network. There is also more including styles and DOM breakpoints. Is there a specific menu you want?

Thanks

**Comment by mobitar** [comment]
When signing in, can you click Advanced Options and ensure the sync server URL is set to "https://sync.standardnotes.org"?

**Comment by Jonnycash225** [comment]
HI

> When signing in, can you click Advanced Options and ensure the sync server URL is set to "https://sync.standardnotes.org"?

Hi Mobitar, 
  This is already set up. Any other suggestions? cheers

**Comment by Jonnycash225** [comment]
HI

> When signing in, can you click Advanced Options and ensure the sync server URL is set to "https://sync.standardnotes.org"?

Hi Mobitar, 
  This is already set up. Any other suggestions? cheers.

**Comment by baptiste-grob** [comment]
Hi @Jonnycash225,
Did you use a beta version recently and used it to upgrade your account encryption? If that's the case, you'll be unable to access your account from stable versions of the app and will have to use the beta until we release it.
Could you try logging in on https://app.standardnotes.org and tell us if that works?

**Comment by Jonnycash225** [comment]
> Hi @Jonnycash225,
> Did you use a beta version recently and used it to upgrade your account encryption? If that's the case, you'll be unable to access your account from stable versions of the app and will have to use the beta until we release it.
> Could you try logging in on https://app.standardnotes.org and tell us if that works?

HI Baptiste,
  Not sure about the Beta version. Is all i know is that i was using the app on UBUNTU 18.04 and it was logging in and working fine. Now that i have updated to 20.04 it does not log in anymore saying that it is offline. I have just logged into the browser app and that is working fine. It is also working fine on the app on my mobile phone. Cheers

**Comment by Jonnycash225** [comment]
> Hi @Jonnycash225,
> Did you use a beta version recently and used it to upgrade your account encryption? If that's the case, you'll be unable to access your account from stable versions of the app and will have to use the beta until we release it.
> Could you try logging in on https://app.standardnotes.org and tell us if that works?

HI Baptiste,
  Not sure about the Beta version. Is all i know is that i was using the app on UBUNTU 18.04 and it was logging in and working fine. Now that i have updated to 20.04 it does not log in anymore saying that it is offline. I have just logged into the browser app and that is working fine. It is also working fine on the app on my mobile phone. Cheers

**Comment by JaspalSuri** [comment]
> This is for the desktop app that i downloaded from the Ubuntu Software Center (version 3.4.6). I am not sure what Snap or AppImage is! How would i find this out?

If it's from there, it's the Snap package. Thank you for letting me know. 🙂 

> Also, i have accessed developer tools, however there are different menus such as elements, consoles, sources, network. There is also more including styles and DOM breakpoints. Is there a specific menu you want?

Sorry about that; I meant to include a step in navigating to the `Console` tab. Thank you for asking!

I'll let @.Mo and @.Baptiste handle things from here, but I just wanted to answer your questions.

**Comment by Jonnycash225** [comment]
HI,
  Please tell me if this is not the correct part that you need. I took a screen shot as it would not copy.
![2020-10-14_14-19](https://user-images.githubusercontent.com/72791593/95962141-30825900-0e30-11eb-9827-648532d4af56.png)

**Comment by baptiste-grob** [comment]
Can you try signing in and take a screenshot of the console right after you get the error message? It should include at least error message (in red).

**Comment by Jonnycash225** [comment]
![2020-10-14_20-50](https://user-images.githubusercontent.com/72791593/95998325-f54b4e80-0e5e-11eb-95b8-76b733758091.png)

**Comment by baptiste-grob** [comment]
Can you show us what the `Console` tab in the developer tools say?

**Comment by mobitar** [comment]
(Also the Network tab if possible)

**Comment by Jonnycash225** [comment]
On the network tab, i done a request because as you see in the second picture there was nothing to see:

![1](https://user-images.githubusercontent.com/72791593/96000585-41978e00-0e61-11eb-9873-4d12e86ab60a.png)
![2](https://user-images.githubusercontent.com/72791593/96000599-43f9e800-0e61-11eb-95b4-8302f6baeea9.png)
![3](https://user-images.githubusercontent.com/72791593/96000601-452b1500-0e61-11eb-88fe-031d06b28257.png)

**Comment by Jonnycash225** [comment]
I have tried logging in with my VPN disconnected also and still not having any luck. I done this because my Spotify app has been doing the same but it has been doing this since i installed UBUNTU 18.04. Standard notes was working for me on 18.04.

**Comment by mobitar** [comment]
Are you using a proxy by any chance? The SN app will not work behind a proxy.

**Comment by Jonnycash225** [comment]
No i do not believe i am. Just a VPN

**Comment by mobitar** [comment]
ERR_NAME_RESOLUTION_FAILED would be a local issue with your computer failing to even reach our servers in the first place.

**Comment by Jonnycash225** [comment]
But i am sitting here using the internet quite freely with everything else so this is confusing.

**Comment by mobitar** [comment]
Can you try other Electron apps to see if you have the same issue there? You can see a list here: https://www.electronjs.org/apps

Preferably one that has recently been updated.

**Comment by Jonnycash225** [comment]
Now i can not reinstall. I have rebooted also
![4](https://user-images.githubusercontent.com/72791593/96003346-56c1ec00-0e64-11eb-9f84-badb634288bd.png)

**Comment by Jonnycash225** [comment]
Can you tell me an app that is in the app store? I cant seem to find one of these in the store from the 5 i have tried?

**Comment by Jonnycash225** [comment]
OK found one: todolist

**Comment by baptiste-grob** [comment]
snapcraft.io is the infrastructure Ubuntu Software Center is running on so that's fine.
You can try installing Visual Studio Code on the store, for example.

**Comment by Jonnycash225** [comment]
> snapcraft.io is the infrastructure Ubuntu Software Center is running on so that's fine.
> You can try installing Visual Studio Code on the store, for example.

HI there, OK i downloaded Visual Studio Code and that seems to be working fine from what i can gather (although i have no idea how to use it!!). Do you have any other instructions for me or would you like to see some settings from this app?

THank you

**Comment by Jonnycash225** [comment]
> snapcraft.io is the infrastructure Ubuntu Software Center is running on so that's fine.
> You can try installing Visual Studio Code on the store, for example.

HI, I have re-installed the Standard notes app, however, i am still seeing the offline status. I have downloaded Visual Studio Code and that seems to be working fine from what i can gather. If any of you guys have any other suggestions, it would be really appreciated. Whilst i do only have the free version currently, i am planning on upgrading to the 5 year plan. I can manage with the browser version on my laptop for now, but it would be convenient to get the app up and running. Do you think i may need to wait until a new version is released for update? Thank you for the help thus far.

**Comment by baptiste-grob** [comment]
Thanks for considering the upgrade @Jonnycash225 :) we have a new version in the works, hopefully it'll solve your issue.

**Comment by Jonnycash225** [comment]
> Thanks for considering the upgrade @Jonnycash225 :) we have a new version in the works with new internals, hopefully it'll solve your issue.

HI There, this issue is still unresolved for me. May i ask, when will the new release be coming out?

**Comment by baptiste-grob** [comment]
Hey @Jonnycash225, version 3.5.1 has been released today so once the update propagates to the Ubuntu Software Center you'll be able to upgrade. Let us know how it goes!

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
