### ISSUE TITLE
Where can I get a full copy of the non-free, enhanced, pay version of the software?

### ISSUE THREAD

**Issue by Cognitive-dissonance** [standardnotes/forum#1113]
**Describe the issue**
The license used clearly guarantees any modification must also include the open source. Regardless if the mods are for pay or not.

**To Reproduce**
1. Go to 'github source page for the standard desktop, release or develop, and read the License file'
2. Click on 'contact/help button link somewhere as the location of the source is not immediately obvious - apologies if I missed it'
3. Scroll down to 'the "submit" button and clck'
4. See error - Hopefully NOT, or you might then have to open a new bug ticket for submitting help request issues. 

**Expected behavior**
As per the GNU AFFERO GENERAL PUBLIC LICENSE V 3, 19 November 2007, it is expected to see a link or way to access the modified source.

**Screenshots**
![Screenshot from 2020-10-14 20-45-21](https://user-images.githubusercontent.com/13725888/96074851-879f2280-0e5e-11eb-890e-36733857ef6f.png)

Version: latest Develop and release on Github Oct 14, 9pm

**Additional context**
Seem odd to brag and flash the Free and Open Source as a major feature, but if you actually pay money for the pay bits, you lose (or can't find) the source for the modified version as clearly stated must be available by the license. 2 relevant paragraphs and URL in "screenshot" seem very unambiguous. I'm not going to modify or sell it, but it's obvious the source should be easily available.. particularly with this type of software - who knows what source changes may even just have a typo that opens a hole.. that's all about what you keep bragging is such a great thing about the free one - so the pay one is not only less secure, but breaks the license.

**Comment by JaspalSuri** [comment]
Hi @Cognitive-dissonance,

Are you looking for the source code of any particular extension that's not already listed [here](https://github.com/standardnotes) or [here](https://github.com/sn-extensions)?

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
