### ISSUE TITLE
Security Update: Accidental 3.5 desktop beta upgrades

### ISSUE THREAD

**Issue by arielsvg** [standardnotes/forum#1114]
**UPDATE (November 2nd, 2020):** Version 3.5 is now out on all platforms.

# Context

On October 16, 2020, a beta build (version 3.5-beta9) was inadvertently distributed to all desktop users due to our deployment process failing to mark it as a beta. Because our global 3.5 release is not yet ready, and not yet available on all platforms, upgrading your encryption version prematurely means you will not be able to access your account unless you are using the 3.5 beta on all platforms.

**Unless you have explicitly opted into the beta, DO NOT upgrade your encryption version if you are prompted to in app.**

# Going back to a stable version

1. **Sign out**
2. Uninstall the application
    - On Windows, look for any _Standard Notes_ entry in your applications list
    - On macOS, drag any Standard Notes app in your Application folder or Launchpad to the trash
3. Go to https://standardnotes.org, download the application and install it
4. In the app, ensure you are now running a stable version by clicking on the _Account_ and noting that the version number in the bottom left starts with _3.4_, and has no _beta_ suffix of any kind.

# FAQ

## How can I know whether I have upgraded my encryption version or not?

- If your app reports a version in the 3.4 range, like 3.4.6 or 3.4.10, and you are using Standard Notes without issue, then you have not upgraded your encryption and can ignore this message.
- If you can sign in from https://app.standardnotes.org and use Standard Notes without issue, then you have not upgraded your encryption.
- If you can use the Android app and have never opted in to the testing group on Google Play or TestFlight, then you have not upgraded your encryption.
- If the iOS or Android app tells you that your email or password is invalid, yet you are sure that you entered it correctly, you may have upgraded your encryption.

## I have upgraded my encryption. How can I keep using Standard Notes?

If you have upgraded your encryption, you will need to use version 3.5 on all the platforms you are using:
- Desktop: https://github.com/standardnotes/desktop/releases (look for the latest release with _beta_ in the name)
- Web: https://app-beta.standardnotes.org/
- Android: https://play.google.com/apps/testing/com.standardnotes (restart the Play Store app and check for updates)
- iOS: https://testflight.apple.com/join/H61MmmCA 

---

We will be monitoring this thread and answer any additional questions or issues you may have. We are deeply sorry for any inconvenience this may have caused.

**Comment by MonolithOrchids** [comment]
Too late now for the big warning, i've got the update and the next day the program wasn't opening, then i saw that it was installed a beta version, didn't knew it would also affect the ios version, oh well, at least it didn't break anything else.

**Comment by JaspalSuri** [comment]
Hi @MonolithOrchids,

I'm sorry to hear that. Are you able to get the iOS app to work again after joining the testing group on [TestFlight](https://testflight.apple.com/join/H61MmmCA)? Are you having any issues with the desktop app?

**Comment by MonolithOrchids** [comment]
@JaspalSuri Yeah no problem using the Test Flight, everything is fine now thanks.

**Comment by h1d3m3** [comment]
I seem to be in a bad spot.

I don't remember upgrading my encryption, but your instructions seem to indicate that I may have. I am currently in a situation where I cannot use the app at all or access my notes.

- I was using `standard-notes-3.4.4-win.exe` fine, until I logged out. When I logged in, I received the message `This version of the application does not support your newer account type. Please upgrade to the latest version of Standard Notes to sign in.`
- Following the instructions, I first uninstalled and re-downloaded `standard-notes-3.4.4-win.exe`, thinking maybe it could help. It produced the same error as above
- At this point, I tried using the web based UI (which produced the same error above) and was now convinced I must have upgraded the encryption. Following the instructions, I uninstalled the old version, downloaded and installed `standard-notes-3.5.1-beta05-win.exe
- At this point, when I try to log into my account, it starts with "generating login keys" and then I get the message "Invalid email or password." I am 100% sure I am using the right login/keys that I have previously stored in my password manager.

Any pointers you can give would be helpful.

**Comment by karan** [comment]
I'm disappointed in SN for making 3.5 available without updating F-Droid. I upgraded to 3.5 (which didn't show any warnings for known issues) and then my Android app stopped working. Had to revert to using a GPS version instead.

**Comment by JaspalSuri** [comment]
Hi @karan,

> I'm disappointed in SN for making 3.5 available without updating F-Droid. I upgraded to 3.5 (which didn't show any warnings for known issues) and then my Android app stopped working. Had to revert to using a GPS version instead.

It's something that we'd like to have on F-Droid; for more information, please see [here](https://github.com/standardnotes/mobile/issues/292).

Did you initially update the mobile app to v3.5 with the .apk available on [GitHub](https://github.com/standardnotes/mobile/releases) or are you referring to what happened after updating the desktop app?

**Comment by karan** [comment]
No only the web app was upgraded to 3.5 and probably the iOS app was running the latest version. The Android version from f-droid was latest available there (3.17 I think?).

**Comment by JaspalSuri** [comment]
> No only the web app was upgraded to 3.5 and probably the iOS app was running the latest version. The Android version from f-droid was latest available there (3.17 I think?).

Thanks for clarifying! While it doesn't have the ability to automatically update to the latest version, you can download the [latest .apk's from GitHub](https://github.com/standardnotes/mobile/releases) if you do not want to install the [app via the Google Play Store](http://play.google.com/store/apps/details?id=com.standardnotes).

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
