### ISSUE TITLE
Unexpected behavior with protected notes after quitting/relaunching OS X desktop app

### ISSUE THREAD

**Issue by sethmad** [standardnotes/forum#1115]
I have passcode lock enabled and have my privileges set such that viewing protected notes requires both the local passcode and the account password. If I view a protected note, quit the app, then relaunch, I can view the protected note without entering the account password. 

1. Enable passcode lock
2. Set privileges such that protected noted require both account password and local passcode
3. Create a note
4. Set the note to protected
5. Quit and relaunch app. Access protected note by entering password and passcode.
6. Quit and relaunch app. Access protected note without entering password and passcode.

I would expect that protected notes would require password/passcode any time the app is relaunched.

OS X 10.15.7
Standard Notes 3.4.10

**Comment by JaspalSuri** [comment]
Hi @sethmad,

Please click on the `Account` button (in the bottom left-hand corner of the main window) > click on `Manage Privileges` > and then click on `Clear Session`. It should immediately ask you for your password or passcode the next time that you view a protected note. 🙂

**Comment by sethmad** [comment]
That worked, thanks. Is the issue I reported a bug, or did I accidentally make a change that enabled it?

**Comment by JaspalSuri** [comment]
You didn't do anything on your end that enabled it. :) 

We accidentally released the desktop beta app to all of our users so it's possible that your client was updated to it (but might currently be back on the stable app) which resulted in what you experienced. 

If it happens again, please let us know!
