### ISSUE TITLE
Offline version of text/md import tool

### ISSUE THREAD

**Issue by jamesrobb** [standardnotes/forum#1116]
**Describe the issue**
I'd like to know if there is a way to download and use the plaintext import tool found on this webpage: https://dashboard.standardnotes.org/tools

I have a pretty complicated folder structure I would like to convert and uploading it all on the web would be very tedious.

**To Reproduce**
Not relevant.

**Expected behavior**
Not relevant.

**Screenshots**
Not relevant.

**Desktop (please complete the following information):**
 - OS: Linux

**Smartphone (please complete the following information):**
Not relevant.

**Additional context**
Not relevant.

**Comment by mobitar** [comment]
The tool comes from this package: https://github.com/standardnotes/sntools

The tool doesn't upload anything to a server; the conversion is done fully locally and offline. So if you loaded the page, disabled your connection, and used the tool, it should continue to work.

**Comment by jamesrobb** [comment]
Thanks
