### ISSUE TITLE
[Help Wanted] Unable to add text in large text body field; blinking cursor oddly indented after creating note.

### ISSUE THREAD

**Issue by cr3ative9uru** [standardnotes/forum#1117]
**Describe the issue**
Unable to add any content inside the large text body field for a new note. Cursor in field blinks but is oddly placed at least 4 tabs in from the left. I am using plain text editor. I do not have the spreadsheet module activated.

**To Reproduce**
1. Open macOS desktop app Standard Notes
2. Click on plus button to create a new note
3. Click on large body text field where you would add content for a new note

**Expected behavior**
Unable to add any content inside the large text body field for a new note. Cursor in field blinks but is oddly placed at least 4 tabs in from the left. I am using plain text editor. I do not have the spreadsheet module activated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina, version 10.15.7 (19H2)
 - Browser: N/A
<img width="672" alt="Screen Shot 2020-10-21 at 10 25 06 AM" src="https://user-images.githubusercontent.com/71854307/96734282-61124780-1388-11eb-8653-f47f8d44ebd6.png">

**Additional context**
The app has been running in for several hours. I was doing research in Firefox and went to Standard Notes to create a new note. I was unable to create a new note that would accept any text in the large text body field.

**Comment by mobitar** [comment]
It looks like the margins for the editor are adjusted awkwardly. If you start hovering your mouse from the left of the editor and move it to the right, you should eventually see a vertical bar appear, and you can drag that to left to adjust the margins. If you can't find the bar, you can click Options > Margin Resizers, and it will flash the bars momentarily.

**Comment by mobitar** [comment]
It could also be an issue with the Quick Tags extension, which in rare cases has been known to enter into an infinite loop. This issue is fixed in 3.5-betas, but not in the production apps.

Can you do this:

1. Click Help > Toggle Error Console
2. Open the Network tab
3. Observe if the app seems to be making an abnormal number of requests to the autocomplete-tags endpoint?

**Comment by cr3ative9uru** [comment]
Mobitar, thank you for the helpful advice and information. I will monitor. I will reopen if I see it appear again.
