### ISSUE TITLE
Web client, Futura Theme has two small issues

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#112]
- **UPDATE: Logged out, then back in -- problem with Menu / Editor was no longer present.**

- **But the problem with selected text having very low contrast still exists...**

For Standard Notes Web client, Futura Theme, Firefox 56.

Per the following screenshot, in Firefox 56 the Futura theme has a couple of small issues. (The problem doesn't exist in the Vivaldi browser based on Chrome.)

![2017-10-31_standardnoteswin-futuratheme](https://user-images.githubusercontent.com/3333327/32251560-bb426ede-be4e-11e7-8969-11c80935d5db.png)

- The *Menu* and *Editor* elements are not completely visible and so hard to click.
- Selected text has very low contrast.

The Windows client:

- Displays the *Menu* and *Editor* elements properly.
- Displays selected text with a slightly better amount of contrast, albeit still a bit too low.

I'd edit the CSS(?) if I knew how to do that...

Cheers & hope this helps,
Riley
SFO

**Comment by mobitar** [comment]
Ok, the highlight issue has been fixed and deployed. However, the auto complete issue is a more serious one. It didn't use to behave like this. But I just tested and now and can confirm the same. Will get this fixed for 2.1.

**Comment by WritingSolutions2020** [comment]
Oops, the updated Windows desktop client does provide a bit better contrast, but the Web client in Firefox 56 seems even worse:

![2017-11-01_snwebclientffox56](https://user-images.githubusercontent.com/3333327/32299089-8424a1e2-bf11-11e7-9d88-11bf18666e10.png)

Is the CSS or the theme itself available for editing? I could tweak this on my own if you pointed me in the proper direction...?

Cheers & thanks,
Riley
SFO

**Comment by WritingSolutions2020** [comment]
Note that I this morning upgraded the Windows desktop client to 2.0.3. The contrast of selected text in the Futura theme was much improved there.

But the Web client in Firefox 56 still "censors" selected text with gray-on-gray as shown in my preceding post's screen shot...

Cheers,
Riley
SFO

**Comment by mobitar** [comment]
Actually have it on my to do to take a look at this. Will hopefully get to it soon.

**Comment by effieeee** [comment]
Current Futura theme no longer has these issues on web
