### ISSUE TITLE
Self-Hosting Account Creation Restrictions

### ISSUE THREAD

**Issue by ohdisyus** [standardnotes/forum#1123]
Hello All. Great app! I've started my own self-hosted version of StandardNotes on my VPS and am wondering if I can restrict registrations to only those I invite to create accounts--or can I just create accounts and hand out the credentials instead of allowing anyone to register? Appreciate it. -Jason

**Comment by mobitar** [comment]
See [here](https://docs.standardnotes.org/self-hosting/managing-options) :)
