### ISSUE TITLE
blank page on Android 8.00 v.3.5.0

### ISSUE THREAD

**Issue by johnbook3241** [standardnotes/forum#1124]
**Descrption of the bug**
Just updated to the newest Standard Notes version.

Nothing is displayed, only a blank page with "All notes" in the header and the hamburger menu.

No data. Nothing.

I tried reinstalling the app, still nothing.

**Smartphone:**
 - Device: Samsung galaxy S7

**Android Version**
8.00

**Comment by E-Baler** [comment]
Hello, same issue on iOS 12 and 14! Thanks

**Comment by mobitar** [comment]
cc @radko93

**Comment by mobitar** [comment]
If your data is properly synced to your account, you may try signing out and back in to see if that resolves the issue. If you do not have an account and are using the app offline, then I do not recommend uninstalling or deleting any data, and instead waiting for a resolution.

**Comment by radko93** [comment]
@johnbook3241 can you try to clear app data?

**Comment by johnbook3241** [comment]
brilliant ! clearing app data resolved the problem, thanks !

**Comment by E-Baler** [comment]
Same for iOS it works - with an account: delete the app and reconnect and everything is ok 😁. 

Thanks for your work!!!
