### ISSUE TITLE
Enex conversion failed

### ISSUE THREAD

**Issue by hotigris** [standardnotes/forum#1125]
When I try to convert an .enex file by SN Tools (https://dashboard.standardnotes.org/tools), it returns this very unspecific error message: "There was an error processing your file. Please submit your console output to help@standardnotes.org." I tried it with several files from Evernote. Any idea?

**Comment by JaspalSuri** [comment]
Hi @hotigris,

I apologize for the lack of specific instructions; I've provided some feedback to the team for review. Please try using the ENEX converter with the same file(s) again, and within your web browser, please right-click on any blank part of the page and click "inspect element". In the window that appears after, click on the `Console` tab, copy the text or take a screenshot of the errors that are highlighted in red, and then submit your console output to help@standardnotes.org (in what I assume is to help preserve your privacy).

Here's what it might look like. 
![image](https://user-images.githubusercontent.com/44656000/97965487-4a4bf780-1d6f-11eb-82b8-1f17e7262ef1.png)

Thank you so much for reaching out to us!

**Comment by hotigris** [comment]
Hi there,
thank you very much for the instructions. It's done.
Regards,
Imre Knausz

**Comment by JaspalSuri** [comment]
Thank you so much for doing that. We'll look into it further!

**Comment by JaspalSuri** [comment]
Hi @hotigris,

This issue was fixed; you should be able to reuse the [Evernote importer tool](https://dashboard.standardnotes.org/tools) again. 🙂 

Let us know how that goes and if you run into any other issues, or have any other questions!

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
