### ISSUE TITLE
Black Screen on ios after update to 3.5.0

### ISSUE THREAD

**Issue by SusanLO10** [standardnotes/forum#1126]
**Describe the bug**
Experiencing this bug on the app version of Standard Notes, on an iPhone Xr running iOS13.5.
I had version 3.0.23, updated today to 3.5.0.

When I opened the app after completing the install, the UI was black instead of white as per the update.

I was prompted to enter my password two (2) times, then the app behaved as it typically does when I enter the local password, except for, now, the only things showing are the blue hamburger on the left, and "All notes" in the header. When clicking the hamburger, none of the typical options are shown.

I reset my device, and the problem persists. I left it alone for a few hours, and the problem persists.

Same problem as covered in post blank page on Android 8.00 v.3.5.0 made by johnbook3241,
but I do not have an account, and use offline.

Should I clear my app's cache, or are my odds at preserving my notes better if I wait for the fix?
Alternatively, any knowledge on how to rollback to 3.0.23?

Links to screenshots:
https://snipboard.io/q1EQWK.jpg
https://snipboard.io/u8hBWn.jpg

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS13.5.
 - Version 3.5.0.

**Comment by radko93** [comment]
Hi, I'm really sorry for the trouble with the new update. We are working on fixing this issue and there will be a new update coming out very soon. If you can wait please do. Unfortunately, I don't think it's possible to install an older version of the app.
#1124

**Comment by jeifour** [comment]
![3992E8A8-3788-4767-815A-503648D43AB7](https://user-images.githubusercontent.com/3247063/141793982-60ff76ca-1edf-4663-89d1-fb9d5e9a3dec.png)

getting this today. Cannot access my notes at all, everything becomes blank white after 1 second. Version 3.9.1 on iOS 15.1

**Comment by moughxyz** [comment]
Glad to hear it's been fixed!

**Comment by alex17pat** [comment]
After trying so many things eventually got rid of the issue by forcing restart your iPhone. [](https://thegeekpage.com/iphone-screen-goes-black/)
