### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by docd3514** [standardnotes/forum#1127]
Account issues

i can't access my notes, here some the alert i got:

"waiting for keys" and when i try to access my notes again it says "Please sign in to restore your decryption keys and notes." with a notes that says "Unable to Decrypt"

 - Device: Redmi 9
 - Android 10
 - Mobile App
 - The latest (just updated the app)

**Comment by JaspalSuri** [comment]
Hi @docd3514,

I’m sorry to hear that. Can you try signing into our [web app](https://app.standardnotes.org)? 

Please see if all of your most recent notes are still there, and then try signing out of the Android app and sign back in again.

**Comment by radko93** [comment]
@docd3514 we released a new update, can you try to update to that version and let me know if the error is fixed?

**Comment by docd3514** [comment]
i'm continuing the issues solving through Slack, i'm closing the issue in Github and move to Slack,
