### ISSUE TITLE
Password required for local storage upgrade

### ISSUE THREAD

**Issue by ktleary** [standardnotes/forum#1128]
Upon opening the iOS app, it prompted to enter the application password to upgrade the local data storage structure (see attached). 

I came here to see if there was any information on this and saw there have been some version control issues recently. 

Should we perform this upgrade?

![image](https://user-images.githubusercontent.com/8782728/97983664-87df6d80-1dcd-11eb-99ca-a9273ef50688.jpeg)

**Comment by JaspalSuri** [comment]
It should be safe to upgrade. 🙂  The new app asks for your passcode as it will need it to decrypt the keys that will in turn decrypt your local storage data. If you'd like, you can sign into the [web app](https://app.standardnotes.org/) and download a copy of your notes as a precaution. 

Please let us know how it goes or if you have any other questions before proceeding.

**Comment by ktleary** [comment]
Thanks, I followed your advice and everything worked great. Looks amazing. You can close afaik.

**Comment by JaspalSuri** [comment]
That's great to hear! Thank you for letting us know. 🙂
