### ISSUE TITLE
About: anonymized automatic error reporting in the latest web and desktop apps

### ISSUE THREAD

**Issue by arielsvg** [standardnotes/forum#1129]
Hello everyone,

Version of the [web](https://app.standardnotes.org/) and [desktop](http://standardnotes.org/download) apps, v3.5.2, includes automatic, anonymized error reporting that will be enabled by default when you load it for the first time, and we would like to tell you how that came to be.

# Context

This week we released our new major version of the Standard Notes app on all platforms, v3.5. It is a rewrite of the core logical units of the app, and features a new encryption as well. You can read the release notes [here](https://github.com/standardnotes/desktop/releases/tag/v3.5.1).

This version had gone through a series of automated, internal, _and_ external tests (via a beta run announced on our public Slack).

This unfortunately wasn't enough to catch every issue that could come with migrating one's local storage to the latest format that the 3.5 app relies on, and some users who were not on the latest encryption protocol prior to v3.5 have opened the app to a blank screen, or 'Missing Keys' errors.

We have since identified and fixed this issue, and we are awaiting further testing to deploy this fix to everyone. Your data is safe. We would like to apologize to everyone who was affected and the scare it may have caused you.

To ensure there are no other user is facing this kind of scary-looking issue when their storage structure is being migrated, we have added Bugsnag, an error reporting service, to the latest version of the web app. We have made sure that these reports are fully anonymized (we do not collect IP addresses, for example,) and have included a way to disable error reporting as well. To read more about what data is being sent, See [this article, paragraph 'Browser' under 'Sending diagnostic data'](https://docs.bugsnag.com/platforms/javascript/#sending-diagnostic-data)

# Opting out

To opt out of automatic error reporting, open the _Account_ menu, then look for the _Disable Error Reporting_ button at the bottom of the menu.

**Comment by rumpnado** [comment]
There doesn't seem to be a "Disable Error Reporting" button at the bottom of the Account menu. Can you please confirm whether this button/function should be available on Desktop or mobile versions? Opting people in by default is not appreciated, especially when the opt out function is not easily discovered.

**Comment by radko93** [comment]
@rumpnado bugsnag opt-out on mobile is a more complex task to accomplish because we have to out opt of 2 levels (native and JS) and sync this setting between those two environments, But we are committed to providing this feature in a future update. 
If there is no opt-out button on desktop you might be using an older version that does not include bugsnag.

**Comment by rumpnado** [comment]
You are correct, good sir. Found the setting after it updated. Thank you!

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
