### ISSUE TITLE
[Plus Editor] Selecting all text and then change font does not work

### ISSUE THREAD

**Issue by glenn-holmgren** [standardnotes/forum#1130]
**Describe the issue**
[Help Wanted] 
Extensions > Plus Editor > 

Ctrl + A then change font to whole page does not work.
I have to select portions of my note/page just to apply the intended font format.

Am I doing it wrong or does this extension needs some modification or its just a limitation.

I wish to have this features because I am transferring my notes from evernote (security risk) to standardnotes which contains application scripts/codes. And its format/design is dependent on a specific font.

Thanks all for your kindness... 💯

**Comment by JaspalSuri** [comment]
Hi @glenn-holmgren,

Thank you so much for reaching out to us and for providing those reproduction steps. I was able to successfully reproduce it on my end. I will create a report for the team to review. 

I would advise against using the Plus or Bold Editor for scripts, just in case any HTML tags get removed by the editor. You could use the Code Editor instead, which provides the option to highlight/format the syntax of the code in the body of the note according to the language selected at the bottom of the editor. You could then [create a theme](https://docs.standardnotes.org/extensions/themes) that uses a specific font and apply it to the desktop app.

**Comment by glenn-holmgren** [comment]
Wow! It worked! The format/design of my scripts showed up perfectly! 👍 
From now on I will use this for my scripts.
Thanks too for reporting this concern. It might help the other users too.

Thanks a lot for your guide! 🥇

**Comment by JaspalSuri** [comment]
You're welcome! I'm so glad to hear that! Thanks for the update. 😃

**Comment by JaspalSuri** [comment]
Hi @glenn-holmgren, we haven't been able to reproduce this issue in the current version of the Plus Editor in the latest stable and internal betas of the web apps. I am going to close this ticket; please let me know if you're still able to reproduce this issue or have any other questions!
