### ISSUE TITLE
Desktop/Web app freezes

### ISSUE THREAD

**Issue by jimnyo** [standardnotes/forum#1133]
**Standard Notes freezes in desktop app**
Periodically, SN freezes. The screen is visible w/the note, but cursor is inactive and there are red underlines scattered throughout the screen. Sometimes refreshing helps to get it going again, but sometimes I even have to close the tab and reopen it. See screenshot.

**To Reproduce**
Seems to happen when I:
1. work on a note
2. click on a different note to open and work on it
3. then it freezes

**Expected behavior**
I expected it to open the second note and work on it w/o any problems, like it used to.

**Screenshots**
gotta get a new one just realized the original had private info

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.6
 - Browser: Chrome 
 - Version 86.0.4240.183 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
n/a

**Additional context**
I think the red underlines may be coming from Grammarly

**Comment by jimnyo** [comment]
I THINK I FIXED IT! I didn't even realize Grammarly might be an issue until I wondered about the red underlines. I turned it off for Standard Notes and everything works fine now!

**Comment by JaspalSuri** [comment]
Hi @jimnyo,

Thanks so much for the update and for letting us know! 

I deleted the first version of your message that contained the screenshot that you provided. While several users might have a copy of it in their email, you can reach out to GitHub support to delete the image from their servers if you'd like.

**Comment by baptiste-grob** [comment]
Hey @jimnyo! Glad you got it fixed :) if you're working with sensitive/private data I would make sure to disable addons that are similar to Grammarly as they would have access to whatever you're typing and could potentially send your decrypted data to an unknown third party. 🙂
