### ISSUE TITLE
[Help Wanted] "pinning" tags?

### ISSUE THREAD

**Issue by dsclough** [standardnotes/forum#1134]
Is there any way to pin specific tags in the leftmost menu? Previously I was appending tags I wanted listed at the top with a "_". This worked for the web UI but not the mobile UI, and as of a few days ago the behavior has disappeared from the web UI. Is there any other way to achieve this?

**Comment by JaspalSuri** [comment]
Hi @dsclough,

Currently this isn't possible, other than using letters before the tags, such as `AAAtag` or `AAA.tag`. If you have the [Folders extension](https://standardnotes.org/extensions/folders) installed, you could drag tags into and out of the folder (`AAA` in this case). 

Another option is to create a [Dynamic/Smart Tag](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters) for the set of notes with certain titles or tags that you want to retrieve, but it might require a regular replacement.

> and as of a few days ago the behavior has disappeared from the web UI

I apologize for that; we're aware of a similar issue and have plans to fix it.

**Comment by dsclough** [comment]
Thanks! I discovered that using a period instead of the underscore has regained the desired effect.

![image](https://user-images.githubusercontent.com/7521806/98842485-470bd800-240f-11eb-9757-a6560b4df093.png)

**Comment by JaspalSuri** [comment]
That's great to hear! Thank you for letting us know. 🙂
