### ISSUE TITLE
Cannot Access Notes

### ISSUE THREAD

**Issue by longtimeuser1** [standardnotes/forum#1137]
**Describe the bug**
When opening the (recently updated) app on iOS / Apple iPhone 12, I am prompted to login. However, I have never created an account. I have used the app for several years without an account. Now I cannot access my notes because there is no way to bypass the login prompt. 

**To Reproduce**
1. Have any user that does not have an account try to open the app to access their notes. 

**Expected behavior**
I expect to open the app and see my notes, without being forced to login. 

**Screenshots**
![DF5EFCFC-FD4C-4823-B922-9248F27D1CB7](https://user-images.githubusercontent.com/74337192/98890716-d63ddd80-2459-11eb-9050-478fe2f96f78.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: Latest build of iOS
 - Browser iOS App
 - Version Latest Version

**Additional context**
Thank you for your help. I have thousands of important notes I need to retrieve.

**Comment by SCNate20** [comment]
Yes. WTF is going on?!

**Comment by arcanecode** [comment]
I just got in with no problem. Been in and out of it all evening with no issues.

Thanks,

    Robert

Robert C. Cain
Arcane Training and Consulting, LLC
Author: Pluralsight <https://www.pluralsight.com/authors/robert-cain>  | PACKT<https://www.packtpub.com/big-data-and-business-intelligence/sql-server-2016-reporting-services-cookbook> | Red Gate’s Simple Talk<http://arcanecode.red/>
Online:  arcanecode.me<http://arcanecode.me/> | @ArcaneCode<http://twitter.com/arcanecode> | LinkedIn<http://arcanecode.in/>

**Comment by longtimeuser1** [comment]
> I just got in with no problem. Been in and out of it all evening with no issues. Thanks, Robert 

This issue affects everyone using the latest iOS App build, who also don’t have an account/login. Maybe it’s working for you because you have an account?

**Comment by SCNate20** [comment]
Robert, are you the gentleman that posted the problem or are you with the
app?

Please see the attached picture. I’ve lost access to my passwords among
other data.

Nathan

**Comment by radko93** [comment]
Hi, we had a bug introduced in version 3.5.5 that unnecessarily asked users for credentials. We released a new version already on Android that fixes this, iOS update is pending Apple approval. I’m really sorry for the troubles this caused. Please do not uninstall the app. I recommend setting up an account to backup your notes after the update is released.

**Comment by SCNate20** [comment]
How do we set up an account and what do you suspect the timetable is on the
iOS review?

**Comment by radko93** [comment]
With the last couple of releases it took less than 24 hours for the update to be approved. So it's 12 hours left if there is no delay from Apple.

**Comment by SCNate20** [comment]
Great. Thanks for the update.

**Comment by mobitar** [comment]
iOS app is presently "In Review".

**Comment by JaspalSuri** [comment]
The update with the fix (v.3.5.7) should be available for iOS now.

**Comment by SCNate20** [comment]
Yes. Got it last night. Thank you for the update. The follow up service was
exceptionally good.

**Comment by JaspalSuri** [comment]
We're glad to hear that! Thanks for the kind words! Please let us know if you ever have any other questions.

**Comment by brycewray** [comment]
I **do** have an account and password (paid user — 5-year plan), when I try to open the app on iPad, am getting a screen headed "Storage Update" that wants me to enter my "application passcode," but it refuses to take the only password I have for Standard Notes. Fortunately not (yet) seeing this problem in either macOS app or on the iPhone. Upgraded to the most recent version on iPad, but still same issue. Thoughts? Help? Thanks.

**Comment by JaspalSuri** [comment]
Hi @brycewray,

Thanks for supporting us by subscribing to Extended! 🙂 

If the notes that appears on your Mac and iPhone are up-to-date, you may want to try deleting and reinstalling the app. 

If that doesn't work, please delete the latest backup of your phone via iCloud through the [steps provided in Apple's official support document](https://support.apple.com/guide/icloud/remove-a-backup-from-icloud-mm122d3ef202/icloud) and then try reinstalling the app once more. It would be ok to keep any future backups of your device after that, of course. 

Please let me know what else you've tried so far so that way I can better assist you.

**Comment by brycewray** [comment]
@JaspalSuri I appreciate the response. Wanted to wait until I heard from you folks before I tried deleting/reinstalling, just to make sure there wasn’t something else I should try first. Have now deleted/reinstalled on the iPad, and everything seems to be working fine. Thanks!

**Comment by JaspalSuri** [comment]
@brycewray now that I think about it, I should have requested your device's details so that way we could look into the error logs for any potential insights towards a fix for the issue you were experiencing. I figured that since you had an account, it would be safe to reinstall the app and remove the obstruction from your workflow. 

Thank you so much for letting us know that it's working as expected again!
