### ISSUE TITLE
Unable to pop-up Stripe window after changing plan

### ISSUE THREAD

**Issue by cconmy** [standardnotes/forum#1141]
**Describe the bug**
After changing plan from payment screen unable to get stripe pop-up to spawn again

**To Reproduce**
1. Starting from: https://standardnotes.org/extensions
2. Select upgrade for "$9.99" plan
3. Enter email as new users press enter
4. Select Credit Card
5. Close Stripe Pop Up with X
6. Select "View other purchase options"
7. Select "1 Year" radio button
8. Stripe window does not reappear even if you try to use "Stripe checkout window has opened. If on mobile, press here to open manually."
 - Note there also are no warnings in the browser for blocked popups either.

***Work-around***
I was able to select and pay for the plan I wanted by returning to the https://standardnotes.org/extensions page.

**Expected behavior**
Respawn of Stripe checkout window

**Screenshots**
![image](https://user-images.githubusercontent.com/12626157/99909775-11d57480-2cb0-11eb-84b1-98229659e8ad.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 LTS
 - Browser: Firefox
 - Version: 83.0

**Additional context**
Note Privacy Extensions installed:
- uBlock Origin
- Privacy Badger

**Comment by JaspalSuri** [comment]
Hi @cconmy,

I apologize for the late reply. Thank you so much for taking the time to report this, especially given that the issue adds more friction to the transaction process, with the Black Friday sale currently in place.

I reported it to the the team yesterday and hopefully we'll be able to fix it soon (currently they're focused on adding more improvements to the apps and making sure the server is ready for the sale period).
