### ISSUE TITLE
[Feature Request] Add a right-click context menu in the notes list

### ISSUE THREAD

**Issue by ganomi46** [standardnotes/forum#1142]
When I left click on notes, I should get copy, duplicate, delete, etc. Fix it.

**Comment by clough-fyi** [comment]
"Fix it" is a bit rude?

It's not broke, minimal options is the point of this app right. 

But if it is coming in 4.0 then that's lovely.

**Comment by myreli** [comment]
We now have context menu in notes:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/17554234/219060955-029ee108-ba2f-4df3-96ff-f48db07a344b.png">
