### ISSUE TITLE
app does not sync unless logoff-delete and resync

### ISSUE THREAD

**Issue by Lwnzhn** [standardnotes/forum#115]
edit a few notes in web app, those notes were removed/hidden in app.
After deleting local data, sync on android is good again.

**Comment by mobitar** [comment]
Hmm strange. So you edited a note in the web app, saw that it synced properly, opened your Android app, and the changes weren't reflected—do I have that right? Did you see any error messages, or have a shaky network connection?

**Comment by wginsberg** [comment]
I'm having the same issue described above. My notes only sync between my devices when I sign out and sign in again.

FWIW I'm self hosting https://github.com/tectiv3/standardfile
The server output looks ok I think, it spits out these messages every few seconds:
`2018/04/23 02:56:08  202 [POST] "/api/items/sync" 3.278942ms 96`

**Comment by mobitar** [comment]
App versions?

**Comment by wginsberg** [comment]
OSX: Version 2.1.28 (2.1.28)
Android: 2.1.2

**Comment by mobitar** [comment]
Can you describe what you're seeing?

**Comment by mobitar** [comment]
Have you changed your password recently? Note that updates aren't refreshed immediately, but every 30 seconds. Does the note appear when you do a manual refresh, via "Refresh" in lower right corner on Mac, and pull to refresh on android?

**Comment by wginsberg** [comment]
I made a fresh account, since I'm just playing around with a self hosted instance of standardfile. Yes, I waited for several minutes to see if it would sync, and no, the manual refresh didn't do anything.

**Comment by mobitar** [comment]
Is this reproducible? Or was it just that one time? I have no way of knowing if this is a server or client issue at this point. If it's reproducible, can you try creating an account on our server and see if the same thing happens?

**Comment by wginsberg** [comment]
Happens without exception on my own server.
Tried with your servers and everything works fine.
So I guess it could be a problem with the go standardfile implementation then? It's just really strange to me that syncing still works on sign in.

**Comment by mobitar** [comment]
Might have something to do with the sync token. That's the only thing that gets wiped after a sign out. You can try to replicate this if you go into the developer console in the desktop app (same as Chrome shortcut), Application -> Storage -> Local Storage, then find the syncToken row and delete it. That will perform a fresh sync. If that works, then you know it's something to do with that.

**Comment by mobitar** [comment]
> half of the body of a note was missing

Given it's encrypted, the server does not have the ability to modify contents. So what you're getting back is what the server has, which means the server is not receiving your latest updates. Perhaps it's saving that's the issue, not retrieving?

**Comment by eurbon** [comment]
Can confirm. I just login via web app and see my synced notes. If I refresh the page or close tab and open the page again, all my synced data is lost until I do relogin & resync. So basically web app is unusable.

Windows app doesn't have a search function embedded (I mean search for text throughout an opened page, basically CTRL+F). The only search function is which scrapes all data contents in all files and then puts matched files in the list.

**Comment by mobitar** [comment]
@eurbon can you check the javascript console and see if there are any errors occurring?

**Comment by eurbon** [comment]
I already switched to evernote. Just create a new user and try reproducing the isue with google chrome

**Comment by mobitar** [comment]
Thanks Eimantas. Appreciate you stopping in.
