### ISSUE TITLE
Sheets extension does not expand to window size

### ISSUE THREAD

**Issue by theontho** [standardnotes/forum#1150]
**Describe the bug**
Sheets extension does not expand to window size.  Same with shrinking window size

**To Reproduce**
I ran into this by opening a sheet note I have made previously

**Expected behavior**
Sheets expand to window size properly

**Screenshots**
<img width="745" alt="Screenshot 2020-11-25 164831" src="https://user-images.githubusercontent.com/22130/100295452-7f96d000-2f3e-11eb-859b-1d03afdcd7b8.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - App
 - Version 3.5.6

**Comment by theontho** [comment]
Restarting the app and sheets were updating their size properly, still this can happen so it's a bug :)

**Comment by JaspalSuri** [comment]
Hi @theontho,

It looks like the margin resizers aren't locked. You can expand the width of the editor to the desired amount or snap it to the right edge of the application's window. From there, click on **Options** button (located beneath the tags text field) and click on **Margin Resizers**. This should prevent your cursor from unintentionally dragging the edges of the editor and adjusting the margins. 

[Here's a video](https://drive.google.com/file/d/1rv6hqiOGtM6q6MRvARNtOBQlaoYVjaSG/view?usp=sharing) on what utilizing that option looks like.
