### ISSUE TITLE
[Help Wanted] Listed options menu appears twice

### ISSUE THREAD

**Issue by kfiresmith** [standardnotes/forum#1154]
**Describe the bug**
After installing the listed plugin, the menu appears twice.

**To Reproduce**
1. install listed plugin

**Expected behavior**
Listed plugin action menu should only appear once

**Screenshots**
![image](https://user-images.githubusercontent.com/8343629/100519338-42605700-3165-11eb-9a22-9f9dbe6de84b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Google Chrome latest
 - Version Std Notes AppImage latest

**Comment by JaspalSuri** [comment]
Hi @kfiresmith,

Do you see two extensions named **Listed** in the **Extensions** menu button? If so, use the **Actions** button of a note that doesn't contain any sensitive info to publish the note to both Listed blogs and check to see which one is the blog that you didn't intend to create. I will check in with the team to see which extension should be uninstalled.

**Comment by JaspalSuri** [comment]
Hello again,

In the **Extensions** menu, under the **Actions** section where the **Listed** extensions are installed, you can click on the button containing the horizontal set of dots, and then click on **Rename**. This will help make the aforementioned testing process easier by helping you distinguish between the two blogs in the Actions menu.

![image](https://user-images.githubusercontent.com/44656000/100850517-c30aa600-3438-11eb-9517-d7956c05c1e5.png)

**Comment by kfiresmith** [comment]
Hi @JaspalSuri  - I discovered after filing this that the Listed extension somehow installed twice.  IMO that shouldn't be possible.  I uninstalled one copy of the extension and all is well now, but it does seem odd that two copies of an extension could be installed.

**Comment by JaspalSuri** [comment]
> IMO that shouldn't be possible.

This is what allows users to maintain multiple Listed blogs. 😃 

> I uninstalled one copy of the extension and all is well now, [...]

I'm glad to hear that!
