### ISSUE TITLE
How do you add a launch shortcut for the AppImage?

### ISSUE THREAD

**Issue by pupscout** [standardnotes/forum#1155]
Hi there, I have downloaded the appimage file to use the Standard Notes desktop Linux application. It works nicely but I have one question... is it possible to register the application, so it can be launched quickly - either via an app launcher, or by pinning/favorite-ing to the sidebar/dock? 

Right now I have to open my file explore and navigate to the appimage file every time I want to launch it. It would just be more convenient if I could pin it to my dock like other applications. :-) I've tried creating my own .desktop file by hand, but I can't seem to get it working consistently. And while my .desktop file was working, it still did not bestow the ability to pin the app.

Thanks!

**Comment by johnny243** [comment]
Hey @pupscout, there are several ways to integrate `.appimage` files into your application launcher. For example, you can use [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) to automatically create a `.desktop` file whenever you run a `.appimage` file (it will prompt you if you just want to run the file or if you'd like to integrate, then run).

Let me know if that helps!

**Comment by patgadget** [comment]
I install mine in ubuntu using the ubuntu software icon, and i can easilly start it without any issue from the application manager.
i am not a super tech savy, and every things work as normal, i don't have to use any file explorer.
PatGadget

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
