### ISSUE TITLE
Stuck on "Generating Keys"

### ISSUE THREAD

**Issue by naioboot** [standardnotes/forum#1158]
Today, when I tried to use the web app from my Brave browser I've got a warning that saving was disabled and I had to restore encryption keys.
Now I'm in a page with this text:

> Authentication Required
> Restore Keychain
> We've detected that your keychain has been wiped. This can happen when restoring your device from a backup. Please enter your account password to restore your account keys.

However, when I enter my password nothing happens, the app is stuck with the "Generating Keys" message.

How can I recover my notes??

**Comment by JaspalSuri** [comment]
Hi @naioboot,

I just wanted to double-check on this issue since users sometimes accidentally close them. Are you still experiencing this issue? If not, can you log into the [legacy web app](app-legacy.standardnotes.org) in the meantime and contact us with a link to this thread at help@standardnotes.org?

**Comment by naioboot** [comment]
Hi Jaspal,

I closed the issue in Github because I contacted Standard Notes help email
and I thought it would be better to have a single contact for it.

The issue is solved by clearing cookies, cache and navigation data.

Thank you,



Missatge de Jaspal Suri <notifications@github.com> del dia dv., 4 de des.
2020 a les 7:50:

**Comment by JaspalSuri** [comment]
Thank you so much for letting us know! I'm glad to hear that it was resolved by doing that; thanks for sharing that here for anyone else who might run into a similar issue.
