### ISSUE TITLE
Feature Request: import from other apps, like ColorNote

### ISSUE THREAD

**Issue by ardentmusician** [standardnotes/forum#116]
Would it be possible to be able to import my notes from other apps, like ColorNote on Android?

I am totally going to use this to replace ColorNotes, but there are a couple of features that were really great that would be cool to have:

1.  The ability to set a color for the note.  It seems like a little thing, but was really rather useful.
2.  The ability to create checklists in addition to simple text notes.  This was invaluable.

These seem like features that would fit well in the free version.

**Comment by mobitar** [comment]
Hi Hubert, please check out some of these extensions, which do the things you mentioned: https://standardnotes.org/extensions

You might also read our Longevity Statement, which explains a little of why we choose to keep the core application as simple as possible: https://standardnotes.org/longevity

**Comment by morvenwestfield** [comment]
Hi,

I'm also looking to import from other apps. I have notes from Toodledo. It will only export as a .csv file.

**Comment by mobitar** [comment]
We don't have a custom importer for that I'm afraid. Only import tools are present here: https://dashboard.standardnotes.org/tools
