### ISSUE TITLE
All my extensions stopped working [Help Wanted]

### ISSUE THREAD

**Issue by MarcSousbie** [standardnotes/forum#1162]
**Issue**
On the Linux desktop app, when I open a note that I made with an editor extension, I get the message "There was an issue loading [extension]. Reload"
Same thing if I make a new note and try to switch editors.
The reload button does nothing. Switching back to the default editor works.
The theme extension is not applied either.

**Desktop**
 OS: Manjaro Linux

**Standard Notes desktop app version**
3.4.10 (installed from the AUR).

Is there anything I can/should do to fix this?

**Comment by JaspalSuri** [comment]
Hi @MarcSousbie,

I'm sorry to hear that; thank you for providing all of those details! I'm afraid that you'll have to switch away from the package provided by AUR, as the latest version of the official package is v3.5.11. Before doing so, I would recommend signing into [our legacy web app](http://app-legacy.standardnotes.org/) and exporting a backup of your encrypted and decrypted data via the **Account** menu button as version 3.5.X (of our apps) contains several significant changes and updates. 

[Here is the link](https://github.com/standardnotes/desktop/releases) that will contain the latest version of our desktop app at the top. You can reveal the list of packages by clicking on the triangular button next to the word **Assets**. If you accidentally install an older version of the desktop app, it will allow you to update to the latest version of the app. 🙂  If the update fails to work, you may need to manually update the app via the releases page. 

Please let me know if this helps resolve the issue. Thank you for reaching out to us!

**Comment by MarcSousbie** [comment]
Hi @JaspalSuri,

Thank you for your answer, I followed your instructions and everything works fine now! I installed standard-notes-3.5.11-linux-x86_64.AppImage.

**Comment by JaspalSuri** [comment]
I'm glad to hear that! Thank you for letting us know!
