### ISSUE TITLE
[Help Wanted] Is there a way to make a url link open a webpage directly without having to cut and paste it?

### ISSUE THREAD

**Issue by patgadget** [standardnotes/forum#1173]
**Clickable WebLink in notes**
Is there a way to make a url in a note to be clickable?
let say i have in my notes this link
nothing happen if i click on it, (oops, it automaticly created a link)
https://www.google.com/search?channel=fs&q=wow

In this github editor, i can create a link instead:
[https://www.google.com/search?channel=fs&q=wow](https://www.google.com/search?channel=fs&q=wow)
And now it is clickable

But i don't know how to do this in Standard Note (plain editor)
is it only available in other editor?

Thanks

**Comment by JaspalSuri** [comment]
Hi @patgadget,

The Plain Editor uses the web-based text editor that your OS provides so it won't hyperlink text. You would need to use the editors included in [Extended](standardnotes.org/extensions) or the ones [maintained by the community](https://github.com/jonhadfield/awesome-standard-notes#editors). Extensions can be installed on the [desktop](standardnotes.org/download) or [web](app.standardnotes.org) apps through the **Extensions** menu. 

Please let me know if you have any additional questions!
