### ISSUE TITLE
Extension for Project?

### ISSUE THREAD

**Issue by patgadget** [standardnotes/forum#1174]
**Is there and extension that exist for Project Management?**

Something dedicated to handling project
Project list, project task, project subtask?

**Additional context**
I am a fan of GTD (Getting things done) by David Allen and i was wondering how to implement it with Standard Notes

Thanks
PatGadget

**Comment by JaspalSuri** [comment]
Hi @patgadget,

Currently there isn't, but you can assign tags to notes that are using the [Task Editor](https://standardnotes.org/extensions/task-editor) to create a GTD-like system; the tags could be nested in [folders](https://standardnotes.org/extensions/folders) for further organization. For example, you could create the tags: `GTD.Inbox`, `GTD.Projects`, and `GTD.Someday` and assign them to notes using the Task Editor, or click on the tags and then create a new note and it will be assigned the correct tag. You could assign a single note to a tag, or if you have a project, you can assign multiple notes to the tag. 

![image](https://user-images.githubusercontent.com/44656000/103086501-a7a73c80-4599-11eb-8b5a-6aedc64c35f3.png)


I hope this helps! Please let me know if you have any additional questions.

**Comment by patgadget** [comment]
Thanks, i will do that.
