### ISSUE TITLE
[Help Wanted] Is Standard Notes Compatible with sync.com for files saving?

### ISSUE THREAD

**Issue by patgadget** [standardnotes/forum#1175]
**Describe the issue**
I am using sync.com for files instead of dropbox, i am wondering if the FileSafe Extension would work with this site?

sync.com is a Canadian company that already encrypt the files.
Any one know if they are compatible?

Thanks
PatGadget

**Comment by JaspalSuri** [comment]
Hi @patgadget,

I'm afraid that Sync.com currently doesn't provide an API that other services can use.
