### ISSUE TITLE
[Help Wanted] Is there a way to create a un-encrypted share Link on a specific Note?

### ISSUE THREAD

**Issue by patgadget** [standardnotes/forum#1176]
**Describe the issue**
Is there a way to create a Not Encrypted Share link to give away to friends.
let say that i want to share a note.
is there a way to do it in Standard Note?

Thanks for your help
Pat Gadget

**Comment by patgadget** [comment]
Thanks, i found out that i could add the Extension "Listed" and post a blog
and also this gave me the possibility to post to a private link

**Comment by JaspalSuri** [comment]
I'm glad that you were able to locate the solution! Thanks for letting us know!
