### ISSUE TITLE
Secure Spreadsheets - basic usage questions

### ISSUE THREAD

**Issue by X1SDNA** [standardnotes/forum#1181]
Hi - I can't seem to find any formula buttons anywhere. For instance, where is the sum function? Pretty sure I've checked every button and right click menu...

Also, inserting rows and columns doesn't work either.

I'm on Win 10.

Thoughts appreciated.

**Comment by X1SDNA** [comment]
Ok understood, thanks Jaspal.

I'm fully assimilated to Standard Notes Pro now. It is a great product. Look forward to seeing the ongoing development as time rolls on.

**Comment by JaspalSuri** [comment]
Hi @X1SDNA,

I'm glad to hear that! Thank you for taking the time to report issues as you encounter them.

**Comment by JaspalSuri** [comment]
Hi @X1SDNA, we've decided to go ahead and [add the insert column/row feature](https://github.com/standardnotes/secure-spreadsheets/pull/39) as it doesn't include any breaking changes. 🙂
