### ISSUE TITLE
Font becoming very small on iphone app

### ISSUE THREAD

**Issue by suppyoyo** [standardnotes/forum#1182]
font size becomes very small despite changes in system size. Tried restarting phone and reinstalling app but to no avail. 

![DF0E66E2-776D-4409-954B-A2068CA3B4E4](https://user-images.githubusercontent.com/41885178/103323438-d3389400-4a7d-11eb-839d-969cbbaef645.png)

**Comment by x218935** [comment]
Same with me. Any fix??

**Comment by tonydunn** [comment]
Same here as of first start this morning, font size is much too small on iPhone after the upgrade to 3.5.14

**Comment by nekothreesixty** [comment]
Mine too! Hallllp!

**Comment by JaspalSuri** [comment]
Hi everyone! This is fixed (https://github.com/standardnotes/mobile/commit/178d999ee1a43adefeaad2676b6d51fdabca6a87) and will an update will be released within a few days.

**Comment by TheodoreChu** [comment]
This is fixed in `v3.5.15`: https://github.com/standardnotes/mobile/releases/tag/3.5.15
