### ISSUE TITLE
Custom SEO Title and Descriptions

### ISSUE THREAD

**Issue by afar1879** [standardnotes/forum#1185]
Hello, 

Is it possible to add custom SEO titles and descriptions to Listed posts? 

I was hoping to create titles that are different than the visible title on the page to fully optimize the SERP snippet. It also looks like the meta descriptions default to something like "title / date / opening text" -- I was hoping to remove the title and date if possible.

Thanks in advance!

**Comment by JaspalSuri** [comment]
Hi @afar1879,

I'm afraid that this currently isn't possible. Please [visit this link](https://docs.standardnotes.org/listed/options) on per-post options that are available for Listed (if you haven't already).

**Comment by afar1879** [comment]
@JaspalSuri No problem, I was just curious. Thanks for the info!
