### ISSUE TITLE
[Help Wanted] How to configure Correctly the Webdav in the filesafe Extension

### ISSUE THREAD

**Issue by patgadget** [standardnotes/forum#1186]
**Describe the issue**
I can't seem to attach a file to a Standard Notes.
i did create a Webdav connection into my server side
i have the user name and password
but: in my server, it says that i need to connect to the 2078 port, and i have no ability to set this into filesafe.
I also can ENABLE or DISABLE DIGEST AUTHENTICATION not sure what to set this to?
![image](https://user-images.githubusercontent.com/1461231/103448281-5962ff00-4c65-11eb-90db-f47efbd95c32.png)

i  try 
Server:  myserver.com, myserver.com:2078
Username:  username, username@myserver.com
Password: mypassword
Directory: "", "/correct_directory/username"

and on the Standard Notes side, i created a Key and Integration
The only feedback that i have when i try to attach a file is : Error Uploading File, it would help if i would know a little more ;-)

Any idea?

Thanks

![image](https://user-images.githubusercontent.com/1461231/103448655-94b3fc80-4c6a-11eb-855f-97805c0240ff.png)

![image](https://user-images.githubusercontent.com/1461231/103448420-74cf0980-4c67-11eb-806d-346194742abf.png)

**Comment by JaspalSuri** [comment]
Hi @patgadget,

I'm afraid that we currently don't provide dedicated technical support for WebDAV (as each setup is usually unique), but one thing that might help you, if another user comes across this thread, is if you click on the menu bar/button > View > Toggle Developer Tools > Console and then attach a screenshot of whatever you see highlighted in red.

**Comment by patgadget** [comment]
Ok thanks,
well this is the list of error that i can see that related to me trying to save a file
but i think that the first one is the most important as it looks like the extension itself.


DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:45653/Extensions/org.standardnotes.file-safe/dist/filesafe-js/EncryptionWorker.js.map: Unknown error

Then i got a bunch of other error regarding EncryptionWorker (that looks normal if it did not even load properly !)
EncryptionWorker.js:4280 Request error: {error: {…}}error: message: "Could not save item. Please verify your integration."

Thanks

**Comment by BobWs** [comment]
Did you open and forward port 2078 in your router? FileSafe only works if it has access from the outside.

**Comment by myreli** [comment]
Since [FileSafe is deprecated](https://standardnotes.com/blog/deprecation-notice-filesafe) and this issue is unlikely to receive more interaction I'm closing it. [Files are now a native](https://standardnotes.com/blog/introducing-encrypted-file-storage-with-automated-backups) feature through encrypted storage. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
