### ISSUE TITLE
Feature request: Honour creation date when importing notes

### ISSUE THREAD

**Issue by a-lagopus** [standardnotes/forum#119]
When using the https://dashboard.standardnotes.org/tools, would be great for it to see either the first line of the note in YYYYMMDD format, or pick it up from the file name, i.e. YYYYMMDD.txt would set the imported note to be at that date.
So far I couldn't make it work and I'd like to import my notes from another app with respective dates.

**Comment by mobitar** [comment]
Hmm, no way to do that automatically. But if you insert "created_at" in the resulting JSON file the import will pick that up and respect it.

**Comment by a-lagopus** [comment]
Thanks, that works.
