### ISSUE TITLE
Backups are made with every application unlock

### ISSUE THREAD

**Issue by chairmantheboring** [standardnotes/forum#1190]
**Describe the bug**
Backups are made with every passcode unlock, even if one was made under a minute prior. 

**To Reproduce**
1. Set a passcode.
2. Lock and unlock the application a few times.
3. Open the local backups folder to see new backups.

**Expected behavior**
Backups are only made once daily, [according the help article on making backups.](https://standardnotes.org/help/14/how-do-i-create-and-import-backups-of-my-standard-notes-data)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: AppImage
 - Version 3.5.11

**Comment by JaspalSuri** [comment]
Hi @chairmantheboring,

Thank you so much for taking the time to report this issue! I was able to reproduce it and will let the dev team know. I will get back to you once it's fixed (or discover that it's a new feature). 🙂
