### ISSUE TITLE
Unable to sign in to the app without entering previous password

### ISSUE THREAD

**Issue by meaganmargaret** [standardnotes/forum#1191]
**Describe the issue**
I am continuing to get the following warning:  "Your account password is required to recover an encryption key"

But, it is asking for an old password (11/4) that I don't recall what it is as I changed my password in December, and until yesterday, everything was fine.

NOTE:  this issue occurs in my cellphone (a motorola running android 10), on any desktop that is running Standard Notes, Mac or Windows.  If I just ignore this warning, and click cancel, it just goes away.  However, if I enter my current password, it gets rejected!

**To Reproduce**
1. Logout
2. Login with current password

**Expected behavior**
Normal login with no error message or request for an old password

**Screenshots**

<img width="552" alt="image" src="https://user-images.githubusercontent.com/18254735/103543790-f08da980-4e53-11eb-9604-5177e00fd7e5.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Firefox (this issue has nothing to do with Firefox)
 - Version 84.0

**Comment by JaspalSuri** [comment]
Hi @meaganmargaret,

I'm sorry to hear that. Can you try signing into our [web app](app.standardnotes.org) and let us know if asks for your password there as well?

(Only proceed with the following if the suggestion above works.) If it works as expected there, you can clear the Android app's data/storage. On the desktop apps, you can sign out, click on the menu button/bar > View > Toggle Developer Tools > Application > Clear Storage > Clear Site Data and then sign in again.

**Comment by meaganmargaret** [comment]
So, your web app corresponds to:  https://github.com/standardnotes/forum/issues/app.standardnotes.org. and it doesn't open in Firefox or Chrome.  I get "Not Found".   I'm on a Mac, btw.  I tried downloading the URL to see if it would open as an app, and it would not.

Also, things have gotten worse.  On my cell, I deleted the app, rebooted and then re-installed.  Now I can't use the app at all.  It will not accept my password at all, so Standard Notes on my cell is completely unusable.

**Comment by JaspalSuri** [comment]
I apologize for that. Please try [this link](https://app.standardnotes.org) instead. https://app.standardnotes.org

**Comment by meaganmargaret** [comment]
On my android cell, that doesn't work.  It still won't let me login.  On my desktop app, that also didn't work - as soon as I attempted to login, I got the password prompt for 11/14 again.  Also on your web app, which now works, I get the password prompt for 11/14, just with the desktop apps and then I cancel and it goes away.

What about this - can you just reset my account to zero and I will rebuild all my notes from scratch?  I do have them backed up in another format (mainly because I had to have that ready just in case).

**Comment by meaganmargaret** [comment]
On the cell, standard notes is completely useless to me, btw.

**Comment by meaganmargaret** [comment]
Please tell me how to get rid of this app on everything, please!  I'm at the point of not wanting even a shred of it on anything, especially my cell phone.

**Comment by meaganmargaret** [comment]
It's pretty apparent to me that somehow you have local storage which is hidden from me, and uninstalling the app doesn't remove it.  I want to know where that storage is.  Where is it?

Or is the problem with my account on your website presence?  Why can I login with the desktop apps and your web app but not with my cell????

**Comment by JaspalSuri** [comment]
Hi @meaganmargaret, 

I'm sorry to hear that you're not able to sign into the web app. 

Here's what I would suggest based on your requests:

### Import a backup and create a new account

1. Open either of the desktop apps. 
2. Click on the **Account** menu button.
3. Click on the [radio button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio) next to the word **Decrypted**. 
3. Click on the **Download Backup** and save it somewhere you can recall later.
2. Open the [web app](https://app.standardnotes.org) once more. 
2. Click on the **Account** menu button.
3. Click on the **Import Backup** button, locate, and upload the Decrypted backup that you've saved earlier. 
3. After the import is complete, click on the **Account** menu button again, if needed.
4. Click on **Register** and create a new account. The notes that were imported into in the web app will be uploaded/synced to your account. Please wait for that process to complete as it may take anywhere from a few seconds to a few minutes.
2. Click on the **Account** menu button again.
3. Click on **Sign Out**.
2. Click on the **Account** menu button again.
3. Click on **Sign In** and sign in (with the **new** account). 
4. Confirm that everything was synced and saved before continuing. 

### How to remove the locally stored data on Android
1. Locate the app in the app drawer.
2. Press and hold the app's icon.
3. Tap on **App Info**.
4. Locate the options to delete the storage (not just the cache).
5. Do not reinstall the app.
5. Relaunch the app.
6. Sign in with the new account's credentials. 

For the desktop apps, simply sign out of your old account and sign into the new account. You can click on the menu bar/button > Backups > Open Backups Location and remove the locally stored backups on both your Mac and Windows PC.

To initiate the process of deleting your old account, please visit [this page](https://standardnotes.org/reset) and provide the email address of the old account. 

Please let us know if you have any additional questions!

**Comment by meaganmargaret** [comment]
Well, most of that is already done, because once I realized the app was screwed up, I did most of that.

I have the decrypted backup.  My question is that I can't re-create another account with the same email address, can I?  I thought I was limited to one email address per account?

**Comment by meaganmargaret** [comment]
Why can't you just reset my account?

**Comment by JaspalSuri** [comment]
>My question is that I can't re-create another account with the same email address, can I? I thought I was limited to one email address per account?

That's correct, you wouldn't be able to without resetting the account. I mistakenly assumed that you had another email address available and apologize for that.

> Why can't you just reset my account?

I'm afraid that I personally don't have the ability to do that (and we can't just reset anyone's account without some form of verification). To initiate the process of deleting your account, please visit [this page](https://standardnotes.org/reset). If you're having trouble with this, please email help@standardnotes.org from the email address that you're using with Standard Notes.

**Comment by meaganmargaret** [comment]
That didn't work.  The web app has data in it, so when you import that data, you're screwed and it just repeats the same process all over again.  There's no way to delete the data on the web app, so it just gives you the same error all over again

**Comment by meaganmargaret** [comment]
It says "this e-mail is already registered"

**Comment by meaganmargaret** [comment]
So, I do have other e-mail addresses available, but this is my main e-mail address and I really really don't want to not use it.  So, if I ask them to delete my account, can I recreate it, or is that it and I can never re-use that account ever again?

**Comment by meaganmargaret** [comment]
I mean, this app is useless if every time I need to use it, and something happens and it goes south, I can't re-use my same email address.  Is that the way this works????

**Comment by JaspalSuri** [comment]
> So, if I ask them to delete my account, can I recreate it, and use it again, or is that it once used I can never re-use that email account ever again?

You can delete the account and sign up for a new one with the same email address. You don't have to email us, you can enter it into [the form on this page](https://standardnotes.org/delete), confirm the deletion of the account via the email that you'll receive in your inbox, wait for that to process, and then sign up for a new account with the same email address.

**Comment by meaganmargaret** [comment]
So, in desparation, I tried another email address, and again I got yet ANOTHER error:

Unable to write to local database. Please restart the app and try again. ?????

**Comment by JaspalSuri** [comment]
> I now have tried both the desktop app and your web app and it won't import my decrypted backup! Why?

What exactly happens when you import the backup? Does it provide an error message? Please click on the menu bar/button > View > Toggle Developer Tools > and then click on the Console tab. Send us a screenshot of any errors that you see in red.

**Comment by meaganmargaret** [comment]
<img width="1326" alt="Screen Shot 2021-01-04 at 11 36 14 AM" src="https://user-images.githubusercontent.com/18254735/103572218-154c4600-4e81-11eb-9090-7c76760c565a.png">

**Comment by JaspalSuri** [comment]
Thanks for providing those screenshots! I'll forward this over to our dev team and get back to you ASAP.

**Comment by myreli** [comment]
Seems like this issue was solved and is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
