### ISSUE TITLE
Sync Unreachable from Web app (self-hosted)

### ISSUE THREAD

**Issue by sergio-ns** [standardnotes/forum#1192]
**Describe the issue**
I have a fully self-hosted Standard Notes installation via docker containers (sync, web and filesafe although I can't get this last one to work with my WebDav but this is a different story).

It currently works perfectly from mobile (both Android and iOS) and Windows desktop: **all notes get synchronized nicely across all devices .**

**But I can't get the web app to work** (actually it did work initially but I've changed some components in the deployment, added File Safe and now it doesn't, so, let's assume it never worked).

**To Reproduce**
1. Open the browser to the domain where the standard notes web server is running (e.g. https://sn.mydomain.com)
2. The application page opens
3. Click on the "Account" button located at the bottom left: the sign-in / registration panel opens
4. Click on Sign-in
5. Enter the credentials (email, password)
6. Click on Advanced Options
7. Enter the Sync Server Domain name (e.g. https://sn_sync.mydomain.com)
8. Click on "Sign In"
9. The message "Generating Login Keys" appears for a brief moment
10. The login panel closes
11. The "Account" button label at the bottom left turns red
12. By clicking on that button again, the login panel opens and shows a  red text box saying: Sync Unreachable, Hmmm...we can't seem to sync your account. The reason: Unknown Error". The "Syncing" icon spins forever

**Expected behavior**
After step 8 the login panel should close and the notes should start synchronizing.
I just performed the same procedure in the Windows desktop app and it went flawlessly.

**Screenshots**
[See here](https://gyazo.com/ba0ca44eaaae7ea2c1aa4bd19a5f7864)

**Desktop (please complete the following information):**
 - Windows 10
 - Tried with Firefox, Chrome and Edge

**Additional context**
standard notes web is deployed in a docker container with the following command:
`docker run -d -p 3001:3001 --name "standard_notes_web" --env-file=standard_notes_web_env --network=mynetwork --restart always standardnotes/web:stable`
The env file used by this container is:
```
RAILS_ENV=production
PORT=3001
WEB_CONCURRENCY=0
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true
SECRET_KEY_BASE=[my secret key]
APP_HOST=https://sn.mydomain.com

EXTENSIONS_MANAGER_LOCATION=extensions/extensions-manager/dist/index.html
BATCH_MANAGER_LOCATION=extensions/batch-manager/dist/index.min.html
SF_DEFAULT_SERVER=https://sn_sync.mydomain.com

# Datadog
DATADOG_ENABLED=false
```

Question on the web server SECRET_KEY_BASE variable: must this match the namesake env variable of the syncing server?

Thanks
S.

**Comment by mobitar** [comment]
The only difference with our web app is that it will require that your sync server be behind HTTPS. If you're using http:// it won't work.

**Comment by sergio-ns** [comment]
> 
> 
> The only difference with our web app is that it will require that your sync server be behind HTTPS. If you're using http:// it won't work.

Hi Mo,
I'm using https everywhere with my registered domains for which I generated Let's Encrypt wild card certificates delivered by my reverse-proxy (Traefik).
Am I overlooking something?
Thanks
S.

**Comment by mobitar** [comment]
I can potentially help you more if I knew your server URL. Feel free to email it to me.

**Comment by mobitar** [comment]
Problem seems to be with your syncing server blocking syncing requests:

Access to XMLHttpRequest at 'https://your.server/items/sync' from origin 'https://app.standardnotes.org' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by sergio-ns** [comment]
> 
> 
> Problem seems to be with your syncing server blocking syncing requests:
> 
> Access to XMLHttpRequest at 'https://your.server/items/sync' from origin 'https://app.standardnotes.org' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.


There was indeed an issue with my Traefik CORS middleware.
The web app could connect successfully after fixing it.
Thanks for your help
S.
