### ISSUE TITLE
[Help Wanted] Unable to write to local database. Please restart the app and try again.

### ISSUE THREAD

**Issue by newyokohama** [standardnotes/forum#1197]
**Describe the issue**
Good morning, issue started when I noticed "Encryption Update Available" in the bottom right of the Windows Desktop version. it was not accepting my application password, I logged out and logged back in (successfully with the same application password) to test, suddenly I had no notes.

I saw "Potentially Out of Sync" in the bottom right also, so I performed a Sync Resolution, which brought back all my notes, but won't actually save this good configuration, I receive the message "Unable to write to local database. Please restart the app and try again." It will try and sync indefinitely, and then not.

**To Reproduce**
0. Upgrade desktop to 3.5.14
1. Click "Encryption Update Available"
2. Correct application password fails
3. Logout, login successfully with password, no notes
4. Sync resolution, which works, but won't save.

**Expected behavior**
Normal behavior

**Screenshots**
![image](https://user-images.githubusercontent.com/54448140/103940936-22289e00-50fc-11eb-884d-0c71bf22c834.png)
![image](https://user-images.githubusercontent.com/54448140/103940963-2d7bc980-50fc-11eb-9c07-ce0e1d124a2b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (The SA Web version is the same experience)
 - Version 84.0.2

**Additional context**

**Comment by newyokohama** [comment]
different computer entirely, web app loads, but gives this:

![image](https://user-images.githubusercontent.com/54448140/103943617-5ef69400-5100-11eb-9b50-ae35c5e604ea.png)

**Comment by mobitar** [comment]
"Unable to write to local database" is a staple of odd Firefox configurations. Be sure you're not in a private window. I'd also try a different browser to see if you get the same results.

**Comment by newyokohama** [comment]
Thank you Mo, I will reset back to default settings and see what's up.

Thanks,
-NY

**Comment by newyokohama** [comment]
I logged out of the iOS app, and greeted with this when I log in, lasts indefinitely.

![E339BC96-E3A1-46E2-994B-D3A5DA4DFD63](https://user-images.githubusercontent.com/54448140/104058426-b1e45000-51c1-11eb-9b78-3964b7b709eb.png)

So I’m on app-legacy now, will export everything unencrypted, get all my filesafe files out of there, because app-legacy.standardnotes.org is all that works at the moment.

**Comment by mobitar** [comment]
Can you email me your account email, referencing this thread?

**Comment by newyokohama** [comment]
done!

**Comment by mobitar** [comment]
Hmm, I don't see anything off in particular about your account. Can you try this:

1. Using Chrome or Safari (not FF) in a regular (non-private) window, open app.standardnotes.org.
2. If signed in, sign out.
3. Open [Developer Tools](https://developers.google.com/web/tools/chrome-devtools/open), then choose the Console tab.
4. Sign into your account

Can you then share a screenshot of what the console is reporting? I imagine you should see a bunch of things in red, reporting errors that are preventing your application from loading properly.

**Comment by newyokohama** [comment]
Hi Mo, here's the console:

[image: image.png]

Here's the Issues tab, not sure if it's relevant:
[image: image.png]

Thank you,
-NY

**Comment by mobitar** [comment]
Thanks for the info, that gives us a hint. We'll be deploying an update to the web app that should resolve this one particular issue. Basically what would happen is that if it detected one item that it couldn't decrypt, it would halt execution of sync. The fix will instead make it so this one item is marked as "error decrypting", but doesn't halt execution of sync. We'll have to see if there are additional issues past this one. But that would explain why it hangs on just 1 item on the mobile app.

I'll update you in this thread once we release this to the web app (sometime today or tomorrow).

cc @baptiste-grob

**Comment by newyokohama** [comment]
Interesting! Thank you Mo - take your time. :-)

**Comment by mobitar** [comment]
We have the fix up on https://app-dev.standardnotes.org (**not** app.standardnotes.org). Can you follow these steps again and report what happens:

1. Using Chrome or Safari (not FF) in a regular (non-private) window, open https://app-dev.standardnotes.org.
1. If signed in, sign out.
1. Open Developer Tools, then choose the Console tab.
2. **Important:** before signing into your account, click Advanced Options, and under Sync Server Domain, change the URL to https://sync.standardnotes.org (see image).
1. Sign into your account

<img width="416" alt="Screen Shot 2021-01-12 at 8 30 00 AM" src="https://user-images.githubusercontent.com/3277844/104327514-7cd14980-54b0-11eb-9196-39a618c52f28.png">

**Comment by newyokohama** [comment]
Hi Mo, thanks again, I'm able to load all of my notes with this method. Here's the console:

![image](https://user-images.githubusercontent.com/54448140/104345488-689b4580-54cc-11eb-9491-3a57dca9c115.png)

Best,
-NY

**Comment by baptiste-grob** [comment]
Hey @newyokohama, version 3.5.15 of the app is now live on app.standardnotes.org/ and includes the fix that we had you try earlier, so you can try signing in from there now.

**Comment by newyokohama** [comment]
Thanks you @mobitar  and @baptiste-grob , things are looking much more normal now, outside of a couple duplicate notes that aren't listed as conflicted, no big deal. Also noticed it still won't take my password when trying to do the Encryption upgrade, but maybe I'll just skip that for now.

Should I be concerned at all about all that red in my console?

Best, and thanks again,
-NY

**Comment by mobitar** [comment]
Your account has a strange case of a few items that don't have any content but are not marked as deleted. All created on August 3, 2020. Perhaps you imported a bad import file? In any case I've deleted these from your account. This will take care of all the red warnings; you shouldn't see them again after signing out and back in. You can try signing out and back in one last time to see if that allows you to perform the encryption update.

**Comment by newyokohama** [comment]
Thank you Mo, yeah on August 3rd, I definitely had an issue when using Folders where every note and tag got duplicated. I didn't know Batch existed then, so I deleted the duplicates manually, extensions included. I did try and import a seemingly good backup file on that day.

Tried the encryption upgrade after signing out and back in, no luck, but that's alright. I also can't download my notes into the mobile app (iOS), but that's also alright. I've got my notes, and I have them on multiple computers, and that's a fine start for me.

Thanks again,
-NY

**Comment by mobitar** [comment]
Ah yes, I recall that bug with the Folders extension that caused some erroneous items to be created.

The fix we made was not yet made to the iOS app, so that will be made soon. Although, given these faulty items are now deleted off your account, you shouldn't have the loading issues to begin with. Can you try signing out and back in on the iOS app?

**Comment by newyokohama** [comment]
hi Mo, apologies for the delay. The iOS app had some strange data in it, but I logged out, logged in, and everything is looking fine again.

I appreciate all your help on this one, I was truly stuck.

Warm regards,
-NY

**Comment by mobitar** [comment]
Awesome, glad to hear!
