### ISSUE TITLE
SN locks up during save operations

### ISSUE THREAD

**Issue by FlagPonder** [standardnotes/forum#1198]
**Describe the bug**

**To Reproduce**
1. Go to 'on Android open an existing note or create a new note and begin composing and after entering enough text "Saving... appears beneath Compose but the application locks and remains in this state until I close the app'

**Expected behavior**
I expect the app to auto-save as it has done flawlessly prior to the encryption update I administered per instruction last night.

**Screenshots**
![Screenshot_20210107-165613](https://user-images.githubusercontent.com/1273496/103950029-28be1200-510a-11eb-99c0-7e5b903d915d.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: OnePlus7T
 - OS: Oxygen OS (10.0.15.HD65AA)
 - Browser Brave
 - Version 1.18.77,Chromium 87.0.4280.101

**Additional context**
This only seem to happen after the encryption upgrade.

**Comment by JaspalSuri** [comment]
Hi @FlagPonder,

I'm sorry to hear that. Just to double-check, have you signed out of and back into the Android app after performing the encryption upgrade on the desktop app?
