### ISSUE TITLE
Make deleting notes easier

### ISSUE THREAD

**Issue by ncserny** [standardnotes/forum#1200]
Currently it is time consuming to delete notes. 3 clicks are needed: 1. click on the note, 2. Click on Options, 3. Click on Move to trash. 

It would be great if there could be a right click menu in the desktop app or the option to drag the note into trash. 
On mobile devices it would be great if it could be swipable.

**Comment by JaspalSuri** [comment]
Hi @ncserny,

Thanks for your feedback. Improving the UI and UX of several features, especially for basic functions like deleting a note, is something that we have planned for our next long-term update. 🙂 

For what it's worth, while viewing the notes list or search results on the mobile app, you can press and hold a note to reveal the note management options menu.
