### ISSUE TITLE
encryption upgrade and self-hosted syncing server

### ISSUE THREAD

**Issue by ohdisyus** [standardnotes/forum#1206]
Hello. I recently upgraded my encryption, as recommended, but whenever I open the Standard Notes app from any of my devices, I am prompted to login again. I expected this to be the case once per app, but it happens all the time. I do host my own syncing server. Could that be the issue? Does it need an upgrade as well? Thanks. -Jason

**Comment by mobitar** [comment]
Please see this thread: https://github.com/standardnotes/syncing-server/issues/143#issuecomment-737763083

We'll be making changes in the near future so that it defaults to master branch so new self-hosters don't have this issue 👍

**Comment by ohdisyus** [comment]
Looks like swapping RAILS_ENV=development with RAILS_ENV=production in the .env file was the key! Appreciate it.
