### ISSUE TITLE
FileSafe does not downlad files from Google Drive

### ISSUE THREAD

**Issue by opiechow** [standardnotes/forum#1209]
**Describe the bug**
Filesafe cannot download any of my Files.

**To Reproduce**
1. Go to any note
2. Click on FileSafe on the bottom
3. Scroll down to 'All files'
4. Click on any of your files
5. Click 'Download'
6. See error

**Expected behavior**
File is downloaded and decrypted and ready to use.

**Screenshots**
![2021-01-13-074248_255x110_scrot](https://user-images.githubusercontent.com/12622836/104415893-1f520100-5573-11eb-9cc5-1f1ceff1e396.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Both Firefox and AppImage
 - SN: 3.5.14, Firefox 84.0.2

**Additional context**
Uploading also seems to not work, but I've seen another issue dedicated to it (https://github.com/standardnotes/forum/issues/1202), so I'm not duplicating it here.

**Comment by opiechow** [comment]
FYI I solved the issue by removing and adding back again the Google Drive integration.
Nevertheless, it never should have broken in the first place. I almost had a heart attack when I couldn't download my file at first 🗡️

**Comment by mobitar** [comment]
Glad to hear you got it resolved. Not quite sure what the issue could have been. Not to worry in general though—as long as you can still access the raw encrypted files in your Drive, they can still be decrypted by dragging and dropping them onto the FileSafe interface.
