### ISSUE TITLE
[Help Wanted] Restore keychain (android version 10, EMUI version 10)

### ISSUE THREAD

**Issue by andersliland** [standardnotes/forum#1210]
**Describe the issue**
I get the following screen when opening the application (ignore the Bitwarden button, this is a password manager)

The message reads:

**Restore Keychain**

**We’ve detected that your keychain has been wiped. This can happen when restoring your device from a backup. Please enter your account password to restore your account keys.**

What keychain password is this?

I have tried
- standard notes password
- google account password
- phone lock code

**To Reproduce**
1. Open the application

**Expected behavior**
Expect to see login screen.

**Screenshots**

![Screenshot_20210113_090915_com standardnotes](https://user-images.githubusercontent.com/8539036/104424511-c5a40380-557f-11eb-94b0-763860aeddde.jpg)

This is the screen I see when opening the application. Nothing more or less. Cannot remove the screen.

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - OS: Android 10, with Huawei EMUI version 10.0.0

**Additional context**

Loggin and usage work fine on any browser, desktop and mobile. The problem is only in the Android application.

I have uninstalled the application.
Deleted cache and storage.
Then reinstalled the application. 

The problem still persists.

Is this an android problem or standard notes problem?

I have used the phone for 2 year and have not done any factor reset or account (google) change recently.

**Comment by radko93** [comment]
Hi,
I'm sorry for the trouble with the app. Unfortunately reinstalling the app might bring back a corrupted backup. If you can confirm that signing in on the web works, you can clear application data (cache and storage) and start the app again.

**Comment by andersliland** [comment]
Login on browser works.

I have already cleared cache and storage then reinstalled

**Comment by radko93** [comment]
@andersliland reinstalling the app might restore a corrupted backup. Please **only** clear cache without reinstalling.

**Comment by andersliland** [comment]
That worked!! Thanks so much!!!
