### ISSUE TITLE
Extension communication issue

### ISSUE THREAD

**Issue by corvec** [standardnotes/forum#1215]
**Describe the bug**
I recently purchased Extended and activated it, then installed several extensions. I then started encountering this bug. I also see this bug in the demo (in addition to another set of error messages).

An alert titled "Standard Notes" and only one button, "OK" appears after performing various actions. The body of the alert is "This extension is attempting to communicate with Standard Notes, but an error is preventing it from doing so. Please restart this extension and try again."

Upon clicking "OK" the alert is dismissed and another immediately pops up. This repeats anywhere from 2-6 times (up to 7 alerts in a row).

In the demo, the above behavior is experienced (though there is no alert title bar) as well as error messages like "Standard Notes is trying to communicate with Simple Task Editor, but an error is occurring. Please restart this extension and try again."

**To Reproduce**
1. Activate several extensions
2. Create a new folder/tag or change the editor in a new note.

Option 2:

1. Load the demo.
2. Select a note that uses an extension.

**Expected behavior**
Optimally there would not be errors with the extensions in an empty account immediately after disabling them.

However, given that there is an issue, the error message should indicate the name of the problematic extension and should give some information about where to find more information on the error (like a stack trace).

Additionally, the alert should not be blocking. A toast or status bar message would be less obtrusive.

**Screenshots**
![StandardNotesError](https://user-images.githubusercontent.com/755349/104988041-0d45e780-59e5-11eb-8e77-0bd257e9f4e9.PNG)

![StandardNotesError-demo](https://user-images.githubusercontent.com/755349/104988119-42523a00-59e5-11eb-80e4-4302fc66f196.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (demo app), but also in the Desktop app (Extended account)
 - Version 3.5.14 desktop app, 3.5.15 demo app

**Additional context**
After restarting the desktop app, the issues went away there.

**Comment by colournoise** [comment]
I'm seeing similar in the browser app (valid extended account). Extension communication issues, UI and functionality affected by placeholders like this...

![image](https://user-images.githubusercontent.com/78282411/106370214-d0b4ad00-634f-11eb-8f79-9ad23f5680da.png)

(Clicking 'reload' has no effect)

Windows 10. Chrome and Brave (shield up or down makes no difference). Desktop app 3.5.18 working fine with all extensions.

**Comment by colournoise** [comment]
Weird. Now solved for me. After several failed attempts, the browser version suddenly let me delete the Extension repository and enter my membership code (had tried this previously with no result). Once reactivated, I was able to uninstall/reinstall the desired extensions and they now work fine.

**Comment by corvec** [comment]
I've been using StandardNotes since reporting this issue. With few exceptions, I haven't seen the error messages that I reported, and certainly not with the frequency that I was seeing them then. I don't know what changed, but I'm going to go ahead and close this.
