### ISSUE TITLE
[Help Wanted] Question about Dropbox Sync - Safe to delete?

### ISSUE THREAD

**Issue by mbrochh** [standardnotes/forum#1217]
This is probably a very stupid question.

I have realized that Standard Notes has been writing 2.4MB files (which is probably my entire DB) into my Dropbox on a daily basis. I assume that is because of the CloudLink Extension.

This made me wonder: How does SN actually sync? I assume that my notes also get uploaded to the SN central server, and that is how they sync between all my devices.

The files in my Dropbox are not really for syncing, but just as a backup.

Therefore, am I right to assume that I can just delete the backups from previous years and months? Nothing of value would be lost, correct? If SN ever goes down, then I could install the open source app and load my latest backup from my Dropbox, correct?

**Comment by baptiste-grob** [comment]
Hey @mbrochh, sorry for the late response!

Your assumptions are all correct :)

With CloudLink, we copy your encrypted content from our server to your dropbox, on a daily basis. So it's exactly like a backup and if you are only interested in the latest snapshot(s) of your content then deleting the older backups will cause no malfunction in the system.

**Comment by mbrochh** [comment]
Perfect, thank you!
