### ISSUE TITLE
[Help Wanted] I'm Stuck: SmartTag syntax

### ISSUE THREAD

**Issue by VentureVision** [standardnotes/forum#1223]
I'm trying to create a Folders View that filters all notes containing both the tag "Ruth and "@Agenda". I'm having no luck. Here's my latest attempt:

!["Ruth Agenda", "tags", "and", [["title", "startswith", "Ruth"], ["title", "startswith", "@Agenda"]]]

- Any suggestions? Is the value of the tag "Ruth" or "People.Ruth", as it's a sub-folder of "People"? I've tried both.
- Not sure if I'm using the right operator. I've tried "includes" and that didn't seem to work.

Any suggestions? Thanks very much in advance for your help.

Bill

**Comment by JaspalSuri** [comment]
Hi @VentureVision,

Please try: `!["Ruth & @agenda", "tags", "includes", ["title", "startsWith", "Ruth", "and", "@agenda"]]`

Thank you for supporting us and our work by subscribing to Extended!

**Comment by VentureVision** [comment]
Hi JaspalSuri,

Thank you!! That worked. I did have to change the "Ruth" tag to "@People.Ruth", but that's a minor tweak. I appreciate your help.

**Comment by JaspalSuri** [comment]
Hi @VentureVision,

>Thank you!! That worked. 

You're welcome! Thanks for letting us know that it worked!  🙂

>I did have to change the "Ruth" tag to "@People.Ruth", but that's a minor tweak. I appreciate your help.

That's because it's tag's raw/true value. Sorry for not accounting for that in my example! I'm glad that I could help. 🙂
