### ISSUE TITLE
Login issue since client Version 2.0 on self-hosted instance

### ISSUE THREAD

**Issue by sweah82** [standardnotes/forum#123]
Since client version 2.0 I have problems to log in to my self-hosted instance of the ruby-server.
I get the following error message all the time:

The protocol version associated with your account is outdated and no longer supported by this application. Please visit standardnotes.org/help/security-update for more information.

Is that a known problem and is there anathing I can do to solve it?

**Comment by mobitar** [comment]
Hi, please upgrade your self-hosted server. You can do this by:

```
git pull
rails db:migrate
```

Then restart your server (probably optional).
