### ISSUE TITLE
[Question] Migrating FileSafe Storage Between Integrations

### ISSUE THREAD

**Issue by ozymandium** [standardnotes/forum#1230]
I have two FileSafe integrations that are functioning normally: Google Drive and WebDAV/Nextcloud. The GDrive FileSafe integration has a fair number of files attached, and I'm nearing the end of a multi-year effort to cleanly delete the underlying Google account. As such, the goal here is to migrate all the stored files from the GDrive integration into the WebDAV integration.

Using the UI, I'm not aware of a good way to do this without potentially losing files and/or associations with their respective Bold Editor notes. It seems possible to go to every note in the account, and for the ones that have attached files, manually download the unencrypted attachments and re-upload to the new integration, then re-embed. This would continue until the FileSafe master drop-down list for the old GDrive integration showed as being empty.

Is there a way to do this in bulk though?

What I'm envisioning as the ideal scenario would be to move the encrypted JSONs (without decrypting) in bulk from the GDrive location to the WebDAV location. After that, if there's some master "address book" of encrypted storage locations, then only the storage prefixes would need to be changed. Searching for something resembling this address book hasn't turned up any results yet, though.

Am I on the right track? Any pointers?

**Comment by ozymandium** [comment]
Answered by @JaspalSuri in another forum. Closing.

**Comment by alejandrogutierrez12** [comment]
Hi, is there a link for the forum where this was responded? thanks

**Comment by ozymandium** [comment]
Sorry, can't find it anymore, but for my use case there wasn't a great option. I stopped using standardnotes to store files altogether as the simplest approach.

**Comment by ozymandium** [comment]
Also worth noting that once the files (images in my case) were in FileSafe and attached to notes, there wasn't a way to sort them or handle them in batch. Only the filename could be seen and they had to be manually recovered one by one. I opted to just cut my losses and delete them all.
