### ISSUE TITLE
[Help Wanted] Can't access extensions demos

### ISSUE THREAD

**Issue by cjholly** [standardnotes/forum#1231]
Feelin' a little dumb, but here goes: I log into dashboard, and then I go to extensions tab. Before I can view the demos I get this message, but the only password I have is for my standard notes app, and it does not work here. What am I missing?

Please enter your account email and password.
Your credentials are needed for demo@standardnotes.org to refresh your session with the server.

**Comment by JaspalSuri** [comment]
Hi @cjholly, 

Are you trying to access the [demo app](https://standardnotes.org/demo), or activate Extended on the [web app](https://app.standardnotes.org) by inserting the Extended code that's available in your [dashboard](https://dashboard.standardnotes.org)?

**Comment by cjholly** [comment]
I was trying to access the demo app. Not sure if my email went through, so this may be a repeat

**Comment by myreli** [comment]
Looks like has been fixed since this issue was opened. It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
