### ISSUE TITLE
Sync after reconnecting results in conflicting copies

### ISSUE THREAD

**Issue by StefanBlamberg** [standardnotes/forum#1234]
**Description**
When the network connection is unstable, the app often creates conflicting copies after reconnecting.
I am using the Mac version of SN and when I am connected to the VPN of my company, the connection seems to be quite unstable.
It is weird why SN struggles with the network connection in the first place as I don't have such problems with other apps but it wouldn't be a huge deal in general as it reconnects after a few seconds.
However, when the connection is re-established, the app detects merge conflicts for whatever reason, even if the app is not open on any other devices.
The conflicting copies also don't have any real conflicts, one version is simply ahead of the other.
It is really strange that SN is unable to detect that the conflicting copy originated from the same source.

**Steps to reproduce**
I cannot really describe exact steps to reproduce the issue but on my device it happens whenever I am connected to the company VPN and keep typing after SN lost the network connection.

**Expected behavior**
I expect SN to detect that a "conflicting version", which is probably coming from the backend sync after re-connection, is just an older version that was originally synced from the same device. Manually deleting conflicting copies every few minutes is very tedious.

**Device info**
 Desktop version for MacOS, v3.5.18

**Comment by mobitar** [comment]
> it happens whenever I am connected to the company VPN and keep typing after SN lost the network connection.

Can you go deeper into this? Is the VPN disconnecting, or your network? Where are you located, and where is your VPN located? Do you change wifi networks throughout the day? Do other services lose connection at the same time?

**Comment by StefanBlamberg** [comment]
Hi, sorry for the late response.
1) It is probably the VPN disconnecting for very short periods of time, my network is usually stable
2) Both my PC and the VPN are located in Germany
3) No
4) I am not facing any issues with other services, but the disconnects are very brief so it is possible that I am simply not noticing it due to buffering etc. The SN sync is also re-established within a few seconds and the merge conflict is usually just a few characters

In general I am less concerned about the disconnects though, it just seems strange to me why it would lead to a merge conflict.
