### ISSUE TITLE
Extra pane on right of SN window?

### ISSUE THREAD

**Issue by johnatpackawhallop** [standardnotes/forum#1239]
This is a dumb question, but for some reason the SN documentation does not seem to include any tour of the interface. To be fair, the interface is pretty straightforward. However, I inadvertently expended an extra pane on the right of the SN window, and I can't figure out what it's for. It seems like some kind of preview pane, although for me at least nothing appears in it. I can move the divider all the way to the right and it doesn't really show, but still I am curious. Possibly it is a preview pane useful only if you have additional editors? Any insights on this are appreciated. Thanks!

**Comment by JaspalSuri** [comment]
Hi @johnatpackawhallop ,

I apologize for the lack of a detailed tour of the app's interface. 😞 I'll forward your feedback to our technical writer. 🙂 

It looks like the Margin Resizers aren't locked. You can expand the width of the editor to the desired amount or snap it to the right edge of the application's window. From there, click on **Options** button (located beneath the tags text field) and click on **Margin Resizers**. This should prevent the edges of the editor from being dragged accidentally.

[Here's a video](https://drive.google.com/file/d/1rv6hqiOGtM6q6MRvARNtOBQlaoYVjaSG/view) on what utilizing that option looks like.

**Comment by Parkertg** [comment]
@JaspalSuri 
I had momentarily been confused about this as well last week. I'd suggest adding a tooltip/ hover hint stating what it is.. "Left Margin" & "Right Margin"

**Comment by JaspalSuri** [comment]
Hi @Parkertg, sorry to hear that! Thanks for the feedback; I'll forward it over to the dev team for review. 🙂

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
