### ISSUE TITLE
Code block consistency between Standard Notes and Listed

### ISSUE THREAD

**Issue by alokw** [standardnotes/forum#1243]
Admittedly new to both Standard Notes and Listed - I'm using the Code Editor in Standard Notes, which is working great.
However, if I publish a simple block of code to Listed, it appears like a blog post (not code-formatted).

If I follow Listed's code instructions and add a ```python at the beginning of my code block, it looks great in Listed, but the code formatting breaks in Standard Notes.

In the meantime I'm just adding an extra ` on the second line, which works okayish, but it would be cool if there was consistency between the two - either proper formatting in Standard Notes with the ``` callout for Listed - or if Listed could interpret the code setting and format it accordingly.

**Comment by JaspalSuri** [comment]
Hi @alokw,

> If I follow Listed's code instructions and add a ```python at the beginning of my code block, it looks great in Listed, but the code formatting breaks in Standard Notes.

I'm afraid that I wasn't able to reproduce the issue. Did you change the language via the dropdown menu located at the bottom of the editor as well? If I select either Markdown or Python, the code appears to be formatted properly. If I use the Plain Text option, then it doesn't work as expected.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
