### ISSUE TITLE
Hide Note Previews & Hide Note Dates in Desktop App / Web

### ISSUE THREAD

**Issue by alokw** [standardnotes/forum#1244]
I really like the "Hide note previews" & "Hide note dates" options in the iOS app - really keeps the notes list looking nice and clean.

Is there a way to do the same in the Web or Windows apps? Wasn't able to find one, but would be a great option if it doesn't exist yet!

**Comment by JaspalSuri** [comment]
Hi @alokw,

You can modify the appearance of the notes list from within the **Options** menu, whose button is located beneath the search bar, under the **Display** section. 

![image](https://user-images.githubusercontent.com/44656000/108829771-71784000-757d-11eb-9fe4-aef79bb1106c.png)
