### ISSUE TITLE
[Help Wanted] Extensions not loading on self hosted Web

### ISSUE THREAD

**Issue by jbenitosantoni** [standardnotes/forum#1246]
Hello, Im using docker image for standardnotes self hosted Web interface.

When I login it tries to load the extensions from domain.com instead of loading them from my own domain, I have setted the .env file with all the correct parameters but im still having this issue.

Im getting: We couldnt load http://www.domain.com/extensions/plus-editor/1?

**Comment by JaspalSuri** [comment]
Hi @jbenitosantoni,

It appears that you've closed this thread; please let us know if you still need help with this!

**Comment by e1025735** [comment]
Hi @jbenitosantoni or @JaspalSuri,

I am using the docker standalone image as well. After installing the extensions I got the same error. Can you give me a hint how to fix the problem?

**Comment by JaspalSuri** [comment]
Hi @e1025735, I'm sorry to hear that you encountered that issue but am glad to see that you were able to find the solution!
