### ISSUE TITLE
Clam found PUA.win.trojan.Xored-1 in Bold editor extension files

### ISSUE THREAD

**Issue by TmrwBg** [standardnotes/forum#1247]
Hello,

today I ran a ClamAV scan on my debian. It flagged several PUA.win.trojan.Xored-1 in Bold editor files and one in Standard notes .cache. Didn't know where to report this. I don't have a log file or screenshot unfortunately as the idea of reporting came after I closed ClamTk.  I'm new to this and thus sorry if the issue is misplaced or incomplete.

**Comment by mobitar** [comment]
False positives are quite common with these tools in general. I don't believe there is anything to be concerned about here, but the code to the [Bold Editor](https://github.com/standardnotes/bold-editor) is open-source nonetheless.
