### ISSUE TITLE
Query of distribution of key

### ISSUE THREAD

**Issue by alexios-y** [standardnotes/forum#1250]
Hi,

I just come across this app today and really like the idea of a E2EE note app. Sorry if this question is answered somewhere before but I checked the website didn’t find anything regarding it.
My question is: Do we store encryption key or password  on the sever? If not, what kind of parameters are stored in server? What happen when you sign in on a new device?
My understanding now is the server stores some parameters which could be used with password to generate the key but never store password. Since the key is generated locally, there is no need to store it or the password on the server for distribution. Is that correct?

**Comment by JaspalSuri** [comment]
Hi @alexios-y,

Thanks for reaching out to us and welcome to the forum! While I will reach out to the dev team for a more official answer, I will try to answer your questions as best as I can.

Your password is not stored anywhere. The keys that are derived from it, that encrypt everything that's stored in your account, are not stored on the server. The key parameters are stored on the server and are used to validate a password. If a user has [2FA enabled](https://standardnotes.org/help/25/how-do-i-enable-two-factor-authentication-for-my-account), then they must provide the correct token in order for the client to retrieve the key parameters from the server.

>My understanding now is the server stores some parameters which could be used with password to generate the key but never store password. Since the key is generated locally, there is no need to store it or the password on the server for distribution. Is that correct?

Your understand appears to be correct; I'll be sure to have someone double check this (and potentially provide more info) just in case.

**Comment by alexios-y** [comment]
Hi @JaspalSuri 

Thanks for your confirmation. That’s quite informative. More confident on its security now.

**Comment by JaspalSuri** [comment]
Hi @alexios-y,

Thank you for letting me know! We've also had [two audits completed](https://blog.standardnotes.org/standard-notes-security-audits-2021/) in recent months.
