### ISSUE TITLE
[Help Wanted] Can't log on to Standard Notes (Window version)

### ISSUE THREAD

**Issue by error1021** [standardnotes/forum#1254]
Hi.
After updating the app, I can't log on to the Window version of Standard Notes. I enter the password to unlock the app then the screen just turns white. Nothing appears. I'm not sure what the problem is. I hope you can help me solve this problem. (The mobile version works normally.)

**Comment by JaspalSuri** [comment]
Hi @error1021,

I'm sorry to hear that. Do you have 2FA enabled on your account?

Can you try terminating the session on the desktop app from the mobile app, relaunch the app, try signing into the app again, and relaunch it once more?

If that doesn't work, please press and hold `CTRL-SHIFT-I` until the developer tools modal appears, click on the **Console** tab, and then send us screenshots of whatever appears in red.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
