### ISSUE TITLE
Search for text within a Note - Jan 2021

### ISSUE THREAD

**Issue by deacl** [standardnotes/forum#1255]
We need to be able to search for text within a note and click to move focus from one match to the next, next, ....
I'm using desktop app on a Mac and now there is a search bar at the top which highlights all notes with matching the search text, but I still see no way to progress to the locations within the Note of each match.

I thought that this was promised earlier, is it planned?
thank you, -deacl

**Comment by effieeee** [comment]
Currently tracking here: https://github.com/standardnotes/forum/issues/1770
