### ISSUE TITLE
Mac OS Backup Location Reverting

### ISSUE THREAD

**Issue by jbfrobozz** [standardnotes/forum#1256]
On Mac OS it appears that the backup location is reverting to my home folder after each update.  The files are stored in my home folder within a subfolder called Standard Notes Backups.  I have my backup folder set to another area of my hard disk.  When I use Backups, Change Backup Location it shows the other area of my hard disk (my desired location), but the files are still being saved in the home directory.  If I click OK to change the backup location, then the files are moved, even though I didn't change anything in the dialog box.

I believe that this problem is occurring after an upgrade, but it is difficult to determine if it is all upgrades or just some. 

I'm on MacOS 11.2.2 and now Standard Notes 3.6.1

Thanks!

**Comment by JaspalSuri** [comment]
Hi @jbfrobozz,

I haven't run into this issue on macOS so far, but I'll keep an eye out and create a report accordingly. Have you signed out of the app between updates? Do you recall when you first noticed this issue?

**Comment by jbfrobozz** [comment]
Yes, I have signed out between the updates, but I don’t believe that fixed it.  This has occurred two or three times since January.  However, I didn’t have a good grasp for the issue and just reset it.  Next update, I will carefully record a few things, including screenshots, before and after to see I can help with the specific cause.

**Comment by JaspalSuri** [comment]
> Yes, I have signed out between the updates, but I don’t believe that fixed it.

Thank you for letting me know! I was actually wondering if it was causing the issue, but I have signed out of the app in the past few months as well.

> This has occurred two or three times since January.  However, I didn’t have a good grasp for the issue and just reset it. 

Thank you for sharing those details it will help in our investigation. The only major change that comes to mind is the rollout of the option to upgrade one's account's encryption suite.

> Next update, I will carefully record a few things, including screenshots, before and after to see I can help with the specific cause.

Thank you so much, I really appreciate it!

**Comment by jbfrobozz** [comment]
I saw that an update was available so I went to take screenshots before upgrading.  However, updates are apparently not the issue as the problem has already occurred.  I have not logged out of the app sign my last message.

I'm attaching several screenshots.  The first shows where I last set the backup location.   Backups were going here through March 13.  

![Desired location - Where I last set](https://user-images.githubusercontent.com/80055539/111486309-c38c2b80-870d-11eb-9d6f-3128b77c816a.png)


Since March 13 they have been going into my home folder.  That is confirmed when I go to Backups, Open Backups Location. 
![Backups - Open Backup Location](https://user-images.githubusercontent.com/80055539/111486329-c71fb280-870d-11eb-88ea-dd29308f7047.png)


However, when I go to Backups, Change Backup Location the folder defaults to opening to my actual preferred location.
![Backups - Change Backup Location](https://user-images.githubusercontent.com/80055539/111486338-c8e97600-870d-11eb-9f3e-6544a389a8a2.png)

It did occur to me that this could be related to Google Drive somehow, but I haven't experienced any issues with Google Drive and that folder is available offline so writing to it even if I'm not connected to the internet shouldn't be a problem.

**Comment by JaspalSuri** [comment]
Hi @jbfrobozz,

Thank you for the update. I'm sorry that it happened again. I have a similar setup and will keep an eye out for this issue in case it happens again. 

>However, when I go to Backups, Change Backup Location the folder defaults to opening to my actual preferred location.

For what it's worth, this appears to be working as expected. The last path that is selected to save a downloaded file or exported backup, or set the location of a backup is remembered by the app.

While not ideal, until this bug is reproduced and a fix for it has been released, I would suggest leveraging the feature in Google's Backup and Sync app that allows you to backup folders/directories outside of the main sync folder.
