### ISSUE TITLE
V3.6.1 has read-protected all of my notes

### ISSUE THREAD

**Issue by Stever888** [standardnotes/forum#1257]
**Describe the bug**
Immediately after the upgrade to V3.6.1, all of my notes had the "protect" bit set. I have to enter my password to edit the note, and the explicitly choose Options > Unprotect (and then authenticate again) to unprotect the note. OBNOXIOUS

As best as I can figure out, the protection model has changed from having different kinds of protection to a single "protected" or "unprotected" status. So the fact that I delete-protected dozens of my notes now has those same notes READ PROTECTED and MODIFY PROTECTED, so I have to explicitly unprotect them to read them.

BIG BIG LOSSAGE. I have dozens of notes that were delete protected. Now I'm going to have to unprotect every one with a double authentication.

Really bad choice in how to change the architecture from multiple permissions to a single protected bit. REALLY bad choice.

**To Reproduce**
Update to 3.6.1
Click on any protected note to edit it

**Expected behavior**
Let me open my notes without having to enter my password.

**Desktop (please complete the following information):**
Happens on all platforms.

**Comment by JaspalSuri** [comment]
Hi @Stever888, when entering your passcode, you can set an amount of time for the app to remember not to ask for your passcode when interacting with a protected item. If you want to largely rely on the app's passcode lock, you can set the app to remember your passcode for a week.

![image](https://user-images.githubusercontent.com/44656000/110118708-9df73d80-7d6f-11eb-99c9-871a072a43ed.png)
