### ISSUE TITLE
Protected notes no longer require account password

### ISSUE THREAD

**Issue by sethmad** [standardnotes/forum#1259]
Viewing my protected notes in the desktop application previously required entering both my account password and application passcode. Now the app only requests the application passcode. [This Help page](https://standardnotes.org/help/54/what-does-it-mean-to-lock-or-protect-a-note) says that protection features for protected notes can be managed under Manage Privileges in the Account menu. However, the Account menu has no Manage Privileges option.

**To Reproduce**
1. Create a new note
2. Mark note as Protected
3. Navigate to an unprotected note
4. Navigate to new protected note. See authentication required.

**Expected behavior**
Viewing the protected note should require both application passcode and account password (to protect those notes if the application passcode is compromised). Also, the Account menu should have options as described on the Help page.

**Desktop**
 - Standard Notes 3.6.1
 - Mac OS 11.1

**Comment by JaspalSuri** [comment]
Hi @sethmad,

Sorry about the confusion. These options and features have been removed as a part of our simplification of the Privileges features (now named "Protections"), so this isn't a bug but an intentional change. I've put in a request to update the help page; thank you for bringing that to our attention!

**Comment by mobitar** [comment]
Thanks for catching that outdated help post, this is now fixed (pending deploy). Please read our [3.6 release blog post](https://blog.standardnotes.org/standard-notes-3-6-update/) on how Protections now work. Account password is now used as a fallback for when a local passcode is not set.

Note that Protections are not cryptographically backed in the first place, but are UI-level protections. It's not clear what threat model your theoretical of "application passcode is compromised" is operating under. If someone gains access to your unlocked application, all data is unencrypted in memory. So having an account password configured to access protected notes will not deter a savvy attacker. In the case of the local access threat model, a locked application with a strong passcode is the only cryptographically sure way to prevent access.

**Comment by sethmad** [comment]
I understand that Protections are UI-level only, but that's precisely why they were helpful in real-world situations with unsophisticated/accidental breaches, i.e. you accidentally leave the app running on your computer in your workplace, step out of the office, and someone steps in and clicks through your notes before the time-out. The old feature added a level of two-factor authentication for especially sensitive Protected notes. 

With that feature eliminated, I'd like to see it replaced with the ability to set local passcodes for individual notes or some other kind of UI wall around selected notes/classes of notes.

**Comment by mobitar** [comment]
> and someone steps in and clicks through your notes before the time-out.

Even in the old case this would be possible, since the Remember option applied to both app passcode + account password.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
