### ISSUE TITLE
All notes suddenly empty, but one

### ISSUE THREAD

**Issue by abulte** [standardnotes/forum#126]
Hi,

I woke up a few days ago to see all my notes empty but one. This happens on all clients (web, desktop and mobile iOS). All the notes have the same modification date on the Standard Notes client but not on the filesystem. A bunch of them also have the same size (`758 octets`). 

I don't think I did anything special to trigger this.

Any idea how I can get back access to my notes? I tried to restore a previous version of a note from the Dropbox history, no luck. I also tried to decrypt with `decrypt.html` the content of my Dropbox backup. When I do this, I can get back a few of my notes but not all of them.

Thanks for your help.

NB: Standard Notes desktop version 2.0.3, iOS version up to date.

**Comment by abulte** [comment]
I also tested an export of unencrypted data. All notes but one show up as attached.

[undefined-fecd8cad-ec8b-4570-bbe5-d76e2932b1b9.txt](https://github.com/standardnotes/forum/files/1464448/undefined-fecd8cad-ec8b-4570-bbe5-d76e2932b1b9.txt)

**Comment by mobitar** [comment]
Hey Alexandre, there are two bugs that could have caused this, both of which have been fixed. Also, not to worry, we create nightly backups of our database so I can restore your data for you.

The first bug was, if you restored an iPhone from iCloud, it will have restored access to your notes, but not encryption keys. This would make all notes "Error decrypting", and when you signed in, it would merge those notes with the server. See this issue for more: https://github.com/standardnotes/mobile/issues/18

The other issue was that on some browsers, especially Firefox, they have the capability of signing you out of your account when you clear your history, but not removing the local database data. This would mean the same issue as above would occur. There was also an issue where if you enabled passcode lock on web or desktop in versions prior to 2.0.3, you were more likely to be signed out and trigger the above scenarios.

Have you done either of those?

Lastly, can you double check the exact version of the iOS app you're using. I want to make sure you're not using the old app, which is unpublished and has not been receiving updates. 

Regarding an export, they will only be valid prior to being affected by the above two issues. If you create an export after this issue, then the data will remain in the same state.

Please also send me an email with your account email to mo@standardnote.org.

**Comment by abulte** [comment]
Yep, iCloud restore last Friday for me. I’ll send you an email, thanks.

**Comment by CamJohnson26** [comment]
I have this issue too, how do I restore the empty notes, do I have to import a backup?

**Comment by mobitar** [comment]
Hey Cameron, if you have a backup saved, then you can just import it. If you don't have a backup, please send me an email from your account email to mo@standardnotes.org and I'll create a restore file for you.

**Comment by mobitar** [comment]
For anyone else who experienced an issue restoring from iCloud, please send me an email directly at mo@standardnotes.org.
