### ISSUE TITLE
Frequent crashes of Android app when using Markdown Basic

### ISSUE THREAD

**Issue by sethmad** [standardnotes/forum#1263]
The Android app frequently crashes (abruptly closes, returns to home screen) when I am creating notes in Markdown Basic. Although I am able to reproduce this regularly, I'm not sure of the exact steps. Here is as close as I can get:

**To Reproduce**
1. Create a new note in Android App
2. Switch editor to Markdown Basic
3. Begin typing note. Type for approximately 3 minutes or to about 350 characters.
4. App abruptly crashes while typing

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e (Verizon)
 - OS: Android 11
 - Standard Notes 3.6.2 (3000265)
 
**Additional context**
- Signed in to Extended account with 745 notes
- On WiFi
- Using Microsoft SwiftKey Keyboard 7.7.3.5

**Comment by mobitar** [comment]
Thanks, we're aware of this issue, and getting close and closer to identifying the cause. It's a bit tricky because, as you mentioned, it's not always reproducible. But we're thinking it's a memory overallocation issue.

**Comment by sethmad** [comment]
I'm also now occasionally getting an error, in case this is helpful:

Standard Notes is trying to communicate with the extension Markdown Basic
but an error is occurring. Please restart the extension and try again.

**Comment by sethmad** [comment]
I have yet to be able to, but I haven’t tried extensively.

**Comment by jaxom** [comment]
Hi! I experience this sporadic crashes of the Android app in the middle of typing with using editor Markdown Pro.

**Comment by effieeee** [comment]
Resolved on new mobile UX
