### ISSUE TITLE
Issues with Plus Editor

### ISSUE THREAD

**Issue by snakespan** [standardnotes/forum#1264]
New issue this morning with lots of notes using Plus Editor:

The extension was not found on your system, possibly because it is still downloading. If the extension doesn't load, try uninstalling then reinstalling the extension.

Tried installing / reinstalling the extension as recommended but not able to fix this way. 

Using v3.6.1 on Windows 10 desktop. Seems to work fine on mobile (Android). Plus Editor version is 1.4.6

**Comment by Fudiem** [comment]
I can confirm this.
Works fine on Web and android, but the error _"The extension was not found on your system..."_ appears on windows desktop.

**Comment by gitgurts** [comment]
I can confirm this, too.
I'm on macOS 10.13.2, running 3.6.1
Reinstalling doesn't fix it.

**Comment by mobitar** [comment]
We can reproduce this issue and will be pushing out a fix shortly.

**Comment by JaspalSuri** [comment]
The fix was released and you should be able to use the Plus Editor without needing to make any changes on your end. 🙂 I'm closing this thread for now; please let us know if you're still running into any issues.

**Comment by gitgurts** [comment]
Thanks so much, this was really quick!

**Comment by snakespan** [comment]
Perfect, thanks for the quick turnaround

**Comment by JaspalSuri** [comment]
On behalf of the dev team, you're both very welcome. Thankfully a small change was needed to resolve this issue.
