### ISSUE TITLE
2FA Manager is completely broken (for me at least)

### ISSUE THREAD

**Issue by C0Nd3Mnd** [standardnotes/forum#1266]
I created a screen recording:

https://user-images.githubusercontent.com/47672946/111066681-33a17400-84b8-11eb-9d17-412d5a123f08.mp4

I'm using version 3.6.1 on Windows 10, but I tried the browser version as well with similar symptoms.

I start the app, then I try to install the extension (which at first seems to work fine), but soon after that it shows that it can't be installed locally. When I click _Open_, the extension sometimes opens multiple times (my mouse is fine, it doesn't double-click). Then, the extension refreshes every few seconds, making it virtually impossible to use because the secret key keeps changing. When I manage to copy the secret key and then go to the next page, it refreshes soon after and goes back to the first page again.

The URL where it tries to download a local copy of the extension from is 404: <https://github.com/standardnotes/mfa-component/archive/1.2.2.zip>

**Comment by C0Nd3Mnd** [comment]
Well, I fixed the issue by clicking "Refresh" on the "Your extended benefits are valid until [...]" line. Maybe the repository information was outdated?

I still think that not showing a proper error (and adding a refresh button to the part of the UI that's actually showing the repository content) and the application "acting up" like this is pretty bad UX.

**Comment by C0Nd3Mnd** [comment]
Well, after activating 2FA, it's acting up again:

![Standard_Notes_mR27tXenRo](https://user-images.githubusercontent.com/47672946/111067152-bc211400-84ba-11eb-9ef5-415c85199cf0.png)

When opening the extension, it does its refresh thing again where it refreshes every few seconds.

**Comment by johnny243** [comment]
Hi @C0Nd3Mnd thanks for reporting this!

The issue should be fixed now. Please try again and let me know!

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
