### ISSUE TITLE
Spreadsheet Editor

### ISSUE THREAD

**Issue by Stolas** [standardnotes/forum#1267]
**Describe the bug**
Calculations are not added.

**To Reproduce**
1. I add the formula `=Sheet1!B3*Sheet1!B8-Sheet1!B6*(Sheet1!B4+1)`

**Expected behavior**
Assigning the formula to the cell.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 3.6.1

**Comment by mobitar** [comment]
Haven't tested but try this:

```
=(Sheet1!B3)*((Sheet1!B8)-(Sheet1!B6))*(Sheet1!B4+1)
```

If not try putting quotes around the sheet name.

**Comment by johnny243** [comment]
Hi @Stolas, I don't see any issues with your formula. I tested it in both Secure Spreadsheets and Google Sheets:

![image](https://user-images.githubusercontent.com/5891646/111241206-0b5a6800-85d3-11eb-8479-bd88d951ec63.png)
![image](https://user-images.githubusercontent.com/5891646/111241174-f978c500-85d2-11eb-8508-ec3981c67efc.png)

**Comment by Stolas** [comment]
This is exactly what I did.
But the formula is not added to the sell when I press enter.

**Comment by johnny243** [comment]
That's unexpected. What if you paste the formula into the formula field:

1. Select the A1 cell
1. Click on the formula field (fx) an paste your formula
1. Press enter

**Comment by Stolas** [comment]
The program locked up and it worked when it unfroze.

**Comment by johnny243** [comment]
Can you reproduce this consistently? If so, can you please attach a screen recording?

**Comment by Stolas** [comment]
I can and I can't I've uninstalled standardnotes and moved to a different note taking app.
