### ISSUE TITLE
CORS Error with external theme (desktop app only)

### ISSUE THREAD

**Issue by Lissy93** [standardnotes/forum#1268]
I am trying to make a theme, just using the CSS variables in the :root selector. Following the docs, I published the CSS and the JSON extension to a private link on Listed, and added it through the extensions menu.

Using the Standard Notes web app, everything works perfectly and my theme is applied, similarly in the Android app everything is working as expected. But in the desktop app (Arch Linux), I get a CORS error for my stylesheet hosted on Listed.

```
Refused to load the stylesheet '<URL>' because it violates the following 
Content Security Policy directive: "style-src 'unsafe-inline' 'self' <URL>". 
Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

The UI also [shows](https://i.ibb.co/fXX5QJc/sn-extension-error.png) `Error installing locally: error-downloading`, above the Deactivate button.

I tried with other community themes, like [Dracula](https://draculatheme.com/standard-notes) (which is served up from jsdelivr: [json extension](https://cdn.jsdelivr.net/gh/dracula/standard-notes/sn-theme-dracula.json) / [css theme](https://cdn.jsdelivr.net/gh/slybouhafs/sn-theme-dracula@0.0.15/dist/dist.css)), and I face the same issue.

Weirdly, certain parts of the CSS is applied - the collapsible dots for each label, the code editor background and the extensions /settings dialog background.

I am unsure why I get this error, as the Listed domain seems to be allowed, and other requests are going through just fine. I've tried on both Arch and Windows.

Any ideas what this is caused by, or what I may be doing wrong? Other than hosting the assets locally, or building SN from the source to modify the content controls headers, is there anything that I can do in order to load my stylesheet in? Thanks very much :)

**Comment by JaspalSuri** [comment]
Hi @Lissy93, I was able to install and view the Dracula theme extensions on the desktop apps for macOS and Windows 10. Usually there are CORS issues with the web app but not the desktop app, so this is a particularly peculiar issue. Can you share the link to the private Listed post if you're comfortable with doing so?

Are you self-hosting or using a different custom setup by any chance?

**Comment by Lissy93** [comment]
Thanks for your reply, hmm so this sounds like it's something I'm doing wrong then. 
Sure, here's the [JSON extension](https://listed.to/p/9Nggclsf0G), and here is the [CSS stylesheet](https://listed.to/p/ws16hyIrmT), and I'm testing it on the normal hosted instance, with Extended membership, on a Windows 10 device

Actually Dracula is working on Win 10, my mistake - it's just my theme which doesn't work (so more indicators pointing to something I've done wrong). Weirdly, some of the requests go through (which is how some parts of the interface are styled correctly), but mostly it just returns a ton of CORS errors. And things do work correctly on web and mobile. Here's what the console shows:

<details>
<summary><b>Network Tab</b></summary>
<img src="https://i.ibb.co/r23yLKr/sn-error-network-tab.png" />
</details>

<details>
<summary><b>Console Error</b></summary>
<img src="https://i.ibb.co/GQk5VhH/sn-error-console-tab.png" />
</details>

**Comment by JaspalSuri** [comment]
I'll get in touch with the team for further assistance with this issue. In the meantime, it might be worth hosting the CSS on GitHub or GitLab Pages, according to a comment made by another user.

GitLab Pages: https://github.com/standardnotes/web/issues/334#issuecomment-626436030
GitHub Pages: https://github.com/standardnotes/web/issues/334#issuecomment-636250525

**Comment by Lissy93** [comment]
Great, thank you very much. 
I'm just using the AppImage binary from the Releases tab.

**Comment by antsgar** [comment]
Hi @Lissy93! Thank you for reaching out.

For the desktop app, as a security measure the CSS file can't be downloaded from an external URL, but rather needs to be included in the extension's (in this case, theme's) source code. You can follow the steps under the "Local Installation" section in this page of the docs https://docs.standardnotes.org/extensions/publishing.

Basically, you would need to zip and upload your CSS file, together with a package.json file pointing the root of the extension to the CSS file. Easiest way to do this is to upload both files to GitHub, and create a release — this will create a zip file and give you a link for it. Once you have that link, you'd only need to add it to your extension's JSON file, as a "download_url", like this:

```
{
  "identifier": "com.aliciasykes.aht-theme",
  "name": "AHT StandardNotes Theme",
  "content_type": "SN|Theme",
  "version": "1.0.0",
  "description": "A dusty navy and neon turquoise theme",
  "url": "https://listed.to/p/ws16hyIrmT",
  "download_url": <your_zip_file_link>, --> add this line
  "dock_icon": {
    "type": "circle",
    "background_color": "#0b1021",
    "foreground_color": "#d6085a",
    "border_color": "#1EE3B5"
  }
}
```

Here's one of our own themes uploaded to GitHub which can provide some guidance, too https://github.com/standardnotes/titanium-theme

Please let me know if that helps, and don't hesitate to reach out if you run into any issues 🙂

**Comment by Lissy93** [comment]
Thank you :)

**Comment by JaspalSuri** [comment]
Feel free to let us know when you've updated the JSON. 🙂

**Comment by Lissy93** [comment]
Thanks very much for the help, so I uploaded the theme to a GH [repo - here](https://github.com/Lissy93/callisto-theme-standard-notes), and it works perfectly on the desktop app and mobile.

But when adding it via the web app, I again get a CORS error, however if I set it up on the desktop app, and then open up the web app, everything works great - so it's only the import process / fetching package details, on the website that throws as error.

![screenshot-of-console-error_web-app-cors](https://user-images.githubusercontent.com/1862727/112016453-a1871480-8b24-11eb-94c8-90482279f7de.png)

No big deal, since I can get it working with the desktop app, but I was wondering if there was anything that jumps out at you as totally wrong, that I'm doing. For reference, here's my [json file](https://github.com/Lissy93/callisto-theme-standard-notes/blob/master/callisto-theme.json), [css styles](https://github.com/Lissy93/callisto-theme-standard-notes/blob/master/main.css) and [package.json](https://github.com/Lissy93/callisto-theme-standard-notes/blob/master/package.json) via GitHub

**Comment by JaspalSuri** [comment]
>Thanks very much for the help, so I uploaded the theme to a GH repo - here, and it works perfectly on the desktop app and mobile.

On behalf of @antsgar, you're welcome! I'm glad to hear that! The theme looks great and it should be ok to update the Listed post that points to the JSON and add it to the README of your theme's repo. 

>But when adding it via the web app, I again get a CORS error, however if I set it up on the desktop app, and then open up the web app, everything works great - so it's only the import process / fetching package details, on the website that throws as error. No big deal, since I can get it working with the desktop app, but I was wondering if there was anything that jumps out at you as totally wrong, that I'm doing. For reference, here's my json file, css styles and package.json via GitHub. @JaspalSuri

It seems that you've set up everything correctly on your end 🙂; we're aware of the issue where some extensions can't be added through the web app.
