### ISSUE TITLE
Option to manually reorder tags in side bar

### ISSUE THREAD

**Issue by OddHouseGames** [standardnotes/forum#1269]
I had to add numbers to the tags in the sidebar to force them to display in a particular vertical order, it would be great if there was an option to manually drag and drop order, or to have a new settings section for 'sort tags by' which could be A-Z or manual.

**Comment by JaspalSuri** [comment]
Hi @OddHouseGames, thank you for your feedback! I'll add your +1 to this request. 🙂

**Comment by myreli** [comment]
Closing as duplicated of https://github.com/standardnotes/forum/discussions/2546 (which has more traction)
