### ISSUE TITLE
iOS11 app crashes on note save

### ISSUE THREAD

**Issue by nickAtWybar** [standardnotes/forum#127]
I've been using standard notes on iOS 11.0.2 (version 2.0 and 2.0.3) for some weeks now. Just a few days ago (I believe this was on version 2.0, but the problem still exists on 2.0.3), I noticed the app crashed on entry into any note.

I can view the note no problem, but as soon as I start editing, I assume it starts to try and save the note. So somewhere between 0.5 - 3 seconds into typing, the entire app quits unexpectedly.

thanks @mobitar for all your work, really appreciate it.

**Comment by mobitar** [comment]
Hey Nick, so this happens any time you try to edit any note? How many notes
does your account have in general?

**Comment by nickAtWybar** [comment]
I've tried again this morning and the problem seems to have disappeared - saving is great.

I have close to 1300 notes in the system with encryption before local save on.

Let's consider this issue closed until it happens again.

**Comment by mobitar** [comment]
Strange. Maybe it was some kind of network issue. Won't argue though ;) Let me know if it happens again.
