### ISSUE TITLE
[Help Wanted] Web client is not working

### ISSUE THREAD

**Issue by olodar** [standardnotes/forum#1270]
Hi there,
I'm trying to setup web client like this:
docker run -d -p 3001:3001 --env-file=.env standardnotes/web:stable
using this instruction https://github.com/standardnotes/web
env file:
```
RAILS_ENV=development
PORT=3001
WEB_CONCURRENCY=0
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true
SECRET_KEY_BASE=changeme123
APP_HOST=http://10.0.3.68:3001

EXTENSIONS_MANAGER_LOCATION=extensions/extensions-manager/dist/index.html
BATCH_MANAGER_LOCATION=extensions/batch-manager/dist/index.min.html
SF_DEFAULT_SERVER=http://10.0.3.68:3000

# Datadog
DATADOG_ENABLED=false

# Development options
DEV_DEFAULT_SYNC_SERVER=http://10.0.3.68:3000
DEV_EXTENSIONS_MANAGER_LOCATION=public/extensions/extensions-manager/dist/index.html
DEV_BATCH_MANAGER_LOCATION=public/extensions/batch-manager/dist/index.min.html

```
so syncing server running on address 10.0.3.68:3000 and working well with usual desktop client, but not with web; when I'm logging in web client I'm getting error: 
https://a.radikal.ru/a25/2103/01/75d3bc7e924b.png
and it is stuck on "Generating Login Keys...".

**Comment by mobitar** [comment]
This is the failing line of code: https://github.com/standardnotes/sncrypto/blob/004/packages/web/src/crypto.ts#L181

Looks like WebCrypto is not loaded in your browser for some reason.

**Comment by mobitar** [comment]
Try typing `window.crypto.subtle` in the dev console and make sure it's not undefined.

**Comment by olodar** [comment]
> Try typing `window.crypto.subtle` in the dev console and make sure it's not undefined.

Yes, it is wrote 'undefined'.
Not working in any browser, including FireFox - 'Uncaught (in promise) TypeError: crypto.subtle is undefined'

**Comment by mobitar** [comment]
In some browsers WebCrypto is not available in insecure contexts (like an http page as opposed to https).

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
