### ISSUE TITLE
Failed Daily Backup to OneDrive Sync

### ISSUE THREAD

**Issue by nevadaperry** [standardnotes/forum#1271]
```
We recently tried backing up your data to OneDrive Sync, but an issue prevented us from doing so.

The usual cause is an expired or revoked token from your sync provider. Please follow these instructions to use CloudLink on the web or desktop Standard Notes application to uninstall then reinstall this sync provider.
```

**Describe the bug**
Standard Notes sends me these emails on ~70% of days, starting on the day after successfully re-authenticating with OneDrive.

**To Reproduce**
1. Set up CloudLink with OneDrive.
2. If the initial sync fails, repeat step 1.
3. Wait until midnight 0-24 hours later for the daily backup failed email.

**Additional context**
This also happened regularly with Dropbox when I used that, a few months ago.

The Microsoft account associated with OneDrive has 2FA on by either phone or email. SN signs in to MS/OneDrive as an app and returns a code which I paste into the CloudLink setup.

**Comment by janpeeters70** [comment]
I'm experiencing the same problem. Thanks for a fix.

**Comment by nevadaperry** [comment]
Addendum. According to my emails, CloudLink with Dropbox never failed, or didn't email about it. I set CloudLink back to my Dropbox after creating this issue report and have had successful syncs since.

**Comment by mobitar** [comment]
Thanks for reporting this. We're aware of this issue and have created an issue with OneDrive here: https://github.com/OneDrive/onedrive-api-docs/issues/1463
