### ISSUE TITLE
nevermind have a splendid night!

### ISSUE THREAD

**Issue by soscrewedhelpmeplzzz** [standardnotes/forum#1272]
Apologies if I wasted anyone’s time reading this!
I’m an 
> idiot)

also don’t know how to delete this query/ total noob here in all ways poss...
But I figured out my issue

leaving all alone
Goodnight!

**Comment by JaspalSuri** [comment]
Hi @soscrewedhelpmeplzzz,

Sorry to hear that you were locked out of your temporarily locked out of your notes. 😔 I'm glad that you were able to figure it out! 😃 If you'd be willing to share the solution to the issue that you were facing, we'd greatly appreciate it as it might help other users experiencing similar issues.
