### ISSUE TITLE
I can't import a backup file [Help Wanted]

### ISSUE THREAD

**Issue by MarcSousbie** [standardnotes/forum#1275]
For some reason, the password from my password manager did not work anymore.

I exported my data, deleted my account, and created a new account.

Now, when I try to import the zip file that was exported by clicking on "Account'" then "Import Backup," I get the error message: "Unable to open file. Ensure it is a proper JSON file and try again."

When I try to import today's automatic backup (which is a JSON), I get the error message: "This backup file was created using an unsupported version of the application and cannot be imported here. Please update your application and try again."

I have not changed the application version. It is the Linux 3.6.3 AppImage. I also tried version 3.6.2 and got the same results.

Am I doing something wrong? How do I import my backup file?

**Desktop**
 - OS: Manjaro linux

**Comment by mobitar** [comment]
Be sure to import the .txt file inside the zip file, and not the zip file itself.

**Comment by MarcSousbie** [comment]
That worked. Thank you.

**Comment by JaspalSuri** [comment]
We're glad to hear that it worked, @MarcSousbie! Please let us know if you have any additional questions or feedback. 🙂
