### ISSUE TITLE
[Help Wanted] I can't see my protected notes in the app and there's no way to search for them?

### ISSUE THREAD

**Issue by jimnyo** [standardnotes/forum#1276]
As my subject line says I can't see my protected notes in the app, but I can see it in the Chrome web app. In the Chrome web app, I have to check a box that says search protected contents to but there is no such box in the app. Please help I need to access my notes!

**Comment by mobitar** [comment]
This same check box should now be available in desktop as of 3.6.3 👍 Also, Protected notes still appear in your list, but they are a little more subtle now. Be sure to check this out: https://blog.standardnotes.org/standard-notes-3-6-update/

**Comment by jimnyo** [comment]
> This same check box should now be available in desktop as of 3.6.3 👍 Also, Protected notes still appear in your list, but they are a little more subtle now. Be sure to check this out: https://blog.standardnotes.org/standard-notes-3-6-update/

@mobitar sorry if my question wasn't clear. Yes, I know that there is the check box on the web app. That is where I can search and find my protected notes. On my Android phone, there is no checkbox to search for protected notes and I cannot see my protected notes in the list of notes. How do I find my protected notes and view them on my Android phone app?

**Comment by jimnyo** [comment]
To clarify again, I searched for the title of my protected notes and nothing pulled up.

**Comment by jimnyo** [comment]
OK I finally found the protected note. But is there a way to search for a word in my protected notes?

**Comment by mobitar** [comment]
This feature will be released on Android this week :) You can grab it on the beta today if you'd like: https://play.google.com/apps/testing/com.standardnotes

**Comment by JaspalSuri** [comment]
Hi @jimnyo, the latest versions of the mobile apps contain this feature, so I am going to close this thread. Please let us know if you have any additional questions or feedback!
