### ISSUE TITLE
Currently selected note title disappears in Windows app

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/forum#1277]
**Describe the bug**
Currently selected note title disappears from the All Notes pane in the Windows App when scrolling through titles.

**To Reproduce**
1. Go to All Notes view in Windows app
2. Click on the last visible item in the All Notes pane
3. Use the down arrow to scroll down through the notes
4. The selected note title eventually disappear out of view

**Expected behavior**
The currently highlighted note title should remain in view in the All Notes pane while scrolling.

**Desktop (please complete the following information):**
-  OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by myreli** [comment]
It doesn't seem like this is an issue anymore, so I'll close it. Please re-open in case you run into problems. Thanks!
