### ISSUE TITLE
Down arrow does not advance to next item for note with no body text

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/forum#1278]
**Describe the bug**
Down arrow does not advance to next item when scrolling past a note with no body text in Windows App.

**To Reproduce**
1. Go to All Notes view in Windows App
2. Click on a note that has a title only - no body text.
3. Hit the down arrow to scroll to the next item.
4. Instead of going to the next item, the cursor is placed at the end of the title in the note.

**Expected behavior**
The down arrow should continue to the next note title in the All Notes pane.

**Desktop (please complete the following information):**
-  OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by affvalente** [comment]
Also happens when note has [ ] in the name

**Comment by JaspalSuri** [comment]
Hi @lnolan5017 & @affvalente, sorry for the delayed response. I was able to reproduce the issue in both cases, as well as for notes that are using certain editors, such as the Bold Editor. I'll create a report for the dev team to review.

**Comment by effieeee** [comment]
Already fixed!
