### ISSUE TITLE
Search inside a note?

### ISSUE THREAD

**Issue by axitkhurana** [standardnotes/forum#128]
Can I search for a phrase in the current note? cmd + f didn't work.

**Comment by mobitar** [comment]
There is no search highlighting in the desktop app currently. You can use the middle notes panel search to search note contents, but it won't highlight the results just yet. 

For now you can use the web app which will handle highlighting from the browser.

**Comment by jan-gerard** [comment]
Actually, I would like to be able to search within notes on the Android app.

**Comment by Kiminaka** [comment]
I would love this function as well. It's necessary in my daily use.

**Comment by RebelCodeBase** [comment]
This is the one missing feature (besides search & replace) that forces me to copy & paste text from standardnotes to a local editor regularly. It would be much appreciated!

**Comment by simonhurtz** [comment]
I miss a proper search function as well and consider it essential. But I think that there's an easier alternative to copying the text to a local editor: You can just temporarily switch to the Minimal Markdown Editor where you can search (ctrl/cmd + f) or search & replace (ctrl/cmd + shift + f).

**Comment by RebelCodeBase** [comment]
@simonhurtz Thanks a lot for the hint!

**Comment by kfeine** [comment]
Hi, for me it's THE missing feature in Standard Notes. I really hope to see it in a future release :)

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/1770
