### ISSUE TITLE
PayloadTooLargeError: request entity too large (when restoring a backup)

### ISSUE THREAD

**Issue by Svarto** [standardnotes/forum#1281]
**Describe the issue**
Selfhosted version here, moved to your standardnotes sync server with the docker setup. When trying to import my old backup, it works, but it refuses to sync to server and in the logs it gives the following error:

```
api-gateway_1               | PayloadTooLargeError: request entity too large
api-gateway_1               |     at readStream (/var/www/node_modules/raw-body/index.js:155:17)
api-gateway_1               |     at getRawBody (/var/www/node_modules/raw-body/index.js:108:12)
api-gateway_1               |     at read (/var/www/node_modules/body-parser/lib/read.js:77:3)
api-gateway_1               |     at jsonParser (/var/www/node_modules/body-parser/lib/types/json.js:135:5)
api-gateway_1               |     at Layer.handle [as handle_request] (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/layer.js:95:5)
api-gateway_1               |     at trim_prefix (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:317:13)
api-gateway_1               |     at /var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:284:7
api-gateway_1               |     at Function.process_params (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:335:12)
api-gateway_1               |     at next (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:275:10)
api-gateway_1               |     at internalNext (/var/www/node_modules/helmet/dist/index.js:86:6)
```

**To Reproduce**
Setup Standardnotes Sync Server, import old backup (my txt size is 400 kb), look at backend through ./server.sh logs and see an error as above.

**Expected behavior**
The imported backup correctly syncs to backend server

**Screenshots**
![image](https://user-images.githubusercontent.com/24279217/112885718-5d21e880-90d1-11eb-81de-1dbfad4d3892.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Desktop app
 - Version: 3.6.4

**Comment by mobitar** [comment]
I believe this is on @karolsojko's todo to look into ("PayloadTooLargeError: request entity too large").

**Comment by Svarto** [comment]
@mobitar @karolsojko super, let me know if I can help with additional testing or debug logs!

**Comment by karolsojko** [comment]
Yup - I have this on my list .. top 5 at most 😅

**Comment by karolsojko** [comment]
Fixed in: https://github.com/standardnotes/syncing-server-js/commit/e663a3d3d0f3454a438c8a99ae441b9bcd8a5cf4 `develop` (not safe for self-hosting).

Will ping in this issue once release to `master`

**Comment by Svarto** [comment]
Awesome! Looking forward and thank you!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by astingengo** [comment]
Any news?

**Comment by astingengo** [comment]
Any idea about when this will go to master?

**Comment by karolsojko** [comment]
We have the new standalone setup live now. Please read the instructions here: https://docs.standardnotes.org/self-hosting/getting-started/

Let me know if that fixes the issue

**Comment by astingengo** [comment]
Uh ... so founded the problem but not the solution.
If I'm exposing syncing-server-js on port 80 I'm able to sync with no issues
If I'm not exposing syncing-server-js at all and serve it via nginx on port 80, it is not working.
My nginx config is a basic one

`
# notes
server {
    # Listen on ipv4/ipv6
    listen 80;
    listen [::]:80;

    server_name notes.DOMAIN_COM;

	location ^~ /extensions {
		autoindex off;
		alias /opt/extensions;
		# CORS HEADERS
		if ($request_method = 'OPTIONS') {
		   add_header 'Access-Control-Allow-Origin' '*';
		   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		   #
		   # Custom headers and headers various browsers *should* be OK with but aren't
		   #
		   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		   #
		   # Tell client that this pre-flight info is valid for 20 days
		   #
		   add_header 'Access-Control-Max-Age' 1728000;
		   add_header 'Content-Type' 'text/plain; charset=utf-8';
		   add_header 'Content-Length' 0;
		   return 204;
		}
		if ($request_method = 'POST') {
		   add_header 'Access-Control-Allow-Origin' '*';
		   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		   add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		if ($request_method = 'GET') {
		   add_header 'Access-Control-Allow-Origin' '*';
		   add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		   add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		   add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
	}

    location / {
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        add_header Front-End-Https on;

        proxy_pass http://syncing-server-js:3000;
    }
}
`

**Comment by astingengo** [comment]
Fixed the problem:
`client_max_body_size 30M;`

thanks

**Comment by karolsojko** [comment]
Added to docs: https://github.com/standardnotes/docs/commit/dc5f9b741c47c2c379f2fef133226e1ed866aaa3

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
