### ISSUE TITLE
[Feature Request] Dark theme on Windows app 

### ISSUE THREAD

**Issue by ben981** [standardnotes/forum#1282]
Hi, I was wondering whether you were planning to add dark theme on the Windows app since the Android app has had it for a while now. I creave this update and I think it would be appreciated by so many users!

**Comment by JaspalSuri** [comment]
Hi @ben981, we plan to add a dark theme to the web and desktop apps at some point in the future, most likely around the time when we launch v4 of our apps. 

We currently offer several dark themes as a part of our [Extended plans](https://standardnotes.org/extensions) and members of the community have created some as well. 🙂

**Comment by ben981** [comment]
Great, thanks!

**Comment by Parkertg** [comment]
this can now be closed. Dark theme is included for free.

**Comment by myreli** [comment]
Thanks, @Parkertg!
