### ISSUE TITLE
Unable to Use Backup Explorer 

### ISSUE THREAD

**Issue by joshcsullivan** [standardnotes/forum#1283]
**Describe the bug**
When using the Backup Explorer in Batch Manager, I am able to chose the file, but when I enter the password and hit enter/return, nothing happens. I've tried this on SN Desktop Windows 3.6.4, SN Web 3.6.4. I've tried with an email backup as well as a cloud link backup, and manually exporting an encrypted backup.

**To Reproduce**
1. Open Extensions
2. Click Open under Batch Manager
3. Click Backup Explorer
4. Chose File
5. Enter password and click enter/return 

**Expected behavior**
Password should be accepted and the backup should be opened.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Brave (Chromium)
 - Version: 1.22.70 Chromium: 89.0.4389.105

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

**Comment by JaspalSuri** [comment]
Hi @joshcsullivan,

Sorry to hear that. There are some issues with the Batch Manager and we plan to deprecate it after replacing some batch management features in future updates. 

A workaround that you can use in the meantime would be to import the encrypted backup into an incognito or private browsing window and then use the Batch Manager, if needed, to delete several items and create a new backup or sign into a your account to import what remains in the [web app](https://app.standardnotes.org).

If you plan to import the modified backup later, it would be best to import it while signed out and then sign into your account.

**Comment by joshcsullivan** [comment]
Okay, that works for me, thanks!
