### ISSUE TITLE
iOS: Generating keys

### ISSUE THREAD

**Issue by ely-see** [standardnotes/forum#1284]
Hello,

When signing into the iOS app the app doesn’t log in. It stops saying generating keys.

Please advise.

Thanks and best regards,
Andreas

**Comment by mobitar** [comment]
Hi there, can you share which version of the app you're using, your iOS version, and also [DM](mailto:mo@standardnotes.org) me your account email?

**Comment by jkpmurray** [comment]
I’m also getting this issue. Been since the previous update and also this new one.

**Comment by mobitar** [comment]
Sorry about that, we've identified the source of the issue (signing in with non-upgraded account types), and will have a release out today. It's available now in our beta program:

Android: https://play.google.com/apps/testing/com.standardnotes
iOS: https://testflight.apple.com/join/H61MmmCA

**Comment by ely-see** [comment]
Thank you very much, Mobitar. Now it works.
