### ISSUE TITLE
Unable to sign-in on Android

### ISSUE THREAD

**Issue by efv80940** [standardnotes/forum#1287]
When I try to sign-in on Android, the app keeps on showing the message "Generating Keys". I'm using a Samsung Galaxy S8 with Android 9 and One UI 1.0. I've tried the app from Google Play  (version 3.6.5 3000269) and the apk from StandardNotes Website. I have no problem accessing my account and notes with the desktop app in Windows 10, Linux or the web version in Firefox

**Comment by mobitar** [comment]
Hi there, can you [email](mailto:mo@standardnotes.org) me your account email address?

**Comment by vuurvogelblog** [comment]
I have the same, I tried to download via auroradroid and to side load. First method fails to download, second method hangs at login in "registering keys"

**Comment by mobitar** [comment]
Sorry about that, we've identified the source of the issue (signing in with non-upgraded account types), and will have a release out today. It's available now in our beta program.

Android: https://play.google.com/apps/testing/com.standardnotes
iOS: https://testflight.apple.com/join/H61MmmCA

**Comment by vuurvogelblog** [comment]
Great! Is there a way to sideload the beta, I do not have a google account.

**Comment by mobitar** [comment]
You can download the APK here: https://github.com/standardnotes/mobile/releases/tag/3.6.6

**Comment by infosisio** [comment]
@mobitar I am sorry to post on another thread but I posted this issue right after I purchased extended: https://github.com/standardnotes/forum/issues/1286

Could I please have the same treatment? Thank you.

**Comment by mobitar** [comment]
Sorry, we're aware of this issue but don't have a fix yet. @karolsojko created an issue: https://github.com/OneDrive/onedrive-api-docs/issues/1463

Also here: https://github.com/standardnotes/forum/issues/1271

Typically @JaspalSuri will reply to most issues here, he must have overlooked these. I reply very seldom and only when I have specific info to give based on something I'm actively working on.

**Comment by infosisio** [comment]
@mobitar No problem, thanks for the response.

**Comment by JaspalSuri** [comment]
Hello everyone, the updated apps should be available for everyone to download from the [Play Store](https://play.google.com/store/apps/details?id=com.standardnotes) and [App Store](https://apps.apple.com/us/app/standard-notes/id1285392450). 

Hi @infosisio, I apologize for not getting back to you. I try to get back to users within 24 hours but have been trying to get caught up with the recent surge in tasks. I've made some adjustments on my end to help keep in touch with users more consistently. Rest assured that the issues you report are not being ignored.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
