### ISSUE TITLE
Imgur image not shown in Markdown-note 

### ISSUE THREAD

**Issue by odyon01** [standardnotes/forum#1288]
When I create a new note in StandardNotes for Windows, or mobile app, I use any of the Markdown editors (simple/pro), and add the following line, it will show a broken image link as shown in the screenshot below. The link itself https://i.imgur.com/dXau8BV.png is normally reachable.

`![image](https://i.imgur.com/dXau8BV.png)`

![image](https://user-images.githubusercontent.com/7446891/113260308-64faac00-92ce-11eb-97d5-d96f71fd315f.png)

**Comment by odyon01** [comment]
Ok, makes sense to close this issue. Pity that they block it. Thanks anyways.

**Comment by JaspalSuri** [comment]
You're very welcome! This is probably done to reduce costs related to bandwidth.
