### ISSUE TITLE
Unable to delete folders on the left side from the desktop app (Linux)

### ISSUE THREAD

**Issue by s-p-k** [standardnotes/forum#129]
Hi,

I just went for the extended version of standard notes.
I'm still not converting 100% from evernote but I'm still
testing the app although I really like the encryption
feature.

I noticed that in the Linux Desktop app when I'm trying
to follow this guide:

https://standardnotes.org/help/16/how-do-i-delete-a-tag

I'm still not able to remove the tag. Attempting to do the
same from the Android app works without issues.

I'm using standard-notes-2.0.41-x86_64.AppImage on
Linux.

**Comment by mobitar** [comment]
Hey, what happens when you click Delete in Linux? Is it clickable but nothing happens?

**Comment by s-p-k** [comment]
When clicking on the tag no option appears. So no "Delete" or any other option.
I just checked the OSX version as well. The same thing happens.

When clicking on a tag I only have the option of the [+] button to add a nested tag.

**Comment by s-p-k** [comment]
Ooops. That indeed works!

But I'm still confused:

Is there a clear distinction between folders and tags? Adding tags to a note will make them appear
as folders on the left side.

**Comment by mobitar** [comment]
The Folders extension is just a visual layer on top of tags. The underlying system is just tags. Folders makes use of dot separated tags. So when you nest "personal" under "blog", it will create a new tag called "blog.personal".
