### ISSUE TITLE
New to Standard Notes - query about attachments

### ISSUE THREAD

**Issue by srm39** [standardnotes/forum#1290]
Hi

I'm an ex-Evernote user who switched to Joplin and now testing Standard Notes, mainly because Joplin (although a great app) will not allow the app itself to be locked on a mobile device.

My question is about attachments. I've purchased Extensions, added the Bold Editor and have added attachments to a note (a PDF, a JPEG and a Word document.  I'm unable to view any of the attachments in the iOS app, although I can see that attachments exist. I don't want to download the attachments but I do need to view them. This is a dealbreaker if it's not possible, unfortunately.

Conversely, a JPEG I added using the iOS app is visible in-line in the note.

What am I doing wrong? I'm using File extensions and the Bold editor.

Thanks for any advice.

**Comment by JaspalSuri** [comment]
Hi @srm39,

You're not doing anything wrong. Currently the Bold Editor provides support for viewing embedded images that were uploaded via FileSafe to your designated cloud storage provider. Viewing and downloading attachments on the mobile apps isn't currently possible, but the dev team is currently working on (among other things) providing the ability to do so by having the mobile apps leverage (more) technologies from the platform it's running on.

**Comment by myreli** [comment]
[Files are now native](https://standardnotes.com/blog/introducing-encrypted-file-storage-with-automated-backups). It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
