### ISSUE TITLE
create separate note spaces / notebooks

### ISSUE THREAD

**Issue by xconnected** [standardnotes/forum#1291]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes

**Is your feature request related to a problem? Please describe.**
I want to maintain all my notes in a single place. Sometimes I share my screen with others while discussing a note (e.g. minutes). While doing that private notes are visible as well including some summarized content. Which I don't wanna share. 

**Describe the solution you'd like**
I would envision  a feature to create global filters, to hide notes with selected tags assigned. This way I can create my own note spaces.

**Describe alternatives you've considered**
Create second account would be an option with 2 shortcomings. They are completely not visually separated and require a sign off-sign on procedure which is too cumbersome to switch back and forth.

**Comment by joshcsullivan** [comment]
If you are on the Extended plan, you can use Views to accomplish this by assigning a tag to the notes that you need to show, for example, Public, then create a view:
```
!["Public", "tags", "includes", ["title", "startsWith", "Public"]]
```
When I'm going to be sharing notes, I tag them with Public, then before I start my screen share I select the Public view and hide the side bar so only the notes list is showing.

More on Views: [How do I view a list of untagged notes (and create other dynamic filters)?](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters)

**Comment by JaspalSuri** [comment]
I just wanted to add on to @joshcsullivan's excellent suggestion and share that you can click on the circle-shaped buttons on the left side of tags to collapse them. This way you can click on the circle next to `All Tags` to hide/collapse all of the tags that aren't smart tags or dynamic filters.

>Create second account would be an option with 2 shortcomings. They are completely not visually separated and require a sign off-sign on procedure which is too cumbersome to switch back and forth.

For what it's worth, you can sign into both the [web](https://app.standardnotes.com) and [desktop](https://standardnotes.org/download) apps simultaneously if you'd like to use multiple accounts without having to constantly switch accounts on the same client. You can install another [web browser](https://en.wikipedia.org/wiki/Web_browser) on your computer just for work and use the [web app](https://app.standardnotes.com) app there, if needed.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
