### ISSUE TITLE
$34 yearly subscription automatic renews?

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#13]
When you buy the $34 year subscription, does it auto charge your card automatically? Or is it a one time purchase and you have to manually renew it?

**Comment by mobitar** [comment]
It auto-renews every year.

**Comment by ClarkeCC** [comment]
@mobitar is there a way to just buy once without the auto-renew? I have the $4 subscription (for now) onces it's up I won't resubcribe for a few days, does the order I have my folder go away? or will everything go back to normal once I resubcribe?

**Comment by mobitar** [comment]
You can purchase the annual subscription and then cancel it right away. It'll stay active for the year but won't renew.

All data related to Extended is stored in your notes account, so nothing goes away when your Extended sub is up.

**Comment by ClarkeCC** [comment]
@mobitar perfect, Thank you!
