### ISSUE TITLE
Markdown Pro: keyboard behaviour

### ISSUE THREAD

**Issue by affvalente** [standardnotes/forum#1301]
Hi,

In Markdown Pro, the keyboard does not behave as expected in IOS: no text suggestions, keyboard doesn’t return to letters after a space after a comma, etc 

IOS 14.4.2
S|N 3.6.6

everything works normally with other editors

thanks
A

**Comment by JaspalSuri** [comment]
Hi @affvalente,

The Markdown Pro Editor was derived from the [Easy Markdown Editor](https://github.com/Ionaru/easy-markdown-editor). Feel free to [create a thread there](https://github.com/Ionaru/easy-markdown-editor/issues) for a more official answer. 🙂

**Comment by affvalente** [comment]
They will upgrade it when codemirror v6 is stable and has a few more features. Seems like it may take a while

**Comment by JaspalSuri** [comment]
Hi @affvalente, thank you for taking the time to look into that and for letting us know!
