### ISSUE TITLE
Creating Backlinks between notes

### ISSUE THREAD

**Issue by Cmhorn** [standardnotes/forum#1305]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I wanted to leverage the security of SN with my building a second brain project. Unfortunately the lack of support for document linking makes this a non-starter. 
**Describe alternatives you've considered**
I will go back to using Obsidian or Dendron instead, though they are not secure from a data / telemetry perspective. I will just have to come up with some sort of abstraction layer to obfuscate content, which makes those tools pretty much unusable. 

Late stage surveillance capitalism tools are the worst. 
**Additional context**

**Comment by JaspalSuri** [comment]
Hi @Cmhorn, thanks for the feedback! We plan to implement some form of note linking in the future as part of a long-term update. I am going to close this thread since it is similar to #723. 

Please let us know if you have any additional questions or feedback. 🙂
