### ISSUE TITLE
Zoom level widely unbalanced between interface and note content

### ISSUE THREAD

**Issue by bbeennjjnneebb** [standardnotes/forum#1308]
Since yesterday (possibly after updating to 3.6.8 on the macOS version), the zoom level of the content of my notes (the font size if you want) has become incredibly tiny, while all the rest of the interface (notes and tags lists etc.) has kept its regular appearance.
I can of course zoom in from the view options to get something more readable, but this makes the rest of the window massive.
This seems to apply mostly to Markdown Pro (which is my default editor) but possibly to the other editors as well (I cannot quite remember what their usual look was size-wise). I've tried reloading several times and uninstalling / reinstalling Markdown Pro to no effect.

<img width="1457" alt="Screen Shot 2021-04-28 at 2 21 50 PM" src="https://user-images.githubusercontent.com/61915147/116403011-5bad2280-a82d-11eb-9a81-332c8de60e69.png">

**Comment by mobitar** [comment]
Can replicate with the Markdown Pro editor, thanks for the heads up!

**Comment by johnny243** [comment]
Should be fixed now. Thanks for reporting!
