### ISSUE TITLE
[Help Wanted] Unable to set local password on iOS

### ISSUE THREAD

**Issue by alat-rights** [standardnotes/forum#1310]
**Describe the issue**
I'm on an iPhone 11, on the latest version of iOS. I wanted to enable storage encryption without creating an account, but there was no option to set a local password so that I can use storage encryption without an account.

**To Reproduce**
1. Go to hamburger menu on iOS
2. Click on cogwheel icon at the bottom right of the screen
3. See no option to set local password.
4. See no way to enable local storage encryption or FaceID lock without creating an account.

**Expected behavior**
It should be possible to create a local password on iOS and use it for local storage encryption without enabling sync.

**Screenshots**
If applicable, add screenshots to help explain your pr

**Smartphone (please complete the following information):**
 - OS: iOS 14.5.0
 - Standard Notes app is up to date

**Additional context**
I'm not opposed to having an account. If there was a way to have an account and disable sync then I would be happy to do that as well.

**Comment by alat-rights** [comment]
Never mind, I found that to encrypt locally you have to set a passcode under SECURITY. The option is not under account.

Also, I found that enabling biometric security was not enable to enable local encryption. 

I don't think these were very clear from the existing UI/UX, but my issue is resolved.

**Comment by JaspalSuri** [comment]
Hi @alat-rights, thank you for letting us know that the issue has been resolved. We are planning to redesign the apps in the future and are currently adding more features to them in the meantime.

**Comment by alat-rights** [comment]
Thank you, I appreciate what y'all do!

**Comment by JaspalSuri** [comment]
You're very welcome! Thank you for the support!
