### ISSUE TITLE
Closeable Folder Tags

### ISSUE THREAD

**Issue by dsuserds** [standardnotes/forum#1313]
It'd be great if I could collapse the tag-folders so it's easier to find certain subfolders with a few clicks (without scrolling) and if I share my screen only the relevant namespace(s) will be visible.

**Comment by JaspalSuri** [comment]
Hi @dsuserds, on the desktop and web apps, you can click on the circles next to each tag's/folder's name to hide the subtags beneath it. 🙂

As for the mobile apps, we plan to add a native folders feature that supports this ability at some point in the future.

**Comment by dsuserds** [comment]
Wow thanks, the circle was so small that when I tried that the first time I missed it!
