### ISSUE TITLE
Subscribers do not receive any notification when a new article has been published (LISTED)

### ISSUE THREAD

**Issue by pgiordanello** [standardnotes/forum#1316]
Hello, I am an extended user of Standard Notes and whenever I publish a new blog post with Listed my subscribers do not receive any notification/email. Could you please help me fixing this issue? Thank you in advance.
Cheers!
Paolo

**Comment by JaspalSuri** [comment]
Hi @pgiordanello,

Sorry to hear that. Just to make sure - does this issue persist even after you click on the option **Email Subscribers** in the **Actions** menu that appears after you have published a public post to your blog?

**Comment by pgiordanello** [comment]
Hi @JaspalSuri, I never noticed this option in the Actions menu. By clicking on it works perfectly. Thank you! The moderator can mark this query as closed.
Cheers
