### ISSUE TITLE
Extention CloudLink do not work

### ISSUE THREAD

**Issue by HHZZUUJH** [standardnotes/forum#1319]
I have set up CloudLink For Dropbox, Google Drive and OneDrive. 
The installation worked. 
The connections are set up and confirmed. 
If I use Perform Backup, this message appears in all three cases for 20 hours after setting up: 

“A Backup has been triggered for this provider. Please allow a couple minutes for your backup be processed.”

What can I do?

**Comment by JaspalSuri** [comment]
Hi @HHZZUUJH, sorry to hear that. Can you try performing another set of backups once more and let us know if it works? Have you checked the folders of each cloud storage provide to see if the backups were successfully saved? For example, in OneDrive, the backups would be located in the following directory: **Apps** > **Standard Notes** > **Month Name** (e.g. May).

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
