### ISSUE TITLE
Error loading your offline database

### ISSUE THREAD

**Issue by Brad2018** [standardnotes/forum#132]
I am new to using Standard Notes and need some help.

I am running Linux Mint 17.3
I downloaded the file "standard-notes-2.0.41-x86_64.AppImage" 
I made it executable with the command: chmod u+x standard-notes-2.0.41-x86_64.AppImage
I ran the command: sudo ./standard-notes-2.0.41-x86_64.AppImage
I followed the on screen instructions and created a Standard Notes icon to launch the program.
I logged in to Standard Notes and created a couple of notes and all worked well.
I installed the Standard Notes app on my OnePlus 5 Android phone.
I created several notes using my phone.
I tried to access my notes with my Linux machine but got the following error:
"There was an issue loading your offline database. This could happen for two reasons:

1. You're in a private window in your browser. We can't save your data without access to the local database. Please use a non-private window.

2. You have two windows of the app open at the same time. Please close any other app instances and reload the page."
I rebooted the computer. There are no other windows open. I still get the same error. No matter what I try, that same error pops up over and over. There is no browser open. I am not running another instance. There is only the one window open after a fresh reboot.

I appreciate any help. Thank you.

**Comment by Brad2018** [comment]
Update: I have installed Standard Notes on two other computers and they both work properly.  One is running Linux Mint 18.2 and the other is running Linux mint 17.3, the same as the first one. How strange.

**Comment by mobitar** [comment]
Usually this can be because there is another Standard Notes process running. You can either try hunting down that process, or restarting your computer.

**Comment by AtomicCons** [comment]
@mobitar 
Seeing this as well on a fresh install. tried both the .deb and appimage
