### ISSUE TITLE
[Help Wanted] Possible to delete/clean up remote note history?

### ISSUE THREAD

**Issue by bfaw** [standardnotes/forum#1324]
**Describe the issue**
I would like to know if there is a way to delete or clean up the Remote note history for notes. Based on my observations, I am able to see and restore remote note histories, but cannot remove them.

If there is not a way to remove them, I would like to know how long they are stored on the server.

I have tested this on the iOS version of the Standard Notes app as well as the Windows app.

**To Reproduce**
Steps to reproduce the behavior (on iOS):
1. Click on a note to open it
2. Click on the hamburger menu in the upper right corner
3. Select History to open the Note history window
4. Select the Remote option to view the list of saved revisions

**Expected behavior**
n/a

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 3.6.7

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 14.5
 - Version: 3.6.8

**Additional context**
n/a

**Comment by mobitar** [comment]
There is no way to delete remote history. The lifecycle of the revisions is tied to that of the note. So they are deleted when the note is deleted, or when your account is deleted.

**Comment by bfaw** [comment]
Thank you for the confirmation! So if I do not want to have the revisions available, I should just delete the note or copy the current contents to a new one?

Just for clarification, my concern is that if I put some sensitive information in a note and no longer want it there, it could still be accessed through remote history.

**Comment by mobitar** [comment]
> my concern is that if I put some sensitive information in a note and no longer want it there

Correct, the approach in this case would be to delete the note (from the trash as well), which would delete its history, then create a new note with the latest contents.

**Comment by bfaw** [comment]
Thanks so much for the quick reply! I appreciate it!
