### ISSUE TITLE
Accessibility - option to change font size

### ISSUE THREAD

**Issue by Marxsal** [standardnotes/forum#1331]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

Yes. If the developer ever lives a hundred years, he'll want this too.

**Is your feature request related to a problem? Please describe.**

AFAIK, there's no way, even with the extensions to easily change font size. I'm probably one of your older users. There's a lot of lip-service about accessibility these days. One of the easiest ways to make an application more accessible is to increase the font size.

**Describe the solution you'd like**

A way to set the base font size, either in the base app or in an editor/viewer without having to format the entire text.

**Describe alternatives you've considered**

You could use the bold editor, but then you would have to use html (or whatever it is the editor is using) instead of plain text. And you would have to edit (format) the entirety of the text when all you want is to make the text easier to read.

**Comment by antsgar** [comment]
Hi @Marxsal! How are you today? Thank you so much for bringing this to our attention. Including font size and font style settings as preferences is on our current roadmap 🙂 although we don't have a set timeframe for implementing it yet. In the mean time, here are a few alternatives for increasing the font size on all platforms —

- Web: You can adjust the font size in the browser's settings (this will change font size on all webpages). On either Chrome or Edge, you can do this by going to Settings > Appearance > Font size (to choose one of the default font sizes) or Customize fonts (to choose a specific font size). On Firefox, it can be done by going to Preferences > General > Language and Appearance > Fonts and Colors and choosing the size. You can also increase the zoom of the browser, either on Settings / Preferences, or by pressing Control/Command and +.

- Desktop: Zoom on the app can be increased by clicking on View on the top menu and using the Zoom In option, or by using the Control/Command and + shortcut.

- Mobile: Font size should be adjusted depending on the overall font size setting on your phone. Changing this preference depends on your particular device, if you could specify your device brand and model I could help you adjust this.

Please let us know if this helps a bit. Thank you for your feedback, and don't hesitate to write if you run into any other issues!

**Comment by effieeee** [comment]
Apart from Antonella's comment, font size customization is now available on the latest versions of the app :)
