### ISSUE TITLE
Apple M1 question

### ISSUE THREAD

**Issue by TBOTO** [standardnotes/forum#1337]
Out of curiosity, I have just downloaded the Standard Notes iOS app on my M1 MacBook Air and it works. The font is a bit small.

Anyway, which version is more resource efficient on M1, the iOS version or the intel desktop version?

Thanks

**Comment by JaspalSuri** [comment]
Hi @TBOTO, I would wager that the iOS app is more resource-efficient, but (aside from the inability to change the font size,) the iOS app does not generate daily local backups of your notes, tags, and other items unlike the (Intel) desktop app. We do plan to provide an M1 desktop app in the future as the libraries that the desktop apps depends on supports M1 Macs.

**Comment by TBOTO** [comment]
Thanks for the reply @JaspalSuri.
I look forward to using the M1 version in the future.

**Comment by myreli** [comment]
The desktop silicon package is now provided.  

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
