### ISSUE TITLE
[Help Wanted] Looking for fast way to enter notes on phone

### ISSUE THREAD

**Issue by MaudMan** [standardnotes/forum#1338]
Hi All:  I've been a Standard Notes user since the end of 2019. I've never found a way to quickly enter notes on iPhone or Android. For instance, other apps let you long press on the icon and select New Note, or say "Hey Siri, note to self..." and have that default to a certain notes app. Is there a way to do this with Standard Notes? I'm just looking for any tips to make it faster & easier to enter fleeting notes & ideas while driving or doing other things when I need to just quickly capture a thought or idea. Thanks!

**Comment by JaspalSuri** [comment]
Hi @MaudMan, there currently isn't a way to quickly add or share content to the mobile apps from outside of the app at the moment but it's something that we'd like to add in the future. 🙂

**Comment by myreli** [comment]
I will close this in favor of https://github.com/standardnotes/forum/discussions/2526

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
