### ISSUE TITLE
Local Themes Don't Style Everything

### ISSUE THREAD

**Issue by artinmg** [standardnotes/forum#1341]
I'm using an M1 Mac with MacOS 11.4 and Standardnotes 3.8.0. 

Following these directions: https://docs.standardnotes.org/extensions/local-setup/, I made a copy of the Solarized Dark theme by cloning https://github.com/standardnotes/solarized-dark-theme, and made an ext.json with the following content:

```
{
    "identifier": "org.yourdomain.my-extension",
    "name": "Solarized Dark",
    "content_type": "SN|Theme",
    "area": "themes",
    "version": "1.0.0",
    "url": "http://localhost:8001/dist/dist.css"
}
```

I then ran the following commands in my terminal in the cloned solarized-dark-theme directory:

```
npm install -g http-server
http-server -p 8001 --cors
```

I then imported the theme using http://localhost:8001/ext.json. It seems to import correctly but when activated only the extension window is themed, while the rest of the application seems to be the default theme:

<img width="1234" alt="screenshot" src="https://user-images.githubusercontent.com/68201207/121376978-fc542f00-c90f-11eb-9bf5-392fc97e064e.png">

If I toggle the developer console I see this error:

```
app.js:2 Refused to load the stylesheet 'http://localhost:8001/dist/dist.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self' http://127.0.0.1:45653". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
activateTheme @ app.js:2
```

Has anyone experienced this or know where to go from here?

**Comment by JaspalSuri** [comment]
Hi @miagit87, I'll get in touch with our dev team so that someone will be able to better assist you with this. 🙂

**Comment by miagit87** [comment]
Thank you, I got a solution from that! I simply added the theme manually to ~/Library/Application Support/Standard Notes/Extensions/<identifier> and it loads just fine after importing it. Ultimately I don't want to run it locally, but for a theme you may want to tweak it a bunch before publishing it.

**Comment by johnny243** [comment]
@miagit87 you can also use the web version of Standard Notes (i.e: https://app.standardnotes.org/) and develop your themes there in the meantime 🙂

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
