### ISSUE TITLE
Backup Explorer shows blank page on attempting to import

### ISSUE THREAD

**Issue by jwodder** [standardnotes/forum#1342]
After converting an export of an Evernote notebook using the Evernote converter (producing a file only 26 kB in size), I tried to import it by opening the Batch Manager, clicking "Backup Explorer", and selecting the file, only for the Backup Explorer window to go completely blank.  My notes were not imported.

 - OS: macOS 11.3.1
 - Standard Notes app 3.8.0

**Comment by jwodder** [comment]
The same thing happens when attempting to import in Firefox 89.0.

**Comment by JaspalSuri** [comment]
Hi @jwodder, sorry to hear that. We're aware of the issues with the Batch Manager and plan to phase it out completely. We may introduce replacements for some of its features in the future. (Currently the desktop and web apps allow you to select multiple notes in the notes list.)

As a workaround/alternative, I would suggest opening an incognito or private browsing Windows (in a Chrome-based browser), importing the backup via the **Account** menu and then verifying that everything there is ready to merge into your account before signing into it (and selecting the option to merge the locally stored data) or importing it to another instance of the web app that you're already signed into.

**Comment by effieeee** [comment]
Backup explorer and batch manager have been deprecated
