### ISSUE TITLE
VIM Editor stuck in insert mode - Android App (ChromeOS/Chromebook)

### ISSUE THREAD

**Issue by tommodev** [standardnotes/forum#1347]
**Describe the bug**

Using the Vim Editor on the Android app (ChromeOS/Chromebook), after one keypress in Normal mode, the editor switches to Insert mode. Pressing escape does not switch back to normal mode.

This means you cannot use normal mode operations (navigation, sorting, search etc) in the Vim editor.

**To Reproduce**

Steps to reproduce the behaviour:

1. Create a new note
2. Switch to the VIM Editor
3. Test an operation (e.g., k to navigate right)
4. Second press will be in insert mode ("k" inserted into document instead of navigation)
5. Press Esc to switch back to normal mode
6. Insert mode is still active

**Expected behavior**

Should be able to switch between Insert and Normal mode in the Vim editor.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: ChromeOS 92.0.4515.56
 - Android App Ver: 3.6.11 installed via Google Play Store

**Smartphone (please complete the following information):**
 - Device: Lenovo Chromebook Ideapad 3C
 - OS: ChromeOS 92.0.4515.56

**Additional context**

Testing in browsers on the chromebook via `app-beta.standardnotes.org`, the issue is reproducible there, so might be an android-keyboard-thing? The Chromebooks have an `esc` key, but there is a lot of jank around how the apps and keyboards behave across a few apps and webapps.

**Comment by mobitar** [comment]
The Vim Editor has largely been replaced by the Code Editor with a Vim mode button in the bottom right corner. We'll be removing the Vim editor from being offered standalone in the near future.

Can you see if this issue occurs for you in the Code Editor?

**Comment by tommodev** [comment]
Very cool! Being able to quick-toggle is sorta handy.

Field report on the code editor on the same setup as above: it looks like it's having issues.

**SN Android App**

It presents with the following in the top 1/3rd of the screen:

- Note title
- A single line edit box with free-text entry (not VIM or SN editor, more like default android text field)
- An empty language select drop-down (clicking the arrow doesn't work), and Enable vim mode toggle present.

It's like the editor is loading but then failing to load the note contents?

**Chromebook default chrome browser**

Code editor works fine! None of the issues that the Android app is having.

**Comment by effieeee** [comment]
Closing since Vim Editor is now deprecated
