### ISSUE TITLE
More consistent display of number of notes/tags on Desktop/mobile

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/forum#1349]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?** 
Yes

**Is your feature request related to a problem? Please describe.**
When viewing on the desktop platform, the number of notes is displayed under Views as follows: All notes 1439
When viewing on the Android app, there is no display of the number of notes and when I open the menu I see the count for notes + tags (1517). 

To do a quick verification that my android app has the same number of notes + tags, I have to open the Account menu on the desktop to see the same information.

**Describe the solution you'd like**
It would be better to show both the notes count and tags counts next to the All notes and Tags titles in both the desktop and app version. 

This would avoid any confusion over the counts matching on Android and Desktop and eliminate the extra steps of having to open menus to check.

![image](https://user-images.githubusercontent.com/81375814/122648605-fb818100-d0f7-11eb-94aa-0a2600af9fdb.png)

**Comment by JaspalSuri** [comment]
Hi @lnolan5017, thanks for the suggestion! We might keep these elements of the UI as is for now as we plan to make the Folders extension a native feature. We'll consider providing alternative ways of communicating the total amount of items synced to a user's account as we occasionally receive questions about it.

**Comment by myreli** [comment]
With the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon), which guarantees feature parity between all clients, we now have consistent note counts.
