### ISSUE TITLE
directly adding screenshot into note

### ISSUE THREAD

**Issue by superlooper615** [standardnotes/forum#1353]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
**Is your feature request related to a problem? Please describe.**
Can I directly add screenshot into note? Adding  it to filesafe just not convenience. 
**Describe the solution you'd like**
Take a screenshot -> copy to clipboard -> paste it directly into the note.

**Describe alternatives you've considered**
MS note

I really like SN and have a 5 year subscription on it. This is the only thing that's missing for me. Thank you!

**Comment by JaspalSuri** [comment]
Hi @superlooper615, while this currently isn't possible in the iOS or iPadOS apps, it should be possible within the web and desktop apps when editing a note that is using the Bold Editor.

**Comment by myreli** [comment]
This should also be possible now with the Super editor. It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
