### ISSUE TITLE
[Help Wanted] Android phone - Plus Editor Extension loading for every single attempt to open a note

### ISSUE THREAD

**Issue by iieeann** [standardnotes/forum#1357]
**Describe the issue**
Annoying delay of loading extension (Plus Editor) for ~1 sec for every single attempt to open a note, even the note has just been opened before it still need to reload the extension.  Switching between notes is very annoying on phone because of this delay.

**To Reproduce**
- Plus Editor enabled
- create a few notes with Plus Editor
- click on different notes and observe the slow loading for every single click

**Expected behavior**
Extension should have been loaded only once for the app upon startup, not on every single attempt to open a note.  on Windows desktop version there is no such delay with Plus Editor, switching between notes is smooth and fast.

**Screenshots**
-

**Desktop (please complete the following information):**
- Win10
- Dell Precision 7720 workstation

**Smartphone (please complete the following information):**
 - Device: Note 20
 - OS: Android 11
 - Browser: N/A
 - Version: 3.6.15

**Additional context**
I am switching from Evernote because it is getting more and more clumsy.  Their phone apps takes longer time to start, but once started it is ok and there is no such delay like Standard notes when switching between notes.  I would say for desktop version, Standard notes could be the winner for faster startup (15 sec Evernote startup!), but on phone Evernote is still better.

**Comment by JaspalSuri** [comment]
Hi @iieeann, sorry to hear that. The mobile apps currently do not store the editors offline, but this is something that we would like to add support for in the future. We've made some progress in this area but have noticed some issues with some of the editors that we need to fix before shipping support for offline editors.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
