### ISSUE TITLE
[Help Wanted] Emulating Apple Notes functionality

### ISSUE THREAD

**Issue by Pic146** [standardnotes/forum#1359]
Hello, 

I am switching from Apple Notes to Standard Notes for better cross-platform usability and security. 

I am looking for the extension that allows a similar checklist behavior whereby it's possible to mix formatted text with checklist items which move to the end of the list when a box is ticked. 

I downloaded the "task editor" but it seems to only allow for very basic checklist items and no other text in between the items. 

Any recommendations?

Thank you in advance.

**Comment by JaspalSuri** [comment]
Hi @Pic146, I'm afraid that there aren't any extensions that are offered as a part of [Extended](https://standardnotes.com/features) or by the [community](https://github.com/jonhadfield/awesome-standard-notes) that currently contain this exact functionality.

**Comment by Pic146** [comment]
Hello Jaspal, thank you for your response!
