### ISSUE TITLE
Tags without the # sign

### ISSUE THREAD

**Issue by vstepaniuk** [standardnotes/forum#136]
Is it possible to add tags without the # sign and to view them some other way?

**Comment by mobitar** [comment]
Which view are you talking about? The tags bar? No way to customize this currently I'm afraid.

**Comment by stepaniuk** [comment]
![screenshot from 2017-12-23 21-04-30_best](https://user-images.githubusercontent.com/24701640/34322141-204b8718-e828-11e7-9038-409780083b4b.png)

**Comment by mobitar** [comment]
No way currently, but you can check out the autocomplete extension: https://standardnotes.org/extensions/autocomplete-tags

**Comment by effieeee** [comment]
Tags can now be added without the hash mark, autocomplete extension is now a native app component :)
