### ISSUE TITLE
Option to filter the list by selecting multiple tags

### ISSUE THREAD

**Issue by jrcacd** [standardnotes/forum#1363]

**Comment by JaspalSuri** [comment]
Hi @jrcacd, thanks for the suggestion. 🙂 For what it's worth, if you're subscribed to [Extended](https://standardnotes.org/features), you can [create smart filters](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters) on the desktop and web apps that will only return a list of notes that contain certain tags.

**Comment by jrcacd** [comment]
Thanks, didn't know. This will really help.
However, I am often not near the PC and need to do quick searches. Filtering by multiple tags is really very useful in search.

**Comment by JaspalSuri** [comment]
>Thanks, didn't know. This will really help.

I'm glad to hear that!

> However, I am often not near the PC and need to do quick searches.

I completely understand; I've taken note of your feedback.

**Comment by myreli** [comment]
Duplicates https://github.com/standardnotes/forum/discussions/2515
