### ISSUE TITLE
I am finding the web and Android app really buggy

### ISSUE THREAD

**Issue by modernNeo** [standardnotes/forum#1364]
**Describe the issues**
Been using StandardNotes for about 10 months and now I finally gathered a list of all the usability issues I have had with StandardNotes.

**To Reproduce**
1. The preview of a note on desktop and mobile does not always seem to update
2. My default editor is the rich markdown editor and sometimes, when I insert a new to-do list item between 2 existing ones and paste some text there, I cannot place the cursor on the pasted text. I have to switch to another note and then go back to be able to edit the new item.
3. On mobile, I can't seem to set a default editor to match the editor I use on desktop, which means every-time I load a note, I have to manually change the editor on the app.
4. on mobile, its sometimes incredibly hard to delete a to-do list. if I keep doing backspace, it instead just goes to the previous to-do item and deletes the characters on that to-do item but leaves an empty to-do bullet below it.
5. I don't know if this can be fixed but, checking and un-checking a to-do item on mobile is frustratingly hard. I keep trying to click the to-do checkbox but apparently my thumb goes just a bit too far left or right and it instead scrolls up on the note. I then have to scroll back to where I was and try it again. Google Keep Mobile App was far better at this.
6. If I paste a video link on the web-app in rich markdown editor, it refuses to not embed the video. I have to switch back to plain text editor, paste the link and then switch to rich markdown editor

**Desktop (please complete the following information):**
 - OS: Debian
 - Firefox-Esr
 - Version 78.10.0esr (64-bit)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: grapheneOS
 - StandardNotes app installed with APK from standardnotes git repo release

**Comment by JaspalSuri** [comment]
Hi @modernNeo, sorry to hear that. Do all of these issues all pertain to notes using the Rich Markdown Editor? Since the dev team doesn't maintain the Rich Markdown Editor (it was provided by the community by adapting The Outline's editor), we can't provide fixes for it. 

>On mobile, I can't seem to set a default editor to match the editor I use on desktop, which means every-time I load a note, I have to manually change the editor on the app.

You should be able to press and hold on an editor's name to select it as the default editor. Does this work? 

>I don't know if this can be fixed but, checking and un-checking a to-do item on mobile is frustratingly hard. I keep trying to click the to-do checkbox but apparently my thumb goes just a bit too far left or right and it instead scrolls up on the note. I then have to scroll back to where I was and try it again. Google Keep Mobile App was far better at this.

Does this apply to the Rich Markdown Editor or the Task Editor? 

>on mobile, its sometimes incredibly hard to delete a to-do list. if I keep doing backspace, it instead just goes to the previous to-do item and deletes the characters on that to-do item but leaves an empty to-do bullet below it.

If this is related to the Task Editor, you should be able to delete a task by removing the task's text and then press enter/return.

**Comment by modernNeo** [comment]
> Do all of these issues all pertain to notes using the Rich Markdown Editor? For issues 2 & 6, since the dev team doesn't maintain the Rich Markdown Editor (it was provided by the community by adapting The Outline's editor), we can't provide fixes for it.

OK, I will make an issue on https://github.com/arturolinares/sn-rme instead for those.

>Is this for any note using any editor?

I am not totally sure about that tbh. I only ever use Rich Markdown Editor.

> You should be able to press and hold on an editor's name to select it as the default editor. Does this work?

That did work, thanks. But not intuitive imo. Did I miss instructions somewhere on the standardnotes website that state that that is how to do it on mobile?

>Do these issues pertain to the Rich Markdown Editor or the Task Editor?

Only Rich Markdown Editor.

**Comment by JaspalSuri** [comment]
Thanks for clarifying that these issues pertained to the RME. 🙂

>That did work, thanks. But not intuitive imo. Did I miss instructions somewhere on the standard notes website that state that that is how to do it on mobile?

Sorry to hear that; thanks for the feedback. 🙂 It's in the second set of steps on [this support article](https://standardnotes.com/help/69/how-do-i-make-an-editor-my-default-editor).

**Comment by modernNeo** [comment]
what about points 1, 4 and 5?

**Comment by JaspalSuri** [comment]
Since they all apply to notes using the [Rich Markdown Editor](https://github.com/arturolinares/sn-rme) (according to my current understanding), then separate issues would need to be created in [its repo](https://github.com/arturolinares/sn-rme).

**Comment by modernNeo** [comment]
ok. I have opened the issues on that repo

**Comment by JaspalSuri** [comment]
Thank you 🙂
