### ISSUE TITLE
Notes do not sync on Galaxy Tablet

### ISSUE THREAD

**Issue by Consoledotlog** [standardnotes/forum#1367]
**Describe the bug**
App won't sync notes on Galaxy Tab S7, I've cleared cache, cleared data, uninstalled/reinstalled the app, left the app beta, all with nothing changing it. The app before I cleared data, would still let me create new notes/view old notes, but it wouldn't sync anything from the tablet, or sync any changes made on other devices. I can use a browser to view/edit notes on the same tablet. The app just shows Loading Notes... in the main area, and after a few seconds Unable to Sync up in the top left. The app stopped working maybe a month ago... I am using a VPN, but my other devices still work with it and the app used to work with the VPN as well. 

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab S7
 - OS: Android 11 / OneUI 3.1

**Comment by JaspalSuri** [comment]
Hi @Consoledotlog, sorry to hear that. So, just to make sure, the app only doesn't sync when your device is connected to the VPN?

**Comment by Consoledotlog** [comment]
It actually doesn't work whether it's connected to the VPN or not, and the app still works on other devices connected to the same VPN.

**Comment by JaspalSuri** [comment]
Thank you for clarifying. We've received some reports of the app crashing when entering in the passcode or signing in on Samsung Galaxy Tabs, but haven't been able to figure out what's causing it yet. Hopefully it's related to this issue and will bring us closer to a potential fix.

**Comment by JaspalSuri** [comment]
Hello again @Consoledotlog, while the fix that was rolled out doesn't address the specific issue that you're experiencing, can you update the Android app (to [v.3.6.20](https://play.google.com/store/apps/details?id=com.standardnotes)) on your tablet and let us know if it's working again?

**Comment by Consoledotlog** [comment]
Yes that did fix it! Notes are syncing again both ways, thanks you all so much!

**Comment by JaspalSuri** [comment]
That's awesome! We're so glad to hear it!
