### ISSUE TITLE
Add an Org mode.

### ISSUE THREAD

**Issue by ryanpcmcquen** [standardnotes/forum#137]
Could be a near dupe of the [_Code_ editor](https://github.com/sn-extensions/code-editor), but with this special parser:
https://github.com/mickael-kerjean/nuage/blob/master/client/pages/viewerpage/editor/orgmode.js

**Comment by mobitar** [comment]
Thanks, will take a look at this.

**Comment by ryanpcmcquen** [comment]
I've started work on this, is the `ComponentManager` inherited from Standard Notes itself?

**Comment by mobitar** [comment]
Not sure what you mean. Some helpful links:
https://github.com/sn-extensions/components-api
https://docs.standardnotes.org/extensions/components.html

**Comment by ryanpcmcquen** [comment]
Mind taking a look at what I have so far?
https://github.com/ryanpcmcquen/standardnotes_org_mode_editor

**Comment by mobitar** [comment]
Looks to be in the right direction to me. Have you got it working?

**Comment by ryanpcmcquen** [comment]
I was just about to test it ... how do I create the install URL?

**Comment by mobitar** [comment]
See the "Installing" section in the doc link I posted above.

**Comment by ryanpcmcquen** [comment]
It's being plopped into the bottom of the current editor.
![screenshot 1514315323](https://user-images.githubusercontent.com/772937/34363028-2d30b92e-ea2d-11e7-9287-9d9dec158f5b.png)

**Comment by mobitar** [comment]
What's the URL you're using? `area` should be `editor-editor`

**Comment by ryanpcmcquen** [comment]
I was using:
```
https://ryanpcmcquen.org/standardnotes_org_mode_editor/?type=component&area=editor-stack&name=Org mode
```

Switching the `area` like you said fixed it. Doesn't seem to be saving though ...

https://ryanpcmcquen.org/standardnotes_org_mode_editor/?type=component&area=editor-editor&name=Org mode

**Comment by mobitar** [comment]
Seems to be some errors in the console. ComponentManager is not included and must be added to your assets manually.

**Comment by ryanpcmcquen** [comment]
Ah, that would explain it. Do I need it? What does it do?

**Comment by mobitar** [comment]
It communicates back with Standard Notes

**Comment by ryanpcmcquen** [comment]
Do I just grab it from here?
https://github.com/standardnotes/web/blob/master/app/assets/javascripts/app/services/componentManager.js

**Comment by mobitar** [comment]
No it's here https://github.com/sn-extensions/components-api

**Comment by ryanpcmcquen** [comment]
Thank you! Is there a CDN version I can point to or do I need to just manually include the file in my project?

**Comment by mobitar** [comment]
No CDN version currently, best to just copy it

**Comment by ryanpcmcquen** [comment]
Well, I definitely have it loaded in there now, and this works from the console:
```js
        let permissions = [{ name: "stream-context-item" }];
        componentManager = new ComponentManager(permissions, function() {
            // on ready
        });
```
But this error still shows up on page load:
```
script.js:87 Uncaught TypeError: ComponentManager is not a constructor
```

**Comment by mobitar** [comment]
I'd have to see your code. Push what you got

**Comment by ryanpcmcquen** [comment]
It's here:
https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/blob/gh-pages/script.js

**Comment by ryanpcmcquen** [comment]
You can check just the editor here:
https://ryanpcmcquen.org/standardnotes_org_mode_editor/

**Comment by mobitar** [comment]
Try renaming this https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/blob/gh-pages/script.js#L6 so that it doesn't conflict

**Comment by mobitar** [comment]
camelCase should do as that's what you use here https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/blob/gh-pages/script.js#L87

**Comment by ryanpcmcquen** [comment]
I bet that was it, I've pushed that. **Fingers crossed**.

**Comment by ryanpcmcquen** [comment]
Much better now. Is this warning typical?

![screenshot 1514317294](https://user-images.githubusercontent.com/772937/34363546-e2f6b408-ea31-11e7-8829-958b7c34c3bd.png)

Also, I am getting this error too:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
```

**Comment by mobitar** [comment]
The permissions dialogue is typical. 

Are you using localStorage? I don't think I've tested that..

**Comment by ryanpcmcquen** [comment]
Not that I know of? Most of the code is a pretty straight copy of the Standard Notes code editor.

**Comment by ryanpcmcquen** [comment]
That error seems to be totally unrelated. Now to get the Org mode part working.

**Comment by mobitar** [comment]
Could be minified, not sure. If you click on the inspector link, it will take you to the area of the code where that's being called.

**Comment by ryanpcmcquen** [comment]
Coming from:
chrome-extension://jeoacafpbcihiomhlakheieifhpjdfeo/scripts/vendor/port/port.js

**Comment by ryanpcmcquen** [comment]
This pretty much works now, but folding still isn't working. It's usable and at least offers highlighting for `.org` files. FYI, I grabbed the `ComponentManager` lib using [GitCDN](https://www.gitcdn.xyz/) (which I just found out about):

https://www.gitcdn.xyz/repo/sn-extensions/components-api/master/dist/dist.js

**Comment by mobitar** [comment]
Nice! GitCDN also looks pretty cool.

**Comment by ryanpcmcquen** [comment]
@mobitar, do you have any experience with CodeMirror folding? It seems to be the missing link for me in publishing this.

**Comment by mobitar** [comment]
No afraid not :/

**Comment by ryanpcmcquen** [comment]
Fixed as of this commit: https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/commit/346dcf6fa9bc34c29e448a06cb393671eb16e8d6

:tada: :tada: :tada:

**Comment by ryanpcmcquen** [comment]
Head here to install it!
https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/blob/gh-pages/README.md#install-link
