### ISSUE TITLE
Add grid view of notes

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#1371]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes. 

**Is your feature request related to a problem? Please describe.**
No. It is a brand new feature. 

**Describe the solution you'd like**
Add a **grid view** just like shown in the picture. And there is a button that I can switch the way notes are displayed. 
![Screenshot_20210708_204605_org fdroid fdroid~2](https://user-images.githubusercontent.com/87076776/124927377-2a24b480-e031-11eb-81e8-bf651d12d4a5.jpg)

**Describe alternatives you've considered**
None.
**Additional context**
The grid view is efficient, elegant and clear, so I sincerely hope it be added. Thank you.

**Comment by JaspalSuri** [comment]
Hi @denholm0hsun, thank you for the suggestion and screenshot! While it's not a part of our near-term or short-term plans, we may consider it when working on the app's redesign.
