### ISSUE TITLE
Icon file for Standard Notes (for use with appimage)?

### ISSUE THREAD

**Issue by cpuhog** [standardnotes/forum#1376]
Hi.  On my linux desktop I created a .desktop file in order to launch Standard Notes.  By default the icon is generic.  Is there an icon file I can download and reference in my .desktop setup in order to get things looking nicer?

Also, I searched and discovered desktop integration is no longer supported by electron-builder.  That's too bad.  The installation instructions still say "If you're prompted to create desktop shortcuts, choose Yes."  I wish!  Maybe that should be removed?

Thanks

**Comment by JaspalSuri** [comment]
Hi @cpuhog, thanks for the feedback! [Here's the link](https://github.com/standardnotes/desktop/blob/develop/build/icon/Icon-512x512.png) to the icon that you can download for the desktop app. 🙂 I hope this helps!

**Comment by cpuhog** [comment]
Perfect.  Thank you.
