### ISSUE TITLE
Android app crash observed in Secure Spreadsheets interaction

### ISSUE THREAD

**Issue by GlennSchner** [standardnotes/forum#1377]
**Describe the bug**
Standard Notes Android crashes when trying to view any note with Secure Spreadsheets turned on, except empty ones.

**To Reproduce**
1. Create Note (in any browser, app, etc)
2. Convert Note to Secure Spreadsheet (in any browser, app, etc)
3. Type anything or add any kind of data to an empty cell.
4. Exit note, and make sure it saved properly.
5. Attempt to open Spreadsheet Note in Android
6. Observe error message: "Standard Notes has stopped"

**Expected behavior**
Standard Notes for Android should be able to read, view, and edit native Secure Spreadsheets without issue, within reason.

**Smartphone:**
 - Device: Samsung Galaxy Note 8 SM-N950U1
 - OS: Android Pie 9 (28), last security patch 01 December 2020, Kernel 4.4.153-21498607
 - Standard Notes Version: 3.6.21

**Additional context**
Standard Notes Android may create and edit Secure Spreadsheets notes, but once I exit out of the note, I cannot view it again without crashing.
Upon crashing, there is an option to send feedback through Google Play services. I will do so if requested.
I do not know if this issue is reproducible on other Android devices. I cannot find open reports of a previous issue.

**Comment by JaspalSuri** [comment]
Hi @GlennSchner, sorry to hear that. 

Thank you so much for those details. Can you enable the **Error Reporting** option through the bottom of the settings page of the Android app, reproduce the crash, and then let us know which time (and the time zone; feel free to convert it to UTC for some additional privacy), the crash occurred? The team will then check to see if they've received an error message that can help them work towards a fix.

Also, are you able to reproduce the issue if you have an account, are signed in, have confirmed that all of your changes have synced to another app, and [reset the app](https://docs.standardnotes.org/troubleshooting/reset-apps/) without reinstalling it?

**Comment by GlennSchner** [comment]
Thank you very much for your response @JaspalSuri 

Error Reporting has been enabled; crash should have been reported at about 2am UTC on Mon, Jul 26. I crashed the app using a brand-new spreadsheet; labeled Test - the only edit I made to the spreadsheet was to type a few random letters into a cell.

Afterwards, I reset the app by deleting data and cache as instructed, signed back in, and reproduced the crash using the same spreadsheet as before. The data for the second crash should have been reported about 5 minutes after the first (I actually crashed the app twice after signing back in; I noticed after the first crash that error reporting got turned off after I reset the app).

**Comment by JaspalSuri** [comment]
You're very welcome, @GlennSchner!

Thank you for taking the time to do that and thank you for those details! 🙂 

For what it's worth, we (thankfully) cannot read the contents of your notes, even with error reporting enabled as it wouldn't involve your note's contents.

**Comment by jacksonMcode** [comment]
This same issue is happening to me. Today is the first time I have tried to use the spreadsheet editor.
Samsung Galaxy Note 8, Android Version 9
Standard Notes version 3.9.7 (3000314)

Android app crashes when trying to load any spreadsheet with data. Android app can create a new note with spreadsheet editor, but if data is put in even one cell, the app will crash when trying to re-open that note. The app also crashes when opening populated spreadsheets which were created on PC. Restarting phone did not help.
Hopefully this can be resolved soon! Let me know what more I can do to help.

**Comment by effieeee** [comment]
Spreadsheets now load more reliably on new mobile experience :)
