### ISSUE TITLE
Android app keeps crashinb

### ISSUE THREAD

**Issue by dh99taf** [standardnotes/forum#1378]
Just downloaded ver 3.6.21 via F-Droid on an Android version 8 Samsung Galaxy S7 phone. The app won't even open. Every time I try to open it, it crashes and says that the app has stopped.

**Comment by JaspalSuri** [comment]
Hi @dh99taf, I'm going to close this thread since it's a duplicate of https://github.com/standardnotes/forum/issues/1378.
