### ISSUE TITLE
bug - Mobil app won't open

### ISSUE THREAD

**Issue by dh99taf** [standardnotes/forum#1379]
Just downloaded ver 3.6.21 via F-Droid on an Android version 8 Samsung Galaxy S7 phone. The app won't even open. Every time I try to open it, it crashes and says that the app has stopped.

**Comment by JaspalSuri** [comment]
Sorry to hear that, @dh99taf. Can you reproduce this issue when using the [APK from GitHub](https://github.com/standardnotes/mobile/releases) or the app from the Play Store?

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
