### ISSUE TITLE
Feature request: Select multiple notes

### ISSUE THREAD

**Issue by krisovice** [standardnotes/forum#138]
Selecting multiple notes for batch processing (adding tags, archiving etc.) currently not possible. Any plans to add this feature in near future?

**Comment by mobitar** [comment]
I do have plans to add this as an extension component in the near future.

**Comment by msbentley** [comment]
Yes, this is a must - I was struggling just now to try and delete a bunch of test notes I'd created, but couldn't find a way...

**Comment by kengribble** [comment]
I'm also interested in this feature. Specific use cases would be:

- add, remove, or change a tag on multiple notes chosen by a tag, or search, or manually from "All"
- delete multiple notes
- Pin/unpin multiple notes
- Archive multiple notes
- Lock multiple notes

There could be more, but I'm just starting with Standard Notes!

Thanks for the great work!

**Comment by jjtk88** [comment]
+1

This would be fantastic!  Am struggling to select multiple notes.

**Comment by mobitar** [comment]
Btw, the Batch Manager has been released (available in the Extensions menu). It allows you to batch delete for the most part and nothing else. But perhaps in the future it will get the ability to do more than that.

**Comment by laurasue** [comment]
I would love to select multiple notes and change to Plus Editor for all of them. I'm importing a LOT of notes from Evernote and I like my formatting. It would be nice to batch change notes to Plus Editor, among other things like change tags, etc. ^^^ Thank you! :)

**Comment by andmib** [comment]
Is there a way to have this batch work to archive a bunch of imported notes? If not, what would be the best way of doing so?

**Comment by metbril** [comment]
I really hope selecting multiple notes and performing different actions on it (archive, delete, tag) will be possible in the **near** future. Do you have an ETA or can you at least confirm you are actively working on it? 🙏

**Comment by mobitar** [comment]
More of a long term priority. Not something I would expect any time soon.

**Comment by macariojames** [comment]
Any luck with this? I'm testing out the paid version now of Standard Notes, mainly importing batches of documents from Evernote and Notion, and it's a PAIN to have to delete these notes one by one.

**Comment by amccaugh** [comment]
I'm in the same boat -- not being able to delete several notes at once makes note management a bit more of a pain than it needs to be.

**Comment by tylerdq** [comment]
I am also highly interested in this feature and would use it a lot. Looking forward to seeing it in the future.

**Comment by bryvin** [comment]
This will be in an upcoming version of the app; not timeline yet but we agree this is a very needed feature.

**Comment by andreamoro** [comment]
Just want to add my few bits as an Evernote User willing to transition. 

I went straight for the $149 payment just because I have faith (and I hope this will be in a good place). That being said, not being able to select multiple notes and change the Editor in bulk to allow me consuming my Evernote notes straight off the book is a kind of a big pain/fail

Can you please advice?

**Comment by mobitar** [comment]
Something we're working towards for v4, which is a major redesign (no dates yet). For now you can make an editor your default editor by selecting the editor from the menu, then opening the editor menu again and choose "Set Default".

**Comment by ShuminKong** [comment]
i'll be staying on my icloud notes until this is finalized... can't be productive without this feature..

**Comment by echokos** [comment]
Wish I would've noticed this before paying for 5 years... ouch. Impossible right now to manage a lot of notes.

**Comment by JaspalSuri** [comment]
> Wish I would've noticed this before paying for 5 years... ouch. Impossible right now to manage a lot of notes.

If you've purchased it within 30 days, you should be able to get a refund by contacting help@standardnotes.org. 

That said, we should have this out within the next five years, keeping everything constant (e.g. no giant meteors).

**Comment by joeySeal** [comment]
This would make SN much more practical. For now if I wanted to so a bulk delete, is it possible to?

1. Decrypt the backup files
2. Delete notes as needed
3. Load backup

**Comment by daveQD** [comment]
I too would love to see this feature.  Just in the process of importing all my old Onenote notebooks.  Excited to hear what version 4 will bring..

**Comment by JaspalSuri** [comment]
Hi @joeySeal, sorry for the delayed response. To import backups and bulk delete items, please refer to [this support article](https://docs.standardnotes.org/troubleshooting/import-backups/) on decrypting and importing backups via the **Account** menu of the [web](https://app.standardnotes.org)/desktop apps (for 1 & 3), and then use the Batch Manager extension (located in the **Extensions** menu) to bulk-delete items (for 2) before signing in to merge what remains into your account.

Hi @daveQD, thanks for letting us know. We're excited for v4 as well. We currently plan to have this feature implemented before v4 is released. 🙂

**Comment by virtuallyvlad** [comment]
Looks like this is mostly implemented, at least on desktop and web, with v3.7.0.  You just can't change tags on multiple notes simultaneously.

https://github.com/standardnotes/desktop/releases/tag/v3.7.0
https://github.com/standardnotes/web/releases/tag/3.7.0

**Comment by antsgar** [comment]
Hi @virtuallyvlad! You can also add or remove tags on multiple notes by either right clicking on the notes or accessing the top-right overflow menu, and clicking on the Add tag option 🙂

**Comment by virtuallyvlad** [comment]
> Hi @virtuallyvlad! You can also add or remove tags on multiple notes by either right clicking on the notes or accessing the top-right overflow menu, and clicking on the Add tag option

Oops, my mistake.  Seems the tagging option appears if you have some tags already created.  With 0 tags, it's hidden.

**Comment by antsgar** [comment]
Oh yes that's correct, you'd need to have some tags available for the option to show up since new tags can't currently be created from the context menu

**Comment by effieeee** [comment]
Closing, already implemented :)
