### ISSUE TITLE
Add DayOne diary post in standardnotes actions

### ISSUE THREAD

**Issue by albdv** [standardnotes/forum#1388]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
yes
**Is your feature request related to a problem? Please describe.**
I like working with standardnotes very much and would like to do more actions from the single one place instead of switching across the apps

**Describe the solution you'd like**
I would like to have an additional Action to post to DayOne diary

**Describe alternatives you've considered**
Drafts editor have such an action and it was very convenient to use the editor to do everything from it. I switched to Standardnotes because of other issues, but I would like to have the same functionality

**Additional context**
No additional context

**Comment by JaspalSuri** [comment]
Hi @albdv, thanks for the feedback. We will probably not add any special integrations as it will cut into our already limited development time for other features, but it may be something that we might explore in the far future. 🙂

**Comment by albdv** [comment]
@JaspalSuri if so, is there any documentation available how I can add actions to the StandartNotes on my own? I would be interested to develop an action that I would be able to selfhost. Thanks in advance!

**Comment by JaspalSuri** [comment]
Hi @albdv, thank you for your interest in developing an **Action**!  You can review [the docs on creating **Actions** here](https://docs.standardnotes.com/extensions/actions).🙂
