### ISSUE TITLE
[Help Wanted] Can no longer sync or log in

### ISSUE THREAD

**Issue by BackedUpBooty** [standardnotes/forum#1389]
**Describe the issue**
After a few months of flawless operation over apps on 2x windows machines, 1x android phone and the web app (app.standardnotes.org) all of the apps in question have been reporting 'unable to sync' for the past few days. I signed out of the web app and was unable to log back in (it returns 'Unknown error' on the gui with an 'OK' box). I'm using a reverse proxy of https://standardnotes.mydomain.com using nginx within a swag container. I'm using a basic nginx config

I'm on a Synology 920+, and had followed the `git clone` and `./server.sh` setup and start processes successfully, so I removed all the containers and tried to set it up again. I get an 'OK' from the healthcheck, but nothing is able to sync or connect. Up til this issue started manifesting, the containers were working fine, and the logs seem to say that everything is working fine. 

I've copied logs into a pastebin (link below). 

I've noticed at least one other sync issue being raised, but I couldn't see a resolution that would work for me

**To Reproduce**
I'm not sure how I can suggest reproducing this error as I don't know how it's happened in the first place.

**Expected behavior**
All devices to sync successfully as they had done for the past few months. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - App v 3.8.18

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - OS: Android Version 11
 - App Version 3.6.22 (3000298)

**Additional context**

Pastebin for logs:
https://pastebin.com/G4NLVcXq

Like most things it's probably something I've done and not realised, but I'm having trouble tracking it down. Thanks for any help that can be given!

**Comment by mobitar** [comment]
Try running `./server.sh update`. Most likely your server version is outdated, which the latest client versions rely on.

**Comment by BackedUpBooty** [comment]
100% I should have tried that first, thanks. Wonder if you could help me with this next bit though as I'm unsure. I get this printout when running update:
```
error: Your local changes to the following files would be overwritten by merge:
        docker-compose.yml
Please commit your changes or stash them before you merge.
Aborting
```
I changed the container names in the docker-compose file when I first installed the app, and I'm not sure what `commit` or `stash` above refers to.

**Comment by BackedUpBooty** [comment]
Thanks for that. 

I've managed to update everything and get my compose file back to what it was, but unfortunately the issues listed in my original post still persist - logs still look good but cannot log in on app.standardnotes.org, and the device apps are stating 'Unable to Sync'. I've triple checked that the reverse proxy is working (I can access the healthcheck through it) and account details are correct, scratching my head at this.

**Comment by mobitar** [comment]
I'd say to throw out your existing containers and start anew, just to be sure (be sure to back up any account data).

**Comment by BackedUpBooty** [comment]
Yeah in the absence of any other ideas I think I may have to. Thanks for your support and taking me through a few things, appreciate it.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
