### ISSUE TITLE
Notes in iOS app “Waiting For Keys”

### ISSUE THREAD

**Issue by pc-bert** [standardnotes/forum#1390]
Some of my notes, currently 14 of 60, are not available for viewing/editing in the iOS app. The message displayed is “Waiting For Keys”.

All 60 notes are accessible in the Android app.

I’ve tried force closing and restarting the app, however this has no effect.

I’m not sure what the steps to reproduce this would be. I do notice that the unreadable messages are all at the bottom when I sort by “date modified”.

![B7DEA767-C882-44BF-B790-658D068D87C1](https://user-images.githubusercontent.com/88080348/128308534-6f2c1e0a-8e14-4f54-ad57-e1ec1eaa2264.png)

Let me know if there is any other information I can provide to help with debugging this and getting this fixed.

**Comment by mobitar** [comment]
Firstly, please export a backup from your Android app, just so this issue doesn't "sync over" to your other devices.

Then, sign into your account on app.standardnotes.org in a new session. Does all the data decrypt?

If so, you might just try signing out on iOS and signing back in.

**Comment by pc-bert** [comment]
@mobitar thanks for the support on this issue. I exported a backup file and then tried signing out of the web UI on app.standardnotes.com and signing back in. That does not seem to have had any effect on the issue I'm seeing in the iOS app. I'll try signing out of the app and report back on whether that resolved the issue or not.

For reference the iOS app version is: 3.6.22 (78)

**Comment by pc-bert** [comment]
Ok, signing out and signing in again did resolve the issue. Thank you.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
