### ISSUE TITLE
Trying to sign in on my second PC. Always getting "Unknown Error"

### ISSUE THREAD

**Issue by BrendonGriffiths** [standardnotes/forum#1391]
I tried uninstalling Standard Notes and downloading the latest version. Even then, after installing, I still get an "unknown error" after pasting in my username and password.

I have also tried deselecting "Merge local data" but still get the same error.

This is on Windows 10. I've also tried removing sessions from the PC where standard notes is working fine. I also tried clearing session data. Still no dice.

**Comment by mobitar** [comment]
Are you self-hosting your own server? If so you'll need to update your server to the latest version.

**Comment by BrendonGriffiths** [comment]
How do I check if I'm self-hosting my own server? How do I update the server?

Under advanced options upon sign-in to the PC where it is working, it says "https://api.standardnotes.com"

**Comment by mobitar** [comment]
In that case you're not self-hosting. Can you confirm the version number of the application you're using? It should be 3.8.18. You can see this number in the lower left corner inside the Account menu. If that is the correct number, then please email me your account email so I can investigate further. My email is in my bio.

**Comment by BrendonGriffiths** [comment]
Yes it's on version 3.8.18. I will email you now. Thank you.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
