### ISSUE TITLE
Unknown error, while trying to login in on a Mac

### ISSUE THREAD

**Issue by pagenstedt** [standardnotes/forum#1393]
I opened an account on ios today (worked fine) and just tried to log in a few times on my mac. After a while "generating login keys" I always receive the Unknown error message, as others obviously do as well. I cleared the session cache and even reinstalled the app, but nothing helps. Version # is 3.8.18.
Would appreciate your help.

**Comment by JaspalSuri** [comment]
Hi @pagenstedt, sorry to hear that. Are you using a VPN on your Mac by any chance? Can you share your username with us at help@standardnotes.com or protonmail@standardnotes.com?

**Comment by pagenstedt** [comment]
Thanks, i sent you an email.
