### ISSUE TITLE
Dark theme not working on macOS 11.5.1

### ISSUE THREAD

**Issue by busbit** [standardnotes/forum#1395]
**Describe the bug**
The dark mode for the desktop app on macOS Big Sur 11.5.1 will not apply. I've tried both running system preference(dark) and selecting dark from the drop down menu to no avail. 

**To Reproduce**
1. Toggle Developer Tools via View>Toggle Developer Tools
2. Click on 'Settings' cog in top right corner
3. Under Appearance select 'Theme>Dark'

**Expected behavior**
A dark appearance for the desktop app. App continues to appear with a light theme even after restarting desktop app. 

**Screenshots**
![Screen Shot 2021-08-12 at 2 37 21 PM](https://user-images.githubusercontent.com/88857220/129266305-be4cb893-f707-4a22-945c-7fbd7677d42d.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.1 
 - Desktop App
 - 3.8.18

**Comment by JaspalSuri** [comment]
Hi @busbit, the app currently doesn't come with a free dark theme but will in the future as a part of our long-term roadmap. The dark theme within the developer tools appears to be just for the developer tools window. The desktop app currently doesn't follow the system light and dark modes, even if a dark theme is installed, but once the themes are installed, it's easy to quickly toggle them on. You can install the themes that we offer as a part of [our Extended plans](https://standardnotes.com/features) or the themes that are provided by the community.

**Comment by myreli** [comment]
New versions of the app include a dark theme and follow OS preferences. It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
