### ISSUE TITLE
Each extension is listed twice

### ISSUE THREAD

**Issue by SuppenGeist** [standardnotes/forum#1397]
**Describe the bug**
In the extensions overview I see each extension listed twice. Like this
E1,E2,E3,E4,...,E1,E2,E3,E4
As if the list of all extensions is fetched twice.

**To Reproduce**
1. Open the extensions overview

**Expected behavior**
Extensions are not listed twice

**Desktop:**
 - OS: arch + bspwm
 - Desktop app, 3.8.18

**Comment by JaspalSuri** [comment]
Hi @SuppenGeist, sorry to hear that. I'm afraid that you'll have to uninstall the duplicate extensions. Do you recall anything significant happening before you ran into this issue? Did you sign into a new device, use the app after a while, or update the desktop app recently?
