### ISSUE TITLE
A little confused, how do I activate a theme?

### ISSUE THREAD

**Issue by mrtargaryen** [standardnotes/forum#14]
I have loaded the theme link into the extensions section but I'm not sure how to activate the theme. How do I do that? Thanks.

**Comment by ClarkeCC** [comment]
Just click the theme you would like to use and a activate button should appear, click that and you should see the change. This also work if you want to deactivate the theme.

Note: Some themes won't work unlesss you have a subscription.

**Comment by porcupinepete** [comment]
Thank you very much.

**Comment by ClarkeCC** [comment]
@porcupinepete no problem, here to help.
