### ISSUE TITLE
Hard to determine difference in duplicated files

### ISSUE THREAD

**Issue by supermensa** [standardnotes/forum#1400]
When a user edits a file and it somehow doesn't sync, a new file (of the same name) is created by standard notes.

In the mobile app, as well as desktop, it is impossible to know which file is latest or see a diff style comparison of what file the user might prefer to keep and which to delete.

**Comment by JaspalSuri** [comment]
Sorry to hear that, @supermensa. I'm afraid that users will need to use an offline text-diff tool in order to determine the difference. I'll take note of the enhancement for providing in-app text diff feature if possible.

**Comment by supermensa** [comment]
- A suggestion to this would be to question why it doesn't just merge the difference automatically - instead of having to identically named files which are impossible to diff without another piece of software.

**Comment by supermensa** [comment]
I understand that this might be a problem, but the other case is that you end up with two, possibly large, and it is not immediately possible to know which one is the latest, especially on a mobile. Thus you can end up with a large amount of duplicate files due to bad network connections (especially if you're on the go).

**Comment by myreli** [comment]
Duplicates https://github.com/standardnotes/forum/discussions/2602
