### ISSUE TITLE
[Help Wanted] Linux desktop app stuck on "generating login keys" when logging in for the first time

### ISSUE THREAD

**Issue by avatar382** [standardnotes/forum#1405]
**Describe the issue**
I can't log in to the desktop app, it's stuck on login with a message "Generating login keys" for more than 20 minutes (and taking up significant CPU). No errors in console in developer tools. If I click on the menu again, the error disappears and the generating login keys message goes away.

If I try to log in again, I get an error "Tried to sign in when an account already exists." in the JS console in developer tools, with the login dialog again showing "Generating Login Keys".

**To Reproduce**
1. download and run SN app image
2. login with username and password
3. app stuck on "generating login keys"

**Expected behavior**
Generating login keys is expected to take a few seconds at most and then log me into my account.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04.3
 - Desktop app 3.8.18

**Additional context**

**Comment by avatar382** [comment]
Update -- problem is gone after installing a different Linux distribution. Using Xubuntu 20.04 (was running Cinnamon before) I'm able to run the AppImage without issues. Not sure what caused the problem in the first place, might have been the system keychain setup in that instance?

**Comment by JaspalSuri** [comment]
Hi @avatar382, I'm sorry to hear that you were experiencing issues with the desktop app on the Cinnamon DE. It's possible that it has to do with the Keychain setup, but we'll have to take a closer look to know for sure. I would suggest exporting a backup of your notes just in case this issue resurfaces in the future.
