### ISSUE TITLE
Android Issue

### ISSUE THREAD

**Issue by ps122** [standardnotes/forum#141]
All of my notes in Android telephone (Android 7) display as html code.   Reading the note under those conditions is a PITA,    Any solutions out there?

**Comment by mobitar** [comment]
This happens when you use the Plus editor to edit your notes on web or desktop. Currently editors are not supported on mobile, so I recommend only using the Plus editor for notes and documents you plan to edit primarily on your computer.

**Comment by mobitar** [comment]
@liquidsunshine please see https://standardnotes.org/help/12/why-are-extensions-not-available-on-the-mobile-app

**Comment by liquidsunshine** [comment]
@mobitar Thanks for the context.  It helps to know that the plan is to focus on the web/desktop apps.  I had missed that detail previously.
