### ISSUE TITLE
Constant Crashes in Android 11 Samsung One UI 3.1 Galaxy S20 5G

### ISSUE THREAD

**Issue by S1588** [standardnotes/forum#1410]
Hi,
I have been a Standard Notes user for 2 years and have a 5 year subscription.

I want to re-iterate the poor usability of the mobile app for anything other than viewing pre-existing notes or writing new notes, only in the basic theme. The mobile app always takes absolutely ages to load (12s to be able to scroll or search through notes). I still use it extensively on desktop nonetheless. 

But I have another serious issue on mobile, that if i spend more than a few minutes editing, it is guaranteed to crash. When I restart the app, and search for the note again, I has normally made a conflicting duplicate and I have to look in both copies to see which one  I should be editing. Its an absolute nightmare, and it gives me a background anxiety whenever I'm using the app. It used to do the same thing on my S8, even when I had far less notes. 

Can you think why this is happening / solve it?

**Comment by JaspalSuri** [comment]
Hi @S1588, sorry to hear that. Please try the following:

1. Export an encrypted and decrypted set of backups via the settings page of the app and the desktop app
2. Verify that the backups actually have content and are successfully imported into the web app running in an incognito/private browsing session of your preferred web browser
3. Follow this guide for [resetting the Android app](https://docs.standardnotes.org/troubleshooting/reset-apps/)
4. After restarting the app and signing in, enable error reporting at the bottom of the app's settings page (you can always disable this later)

If the app still crashes at some point in similar circumstances, please do the following:
1. Take note of the time of the crash
2. Comment here with the time of the crash and the time zone you're in or convert it to UTC for additional privacy. You can also say that it happened X minutes ago
3. With error reporting enabled, we can look into the error logs that we've received and filter it down to the device you've mentioned at the time of the crash and check to see if we've received any helpful details that might give us clues as to what caused the crash.

Some other information that might help us:
- Which editors are you using on the mobile app, if it isn't the plain editor?
- To clarify, are you saying that no theme has been applied to the Android app?
- What is the size (in characters, words, or bytes) of the note you were editing when the application crashed?

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
