### ISSUE TITLE
Undo in Android

### ISSUE THREAD

**Issue by khalil-i-o** [standardnotes/forum#1412]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes, and there is a difference between crazy functions and elementary functions. I think this one should fall into the elementary range.

**Is your feature request related to a problem? Please describe.**
Virtual keyboards in mobile applications are unstable, lack functions (Control + Z, Control + Y) and making a mistake results in having to perform 8 steps to try to undo a typing error. It's torture to make a mistake, whether you deleted it or pasted text in the wrong place, backtracking is an unfortunate process.

**Describe the solution you'd like**
Have an accessible and quick button to undo or redo changes. Perhaps the synchronization and history interval should be extended so that it can be properly integrated.

**Describe alternatives you've considered**
Make note history intuitively accessible.

**Additional context**
Make it not a bureaucratic process to correct errors while typing.

**Comment by JaspalSuri** [comment]
Hi @khlinuxdeveloper, we currently do not plan to provide support for undo functions as it might work with varying success across different versions and different flavors of Android. However, we do provide a **History** feature that provides local and remote (if you're signed in) sets of histories for each note, that could be used to restore earlier versions of notes, that are saved 5 minutes apart.

**Comment by Xenthur** [comment]
Hi, I know it was stated that undo functions were not planned, but up until the latest update on Android I actually was able to use an undo (and redo) button from the cursor menu, but that no longer seems possible with the latest release. I just wanted to know whether this was an intentional change.

**Comment by effieeee** [comment]
Hi @Hunter-K13, sorry to have to ask, but may I know what the cursor menu you were referring to is? 😅 Is it something exclusive to your keyboard?

**Comment by Xenthur** [comment]
I'm not sure exactly, but it appears in the same menu with Paste that pops up when I long tap the screen. I'm using the built-in Samsung Keyboard on my Galaxy S10. I reverted to the older version to show:

![Screenshot_20221020-155915_Standard_Notes](https://user-images.githubusercontent.com/5891579/197047117-d4a52784-1479-487a-b057-d7e230e3baf8.png)

It functions as expected, with the only caveat being that the undo-redo history is cleared if I exit the editor.

**Comment by Xenthur** [comment]
After some testing I think this is actually a feature of my keyboard, in which case I think it may also be related to the issue I opened regarding autocorrect since both are keyboard features that no longer function on Plain Text notes in the newest version.

**Comment by effieeee** [comment]
Thank you for clarifying! Actually for the undo function, that isn't specific to the keyboards, so it is the context menu that appears while entering text, thanks for sharing a screenshot to show it! In this case, yes, I do notice that Undo and Redo are no longer available actions on Plain Text. I'll open this as a new issue, referencing your comment here 🙏

**Comment by myreli** [comment]
Closing so we can track under https://github.com/standardnotes/forum/discussions/2759
