### ISSUE TITLE
[Help Wanted] Unable to access an important revision (Rich Markdown Editor)

### ISSUE THREAD

**Issue by joshl129** [standardnotes/forum#1423]
**Describe the issue**: Additions I made last week (call them "A notes") are absent from the current version of the note ("N"). Non-A notes are there, but A notes aren't. I tried to restore N to the version after I added A notes (~6:40 pm last Tuesday), but I can only restore to 1 version from earlier that day (2:06 pm). 

There are 23 "Remote" revisions within the history tab, but all say "Invalid Date", whether I load it from my phone, browser, or computer app. Clicking any of them produces the following pop-up: "The remote revision could not be loaded. Please try again later", with "OK" as the only option. Clicking the "Options" button next to "Remote" on the browser or computer app reveals a drop-down tab that says: **"Refresh** /Fetch history from server.". Clicking this does nothing, nor does manually refreshing.

**To Reproduce**
1. Go to note N. 
2. Click "History"
3.1. Click any of the options listed as "Invalid Date"
3.2. Click "Options" next to the tab listed as "Remote".
3.3. Click the "Refresh" button below the Action Bar.

**Expected behavior**: After (2), I think there should be actual date-times, including from ~6:40 pm last Tuesday (after I added A notes to N). I think I should be able to click any of them to preview and/or restore their content. In that way, I believe I should be able to retrieve the A notes. (These are important to me in a time-sensitive way because they're from a first interview that I'm following up on tomorrow 😬 )

**Screenshots**:
![SN restore issue - History](https://user-images.githubusercontent.com/21348060/135211632-f00dd252-953a-4ef5-b693-fe39707ac88b.png)

![SN restore issue - remote revision error](https://user-images.githubusercontent.com/21348060/135211659-8b9236d6-105e-4217-bd07-f348aa9196e4.png)

**Desktop**
OS: Ubuntu 21.04, 64-bit, GNOME 3.38.5
Browser: Firefox 92.0 (64-bit) (Mozilla Firefox Snap for Ubuntu canonical-002 - 1.0)
App: 3.8.21 (downloaded via Ubuntu Software Store)
Version: ? (I'm not sure what this is referring to)

**Smartphone**
Device: Google Pixel 3a
OS: Android 11, CalyxOS 2.9.0 
App: StandardNotes 3.6.8 (3000277)
Version: ? (I'm not sure what this is referring to)

Edit: I was using the [Rich Markdown Editor](https://github.com/arturolinares/sn-rme) in all versions of the app.

**Additional context**: While this is the only potential data loss I'm aware of with SN, a small sample of other notes suggest that the issue is universal for all my notes. That is, each of them shows x # of Remote revisions but also x # of "Invalid Date" tabs. Of the tabs I tried clicking, I just get the same error output message listed above. None of them shows any Session revisions (cf. N, which at least showed two Session revisions). This is highly concerning to me.

**Comment by stifle-hue** [comment]
Getting exactly the same error on one particular important note.

**Comment by mobitar** [comment]
@joshl129 it looks like you're using the 3rd party editor Rich Markdown Editor, which has been previously reported to have issues of data not saving properly. I don't know the extent of the issues, but most likely it has an issue with trailing saves (the final edits you make to a note before closing the app or switching to another note).

The remote history invalid date is new to me however. Can you email me your account email + the UUID of this note? You can get the UUID by download a decrypted backup then finding the note in the resulting text file.

@stifle-hue if you can do the same that would be great. Email is in profile.

**Comment by joshl129** [comment]
@mobitar thank you for the prompt reply. I should have had the impulse to change the editor, and yes when I do that I'm able to access the Remote revisions as expected (date-times listed, not "Invalid Date"). 

I'm also noticing that changing the Editor back to Rich Markdown Editor, I'm also able to access the revisions as expected. I didn't think to check this first, which might have helped determine if it was just a timing issue or if it just needed to be "reset" (if I'm using that term correctly - in the sense of switching away from and then back to RME). 

I'm still unable to access the A notes, but noted that it's probably an issue with RME. I will also email you the info you've requested.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
