### ISSUE TITLE
[Help Wanted] [Self-hosting] Any admin tools to manage/monitor the service

### ISSUE THREAD

**Issue by melbv** [standardnotes/forum#1424]
**Describe the issue**

Hi team - having just installed a SN server, i first & foremost wanted to thank you for the great work (tutorial is clear and script to deploy through docker very easy).
I had a quick question on admin activity though. Although I understand that the .env file gives some flexibility to tailor the behaviour of the server, I was wondering if there were cmd-line functions or some sort of admin panel to perform a few tasks: control the # & ID of users on my server (i know there is the option to close the server to new subscribers but is quite binary), monitor any type of tasks such as cron or other in the background, some sort of email alerts when users perform certain tasks, etc...).
I am not sure if this exists not having found docs on the website to that particular purpose.
Thanks in advance for any response on this (and sorry if the question was already asked).

**To Reproduce**

**Expected behavior**
Repo of CLI commands or URL to an admin panel after deploying the self-hosted version of SN

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser [any
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**
Request whether an admin feature exists for self-hosted SN server

**Comment by melbv** [comment]
Thanks @mobitar for your swift answer & suggestions. When you say 'right now', are you planning on potentially develop one in the future?
I'll have a look at tapping into the db through a client in the meantime!

**Comment by mobitar** [comment]
We don't have any concrete plans just yet, more in a casual brainstorming phase.
