### ISSUE TITLE
[Help Wanted] How do I combine different tags?

### ISSUE THREAD

**Issue by yozamacs** [standardnotes/forum#1425]
**Describe the issue**
Sometimes I end up mistagging items and then I end up with two of the same tags (think work twice). Is there a way to move all notes with one tag to another tag? I also can't wait for the features that allow people to drag note to tags. Then I would never have this problem! Typing the tags is so tedious.

**Comment by JaspalSuri** [comment]
Hi @yozamacs, you can use the [web](https://app.standardnotes.com) or desktop apps to select the _wrong_ tag in the tags pane to filter down your notes list, select the note at the top, press and hold the shift key, select the last note, release the shift key and right click the selection, and then apply the correct tag. Finally, delete the tag that you don't want to keep from the tags pane. 🙂

> I also can't wait for the features that allow people to drag note to tags. Then I would never have this problem! Typing the tags is so tedious.

While this suggestion has been noted in the past, currently it's not something that's planned, given that the combination of the aforementioned method of selecting multiple notes and applying tags and the autocomplete tags feature already exist.
