### ISSUE TITLE
Possible to export?

### ISSUE THREAD

**Issue by drbwrites** [standardnotes/forum#1426]
Just getting familiar with StandardNotes, but need the ability to export individual notes or a selection of individual notes. Is export of individual notes possible? Thank you.

**Comment by JaspalSuri** [comment]
Hi @drbwrites, while it isn't possible to select which notes can be exported, you can export a decrypted backup that will contain all of your notes as separate files via the **Account** menu. Uncompress/unzip the decrypted backup file that is generated, and then click on the **Notes** folder to access each text file that is created for each note that was stored in the app that you were using (be it mobile/desktop/web). 🙂

**Comment by BrunoBernardino** [comment]
Hi @drbwrites while not exactly what you asked for, with the solution I provided for the export of tags as folders in https://github.com/standardnotes/forum/issues/1294#issuecomment-1146603741 it should allow you to more easily pick a list of exported notes.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
