### ISSUE TITLE
[Help Wanted] Cloudlink backup fail

### ISSUE THREAD

**Issue by Pistoleer** [standardnotes/forum#1428]
**Describe the issue**
Up until July this year Cloudlink was performing backups to my Google account. I happened to look today and saw nothing since July 6. 

**To Reproduce**
I have triggered a new backup. I get this message: "A backup has been triggered for this provider. Please allow a couple minutes for your backup to be processed." Nothing appears in my backup folder.

I have installed the OneDrive extension and triggered a backup. Same message, nothing happens.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Browser: Safari
 - Version 15.0

**Additional context**
This seems to have been working, not stops. Reloading StandardNotes did not solve the problem, neither did the standard turn off, wait, reboot, restart etc.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
