### ISSUE TITLE
Can't turn off Spelling (underlined suggestions)

### ISSUE THREAD

**Issue by miltersen** [standardnotes/forum#143]
I can't seem to turn off the "red underlined spelling suggestions" in SN. There is no Spelling menu item under Menu - Edit. Assistance appreciated.

**Comment by mobitar** [comment]
Hoping to add this in soon. Right now it can't be disabled.

**Comment by miltersen** [comment]
8 more months of red underlines in my text since I wrote. I can't use SN as I would have liked to because of this problem. It's probably worse for those of us that write in two languages. Red lines everywhere. 

Here's to hoping :-) 
Cheers

**Comment by mobitar** [comment]
This option was added some time ago. You can disable spell check from the "Menu" option in the note editor: https://standardnotes.org/help/37/how-do-i-disable-spellcheck
