### ISSUE TITLE
Cannot Access of Modify the Backup Location

### ISSUE THREAD

**Issue by LalOpen** [standardnotes/forum#1432]
I cannot access or modify the backup location.
I use the 3.8.21 flatpak version of Standard Notes on Fedora 34.

1. I click on the 3 little bars at the top left of the windows.
2. Then I select _Backups_
3. It doesn't work with both Change or Open Backup location : nothing happens...

**Comment by haflaxa** [comment]
Hi @LalOpen!

I think it’s highly likely that the sandboxing permissions of your Flatpak version of Standard Notes aren’t properly configured to allow it access to the files in your home directory, thus limiting the _Backup_ functionality. Try the following:

0. Make sure you have closed any and all instances of Standard Notes running on your system.
1. Install [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)—a graphical utility to review and modify permissions of your Flatpak applications.
2. Launch Flatseal.
3. Locate Standard Notes in the “**Applications**” panel on the left-hand side of Flatseal’s window; click on it.
4. Confirm that Flatseal’s main panel is being populated by Standard Note’s information and its available/modifiable permissions.
5. Scroll down to the “**Filesystem**” subsection of Standard Notes’ available/modifiable permissions.
6. Locate the “**All user files**” permission; click on it to enable it.
7. Close Flatseal.
8. Launch Standard Notes.
9. Enjoy! You should now be able to “_Open Backups Location_” as well as “_Change Backups Location_” from your Flatpak version of Standard Notes.

I hope this helps!
