### ISSUE TITLE
Freeze Panes for Secure Spreadsheets

### ISSUE THREAD

**Issue by acharius-fox** [standardnotes/forum#1435]
Hi there, I'm trying to freeze the top row in Secure Spreadsheets so that the column names persist as I scroll. I've highlighted them, tried every option regarding freezing, to no avail. Is there a workaround to make them persist?

Using Standard Notes for Windows

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
