### ISSUE TITLE
Exporting decrypted notes

### ISSUE THREAD

**Issue by EricEWeir** [standardnotes/forum#1437]
New user. Already lost my password. I think I’ve done what the help pages suggest, though the instructions don’t fit with what I see in my installation.

I elected to export a decrypted copy of my notes and saved the file. To my naive user's eyes the file doesn’t look decrypted what I see is stuff like this:

> {
>   "version": "004",
>   "items": [
>     {
>       "uuid": "2e7a89d2-a766-4962-9c79-a7a827807232",
>       "content_type": "SN|UserPreferences",
>       "content": {
>         "references": [],
>         "appData": {
>           "org.standardnotes.sn": {
>             "client_updated_at": "Tue Oct 26 2021 09:36:11 GMT-0400 (EDT)"
>           }

I’m guessing this actually a decrypted file. I’m hoping that after I delete my account in preparation for starting over with a new account and password I will be able to import this file. And that when I do the notes will look how they looked when I entered them.

is that right?

**Comment by johnny243** [comment]
Hello @EricEWeir, thanks for posting your issue here!

You can tell if an export file is **decrypted** if, for example, the content (title and text) of a Note can be readable.

For reference, here's an **encrypted** note:

```json
{
      "uuid": "3100e263-91ab-40ca-a72f-a0c56e9ac2d0",
      "content_type": "Note",
      "items_key_id": "c4f7a641-be18-468e-88e4-ce03ac37ec0f",
      "enc_item_key": "004:1c3a8784478d47591a519300c3c986236a0fac425ef7f364:7MGmEScsZg9qxKjiKUVktFTP-UScNkn-_07X77pqdNnJIrsC0zxYBUa1dCuBxqrs2zqZRU_o5nnc4cXsoB_yGZeORPlqNm_4UbZ8YKpix58",
      "content": "004:3cdfe801dd99b8e9f578c89959f2a696331faee3effb9c03:jwSdDOP2nu54wP_D-JXT2Nyf854I9t_aPyar8o2MVJmZsYiX-VN6Wi6XHWIGmTdDYoXmnkl2c660mtDMVnE6-u9d1WQvt69fOsRZth_S57Xcj5twMA-IvFcuSejCqXs7gPTiiGBuCMIza7jRTtZTnurD8BomMOgsfMcsUwtPy6VSmqC74OIwfbUy1KZLbi1wo_tqEU5BL0aGO8kBfArMPodxJ2mAjfvvRUnm3uGj_A",
      "created_at": "2021-11-02T01:05:12.868Z",
      "updated_at": "2021-11-03T08:32:12.997Z"
},
```

Let me know if you have any other questions!

**Comment by EricEWeir** [comment]
Thanks, Johnny. I’m taking it that the file I exported was decrypted. My only remaining question is whether, when imported, I will get what I expect—an uncluttered  view of my notes. 

Of course, I can find out by going ahead and importing the file. I’m wondering if I should wait to delete my current account and start over until the release of the updated app, which I understand is coming soon.

I’m guessing updating to the new app will be relatively straight forward, so I think I’ll go ahead and start over with the current version of the app.

**Comment by johnny243** [comment]
> My only remaining question is whether, when imported, I will get what I expect—an uncluttered view of my notes.

Correct. If you want, you can import your backup to a new session of the Web app (in another browser, for example).

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
