### ISSUE TITLE
Waiting for Keys

### ISSUE THREAD

**Issue by EricEWeir** [standardnotes/forum#1439]
I have just deleted my original account and established a new one. Before deleting the old account I deleted two notes that I had, not knowing what I was doing at the time, archived but could not, or did not see how to, unarchive.

Now, with my new account established, I have two notes identified by "waiting for keys." I don't know what "waiting for keys" means. I have tried signing out and signing back in my account on all devices. I don't see any way to change the status of these notes. I cannot even select them.

Help appreciated.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
