### ISSUE TITLE
Passcode field inactive on fullscreen startup (Mac)

### ISSUE THREAD

**Issue by samdevine** [standardnotes/forum#144]
When opening the Mac app in fullscreen (High Sierra) with a passcode lock, I have to manually select the text input field before I can type my passcode. To clarify: the field appears active (cursor is blinking) but typing produces the error sound. Need to manually click to activate field. Issue does not appear in non-fullscreen startup.

**Comment by mobitar** [comment]
Got it thanks, will fix this for the next release.
