### ISSUE TITLE
Configuring the app 

### ISSUE THREAD

**Issue by EricEWeir** [standardnotes/forum#1440]
A couple of complaints:

In the mobile app (ios) on the settings page I am able to specify what to sort on, sort order, and whether to display note previews and dates. However it appears these configurations do not persist between session. Is that, as it seems to be, actually the case.

In the desktop app (macOS) it appears that none of those items can be configured across notes. Display of preview can be configured, but only note by note, not across notes. Again, is that actually the case?

**Comment by EricEWeir** [comment]
Apologies. Just noticed noticed the "options" button at the top of the note titles list in the desktop version. I've configured the display of notes. I'll be interested to see if the configuration persists across sessions.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
