### ISSUE TITLE
Please add: Change account email address OR add secundairy email address (preferably both)

### ISSUE THREAD

**Issue by r0-n** [standardnotes/forum#1442]
1)
Could it be made possible in the future to change the account email address.
(Or at least for the paid subscriptions)

2)
And is this currently possible to do it through support? (should the need arise).

3)
Maybe even better would be if a secondary email address could be added?

Thank you.

**Comment by moughxyz** [comment]
This is now possible with the 3.9 release via Preferences > Account > Change email.

**Comment by r0-n** [comment]
Thank you!
