### ISSUE TITLE
Note "waiting for key" cannot be deleted

### ISSUE THREAD

**Issue by yozamacs** [standardnotes/forum#1444]
**Describe the bug**
I recently reset my account from a backup because I didn't have the password. In that process, there was a note that didn't get into the backup and now it says "waiting for keys". I can't delete the note, every time I try to delete it, nothing happens. I don't have the old password, so the note can't be decrypted. Is there a way for me to get rid of this note? I've only tried deleting the note on my mac standard notes app.

**Comment by moughxyz** [comment]
You should be able to delete this note now in the 3.9 update by right clicking on it from the notes list. Let me know if that isn't the case.

**Comment by yozamacs** [comment]
that works, thanks!!
