### ISSUE TITLE
Moving theme picker to the "quick settings" menu is a UX regression.

### ISSUE THREAD

**Issue by voss** [standardnotes/forum#1446]
**Describe the bug**
A few days ago, picking a theme was a simple process involving one click on the colour dot, or the "No Distraction" icon, in the bottom right corner of the web app. Now the theme picker has been moved into the preferences menu, and enabling "No Distraction" or picking another theme, is now 3 clicks away.

Any chance of getting the coloured dots/icons from the previous method back? I don't think moving them from an actual quick way to change them, into something called "Quick settings", which requires more clicks and a higher cognitive load for the user, is an improvement.

**Comment by yoonbuck** [comment]
I love the new look but am also struggling with this change. I toggle "No Distraction" mode regularly and it's gone from one to three clicks. It's incredibly useful to have an easily accessible button to toggle this. (A keyboard shortcut for toggling no distractions would be super handy too!)

**Comment by gognavx** [comment]
This newly designed bar at the bottom really is a step back in terms of UX, even if it arguably looks better. It also takes up a lot of space just for two icons in the left corner. ActionBar and FileSafe are still and addiotional bar of their own (at least on the Windows Desktop client). It really seems like worthwile design goal to put everything into one bar at the bottom, including the old one-click style change options.

**Comment by moughxyz** [comment]
No distraction is on its way to becoming a native feature. I believe the design specifications have it living directly in the dock so it will be just 1 click. As for themes we can potentially make it 1 step less by not nesting themes in Quick Settings but listing them directly.

**Comment by voss** [comment]
> No distraction is on its way to becoming a native feature. I believe the design specifications have it living directly in the dock so it will be just 1 click. As for themes we can potentially make it 1 step less by not nesting themes in Quick Settings but listing them directly.

Making "No Distraction" a native feature living directly in the dock sounds amazing, and would definitely soothe the pain of the recent UX change (: 

Making a shorter path to changing themes would also be great.

**Comment by effieeee** [comment]
Theme picker now has it's own one-click menu :)
