### ISSUE TITLE
New Update sucks!

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1449]
- Why you forced unwanted Themes to us?
- Why you forced unwanted Editors to us?
- Why is switching between two Themes is now a such pain?
- Why we can't see information about installed extensions? URL? Author? etc.?
- Why the hell, can't we disable all this forced junk?
- Why you raised the price tag and still don't provide a working mobile app?
- Why is there still no way to setup a monospace font in the mobile apps? Seriously?!
- Why are ALL editors still such a buggy pain in the ass?

The last couple of year, all you provide are "under the hood optimisations" and not a single line of code in any editors to make them useable. Think about it..

**Comment by BrexitBollocks** [comment]
Really do have to agree with MMario here ... Now I am just an ordinary, non tech, bod on the street (but paying subscriber) ... happy user of Standard Notes last week, but you really have right buggered it up this week ... click on colored dot, change theme, brilliant ... now, go find it three clicks away buried deep, bloody awkward.
As the marks on my school reports always said .. Must Do Better !!

**Comment by moughxyz** [comment]
Sorry, do better on the communication here. Feel free to re-open with a more humane tone.
