### ISSUE TITLE
Weird list behavior in Advanced MD editor

### ISSUE THREAD

**Issue by samdevine** [standardnotes/forum#145]
This is a very specific behavior I've found in the Advanced MD editor. It occurs when using the "-" character to make an unordered list on the very next line after normal text. The "-" character will briefly be formatted as header text, and will revert to normal formatting as soon as you enter another character. This is consistent for each new item on the list. 

Does not occur when using the "*" to make lists or if you start a list after a header, or if you put an empty line in between the text and the list.

Thus I can reproduce the behavior with this:

List header
- item1
- [<< weird formatting]

but not this:

## List header
- item1
- item2

or this:

List header
[empty line]
- item1
- item 2

Consistent on both web client and Mac client.

**Comment by mobitar** [comment]
Yeah, it does display some weird behavior with lists for some reason. This editor is based directly on https://github.com/sparksuite/simplemde-markdown-editor, so the best hope for getting it resolved is posting there directly, as I won't be able to venture into that code any time soon.

**Comment by TheodoreChu** [comment]
I'm closing the issue as it seems to be resolved. Please comment if you have any more issues
