### ISSUE TITLE
Standard Notes locks up on Android when opening a note

### ISSUE THREAD

**Issue by Paul-5** [standardnotes/forum#1451]
**Describe the bug**
Standard Notes locks up on Android when opening a note. It opens smaller notes but not the larger ones (which are about 3 pages). These notes were developed using the Plus Editor and have not been viewed on this device as yet, so they will be rendering as HTML markup.

**To Reproduce**
Click on a note to open it. Android will become unresponsive. Eventually it will tell you has hung and give you options to close the app, wait, report a fault.

**Expected behavior**
The note should open

**Smartphone (please complete the following information):**
Samsung Galaxy SM-G960F
Android 10, kernel version 4.9.118-222556815

**Comment by Paul-5** [comment]
I have noticed that the notes that don't open contain embedded images. I suspect the extra markup is killing the Android app.

**Comment by DrownedStarfish** [comment]
Lately, when I try to open SN on my phone, it often seems to open for an instant, then closes itself.  Sometimes, even in the middle of writing it becomes completely unresponsive.  I have only noticed this in a big note, and it happens even in the default editor ('no' editor)

Please tell me if this will only happen on very large notes.  I can divide up my notes differently.

Thanks.
DS

**Comment by atmoio** [comment]
Embedded images as in raw base64? If so I would definitely remove that as these can tend to balloon in size. I think both your theories regarding note size are correct; I would try breaking the notes apart and see if that helps.

**Comment by DrownedStarfish** [comment]
**"Embedded images as in raw base64?"**
Mine are pure text.

**"I would try breaking the notes apart and see if that helps."**
OK; I'll try that.

Thanks.
