### ISSUE TITLE
Search should find content within a note

### ISSUE THREAD

**Issue by Paul-5** [standardnotes/forum#1452]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes

**Is your feature request related to a problem? Please describe.**
Yes. I need to find information in a note... this is the whole purpose of creating notes. :-)

**Describe the solution you'd like**
If I enter a search term into the Search field it should find and take me to the search term in the note, at the moment it just finds a set of notes containing the term and I then spend 10 minutes finding what I'm looking for.

**Describe alternatives you've considered**
I could copy each note's contents to another application so I can conduct a search.
I could use a different notes application entirely.

**Comment by moughxyz** [comment]
This is available in the desktop app (press enter after typing in your query), but not presently web.

**Comment by scottbourne** [comment]
The highlighting of note content while searching does not seem consistent for me on the desktop (3.9.4).  Sometimes it highlights and sometimes it does not.

**Comment by moughxyz** [comment]
Yup confirmed issue here: https://github.com/standardnotes/desktop/issues/790

**Comment by scottbourne** [comment]
Thanks @moughxyz I'll follow over there!

**Comment by Paul-5** [comment]
I also just manually upgraded to 3.9.4... no highlighting occurs in the desktop app.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
