### ISSUE TITLE
https://dashboard.standardnotes.com does not exist for accessing your account

### ISSUE THREAD

**Issue by Paul-5** [standardnotes/forum#1453]
**Describe the bug**
The URL https://dashboard.standardnotes.com does not exist for accessing your account.

**To Reproduce**
Go to https://dashboard.standardnotes.com

**Expected behavior**
It should work.

**Comment by twoquestions** [comment]
This is happening for me as well.  I'm beginning to think my payments were lost with the new plan migration or something.

**Comment by moughxyz** [comment]
The dashboard has been replaced. To manage your account now, sign into your account on app.standardnotes.com (or the desktop app), Preferences > Account > Manage subscription.

**Comment by jeifour** [comment]
After clicking on Manage subscription, I'm always getting this message. I can click on the back button and it will show the correct validity date, but yeah, seems like it's a bit broken.

![スクリーンショット 2021-11-16 20 48 30](https://user-images.githubusercontent.com/3247063/142055314-dfd90cfc-8107-4e5f-8abd-af56392c2058.png)

Also [in the blog post](https://blog.standardnotes.com/29709/an-update-on-early-pricing-and-roadmap) this was mentioned:

> If you are an existing subscriber, whether monthly, yearly, or 5-yearly, you automatically get the highest Pro Plan, with no price increase! You're locked into the price you signed up with, and your plan will continue to renew at that price indefinitely until you cancel. _You can also extend your plan today with another X years at current pricing._

There doesn't seem to be a way to extend my plan anywhere. I just have a button for cancelling.

**Comment by moughxyz** [comment]
The blog post was a retroactive posting of our email from November 3. These options are no longer available.

**Comment by Paul-5** [comment]
I manually updated to 3.9.4 and can now see those menu items. All good thank you.
