### ISSUE TITLE
[Help Wanted] delete all notes with a particular tag

### ISSUE THREAD

**Issue by scottbourne** [standardnotes/forum#1455]
**Describe the issue**
I want to delete all notes with a particular tag.  I have 283 Notes with a specific tag.  I want to delete all of those Notes at once, not have to go through the delete process 283 times.

**To Reproduce**
N/A - no error - looking for info on existing functionality

**Expected behavior**
Some way to select all those Notes for deletion

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.0.4
 - Browser Chromium based (Vivaldi, Brave)
 - Version SN: 3.9.3

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: 15.1
 - Browser safari
 - Version

**Additional context**
N/A

**Comment by moughxyz** [comment]
You can use multiple selection for this. Select the first note, then scroll to the last note, and shift + click the last note. Then right click, move to trash (or hold down option key to display Delete immediately option).

**Comment by scottbourne** [comment]
Perfect!  I guess I should have thought of that - appreciate the help!
