### ISSUE TITLE
listed header image

### ISSUE THREAD

**Issue by ohdisyus** [standardnotes/forum#1458]
I'm guessing this is a simple fix ... but what would the custom CSS be to suppress the header image on my listed blog? I'd rather not have an image, or the default block with a letter in it. Many thanks.

**Comment by jeifour** [comment]
The simplest way to disable the box being shown would be to create a note with this content and publish it to your blog.

```
---
metatype: css
---

.header-image-container {
  display: none;
}
```

**Comment by ohdisyus** [comment]
Perfect. Just what I was looking for.
