### ISSUE TITLE
add: attach files un-encrypted  + folder structure in android app (and issues web version standard notes).

### ISSUE THREAD

**Issue by r0-n** [standardnotes/forum#1461]
1)
Currently it is required to have attachments also encrypted and until it's possible the only way to insert images is to embed them by url. Is it possible to give the user the option to choose if the user wants to attach un-encrypted content? The user would be warned first. This at least gives the option to attach files. Currently there is filesafe, but inserting through the image icon above in the toolbar seems to go much quicker (but only works for url's).
Also I can't seem to embed images from filesafe once they have been correctly uploaded to dropbox or google drive through filesafe, Or was this never not possible?). I click the image icon above and paste the [filesafe: ....] -url.

2)
Will the folder structure be also implemented in the android app and if so, Is there any estimation when it will be implemented?

3)
Also some issues regarding the web-version (I do not know if I am the only one or if others have the same issue(s)).
Using the browser on a smartphone (firefox / chrome) doesn't work very well. The application seems autodefault to the mobile version of the site which makes scrolling from the leftside (tags) to the rightside (note content) almost impossible. Once on the left or rightside you can not drag, the page seems to be stuck at that place. Switching to dynamic isn't possible because when you tap the settings icon (the one with the sliders) the content of the "themes" menu expands out of view. (can't select "dynamic" because of the scrolling issue).
Also placing a url-shortcut on the homescreen of the smartphone launches the website mobile version but without the upper menu  visible, so you can't select "desktop site". And even if you could the mobile versions of firefox and chrome do not remember the "desktop site", they always launch the mobile site.

Thank you.

**Comment by myreli** [comment]
1. While attaching unencrypted content isn't possible, with the new [native files](https://standardnotes.com/blog/introducing-encrypted-file-storage-with-automated-backups) and the new [super editor](https://standardnotes.com/blog/introducing-super-notes-moments-and-offline-file-access) this workflow is now possible. You can embed images and have them displayed inline while automatically encrypted and stored. 
2. The [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) now guarantees that all platforms share the same features. 
3. Also through the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) the web is now responsive, so it should display all of the app's features regardless of the screen size. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
