### ISSUE TITLE
[Help Wanted] Cannot find Batch Manager Extension

### ISSUE THREAD

**Issue by scottbourne** [standardnotes/forum#1462]
**Describe the issue**
Cannot find Batch Manager extension any more

**To Reproduce**
Not on Extension list

**Expected behavior**
To see Batch Manager extension on the list

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: 20.0.4
 - Browser N/A
 - Version 3.9.4

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by amund-ersland** [comment]
Any progress on this ?  I cannot find the batch extension in neither the web version (firefox) nor the linux version (ubuntu).

**Comment by stefan-yas** [comment]
All Batch Manager features have been implemented natively. You should be able to do all stuff batch-manager by selecting your notes by holding CTRL/Command or Shift on your keyboard and then right-clicking on the selected notes. Select your action in the context menu which appears after right-clicking.

![image](https://user-images.githubusercontent.com/52251483/162687140-97ac0aab-e367-4ca3-9dcd-d625527dc09b.png)

**Comment by amund-ersland** [comment]
I see, I attempted to do this, select a couple of notes and right click, then, when I put the cursor into the action menu, all notes apart from one gets unselected, and I can thus only do the desired action on one of them.

**Comment by amund-ersland** [comment]
ah, I figured it out, you need to select them by right clicking, not left clicking, or at least the final item you want to chose.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
