### ISSUE TITLE
Listed.to is down

### ISSUE THREAD

**Issue by jeifour** [standardnotes/forum#1463]
**Describe the bug**
Listed.to is down. Since at least 2 hours.

**To Reproduce**
1. Try to open listed.to or any listed.to blog like https://blog.standardnotes.com/

**Expected behavior**
It should work.

**Additional context**
Is there any status page? For a down-time this long it also wouldn't hurt to send out a tweet or something.

**Comment by jeifour** [comment]
Went up again now.

**Comment by salixh5** [comment]
Well, today again completely down apparently. Cannot load my own blog, cannot load the main page.

A status page would be nice :)

<img width="417" alt="スクリーンショット 2022-02-03 16 21 05" src="https://user-images.githubusercontent.com/3247063/152372058-5b2496b6-3432-4b20-b1d6-4e5e69d338fb.png">

**Comment by salixh5** [comment]
Went up again.

**Comment by atmoio** [comment]
Sorry about that. We've made some infra improvements today and hope to allocate some resources to put some redundancy measures in place in the near future.
