### ISSUE TITLE
Deleted notes visible shortly on app open

### ISSUE THREAD

**Issue by pilsnerbeer** [standardnotes/forum#1465]
**Describe the bug**
.deleted notes can be seen for a short while when opening app. Most likely residues from memory (?) 
**To Reproduce**
1. save note XYZ on android app, then close it
2. delete note from desktop
3. open android app. you will notice the XYZ note is visible in full before the list updates

**Expected behavior**
a deleted note should never appear again. replace local-memory placeholder with loading animation?

**Smartphone (please complete the following information):**
 - Device: oP5T
 - OS: 10
 - Version 3-9-3

**Comment by moughxyz** [comment]
The note is visible because it hasn't yet received communication from the server that it is deleted. Once all decryption completes and the first sync completes, it will then get the message from the server that a particular note should be deleted. That's why you temporarily see it.
