### ISSUE TITLE
[Linux] Getting "Unable to write to local database" error and have to re-login every time I open the app

### ISSUE THREAD

**Issue by BBlackwo** [standardnotes/forum#1466]
**Describe the bug**
Every time I open the app I get an error: `Unable to write to local database. Please restart the app and try again.`. Then I am prompted to re-login. Once I log in, it works fine. But next time I open the app I get the same error.

**To Reproduce**
1. Open Standard Notes on Linux
2. Close `Unable to write to local database` error message **twice**
3. Re-login
4. Close `Your credentials have successfully been updated.` message **twice**
5. Close `Unable to write to local database. Please restart the app and try again.` message **again**

**Expected behavior**
I would expect it to not have to re-login every time and just work without error mesages

**Screenshots**
Error when opening:
![Error 1](https://user-images.githubusercontent.com/7598058/142943909-f751a6c2-860e-4138-a026-7694f36775c1.png)

Console message after re-logging in:
![Error 2](https://user-images.githubusercontent.com/7598058/142943258-655294ce-413b-44e3-8097-d76aaef0fbc7.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.04
 - Browser: N/A
 - Version: 3.9.4

**Additional context**
This has been happening consistently for several months.

I tried (1) signing out and clearing local data and (2) uninstalling and re-installing the app, but both didn't fix it

**Comment by moughxyz** [comment]
Can you go to the top level Help menu, then Open Data Directory. Delete everything there, and restart the app. Does that help?

**Comment by BBlackwo** [comment]
That worked @moughxyz! Thanks! :slightly_smiling_face:

**Comment by BBlackwo** [comment]
Will re-open the issue if it starts happening again.
