### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by religionofpeas** [standardnotes/forum#147]
Hi, I am a touch confused by the folders extension. Creating a folder is straightforward. I assumed that the + symbol beside the newly created folder would create an embedded folder, but it doesn't seem to be the case. Is it a tag that it creates?

**Comment by religionofpeas** [comment]
Hi Mo,

 It is behaving the way it should. It just isn’t immediately obvious how it all works. There isn’t a tree structure that can be opened and closed which is what I am used to.

**Comment by gloomy-ghost** [comment]
A tree structure would be much better to use, as it allows not only being able to collapse/expand folders for the sake of tidiness, but also viewing all contents in a category of sub-folders at once.

**Comment by mobitar** [comment]
How would a tree structure act compared to the current way it functions?

**Comment by gloomy-ghost** [comment]
Selecting a parent folder would show all notes in its children folders, so that a dummy folder could be used for the sole purpose of classification. Also the UI/UX could allow collapse/expand folders in case of too many sub-folders in a category.

**Comment by M-Pixel** [comment]
@gloomy-ghost nested folders are already indented.

To be clear, are you talking about adding the ability to expand/collapse folders? That's certainly a feature that I would like, too!

Or are you talking about entering/exiting folders, changing which one is "current", or top-level?

**Comment by dustinsterk** [comment]
Has anyone else been able to delete a folder?  When I try to drag a folder to the trash, the entire window moves.

**Comment by religionofpeas** [comment]
From memory the delete option is either directly below the list of folders in the folders column, or it is in the action list.

**Comment by M-Pixel** [comment]
I think you have to remove the folder's tag from all notes, then restart Standard Notes to force it to re-render to folder list.

**Comment by mobitar** [comment]
You should be able to delete a folder by dragging it to the Trash below. Need to figure out a better UX for this.

**Comment by dustinsterk** [comment]
Thanks all, when I try to drag it to the trash, the entire window moves.  I am using the OSX desktop client.  I will try the web client as well.

**Comment by mobitar** [comment]
Hmm..in that case, until I can investigate this, please disable the Folders extension, delete the tag that way, then re-enable.

**Comment by dustinsterk** [comment]
Will do, thank you!
