### ISSUE TITLE
[Help Wanted] Last two updates overwrite previous app OSX, all of my notes from the last 2 years are gone.

### ISSUE THREAD

**Issue by spiritewolf** [standardnotes/forum#1472]
**Describe the issue**
The last two updates have been extremely funky on OSX, either it updates automatically or I'm not sure what. But the app will start crashing (this time, I was simply left with a question mark in my dock where my app previously was) and to actually get the new update I have to go into the updater folder and click on the new zip thus overwriting my previous app. Last time, it still had all of my previous notes. This time my notes aren't there. The backup appears to still be there but I can't figure out how to get the notes to show up

**To Reproduce**
Honestly have no idea how you can reproduce this if its not already an issue you're facing.

**Expected behavior**
I expect for updates to install automatically, I suppose. 

**Screenshots**
The previous app is the ? mark, the one after going into the update folder and opening the zip file is next to it
![Screen Shot 2021-11-27 at 10 25 09 AM](https://user-images.githubusercontent.com/67026947/143689150-3c39ec6b-c4f7-4c3e-abb9-2036e751825b.png)
Updates folder, pending updates
![Screen Shot 2021-11-27 at 10 25 34 AM](https://user-images.githubusercontent.com/67026947/143689151-11350c41-a186-4aad-abc7-2b71fc597a5d.png)
My backups
![Screen Shot 2021-11-27 at 10 25 50 AM](https://user-images.githubusercontent.com/67026947/143689152-5b6ab142-7fb5-4eb8-8934-6bdf2193a4ec.png)

**Desktop (please complete the following information):**
 - OSX Catalina 10.15.6

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by moughxyz** [comment]
Seems to be an isolated issue as we haven't received any other reports about this. You'd want to import the backup file into your account to get them to show up in the app.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
