### ISSUE TITLE
[help wanted] Only blank (white) screen on macOS desktop - nothing else

### ISSUE THREAD

**Issue by Wlhale** [standardnotes/forum#1473]
**Describe the bug**
I want to use the desktop app on my MacBook. When I open it, all I get is a white screen inside the app window. I can not even drag around the app window or use any menu functions (like toggling Developer Tools) - I can click on it in the menu or use the keyboard shortcuts, but nothing ever happens.

**To Reproduce**
1. Open Standard Notes App.
2. See the white app window.

**Expected behavior**
I expect Standard Notes to open normally and being able to use.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/95140982/143690039-8d2aaf13-beac-4138-bb71-8e23b0f46204.png)

**Desktop (please complete the following information):**
 - OS: MacBook Pro Mid 2009
 - Browser: Firefox
 - Version: 94.0.1

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - OS: Emui 10.0.0
 - Browser: Firefox Mobile
 - Version: 81.1.1 beta

**Additional context**
Standard Notes works both on my Android phone as well as a web app on the same MacBook Pro. Only thing that does not work is the macOS desktop app. It is updated to the latest version.

**Comment by jbeldia** [comment]
Hi @Wlhale , I'm sorry to hear about the issue you've encountered. May I know if you've tried doing a clean reinstall of the app by following our [uninstallation instructions](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes) on our website, then downloading and installing a fresh copy of the desktop app for Mac?

**Comment by myreli** [comment]
This issue was closed because it has been inactive, and we haven't had similar reports in recent versions.
