### ISSUE TITLE
Some Extended extensions are not available for install in the preferences UI

### ISSUE THREAD

**Issue by StuartMorrisAU** [standardnotes/forum#1476]
Hi there,

It was possible to install the following extensions as part of the Extended/Repo UI, but it doesn't appear they've been carried forward into the new preferences UI. Is there any way to install them? Or are the first two no longer supported?

- [Action Bar](https://github.com/standardnotes/action-bar)
- [GitHub Push](https://github.com/standardnotes/github-push)
- [Listed](https://github.com/standardnotes/listed)

For Listed, while it does appear by default, there's no way to reinstall it once uninstalled. Comparatively, other extensions available within my subscription automatically reinstall if I uninstall them and then refresh the app/browser.

Thanks.

**Comment by moughxyz** [comment]
You can install Listed via Preferences > General > Advanced. We have plans for a dedicated install option in the Listed preferences pane.

Action Bar and GitHub Push have been deprecated. They are only available to people who previously had them. The functions of Action Bar are mostly now available in the note context menu.

**Comment by StuartMorrisAU** [comment]
> You can install Listed via Preferences > General > Advanced

@moughxyz, the option is not there. Is there a way to install via custom URL?

> Action Bar and GitHub Push have been deprecated

OK, I figured this was the case but wanted to double-check.

**Comment by moughxyz** [comment]
It's there (v3.9.5). General > Advanced Settings > Scroll to bottom:

<img width="505" alt="Screen Shot 2021-12-01 at 7 55 48 AM" src="https://user-images.githubusercontent.com/3277844/144247021-d71b2e6c-00d1-4dd4-b257-da2cb7065d0e.png">

**Comment by BonPacific** [comment]
"https://github.com/standardnotes/listed" does not work when put in that field. What URL are we supposed to use to install Listed?

**Comment by stefan-yas** [comment]
Hey @BonPacific, you can visit [listed.to](https://listed.to/) and click on the "Start Writing" button in the top right corner, which will provide some simple instructions and generate an author code for you. This is the code you'd put in the Install Custom Extension input field in the Standard Notes app, without needing to install anything additionally. Let me know if you have any other questions!

**Comment by Teofilios** [comment]
If I want to install Plus Editor, how do I install it. In Preferences > General > Advanced, I do not see that various editors or extensions are available for installation. There is only the option to install Custom Extension, but you need extension URL. Is Plus Editor a Custom extension? What is the url for Plus Editor?

SOme years ago, it was much simpler to install extension. You got a list of extensions, and you just choose the one you want to install.

Aleksandar

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
