### ISSUE TITLE
I'm not able to sync all my notes on new devices 

### ISSUE THREAD

**Issue by Itarey** [standardnotes/forum#1482]
**Not able to sync all my notes on new devices **

1. Go to 'web version of standard notes'
2. Click on 'Sign In'
3. See error of "Unable to Sync"

**Expected behavior**
All notes should sync within few seconds.

**Comment by itinfosec** [comment]
I think the server is currently down or under maintenance since myself and some other people are having the same issue. Hopefully it'll be resolved soon 👍

**Comment by moughxyz** [comment]
Should be back up now.
