### ISSUE TITLE
[Feature Request] Allow locking Standard Notes with "Touch ID"/ fingerprint scanner on MacOS app

### ISSUE THREAD

**Issue by Winterludes** [standardnotes/forum#1485]
Recent M1 Mackbooks and M1 Macs have fingerprint scanners in the keyboard.  Can you please let your desktop app be locked with the fingerprint ID to open it, the same way you allow the iOS app to be locked with faceID?  

I feel like my Standard Notes desktop app is not secure without this.  And I can't enter a password every time I open the app, it would have to be too simple a password in order to remember it.  

Touch ID/fingerprint scanner is available now, why not take advantage of it and make the MacOS Standard Notes app more secure with it?

**Comment by myreli** [comment]
I will close this in favour of https://github.com/standardnotes/forum/discussions/2524 so we can track it in a single issue. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
