### ISSUE TITLE
Grey screen after loading notes

### ISSUE THREAD

**Issue by cezarnik** [standardnotes/forum#1486]
**Describe the bug**
After loading the notes, screen becomes grey, and the navigation in the app is impossible. While loading/syncing the notes, however, I can see them.

**To Reproduce**
1. Just open the app

**Expected behavior**
After loading the notes, navigation should remain possible.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Huawei P30 lite
 - OS: Android 10.0.0
 - App version: 3.9.3

**Additional context**
Reinstalling the app and deleting all the data/cache didn't help

**Comment by cezarnik** [comment]
If i disable the connection to internet and the notes are not fully synced, the notes are remained shown. Looks like there is some problem after syncing.

**Comment by moughxyz** [comment]
Can you DM me your account email?

**Comment by moughxyz** [comment]
This issue should now be fixed in 3.9.4.

**Comment by cezarnik** [comment]
The issue seems to be fixed, thanks a lot!
