### ISSUE TITLE
Filtering with labels no longer works

### ISSUE THREAD

**Issue by yozamacs** [standardnotes/forum#1487]
**Describe the bug**
I updated my mac standard notes app and now the filtering by labels no longer works! Is it possible to downgrade a version until this is fixed?

**To Reproduce**
Click on label to filter notes for that particular label....and nothing happens

**Expected behavior**
Only notes with that particular label should be visible

**Desktop (please complete the following information):**
 - OS: big sur
 - standalone app (not browser)
 - Version 3.9.6

**Comment by moughxyz** [comment]
Hmm, seems to happen with the Folders extension. Please disable Folders via Quick Settings and we'll get a fix out for this asap.

**Comment by yozamacs** [comment]
ah right you are correct....works fine without folders
