### ISSUE TITLE
Extension for pen input/drawing

### ISSUE THREAD

**Issue by hand-made** [standardnotes/forum#1488]
I know that it looks like for now it is a text-oriented app which for me has been working really good, but since I use standard notes a lot on my iPad, It would be just incredible to have the ability to sketch/draw directly on the note.

**Comment by Saldef** [comment]
Finally, There is. Check out this new [Draw Extension](https://github.com/antonheitz/sn-tldraw-editor) editor based on the TLDraw React Package. I have tried it on a Linux machine and on Android, and it works pretty well. Hope it satisfies your needs.

**Comment by effieeee** [comment]
@Saldef This is so awesome, thank you for sharing!! ❤️
