### ISSUE TITLE
Can’t edit cells on secure spreadsheets on mobile

### ISSUE THREAD

**Issue by hand-made** [standardnotes/forum#1489]
**Describe the bug**
When I enter the secure spreadsheets edite on an existing spreadsheet and try to edit the cells, I am not able to change the selected cell by clicking other cell on the screen.

The only way to change the selected row is clicking enter on the keyboard.

**To Reproduce**
1. Go to an existing secure spreadsheet note on mobile 
2. Click on any other cell different than the selected one
3. The app should select the cell that you tapped but instead it remains the same selected

**Expected behavior**
The app should be allow the user to select another cell by taping on their different than the selected one 

**Desktop (please complete the following information):**
 - OS: iOS 15.1

**Smartphone (please complete the following information):**
 - Device: iPad mini 6
 - OS: 15.1

**Additional context**
Note: this has happened randomly to me. Sometimes it works, sometimes not.

**Comment by stefan-yas** [comment]
Hey @alejandrogutierrez12, I tried to reproduce this issue but had no success. Any chance you could show this off in a screen recording? Be sure to disable multitasking/screenshot privacy in Settings before recording anything as it will just be a blank recording that way.

**Comment by alejandrogutierrez12** [comment]
Sure, I'll record next time I face it. Thanks

**Comment by myreli** [comment]
I'm triaging older issues and I'll close this issue as it seems we don't have any recent reports. Thanks!
