### ISSUE TITLE
Importing from Notes within Outlook or Contacts

### ISSUE THREAD

**Issue by MNTom** [standardnotes/forum#149]
Hi can you do a direct import from Microsoft Contacts? Or take the output form MS Outlook if the Notes column is exported? Thanks -

**Comment by mobitar** [comment]
I'm not too familiar with that format, but we only have support for Evernote and plain text importing currently. If you can convert your data into plain text files, you can use the tools here: https://dashboard.standardnotes.org/tools

**Comment by MNTom** [comment]
Thanks for the reply, I was hoping for a cleaner method to bring my existing notes into this tool.  I currently have over 1000 notes attached to various contacts.  The method you are suggesting will require me to create 1000 individual text documents.  It would be nice if your users had a method to import multiple notes from a single CSV file for example.  I can easily create a single CSV with 1000 notes in it, i.e. one per line.  Separate Note Title from Note Content using a delimiter such as a semicolon. Let me know if this is possible, Thank you.

**Comment by mobitar** [comment]
In that case, you might be able to convert your CSV file into a JSON file. I'm sure there's an online tool for this. Then what you can do is download a sample of SN's JSON format by clicking Account -> Download Data Archive, and seeing how you could fit one into the other, perhaps with a find-and-replace type scheme.

**Comment by morvenwestfield** [comment]
I have a similar problem: My notes, exported from another note-taking app, can only be exported in one CSV file.

You mentioned an online tool for converting CSV to JSON. Where can I find that?

Or, alternatively, do you know of a tool that would convert out each row of my CSV file into separate files that I could then import using your plain text import tool?

**Comment by mobitar** [comment]
I haven't encountered any such tool personally, you'd have to search around for one. If you do find one please post it here.

**Comment by Sebasaddam** [comment]
Export VCF Import VCF for Outlook this software is capable Importing from Notes within Outlook or Contacts . 
More Info :- http://www.osttopstapp.com/vcard-export-import.html
