### ISSUE TITLE
Duplicate Menu Entries

### ISSUE THREAD

**Issue by bytzqtvmbx** [standardnotes/forum#1492]
### Description of Bug
I have just created a brand new (paid) account and am getting a bunch of duplicated drop-down menu items and settings menu items. Prime example being when selecting an editor it shows most of the entries twice. I also see the **Cloud Link** menu twice in Preferences.

### To Reproduce
All I have done is create a new account, update to Pro and then login.

### Expected Behavior
Duplicate items should not be showing.

### Impacted Device Information
M1 MacBook Air - iOS 12.0.1
Iphone 12 Pro Max - iOS 15.1.1

### Attempted Fixes
* Check the internet to see if anyone else has had the issue
* Reboot devices
* Sign out and clear cache
* Completely uninstall the app and start again.

### Screenshots
<details>
<summary>Click to show screenshots</summary>

![image](https://user-images.githubusercontent.com/84760416/145944867-7ae9ae5e-bdc8-4325-abdc-f444d64fd4b6.png)
![image](https://user-images.githubusercontent.com/84760416/145944943-1df6743b-ac34-4dfb-bc46-c999c94edeee.png)
![image](https://user-images.githubusercontent.com/84760416/145945806-8ce58f66-6cd6-4c44-8351-a2ca1001ca13.png)
![image](https://user-images.githubusercontent.com/84760416/145945909-97c667ca-7186-4250-bc0c-828bf31019a4.png)
</details>

**Comment by jbeldia** [comment]
Hi @bytzqtvmbx , I've responded to your email as well, please do take a look when you have the time!

**Comment by bytzqtvmbx** [comment]
Thanks for your response @jbeldia, I have got the problem sorted now.

In case anyone stumbles upon this issue in the future, I did the following to fix the issue **on the desktop/web app**:

Quick Settings (bottom left) -> Open Preferences -> General -> Advanced Settings.

Then I actually uninstalled **all** the plugins. Just uninstalling the duplicates didn't work and left things broken so I uninstalled everything and let the app re-install the pro plugins again.

You can also uninstall the duplicate CloudLink entries too by clicking on CloudLink -> Uninstall

Thanks again for your support, it is appreciated.
