### ISSUE TITLE
Quick Tags not working as before

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/forum#1494]
From version 3.9.9 of the desktop app (on Windows and Linux), the Quick Tags extension has changed behavior. Before, if you added a sub tag, you also added the main tag automatically. This is no longer the case, so Quick Tags isn't so quick anymore. If it's a bug, please fix it. If it's a feature, add the old behavior back, at least as an option in settings.

Also, if it's indeed a feature, be careful about changing things just like that. Adding functions is fine. Removing them ... not so much. What's good about Standard Notes is it's dependability - that things don't change abritrarily (as opposed to practically every other piece of software out there). To paraphrase [a great sage](https://www.youtube.com/watch?v=uIfKsuAGzi4): "No one in this digital world can you trust. Not OneNote, not Google Keep, not Everote. But Standard Notes, you can trust!"

**Comment by moughxyz** [comment]
Hmm seems like a regression. cc @laurentsenta

**Comment by onlinemumie** [comment]
It's seems to be fixed in version 3.10.0, so I will close this.
