### ISSUE TITLE
[Bounty] Humble Markdown Math

### ISSUE THREAD

**Issue by kobigurk** [standardnotes/forum#1495]
I'd be happy to see an overhaul, or a rewrite-from-scratch, of a Markdown Math editor.

My dream editor would be:

* Interface similar to the simple Markdown tabbed choice of edit, split, preview
* Desktop and mobile compatible
* Single dollar for inline math, double dollar for display math 
* Local rendering (perhaps using Katex)
* PDF export

I believe that with this feature-set I'll be able to move a lot of my math notes to standard notes. Feedback and suggestions are welcome!

To start this off, I'm happy to put 0.1 ETH as a bounty to get this done.

**Comment by chaserene** [comment]
great initiative, and I especially appreciate that the bounty is priced in crypto :)

I'm interested in seeing this too, so I'm adding 0.05 ETH to the bounty (raising the total bounty to 0.15 ETH, which is ~$600 at current prices).
