### ISSUE TITLE
iOS App: Why the app is connecting to google domains?

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1496]
Why does the Standard Notes iOS app connecting to the following google domains?
- clients3.google.com
- ocsp.pki.goog

There is no 3rd party editor/theme or any other extra installed.
Only plaintext "editor" is used, so there is absolute no reason to
connect to the above domains.

**Comment by moughxyz** [comment]
https://www.reddit.com/r/StandardNotes/comments/rm9dvt/comment/hpkygw5/?utm_source=share&utm_medium=web2x&context=3
