### ISSUE TITLE
Passcode keyboard pop-up on android not consistent 

### ISSUE THREAD

**Issue by leto78** [standardnotes/forum#1497]
When I open the app on android, most of the times the keyboard does not pop up automatically. 

1. Close the app using the overview/recents view (3rd button on android) 
2. Open the app 
3. The passcode pop up keyboard does not show

**Expected behavior**
The focus should be on the application passcode, which would make the keyboard pop up automatically. 

**Smartphone:**
 - Device: Huawei Mate 10 Pro 
 - OS: Android 10.0
 - Standard Notes app version 3.9.7

**Additional context**
The passcode keyboard is able to pop up automatically when switching between apps using the recent/overview button. First open the app, then switch the focus to a different app and then switch the focus back to Standard Notes app. The keyboard will pop up automatically.

**Comment by myreli** [comment]
Since the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon), this seems to have been resolved. Feel free to re-open the issue.
