### ISSUE TITLE
Auto-update does not appear to be working

### ISSUE THREAD

**Issue by IceFire23** [standardnotes/forum#1498]
**Describe the bug**
I'm not sure exactly how long, but at least for months the auto-update feature has not been working for me. To perform updates, I've had to manually download the newest version of the app and install it. 

For example, right now if I click on the menu button, I see a tab that says "(1) Update Available". If I mouse over that, it opens a new menu that says the current version is 3.9.7 and the latest version is 3.9.10. When I click on "Check for updates", it says:
"A new update is available (version 3.9.10). You can wait for the app to update itself, or manually download and install this update."

I've tried leaving the app open for 15+ minutes, though, and it doesn't seem to have automatically updated and there's no indication it is in the process of updating.

**To Reproduce**
Not sure how to reproduce.

**Expected behavior**
I expect that the app would automatically update itself and give some indication it is in the process of doing so. If it's unable to do so, I was expecting some sort of error message or indication of why it couldn't do that.

**Screenshots**
![image](https://user-images.githubusercontent.com/35338/147706930-a48dfbc1-f82d-41ef-8c18-02c764d3a07a.png)

![image](https://user-images.githubusercontent.com/35338/147706895-92ca5e4b-e6bc-41d6-bea0-e0a111ea5238.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1 (OS Build 19043.1415)

**Comment by Regina3000** [comment]
I have this issue, as well, over several OS builds.

**Comment by moughxyz** [comment]
Autoupdate should be working now. A CDN-side issue was fixed for Windows and macOS late last week.

I also tested Linux AppImage arm64 autoupdate and it worked as-is with no fixes required.

**Comment by IceFire23** [comment]
Thanks! I can see it working now

**Comment by bmhj2** [comment]
Thank you - seems to be working for me as well.
