### ISSUE TITLE
How to embed images, videos or audio into published Listed blog posts?

### ISSUE THREAD

**Issue by rrrnn** [standardnotes/forum#1500]
New to all this so forgive me if this seems obvious. Do I need a paid subscription to directly embed? Can I use the plain editor or is there a specific one I'd need to use? Thank you in advance.

**Comment by moughxyz** [comment]
Right now there are two ways to embed files:

- Using the FileSafe bar on desktop and web. This allows you to attach files, but not directly embed them in the contents of a note. The files are however associated with the note.
- Using the Bold Editor. The Bold Editor integrates with FileSafe, so you can embed images directly in the editor. 

FileSafe uses your existing cloud provider for storage (Dropbox, Google Drive, OneDrive, and WebDAV).

We have plans for a native file solution that works out of the box, but we haven't commenced this project yet.

**Comment by rrrnn** [comment]
Thanks for your reply. I embedded the images into the note using FileSafe/bold editor and they show up fine in the editor but when I publish they appear on the blog post as the following lines of text rather than the images:

[FileSafe:0ca56810-a839-4012-a92b-2cecf78e264d:1.png]

[FileSafe:f25663aa-c2f0-497f-87fc-9ebe53aca441:2.png]

**Comment by moughxyz** [comment]
Correct these are encrypted file references and they are not understood by the outside world. Only the SN app knows how to translate FileSafe encrypted images into displayable images.

**Comment by rrrnn** [comment]
Can you advise on how to post visible images etc into blog posts? I noticed that on some of yours and other Listed blogs people have posted entries with photos and videos that I'm able to see. That's what I would like to do.

**Comment by moughxyz** [comment]
You'd just have to take your pick of any public image hosting solution, like Imgur.

**Comment by rrrnn** [comment]
Is there html involved that you can fill me in on? I uploaded the image to imgur and then entered the imgur embed code into the SN code editor but when I publish it's either blank or it displays a link that says "View post on imgur.com".

**Comment by moughxyz** [comment]
You need to get the direct .jpg link from Imgur. Their root url is just an Imgur web url I believe. They kind of make it difficult now to get the raw url.

Then you embed the image using the image option in bold editor. Or the respective HTML would be something like `<img src='https://imgur.com/...'></img>`.

**Comment by rrrnn** [comment]
Got it, thanks! In case anyone else comes across this experiencing similar difficulties, to get the raw image url I right-clicked on the uploaded image on Imgur and clicked "Inspect". Then I copied and pasted the highlighted code into the SN code editor (which read similar to what you described).

Thank you for your help.
