### ISSUE TITLE
[help wanted] scroll bars white regardless of theme

### ISSUE THREAD

**Issue by ohdisyus** [standardnotes/forum#1502]
The scroll bars for each panel are white now regardless of the theme I choose. This seems to be a new issue as of yesterday. I upgraded to the newest version (3.9.13), but that didn't help. I've also signed out of my SN account--still didn't help. Is this a known issue? BTW, I'm on a Macbook Pro (early 2015) running Monterey. Appreciate it!

**Comment by moughxyz** [comment]
It seems like if you have in your macOS System Preferences > General > "Show scroll bars" set to Always, we can't override the color of the track. It just doesn't seem to be possible.

If you set this to "Automatically..", you should get nicer scroll bars.

<img width="432" alt="Screen Shot 2022-01-06 at 12 06 24 PM" src="https://user-images.githubusercontent.com/3277844/148429768-7a5a41dd-4688-4035-88b7-26f508672d92.png">

**Comment by ohdisyus** [comment]
That did the trick! Thanks.
