### ISSUE TITLE
[Help Wanted] Question re FileSafe: file formats: visibility on web app & mobile: combining Bold Editor and others

### ISSUE THREAD

**Issue by umbellipher** [standardnotes/forum#1504]
I am a recent Plus Plan user, having moved from Joplin because of the encryption. FileSafe is great. But two related questions:

1. Which attachment formats (.jpg, .bmp, .pdf, etc) are visible, on desktop app and Android, once uploaded into a note via FileSafe? Is the number of formats likely to expand any time soon?

2. Combining editors in the same note: Having uploaded an attachment via Bold Editor so as to make it visible, how do I add text to the same note? By changing the editor to Note/Plain/Markdown, adding text, and then changing it back to Bold so that I can see the attachment again? Is there any other slicker way?

(Thanks! Great app!)

**Comment by stefan-yas** [comment]
Hey @umbellipher!

1. You can upload any file format you'd like via FileSafe as the files will be uploaded your cloud provider of choice, after being encrypted by FileSafe. Which attachments will be visible may depend on the Editor you're using - which file format are you aiming to embed into your note and which Editor is your go-to?
2. You don't have to switch Editors to attach text above or below your attachment. You could attach a file to a specific note while using the Bold Editor using FileSafe. Select the uploaded file and click on "Copy Insert Link". Copy paste the link into the note with Bold Editor active and, your attachment will be inserted into your note. You can freely add text above or below your attachment then.

Hope this helps!

**Comment by umbellipher** [comment]
@stefan-yas Thank you. So helpful.

1. Markdown Pro is my go-to Editor, though happy to use any Markdown flavor if that gives me more attachment visibility.  I was thinking visibility of: .pdf, .doc/x, .txt, .rtf, all the standard image formats (jpg,jpeg, tif, bmp...).
2. Thanks!

**Comment by stefan-yas** [comment]
Hm gotcha. I think your best solution would be to embed an image as a preview of your document, and then link that specific image to the link provided with FileSafe. There's no real elegant way of previewing .pdf or such in the Editors right now, so this could be a workaround that works for you.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
