### ISSUE TITLE
3.9.14 Issue - Unable to see login screen after updating

### ISSUE THREAD

**Issue by zzzpppzzz** [standardnotes/forum#1506]
Hello,

I updated through the app from 3.9.13>3.9.14 today and now I am unable to see the password login screen when Standard Notes is launched. It just displays a blank white screen with me unable to access anything, even menus. I've force quit and restarted the app and it does the same thing. I've also tried waiting for quite a while and nothing ever appears.

Windows 10
Occurred immediately after update from 3.9.13>3.9.14
No issues using latest iOS version

I'm going to try and downgrade to 3.9.13 for now as I assume that will fix the issue. 

EDIT: Confirmed downgrading to 3.9.13 fixed the issue

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
