### ISSUE TITLE
[Help Wanted] Cannot hide editor icon

### ISSUE THREAD

**Issue by hisel-sabermetrics** [standardnotes/forum#1507]
Hello, I cannot choose to hide the new editor icon. The path shown in the release notes is useless as the option menu is not there.

**To Reproduce**
1. Update to 3.9.14 from 3.9.13 inside the app
2. Tried to hide the icon according to thew release notes
3. Cannot find the option menu

**Expected behavior**
To be able toggle the editor icon somewhere in the app

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.1

**Comment by stefan-yas** [comment]
Hey @hisel-sabermetrics, could you log in and out of the app and try finding the toggle again?

**Comment by moughxyz** [comment]
Here's some visual context as to where the option is:

<img width="295" alt="Screen Shot 2022-01-13 at 6 46 08 AM" src="https://user-images.githubusercontent.com/3277844/149332810-08622e17-57ac-49d7-ac32-8c33c6d5e257.png">
