### ISSUE TITLE
Folder problem with 3.9.14

### ISSUE THREAD

**Issue by umbellipher** [standardnotes/forum#1509]
**Describe the bug**
Desktop app: with folders enabled, they do not appear on opening, and there is a note at the top that there is a folder problem.

**To Reproduce**
1. Open SN and enter passcode. SN opens.
2. With folders switched on, no folder tree appears, and there is an error message at the top. Reloading does nothing.
![1](https://user-images.githubusercontent.com/59395777/149326884-daa4668d-5b43-4770-994d-8f497828758b.png)
3. Disable folders - and they appear, but a new folder cannot be set.
![2](https://user-images.githubusercontent.com/59395777/149326905-5697fb11-2a77-4099-a2e9-0dcd400b075a.png)
4. Enable folders again, and it becomes possible to add a new folder and create new note within it.
![3](https://user-images.githubusercontent.com/59395777/149326942-a098f827-f74a-475f-ac94-934645c316f2.png)
5. Close SN, re-open, and the problem at 1. reoccurs.

**Expected behavior**
See, add to, edit folders on opening, with folders enabled.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - Windows 10 Enterprise 19043.1415
 - Desktop app (via Scoop)
 - Version 3.9.14

**Additional context**
Nothing to add.

**Comment by BillPerrin** [comment]
This happens to me on the desktop app 3.9.20 in Fedora 34 and Debian 11 (AppImage). To restore the folders I must log out, and then log back in after restarting the program.

**Comment by atmoio** [comment]
This issue will be fixed in 3.10 (beta available now: https://github.com/standardnotes/desktop/releases)
