### ISSUE TITLE
3.9.14: as in the previous issue, the resize button doesn't work, ...

### ISSUE THREAD

**Issue by umbellipher** [standardnotes/forum#1510]
**Describe the bug**
As in 3.9.13, the resize button (see image) is of no effect, the app is always maximized, and always on top of the screen.

The Windows 10 pop-up taskbar becomes inaccessible. To do anything else on the screen requires minimizing the app entirely.

**To Reproduce**
N/A

**Expected behavior**
As above.

**Screenshots**
![Screenshot - 13_01_2022 , 15_57_24](https://user-images.githubusercontent.com/59395777/149354579-bf0ad454-9884-4c98-b4d8-1d0faf0cf6bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 19043.1415
 - Desktop app3.9.14

**Comment by stefan-yas** [comment]
Hey @umbellipher, thanks for the report, but I couldn't reproduce your issue in either 3.9.13 or 3.9.14. Could be a generic problem with Windows, I've had this issue before with other software, so I don't think it's specific to Standard Notes.

**Comment by umbellipher** [comment]
@stefan-yas 

FIXED: Three lines, top left > View > toggle off "Toggle Full Screen".

I did not know this option existed, until I thought to look. Is it 'On' after installation by default?
