### ISSUE TITLE
Themes not loading color schemes correctly on launch/

### ISSUE THREAD

**Issue by filupmarley** [standardnotes/forum#1513]
**Describe the bug**
When opening standardnotes the current theme colors are not loaded correctly. The main note body is correct, but the remaining screen is white. Switching themes corrects the issue. Reappears at each next app launch. Same issue with web app. Currently using Windows Desktop 3.9.15

**To Reproduce**
1. Close standardnotes app.
2. Re-Launch standardnotes app
3. Focus theme or any theme that was selected at last close does not open with correct scheme

**Expected behavior**
Correct theme color scheme is loaded with standardnotes launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/28628909/149637261-72a31151-b7ba-4b53-82c5-20220d3b9321.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 96.0.1 (64-bit)

**Additional context**
I'm 1 year into my 5 year plan. I'm using the legacy plan.

**Comment by stefan-yas** [comment]
Hey @filupmarley, thanks for the report! I tried to reproduce this issue with no success. Could you sign out and in of the Windows app and then try to reproduce? If the issue persists, perhaps it's worth sharing a brief screen recording, just so I can get a sense of the flow which may be happening.

**Comment by upward4** [comment]
I'm using a third party theme ([Gruvbox Dark](https://github.com/christianhans/sn-gruvbox-dark-theme)), and it doesn't load properly anymore. Actually, I can enable it and it applies, but after a refresh (F5 on Firefox), SN reverts to the default (light) theme.

Here's a screencast I made: https://streamja.com/0jjkj. This has been recorded on a fresh Firefox profile (no extensions, customizations etc.). As you can see, there's also a 404 error in the javascript console, but I don't know whether it's related to this issue.

Hope this helps.

**Comment by atmoio** [comment]
This will be fixed in tomorrow's 3.11 release.
