### ISSUE TITLE
Windows app: Search does not include pinned notes

### ISSUE THREAD

**Issue by popolski67** [standardnotes/forum#1515]
When using the Windows desktop app, the search functionality does not find keywords from titles of pinned notes. When I remove "pinned" status using  the mobile device, then the note is found by the search functionality of the Windows app. I would prefer that a note is always found - whether pinned or not.

**Comment by stefan-yas** [comment]
Hey @popolski67, if you're using tags or folders, perhaps you're still in one folder while searching for your pinned note? Try going to "All notes" and searching then, Standard Notes should return pinned notes as well. If your note is protected, make sure you also include these in your searches, by enabling this option:

![image](https://user-images.githubusercontent.com/52251483/149734579-740a8d37-4e5c-4ca4-9a88-72d1904870c9.png)

**Comment by effieeee** [comment]
Closing, Stefan's comment applies to latest versions as well
