### ISSUE TITLE
Persistent potential sync issue

### ISSUE THREAD

**Issue by alxtrnr** [standardnotes/forum#1516]
**Describe the issue**
Persistent potential sync issue showing up when signing in on desktop and web app despite ending all sessions and signing out of account on all devices used. 

**To Reproduce**
1. Use the web app or desktop app

**Expected behavior**
1. No sync issue after ending all sessions and signing out then in again. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu Ubuntu 20.04.3 LTS
 - Browser: Brave
 - Desktop app
 - Version: standard-notes-3.9.15-linux-x86_64.AppImage

**Smartphone (please complete the following information):**
 - Device: Galaxy S- A600FN
 - OS: Android 
 - Browser: Brave
 - Version: 10

**Additional context**
standard-notes-3.9.15-linux-x86_64.AppImage causes my laptop to work very hard going by the fan activity.

**Comment by moughxyz** [comment]
Are you self-hosting? If so you'll need to update. If not this would be an account specific issue. Please DM or email me with your account email.

**Comment by alxtrnr** [comment]
Will do. Thanks. @moughxyz

**Comment by alxtrnr** [comment]
> Are you self-hosting? If so you'll need to update. If not this would be an account specific issue. Please DM or email me with your account email.

I have emailed you. The problem persists...

**Comment by alxtrnr** [comment]
Thanks @moughxyz - Sync issue sorted.
