### ISSUE TITLE
Unable to download files and image using FileSafe in Bold Editor

### ISSUE THREAD

**Issue by Maker9001** [standardnotes/forum#1517]
**Describe the bug**
When I attach a file to a note, the file is successfully uploaded into the Webdav server (Nextcloud). The json file appear encrypted in the server. However the file is not downloaded back into Standard Notes, so it's not visible or accessible. 
If it's a screenshot or an image that should appear in the note, it shows "Unable to download image.png...". When using the "Download" button in the FileSafe action bar, it shows "Error downloading file".

**To Reproduce**
1. Configure FileSafe by adding an integration to WebDAV
2. Open a note and add a file (or paste a screenshot in the note)
3. Try to download the file

**Expected behavior**
I expect to be able to download the file attached to a note or see it in the note when it's a screenshot.

**Screenshots**

When I paste a screenshot, I get this back:
![image](https://user-images.githubusercontent.com/83036878/149830480-c0fba681-69f1-4574-9669-d2bd1edd4209.png)

When I download a file, I get this back:
![image](https://user-images.githubusercontent.com/83036878/149830799-17df5453-7dde-4b3b-9f07-a38c99f0cb5e.png)
![image](https://user-images.githubusercontent.com/83036878/149831565-b051b2b5-d321-4a6a-8053-30f8288e224a.png)

What appear in the developer tool console:
![image](https://user-images.githubusercontent.com/83036878/149831029-a0a915a6-2311-4dfe-b843-194eccbba6ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Mozilla firefox 96.0)
 - Version Standard Notes: 3.9.5

**Additional context**
I tried to clear the cache and reload without success. I also tried on two computers, one running windows 10, and the other one running a Linux/Ubuntu OS. The same happen if I use the https://app.standardnotes.org/ website.

**Comment by effieeee** [comment]
FileSafe deprecated :(
