### ISSUE TITLE
2FA Setup broken

### ISSUE THREAD

**Issue by Consoledotlog** [standardnotes/forum#1518]
_ I'm fairly new to 2fa in general so I might be missing something obvious _

I went to enable 2fa in the windows native standard notes app, first using Zoho's Oneauth on my phone. The qr scans fine but then on the 3rd step where I enter my secret key & authorization code from the authenticator app, all I get is: "Incorrect authentication code, please try again." . I've also tried with the lastpass authenticator to the same end. I can intentionally enter an incorrect secret key and instead get "Incorrect secret key, please try again." Also, using or not using a space between the 6 digit code make no difference.

Desktop
 - Windows 10, 19044.1466
 - Version 3.9.15 of Standard Notes

**Comment by stefan-yas** [comment]
Hey @Consoledotlog, thanks for the report! I couldn't replicate your issue using using Aegis, Authy or Google Authenticator clients at this time. What happens if you use another app such as Authy, Google Authenticator or Aegis?

**Comment by atmoio** [comment]
Be sure your system clock matches on all devices involved.

**Comment by Consoledotlog** [comment]
Ah okay yes it works just fine when using Authy. So are only those authenticators intentionally supported right now?

**Comment by stefan-yas** [comment]
> Ah okay yes it works just fine when using Authy. So are only those authenticators intentionally supported right now?

They should work all the same, in my experience. Let's try Zoho's client now. Try to be quick when instructed to add the six-digit code in Standard Notes.

**Comment by bigjdunham** [comment]
I am getting the same bug now with Standard Notes Linux app 3.150.7, web app, android app with latest self-hosted server.

**Comment by MFYDev** [comment]
I am getting the same error now in the latest self hosted server, I am using 1Password @effieeee @stefan-yas 
Could you please have a look on this issue?
