### ISSUE TITLE
2.1 beta available for testing

### ISSUE THREAD

**Issue by moughxyz** [standardnotes/forum#152]
# 2.1 Beta

2.1 features an all new extensions system, including a browser, local installation (on desktop) and autoupdate.

[Desktop download links](https://github.com/standardnotes/desktop/releases)

[Preview web app](https://preview.app.standardnotes.org/)

### Other new features:
- New UI for menus and panels
- Resizable and collapsable panes (tags, notes, editor)
- Fine grained display options in the notes pane
- Ability to toggle monospace font and spellcheck globally (available in Menu in editor pane)
- Search results count (no in-note searching yet)
- Ability to change local passcode without removing it
..and more.

### Local Extensions:
When using Desktop, any extension you install is automatically installed and run locally. You can confirm an extension is running locally by one of:
- If editor, click the Editor menu, then check for "Running locally" under the editor name.
- If not editor, you can open the Inspector via Cmd+Option+i (or Ctrl+Alt+i) and noticing the log output "Loading Action Bar /Users/mo/Library/...". The part after the name is the extension URL, so if you don't see http, it's loaded locally.

You can force an extension to only use the local installation by opening Extensions, clicking the three dots button (...), and unchecking "Use hosted when local is unavailable".

You can browse your installed extensions on your system by clicking Help in the top level menu, then Open Data Directory. You'll find everything in the "Extensions" folder.

### Issues

Pleaes report any issues via any of the following channels:

1. On the [Slack](https://standardnotes.org/slack) group, in the #beta channel.
1. [Web repo](https://github.com/standardnotes/web/issues) issues (if the issue is related to the functioning of the actual app) 
1. [Desktop repo](https://github.com/standardnotes/desktop/issues) (if the issue is related to the Desktop shell around the web app).
1. [Via email](mailto:beta@standardnotes.org)

### Extended code
The new extensions manager requires an Extended code. If you are an Extended member, you can find your code by signing into [https://dashboard.standardnotes.org](https://dashboard.standardnotes.org), then scrolling to the bottom of that page. Copy and paste that code into the Extensions manager input.

### Two-factor authentication
You can toy with installing 2FA, but note that it won't actually be enforced for login just yet (until the new server is deployed).

**Comment by mobitar** [comment]
Also, when using 2.1, old themes will look a little funky. You will need to install the new themes directly from the extensions manager (by uninstalling old ones).

**Comment by bnjbvr** [comment]
Thanks for the update! Looks full of great features!
Will the extension repository format be documented/open-sourced as well?

**Comment by navedcoded** [comment]
Just used it for around a day, looks great and runs great! The new editor margin adjusting is awesome too — but doing that leaves ugly white regions on the left and right of the editor. (See [attached screenshot](http://fb.pics/image/G0Ht))

**Comment by rubiojr** [comment]
I've been using it for a while, using Debian package 2.1.0-beta.3 now with Ubuntu 18.04 (alpha). Seems to be working fine :muscle:.

**Comment by mobitar** [comment]
@bnjbvr yes totally. Hope to document it soon.

@navedcoded wow, good catch! Will get this fixed.

@rubiojr awesome!

**Comment by navedcoded** [comment]
One more thing: after starting to use the beta 4 yesterday, the Android app takes an awful long time (20s) to decrypt. After than, the `+` button is missing and I cannot add a note. Editing an existing note makes the app crash. I don't think the android app was updated recently — so I think it's the beta

**Comment by mobitar** [comment]
Strange. Are you on the Android beta? Can you double check the version
number from the settings menu

On Feb 5, 2018, at 9:09 PM, Naved Islam <notifications@github.com> wrote:

One more thing: after starting to use the beta 4 yesterday, the Android app
takes an awful long time (20s) to decrypt. After than, the + button is
missing and I cannot add a note. Editing an existing note makes the app
crash. I don't think the android app was updated recently — so I think it's
the beta

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/forum/issues/152#issuecomment-363296432>,
or mute the thread

**Comment by navedcoded** [comment]
Actually, even the settings icon had disappeared... But Google play said
it's version 2.0.4

But deleting and reinstalling the app solved the issue, until I fully
closed then reopened the app. That caused the same issue to happen again.

I am on a Samsung S8+, android 7.0 on the November 2017 patch, btw

**Comment by mobitar** [comment]
@navedcoded sorry I'm confused. You initially mentioned "after starting to use the beta 4 yesterday"—is this beta 4 of the Android app, or the desktop app? Because the desktop app only has up to beta 3. Can you open the Android app, go to the Settings menu, scroll all the way to the bottom, and note the version number present there?

**Comment by navedcoded** [comment]
Sorry, this *is* confusing.

I am using the desktop beta 4: screenshot (http://fb.pics/image/SdUt) 
of what I downloaded from the releases page on Github. I just scrolled 
past beta 3, and saw this is more recent.

On Android, I am unable to access the settings page of the app (the 
gear icon is not there). Google Play says I am on version 2.0.4, and I 
do not recall joining any android beta for Standard Notes.

**Comment by mobitar** [comment]
Oh wow, GitHub doesn't seem to be ordering the releases correctly for some reason. So yeah, there are 4 betas for desktop.

Strange re Android, especially since you haven't updated. So even quitting the app and restarting it doesn't fix the issue? I would really doubt it would have anything to do with any new data format..although..do you use themes on Android? It could be something to do with that. I'll investigate that area.

**Comment by mobitar** [comment]
Btw can you try joining the Android beta and seeing if the latest beta fixes the issue you're having? https://play.google.com/apps/testing/com.standardnotes

**Comment by oksanafromhelicopterears** [comment]
Not sure if this is where we report bugs - I'm new here - but, in web app, as soon as I edit tags on a note, its first 11 (I think) become unavailable to click on. Cursor turns into a pointer and I'm unable to click in a place I want to edit in the note's body. This happens on any note I edit tags on. Possibly can be reproduced in other ways. The menu bar (Menu / Editor / Actions) could be the culprit, as it becomes unusable also.

**Comment by mobitar** [comment]
I'm sorry, I'm not following—what do you mean by "its first 11 (I think) become unavailable to click on". Do you have 11 tags on a single note?

**Comment by benwhi** [comment]
No, first 11 lines - sorry. The note's first 11 or 10 lines. Not tags.

I logged into the regular app now, https://app.standardnotes.org/,  and the exact thing seems to be happening there. That was definitely not an issue last time I used the web app, which I think was about a week ago. I wonder if need to clear browser cache or something.

**Comment by benwhi** [comment]
It appears to be a bug in firefox. Signed into the web app in Chrome - no such issues. In Firefox, with each tag clicked off or added, more and more text of the note becomes unclickable for me. It could be some extension getting in the way, I don't know, or the recent updates interfering with something.

**Comment by mobitar** [comment]
@benwhi is this with the Autocomplete Tags extension? I'm able to replicate this issue on Firefox. Thanks for the heads up, will investigate.
