### ISSUE TITLE
Very sloooooow load time on Android  12 / Samsung S10e

### ISSUE THREAD

**Issue by Severus-Sixt** [standardnotes/forum#1520]
Team, the Android 12 app takes 25 seconds to load each time I unlock it on my phone. (Samsung S10e / Android 11). All my other apps run very smooth.

I find myself doing other things while waiting for it to load or even not going back and editing a note because I dread it loading for ever again.

I have 2500 notes and plan to have many more. 

Is there a way Standard Notes can handle this? 

Thanks

**Comment by atmoio** [comment]
On our mind to solve this 👍 No ETA as of yet.

**Comment by effieeee** [comment]
Loading times improved on latest versions and new mobile UI
