### ISSUE TITLE
Setting default editor in the mobile app

### ISSUE THREAD

**Issue by simpliston** [standardnotes/forum#1523]
I looked through the open issues and pull requests, but I could not find anything about this. Setting default editor on the desktop application is great and saves time. Are you considering adding the same to the app? The plain editor is too limited for my use

**Comment by adrihut** [comment]
Hi @MrYdse!

I understand you're looking for a way to make a specific editor type your default one on the mobile version of Standard Notes.

<br>

I'm happy to report that this functionality is already part of both of the mobile apps (iOS and Android), and can be enabled simply by navigating to the options menu—_tapping on the three horizontal lines_ (![hamburger-menu-icon](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hamburger_icon.svg/11px-Hamburger_icon.svg.png)) _located on the top right-hand corner of the note composer screen_—and following these few instructions:

1. Locate the **Editors** section—_and tap the word "Editors" to expand it, if it isn't already_.
1. Tap and hold on the name of the editor you'd like to make default.
1. Tap the "_**Set as Mobile Default**_" option displayed toward the bottom of the screen.

From now on, the editor you selected will be used to display the contents of all notes by default, except the ones for which you've selected a different specific editor.
<br>

I hope you found this information useful, happy note-taking!

**Comment by simpliston** [comment]
Ah, thank you, it worked! Though I would suggest making the feature more obvious if possible. Either by adding it to settings or just adding a small help text in the options menu. Thanks for the help, and I really appreciate the product!

**Comment by adrihut** [comment]
We're glad to hear you were able to set up the new default mobile editor without any issues!

<br>

Thanks a lot for your feedback and appreciation; we hope to continue serving your note-taking needs for many years to come, so please don't hesitate to reach out again if there’s anything else we can assist your with in the future.

I'll go ahead and close this issue now.
