### ISSUE TITLE
2FA for everyone

### ISSUE THREAD

**Issue by Evenfire** [standardnotes/forum#1525]
> **Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

Yes

> **Is your feature request related to a problem? Please describe.**

The free plan does not include 2FA. People who **can't** or won't pay don't get 21th century security.

> **Describe the solution you'd like**

2FA included in the free plan, please.

> **Describe alternatives you've considered**

Paying. But what about people who cannot ? Alternatives: none

> **Additional context**

![Screenshot 2022-02-04 183942](https://user-images.githubusercontent.com/17130958/152576998-49bc6f50-db60-4c92-82b9-82ad6930199f.png)

Product seems great, thanks!

**Comment by myreli** [comment]
https://standardnotes.com/blog/two-factor-authentication-for-all
