### ISSUE TITLE
Unable to write to local database. Please restart the app and try again.

### ISSUE THREAD

**Issue by iamthegiantgreengoat** [standardnotes/forum#1528]
**Describe the issue**
I receive this message when I am in a normal Firefox tab:

Unable to write to local database. Please restart the app and try again.

There was an issue loading your offline database. This could happen for two reasons: 1. You're in a private window in your browser. We can't save your data without access to the local database. Please use a non-private window. 2. You have two windows of the app open at the same time. Please close any other app instances and reload the page.

**To Reproduce**
Enter any character into a note or create a new note.
Note count is currently 0

**Expected behavior**
I expect data to populate the title field and the note field.

**Screenshots**
The error is copy and pasted above.

**Desktop (please complete the following information):**
Windows 10
Firefox 96.0.3

**Smartphone (please complete the following information):**
Works fine on Android.

**Additional context**
Firefox is on default settings for privacy and security.

**Comment by stefan-yas** [comment]
@iamthegiantgreengoat Thanks for the report! Do you have any other instances of Standard Notes running on any other devices or browsers? If so, perhaps try closing them first and see if the issue occurs.

If not, do you have any extensions that may be affecting how Standard Notes behaves on Firefox? Eliminating extensions one by one and seeing if anything changes could be a good systematic approach to seeing if there's any interference with the extensions.

Please post your a screenshot of the console and the network tab in Firefox dev tools, if you can - perhaps there's some helpful info there.

**Comment by juliedavila** [comment]
I'm hitting this too. Both on web (safari) and the MacOS desktop.

**Comment by effieeee** [comment]
Hi @juliedavila, can I ask you for the same info that Stefan mentioned in his comment above?

**Comment by senescence01** [comment]
I'm having the same issue on the android app and browser (Vivaldi)...

![Clipboard01](https://user-images.githubusercontent.com/108657131/214033940-f83d47af-24c5-4bc3-b043-29d246f9c735.jpg)

Edit: Tested on Edge browser too, with default settings and no extensions whatsoever, but the issue remains...

**Comment by senescence01** [comment]
I think I got it working. I logged in, hit ok on the error, and then went on to end all sessions. After logging in again, there was no error...

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
