### ISSUE TITLE
There isn't "Sort Notes By" option in Web app and macOS app

### ISSUE THREAD

**Issue by malikshukurlu** [standardnotes/forum#1529]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes

**Is your feature request related to a problem? Please describe.**
There isn't "Sort Notes By" option in Web app and macOS app, but there is in Android app.

**Describe the solution you'd like**
Please add this option to web app.

**Describe alternatives you've considered**

**Additional context**
in Web app default Sort option is "Date Added".. And I can't change this option.

**Comment by stefan-yas** [comment]
Hey @malikshukurlu, you should be able to sort the notes by clicking on the "Options" in Notes view as pictured below.

![image](https://user-images.githubusercontent.com/52251483/153526815-29ed8124-3467-4b85-83ec-3566a379e02c.png)

**Comment by malikshukurlu** [comment]
Thanks @stefan-yas, I had not seen this.
