### ISSUE TITLE
Tag pane chaos

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/forum#1531]
After a few hours of tag pane chaos, the tag pane is now completely gone in both desktop and web versions for Linux and Windows.

What's happening. Are Standard Notes servers getting hacked?

And yes, I have installed version 3.10.0 of the desktop app. And restared Standard Notes. And signed out and in. And rebooted.

**Comment by atmoio** [comment]
Ensure Focused Writing is disabled, and that your panes aren't collapsed. You can double click the long vertical bar of a collapsed pane to expand.

**Comment by onlinemumie** [comment]
Focused writing is disabled and the pane is not collapsed.

**Comment by onlinemumie** [comment]
Wait a minute, after a restart I was able to expand it. Looks pretty rough through, with a "Rename Delete" option that expands whenever I click on a tag. And smart tags are greyed out (but works). Is this intentional?
