### ISSUE TITLE
Code editor does not remember chosen language in v3.10.0

### ISSUE THREAD

**Issue by johnsonjzhou** [standardnotes/forum#1532]
**Describe the bug**
In Standard Notes v3.10.0, code editor no longer remembers / honors the chosen default language or the last used language for that note, when loading the note. It will always revert back to Javascript.

**To Reproduce**
1. Create a note with code editor and select any language other than Javascript.
2. Navigate away from that note.
3. Navigate back to that note.
4. Code editor will display with Javascript rather than the last chosen language.

**Expected behavior**
Code editor should remember the last chosen language or use the chosen default language when creating new notes. This was the behaviour prior to v3.10.0.

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1

**Comment by atmoio** [comment]
Can confirm issue, thanks.

**Comment by johnsonjzhou** [comment]
Issue seems to be resolved in 3.11.0.
