### ISSUE TITLE
Search by multiple tags

### ISSUE THREAD

**Issue by marcosh** [standardnotes/forum#1534]
Is it possible to search notes filtering by multiple tags?

For example, if I have a `work` and a `friends` tag, I'd like to search all notes with both tags

**Comment by stefan-yas** [comment]
You could do that by [creating a Smart Filter](https://standardnotes.com/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters). So in your case, it would be `!["Work & Friends", "tags", "includes", ["title", "in", ["work", "friends"]]]`. Note that Smart Filters are a paid feature.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)
