### ISSUE TITLE
la colonne des notes ne s'affiche pas ( sur mon ordinateur de bureau, uniquement )

### ISSUE THREAD

**Issue by acha85** [standardnotes/forum#1535]
depuis une semaine, lorsque j'ouvre SN desktop, les notes ne s'affichent pas mais, dans cet espace, apparaît un message: "the extension was not found on your system..." ( voir la pièce jointe )
j'ai un compte payant, SN core
j'utilise SN sous linux Ubuntu x86_64
mon navigateur: firefox

SN s'ouvre normalement sur mon téléphone et bien sûr en ligne sous firefox

merci à celles et ceux qui pourront m'éclairer pour résoudre ce problème facheux? André H.

![SN-préférences-14fevr](https://user-images.githubusercontent.com/60747298/153843725-a69df0ae-3fee-463b-a3e5-f0075b429527.png)
![SN-probl-affichage-notes](https://user-images.githubusercontent.com/60747298/153843728-5d7bbc7b-a16e-4095-991c-1fde359a2ca5.png)

**Comment by atmoio** [comment]
Can you upgrade your app to 3.10? You can download the latest version from our homepage. If that still doesn't help, please reach out to help@standardnotes.com with your account email.
