### ISSUE TITLE
"Standard Notes has stopped" upon launch in Android

### ISSUE THREAD

**Issue by Marxsal** [standardnotes/forum#1536]
Every time I try to launch on Android, it says "Standard Notes has stopped".

Every time.

**Expected behavior**

For the app to open just like any app on Android should.

**Smartphone (please complete the following information):**
Moto G6 
Android 8
SN 3.10.2

**Background**

I had SN intalled (premium). I signed out. I signed back in. Nothing but a blank screen.
Then I uninstalled, and re-installed with the most recent version (3.10.2) from the play store.

**Comment by atmoio** [comment]
Can you try version 3.11.0 to see if it fixes the issue?

**Comment by Marxsal** [comment]
Vsn 3.11.0 doesn't appear in the playstore.

**Comment by stefan-yas** [comment]
@Marxsal Feel free to sideload the .apk downloaded from [mobile releases here](https://github.com/standardnotes/mobile/releases).
