### ISSUE TITLE
migration from Folders to Nested Tags hangs

### ISSUE THREAD

**Issue by ccrowner** [standardnotes/forum#1537]
**Describe the bug**
Folders now forces Migration but then when running migration app hangs in Chrome
New: Folders to Nested Tags

**To Reproduce**
1. click on Migration Available in Folders sidebar
2. click on Run Migration

**Expected behavior**
Migration runs and restore Folders (or Nested Tags equivalent)

**Comment by ccrowner** [comment]
patience helps - migration appears successful

**Comment by atmoio** [comment]
How many tags did you have 🙂

**Comment by ccrowner** [comment]
595 tags

It took a long time but the migration appears successful.
Is it the case that every time I open StandardNotes all the nested tags are
displayed? Is there a way to change this behavior?

Also, I have had persistent trouble downloading Decrypted Backups (on both
Chrome and in Windows Desktop app).
I download a Encrypted Backup (providing my password) then when I select
Decrypted it hangs/fails - in the case of the
Windows 10 app the StandardNotes apps exits (though there persists a
Process)

I have 9492 notes - I am informed that there are too many notes for
Automatic Backup to email

Thanks!

**Comment by atmoio** [comment]
> Is it the case that every time I open StandardNotes all the nested tags are
displayed? Is there a way to change this behavior?

Once you collapse a parent that should be remembered across sessions. Is this not the case for you?

How big is the file when you download an encrypted backup? It may be hanging due to memory pressure. 9k notes is definitely a lot.

**Comment by ccrowner** [comment]
No, when I reenter my tab with my StandardNotes all of my parents are
expanded. With over 500 tags it is a pain to recollapse them

I successfully backup a 78.2 MB Encrypted notes file. How much bigger could
a Decrypted backup be (encryption does not compress does it?)?
I have always experienced problems doing Decrypted backups (which I prefer
since worst case scenario I can handle a big json file)

**Comment by atmoio** [comment]
Please update to 3.11.0 for the collapse issue.

A 78mb dataset would indeed cause some hanging. I would use the desktop app for this and just give it some time to process.

**Comment by ccrowner** [comment]
Will do, thanks!
