### ISSUE TITLE
3.10.0 screwed up the folders and won't decrypt notes

### ISSUE THREAD

**Issue by SpaceRaccoonFluff** [standardnotes/forum#1538]
I'm using Manjaro Linux with the Standard Notes Appimage. After opening up the app and putting the application password, the entire thing is just frozen. Before putting in your application password I can click on the thing in the top left corner and clear cache and all the other things there but once you put in the password, everything if frozen, nothing inside the app is clickable besides closing the app. At the bottom there is a small text saying "Decrypting 0/168 items..." but it doesn't progress, stuck at 0. When I re-download the appimage and try again, it works perfectly, but after you close the app it goes back to this issue. This only started happening once I downloaded 3.10.0, it wasn't doing this before.

When I downgrade back to 3.9.20 everything works besides my folders. They seem to be permanently messed up. Also it looks like the amount of notes I had went from 168 to 122. Did they get deleted? I have email backups but that's pretty scary if true to loose that many notes.

**Comment by atmoio** [comment]
Likely an exception occurring blocking execution of further code. Can you open top-level Help > Toggle error console, then choose the Console tab, then share a screenshot of what you see (when you experience the issue)?

Regarding note counts, 3.9.20 and 3.10 differ in how they count notes. 3.10 has the correct counts.

**Comment by SpaceRaccoonFluff** [comment]
This came up after putting in my application password.
![standardnotesconsole](https://user-images.githubusercontent.com/97198569/154330736-124e2f38-5a2e-49ec-a15a-f609eecb6a2a.png)

**Comment by atmoio** [comment]
Hmm. We'll include a patch for this for tomorrow's release. Likely some unexpected tag hierarchy or botched migration.

**Comment by SpaceRaccoonFluff** [comment]
Great, thanks.
