### ISSUE TITLE
Web & MacOS Desktop Apps Unresponsive

### ISSUE THREAD

**Issue by andyhitchcock90** [standardnotes/forum#1539]
I'm having an issue with 3.10.0 where SN is stuck at "Decrypting 0/x items" and unresponsive. I can scroll up and down the folder list, item list, and in my first note which opens with the app but can't click anything, including app settings.

I usually use the web app but tried downloading the MacOS desktop app and am having the same issue - the desktop app itself is apparently running fine but I can't do anything within it as it's stuck on decrypting. Using the Android app seems to be working fine. Any help or suggestions would be greatly appreciated.

Edit to add: Error console shows the following
```
ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentId')
    at Zr.getTagParentChain (app.js:2)
    at Zr.getTagPrefixTitle (app.js:2)
    at s.getTagPrefixTitle (app.js:2)
    at t.NoteTagsState.getPrefixTitle (app.js:2)
    at app.js:2
    at app.js:2
    at app.js:2
    at et (app.js:2)
    at e.t.track (app.js:2)
    at w (app.js:2)
```
Could this be a problem with reading folders after converting them from tags?

**Comment by atmoio** [comment]
This will be fixed in today's 3.11 release.

**Comment by atmoio** [comment]
3.11 available now: https://github.com/standardnotes/desktop/releases/tag/v3.11.0

**Comment by andyhitchcock90** [comment]
That's sorted it. Thanks Mo
