### ISSUE TITLE
Are Plug In extensions dead now?

### ISSUE THREAD

**Issue by drhus** [standardnotes/forum#1540]
since the last changes to Standardnotes it seems that all extension became kind of default and there are no option to add new one? is plug in extensions disabled if not how to install external one?

**Comment by throwaway82945** [comment]
Go to Settings > General > Advanced Settings

**Comment by Teofilios** [comment]
In Advanced Settings, you do not have the option to install new extensions. There is an option to install Custom Extension, but you need extension URL.I cannot find web pages for Plus Editor or Bold Editor.

**Comment by stefan-yas** [comment]
@Teofilios if you are on the paid version of Standard Notes, the Plus and Bold editors are included with your subscription, so they don't require an URL to install.

**Comment by dnszero** [comment]
@stefan-yas Yes they do require a url. On a paid account, I just uninstalled the Plus Editor on the desktop (because of an error message), and now there is no way to re-install it without a link. :(

**Comment by myreli** [comment]
You can check https://github.com/standardnotes/plugins. It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
