### ISSUE TITLE
enable opting out of login email notifications

### ISSUE THREAD

**Issue by chaserene** [standardnotes/forum#1543]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
yes.

**Is your feature request related to a problem? Please describe.**
for a while now, the official server has been sending email notifications about logins to one's Standard Notes account. the way it works lessens one's privacy: each mail exchange server the email passes through learns the following:

* this person uses Standard Notes
* they logged into their account at a certain time
* from a certain operating system (and by proxy, device)
* using a certain version of the SN client.

while this brings the obvious security benefit of being informed when there's an unauthorized access to the account, not everyone wants to make this trade-off between privacy and security. I wish this trade-off were decided with the user's consent, but I recognize the difficulties of that. **my main issue is that there is no way to opt out of this feature.** 

**Describe the solution you'd like**
* in the first such email for each user, I'd like to see a short introduction saying that login mail notification are now a thing. this improves a bit on the consent issue.
* I'd also like to see, in every notification email, a hyperlink with the same font size as the email body that lets the user opt out of these emails.
* I'd also like to see an entry in the application's settings that allows the user to turn this feature on if it's turned off. this takes care of the case when someone opts out by accident or changes their mind. (it wouldn't let them turn it *off* in the app, since we're using email as an 2nd factor check. it would be too easy for an attacker to turn off login notifications in a logged-in instance, then log in from another device, without leaving a trace in the victim's mailbox.)

**Describe alternatives you've considered**
* moving the whole of the login notifications into the app (but that doesn't protect users who rarely use SN)
* requiring each new login to be approved from an existing login, Signal-style but without the master-slave hierarchy (but that makes it dangerously easy to lock yourself out)

**Additional context**
code-wise, this issue belongs to the [syncing server repo](https://github.com/standardnotes/syncing-server-js/issues?q=is%3Aissue+), but considering I reported there what I consider the greatest vulnerability in Standard Notes half a year ago and it received no substantial response, I'm posting here.

**Comment by atmoio** [comment]
I do agree this behavior should be customizable, and we will offer this option. But I'm wondering if as a user it would be risky to disable this alert? You now gain perhaps a little more privacy from your email provider, but you completely lose the ability to be notified of wanted access.

**Comment by chaserene** [comment]
it's a subjective trade-off. for some it isn't too risky, for some it is. there will inevitably be users disabling it who, from an educated point of view, "shouldn't". but the current mechanism doesn't let us detect those users. I see why this feature is important, but also be mindful that in surveillance metadata is just as valuable as data. the design space is vast and I'm sure there are solutions that satisfy both security, privacy and simplicity.

how about this: it can be disabled from within the email, but the disabling needs to be confirmed from within a client, informing you about the risks. if you approve, as long as emails are disabled, login alerts appear in your clients. in-client login alerts can't be disabled. this won't prevent all users from hurting their own security, but deters the unwilling, and allows only those users to expose themselves to "undue" risk who don't use SN often.

**Comment by atmoio** [comment]
We already have mechanisms for controlling preferences such as daily email backups, so we'll likely hitch onto that mechanism for this preference as well 👍

**Comment by wenman-ualberta** [comment]
This option should only be available if 2FA is enabled. If you have your 2FA device available when logging in SN should be able to reasonably assume you are aware you are logging in.
If 2FA is disabled you should still receive a notification email with the message that 2FA has been disabled.

**Comment by atmoio** [comment]
This option is now available in the latest version via Preferences > Security > Privacy.

**Comment by chaserene** [comment]
great, thank you so much! closing.
