### ISSUE TITLE
how do you add a nested tag?

### ISSUE THREAD

**Issue by ccrowner** [standardnotes/forum#1544]
The old folders had a '+' while the new nested tags has a count of the notes with the tag

I tried to create a new tag "existing tag/new nested tag"
but this creates a new tag with the forward slash in it - does the forward slash need to be escaped?

**Comment by atmoio** [comment]
Did you checkout the new 3.11.2 release? https://github.com/standardnotes/desktop/releases/tag/v3.11.2

> New: Right-click tags context menu with options to add subtag (for users with Folders enabled), rename, and delete. Also accessible by selecting a tag then clicking the three-dots button.

**Comment by ccrowner** [comment]
OK great, new version fixed it - thanks

**Comment by ccrowner** [comment]
fixed in new version
