### ISSUE TITLE
Search does not highlight within active note

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/forum#1545]
In the desktop app, when you search for something that is in the current/active note, it doesn't apply highlighting unless you click another note and then click back to the one you were on originally.

I guess the issue is that the highlighting only activates upon clicking/opening a note, which obviously wouldn't happen if the note was already open.

The expected behavior would be to activate/apply the highlighting after each key press, so that it occurs immediately in the current note.

**Comment by atmoio** [comment]
You can also press enter to highlight. I believe it can't be live because the act of highlighting takes focus away from the search field.

**Comment by virtuallyvlad** [comment]
> You can also press enter to highlight. I believe it can't be live because the act of highlighting takes focus away from the search field.

Just curious, is that an electron quirk?  And thanks for the enter tip; can't believe I never tried that.

**Comment by atmoio** [comment]
> is that an electron quirk

Yeah, it is. Because if you try to highlight while typing, Electron will find a result in the search bar itself, causing weird behavior.
