### ISSUE TITLE
Offline Subscription doesn't work anymore.

### ISSUE THREAD

**Issue by AUGUAA** [standardnotes/forum#1546]
**Describe the bug**
Offline Subscription is just as same as the Free Plan after an update or clean install.

**To Reproduce**
1. Install SN app
2. Type Offline activation code
3. The app says it is activated
4. No difference between the Free Plan and Offline Subscription.
5. Uninstalled and Reinstalled, relaunched, nothing different.

**Expected behavior**
Various editors should be available.

**Screenshots**
![My current SN status](https://user-images.githubusercontent.com/74411544/155659528-73064c17-0bc7-4dc9-bea2-cb080d129538.JPG)

**Desktop (please complete the following information):**
Windows 10 64-bit version 1809

**Smartphone (please complete the following information):**
Null

**Additional context**
Before an update, Everything worked fine. my previous version was 3.9.8
I received (converted) Offline activation code on Dec 8, 2021, and expiration date is sometime in 2025.

**Comment by atmoio** [comment]
We'll need your account email to look this up. Please get in touch directly.

**Comment by AUGUAA** [comment]
> We'll need your account email to look this up. Please get in touch directly.

Hi, this issue has been solved with one of the Standard Support Team staff. Thank you.
