### ISSUE TITLE
Tag folders (ex "tag nesting") was removed from Core plan

### ISSUE THREAD

**Issue by abaumg** [standardnotes/forum#1547]
I see that tag folders [were included in the Core plan](https://web.archive.org/web/20211111115330/https://standardnotes.com/plans), but [silently removed](https://web.archive.org/web/20220120222350/https://standardnotes.com/plans) in the past weeks. I understand that some features might be removed from the Free plan, but this is a feature I paid for.

Modifying existing plans and **silently removing already paid features** is a huge no-go!

**Comment by atmoio** [comment]
We definitely wouldn't pull paid features out from existing users. Tag folders was moved to a different plan for **new users** only. If you're an existing paid user and are having trouble accessing folders please contact us with your account email, as there may be some plan mixup with your account, i.e if you canceled and renewed or other various combos of actions.

**Comment by abaumg** [comment]
I contacted the StandardNotes support, and they were able to resolve my issue. Apparently, it was some kind of account mixup/hiccup. Therefore I would like to apologize for my annoyed tone. Everything is fine now.
