### ISSUE TITLE
Self Hosting Extensions requires subscription

### ISSUE THREAD

**Issue by twizzayy** [standardnotes/forum#1550]
First off, I just want to say that standard notes is my go-to note and pastebin application. I love everything that this software is doing and where the company is going. 
I want to be able to contribute to this project some day.

# **Describe the issue**
### SN version 3.9.0 allows me to self-host my own extensions.
&nbsp;
<img width="711" alt="Screen Shot 2022-03-04 at 5 12 39 PM" src="https://user-images.githubusercontent.com/88040412/156854533-34fdd66d-6644-40b3-b6ee-6e2347217404.png">
&nbsp;
&nbsp;
### From version 10 and over it seems to require a subscription even if I am self-hosting the extesnion repo on my SN syncserver.
&nbsp;
<img width="708" alt="Screen Shot 2022-03-04 at 5 10 38 PM" src="https://user-images.githubusercontent.com/88040412/156854642-6e179a5c-0dd4-4987-9a29-4211db9daf9c.png">
&nbsp;
&nbsp;
<img width="709" alt="Screen Shot 2022-03-04 at 5 07 15 PM" src="https://user-images.githubusercontent.com/88040412/156854656-d95267ff-9b77-432d-8075-83abf6f7d420.png">

&nbsp;
&nbsp;
&nbsp;

**Expected behavior**
I kinda liked it when the options were to either self-host or pay for the subscription although I can understand the need to up the ante on subscriptions in order to pay for the development of the project.

## OS's Affected
 - Mac OS Big Sur and Catalina
 - GNU/Linux: Debian, POP!_OS, and Manjaro
 - SN: Web app (Firefox Browser)
 - I have noticed that these issues do not apply to the IOS app.

**Comment by atmoio** [comment]
Self-hosted editors are very much possible. But you have to make sure their identifier does not match up with one of our precompiled identifiers, as that's how we determine whether they are official or not. Official ones require a subscription. So you'll need to reinstall these editors and make sure the ext.json payload identifier field does not include the traditional "org.standardnotes.x" format.

**Comment by twizzayy** [comment]
@moughxyz 
>you'll need to reinstall these editors and make sure the ext.json payload identifier field does not include the traditional "org.standardnotes.x" format

Thanks for the help. :)
Ok, so I have edited my `repo.json` file located in `/var/www/snserver/extensions`. I did a find for `org.standardnotes` and placed a `#` in front of every occurrence that was an "identifier" so they now read `#org.standardnotes.xxxx`

(Reminder: this is a Yunohost install, so the path might be different for others.)

 Then, I uninstalled all the extensions in the GUI under Account Settings > General > Advanced Options

However, now when I go to reinstall them with the link that is provided at "my.SN-instance.com/help (for me that would be https://my.SN-instance.com/extensions/repo.json) I get the following error:

![image](https://user-images.githubusercontent.com/88040412/157110808-a4e6c853-e415-4f2a-bae4-7f2274c9de90.png)

>Error downloading package details. Please check the extension link and try again.

Doing this from the Desktop app on Mac just causes the app to deadlock with no error displayed. The above screenshot comes fromthe web app.

Any ideas on what I'm doing wrong? Maybe I need to use a different name??

**Comment by atmoio** [comment]
> and placed a # in front of every occurrence that was an "identifier" so they now read #org.standardnotes.xxxx

Hmm I'd have to double check but we may be doing a string "includes" check and not a strict equality check. So you'd want to make sure the identifiers don't include "org.standardnotes" at all.

**Comment by twizzayy** [comment]
@moughxyz will it be necessary to also edit the individual extension JSON files located in `/var/www/snserver/extensions/src`?

I just noticed that each of these also include the 'org.standardnotes.xxxx`

I will try removing the entire string from the `repo.json`

**Comment by atmoio** [comment]
I'm not familiar with your server layout/architecture so I couldn't say. Ultimately you can load the URL in your browser first and make sure the response doesn't include that identifier anywhere.

**Comment by twizzayy** [comment]
@moughxyz 
Removing the entire `org.stndardnotes.` string from `repo.json` and from the individual extension JSON files still does not allow me to install them in version 3.12.0 or on the web app. Getting the same error.

Tested by first removing the string from repo.json and then additionally from the extension JSON files.

Switching to version 3.9.0 yielded the same results. I seem to be effectively locked out of installing these...

Any other thoughts?

**Comment by twizzayy** [comment]
Duplicate of #789

My solution came from this issue: 
https://github.com/YunoHost-Apps/snserver_ynh/issues/58

**Comment by atmoio** [comment]
Can you share the JSON payload of the URL you're entering in the input box?

**Comment by twizzayy** [comment]
[redacted]

**Comment by atmoio** [comment]
Link doesn't work..

**Comment by User-Deleted** [comment]
https://paste.mylegendary.quest/?b040c341eeb54817#5rEQZab64ZXQmMkUEA6tsjFhZJKcQwvp8q9PDv53ewPP

Sorry about that.

**Comment by twizzayy** [comment]
[redacted]

sorry about that.

**Comment by atmoio** [comment]
So the input doesn't support the legacy "repo" concept anymore. Packages need to be installed individually. So you'd take each blob inside packages and put that in its own endpoint. Basically you already have this since that's the `latest_url` value in each entry. Just put that URL into the input box.

**Comment by twizzayy** [comment]
This worked. :) Thanks so much for your help.

To make the process faster, I installed the entire repo.json by downgrading the desktop app to [v3.8.0](https://github.com/standardnotes/desktop/releases?page=5) to install the repo and then upgraded the app to the latest version instead of copying them all one at a time.

Also, despite every other extension working, the "folders" extension still seems to only work in older versions.

Out of curiosity, why was the repo concept ditched? It seems more UX friendly...

**Comment by atmoio** [comment]
Glad it worked! See here regarding folders and the general extensions architecture direction: https://blog.standardnotes.com/33143/folders-from-extension-to-native

**Comment by twizzayy** [comment]
Dang. In the future, with the implementation of these features being native, will it still be possible to self-host external plugin-like features?

(I think of SN Extensions the same way I think about WordPress Plugins)

**Comment by atmoio** [comment]
Yes, editors and themes will likely always remain a plug-in architecture.

**Comment by twizzayy** [comment]
https://docs.standardnotes.com/self-hosting/subscriptions/
