### ISSUE TITLE
3rd-party Editors glitching on iOS (not loading content at all, or loading only randomly)

### ISSUE THREAD

**Issue by stripedgoat** [standardnotes/forum#1551]
**Describe the bug**
When I set a note to use a 3rd-party editor, they don't work correctly. Depending on which one I try, it either doesn't display my note content at all, displays it only with using the built-in themes, or displays it randomly,like 2-3 times out of 10 ([see video presentation here](https://i.imgur.com/AVHaIoX.mp4) <- In this example, using the built-in "Dark" theme.

**To Reproduce**
1. Install a 3rd-party Editor. In the example I'm trying Milkdown Editor (https://sn-extensions.melty.land/milkdown/ext.json).
2.Create a new note, pick the 3rd-party editor. Create some content.
3.Close the note. Quit the app entirely from the app drawer.
4.Open the app, then try to open the previously created note. The bug appears. Depending on which 3rd-party editor is being used, it either doesn't display any content at all (no matter how many times I try to open it), or displays content only on random occasions (as shown in the video linked above).

**Expected behavior**
Load the 3rd-party editor correctly, and display the note content every time I open it.

**Screenshots**
[Video showcasing the issue](https://i.imgur.com/AVHaIoX.mp4), in this example with Milkdown Editor.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.4
 - Browser: Not using the web app
 - Version: 3.12.0 (114)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS
 - Browser: Not using the web app.
 - Version: 15.3.1

**Additional context**
- Tried re-installing the app on my iPhone, including the Desktop app. It didn't change anything.
- Tried creating a new account. Didn't help either.
- The desktop client works as intended, and everything loads fine, with the same exact extensions.

**Comment by stefan-yas** [comment]
Thanks for the report, @stripedgoat, but it would be better to let the 3rd-party editor's developer know about the issue as maintaining the 3rd-party extensions to be up-to-date with current version of Standard Notes is up to the extension maintainer.

**Comment by stripedgoat** [comment]
Thanks for your response, @stefan-yas !

The issue occurs with any 3rd-party editor. It doesn’t matter which one I try to use (while other users have no issues with the same ones).

I just emailed you from w*****id@protonmail.com.
