### ISSUE TITLE
Reinstalling FileSafe -  where is it?!

### ISSUE THREAD

**Issue by seumas** [standardnotes/forum#1552]
I've been using StandardNotes for several years. Today, I started running in to a couple problems. The first was that I couldn't change the width of the left-most pane (making it impossible to read the nested tags tree).  The second is that I'd  get an error message when I attempted to upload a file to Google via FileSafe. Since the  debug error messages in the console didn't seem to indicate much, I  planned on just  removing the extension and re-installing it.

So, I went to Advanced Settings and clicked "Uninstall". Then, I went back to click the install button and... I have no idea where the hell o ne installs FIleSafe from. I don't see it in the Advanced Settings list. I don't see it  on the website... And of course, I'm hoping t hat once I find it I won't have lost connection to my  Google-hosted FileSafe files and it'll be smart enough reconnect everything after I activate the extension, again.

Regards.

**Comment by stefan-yas** [comment]
Because we're in the process of making the switch to native Files and deprecating FileSafe as an extension, you wouldn't be able to install the extension again. FileSafe as an extension was one of the overlooked and most unmaintained aspects of the app, with occasional errors when trying to upload or download a file to different services. Because of the work on native Files, FileSafe as of recently is deprecated.

**Comment by atmoio** [comment]
> So, I went to Advanced Settings and clicked "Uninstall".

Ah, that's one step too far I'm afraid. During our [deprecation of FileSafe](https://blog.standardnotes.com/32429/deprecation-notice-filesafe), we let people keep it if they already have it, but removed it from our list of services that were auto-installed.

However, what I think we'll need to do is offer a manual way for people like you to install FileSafe from a custom URL. We'll try to have that ready soon.

And yes, it should just keep everything connected as it was. Although, if you had difficulty with uploading, that wouldn't change. It might be that your Google token has been revoked or expired.

**Comment by atmoio** [comment]
Ok, you can install FileSafe manually by following these steps:

1. Open Preferences > General > Advanced Settings
2. Scroll to the bottom, then copy and paste this link into the install box: https://extensions.standardnotes.org/repos/legacy/filesafe
4. Proceed through installation steps.

**Comment by seumas** [comment]
Appreciate the responses. I was not aware of this change. I've installed the extension,  retrieved the files, and removed the extension and will look forward to SN's implementation  in the future.  My current sub doesn't expire until after 2030 and I'm looking forward to seeing  the product grow while sticking to core values. Thanks  again!

**Comment by udaykapur** [comment]
The solution recommended here is not working - is this not a valid solution anymore.

![Screenshot from 2023-09-28 13-35-52](https://github.com/standardnotes/forum/assets/15121710/6bdad894-ab71-443a-9c53-af8a31dbf989)

Filesafe stopped working for me and I thought uninstalling and reinstalling might help.

**Comment by atmoio** [comment]
The new FileSafe install link is: 
https://standardnotes.github.io/plugins/cdn/dist/entries/org.standardnotes.legacy.file-safe.json

Delete any previous FileSafe installations from Preferences > General > Advanced

Source: https://github.com/standardnotes/plugins

The plugin can then be activated from the quick settings menu:

<img width="323" alt="filesafe" src="https://github.com/standardnotes/forum/assets/3277844/8762a192-0c28-458e-9ec4-827699492d5a">
