### ISSUE TITLE
Resizing columns changes theme back to default (macOS)

### ISSUE THREAD

**Issue by eisolo** [standardnotes/forum#1556]
**Describe the bug**
Clicking (with or without dragging) the column resize bar will change theme back to default once un-clicked.

**To Reproduce**
1. open app
2. set theme to one that is not default theme
3. click column resize bar (either the one between menu/notes or notes/note content)

**Expected behavior**
Once the column resize bar is unclicked the theme will change back to default.

**Screenshots**
Video attached and here: https://imgur.com/kaSErxM

**Desktop (please complete the following information):**
 - macOS High Sierra 10.13.6
 - SN version 3.12.1
 - tried with themes Midnight, Futura, Solarized Dark
 - subscription: Standard Notes Core

https://user-images.githubusercontent.com/70426159/157368623-5d8e56eb-535e-46d8-ae75-6e10d68e167d.mov

**Comment by myreli** [comment]
It seems like this no longer happen with the latest version. I'll closet it, but please feel free to re-open in case you still experience any issues.
