### ISSUE TITLE
Unable to Enter Offline Activation Code

### ISSUE THREAD

**Issue by julianrmartinez** [standardnotes/forum#1559]
### Bug Summary
Cannot activate Standard Notes subscription using Offline Activation Code. The instructions in my email inform me to add the Offline Activation Code in Advanced Settings: however, the Advanced Settings section does not have a field for me to enter my code. 

### Proof 
![Screen Shot 2022-03-14 at 10 55 47 AM](https://user-images.githubusercontent.com/41017290/158232382-0f1ded14-e6fd-4b62-bbbe-0b826b5bb865.png)

### Compatibility Info
Using Standard Notes 3.13.0 on MacOS Monterey 12.1

### Request
Can you add this field to the Advanced Settings section so I can activate my offline account?

**Comment by atmoio** [comment]
Hmm I see this:

<img width="527" alt="Screen Shot 2022-03-14 at 1 51 55 PM" src="https://user-images.githubusercontent.com/3277844/158241009-a826f893-0abe-4b04-83bc-c767878031c9.png">

Do you perhaps already have a regular subscription associated with your account?

**Comment by julianrmartinez** [comment]
I do not have a regular subscription. I do not have access to Rich Text or any other features. 

> Hmm I see this:
> 
> <img alt="Screen Shot 2022-03-14 at 1 51 55 PM" width="527" src="https://user-images.githubusercontent.com/3277844/158241009-a826f893-0abe-4b04-83bc-c767878031c9.png">
> 
> Do you perhaps already have a regular subscription associated with your account?

**Comment by atmoio** [comment]
So offline subscriptions and online subscriptions can't be used together in the same session, otherwise it would cause conflicts. Is your online subscription still active? You'd have to cancel that first. If you can't get it sorted please reach out to help@standardnotes.com with your account email so we can take a look.
