### ISSUE TITLE
[Help Wanted] Unable to perform offline decryption of daily backup 

### ISSUE THREAD

**Issue by cyb3rz3us** [standardnotes/forum#1560]
**Describe the issue**
Cannot perform offline decryption of data using the latest decryption script and known account password.

**To Reproduce**
1. Download latest offline decryption script.
2. Open the script in Google Chrome v99.0.4844.51 or later.
3. Select the backup file to decrypt.
4. Enter the account password in place at the time the backup file was generated.
5. Click either "Download..." button (it does not matter which).
7. The script responds with "An error occurred while trying to decrypt your data. Ensure your password is correct and try again."

**Expected behavior**
The encrypted backup file would be decrypted and the content presented as directed.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 High Sierra
 - Browser: Chrome v99.0.4844.51

**Additional context**
The password being used for decryption is confirmed as correct based on the "Current password was set" information shown in my account preferences.

Also, a newer encrypted file was able to be decrypted properly so it appears that the backup process used the wrong password during encryption.

**Comment by atmoio** [comment]
Can you confirm the full name and ext of the backup file you're attaching? Sometimes people upload the zip file, when in fact you should be opening that up and attaching the embedded txt file.

**Comment by cyb3rz3us** [comment]
These are all TXT files taken directly from the daily backup emails I receive.  Also, as mentioned, the exact same process did work for a much later file but files within at least 30d of the password change date do not work.  That date range may be longer but I decided to stop at 30d.

I have attached some screenshots below:

### Script date

![stdNotes_decrypt-issue_script-date_220315](https://user-images.githubusercontent.com/26828291/158687092-f8e570d2-0205-4ff8-85f9-100fcfc0c242.jpeg)

### Last password date

![stdNotes_decrypt-issue_lastAcctPw_220315](https://user-images.githubusercontent.com/26828291/158687117-71a2a6e1-18dd-425d-83c0-92971c64398c.jpeg)

### Error message & filename

![stdNotes_decrypt-issue_errMsg_buFile-210720](https://user-images.githubusercontent.com/26828291/158687126-d58d91f0-8457-49d6-b48a-a524a14f1c9d.jpeg)

**Comment by atmoio** [comment]
So you're entering your account password as it was before it was changed, right, and not your most recent password?

**Comment by cyb3rz3us** [comment]
No - please re-check the password and backup file dates.  The password was implemented on Jun 19, 2021.  The backup file is dated Jul 20, 2021 - i.e. 30 days later.  Should the current password not be used for all backups **after** Jun 19, 2021?

**Comment by atmoio** [comment]
You have it correct then. Are you able to DM me the backup file auth_params value at the bottom? Then I can compare this to the server value and make sure they match up.

**Comment by cyb3rz3us** [comment]
Well let me ask, will that really help?  I ask because I'm confident the server values are correct because I can decrypt some newer files.  For example, I just decrypted the BU dated Mar 7, 2022.  I don't know where the cutoff is between good\bad but I will start testing other files and will let you now if I can find where it starts working...

**Comment by atmoio** [comment]
What about comparing the auth_params from the files that don't work and the files that do work—are they the same?

**Comment by cyb3rz3us** [comment]
auth_parms - need a little more here...do you mean the password?

**Comment by atmoio** [comment]
If you open the txt file and scroll to the bottom you should see a JSON portion called "auth_params". You want to compare the contained data values of identifier, pw_nonce, and version, and make sure they match up between files.

**Comment by cyb3rz3us** [comment]
Thx - they are indeed the same.  I also went and checked Jun 19 & 20 - the nonce changes between those dates which makes sense given the password change.  All files after Jun 19th that I have checked (about 5 so far) all have the same nonce - so that's good.

This is bizarre so I will continue with my file-by-file decrypt testing...might cough up a decent clue...

**Comment by cyb3rz3us** [comment]
OK - it looks like the line is between Jan 13 & 14 2022.  The 13th fails but the 14th decrypts.  The auth_params are the same for both files...

**Comment by atmoio** [comment]
Hmm, strange. Can you do a diff on the two files and see where they differ? It could be one item in there somehow tripping up the whole process. If you open the dev console in your browser while decrypting that would be helpful to capture to see if there are any exceptions reported.

**Comment by atmoio** [comment]
Also, can you try decrypting the file by importing into a non-signed in session using the web or desktop app? Could be some unexpected differing functionality between the backup script and the apps.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)
