### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by red-ochre** [standardnotes/forum#1563]
On a Mac running Monterey with SN 3.13.0 
Wondering why there are two passwords: account and application? Isn't one enough?

**Comment by atmoio** [comment]
Please see here: https://standardnotes.com/help/79/how-does-standard-notes-encrypt-data-on-my-device

Essentially: account passwords are for cloud encryption. Application passcodes are for local device encryption.

**Comment by red-ochre** [comment]
@moughxyz Thanks. That explains it.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)
