### ISSUE TITLE
Does Standarnotes "calls home" when in offline mode? [Help Wanted]

### ISSUE THREAD

**Issue by stebansaa** [standardnotes/forum#1564]
Just trying to understand what kind of information standarnotes sends home.... I have kept mine always "offline", does it send any information?

**Comment by atmoio** [comment]
What you can do is open the web app in incognito mode in your browser, open dev tools, then Network. You can then see what requests it makes.

On a new session I see 0 network requests. When I open Preferences I see 1 public, non-user specific request to get available subscriptions.

The desktop app might differ only with regards to two requests I can think of:

- One to download the dictionary file from our server.
- And the other to check if a new update is available. For this the desktop pings our GitHub desktop repo, as well as our server for more information about the latest version.

But to answer your specific question about "does it send any information?", the answer is no, in this context. These are GET requests with no specific user information attached to them.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)
