### ISSUE TITLE
How to sort in Windows App?

### ISSUE THREAD

**Issue by cparish17** [standardnotes/forum#1565]
Android app has several sort options, by title, by date, etc. I can' find how to sort my notes in the Windows app.

**Comment by atmoio** [comment]
Select "Options" in the notes panel:

<img width="410" alt="Screen Shot 2022-03-25 at 4 35 08 PM" src="https://user-images.githubusercontent.com/3277844/160204085-dfc416f9-71c2-4356-a334-e83245fac45e.png">

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)
