### ISSUE TITLE
Extensions on Android app

### ISSUE THREAD

**Issue by scra5071** [standardnotes/forum#1566]
Hi, I have a Pro plan subscription. Whenever I try to use any editor other than the Plain Text Editor on the Android app I get the following message:

This extension is not installed correctly. Please use the web or des...
Reinstall extension

How do I reinstall the extension to get it working on Android?

Thanks

**Comment by stefan-yas** [comment]
Perhaps try reinstalling the app? Feel free to [sideload from here](https://github.com/standardnotes/mobile/releases) to get the latest version.

**Comment by atmoio** [comment]
This may be an account related issue, in which case please reach out to help@standardnotes.com with your account email.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
