### ISSUE TITLE
Unable to scroll down on iPad - Safari

### ISSUE THREAD

**Issue by alexgutts** [standardnotes/forum#1568]
**Describe the bug**
Not able to scroll down on the tags and select the tag (folder) that I need on my safari browser on ipad. (before the update on the folders it was working)

**To Reproduce**
1. Open standard notes on safari on (iPad mini 6th)
2. Once logged in, try to scroll down to select one folder
3. not able to scroll down on folder section

**Expected behavior**
Being able to scroll down on folders section to select one folder

**Smartphone (please complete the following information):**
 - Device: iPad mini 6 
 - OS: iOS 15.4
 - Browser: Safari
 - Version: not sure, the one coming with iOS 15.4

**Additional context**
Before the upgrade on folders, it was working fine, also I was able to create folders on mobile, for that reasons, I liked more the other version of folders.

**Comment by stefan-yas** [comment]
I'd recommend using the [mobile app](https://apps.apple.com/us/app/standard-notes/id1285392450) on mobile devices. Is there any particular reason you're using the web version and not the iOS app?

**Comment by alexgutts** [comment]
Yes, I'm using on safari because is super important for mi to download my attached files, that is something the iOS app doesn't allow me to do.

**Comment by stefan-yas** [comment]
Good news in that case - attaching, modifying and downloading files to SN is a feature that is [currently in development](https://standardnotes.com/help/36/how-do-i-attach-encrypted-files-to-my-notes) and will be released in some time.
