### ISSUE TITLE
If Ubuntu is not creating a favorite in launcher, or the .desktop file is not working..

### ISSUE THREAD

**Issue by mobitar** [standardnotes/forum#157]
A user [reported](https://twitter.com/danarel/status/960031796623687680) experiencing this issue on Ubuntu 17.10, and this was the solution he found:

I deleted the original .desktop app that it created, installed it in my home/.local/bin and then launched it, but it didnt ask me to create a new .desktop. So I copied the code from the old one, made a new one with the updated location and it worked.

**Comment by danarel** [comment]
After some testing, I believe the problem was because the original location was in a folder called "Standard Notes" and I think the spacing in the name of the folder caused the issue. Once I moved it into a folder with no spaces, updated the .desktop file it worked right away.
