### ISSUE TITLE
Note sidebar won't close on Android when pressing back button

### ISSUE THREAD

**Issue by ericswpark** [standardnotes/forum#1570]
**Describe the bug**
Pressing the back button to close the notes sidebar will exit the note itself and return me to the list, while still keeping the sidebar open.

**To Reproduce**
1. Edit a note
2. Open the sidebar, either by using the hamburger icon on the top right or by sliding it out from the right
3. Use the back button on Android

**Expected behavior**
The sidebar should close instead with the first back tap, then the second back tap should close the note.

**Screenshots**
https://user-images.githubusercontent.com/13326074/160811787-27a23fbd-4975-4cad-8752-ca423ab58a1f.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 20 Ultra
 - OS: Android 12
 - Version 3.14.0

**Additional context**
Untested on iOS, but probably not applicable since iOS does not have the back button.

**Comment by myreli** [comment]
With the recent versions of the mobile app and the improved navigation gestures, this seems to have been solved. In case you find any problems, feel free to re-open the issue. Thanks!
