### ISSUE TITLE
Setting "Add all parent tags when adding a nested tag to a note" has no effect

### ISSUE THREAD

**Issue by maiertech** [standardnotes/forum#1571]
**Describe the bug**
The new setting **Add all parent tags when adding a nested tag to a note** has no effect. When turned off, it should omit creating all parent tags for new notes in nested folders. But it creates them anyway.

**To Reproduce**
1. Turn this setting off.
2. Create a new note in a nested folder.
3. Parent tags are created.

**Expected behavior**
Parent tags should not be created.

**Screenshots**

**Desktop (please complete the following information):**
Desktop client v3.14.1 on macOS 12.3.

**Additional context**
This worked in 3.14.0 (where this feature was rolled out).

**Comment by atmoio** [comment]
Right now there is a known issue that this setting doesn't apply when creating a new note from within a subfolder. It only takes effect when using the autocomplete tagging feature.

We plan to have this fixed with the next release.
