### ISSUE TITLE
[Help Wanted] Error creating account

### ISSUE THREAD

**Issue by quannghoang** [standardnotes/forum#1572]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/97494537/161221044-1b6c638b-ffb8-4106-a0f7-46993539cc16.png">

When I create an account in : ' Create Account Free ', the error message  ' Cannot read properties of undefined ( reading 'digest' ) ' appears  (information in attached image).
What step did I do wrong ?
Please help me, thank you very much !

**Comment by atmoio** [comment]
WebCrypto is used as part of key generation and this is not available in insecure contexts. So you will need to put the web app behind an HTTPS certificate, or use `localhost` if using on same device.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
