### ISSUE TITLE
Insufficient contrast for selected text in Markdown Pro in dark mode

### ISSUE THREAD

**Issue by maiertech** [standardnotes/forum#1575]
**Describe the bug**

When running the macOS desktop app in dark mode using the Markdown Pro editor, selected text has insufficient contrast.

**To Reproduce**

When in dark mode, open up a note with Markdown Pro and select some text.

**Expected behavior**

The highlight color and text should have sufficient contrast.

**Screenshots**

![selected-text](https://user-images.githubusercontent.com/1482402/161409583-55e41b0b-a98c-454c-968d-39b2596a0bad.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Version: 3.14.1

**Comment by stefan-yas** [comment]
Thanks, @maiertech - we'll have a go at improving contrast when selecting text on different themes with this editor.

**Comment by maiertech** [comment]
Since you offer multiple Markdown editors, I am fully aware that maintaining all of them is a lot of work. Meanwhile I am trying out Markdown Visual and I like it a lot. For me it's ok to close this issue. And in general reduce the number of supported Markdown editors.
