### ISSUE TITLE
The raw of the spreadsheets

### ISSUE THREAD

**Issue by BertramZhangFb** [standardnotes/forum#1576]
Greetings, I am a new user of this software and the number of raw sheets is not enough when a datasheet with 1500 raws needs to import Standard notes. It would be better if the spreadsheets could support more raw sheets. Thanks!

**Comment by stefan-yas** [comment]
Hey @BertramZhangFb, good to have you as a user of Standard Notes - hope you enjoy using it as much as we do making it :)

You can add additional rows by clicking on **Insert -> Add row below** button inside of Secure Spreadsheets menu.

![image](https://user-images.githubusercontent.com/52251483/161480214-ca5bb0fe-4934-4a1e-8c5e-5cd84e31adbf.png)

**Comment by BertramZhangFb** [comment]
OK, thank you very much!

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
