### ISSUE TITLE
Error "Standard Notes keeps stopping"

### ISSUE THREAD

**Issue by closetsuperhero** [standardnotes/forum#1579]
Standard Notes no longer opens after installing the update. F-droid won't let me downgraded either, "Error -25: The new package has an older version code than the currently installed package."
When I tried to install the apk from the website, it says "App not installed as package appears to be invalid."

Pixel 4a
CalyxOS 3.3.0
Android 12

**Comment by steaksweremade** [comment]
Same issue here. Crashes on startup.

Pixel 5
GrapheneOS (latest version as of today)
Android 12

**Comment by Yannig123** [comment]
Same issue on:
OnePlus 6
LineageOS
Android 12

**Comment by muffin-p** [comment]
Same issue on calyxos on pixel 5 with fdroid. I had to uninstall it and then downgrade to previous version.

**Comment by atmoio** [comment]
Please download 3.14.1 from our website until Fdroid updates their version. You have to first uninstall the Fdroid version to be able to do this.
