### ISSUE TITLE
Another Error "Standard Notes keeps stopping" 

### ISSUE THREAD

**Issue by steaksweremade** [standardnotes/forum#1580]
**Describe the bug**
Standard notes crashes about a second after I press it. If i do it enough times, it will say "standard notes keeps stopping"

**To Reproduce**
1. Open Standard Notes

**Smartphone (please complete the following information):**
 - Pixel 5
 - GrapheneOS (latest version as of this post)
 - Android 12

**Additional context**
I tried downgrading the version but it said "failed to install due to an unknown error."

**Comment by atmoio** [comment]
Please see https://github.com/standardnotes/mobile/issues/582 and https://github.com/standardnotes/forum/issues/1579
