### ISSUE TITLE
Cannot resize window on Windows 10 Desktop

### ISSUE THREAD

**Issue by bigjtu** [standardnotes/forum#1582]
With the most recent update 3.14.1 the resizing of the window by grabbing if from the sizes or the top has regressed. Now, when I try to grab the edge, the mouse arrow changes to the resizing arrows, put pulling it around does nothing for the Standard Notes window. Sometimes (maybe 20% of the time) it still works. 

If I toggle OFF the themed menu bar, it works perfectly every time. If I toggle ON the themed menu bar, it again does not work. Restarting, changing themes, changing margin setting option, nothing helps.

Windows 10 version: 64-bit, 10.0.19044 Build 19044

**Comment by stefan-yas** [comment]
> If I toggle OFF the themed menu bar, it works perfectly every time. If I toggle ON the themed menu bar, it again does not work. Restarting, changing themes, changing margin setting option, nothing helps.

What do you mean by the "themed menu bar"?

**Comment by bigjtu** [comment]
At least in the Windows 10 desktop version you can choose if the top bar is "themed" or the Windows default, here:

![image](https://user-images.githubusercontent.com/64022132/162688056-b88a59a7-e116-4b54-b28f-b397c6170658.png)

**Comment by stefan-yas** [comment]
Ah okay, thanks for clarifying - have raised this issue with the team.

**Comment by bigjtu** [comment]
I confirm that this is not issue anymore, i.e. somewhere along the way it has been fixed. So closing the issue.
