### ISSUE TITLE
Notes Background Flashes White When Loading 

### ISSUE THREAD

**Issue by tezoot** [standardnotes/forum#1583]
New user / subscriber here. I am using version 3.14.1 on Linux with Midnight theme. When I navigate between notes the note flashes white (white background) before displaying correctly in the Midnight theme. I have installed latest version on Windows partition and this happens as well. Note that it happens regardless of the type of editor used to create the original note. I hadn't noticed this before - was wondering if possibly related to a couple of custom editors which I installed and subsequently uninstalled? Web UI works just fine. 

Any thoughts / advice would be much appreciated as it's driving me crackers and detracts from what is a great product.

**Comment by atmoio** [comment]
This might happen when switching from one speciality editor to another. It wouldn't happen from plain text to plain text for example. Can you notice which from and to editors this happens with?

**Comment by tezoot** [comment]
Hi, yes this is indeed the case. Plain text is fine but the Rich Text editors cause the problem. I tend not to use Markdown.
