### ISSUE TITLE
Cannot log in, "SetKeychainValue" error (Linux AppImage, Fedora 35 KDE)

### ISSUE THREAD

**Issue by gwerbin** [standardnotes/forum#1585]
**Describe the bug**

I get the following error (which is not user-selectable text...) when I try to sign in on the desktop app:

```
Error invoking remote method 'SetKeychainValue':
Error: No such object path
'/org/freedesktop/secrets/aliases/default'
```

I am not sure if this is a D-Bus path, or something else. Am I missing a system-level dependency?

Then if I close the sign-in box and re-open it, I get a different error:

```
Tried to sign in when an account already exists.
```

It looks like the first error left the local settings in some kind of intermediate state.

Then if I close and reopen the app, I get an "Authentication Required" / "Restore Keychain" panel that I cannot bypass:

> We've detected that your keychain has been wiped. This can happen when restoring your device from a backup. Please enter your account password to restore your account keys.

I type my password and it says "generating keys", but it never finishes the task. The app remains permanently stuck in this state, no matter how many times I restart, until I delete the directory `$XDG_CONFIG_HOME/Standard Notes`.

**To Reproduce**

Download and run the AppImage on Fedora 35 KDE. Try to sign in; it will fail with the first error. Then close the sign in window and try again, to see the 2nd error. Then close and reopen the app to get the "authentication required" prompt.

**Expected behavior**

Successful sign-in.

**Screenshots**

First error: https://files.catbox.moe/agg9yr.png

Second error: https://files.catbox.moe/sqol5d.png

"Authentication required" prompt: https://files.catbox.moe/kviaam.png

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Browser: N/A
 - Version: 3.14.1 AppImage

**Comment by adrihut** [comment]
Will try to replicate this on my end and get back to you with my results, @gwerbin.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Comment by gwerbin** [comment]
I never got this to work and have since stopped using Standard Notes.
