### ISSUE TITLE
Webpage elements are "stacked" and and unclickable (iOS Firefox)

### ISSUE THREAD

**Issue by gwerbin** [standardnotes/forum#1586]
**Describe the bug**

On standardnotes.com, elements are stacked on top of each other, and the links inside are unreadable & unclickable.

**To Reproduce**

Visit <https://standardnotes.com/help>.

**Expected behavior**

Not this!

**Screenshots**

![Screenshot showing links stacked on top of each other](https://user-images.githubusercontent.com/5758789/163668410-fbbbe2bd-4838-4545-8a84-e6d1ee0d1544.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE Gen 2
 - OS: iOS 14.2
 - Browser: Firefox Daylight 98.2 (8475)
 - Version: Firefox Daylight 98.2 (8475)

**Comment by stefan-yas** [comment]
Hm weird. I can't reproduce this on my end.

**Comment by gwerbin** [comment]
@stefan-yas I forgot to list what phone I was using, and what version of iOS. I am using an SE Gen 2 under iOS 14.2, if that helps. Maybe it works on bigger or newer devices.

**Comment by adrihut** [comment]
I don't think it has to do with screen size, per se. I was able to replicate the behavior depending—_seemingly_—on iOS version:

> ### Identical issue <sup>(on both landscape and portrait orientation)</sup>
> - iOS 13.2.3
> - iPhone 8 Plus

> ### Rendering correctly
> - iOS 14.8.1
> - iPhone SE (Gen 1)

<br>

Is it possible for you to update your iOS version @gwerbin?
