### ISSUE TITLE
Replace Snap with Flatpak now that Electron supports it

### ISSUE THREAD

**Issue by SpaceRaccoonFluff** [standardnotes/forum#1587]
Basically seeking an update to https://github.com/standardnotes/desktop/issues/172#issuecomment-820655496 

None of us linux users like snap when flatpak respects users far better. An opensource private note taking app shouldn't be supporting a closed source back-end snap either.  

From what I'm seeing electron now makes it just as easy to publish a flatpak as they do with snaps https://github.com/electron-userland/electron-builder/pull/5711 and i'm wondering if there's been any updates or plans to make the switch since then? All the linux users would love to use flatpak over snaps. I personally wouldn't even mind seeing support for app images go away if that means you guys can just focus on only supporting flatpaks. Maintaining both app images and snaps are redundant but many wouldn't give up app images if snaps are the only alternative.

**Comment by adrihut** [comment]
Currently looking into this, @SpaceRaccoonFluff. Will post updates here as soon as they become available.

**Comment by stkr22** [comment]
Any chance this is supported officially soon? There is a flatpak(https://github.com/flathub/org.standardnotes.standardnotes) but it is not official and I would rather use an supported one (even if that one looks ok).

**Comment by effieeee** [comment]
No plans on this just yet 😞 Though yes, I haven't yet heard much complaints about the 3rd party flatpak that was made
