### ISSUE TITLE
Unable to use Plus Editor on Mobile (Android)

### ISSUE THREAD

**Issue by epsilonvirga** [standardnotes/forum#1588]
I'm unable to use the Plus Editor on mobile. I'm shown a blank, plain white editor when I do so.

Also, it appears that opening up a Plus Editor note on the Android app actually deletes the previous edits...? Not good... they at least show up in the history, but they're still immediately inaccessible.

On creating a note that uses the Plus Editor on mobile, it appears functional and is able to be edited - however, on closing and re-launching the app, the issue occurs. I am then only able to view and edit notes using the Plus Editor on desktop or in the browser, which is not preferable.

I do not see the read-only prompt that indicates I don't have access to the plus editor.

Please see screenshots below.

![Screenshot_20220420-121900](https://user-images.githubusercontent.com/104045849/164134301-a9ac175b-f6a7-45ff-8f7c-89291973fa12.png)

![Screenshot_20220420-122126](https://user-images.githubusercontent.com/104045849/164134319-7b1f6392-d11b-4acc-9585-815f8757d6e5.png)

![Screenshot_20220420-122043](https://user-images.githubusercontent.com/104045849/164134339-f5c16e8c-79ae-466b-b3c7-a7ab96876615.png)

![Screenshot_20220420-122247](https://user-images.githubusercontent.com/104045849/164134357-559452cd-0adc-40ad-996e-dde4b646e09d.png)

Device: Pixel 6
 - OS: CalyxOS 3.4.0 - Android 12 (Occurred in the past two Calyx versions also)
 - Standardnotes App version 3.12.0 (3000334)

Wanted to note a similar issue also occurred on my previous phone, an iPhone 6s Plus where the Standardnotes Plus editor would crash the entire application. However, I'd presumed it was perhaps due to the older hardware being unable to handle the full features of the app. If this is potentially related to my account, let me know - it doesn't happen in the browser webapp, however.

Any suggestions? Is this a bug? Have I missed something?

Thanks guys.

**Comment by epsilonvirga** [comment]
Hey, sorry, have another addition here. Looks like the Markdown editors and Task editors don't work either. (I mainly wanted to use the Plus editor...)

I basically only have free functionality here, then... ouch...?

![Screenshot_20220420-123028](https://user-images.githubusercontent.com/104045849/164135407-93f29cd4-f000-4c7d-a82d-ee05fc5197f5.png)

![Screenshot_20220420-123053](https://user-images.githubusercontent.com/104045849/164135418-b611c826-275c-4cd1-a1f2-ad9a9f8478e9.png)

![Screenshot_20220420-123119](https://user-images.githubusercontent.com/104045849/164135436-f1a5a0c6-a466-4ea1-b1a6-7cd29480bb91.png)

![Screenshot_20220420-123208](https://user-images.githubusercontent.com/104045849/164135445-52e3f5cd-1602-475e-9e40-2aeb68ac24cc.png)

Please let me know if you need further detail.

**Comment by atmoio** [comment]
It seems like the editors are not correctly loading, judging by the fact that they are not receiving your dark theme. Although, this dark theme is not ours; are you installing the editors from third party sources as well?

Also, when you make edits into the editors, does the "Saving..." status change in the title bar? If that status doesn't change as you type, it means the editor did not properly establish a connection the application. This would explain why it does not load the note correctly initially and displays blank values (the note contents are still there, just unable to be loaded by the editor).

**Comment by epsilonvirga** [comment]
Hey! Thanks! I have given your suggestions a go. The issue seems intermittent. It originally persisted with default themes (tested with solarised dark). The editor remained white (so not loading altogether, then?). However, after a restart in solarised dark, the editors work again. I'm going to see if they drop off again after daily use in a default theme.

The status indicator said it was definitely saving. These are the stock editors - Plus Editor, Task Editor and Markdown Pro editors that were not functioning, so that was ruled out.

Though I tried reinstalling several weeks back from the Play Store and had the same issue persist, then procrastinated a bit about reporting the bug in case it went away, I today have reinstalled directly with the apk from the standardnotes website - this actually seemed to resolve the problem for a bit with the third party theme. Then it stopped working again.

I'll stick to the stock themes and report back about whether it still drops off and whether it could be an issue with the theme?

**Comment by myreli** [comment]
Since this report, the [new mobile experience launched](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon), and it seems like this is no longer an issue. I'll close for now, but you can start a new discussion if necessary. Thanks!
