### ISSUE TITLE
Feature Request: Solarized Light

### ISSUE THREAD

**Issue by M-Pixel** [standardnotes/forum#159]
I find that I like Solarized _Dark_ for code, Solarized _Light_ for documents and notes. I see there's already a Solarized Dark theme; it would be great if there were a Solarized Light one, too.

**Comment by mobitar** [comment]
Would be nice! Haven't gotten around to it yet.

**Comment by mobitar** [comment]
Also anyone feel free to fork the solarized dark theme and make some magic happen :) https://github.com/sn-extensions/solarized-dark-theme

**Comment by skulkingfox** [comment]
I did just that today. 

If you want to install it use: https://listed.standardnotes.org/lYxsNwG7Xi
If you want the code: https://github.com/skulkingfox/solarized-light-theme

**Comment by mobitar** [comment]
Wow, looks great!

**Comment by itsfeng** [comment]
Any plans on integrating the code of @skulkingfox ?

**Comment by mobitar** [comment]
I'd probably have my own take on a solarized light. The above needs a lot of updating to work well with recent versions of the app.
