### ISSUE TITLE
Note text not showing up in the web/desktop versions

### ISSUE THREAD

**Issue by SARankDirector-Minecraft** [standardnotes/forum#1591]
**Describe the bug**
When I try to use standard notes I don't see anything under the text of the notes.

**To Reproduce**
1. Start up standard notes
2. Click on a note
3. See error

**Expected behavior**
See the text of the notes

**Screenshots**
![Standard notes help image](https://user-images.githubusercontent.com/16199488/165135254-1c407dad-9891-401f-a907-45ea2cc72573.png)
(ignore the grey boxes they're just there to preserve my privacy 

**Desktop (please complete the following information):**
 - OS: Manjaro KDE
 - Browser: Chrome/Chromium/Electron
 - Version 3.14.1-1, 3.14.1-2

**Comment by atmoio** [comment]
Try restarting the app. There is a rare issue right now that non-plain editors sometimes fail to load. Will hopefully be addressed in the next release. You can also try changing to the Plain Editor to verify this.

**Comment by SARankDirector-Minecraft** [comment]
It always happens, no matter how man times I restart

**Comment by SARankDirector-Minecraft** [comment]
nvm, i fixed it, i had somehow pushed the editor beyond the bounds of the app. This probably shouldn't be possible however.
