### ISSUE TITLE
Issue with "Pure Black" Theme

### ISSUE THREAD

**Issue by LalOpen** [standardnotes/forum#1593]
Good day.
I'm facing an issue with the "Pure Black" Theme. I'll attached two screenshots so that you'll be able to directly see what it is about.

When Pure Black theme is active, we cannot see the title and the description of the selected note, because the selection displays as a white line that obstructs with the white letters...

LalOpen...
![White](https://user-images.githubusercontent.com/92826217/166102862-5cb3113d-f94c-4f86-994e-1035b5aa5c1c.png)
![Black](https://user-images.githubusercontent.com/92826217/166102856-c6b4b9f2-287c-4ddd-8045-2d84bce2059a.png)

**Comment by effieeee** [comment]
Appears fixed for the notes list using this theme
