### ISSUE TITLE
Alternative account login: e.g usernames

### ISSUE THREAD

**Issue by damygdala** [standardnotes/forum#1595]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

Yes

**Is your feature request related to a problem? Please describe.**

Using a static email address to log in/having this email address displayed within the settings menu, can feel counter-intuative to the promotion of privacy.

**Describe the solution you'd like**

The option to login/create an account with usernames (which can, for instance, be randomly generated by the account holder) or account numbers generated on creation of an account (Mullvad comes to mind, whereby the account holder can change their account no. when buying credit).

**Describe alternatives you've considered**

Being able to associate an existing account with a username. 

**Additional context**

In order generate a receipt for payment when creating an account, the user could potentially use an alias/throwaway email. Although I can imagine that this would create additional problems relating to support/account queries etc.

**Comment by atmoio** [comment]
We're exploring something like [this](https://website-dev.standardnotes.com/help/80/what-are-vaults). Would that cover your use case?

**Comment by damygdala** [comment]
> We're exploring something like [this](https://website-dev.standardnotes.com/help/80/what-are-vaults). Would that cover your use case?

Hey, 

Thank you for your swift response. 

This is something I must have looked over in the notes! The description of vaults is everything I could have wanted. I think that I must have associated the term 'vault' with password protection or the deprecating file encryption. 

I also really appreciate the thought that has gone into the proposed use-cases:

_Personal health and sexual wellness data, photos, and videos. Documenting our body over the years is an important health strategy and function. In many cases, taking photos or videos of one's own body is a vital aspect of documenting our evolution and progress through a physical goal.

Religious, political, and ideological beliefs that may jeopardize your safety. Decoupling this information from your primary account, especially in cases of force by an interloper, allows you to retain your ideological dignity without fear of reprimand or retribution._

Super important/incredibly relevant to these changing times.

Thank you.
