### ISSUE TITLE
Unable to add new items using Simple Task Editor on Android

### ISSUE THREAD

**Issue by snakespan** [standardnotes/forum#1596]
**Describe the bug**
Unable to add new items using Simple Task Editor on Android. When I type in a new item into the task bar and click enter, it just moves the cursor down a line rather than adding a new item to my list.

**To Reproduce**
1. On Android, open a note using Simple Task Editor
2. Add a new Item
3. Observe item isn't added correctly.

**Expected behavior**
Expect a new item to be added to the list

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: OS 12
 - App
 - Version 3.14.1

**Comment by OttoUsualConsumer** [comment]
same for me, and the thing is, it doesnt matter if you install an earlier version. but if you make a completely new note with simple task editor, it works. for me its just in older notes.

Edit: okay, after you go out of the new note and in again, it also fails.

**Comment by atmoio** [comment]
The fix for this is in 3.20.0, which was just released 👍
