### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by SmartCollege** [standardnotes/forum#1599]
I just imported an Enex file converted with your tool. The import did not create a special tag like the plaintext tool. I need to see the files imported. Is there a way to search for all notes created today? In last 2 hours, etc?

**Comment by atmoio** [comment]
See here: https://standardnotes.com/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters

Yours might be: `!["Last 2 hours", "created_at", ">", "2.hours.ago"]`

**Comment by SmartCollege** [comment]
Thanks Mo, did I do something wrong in the import? should a tag have been created on an ENEX import? I'm a core plan user. should this syntax work in the search box?

**Comment by atmoio** [comment]
> should this syntax work in the search box?

That's a really interesting idea actually 🤔 Hadn't considered that before. It doesn't work like that presently. Instead you create a new tag and paste in that syntax.

> did I do something wrong in the import?

I'm not sure, we'll need to double check on this to make sure it's working as expected. IIRC it should create an "evernote" tag.

**Comment by SmartCollege** [comment]
Thx Mo, I missed the evernote tag--it is there. Unlike the plaintext import, there is no preceding date on the tag. For consistency, that might be useful.
