### ISSUE TITLE
I can't find Dropbox extension...?

### ISSUE THREAD

**Issue by cryptopana** [standardnotes/forum#160]
Hi guys.

I can't find the Dropbox extension now that I've installed version 2.1 on my desktop computer (PC, Windows 10).

I had it listed there, but I uninstalled it, but now it's not on the Extensions list (I wanna install it and configure it), and I can't find it on the website either?

**Comment by mobitar** [comment]
Sorry about that—you can find it under "CloudLink". Install and open that extension and you will see the various integration options.

**Comment by cryptopana** [comment]
Oh okay! Very nice, thank you. So maybe on the next update add something to the description of that section, so people can clearly see it's used to sync with Google Drive, Dropbox and so forth? It's probably a minor detail, but could be useful.

Thank you! I just purchased the yearly extended subscription. I'm in love with the program!

**Comment by mobitar** [comment]
Yup, just updated the description for CloudLink :)

"Manage and install cloud backups, including Note History, Dropbox, Google Drive, OneDrive, and Daily Email Backups."

> Thank you! I just purchased the yearly extended subscription. I'm in love with the program!

So glad to hear that!

**Comment by cryptopana** [comment]
Andd, I just saw the change. I LOVE THIS!
