### ISSUE TITLE
iOS Version doesn't show tags selection anymore

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1602]
**Describe the bug**
The iOS Verion shows the section "Tags" from the sidebar as an empty section.
"Themes" and "Views" are shown correctly. The Tags assigned to the notes itself are shown corretly in the right sidebar aswell.

**To Reproduce**
1. Click on menu button
2. Left sidebar appears with a empty 'Tags' section

**Smartphone (please complete the following information):**
 - Device: [iPhone 13 Pro]
 - OS: [iOS 15.5]
 - Browser [safari]
 - Version [3.20.1 (130)]

**Comment by MustachedMario** [comment]
Switching between the default white/blue theme and some other theme and back to default fixes this problem until app restart. Well, they are so many problmes with themes on mobile, you should investigate this a bit more.

Example:
Swichting to the "Futura" theme on iPad, type a note on the onscreen keyboard > OK.
But if you attach apples magic keyboard, then ALL editors except plaintext and markdown basic don't let you type anything in any notes anymore. Swichting back to default "white/blue" theme, all problems are gone.

**Comment by atmoio** [comment]
Hmm I can't replicate the tags issue. So if you start the app from scratch while using a dark theme, tags don't show, but if you start it from scratch while using the default theme, they show?

**Comment by MustachedMario** [comment]
The "tag section" doesn't show on every app start. A placeholder apears with something like "No tags. Create one frome the note composer." After changing themes (the default dark or white), the tag section with content is shown again, until the next app start.

Edit: Typos

**Comment by MustachedMario** [comment]
Kicking the app in the backgound and then reopen it, let the tags reapear also. So switching the themes is only one way to get back the tags. But the tags always disapears again after force quit the app.
So a UI refresh, whatever this triggers, solves the problem.

**Comment by MustachedMario** [comment]
iOS Version 3.23.4 (5) fixes the problem with the missing tags.
Closed.

**Comment by atmoio** [comment]
Just double checking, do you mean 3.23.3? There shouldn't be a 3.23.4 yet.

**Comment by MustachedMario** [comment]
You are right, this is a typo. Should be 3.23.3 (5).
