### ISSUE TITLE
[Webapp] Preview of attached images won't zoom correctly

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1603]
**Describe the bug**
Open an attached image with the preview funktion of SN. The attached Image must be larger in resolution as the screenresolution. The preview windows won't let you scroll to the upper half of the image if you zoomed it e.g. 200%.

**To Reproduce**
1. Preview an attached image, e.g. jpeg
2. The preview window opend
3. Zoom to 200%
4. Try to reach the upper half of the zoomed image with scrolling

**Expected behavior**
Zoomed image in preview windows should be accessable in all parts of the image, not only the last 70% of it.

**Webapp (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Browser [Latest Firefox, Latest Edge]
 - Version [3.20.0 Webapp]

**Comment by atmoio** [comment]
Thanks, can replicate 👍 I can scroll down but not up.

**Comment by MustachedMario** [comment]
This zooming behavior is fixed in V3.22.5.
(I'm sure, this was fixed one or two releases before V3.22.5)
Closed.
