### ISSUE TITLE
[Help Wanted] Seem no way to add 'smart views' anymore after redesign

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1604]
I added a bunch of smartviews about 2 years ago and worked fine so far.
After the SN "redesign", adding smartviews seems not working anymore.

[Documentation](https://standardnotes.com/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters) points to add new one's as "folder", but the folder just disapear and adds no new smartview.

**Comment by atmoio** [comment]
Sorry, first sample in the documentation has an extra `]` at the end. We'll get that updated. The rest of the samples seem to work for me in 3.20.0.

**Comment by MustachedMario** [comment]
Yeah, this first "foo" example was used to test, didn't noticed the extra "]" myself.
Tested this again with other examples. works so far, even copys from my older ones.
