### ISSUE TITLE
Unable to load editor in iOS app

### ISSUE THREAD

**Issue by maiertech** [standardnotes/forum#1606]
**Describe the bug**

When I edit a note in the iOS app, switch to another app and then switch back to Standard Notes, the note is now displayed as plain text and I see an error message saying an unknown error occurred and the editor could not be loaded. Only when hitting reload, the configured editor is loaded. 

**To Reproduce**

1. pick a note with editor other than standard text.
2. Edit something.
3. Switch to another app (to copy something, for example).
4. Switch back to Standard Notes.
5. You should see the error shown in the screenshot below.

**Expected behavior**

After switching back to Standard Notes, I should be able to seamlessly continue where I left off.

**Screenshots**

![2022-05-21 07 33 09](https://user-images.githubusercontent.com/1482402/169721528-86e10e08-2656-471c-a076-9564f44257e7.jpg)

I redacted the note in the screenshot with a black rectangle.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15.5
 - Version: 3.20.1

**Comment by MustachedMario** [comment]
I can confirm this behavior. After clicking on reload, problem is gone until you restart the app.
Happends randomly on different notes. All notes used in this case the same editor.

**Comment by bats4turbojetIZgrilled** [comment]
I experience this issue as well. For me it’s mostly with the basic task editor.

Unable to load Task Editor - An unknown error
occurred.Webview Error: Could not connect to the server.

iOS app v 3.23.8
iOS version 15.5

**Comment by myreli** [comment]
With the new mobile experience, it seems like these issues have been solved. Please feel free to re-open it in case it still doesn't work.
