### ISSUE TITLE
Crashes always on startup

### ISSUE THREAD

**Issue by rainerbaers** [standardnotes/forum#1607]
StandardNotes 3.20.1 crashes every time I attempt to start it on my Android phone

Installed the app from Google Play in normal way
Attempted to start it, but it crashes every time

**Smartphone (please complete the following information):**
 - Device: Oukitel WP9 (= Wheatek WP9?) Version: OUKITEL_WP9_EEA_V16_20210609
 - OS: Android 10, build version: alps-mp-q0.mp1-V9.322.1
 - Version: StandardNotes 3.20.1

It works fine on my other Android phone and on Windows 10.

**Comment by atmoio** [comment]
Try clearing the storage for Standard Notes from your Android settings.

**Comment by rainerbaers** [comment]
Thank you, clearing the storage solved the problem! It works without a hitch now.

I appreciate your time and effort.
