### ISSUE TITLE
[WebApp] Preview of attached images - Infopanel out of position on Firefox

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1608]
**Describe the bug**
When you show an attached image with the preview window and click on the "i"
to open the info panel, the panel is always out of position.

**To Reproduce**
1. Load SN on latest Firefox (100.0.2)
2. Open a note with attached image
3. Show the attached image in the preview window
4. Click on the "i"
5. The info panel apears on the right side OUT of the preview window
6. The info text is hangs in the air with no background color.

**Expected behavior**
The info panel should shown INSIDE the preview window

**Screenshots**
![sn_preview_window_info_out_of_position](https://user-images.githubusercontent.com/103278766/169876160-18f7828c-7f2d-49c4-9c68-f8d5e25e5505.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Browser [Mozilla Firefox]
 - Version [V100.0.2]

**Comment by stefan-yas** [comment]
Thanks for the report! It seems good on my side, but we'll try to reproduce this.

**Comment by MustachedMario** [comment]
I think, it's only happend, if the attached image is bigger than the preview window, so it must render a shrinked version of it.

**Comment by MustachedMario** [comment]
WebApp v3.27.5 fixes this problem on firefox.
