### ISSUE TITLE
[WebApp] Preview of attached Images - Navigate with arrow keys not always working

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1609]
**Describe the bug**
Show multiple attached images on a note, navigating thru the images with arrow keys is only possible until you click on an image

**To Reproduce**
1. Open a note with multiple images, lets say 5 images
2. Show the first one in the prewiew window
3. Navigate thru the images with the left/right arrow key
4. Click on one of those images
6. Try to navigate again with the arrow keys
7. No navigation is possible anymore, until you reopen the preview window

**Expected behavior**
Working navigation after clicking on an image

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Browser [Mozilla Firefox]
 - Version [V100.0.2]

**Comment by stefan-yas** [comment]
This is reproducible, will be fixed. Thanks!

**Comment by amanharwara** [comment]
@MustachedMario can you still replicate this? should've been fixed a while ago.

**Comment by MustachedMario** [comment]
@amanharwara
This is not fixed at all. tried again on v3.41.1 and it is still present on my side.
If i click on those images, the focus is set to the elements behind the image. I can clearly navigate elements behind that image with the arrow keys, until i click on the filename on the top left of the preview window. then focus is back in the preview window and navigating works again.

**Comment by amanharwara** [comment]
Fix should be deployed soon :+1:

**Comment by MustachedMario** [comment]
Fixed. (v3.41.2) 👍
