### ISSUE TITLE
Feature Request: Math in at least one Markdown editor.

### ISSUE THREAD

**Issue by benwr** [standardnotes/forum#161]
I'd really really appreciate (optional) math editing support via KaTeX in at least one Markdown editor. Preferably the "simple markdown" editor. Right now I'm forced to use either VSCode (which gets this 100% right via a plugin but is annoying to sync), or to use a less-secure web service like markdownnotes.com

**Comment by mobitar** [comment]
Can you share a screenshot of some sample text, and the desired output? Trying to get an idea for how this would be done client side without a server.

**Comment by mobitar** [comment]
Can you give this a go locally and see how well it works:

https://github.com/sn-extensions/simple-math-editor

**Instructions:**
```
git clone https://github.com/sn-extensions/simple-math-editor.git
cd simple-math-editor
git submodule update --init
open index.html
```

**Comment by mobitar** [comment]
Note that it's markdown + mathjax, so you will have to double escape some things.

`\(a \ne 0\)` would need to become `\\(a \ne 0\\)`

**Comment by mr-islam** [comment]
I'm sorry I'm kind of hijacking this thread, but I've never used git submodules before…

After setting up my SSH keys (I totally forgot I hadn't set it up after my re-install hehe), running `git submodule update --init` simply gives no output, and stays like that for minutes on end. I've tried deleting the whole directory, and doing all the steps again, but that still causes the same issue. 

I've ran the command for over 20 minutes now — there's something wrong, right?

**Comment by mobitar** [comment]
Sorry for the delay. Can you try running:

```
git submodule update --init --force --remote
```

**Comment by mr-islam** [comment]
Whew, it completed cloning the submodule:

`Submodule path 'vendor/MathJax': checked out '2965eab516910550491f895322bc181f1d24ca5a'`

But running `open index.html` doesn't work as it isn't a bash command — was the submodule command supposed to open another interface, where I would use `open`?

(Or maybe it's best if someone else tests, my set up seems to have so many issues)

**Comment by mobitar** [comment]
You can just find the index.html file and open it manually in your browser..(`open` works on Mac, not sure what OS you're using)

**Comment by mobitar** [comment]
Yeah, it's Markdown + Latex, so some escaping is required. What are your thoughts on this editor: https://upmath.me/

**Comment by mr-islam** [comment]
Ah, I recall this style of editor from Dynalist.io — having `$$` to 
escape makes it much clearer, but also more cumbersome to type that 
`\\`. But, the current Mathjax implementation also requires `()`, so 
upmath would overall be less work and clearer.

Dynalist had a keyboard shortcut (`Ctrl+L`) to automatically enter 
`$$`, and that makes it even quicker to use (but this is not fully 
necessary for such a feature in standard, which only some would use)

Overall, the upmath editor is nicer, because $$ is clearer, and it 
doesn't require the ().

**Comment by mobitar** [comment]
Cool, it's available now as the Fancy Markdown Editor: https://standardnotes.org/extensions/fancy-markdown-editor

**Comment by mobitar** [comment]
Note: this editor is now called "Markdown Math"
