### ISSUE TITLE
Unable to deselect note with CTRL

### ISSUE THREAD

**Issue by Sjeiti** [standardnotes/forum#1612]
**Describe the bug**
CTRL-click can be used to select multiple notes. The same interaction should deselect a selected note but it does not.
Plain clicking an unselected note will deselect your selection but when you have all notes selected all you can do to continue is reload the entire app.
The issue is probably related to #607 and #679

**To Reproduce**
1. CTRL-click multiple unselected notes
2. CTRL-click a selected notes

**Expected behavior**
CTRL-clicking a selected note should deselect it.

**Desktop:**
 - Windows 10 app v3.20.0
 - Windows 10 Firefox webapp v3.20.0

**Comment by effieeee** [comment]
Should be fixed on the latest versions!
