### ISSUE TITLE
Better support for a narrow note panel

### ISSUE THREAD

**Issue by altrahm** [standardnotes/forum#1616]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes

**Is your feature request related to a problem? Please describe.**
I keep my notes panel narrow so I can keep it visible without taking up too much desktop space.
Especially with the recent updates adding more buttons, this causes even short note titles to get cut off.

**Describe the solution you'd like**
The additional buttons could be collapsed into the "..." menu if the panel is narrow enough. In fact, the pin/unpin and change note type buttons already exist in the "..." menu, so they just need to be hidden.

There is also a lot of empty space reserved for the "All changes saved" message. That could be moved to the line below (where tags are displayed) and just temporarily block out some of the tags.

**Additional context**
Here's an example. The title is just "Movies" but everything past the "M" gets cut off
![](https://i.imgur.com/DmihOXH.png)

**Comment by atmoio** [comment]
Better responsiveness is on our near term radar 👍 We have some prototypes already, but need to spend more time polishing before we get to the release phase.

**Comment by myreli** [comment]
This should be achievable with the new responsive UI. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
