### ISSUE TITLE
Create new note cause edit window to disappear

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/forum#1617]
**Describe the bug**
When I create new note on the desktop app, and a smart tag, Archived, or Trash is marked in the navigation menu, and I try to write something in the title bar, the note edit window disappears. I can find the note again if I click on "Untagged". This behaviour is different than in previous versions of Standard notes desktop and web.

**To Reproduce**
1. Click on Create a new note ... (the plus-icon) when a smart tag, Archived, or Trash is marked in the navigation menu.
2. Write something in the title bar.
3. The note edit windows disappears.

**Expected behavior**
The note edit windows shouldn't disapperar when I try to write something in the title bar.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon, Windows 10.
 - Browser: Brave 1.39.111 (on Linux Mint and Windows), Firefox 100.0.2 (on Linux Mint).
 - Version: 3.20.0

**Additional context**
The note window shouldn't disappear when I'm working on a note regardless of what I do (adding tags, writing text, etc). The only instance the edit window should disappear, in my opinion, is when I click on another post in the navigation menu to work on a new note.

**Comment by atmoio** [comment]
Can replicate, thanks 👍

**Comment by myreli** [comment]
It seems like this issue has been solved. Feel free to report again in case you face any issues. Thanks!
