### ISSUE TITLE
[Help Wanted] Is it safe to delete backup files?

### ISSUE THREAD

**Issue by Pneumatikos1** [standardnotes/forum#1619]
I was wondering if it's safe to simply delete Standard Notes backup files. I've accumulated quite a few hundred daily backup files, which I know I don’t need. Can I simply delete the older ones, or will doing so break some functionality? I’d appreciate any help. Thanks.

**Comment by atmoio** [comment]
You can safely delete them without affecting functionality, if you are not interested in retaining recovery options for the date ranges covered by those backups.

**Comment by Pneumatikos1** [comment]
Understood. Thanks a million.
