### ISSUE TITLE
V2.4.0, Linux 32-bit, Mate: Scrollbar separates into two parts, both draggable

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#162]
For version 2.4.0, 32-bit client installed from DEB package in Linux Mint, Mate window manager.

As shown in the following screenshot, when I hover over the scrollbar to the right of the list of notes, that scrollbar offers me a second noticeably thinner scrollbar along its right side. If I drag that second scrollbar to the right it indents the text in the text editing area to the right.

![sn32-bitlinuxmatedesktopscrollbarissue](https://user-images.githubusercontent.com/3333327/36236815-0bfa2446-11ad-11e8-89e6-e7a843e49731.png)

That in turn leaves a "void" between the list of notes and the text editing area.

If instead I _carefully_ click and hold on the left side of that same scrollbar its drag behavior works properly. As in, the left side of the text editing area is indeed its "true" left side.

This isn't a show stopper for me -- just reporting it...

Cheers, thanks, & hope this helps,
Riley
SFO

**Comment by WritingSolutions2020** [comment]
None of the other scrollbars seem to exhibit this behavior, by the way...

**Comment by mobitar** [comment]
So actually, those bars that you're seeing on hover are not scroll bars, but panel resizers. You drag them to adjust panel widths and editor margins.

It definitely seems more pronounced on Linux because of the default scroll bars, hadn't anticipated that. Perhaps it might also help to color those bars in the dark themes to a more distinct color.

**Comment by WritingSolutions2020** [comment]
I'm confused -- what would be the purpose of enabling one to create unused space between the list of notes and the text editing area?

Again, IF I carefully grab the left side of the scrollbar / resizing bar that separates the list of notes and the text editing area, THEN I can resize columns: If I drag to the right, the list of notes column gains space while the text editing area loses space. And vice versa.

BUT IF I instead grab the second smaller scroll bar THEN I can only take away space from the text editing column. The notes column gains no space. And there's a seemingly unusable void between the two columns.  Unlilke any other application I've ever used...

Cheers & thanks,
Riley

**Comment by WritingSolutions2020** [comment]
A variation of this issue also manifests itself in the Web client. However in the Web client the resizer bar is invisible -- I need to know where it is and poke around in "complete darkness" to locate it. This particular variation of the problem is probably caused by the fact that for whatever reason SN themes don't always have sensible colors. So I need to select a theme on the basis of, say, being able to see selected text, et cetera...

**Comment by WritingSolutions2020** [comment]
I've attached a second screenshot that illustrates how the resizer bar "comes loose" from the scrollbar.

![sn0201resizerbarissue02](https://user-images.githubusercontent.com/3333327/36286545-21c0970c-1265-11e8-9b99-c9b7833c5c22.png)

As you can see, the resizer bar has made the text editing area narrower but has not made the notes list column wider.

Cheers & hope this helps,
Riley

**Comment by WritingSolutions2020** [comment]
And as far as the Web client goes. the "floating resizer" also occurs in the Vivaldi browser, a Chrome clone (as in not Firefox)...

**Comment by WritingSolutions2020** [comment]
Oops, accidentally closed this while commenting that the issue also occurs in the Vivaldi browser, a Chrome variant. (As in, not Firefox...)

**Comment by mobitar** [comment]
The reason for the resizers on the editor are so you can go from this:

![screen shot 2018-02-16 at 9 52 49 am](https://user-images.githubusercontent.com/3277844/36316164-3902b5fe-12ff-11e8-91b2-541252896762.png)

to this ;)

![screen shot 2018-02-16 at 9 53 01 am](https://user-images.githubusercontent.com/3277844/36316169-3d53bd6a-12ff-11e8-9d97-819515bdf125.png)

**Comment by WritingSolutions2020** [comment]
I admit I don't understand why I would want to do that. What's the benefit / utility?

**Comment by mobitar** [comment]
Full screen mode? Some users use that. And when you're writing in full screen, you don't want text from end to end. It's impractical. You'd want it to read like an article instead.

**Comment by WritingSolutions2020** [comment]
OK, well I'll take it on faith. Thanks as always for your time and help.

Cheers,
Riley
SFO
