### ISSUE TITLE
Notes randomly marked with "Conficted Copy", without creating a copy

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1620]
**Describe the bug**
Another Day, another buggy SN experience, I'm so sick of all the bugs!

- WebApp: Notes randomly marked with "Conficted Copy", while editing other notes.
- Mobile: Every time opening the Mobile App, random notes marked with "Conficted Copy", WITHOUT creating a copy.
- WebApp: Edit Note A, Note C are marked as "Conflicted Copy".
- WebApp: Create a new Note, an random old note was duplicated with a tuncated Notetitle and empty content, the original note was marked as "Conflited Copy".

**To Reproduce**
1. Just use SN, no matter if WepApp or Mobile

**Comment by jrabensc** [comment]
Same here. Happens randomly using the App on Windows.

**Comment by atmoio** [comment]
@MustachedMario you were doing so good reporting issues without getting overly emotional 😓 Tbh seeing email notifications from you in my inbox raises my heart rate. So let's call this one final chance. I'd love to keep fixing issues for you. But the deal is you have to be civil about it. We do our best. If it ends up not being enough, only one of us here's presence is voluntary.

**Comment by MustachedMario** [comment]
@moughxyz It's hard to be not emotional, when you lose at least one important note a day, or the mobile apps doesn't work or start at all, just when you want to note something important. I don't know how you use SN yourself as dev, but on my side i stuggle everyday using it. How does you feel when you typed 5000+ words on iPad, then the mobile app just went black. after closing it, the note title is still there, but the content is empty. oh yeah, the history is empty also.

Editing a exiting note, add a few lines, waiting all is saved. open it again, and the additional text just gone. This happends at least 1-2 times a week. oh yeah, the history is empty also.

Or you just start typing, and after a few words you can't enter anything, must close the app, restart and then the whole thing is repeating. It took me days to find out this was a midnight theme problem.

etc..

**Comment by atmoio** [comment]
Honestly if that is your experience using SN, I would stop using it immediately. This isn't my experience nor the average experience. I'm honestly not sure I could ever forgive an app if it lost 5000 words. Perhaps my perspective is wrong and you are actually incredibly merciful and forgiving 😄

In any case, it is hard not to be emotional. This applies to both of us. But it's the only we can productively and healthily collaborate.

Regarding the issue at hand, please see [Microupdate: Server status and conflicts](https://blog.standardnotes.com/35571/microupdate-server-status-and-conflicts) and the subsequent [Microupdate: Resolution regarding server status](https://blog.standardnotes.com/35591/microupdate-resolution-regarding-server-status).

**Comment by MustachedMario** [comment]
The randomly marked notes as "conflicte copy" wasn't happend again after the microupdates.
Closed.
