### ISSUE TITLE
Changing default editor, alter ALL older plaintext notes, instead of only new ones

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1621]
**Describe the bug**
Changing the default editor, alters all notes, that was previously created with the plaintext editor as default one.

As I understand, a note saves also the editor that is used in its metadata. So if you create a note with a e.g. markdown editor, its saved into metadata. It also does when you switch back to plaintext, plaintext editor is saved as a editor.

But if the plaintext editor is the default one in the settings, all new plaintext notes seems to have an empty editor entry or it doesn't take affect. So if you change the default editor e.g. to spreadcheat, all previous created plaintext notes switching to spreadsheat instead only new created ones. This could be fatal, because the spreadsheat editor destroys the note content, if a change was made to the note.

This doesn't happend, when you set a default editor other than plaintext from the beginning, so changing the default editor later on, doesn't alter all older notes.

**To Reproduce**
Steps to _**reproduce**_ the behavior:
1. go to settings, select 'plaintext' as a default editor
2. create a new note with content, its a plaintext note.
3. go to settings, select 'markdown' as a default editor
4. this previous created plaintext note changes to markdown editor
5. create a second new note with content, its a markdown note.
6. switchback the default editor to plaintext.
7. first note is plaintext again, second note keeps markdown editor

Steps to **_confirm_** the behavior:
1. go to settings, select 'plaintext' as a default editor
2. create a new note with content, its a plaintext note.
3. change the note editor (not the default editor) to e.g. markdown
4. change the note editor (not the default editor) back to plaintext
5. the note should now have an plaintext entry in the metadata
6. now change the default editor to something other, and the plaintext note keeps plaintext

**Expected behavior**
Changing the default editor, should only alter new notes.

**Comment by MustachedMario** [comment]
Tried webapp v3.41.3, and this doesn't happend anymore. Are there any fixes that caused this?

**Comment by myreli** [comment]
It seems like it has been fixed. Please re-open in case you face it again. Thanks!
