### ISSUE TITLE
Sign-in notification emails no longer received since May 30

### ISSUE THREAD

**Issue by Matei59** [standardnotes/forum#1622]
Hello, I am SNpro user and I noticed that I no longer get the email notifications after I sign-in to the SN web interface.
The last "new sign-in" email received was on May 30, 2022. 
No recent changes were done to SN preferences, i.e. the option Security/Privacy/Disable sign-in notification emails is disabled. (so the emails should be sent by SN servers). 
On the email account there were no recent filters added and the spam folder was checked and was empty.
Is it possible to take a look and see if these sign-in emails are working properly?
Thank you.

**Comment by atmoio** [comment]
We discovered a regression wherein sign in emails were not sent for roughly a 24 hour period. Should be fixed and back to normal now.

**Comment by Matei59** [comment]
Many thanks for the prompt response!
