### ISSUE TITLE
[WepApp V3.20.2] Notes sort by 'title' is not alphabetical anymore

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1625]
**Describe the bug**
Until V3.20.0, sorting by title was in alphabetical order. Since 3.20.2 you must revers the sort order to get alphabetical order.

**To Reproduce**
1. Sort notes by title
2. Sort order is from z to a
3. Sort notes by title + reversed
4. Sort order is now from a to z

**Expected behavior**
Sort with active 'reversed' should sort from z to a, not from a to z

**Webapp (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Browser [Firfox]
 - Version [101.0]

**Comment by atmoio** [comment]
Fixed 👍

**Comment by MustachedMario** [comment]
Can confirm the fix.
