### ISSUE TITLE
Dynamic Markdown text size on android is too big

### ISSUE THREAD

**Issue by jrcacd** [standardnotes/forum#1628]

**Comment by viharsheth** [comment]
100% agree. Really like the idea behind the editor but have found the text to be annoyingly large on Android as well.

**Comment by atmoio** [comment]
Could you share a screenshot?

**Comment by jrcacd** [comment]
![Screenshot_2022-06-16-17-03-57-068_com standardnotes](https://user-images.githubusercontent.com/26005662/174115850-8bd59fd4-85c9-4c00-990a-87ff6e7979f1.jpg)
![Screenshot_2022-06-16-17-03-04-179_com standardnotes](https://user-images.githubusercontent.com/26005662/174115861-0483aa8b-dca4-4eb4-8d33-cb960169d64c.jpg)

**Comment by viharsheth** [comment]
Smaller text is markdown minimalist and the larger is the same note when
switched to dynamic markdown.

**Comment by viharsheth** [comment]
Did my attachments come through via email?

**Comment by viharsheth** [comment]
![Screenshot_20220616-110409_Standard Notes](https://user-images.githubusercontent.com/47013219/174323535-8df89d66-f14d-45e5-a42f-7a52bfb4202e.jpg)
![Screenshot_20220616-110358_Standard Notes](https://user-images.githubusercontent.com/47013219/174323546-f73102c5-5e20-4a5a-afa3-29fb51b4da68.jpg)

Here they are.

**Comment by viharsheth** [comment]
The font is still very large on the Android app. Is it supposed to be
smaller or will it be fixed in the next update?

**Comment by viharsheth** [comment]
Just following up on this. Dynamic Markdown still has huge fonts on my Android device. Wondering why this was closed.
