### ISSUE TITLE
Since iOS Version 3.23.3 (5), no Editors is loading. Caused by signature differ.

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1633]
**Describe the bug**
Since iOS Version 3.23.3 (5), no Editors is loading. SN is generating a banner with the following information: **"Unable to load <Editorname> - The remote editor signature differs from the expected value."** Pressing the **reload** button didn't solve the problem.

**To Reproduce**
1. Open SN on iOS
2. Open a random note with active editor
3. Error message is genereated

**Expected behavior**
The selected editor should load.

**Smartphone (please complete the following information):**
 - Device: [iPhone 13 Pro]
 - OS: [15.5]
 - Browser [Safari]
 - Version [3.23.4 (5)]

**Comment by atmoio** [comment]
This was caused by a versioning issue from our new automated deployment system. Working on a patch, close to deployment. Should hopefully be a remote-side fix without a need to upgrade mobile app directly.

**Comment by MustachedMario** [comment]
Server-side fix seems to work, at least for loading the editor once, while opening a existing note.

But this fix causes new problems, when you open a note and kick the app in background. When you reopen the app after around 10 seconds from the background, the editors won't load again, because they lost "connection to the server."

**Comment by MustachedMario** [comment]
Version 3.23.8 (10) seems to fix the problems.
Some editors won't load after the first app start, but after pressing 'reload' on the error banner, all problems are gone. I tried it serveral times, close/reopen the app, the editors are loading fine now.

**Comment by MustachedMario** [comment]
Current iOS Version is 3.30.25 (95) and not happend again.
Closed.
