### ISSUE TITLE
Authenticator / Token Vault "Error Not Found" on web client

### ISSUE THREAD

**Issue by Tomjans** [standardnotes/forum#1638]
**Describe the bug**
Can't use the authenticator / Token Vault  plugin as I receive the following message: {"error":{"message":"Not found."}}. Happens with all authenticators, even newly created ones in the web client. Clearing cookies, cache, storage, site data etc. does not help. Using the Android app, there is no problem. Only the web client. I am Not self-hosting. 

**Screenshots**
![authenticator](https://user-images.githubusercontent.com/77100335/175229359-2438f962-d55c-448e-9f88-fcc3d598cbe4.PNG)

**Desktop (please complete the following information):**
 - Browser: Brave (Chromium)
 - Version: v 1.40.105

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by atmoio** [comment]
Sorry about that, deploying a fix. ETA 1 hour if no issues.

**Comment by atmoio** [comment]
Should be back to normal working order now.

**Comment by jmason888** [comment]
FileSafe seems to be having the same issue.

**Comment by atmoio** [comment]
@jmason888 on it, thanks

**Comment by johnny243** [comment]
@jmason888 should be fixed now 🙂
