### ISSUE TITLE
Regression: "Duplicate" function in Action Bar does not appear to work

### ISSUE THREAD

**Issue by jmason888** [standardnotes/forum#1639]
**Describe the bug**
Clicking on the "Duplicate" button in the Action Bar does not create a copy of the note.

**To Reproduce**
1. Create a new Plain Text note
2. Enter "Hello" as the title
3. Enter "this is a test" in the body
4. Open the Action Bar
5. Click on "Duplicate"
6. Search for "Hello" in the list of notes
7. No duplicate "Hello" note appears in the list

**Expected behavior**
A duplicate note should be created with the same title, contents, and attributes as the original. This is how the "duplicate" function used to work; now it appears to be a no-op.

**Desktop:**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 103

**Smartphone:**
- _(Action Bar plugin is not available on mobile)_

**Comment by atmoio** [comment]
The Action Bar is deprecated and no longer maintained. Most of its functions are now built-in to the app. You can find the duplicate option in the ... note context menu.

<img width="328" alt="Screen Shot 2022-06-24 at 6 38 48 AM" src="https://user-images.githubusercontent.com/3277844/175527131-f56c1843-f5f8-40d3-966c-2fb70a149b61.png">
