### ISSUE TITLE
[SOLVED] Ubuntu 14.04: problems in installing -2.1.0-x86_64 version

### ISSUE THREAD

**Issue by guydog** [standardnotes/forum#164]
I cannot install new SN version on Ubunti 14:04 (x64) as it gives me the following error:

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory

**Comment by mobitar** [comment]
What's the command you're running?

**Comment by guydog** [comment]
Problem solved, probably my file was corrupted.
I downloaded again SN 2.1.0 and this time I could open and run the appimage.
Thank you for your quick answer anyway!

**Comment by mobitar** [comment]
Ok great!
