### ISSUE TITLE
[WebApp] Adding a subtag, adds the same tag in the root folder

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#1644]
**Describe the bug**
Adding a subtag to an existing tag, e.g. add #js to #dev, results in #dev/#js but also #js apears as tag in the root.

Example:
- js
- dev
  - js

**To Reproduce**
1. Click the 3 dots by a tag
2. Click on 'add subtag'
3. Added subtag exists twice, on root and as subtag.

**Expected behavior**
No duplication of added tag in the root

**WebApp (please complete the following information):**
 - OS: [Windows 11 Pro / macOS 12.5]
 - Browser [Latest Firefox/Edge/Chrome]
 - Version [WebApp V3.27.7]

**Comment by atmoio** [comment]
Hmm, can replicate. Seems to be a cosmetic issue as the tag eventually disappears from root on next render.

**Comment by MustachedMario** [comment]
I can confirm, that this duplicated tag is disapearing during a refresh. I'm not tried this at first, because deleting the tag on the root, also deliting the subtag. Looked like a bigger problem.

Refreshing is the current workaround.

**Comment by BobWs** [comment]
I had noticed the same problem…

Out of curiosity...will the folder icon return, as it was with the old extension?

**Comment by amanharwara** [comment]
Should be fixed in latest web & desktop builds.

**Comment by MustachedMario** [comment]
I can confirm the fix, using v3.39.1
