### ISSUE TITLE
[Help Wanted] Reinstalling Action Bar

### ISSUE THREAD

**Issue by apowers313** [standardnotes/forum#1647]
**Describe the issue**
I have a StandardNotes professional account and I accidentally uninstalled Action Bar. How do I reinstall it?

**Comment by viharsheth** [comment]
I have the same issue. Did you @apowers313 ever figure this out?

**Comment by effieeee** [comment]
Hi all, unfortunately the Action Bar doesn’t have an install link like our other deprecated extensions :( However, a number of its functions are already integral parts of the app! (note length statistics, duplicating, sharing/exporting)

**Comment by viharsheth** [comment]
As long as it's missing on purpose and not gone due to a bug I understand.
