### ISSUE TITLE
Loop asking unlock the app in energy saving mode - iphone 6s

### ISSUE THREAD

**Issue by E-Baler** [standardnotes/forum#1649]
**Describe the bug**

Hello, following the last update it is impossible for me to access my notes in a secure way. 

I have closed the ticket but the problem came back that's why I open again the issue.

I unlock the application with my biometric fingerprint and then a code and I can access my list of notes without any problem.

But when I want to access my notes (protected by biometric fingerprint and code), the application protection is overlaid on the notes protection and I have to identify myself once again in the app. 

and I come back to my notes list and it makes an endless loop which prevents me from accessing the notes.

Thank you,

**To Reproduce**
1. Open app
2. enter Biometric fingerprint and alphanumeric code
3. Notes list appears 
4. Select notes (protected by fingerprint and alphanumeric code)
5. Notes protection window appears asking fingerprint 
6. Scan fingerprint
7. App protection window appears asking for unlock
8.unlock again the app
9.notes list appears again
10. problem starts over and over again when try to open a note 

**Expected behavior**
Just select a note, enter fingerprint and code and access note.

**Smartphone (please complete the following information):**
 - Device: [iPhone6s]
 - OS: [ios 15.5]
 - Standard notes app

**Additional context**

__Originally posted by @E-Baler in https://github.com/standardnotes/forum/issues/1646__

**Comment by E-Baler** [comment]
I have found the issue comes when the phone is in energy saving mode.

**Comment by myreli** [comment]
Hi @E-Baler I'm sorry for the late reply. I'm triaging older issues and just came across your report. 

Can you please test if this is still happens with the latest version of the app? 

In September there was the release of the new mobile experience, which changed the implementation of the lock screen and I'm wondering if that fixed it. On Android I wasn't able to reproduce it.

**Comment by E-Baler** [comment]
> Hi @E-Baler I'm sorry for the late reply. I'm triaging older issues and just came across your report. 
> 
> 
> 
> Can you please test if this is still happens with the latest version of the app? 
> 
> 
> 
> In September there was the release of the new mobile experience, which changed the implementation of the lock screen and I'm wondering if that fixed it. On Android I wasn't able to reproduce it. 

Hello, don't worry, you offer a great open source and partly free product I'm not in a position to be demanding and resentful - I can only thank you! 

I used to use it in normal mode but I just tested in power saving mode and it works perfectly. 

Sorry I haven't tried it since but as I said before I had adapted. 

Thanks again for your work!

**Comment by myreli** [comment]
I'm glad it works now! Thank you for your kind words @E-Baler, I'll share them with the team ❤️
