### ISSUE TITLE
Unable to run extensions, warned on every startup that an update is pending.

### ISSUE THREAD

**Issue by garrettjj** [standardnotes/forum#165]
Hey there,

First off, thanks for the awesome bit of software! It's great to have on everything, especially the Linux version. I'm running the AppImage file on Fedora 27 and every time I launch SimpleNote 2.1.1, I'm receiving the note in the bottom-right corner alerting that an update is available and when I click into Extensions, I'm unable to use the extensions and it warns that "This extension is not installed correctly. Please uninstall extensions and then re-install it. Any tips to fix this? It seems like some old data is held somewhere but I'm just not sure where.

**Comment by mobitar** [comment]
So there are two separate issues here. About the blue "update is available" message, sometimes you have to wait a little bit after you quit the app for the update to apply. Do it a few times, and eventually, it should update.

As for the extensions, the message indicating that it is not installed correctly can occur if you access SN from a pre-2.1 version. Be sure you're upgraded on all platforms. If you see this message again, please let me know, and recall any steps you may have taken.

After uninstalling and reinstalling the extension, are you able to successfully run it?

**Comment by garrettjj** [comment]
Hey there, Thanks for the response! I grabbed the latest AppImage from the site and tried running it on my Linux installation but it still appears to be showing the latest update note in the bottom-right corner. Is there a temporary file that might need to be cleared to handle this?

As an aside, the extension error message started showing on all versions of StandardNotes when I grabbed the latest AppImage so I think I associated the two. It doesn't give me the option to uninstall any extensions since the whole extensions menu shows that error.

**Comment by mobitar** [comment]
Ah sorry, I just noticed I had the wrong download links on the website. This has been updated. Please try downloading it again.

**Comment by garrettjj** [comment]
Okay. I was able to clear up the update notification by grabbing the updated link but I'm still unable to use extensions. I've updated to the most recent version on all of my current devices but an OS that was recently removed due to some weirdness might still be causing issues. Is there a way to see what devices it's referring to when it asks to update on all of them?

**Comment by mobitar** [comment]
Please see here regarding double Extensions menu: https://github.com/standardnotes/web/issues/185#issuecomment-366276013

**Comment by garrettjj** [comment]
This is a bit old although I was able to resolve it by following the cited issue. Going to close this now.
