### ISSUE TITLE
Unable to cancel 14 days trial

### ISSUE THREAD

**Issue by slider56** [standardnotes/forum#1651]
Unable to cancel  LM-7769273529 14 day trail .  Phone help has not helped.  Cancel_subscription.msi will not fully open, gives error message. Help number (888)260-7583 "Help" folks unable to help. Please cancel, or I must notify CC company not to pay any charges.
Extremely disappointing support number, did not identify themselves as StandardNotes support, had to question them as to who they were.

**Comment by atmoio** [comment]
This is a spam email that isn't affiliated with us. Most major email providers should have correctly classified it as spam. Never open or download files from a spam email.
