### ISSUE TITLE
Editing an item in Authenticator note type not consistent across mobile(Android) and browser version

### ISSUE THREAD

**Issue by edzed42** [standardnotes/forum#1654]
In the Authenticator note type, I have an item that is set to "Password Only" and when I edit it on Android, it defaults to the 2FA option (has a "secret" text field), there is no option to change it back to "Password Only" on mobile and I cannot save any changes since the "secret" text field being empty/incorrect prevents me from doing so. This happens with any items set to "Password Only".

**To Reproduce**

Follow what's written above.

**Expected behavior**
While editing an item on Android, I expect it to default to the option that the entry was saved as ("Password Only" in this case), and maybe have "2FA" and "Password Only" appear while editing in case I want to change that on an item while on mobile.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 103.0.5060.114 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android Version 12
Standard Notes app Version 3.23.8

**Additional context**
I initially added these items while on the browser version of Standard Notes. I noticed the inconsistency of editing from the browser vs Android while trying to edit while on the Android app of Standard Notes.

**Comment by myreli** [comment]
Since the [new mobile experience launched](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) this should no longer be an issue as the app has feature parity across platforms. 

Please let us know if you still face any issues, thanks!
