### ISSUE TITLE
Very confused about SEARCH missing (using it on mac, linux, and iOS)

### ISSUE THREAD

**Issue by giancarloerra** [standardnotes/forum#1655]
Coming from Evernote I'm a bit confused by what seems a fudamental missing feature like Search?

I can see there's a search in all Notes, and it selects the notes containing that word....but then I would expect all occurrences of the word to be highlighted in the note itself?? Or to have a way to search in the note and easily jump to all occurrences within the note?

I can't see how to do that. Anyone can explain? I use Standard Notes (paid plan) on desktop Mac, desktop Linux, and on iOS iphone and ipad.

**Comment by steel-steven-87** [comment]
It doesn't support searching inside the note. I know, it is ridiculous that a note app is missing such a basic feature. I wish the developers looked around at other note taking apps in the world and realize this is almost as bad as not supporting newline characters in a text editor.

**Comment by SynapseScribe** [comment]
we need search inside note!

**Comment by myreli** [comment]
Duplicate: https://github.com/standardnotes/forum/discussions/2498#discussioncomment-4963504.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
