### ISSUE TITLE
iOS app loses scrolling progress

### ISSUE THREAD

**Issue by cclhk** [standardnotes/forum#1656]
**Describe the bug**
iOS app loses scrolling progress. This started happening a few app updates ago and remains not fixed in the latest update.

**To Reproduce**
1. Open a note
2. Scroll down
3. Close the app (or switch to another app)
4. Open Standard Notes app again
5. App now showing the top of the note. Scrolling progress lost.

**Expected behavior**
Note should remain in the previous scrolling position, which was the behaviour until recently.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 15.4.1
 - Browser: not applicable
 - Version: 3.30.25 (95)

**Comment by fixje** [comment]
I am having the same issue with version 3.36.5 on iOS 15.6.1

**Comment by myreli** [comment]
Hi @cclhk and @fixje, are you still facing this issue with the latest version? 

Since this report, the mobile app has changed significantly and I wasn't able to reproduce it.

**Comment by fixje** [comment]
haven't seen it for a while :+1:
