### ISSUE TITLE
Cannot open web links from android app

### ISSUE THREAD

**Issue by milindpadia** [standardnotes/forum#1657]
**Describe the bug**
When clicked on a URL a pop up shows stating "Unable to open URL <url>"

**Screenshots**
![Screenshot_20220718-195847_Standard Notes.jpg](https://user-images.githubusercontent.com/43411294/179534036-6d77795c-ee3b-4e48-8dc2-091386ae0b1e.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: Android 12

**Comment by myreli** [comment]
Potentially fixed through the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon). Please let us know if you run into any other problems.
