### ISSUE TITLE
Android app stuck during refresh

### ISSUE THREAD

**Issue by 555h** [standardnotes/forum#1659]
**Describe the bug**
In the Android app, after doing the "pull to refresh" gesture in the main screen, occasionally the refresh will hang. All saving/edits is then broken until the app is force-stopped and reopened.

**To Reproduce**
1. [I don't know how to get to this state, but it's happened several times in the past day.]
2. At main screen, pull down to trigger a refresh.
3. Refresh icon stays stuck on the screen. Navigating to a different screen and then going back to the main screen causes the fresh icon to disappear. However trying to trigger further refreshes does not work.
4. Edits to existing notes fail: after opening an existing note and making a change, eventually the app gives the message "This editor is unable to communicate with Standard Notes. Your changes may not be saved. Please backup your changes, then restart the application and try again."
5. Creation of new notes fails: after creating a new note, the app eventually gives the message "Attempting to save this note has failed. The note cannot be found."
6. Functionality is not restored until the app is force-stopped and reopened.

**Expected behavior**
Refresh works properly, and the app syncs changes with the server.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 12
 - Standard Notes App Version 3.23.8 (3002010)

**Additional context**
I don't see any way to get error logs in the android app (like the devtools console in a browser).

**Comment by myreli** [comment]
Fixed through the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon). Please let us know if you run into any other problems.
