### ISSUE TITLE
Notes field jumps up and down while editing in offline mode due to line break in changes saved message

### ISSUE THREAD

**Issue by tylerjdisney** [standardnotes/forum#1662]
**Describe the bug**
In offline mode, the message switching between 'Saving...' and 'Changes Saved Offline' causes the whole note field to jump up and down, because Changes Saved Offline has a line break in between Saved and Offline.

**To Reproduce**
1. Go to Windows Desktop application of Notes.
2. Turn your internet off.
3. Start typing in any note.
4. Watch the note field jump up and down.

**Expected behavior**
The note field staying in one place while editing in offline mode.

**Screenshots**
![notesjump1](https://user-images.githubusercontent.com/5060023/181807520-c4159d59-2f69-4509-b9c0-3c89cf96fa49.png)
![notesjump2](https://user-images.githubusercontent.com/5060023/181807533-9c9c703a-a8ba-404e-912c-2bed02d876fd.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
  - Notes Version 3.23.82]

**Additional Context** 
I edit in offline mode every day. I only noticed this behavior within the last week or so, I think after I was made to manually update to a new version. I'm not sure what version number that was.

**Comment by myreli** [comment]
The UI has been refreshed to look less disruptive, so this should no longer be an issue. Please let us know if you face any problems. 

<img width="624" alt="image" src="https://user-images.githubusercontent.com/17554234/218835768-f9788b59-93e4-4e30-9cb6-3b72c4adb172.png">
