### ISSUE TITLE
Deleting notes doesn't work on Android 

### ISSUE THREAD

**Issue by legate** [standardnotes/forum#1665]
**Describe the bug**
Deleting notes (i.e., move to trash) doesn't work. Nothing happens when selecting "move to trash" on a note.

**To Reproduce**
1. Long press a note
2. Tap "move to trash"

**Expected behavior**
The note is moved to trash and no longer visible in the default "notes" view. Instead, the note is still visible.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 12
 - Browser: Chrome
 - Version: 3.23.8

**Additional context**
Deleting a note from its context menu also doesn't work (open a note, open hamburger menu in top right, then selecting "move to trash"). The note will close, but is still not deleted.

I am using Standard Notes offline (no account, not signed in, no backup or sync).

**Comment by myreli** [comment]
Hey @legate! Sorry for the late reply. Since this report, several changes were made to the mobile app, so it seems like this is no longer a problem, so I'll close this issue. Please re-open in case you still need help. Thanks!
