### ISSUE TITLE
Generating keys forever and asks for keychain authentication [Linux app]

### ISSUE THREAD

**Issue by stvnddd** [standardnotes/forum#1666]
**Describe the bug**
I am experiencing an identical issue to #1631 but with the Linux app. @milkywaymetropolis has detailed exactly what I am having trouble with, except that my issue is with Linux desktop app.

I recently did a fresh install of Kubuntu on my laptop. I downloaded the Standard Notes Linux app again from the website, and when I opened it up, saw the 'Restore Keychain' window:

![image](https://user-images.githubusercontent.com/91346970/184849662-34a27950-6466-4a32-bef4-b3204f463d0c.png)

When entering my password, I am left with infinite load screen, same as the issue with #1631 :

![Screenshot_20220816_104622](https://user-images.githubusercontent.com/91346970/184852439-ecb8bd19-dc67-4030-9f72-aa038b2b11c5.png)

As you can see, I can still access the menu in the Top-Left corner. I tried clearing the cache and reloading it, closing it down, opening up again, but to no avail.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser: n/a
 - Version: 3.23.93

**Additional Comments**
Until this is fixed, I will have to resort to using Web App. This is not ideal. There is nothing obvious that could be obstructing this. I will update here if anything changes. No issues accessing account through Web App or iOS app on smartphone.

**Comment by milkywaymetropolis** [comment]
Thanks for mentioning me. I am looking out for a solution to this issue as well.

**Comment by stvnddd** [comment]
> **Describe the bug** I am experiencing an identical issue to #1631 but with the Linux app. @milkywaymetropolis has detailed exactly what I am having trouble with, except that my issue is with Linux desktop app.
> 
> I recently did a fresh install of Kubuntu on my laptop. I downloaded the Standard Notes Linux app again from the website, and when I opened it up, saw the 'Restore Keychain' window:
> 
> ![image](https://user-images.githubusercontent.com/91346970/184849662-34a27950-6466-4a32-bef4-b3204f463d0c.png)
> 
> When entering my password, I am left with infinite load screen, same as the issue with #1631 :
> 
> ![Screenshot_20220816_104622](https://user-images.githubusercontent.com/91346970/184852439-ecb8bd19-dc67-4030-9f72-aa038b2b11c5.png)
> 
> As you can see, I can still access the menu in the Top-Left corner. I tried clearing the cache and reloading it, closing it down, opening up again, but to no avail.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open Standard Notes app for Linux.
> 2. Enter password for restoring keychain.
> 
> **Expected behavior** Access Standard Notes account after new keys have been generated.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Kubuntu 22.04
> * Browser: n/a
> * Version: 3.23.93
> 
> **Additional Comments** Until this is fixed, I will have to resort to using Web App. This is not ideal. There is nothing obvious that could be obstructing this. I will update here if anything changes. No issues accessing account through Web App or iOS app on smartphone.

This specific issue has not been resolved, and there should still be a method that allows me to do this via the client app, but I went back onto the Standard Notes website to see if there were any alternative download methods. I noticed that it could be downloaded from the Snap Store as well. I hadn't tried doing that, so gave it a go.

I have downloaded it, signed in, and it is now working with no issues at all. I was not even prompted to enter in the password to restore the keys, i just logged straight in with ease.

Maybe @milkywaymetropolis you could try this too if you haven't already. Try downloading it from Snap store instead of using the client and check to see if it works for you too.

I will mark this as resolved, although technically we never got to the bottom of it, at least I have a workaround now.

**Comment by raleighlittles** [comment]
> I will mark this as resolved, although technically we never got to the bottom of it

Why would you mark this issue as resolved when it was never fixed? Please leave this issue open so that it gets visibility -- it's now several months later and I'm still having this issue, with a freshly downloaded version of the AppImage on the website.

Ubuntu 22, 5.15.0-48-generic

**Comment by stvnddd** [comment]
> > I will mark this as resolved, although technically we never got to the bottom of it
> 
> Why would you mark this issue as resolved when it was never fixed? Please leave this issue open so that it gets visibility -- it's now several months later and I'm still having this issue, with a freshly downloaded version of the AppImage on the website.
> 
> Ubuntu 22, 5.15.0-48-generic

Yes in hindsight I should have left it open. I don't think I can change it back now to Open? I actually ended up downloading it via Flatpak, and it has been working fine. Frequent updates can be provided this way, whereas with the AppImage it has to be done manually.

Sounds like downloading the AppImage on Linux is still causing the same issues as I had, which has been unresolved, you're right.

**Comment by ngarcia610** [comment]
This is unresolved. I've had this happen on chrome on windows. I imagine the fix is deleting the local directory that standard notes checks in order to determine that the keychain has been wiped? Perhaps something in %appdata%\local? There should be an easy way to reset the sign in page to treat it like a new sign in.

**Comment by ngarcia610** [comment]
Found a workaround:
1. Have the web browser open on the "restore keychain" screen
2. Right click > inspect > Select 'Application' tab
3. Expand Local Storage under the storage section
4. Right click https://app.standardnotes.com and select clear
5. Refresh the page and sign in.

**Comment by milkywaymetropolis** [comment]
Standard notes app is buggy/laggy in general. I have experienced this on multiple OS till now including Linux mint. Then I had this on Android 5.0 as well. And honestly this issue never got fixed which is why I abandoned standard notes entirely.

**Comment by atmoio** [comment]
If anyone has replication steps, please share. I haven't seen any in this thread.

**Comment by atmoio** [comment]
This issue is fixed in the latest web release (will be live within the hour).

Weird that Firefox's Clear Data feature clears everything but localStorage for a site. This is what was causing the issue. The solution on our end was to detect this and take the remaining step of clearing whatever is left of localStorage so that you're presented with a fresh app session.
