### ISSUE TITLE
[Help Wanted] "A server error occurred while trying to register…"

### ISSUE THREAD

**Issue by thomaskyhn** [standardnotes/forum#1667]
When trying to create an account I get the error message "A server error occurred while trying to register. Please try again."
<img width="326" alt="Screen Shot 2022-08-16 at 22 57 22" src="https://user-images.githubusercontent.com/22273777/184983833-42fbeac6-cdd3-4fb6-b513-55a893dbf767.png">
I've tried several times, in different browsers and in the macOS app.
Any suggestions what could be wrong?

**Comment by myreli** [comment]
Hi @thomaskyhn, I'm sorry for the late reply. I'm currently triaging older issues; your report was probably lost. Have you been able to register for an account?
