### ISSUE TITLE
Feature request - note locking.

### ISSUE THREAD

**Issue by zedgoat** [standardnotes/forum#167]
Would love to have the ability to lock notes as a core feature - for example, where using a password file I sometimes flub the copy and paste or a shortcut which wipes out the entry.

At the moment it's recoverable through the note history, but would be convenient to control the edit status on items that are acting as registers or references.

**Comment by mobitar** [comment]
Definitely, this is actually something on my short-term todo. Hope to get to it soon.

**Comment by zedgoat** [comment]
That's awesome news thank you! Blessing for my fat fingers anyhow.

**Comment by zedgoat** [comment]
Looks awesome, thanks!
