### ISSUE TITLE
standardnotes.com not reachable NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by pierreberthet** [standardnotes/forum#1670]
**Describe the bug**
standardnotes.com is not reachable, it has had issues for days.
NET::ERR_CERT_COMMON_NAME_INVALID

actually listed.to has issues too.

**To Reproduce**
copy paste the url in your browser
get a warning

**Desktop (please complete the following information):**
linux, brave and firefox, same results.

**Smartphone (please complete the following information):**
android 12, chrome

**Additional context**
there is a standard-notes.net website that looks suspicious. I would like to see some official statement about it being legit.  I have doubts. Also, the github repo was moved to a new repo. Why? Highly suspicious.

**Comment by myreli** [comment]
Hello @pierreberthet, we are triaging older issues, I'm sorry for the late reply. 

The official Standard Notes domain is https://standardnotes.com and the official Github Organization is @standardnotes. Previously the domain was https://standardnotes.org, so you might find older references pointing to it. The repository changes were merely a reorganization of the code. 

I don't recall other reports of the `NET::ERR_CERT_COMMON_NAME_INVALID`, but it seems to be working fine on my end. 

Other domains, including http://standard-notes.net, are a scam. Hopefully, I could respond to your concerns.
