### ISSUE TITLE
Unable to log in on Android/FDROID download -- same account works ob Web & MacOS

### ISSUE THREAD

**Issue by lulu-2021** [standardnotes/forum#1671]
Hi Support Team,

I wanted to try out the Standard Notes app today. I first created an account with my email "netflakes@proton.me" - signed in but must have mistyped the password twice.. logged out and could not log back in. Protonmail automatically gives you two equal email addresses, so created a new account with "netflakes@protonmail.com" and stored the password right away in my password safe. Logged out and back in ok and also logged onto the web version - so email/password is definetely working for that second account.

I then went to install on my mobile - I run "grapheneos" - which is an AOSP - no "google app store" - but FDROID works fine. I downloaded your app from FDROID and it installed ok. However when I attempt to log on it always either gives me an "invalid email/password" message OR you have attempted to log on too many times - please try again later.

I tried a few times and just to be certain that I am not misstyping the password - I typed it into notes and copied it - same problem. Given that I can log in and out of the app and the web version - I know the password cannot be the issue.

Can you check your logs to see why the mobile app is failing to sign in. Graphene should not be "messing" with authentication, but your logs might give more of an indication. I really like the app and am hoping I can get the mobile app login resolved. I checked the github/issues to see if anyone else had the same issue, but did not find one so I logged this as an issue.

**Comment by myreli** [comment]
Hi @lulu-2021, I'm sorry for the late reply. I'm triaging older issues and just came across your report. 

Can you please test if this is still happens with the latest version of the app? Since the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) this could have been solved, as the mobile app now shares the same implementation of all platforms.
