### ISSUE TITLE
[Feature Request] Better Autolock options: Selectable Timer, Lock on workstation lock

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#1674]
The autolock timer on the desktop client cannot possibly have enough time options for every use case. It also does not lock when the workstation is locked.

Please:

1) Let users enter a value in minutes or hours for the autolock timer
2) Implement a separate toggle to "lock on workstation lock". This should always lock Standard Notes when the workstation is locked, regardless of whether or not the timer has reached it's limit or is even used.

Thanks!

**Comment by myreli** [comment]
Duplicate: https://github.com/standardnotes/forum/discussions/2542

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
