### ISSUE TITLE
website not rendering ok

### ISSUE THREAD

**Issue by emi7718** [standardnotes/forum#1675]
i see it like this:

![image](https://user-images.githubusercontent.com/108490310/187768932-ca9d6f10-8a3d-42b8-9c76-98a8d3d613be.png)

in firefox, chrome, edge, on different pc's, once open, you can scroll in just that little upper space

**Comment by onlinemumie** [comment]
Having the same problem. Any chance someone at Standard Notes can roll out an older working version of the web app while this is being fixed. Some of us actually use it as a tool, not a toy, and we need it to be stable and reliable. Perhaps there could be an alternative version reserved for experiments, tweaking, and moving things around just for fun.

**Comment by onlinemumie** [comment]
This error occurs on [app.standardnotes.org](https://app.standardnotes.org/). But nowdays, the link to the web app is [app.standardnotes.com](https://app.standardnotes.com/).
