### ISSUE TITLE
We need collapsable notes/bullet points

### ISSUE THREAD

**Issue by SpaceRaccoonFluff** [standardnotes/forum#1678]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes

**Is your feature request related to a problem? Please describe.**
Anyone here who takes extensive notes, which I'm assuming is many, knows how much of a PAIN it is to scroll thru your notes to find something you are looking for when you're constantly looking back and forth. **Unfortunately, the more you write the more unbearable it becomes to use Standard Notes.** 

**Describe the solution you'd like**
I want this beautiful note nesting that Workflowy has https://i.imgur.com/o6XvSQx.png. 

**Describe alternatives you've considered**
I use bullet points extensively for ALL my notes. I specfially make sure the first primary bullet point is short and concise to make it easier to find what I'm looking for when scrolling aggressively. It's still a pain to quickly find as fast as it should be. 

**Additional context**
https://i.imgur.com/o6XvSQx.png

**Comment by vstepaniuk** [comment]
Have you tried scrolling the Google Doc app? That's cool
