### ISSUE TITLE
How do I restore the top toolbar?

### ISSUE THREAD

**Issue by cedewey** [standardnotes/forum#1679]
At some point I turned a setting that hides the top toolbar, but now I cannot find anywhere in the interface an option to restore it.
![Screenshot from 2022-09-09 19-59-10](https://user-images.githubusercontent.com/1270531/189464686-548533c6-c3a9-4d6b-bd2d-dbb3138da8a2.png)

**Comment by adrihut** [comment]
Try **`Alt`+`M`** — _that's the kb shortcut for hiding and displaying the unthemed menu bar_.

![Standard Note's View options in the unthemed menu bar](https://user-images.githubusercontent.com/91064300/191273730-c3ad3eb4-2444-43e5-ac86-6197885eec20.png)

**Comment by cedewey** [comment]
Alt+M is exactly what I needed. Thanks!
