### ISSUE TITLE
Average note takers & saving images? 

### ISSUE THREAD

**Issue by Moab762** [standardnotes/forum#1683]
I'm an average note taker. I keep lists. I save research. I write down ideas. And sometimes I write creatively. I am not a programmer or computer professional of any kind.

I use a note taking app (Standard Notes. I used to use Evernote.) to hold all of the above. There are so many things to love about Standard Notes. Security, ease of use, its open source and never forgets how to sync.

For me its the simplicity and speed. No lag. My notes are always saved between my phone and computer. And its easy to use for keeping track of text notes.

But I do miss the ability to save images in my notes. 

What paid level do I need to get the ability to save images in my notes?

Secondly, why is this note taking app so complicated? And why is it so hard to figure out if I can save images with my text?

If you were an "average note taker" I think you would find the homepage of this app very confusing. And the list of features.

Why do I have to learn a computer language to use what is basically a text note taking app? Every capability listed appears to require a computer language. Again, to the "average note taker".

Isn't the vast majority of your possible app buying public the "average note taker"? If so, why are you trying so hard to make your note taking app sound like its so very hard to use? Why can't I easily figure out whether I can use images in my notes? Isn't that the logical next tiny step up from a text note? Whether or not you can include images in your notes?

I don't think you have a product problem. After some way to difficult research. I discovered how superior Standard Notes is. I think you have a marketing and communication problem. 

You make this app sound way to complicated to understand how to use. And you can't seem to communicate - simply -  what sets it apart from other apps in this category. 

I don't say all this to put Standard Notes down. I say this because I love this app. And I literally tried them all. I say this because you obviously know how to make a great app. But I think your doing the app a disservice by not clearly communicating with your core user or core buyer of a note taking app - why its better and how easy it is to use.

People don't use note taking apps to complicate their lives. They use them to make life easier. 

And right now you're making it really hard for people to figure out how much Standard Notes makes life easier.

**Comment by myreli** [comment]
Hi @Moab762, 

Firstly I'm sorry for the late reply. I'm currently triaging older issues and came across your report just now. 

Your feedback is greatly appreciated as are your kind words about the app. I'm glad you love Standard Notes and enjoy its reliability! I would like to point out that Standard Notes is now actively trying to improve its communication both on Social Media and the website and help pages. 

One of Standard Notes' key differences is its multi-note-type and editors architecture, which while enabling unique abilities to offer sandboxed apps within standard notes (like the Authenticator feature), has been a source of confusion. There is now a specific page detailing how this works and why it's like this, as well as a walkthrough video that displays all editors and their features: https://standardnotes.com/help/77/what-are-editors. Let us know what you think! 

Now addressing your question directly, 
> Whether or not you can include images in your notes?

Yes, you can. Not only images but any kind of file. The best choice is the [Professional Plan](https://standardnotes.com/plans), with 100GB of storage. Here's an example:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/17554234/221367488-f90de03d-15be-4d82-9799-592bdc6de32a.png">

This is possible through the Super note type available on any of the paid plans. Attachments count towards your storage quota, which is 10MB for the Productivity plan and 100GB for the Professional plan. This should now be clearer on the [pricing](https://standardnotes.com/plans) page. You can select the note type through the menu
<img width="841" alt="image" src="https://user-images.githubusercontent.com/17554234/221367555-97b54f39-69b1-42af-8e4d-ee91e62b6e95.png">

Historically attaching files in notes wasn't possible in a simple way, but in the past year, the Files feature and specifically its integration within notes has been greatly improved. 

I hope this answer still works for you, and I will forward your feedback to the SN Team. Thanks!
