### ISSUE TITLE
Add a search inside notes (Issue #1183)

### ISSUE THREAD

**Issue by rajeshisnepali** [standardnotes/forum#1684]
Old issue at [https://github.com/standardnotes/app/issues/1183](https://github.com/standardnotes/app/issues/1183) got deleted. 

Feature: Ability to search inside a note.

**Comment by marosg42** [comment]
+100

**Comment by Universal-Igloo** [comment]
+100 more. This is a very basic feature and makes it hard to use Standard notes without it.

E.g. I search for "umbrella" all my notes with the word show up, I choose the right one, and then am just left scrolling indefinitely and manually searching for one word in a 1000 word note. Impossible!

**Comment by effieeee** [comment]
Hi @rajeshisnepali, you'll find that we've now moved the App repo issues here into the Forum! We're currently making an effort to clean up and sort the many open issues and tickets at the moment, so I hope you bear with us on this effort 🙏I'll be closing this as a duplicate, and this feature request will continue to be tracked on the issue link you provided above!
