### ISSUE TITLE
MacOS context menu doesn't go away (Mac M1) 

### ISSUE THREAD

**Issue by levjoy** [standardnotes/forum#1685]
**Describe the bug**
After bringing up the context menu (two-finger click on my trackpad) I can't get it to go away. Clicking escape or any other key doesn nothing. 

**To Reproduce**
1. Open context menu with trackpad or mouse 
2. Try to remove context menu with "escape" key 
3. Menu doesn't disappear 

**Expected behavior**
Menu should hide after hitting "escape" 

**Desktop (please complete the following information):**
 - OS: MacOS 12.5
 - Desktop app 
 - Version 3.2.135

**Additional context**
This is using an M1 Macbook Pro, with the Mac Arm version installed.

**Comment by myreli** [comment]
Can't replicate with the recent versions of macOS and Standard Notes. Please, feel free to re-open the issue in case you still face this problem.
