### ISSUE TITLE
Desktop App (Mac OS) keeps logging out despite multiple re-logins

### ISSUE THREAD

**Issue by IssuesPlease** [standardnotes/forum#1686]
**Describe the bug**
After logging into the desktop app successfully, within a few minutes Standard Notes logs me out, presenting me again with the login popup. I haven't changed any other parameters of Standard Notes.

**To Reproduce**
1. Log into account
2. Wait about 30-seconds
3. See popup, "Please enter your account email and password."

**Expected behavior**
After logging into my account, I expect to remain logged in until either I close out of my account OR the standard log-in limit is reached. This limit used to be about three days. Now, it's about 30-secondss.

**Desktop (please complete the following information):**
 - Mac OS 10.15.7

**Additional context**
If this is an issue with my version of Mac OS, I'd like to know. I do not want to update to Mac's latest OS and would have to find either a new way to access Standard Notes or use another note service. Thanks...

**Comment by myreli** [comment]
Hi @IssuesPlease! I'm triaging older issues, sorry for the late reply. Do you still have this problem?
