### ISSUE TITLE
It takes 2 to 4 attempts for standard notes android app to open after I switched to the new web view.

### ISSUE THREAD

**Issue by Sandbox8888** [standardnotes/forum#1690]
**Describe the bug**
It takes 2 to 4 attempts for standard notes android app to open after I switched to the new web view. The first 2 to 4 times when I open Standard Notes android app, only blank white page is displayed. I have to close it and then open it again a few times for notes to display.

**To Reproduce**
1. Open Standard Notes Android App
2. Blank White page is displayed.
3. Close the app.
4. Open it again.

**Expected behavior**
I expected Standard Notes android app to open on the first time I clicked the icon.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: POCO M2 Pro
 - OS: Android 11 (MIUI 12.5.6)
 - Browser: stock browser.
 - Version 3.35.12

**Additional context**

**Comment by catwithbanana** [comment]
I am encountering the same issue -- Pixel 5 on Android 12.

**Comment by Sandbox8888** [comment]
I assume this bug was solved. I have not encountered this bug for the past 10 days.
