### ISSUE TITLE
Web interface not cleared after sign out

### ISSUE THREAD

**Issue by Matei59** [standardnotes/forum#1693]
Hello, I use SN web client (Pro account) from Chrome 105.0.5195.127 (incognito mode, Win10 x64) -- when I click the Sign out workspace or Switch workspace / Sign out all workspaces, the system seems to log me out, but all the notes are kept in the browser, i.e. the web interface is still plainly visible in the browser. 

The bottom left icon is red and soon a pop-up window appears asking for password -- so it seems the log-out operation is performed, but the web interface is not reinitialized to a blank account. 

This behavior appeared 4 or 5 days ago -- before Friday 2022-09-23, the behavior of the web interface was correct (as expected) -- logging out was also clearing the web interface. 

Kind request:  Would it be possible to restore the old behavior? 
The current behavior seems to create a security/privacy issue -- when someone logs out from a system, the user data is not supposed to be still visible in plain sight.

**Describe the bug**
Web interface is not cleared after log out.

**To Reproduce**
1. Log in to SN web from browse
2. Click Sign out 
3. Observe all notes still visible in browser

**Expected behavior**
After sign out, the web interface should be blank, without any user data.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser:  Chrome
 - Version: 105.0.5195.127

**Additional info**
My SN account is configured to a dark theme. The default web client has a white theme (before logging in). When I log in, the web interfaces switches correctly to dark. When I click sign out, the web interface switches back to the default white, but all my notes are still plainly visible, as explained above. 
 
**Suggestion**
It would be nice to have a single click Sign out button in the web interface. At present the user needs 2 or 3 clicks to log out.

**Comment by effieeee** [comment]
Hi @Matei59, may I ask if you still experience this on the web app until now, and does [clearing the site data](https://docs.standardnotes.com/troubleshooting/reset-apps/#web) help restore the expected behavior after signing out?

**Comment by Matei59** [comment]
Hello, thank you for the feedback. 
The reported issue disappeared by itself one or two days after reporting the issue here on the forum. 
No changes were done by me on the local system or in SN. 
The previous (correct) behavior was restored "by itself", i.e. after sign out, the web interface is cleared of personal data.
I did not have to do any of the steps listed in the "How do I reset the app?" page -- please note that I use SN from an incognito Chrome window, so I assume that everything is removed anyway after I close the web browser.
My assumption was (is) that SN Team fixed the issue and forgot to write here on the forum :)
In any case, the issue can be closed now, the web app is working as expected.
Many thanks for your support!
