### ISSUE TITLE
No tags below note title?

### ISSUE THREAD

**Issue by quirkyheadband** [standardnotes/forum#1694]
I'm really dismayed to see that the tags are no longer visible or editable under the note title in the right hand column.

I rely heavily on tags to organize my notes, and I found this to be the easiest way to add and remove tags. Right clicking on the note in the middle column and scrolling through my hundred+ tags is clunky and slow.

☹️

**Comment by mcastril** [comment]
I agree. I was used to typing the note title add tags without moving my hands from the keyboard. I am struggling to find a quick way to do it... I cannot believe that the only way is using the mouse...

**Comment by amanharwara** [comment]
This is a bug. Should be fixed soon.

**Comment by mcastril** [comment]
It seems that it's fixed now. Thank you!
