### ISSUE TITLE
Updated version won't open on Android 7.0

### ISSUE THREAD

**Issue by MrIntuition** [standardnotes/forum#17]
Have deleted data, cache and the program and updated with 1.4. I sign in and it takes me to the settings screen. When I try to use the program, it blinks. I'm using an LG G6. I have no such issues with the Mac or the Web app.  Please advise.

**Comment by mobitar** [comment]
What do you mean by it blinks? Does it just crash and return to your home screen?

**Comment by MrIntuition** [comment]
Thanks for your quick response! I touch the icon and the screen blinks but it doesn't open. It's so fast that I wouldn't describe it as a crash but maybe I'm not experienced with such problems. Obviously, I cannot get into the app. I've reinstalled it three times now.

**Comment by mobitar** [comment]
Can you try this APK and see if it fixes the issue? I was able to replicate the issue where an invalid email can result in a crash. 

https://github.com/standardnotes/android/releases/download/1.4.1/app-normal-release.apk

**Comment by MrIntuition** [comment]
Installed it. Same problem. The email I use for Standard Notes is different from my phone's email. Might that be the problem?

**Comment by mobitar** [comment]
Can you try deleting the existing app first, and all associated data, and try installing this from scratch? If that still doesn't work, email me with the email associated with your account: mo@standardnotes.org.
