### ISSUE TITLE
Bug: HTML code in notes list instead of rendered text.

### ISSUE THREAD

**Issue by bdfn31n** [standardnotes/forum#170]
Description: When I use the Plus Editor, the first sentence of the note is shown as piece of code, however I expect to see the actual first sentence.

Environment: SN 2.2.1 on Ubuntu 17.10

Steps:

1) Choose Editor
2) Copy-Paste any web page (see screenshot attached)

![screenshot_2018-03-01_17-59-00](https://user-images.githubusercontent.com/36960791/36851532-54849682-1d61-11e8-8598-4ac874d89a81.png)

**Comment by mobitar** [comment]
This is a known limitation. There is a discussion on this somewhere in one of the repos, but I can't seem to find it :/ tl;dr: probably no solution for the foreseeable future.

**Comment by bdfn31n** [comment]
OK, thank you
