### ISSUE TITLE
Unencrypted images from my notes are stored in Cache folder

### ISSUE THREAD

**Issue by bdfn31n** [standardnotes/forum#171]
Description: I expect my notes data to be encrypted. I even use Passcode Lock to be sure that if anybody get access to my session on PC, the notes will not be available. I want to use SN for saving web content mostly, but now I see that image from my test page is stored locally unencrypted and accessible with file manager.  I consider it an important privacy issue.

Environment: SN 2.2.1 on Ubuntu 17.10, Plus Editor

Steps:
    
1. Choose Plus Editor
2. Copy-Paste any web page with images 
3. Open ~/.config/Standard Notes/Cache folder

![screenshot_2018-03-01_18-12-26](https://user-images.githubusercontent.com/36960791/36852176-fc16c48c-1d62-11e8-9192-1bb33b834afc.png)

![selection_001](https://user-images.githubusercontent.com/36960791/36852122-e5717a92-1d62-11e8-9e6d-b2505ab9b89c.png)

**Comment by mobitar** [comment]
Images are not supported in SN, anywhere. You should see an alert when you try to upload an image with the Plus Editor. See this unfortunately named [reddit thread](https://www.reddit.com/r/StandardNotes/comments/7xkgij/buyer_beware/) for more.

**Comment by bdfn31n** [comment]
Oh, that's a surprise for me, does it mean that if I save the note with images in Plus Editor on PC, the images won't be shown on Android?

**Comment by mobitar** [comment]
Not only will they not show up on Android, they won't show up when you refresh the desktop/web app. Like I said, images are not supported anywhere.

**Comment by bdfn31n** [comment]
Sorry to hear it. I think it would be great if SN provided a kind of free trial with all features. I played about 2 hours with full version to find out that it's not usable for my purposes - keeping  defect reports with screenshots and links in a secure manner for the projects I do QA audits for. Also it would be great if such limitations were shown in one place on the site before buying - SN is an app for storing ONLY text notes, and extensions are not supported on any mobile devices.

**Comment by mobitar** [comment]
There's a few places this is mentioned:

1. https://standardnotes.org/extensions: "Available on Web and Desktop with Extended."
2. https://standardnotes.org/help/12/why-are-extensions-not-available-on-the-mobile-app
3. https://standardnotes.org/longevity
4. https://standardnotes.org/help/9/is-standard-notes-a-good-evernote-alternative

But, I agree that it can't be expected that everyone read these posts. I don't know how else to communicate it though. If you know of a good place, which you crossed paths with, let me know.

**Comment by bdfn31n** [comment]
I see the point, and the most suitable option would be the free trial of full version in my opinion. Anyway, I appreciate your honesty and desire to help. Unfortunately, I will have to find an alternative to SN and won't use the extended features, so consider my year subscription as a donation to your really cool app. After the year I won't be charged automatically, right? The subscription will just expire?

**Comment by mobitar** [comment]
Thanks :) You can cancel it now to turn off auto-renew. It will remain active for the time you paid for.

**Comment by bdfn31n** [comment]
Great, thank you.
