### ISSUE TITLE
Crash When Typing on New Note

### ISSUE THREAD

**Issue by denizonm** [standardnotes/forum#1710]
The Android app crashes when attempting to write on a new note. Crashes consistently, before even the first letter is rendered.

Typing into old and non-empty notes does not crash it.

GrapheneOS on a Pixel 4. GrapheneOS is essentially stock Android 12 with security and privacy improvements.

Up to date F-Droid version

**Comment by myreli** [comment]
Hi @denizonm, are you still experiencing this problem? 

Since the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) launched last year the mobile app has changed consistently and most of those problems should have been solved.
