### ISSUE TITLE
Anyone can access files attached to a protected note without entering a passcode

### ISSUE THREAD

**Issue by avt00** [standardnotes/forum#1718]
I am currently subscribed to a paid plan on StandardNotes, which includes file storage integrated into the application. As far as I know, any information stored within a protected note should be inaccessible if the appropriate protections are enabled.

However, in the current version of the application, it appears that files attached to protected notes can be accessed by anyone through the Files -> All Files dropdown menu. This presents a significant security vulnerability that needs to be addressed.

**Comment by myreli** [comment]
Duplicate: https://github.com/standardnotes/forum/discussions/2849
