### ISSUE TITLE
Advanced Markdown Editor toolbar background is high contrast when toggling preview mode

### ISSUE THREAD

**Issue by scottwernervt** [standardnotes/forum#173]
**Bug**

Toggling Preview Mode will set the toolbar background to high contrast when using Advanced Markdown Editor with _any theme_.

![standardnotes-advanced-markdown-editor-toolbar-preview-theme](https://user-images.githubusercontent.com/1048949/36911585-f936cda2-1e11-11e8-848d-fb6067226905.gif)

I can repeat the issue with the standalone app 2.1.1 and Firefox Quantum 58.0.2 (64-bit).

**Instructions**

1. Extensions > Themes > Activate `Midnight Theme`
1. Editor > `Advanced Markdown Editor`
1. Click `Toggle Preview` or `Ctrl+P`

**Comment by mobitar** [comment]
Good catch, can replicate this. Added to my todo.

**Comment by TheodoreChu** [comment]
I'm closing this issue because it seems to be resolved. Please comment if you have anymore issues
