### ISSUE TITLE
Edge detects Windows installer as a Virus

### ISSUE THREAD

**Issue by M-Pixel** [standardnotes/forum#174]
The Windows installer contains something that the Edge browser detects as a virus, so it is automatically deleted as soon as it finishes downloading.

**Comment by mobitar** [comment]
It's not that it contains something, it's that SN isn't "popular enough" to be trusted. These issues go away with more volume. Nothing more we can really do about it..

**Comment by scottwernervt** [comment]
[Virus Total](https://www.virustotal.com/#/file/d780255b44ddbd742518e366af7150120b7abb99684e4af6088fdd819cbf2fe9/detection) reports the installer clean and the executable is digitally signed with a certificate [digitally signed](https://www.virustotal.com/#/file/d780255b44ddbd742518e366af7150120b7abb99684e4af6088fdd819cbf2fe9/details).

**Comment by TheodoreChu** [comment]
Update: the Windows application is signed with [Digicert Extended Validation Certificate](https://www.digicert.com/code-signing/ev-code-signing/) as discussed here: https://standardnotes.org/help/52/what-services-does-standard-notes-use-for-daily-operation
