### ISSUE TITLE
MacOS, app crashes when right click on a note

### ISSUE THREAD

**Issue by pinpontitit** [standardnotes/forum#1748]
Found a bug today on the MacOs App, downloaded from the Apple store:

When I left click on a note, the note appears on the right side of the app, in the "preview" panel I'dd call it.

If then, I "right click" on the text or anywhere in this panel, the app crashes and closes.

Thanks

**Comment by myreli** [comment]
It seems like this issue has been fixed in recent versions, so I'll close it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
