### ISSUE TITLE
Scrollbar is duplicated in the Backups menu in Preferences

### ISSUE THREAD

**Issue by CarnageDevs** [standardnotes/forum#1749]
On the latest update (3.23.61), the scrollbar is duplicated when viewing the Backups menu in preferences, showing both the native and custom scrollbar:

![image](https://user-images.githubusercontent.com/17109829/178705933-4946c84b-d974-4cf6-9403-3f1747d3d3ab.png)

**Comment by myreli** [comment]
It seems like this issue has been fixed on recent versions, so I'll close it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
