### ISSUE TITLE
Plain Editor behaviour

### ISSUE THREAD

**Issue by foorb** [standardnotes/forum#175]
Hi,
I am not sure if this is a bug or feature:

![kapture 2018-03-04 at 12 23 33](https://user-images.githubusercontent.com/14993807/36944987-019c235c-1fa7-11e8-9385-e4ab1eb08cc1.gif)

If it is a feature, what is it doing?

regards

**Comment by mobitar** [comment]
Yup, it's a feature :) See here: https://github.com/standardnotes/forum/issues/162#issuecomment-366274453

**Comment by foorb** [comment]
Ah ok
