### ISSUE TITLE
[iOS] Basic Checklist - Note list show/hide arrow blocks checkbox

### ISSUE THREAD

**Issue by Toska-04** [standardnotes/forum#1755]
Hello

On the iPad iOS Basic Checklist editor, the arrow that shows or hides the note list often is above the checkbox that's approximately at the midway point, making it difficult to check or move that item without changing the screen orientation.

Thanks!

**Comment by myreli** [comment]
Hi @Toska-04! Are you still experiencing this issue since the new mobile experience?
