### ISSUE TITLE
Feature Requests: Markdown toggle rightklick

### ISSUE THREAD

**Issue by foorb** [standardnotes/forum#176]
Hi,
Boostnote has a nice feature. Toggle Markdown on rightklick.

![kapture 2018-03-04 at 12 49 41](https://user-images.githubusercontent.com/14993807/36945189-cffa4e92-1faa-11e8-8d1e-52bead89cb2d.gif)

I really like the simple markdown editor but I don't need a toolbar or live preview. Here It would be cool, to toggle between preview and edit mode, instead of showing it on the right side. Maybe this could be an additional option in simple markdown editor?

Best regards

**Comment by mobitar** [comment]
What about resizing the middle column in simple markdown editor to hide/show the preview. Not as direct as one click, but pretty close to it, no? Or you can try the minimal markdown editor, which will render in place.

**Comment by foorb** [comment]
I often jump in my notes to just copy & paste a snippet and only need the markdown preview. Sliding the preview would be an option, but the position is not saved. Also it doesn't look really well:

![bildschirmfoto 2018-03-05 um 18 11 01](https://user-images.githubusercontent.com/14993807/36989212-5901dd12-20a1-11e8-8c8a-62b1fa4255bc.png)



In minimal markdown editor is still a problem:
https://github.com/sn-extensions/minimal-markdown-editor/issues/1

**Comment by mobitar** [comment]
Ah ok. Perhaps we can make the resizer column double-clickable to completely hide the split.

**Comment by foorb** [comment]
Sounds good

**Comment by mobitar** [comment]
Check out the Fancy Markdown Editor, which offers full collapsibility: https://standardnotes.org/extensions/fancy-markdown-editor

**Comment by foorb** [comment]
Its very hard to collapse because if the mouse is too far left you confirm by clicking.

**Comment by foorb** [comment]
Also simplenote feels smoother:

![kapture 2018-03-15 at 22 45 51](https://user-images.githubusercontent.com/14993807/37492743-c68821b2-28a2-11e8-8123-3f43756576cd.gif)

I liked the simplicity of simple / minimal markdown editor, but maybe I should get used to the advanced markdown editor. Is there a way to save the preview? So when I open notes its always preview mode?

Can you also explain me what the fullscreen button does in advanced markdown editor?

Is there a way to add custom css to an extension?

Sorry for the many different questions 🙈

**Comment by mobitar** [comment]
There's no way to keep it in preview mode.

The fullscreen button is just part of the interface, and not used by SN. (The editor is an open-source component not developed by us.)

You can use your own CSS if you host your own extension. That's a different story though. https://docs.standardnotes.org.

**Comment by ccmpbll** [comment]
I too would like to see the option for enabling preview by default. No idea how difficult it would be, but I think it would be a great feature.

**Comment by mobitar** [comment]
What about an editor extension called Markdown Preview, that just offers preview with no input option. Would that be useful, and if so, why?

**Comment by ccmpbll** [comment]
For myself, I want to see the pretty, rendered Markdown. It's why I chose to do all my notes in Markdown in the first place, even before I started using Standard Notes. I use it as a documentation repository, not just for simple note taking. I use it for storing procedures or keeping track of how I did something that I only have to do infrequently. I also frequently make use of markdown tables to store information that looks much better when rendered. I'm sure not everyone uses it this way and I know you can't please everyone that uses the product. 

Seeing the image @foorb posted made me go take a look at how Simplenote implements this and it is indeed nice. It defaults to the preview, but a simple click shows you the raw markdown for you to edit. 
The solution of the new preview-only editor would work, but it would be nice to have the option to show the rendered markdown first, with the ability to edit just a click away. Could, for instance, the Advanced Markdown Editor be modified to allow something like this?

Thanks for a great product and sorry for the long-winded response!

**Comment by mobitar** [comment]
Hmm..that's an interesting idea. I think this would be easy enough to build into the Simple Markdown Editor. We could have two modes: split and full. Full would default to preview, but would edit on click. I'll add this to my (mental) backlog and hopefully get an easy day to work on this.

**Comment by foorb** [comment]
Sounds great, will you use rightklick here? I use my notes often for snippets, bash oneliner, etc and when mark for copy with the left mouse button the toggle would be bad.

**Comment by mobitar** [comment]
Not too sure yet about the implementation, but I'm sure we can find a good solution.

**Comment by ccmpbll** [comment]
I'm looking forward to seeing what you come up with. If you need someone to test, I will gladly volunteer!

**Comment by mobitar** [comment]
Simple Markdown Editor update now has the option for different modes:

<img width="709" alt="simple markdown editor" src="https://user-images.githubusercontent.com/3277844/41510730-2c6a8f1c-722f-11e8-833e-68f17ec0c498.png">

**Comment by foorb** [comment]
great, thank you!

**Comment by ccmpbll** [comment]
This is great, thank you! However, it seems to be a bit off the screen at the bottom of the window on iOS, and when I try to choose one of the three selections, the app crashes. 

Thanks for all your hard work!

**Comment by mobitar** [comment]
Yeah sorry, the fix for this has been uploaded to the App Store, currently waiting for review.

**Comment by marc-odp** [comment]
Hi. I am discovering Standard Notes and just registered the extended edition. I reached this page because I was wondering how I could keep the Advanced Markdown Editor in Preview mode... As I understand after reading the messages here, I can't.
However, you edited and created that option for the Simple Markdown Editor and it works great. What is preventing you from doing the same for the Advanced one ? It is really missing. Seriously. :-(

**Comment by mobitar** [comment]
Hey @marc-odp, I'll revisit persisting state for the Advanced MD Editor. The Simple MD Editor is built by us so we have more control over it. But I'll create a developer bounty for the task of remembering state in the Advanced editor.

**Comment by marc-odp** [comment]
@mobistar, Thanks. I noticed today that Advanced and Simple MD Editor show things differently. For example, Simple MD Editor put color in code, not the Advanced one. (```pascal) So, yours is better. :-)
