### ISSUE TITLE
Docker image hosted on ghcr.io

### ISSUE THREAD

**Issue by ptpu** [standardnotes/forum#1763]
It would be great if it could provide a ready-built Docker image in the future. This only requires the use of GitHub Actions. This image can then be stored in the GitHub Container Registry for each release.

**Comment by ptpu** [comment]
Perhaps this is the equivalent [image](https://hub.docker.com/r/standardnotes/web). However, this is not sufficiently documented.

**Comment by atmoio** [comment]
Documented here: https://github.com/standardnotes/app/blob/main/README.md#docker-setup
