### ISSUE TITLE
Feature request: password for individual notes

### ISSUE THREAD

**Issue by smikmiks** [standardnotes/forum#177]
Would be much welcomed.
If you have some extra private notes, currently these are quite exposed once you have your desktop client open and logged in.

**Comment by mobitar** [comment]
Definitely, this is something on my mind. Also, sent this to you via email:

Password protecting individual notes is an increasingly popular request, and is something I have been thinking about as well. Most likely, it will come in the form of some sort of extension, like a “Vault” in which you can put super sensitive stuff.

The only thing holding me back is mobile access. Extensions are not available on mobile, so you would only see the raw encrypted text on mobile. I imagine mobile access would be important as well?

**Comment by smikmiks** [comment]
Oh, and I also replied via mail, may be of interest to others:

Glad to hear it’s on the maybe-plate :)
Actually, I don’t think mobile access is absolutely imperative in this case since you have the ‘require immediately’ option for passcode/fingerprint. Does it for me, anyway :)

**Comment by smikmiks** [comment]
Alternatively, one could have a settings option to automatically log out after a certain amount of time, like LastPass has. 
(Just an idea, have no clue whether it's feasible!)

**Comment by mobitar** [comment]
You can also set up a Local Passcode on the desktop app, and then lock it immediately using the Lock button in the bottom right corner.

**Comment by smikmiks** [comment]
I know, but that would mean you actually had to be mindful of what you’re doing :)
A ”vault” option would definitely be the best solution in my view.

**Comment by TheodoreChu** [comment]
I'm closing this issue because the feature is available as "Protected Note": https://standardnotes.org/help/54/what-does-it-mean-to-lock-or-protect-a-note. Feel free to comment if you have anymore issues.
