### ISSUE TITLE
Unable to open on Android 11

### ISSUE THREAD

**Issue by ordtrogen** [standardnotes/forum#1773]
Phone: OnePlus 7Pro
Android version: 11
Oxygen OS 11.0.7.1.GM21AA

StandardNotes version 3.23.8

When I click on the icon to start the app, an opening animation is displayed but the app never shows.
I can see it in the task list but when I try to activate it, phone says "Standard Notes crashes repeatedly"

I'd be happy to submit some kind of system log, if somebody could provide me with instructions for how to find it on the phone.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
