### ISSUE TITLE
Dark mode as a free feature?

### ISSUE THREAD

**Issue by ezxpro** [standardnotes/forum#1777]
I'm actually a paying notion user and I just began exploring alternatives where I can move my sensitive data. I used www.alternativeto.net to find what looks like notion that possibly has E2EE. Standard notes pops up as the best candidate, apparently.

The problem, I downloaded it 1 hour ago and it already hurts my eyes to look into this interface. I saw you have a config for dark mode under Appearance > Use system color scheme, but it's a premium feature.

No one is offering dark mode as a premium feature anywhere, not that I know at least. Nowadays that's a basic feature of anything you expect people to be staring at for some time.

**Comment by ezxpro** [comment]
@Nicicalu Gosh, I uninstalled this already.
Went back to Joplin. 3 minutes to set up e2ee and my own cloud sync.

And it has a dark mode.

**Comment by ezxpro** [comment]
> > @Nicicalu Gosh, I uninstalled this already.
> 
> Yeah, well then why do you expect it to be free? They need to make money somehow...

You are projecting your own thoughts here. I didn't say a word for or against it them making money.

To clarify things a little bit, i was just testing this app. 

It's pricing model is out of line with competitors (Notion pro =$5, Enterprise= $25) and in its free version it's basically a text editor with cloud sync and encryption.

This drove me right away. 
That's okay, life moves on for both sides.

**Comment by shompoe** [comment]
The mobile app has a built in dark theme for free users. And you can install a custom theme for free to use on any platform. Search for the awesomestandardnotes repository on GitHub for some community themes or make your own. Be aware though that not all the themes in that repository are being maintained.

**Comment by julianfairfax** [comment]
> The mobile app has a built in dark theme for free users. And you can install a custom theme for free to use on any platform. Search for the awesomestandardnotes repository on GitHub for some community themes or make your own. Be aware though that not all the themes in that repository are being maintained.

Are there any themes that actually are being maintained? It seems most of the entries in the awesome repo are all unmaintained.

**Comment by ezxpro** [comment]
> > The mobile app has a built in dark theme for free users. And you can install a custom theme for free to use on any platform. Search for the awesomestandardnotes repository on GitHub for some community themes or make your own. Be aware though that not all the themes in that repository are being maintained.
> 
> Are there any themes that actually are being maintained? It seems most of the entries in the awesome repo are all unmaintained.

I think for standard notes you either pay or you move on.
Free version is basically a text editor with cloud synchronization. There are better alternatives out there if you dont want to buy standard notes.

**Comment by julianfairfax** [comment]
> > > The mobile app has a built in dark theme for free users. And you can install a custom theme for free to use on any platform. Search for the awesomestandardnotes repository on GitHub for some community themes or make your own. Be aware though that not all the themes in that repository are being maintained.
> > 
> > 
> > Are there any themes that actually are being maintained? It seems most of the entries in the awesome repo are all unmaintained.
> 
> I think for standard notes you either pay or you move on. Free version is basically a text editor with cloud synchronization. There are better alternatives out there if you dont want to buy standard notes.

I use https://github.com/arturolinares/sn-rme but I had to modify the package file to install it due to standardnotes/forum#1779 and it doesn't work in dark mode (this is not Standard Notes' fault though). Also of course long load times standardnotes/forum#1797 for both the app and the editor.

I tried self-hosting locally but that doesn't work either because of standardnotes/forum#1775. So it seems I'd have to pay for it if I wanted any maintained editors or themes. Alternatives aren't better either, I've tried them.

**Comment by shompoe** [comment]
I overhauled my theme recently but the white in the left hand pane which has come back again since I last did this still persists. This is because the current version of SN doesn't properly support custom themes. I confirmed this with support and they said it got hard coded as part of a fix for something. My theme is up to date with the latest specification and I am just waiting for it to start working as soon as they resolve that.

So even if they are maintained they won't work anyway.

--- 
Mark Desrousseaux



10 Aug 2022, 15:54 by ***@***.***:

**Comment by shompoe** [comment]
The devs have said that they plan to implement a free dark theme in the future. In the meantime you are welcome to use a custom theme developed by the community which does not require a subscription. There is however a little bug at present which means the selected view/tag background is always white when using custom themes.

https://github.com/jonhadfield/awesome-standard-notes

This is a good starting place but I don't know how many themes here are still maintained.

--- 
Mark Desrousseaux



29 Sept 2022, 16:24 by ***@***.***:

**Comment by myreli** [comment]
Standard Notes now offers a free Dark theme on all platforms. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
