### ISSUE TITLE
Feature Request : Display option on mobile

### ISSUE THREAD

**Issue by antoineschmitt** [standardnotes/forum#178]
On mobile, in a Tag, the notes are displayed with: title, tags, preview and date.
This is cumbersome.
It would be nice to be able to change the display settings like in the desktop app.
Thanks

**Comment by mobitar** [comment]
This is a possibility in the near future.

**Comment by TheodoreChu** [comment]
I'm closing this issue because it's available in the latest mobile apps (v3.5+). Please comment if you have any issues.
