### ISSUE TITLE
Weird strings behavior

### ISSUE THREAD

**Issue by gdonisi** [standardnotes/forum#1785]
One word strings are truncated to the last letter, multiple word strings don't have the final word. As shown in the video, it doesn't just happen with note titles.

<details>
<summary>Device info</summary>

Brand and model: Xiaomi Mi 9T
Android version: 12
OS: custom ROM ArrowOS 12.1
App version: 3.24.4 (updated from GitHub releases when I noticed this bug on the Play Store version)

</details>

https://user-images.githubusercontent.com/82442402/175598980-4837841b-727a-4514-a978-0370968edc0d.mp4

**Comment by atmoio** [comment]
Hmm, I can't replicate this. Can you see if it's reproducible using 3.25.11? https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fmobile%403.25.11

**Comment by gdonisi** [comment]
Yes, the bug is still there in v3.25.11

**Comment by atmoio** [comment]
Ah so the actual note contents are preserved, it's just the display is truncating the characters right? I've seen this issue before on OnePlus phones.

**Comment by gdonisi** [comment]
Exactly, note contents are fine. Note titles and some of the app strings are affected, e.g.
"Archive" -> "Archiv"
"Move to Trash" -> "Move to"

**Comment by atmoio** [comment]
Can you try disabling your global Accessibility > Text and display > Bold text option if you have that enabled, and see if that affects it?

Related issues:
- https://github.com/facebook/react-native/issues/25481
- https://github.com/facebook/react-native/issues/15114

**Comment by gdonisi** [comment]
The option is already disabled. I restored the custom ROM default font just to try, but it didn't work.

EDIT: I deleted app cache after changing font and the issue is gone.
