### ISSUE TITLE
F-Droid version not pulling from this repo.

### ISSUE THREAD

**Issue by ScalableCodex** [standardnotes/forum#1788]
Just the title. Will the F-Droid version get fixed?

**Comment by atmoio** [comment]
@proletarius101 heads up that mobile releases are now tagged in the `app` repo: https://github.com/standardnotes/app/releases

Tag names are of the form `@standardnotes/mobile@3.25.11`

The `mobile` repo has been archived and is no longer used.

**Comment by ScalableCodex** [comment]
I don't really understand. I'm still new to github. So the F-Droid version no longer will get updates?

**Comment by atmoio** [comment]
Sorry I was tagging a maintainer/contributor on the Fdroid repo on the changes required to get SN to update again.

**Comment by ScalableCodex** [comment]
Oh sorry! See I'm not very smart haha. Thanks!

**Comment by proletarius101** [comment]
Track https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11268 for the progress

**Comment by proletarius101** [comment]
I'm confused why there are so many Google classes involved: https://gitlab.com/proletarius101/fdroiddata/-/jobs/2670667529#L1656. I can't find any references in the code. Do you have any hints? @moughxyz 

---

OK. It's `react-native-store-review`. Patched out.

**Comment by proletarius101** [comment]
Done. Waiting for the f-droid build server to build

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
