### ISSUE TITLE
Two factor authentication?

### ISSUE THREAD

**Issue by automine** [standardnotes/forum#18]
It would be nice if some sort of 2FA was supported. I don't think I've seen that in other issues. Thanks!

**Comment by mobitar** [comment]
I agree, that would be nice. Hopefully we can get to that soon.

**Comment by TheodoreChu** [comment]
Update: two-factor authentication is supported as described here: https://standardnotes.org/help/25/how-do-i-enable-two-factor-authentication-for-my-account
