### ISSUE TITLE
Logged out on browser close

### ISSUE THREAD

**Issue by SynapseScribe** [standardnotes/forum#1806]
With the most recent changes on the web app, i am being logged out whenever i close the browser. While this might improve security, it greatly breaks usability.

For example I have set up a very strong password + 2fa + Passcode lock, and I normally should only enter the passcode (which i do automatically through keepassXC), but instead I need to relogin with password + 2fa and set up passcode again (which gets cleared)  upon browser restart. This behavior was introduced in the last few weeks.

![image](https://user-images.githubusercontent.com/7840350/170944082-2ff8f466-f90d-4f66-8ff7-af547e7f298f.png)

Note: I checked all my browser settings + extensions, and none of them trigger this cookie deletion, but the cookie itself is set to expire on session end, as seen in the picture above

**Comment by atmoio** [comment]
This is not to do with us. We don't use cookies for session persistence. Try using a different browser and see if you get different results. Make sure "Stay signed in" is checked.

(Also you should be using app.standardnotes.com. Shouldn't make a difference, but just the more canonical link.)

**Comment by SynapseScribe** [comment]
i tried in firefox, and apparently cleaning cookies or active logins do not log me out. What it does instead, is clearing the offline website data.
