### ISSUE TITLE
Feature request: Advanced Markdown Editor, style more in editor mode

### ISSUE THREAD

**Issue by justyn** [standardnotes/forum#182]
The Advanced Markdown editor styles the following in editing mode (that is, not in preview):

* Bold/italic/strikethrough
* Headers
* Ordered and unordered lists

It doesn't style the following:

* Blockquotes
* Code blocks or inline
* Links
* Tables

This makes it harder to read while editing.

These things are styled in the Minimal Markdown editor but that editor lacks other features (like keyboard shortcuts and proper handling of underscores inside words).

It would make a big difference if they could be styled in the Advanced editor similar to the Minimal one.

That is:

* Monospace (fixed-width font) and alternative color for code blocks/inline, and tables
* Alternative colour for blockquotes, links

Thanks.

**Comment by mobitar** [comment]
Hi @justyn, we just released the Fancy Markdown Editor, which styles a lot more in the text area. Check it out and see if it does what you need: https://standardnotes.org/extensions/fancy-markdown-editor

**Comment by justyn** [comment]
@mobitar I just gave it a try, these problems make it unusable for me as it stands at the moment:

* Doesn't work with dark theme
* Doesn't support keyboard shortcuts (bold/italic, block quote etc)
* Can't seem to fully get rid of the preview window

Are these likely to be added at some point?

Thanks.

**Comment by mobitar** [comment]
Dark theme support will be added. Keyboard shortcuts probably not. Preview window can be resized by dragging the vertical pattern to the right of the middle scrollbar.

**Comment by justyn** [comment]
Thanks, the resizing I had figured but I have not been able to completely shrink the pane, some always sticks out (at least on my system).

Given the lack of keyboard shortcuts though, I think the Advanced Markdown Editor would remain a better fit for someone like me, provided it had more styling (as per this feature request).

**Comment by mobitar** [comment]
Yeah, the Fancy one is less utilitarian for sure. Advantages are it looks nicer, and offers LaTeX.
