### ISSUE TITLE
Feature request: Opening multiple notes on desktop

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/forum#183]
Viewing and/or editing multiple notes simultaneously would be useful.

This could be solved with:
(1) Separate child window for a note
(2) Tabbed interface
(3) More than one main app window

I know it's possible to open the desktop app and one or more web interfaces simultaneously, but I'm not sure if this would cause issues in the current version.  If it shouldn't cause issues, then that could be a workaround.  However, it would still be useful to open multiple notes in the desktop app itself.

**Comment by mobitar** [comment]
This could definitely be possible with extensions. Can you describe your usecase and how this would be useful to you?

**Comment by virtualvlad** [comment]
Like having more than one document open in a notepad or word processor, there are potentially many use cases but some examples might be:

(1) Editing/composing notes while referencing others.
(2) Leaving a note mid-edit to focus on another note.  (Leaving it open preserves the scroll position, cursor/selection, and also serves as a reminder to come back to it.)
(3) In the case of multiple main/master windows, dedicating each window to a certain task or theme (e.g., running two searches at the same time).

I think the benefits become more pronounced if you have a multitasking-type of workflow.

**Comment by mobitar** [comment]
Gotcha, interesting indeed. This would be a trivial extension were we just thinking using the plain editor, but once you introduce other editors, requires a little more complexity. I'm sure we'll get to it some day.

**Comment by alturnwall** [comment]
Just wanted to +1 this idea and add use case / suggestion:

I often have two or more "docs" open at once so that I can write in one space while referencing the content in other notes. In that manner, I need to be able to quickly scan content in multiple notes, so the "tabbed" approach alone would not work for me. Instead, I'd love to see the ability to open multiple windows on the desktop app:
- "drag" a tab away from main window (ala Chrome browser tabs)
- right-click on note preview card to open in new window
- double-click on note preview card to open in a new window.

FWIW, Evernote's mac desktop app does this well, allowing you to open in new tab or new window. 

Thanks!

**Comment by k8oi** [comment]
I'd really like the ability to open multiple notes, simultaneously.

For example:  at work I have a daily journal open for general purpose activities, notes, reminders, etc
I also have specific notes for 1-1 meetings; etc - I frequently need to update both and having the windows open (CTL-TAB) kinda thing would be useful.

**Comment by mobitar** [comment]
Agreed regarding its utility. Still no news regarding when something like this might appear. In the meantime, many users opt for opening two separate instances of the app, one being the desktop app, and another, or multiple, being the web app (app.standardnotes.org) opened in their browser.

**Comment by TK42DAN** [comment]
I'd like this as well. In fact, it's pretty important. In Apple Notes I can just double click on a note and it opens up in its own window. This is fairly typical in my experience. Is that something we could see implemented?

**Comment by mobitar** [comment]
Maybe as an extension, one day. Nothing concrete yet.

**Comment by pablco** [comment]
👍

**Comment by alexisgrenon** [comment]
+1 on this feature request :)

For similare reasons as virtuallyvlad !

**Comment by klack** [comment]
Ooof ran into this trying out Standard Notes.  Might be a dealbreaker not being able to pop out notes (occupying minimal screen space as well).  I'm surprised to see this open for 5 years.

**Comment by fweller** [comment]
Still waiting for this feature to be implemented.  on evernote, I commonly have anywhere from 1 to 6 notes open at once on multiple monitors and desktops.

**Comment by klack** [comment]
Doesn't look like it will ever come

**Comment by virtuallyvlad** [comment]
I can't find the post but I believe this feature was on the table for v4.  However, v4 has been in the works for years so when it will release and whether this feature makes it in for that release are open questions.

**Comment by effieeee** [comment]
Tracking here https://github.com/standardnotes/forum/issues/958

**Comment by munkmode** [comment]
+1 on this feature request.

**Comment by TheMany172** [comment]
+1

**Comment by PathToLife** [comment]
If you want to +1 please use the discussion:

https://github.com/standardnotes/forum/discussions/2698

There's the risk of things getting buried in discussions, but it would be good not to bump an 2022 issue (Google search redirects here).

**Comment by edmondnow** [comment]
+1 on this
