### ISSUE TITLE
protected note stuck in "Waiting for Keys"

### ISSUE THREAD

**Issue by jreus** [standardnotes/forum#1839]
Hello, I use Standard Notes across a few devices (two Linux laptops, two Android phones, and two Windows laptops). I have a few password protected notes with sensitive information in them. And recently one of them is giving me the message

```
Waiting for Key
This note is awaiting its encryption key to be ready. Please wait for syncing to complete for this note to be decrypted.
```

I cannot open the note on any device. Also not on the web at app.standardnotes.org

Is there anything I can do to recover this note?

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
