### ISSUE TITLE
Saving to Dropbox? HTML file?

### ISSUE THREAD

**Issue by cryptopana** [standardnotes/forum#184]
Hi, so...

Before, the Standard Notes used to save to Dropbox one little cool HTML file that you could use to access your passwords, even if you didn't have Standard Notes installed.

Where did it go? I purchased the Premium package with another account, and it seems like the software/automatic backups don't work like this anymore? I think I'm missing something here.

Thanks!

**Comment by mobitar** [comment]
The decrypt file should indeed still be synced to your Dropbox. Are you not seeing it? You can always grab it from: 

- Our site: https://standardnotes.org/offline
- From GitHub: https://github.com/standardfile/decrypt

**Comment by cryptopana** [comment]
Thank you! Worked perfectly
