### ISSUE TITLE
Note editor temporarily becomes narrower when "Saving..." message is displayed

### ISSUE THREAD

**Issue by ashtneoi** [standardnotes/forum#1845]
# Summary

When I size my browser window so that the note editor column is 500 px or smaller, the note editor column temporarily becomes narrower when the "Saving..." message is displayed. By "note editor column" I mean the right-hand column containing the note title, the note's tags, and the note's contents. Here are some screenshots showing that column shrinking when the "Saving..." message is displayed:

![Normal size](https://user-images.githubusercontent.com/33603534/133547753-01c22a69-aeec-4341-bf2c-bfa01a144e6d.png)

![Smaller size while saving](https://user-images.githubusercontent.com/33603534/133547758-cf7aaedf-1b21-4795-bfd7-2fe569832906.png)

# Version info etc.

I see this on both app.standardnotes.com and on my self-hosted instance (Git tag 3.8.24).

I'm using Firefox 90.0 on NixOS Linux. The Firefox config option `layout.css.devPixelsPerPx` (the high-DPI scaling factor) is `1.3`. To my knowledge I'm not using any other kind of display scaling. I have Enhanced Tracking Protection enabled and use an ad blocker, but they don't report anything being blocked on app.standardnotes.com, so I don't think there's any interference.

**Comment by myreli** [comment]
The new UI should solve this issue with the changes to the saving indicator. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
