### ISSUE TITLE
.rtf & DropBox?

### ISSUE THREAD

**Issue by sandraardnas** [standardnotes/forum#185]
Hi, I've just found this suite of programs and am excited about its potential for me.
A couple of queries re. usage:
- am I right in thinking that notes are in plain text format and applying highlighting is only allowed by converting the note to HTML (rather than my preferred .rtf)?
- is DropBox sync only available on paid subscription accounts?
Many thanks in advance,
Sandra

**Comment by mobitar** [comment]
Hi @sandraardnas, correct, notes are plain, unless you use the external editors. The Plus Editor in particular will give you text formatting, but your note will be in HTML. Dropbox backups are available only on paid subscriptions.
