### ISSUE TITLE
Typing in archived notes from search results leads to a switch to different note 

### ISSUE THREAD

**Issue by maxlwang** [standardnotes/forum#1854]
If I search for a note using the search bar (with "Include Archived Notes" option selected), select an archived note, and then try to edit the note, the display will switch to a different note from the search results. This only seems to happen when trying to edit archived notes. It also only seems to happen when searching from the "All notes" tab, it doesn't seem to occur when in the "Archived" tab and searching.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
