### ISSUE TITLE
Feature request: Remember sort order per tag

### ISSUE THREAD

**Issue by bbende** [standardnotes/forum#187]
It would be nice if the sort order of the notes list could be remembered per tag.

I usually have very different types of notes that I organize by tags, and I never really look at "All" notes because I don't have a reason to look at these different types of notes co-mingled.

For some tags I have a running list of notes where I want to look at it in time order, with the most recent note at the top of the list.

For other tags the notes are organized more by topics, and I want to look at these in alphabetical order so I can easily know where to look for a topic name.

It becomes tedious having to switch the sort order back and forth every time you change which tag you are looking at.

**Comment by mobitar** [comment]
Hmm interesting idea. Not totally opposed to it. But the architecture isn't currently set up to handle this, so it probably wouldn't be trivial. I plan on doing more work in the tags area (regarding "smart tags") in the future, and will revisit this then.

**Comment by y0ns0n** [comment]
Just checking, this still isn't possible is it? This is related to https://github.com/standardnotes/forum/issues/987 where I usually sort my notes alphabetical, but would like my journal to be sorted by created date.

**Comment by JaspalSuri** [comment]
I can confirm that this currently isn't possible. I currently don't know if it's something that will be revisited before or after the 4.0 update, but I will pass along your feedback!

**Comment by effieeee** [comment]
It's now possible to set display and sorting preferences for a selected tag :)
![image](https://user-images.githubusercontent.com/54989748/198835752-7fb29775-7732-42ce-9fdf-9a9984a22942.png)
