### ISSUE TITLE
Editing a Note alters another in Web

### ISSUE THREAD

**Issue by bscott** [standardnotes/forum#1876]
Having a weird bug where new notes are somehow linked and edits another note in the same tag. 

See attached videos
[Archive.zip](https://github.com/standardnotes/web/files/6217915/Archive.zip)

OS: CrOS aarch64 13729.56.0
Browser: Chrome
Editor: Bold Editor
SN App: Web v3.6.4

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
