### ISSUE TITLE
All notes and tags have been duplicated

### ISSUE THREAD

**Issue by traymarble** [standardnotes/forum#1879]
As the title says, all my notes and tags have been duplicated. In the past few days, I have been exclusively using the web version of standardnotes in the Firefox browser. I remember I had the issue that it seemed like I was signed in to standardnotes web, my theme and notes were there and I was able to edit my notes. However, when I hit the 'Account' button, it said I was not signed in. I then proceeded to sign in with my credentials. I have not been using standardnotes much lately but today I noticed that all my notes and tags (and even the themes) have been duplicated. I assume what I described caused the duplicates. [Here](https://imgur.com/a/Vv2eNyq) is what it looks like.

I imagine I was somehow able to continue my last session which was saved locally in my browser despite not being signed in? And once I signed in, standardnotes noticed there is a problem and tried to avoid data loss by saving every note which was there in the session to my real note collection, even the ones I did not edit? 

Standardnotes web shows it is version 3.6.1. The duplicates also appear on my phone in the app and the duplicate notes do not have an empty note history action.

Now, I am stuck with around 220 notes which I have to delete manually (hit 'options' > 'move to trash' > 'confirm')? That seems like a pita... Since I have given every note at most one tag, I'd like to delete all notes belonging to that tag, but I am not familiar with a method to select and delete every note belonging to a tag. And deleting a tag deletes the tag but not the notes. Is there any quick way out of this? 

This is not the first time I am having issues with conflicting notes and local states, last time the note collection on my phone forked off the main account note collection (although not every note was duplicated in that case, see [this](https://github.com/standardnotes/mobile/issues/315)) 

I realize that standardnotes 'did the right thing' to avoid data loss, but it would be great if there was some sort of  message about how to handle the conflict so I could choose the action which suits my use case the most.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
