### ISSUE TITLE
[FEATURE REQUEST] Easily Delete Notes

### ISSUE THREAD

**Issue by fivebridge** [standardnotes/forum#189]
I find it difficult and not intuitive how to delete notes. There must be a better way than the current design. At first, I thought I could right click a note, like in many other apps, and delete a note but that functionality does not exist. Please add a feature like this or at the very least don't bury the delete note command in t"Menu."

**Comment by mobitar** [comment]
Noted, thanks for the feedback. The reason for the dissonance is because we're designed as a web application first, which means right click menus are not really a thing. Adapting to the desktop environment is always a work in progress.

**Comment by lchogan** [comment]
+1

**Comment by Punkko3** [comment]
1+ An easier way to delete notes too (password requirement?).

**Comment by vitormv** [comment]
+1

**Comment by kslstn** [comment]
Every now and then I expect the options to show up when I right-click a note. Mainly to delete the note, but also for the other actions.

**Comment by robertmartin8** [comment]
The lack of functionality on the "All Notes" pane is a little bit annoying. I find myself trying to control-click to select multiple notes, or to navigate them with keyboard shortcuts, but nothing happens. This is one thing that evernote does very well, in my opinion.

The difficulty of deleting a note is unfortunately one of the reasons why I don't use Standard Notes as much as I'd like. It stops me from wanting to jot down super quick thoughts.

**Comment by bryvin** [comment]
This is a pain point that we will address in an upcoming release but as of right now we don't have a timeline for this.

The Batch Manager extension that can be opened from the Extensions panel in the lower left of the interface is currently the best way to select multiple items and/or notes for deleting all at once.

**Comment by effieeee** [comment]
Closing, already implemented
