### ISSUE TITLE
RAILS_ENV=production causes web app to crash

### ISSUE THREAD

**Issue by eric-pierce** [standardnotes/forum#1894]
I have been using RAILS_ENV=production on my install for some time (docker-compose), but recent updates to the stable image cause it to crash with that parameter. Changing it to RAILS_ENV=development or removing the parameter entirely resolves this issue. I only was using RAILS_ENV=production because my environment is a production one, not development, but frankly I don't have any visibility into what that parameter actually does.

Wanted to call it out in case anyone else runs into the same issue - I consider my issue resolved now that I changed to development.

**Comment by myreli** [comment]
Since this issue was opened SN has changed, including its [self-hosting documentation](https://standardnotes.com/help/self-hosting/getting-started). It seems like this issue is unlikely to receive more interaction, so I'll close it.
