### ISSUE TITLE
Customize the "Code" style in Plus Editor based on theme

### ISSUE THREAD

**Issue by bbende** [standardnotes/forum#190]
Many of my notes contain snippets of code or commands, and I like to use the "Code" style in the Plus Editor to make those sections stand out. 

I noticed that regardless of the theme, the "pre" block created by the Code style always looks the same. For darker themes like Solarized Dark, the code block seems really bright and I wanted to find a way to customize it (assuming that this is just my personal preference and it is not desired to change the base theme).

I saw the section in the Solarized Dark theme that mentions the Plus Editor:
https://github.com/sn-extensions/solarized-dark-theme/blob/master/src/main.scss#L314-L341

If I created my own theme based off this, what CSS selector would need to be added to target the pre-block?

**Comment by mobitar** [comment]
The best way to determine selectors is to right click and use Inspect Element (while on the web app). Just be sure to wrap it in the #plus-editor selector. Probably `#plus-editor pre` is all you would need, but haven't tested that.

**Comment by bbende** [comment]
Thanks! I'm not sure I setup the package.json totally correctly, but was able to get it to work after some trial and error. 

Decided to try it on the Futura theme:  https://github.com/bbende/futura-theme

**Comment by mobitar** [comment]
Got a before and after image?

**Comment by bbende** [comment]
Sure...

https://raw.githubusercontent.com/bbende/futura-theme/master/images/SN-PlusEditor-CodeStyle-Before.jpeg

https://raw.githubusercontent.com/bbende/futura-theme/master/images/SN-PlusEditor-CodeStyle-After.jpeg

I know it is extremely minor, but the original one felt too bright to me when everything else in the theme was dark/dimmed, and it would stand out a lot when I had many code blocks in a row.

**Comment by mobitar** [comment]
Ah very nice. Feel free to submit a PR if you get a chance. How are you marking a block of text as pre? Just manually via the code view? I don't recall a button in the toolbar for this..

**Comment by bbende** [comment]
Ok cool... the style drop-down in the plus editor has a "Code" style, its before  Header 1-6 and next to Blockquote. I looked in the code view to see that it was using a pre element with no special styling, so it figured it was just picking up default styles.
