### ISSUE TITLE
There is a problem with the behavior of the enter key in the title field.

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#1901]
When I press the Enter key in the title field, the cursor moves to the body field.
This is a very difficult behavior for those using the CJK input method to use.
Change the behavior so that when I press the Enter key in the title field, it doesn't move to the body field.

([Link to previous thread.](https://github.com/standardnotes/desktop/issues/604))

**Comment by myreli** [comment]
It seems like this has been addressed and the issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
