### ISSUE TITLE
docker hub image not working

### ISSUE THREAD

**Issue by MakiG0** [standardnotes/forum#1903]
I read about standardnotes last week and i think that i could get my notes under control. Many thanks for this great software. 
I want to host standardnotes myself with docker.
I was able to set up the sync server successfully with docker and docker-compose. However, I get the following error message when setting up the web-service:
`starting container process caused "exec: \"./docker/entrypoint.sh\": stat ./docker/entrypoint.sh: no such file or directory": unknown
`

i tried the standardnotes/web:stable version.

Is it possible that the image is not correct or or am I doing something wrong?

**Comment by karolsojko** [comment]
As per [Docker docs](https://docs.docker.com/compose/#common-use-cases):

```
Compose has traditionally been focused on development and testing workflows, but with each release we’re making progress on more production-oriented features.
```

So it depends on what you mean by `production` if it's a single host machine with all relationships defined then I guess you're fine with running Docker compose there. When it's a dynamic scalable solution as it is in our case then it's not quite suitable.
