### ISSUE TITLE
[FEATURE REQUEST] Remember zoom level / set font size

### ISSUE THREAD

**Issue by rschouwenburg** [standardnotes/forum#191]
The default font size is too large for me - especially for the editor. I am using Linux. I use zoom out to make the font size smaller, but I have to do this on every startup. It would be great if it could saved in the config. Otherwise I would love I could set the font size.

**Comment by mobitar** [comment]
Ideally it should remember your zoom settings. I believe there's an issue about this somewhere. Made a note to investigate it this sooner than later.

**Comment by mobitar** [comment]
I've just tested with version 2.1.25 on Mac, and the zoom level is remembered automatically and restored on app launch. Are you on 2.1.25? Perhaps a Linux issue..

**Comment by rschouwenburg** [comment]
Yes I'm on 2.1.25 and the problem is still here. I guess it's an electron problem on Linux. Does it remember the window size on Mac too by any chance? Because that gets lost too in Linux.

**Comment by mobitar** [comment]
Yup, that is remembered as well. Though that one is custom code we added ourselves. Strange it's not working on Linux. Will have to investigate.

**Comment by rschouwenburg** [comment]
Ok, let me know if I can help testing or debugging.

**Comment by mobitar** [comment]
Thanks!

**Comment by slvnyai** [comment]
On win 10 the zoom level is not remembered neither.

**Comment by TheodoreChu** [comment]
Zoom level is remembered for me on Windows 10, `v3.5.14`, so I'm closing the issue. Feel free to comment if you still have issues.
