### ISSUE TITLE
the bottom bar on mobile seem unnecessary

### ISSUE THREAD

**Issue by fletom** [standardnotes/forum#192]
currently, the iPad version of SN has a large bar on the bottom with just one "Notes" button and one "Account" button. however, the Account tab is basically a settings interface which should be accessed only very rarely. wouldn't it make more sense for it to be a small gear icon on the top bar instead so it doesn't take up so much space?

**Comment by mobitar** [comment]
Possibly, although, where would the gear icon go? The top two spots are already inhabited. We can cram it, but would probably cause even more anxiety ;)

**Comment by fletom** [comment]
if I were designing, I would change "New" to a "+" icon, change "Filter" to a hamburger icon, and make the hamburger pop out a drawer from the left instead of a whole new window. the "sort by" and "tags" already look a bit strange on their own massive lines on an iPad since they only take up the first 10% of the screen space they're assigned. Apple's Notes app on the iPad is a good example of this. then the hamburger icon would take up it's standard role of a general navigation interface: filter, sort, or access account settings.

the other thing Apple does in Notes is make the notes list itself a side drawer instead of the whole width of the screen, so you see the list as well as the content of your selected note, which makes sense to me on a tablet-sized screen. the current UI is more suited to a phone, where the screen is the correct width for a filter list or notes list.

but those are just random thoughts and none of this is very important. just wanted to bring up the idea!

**Comment by mobitar** [comment]
Ah, if you're using it from an iPad it won't look perfect, as it's just a scaled up iPhone app. Still haven't committed to tablet UI optimization yet. But, I definitely like the idea you're proposing. Worth exploring..

**Comment by TheodoreChu** [comment]
Closing this because the latest versions of mobile v3.5 have design improvements as discussed above
