### ISSUE TITLE
Fingerprint unlock keeps control of home button when app is in background.

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#193]
I am using the Android version 2.1.2 on a Oneplus 3T using Android 8.1.0 (Lineage OS 15.1 [understand if this invalidates the issue]). 

I noticed if I enable fingerprint lock, require a fingerprint Immediately, close SN, open SN, then switch to another app (thus moving SN to the background), the home button is still waiting for input to unlock SN rather than returning to being a normal home button.  

I have a feeling this is more of a fingerprint api issue but SN is the first time this issue has happened to me so I figured Id say something.  

Thank you.

**Comment by mobitar** [comment]
Hmm..very strange. Not familiar with this device model. So when you click the home button, nothing happens? I suppose a fix would be to invalidate the fingerprint request as soon as the app is closed. Have made a note of this, thanks!
