### ISSUE TITLE
Mac OS High Sierra can't open Standard Notes because Dialog Password Required is not working

### ISSUE THREAD

**Issue by Belura** [standardnotes/forum#197]
Hallo, i made a first fresh install on my MacBook and activate local Encryption.
After restart Standard Notes i get a DialogBox "Password Required". If i type in the Wrong Password he say password is wrong, but if i type in the right password nothing happens the Dialog is still Standing and nothing Happens. How can i reset the local Data?

Regards Belura
![dialog](https://user-images.githubusercontent.com/38376804/38767873-2e7f4f30-3fea-11e8-834f-896d3a10c068.png)

**Comment by mobitar** [comment]
Hi @Belura, you can reset local data by clicking Help -> Open Data Directory, then deleting everything inside there. Then reset the app.

As for debugging this issue, if you're able to, please click Help -> Toggle Error Console, and see what error it generates when you hit Unlock.

**Comment by Belura** [comment]
Hi Mo Bitar,
here ist the ErrorMessage. 
After the reset  it works  fine.
Thanks for your help.


TypeError: Cannot read property 'content' of null
    at Function.decryptItem (compiled.js:33438)
    at StorageManager.decryptStorage (compiled.js:40853)
    at PasscodeManager.decryptLocalStorage (compiled.js:40409)
    at PasscodeManager.<anonymous> (compiled.js:40364)
    at SNCryptoWeb.<anonymous> (compiled.js:33288)
    at compiled.js:33604
    at SNCryptoWeb.<anonymous> (compiled.js:33637)
    at SNCryptoWeb.<anonymous> (compiled.js:33668)
    at <anonymous>
(anonymous) @ compiled.js:33670
compiled.js:33599 Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at compiled.js:33599
    at SNCryptoWeb.<anonymous> (compiled.js:33633)
    at compiled.js:33671
    at <anonymous>
(anonymous) @ compiled.js:33599
(anonymous) @ compiled.js:33633
(anonymous) @ compiled.js:33671




Diese E-Mail enthält möglicherweise vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist nicht gestattet.
“Disclaimer”
This E-Mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this E-Mail in error) please notify the sender immediately and destroy this E-Mail. Any unauthorised copying, disclosure or distribution of the material in this E-Mail is strictly forbidden.

**Comment by mobitar** [comment]
Thanks for the info..have you changed your local passcode at all since setting it up? Or disabled then reenabled it?

**Comment by Belura** [comment]
at the first time, i set it as a new password and enable it. I don‘t remember it clear , but maybe i reenable it yes.
