### ISSUE TITLE
date modified does not update on iOS

### ISSUE THREAD

**Issue by cfm** [standardnotes/forum#198]
Compare Standard Notes on macOS—

<img width="172" alt="standard-notes-mac" src="https://user-images.githubusercontent.com/357435/38785385-d5534d66-40cb-11e8-93d2-90217708f236.png">

—versus on iOS:

<img width="320" alt="png image" src="https://user-images.githubusercontent.com/357435/38785390-e3d9f52e-40cb-11e8-9a11-329217ab500d.png">

**Comment by mobitar** [comment]
Is it just the dates that are incorrect? Is the content matched up and up to date?

Can you test another manual change, and see if the content is pulled, but the date is not refreshed?

**Comment by cfm** [comment]
@mobitar:

> Is it just the dates that are incorrect? Is the content matched up and up to date?
> 
> Can you test another manual change, and see if the content is pulled, but the date is not refreshed?

Yes, that's correct.  For example, this change I made *on* iOS—

<img width="320" alt="sn-ios" src="https://user-images.githubusercontent.com/357435/38827112-59473d48-415e-11e8-90a7-ac9a24365c45.png">

—and the content is correct on both (all) platforms, but the date has only updated on macOS:

<img width="177" alt="sn-macos" src="https://user-images.githubusercontent.com/357435/38827147-780911ca-415e-11e8-830c-179066dce296.png">

**Comment by mobitar** [comment]
That's strange. I just tested this on iOS 11 and using the SN Mac app 2.1.26, and unable to reproduce it. The modified dates update right away. Does this reproduce for you 100% of the time? For all notes, or particular notes?

**Comment by cfm** [comment]
@mobitar:

> Does this reproduce for you 100% of the time? For all notes, or particular notes?

The notes I use most often happen to be have been imported from plain text.  But a new note displays the same behavior: the iOS copy does not update from its creation-time of 10:39 AM, even though its content is up to date.

* macOS:

    <img width="174" alt="macos" src="https://user-images.githubusercontent.com/357435/38889721-ff6c1298-422b-11e8-8dad-d137636b15c4.png">

* iOS:

    <img width="320" alt="ios" src="https://user-images.githubusercontent.com/357435/38889723-010e74ec-422c-11e8-8159-13a850d3222e.png">

**Comment by mobitar** [comment]
What about if you quit the app and reopen it? Does it update then?

**Comment by cfm** [comment]
On Tue, Apr 17, 2018 at 11:44:34AM -0700, Mo Bitar wrote:
> What about if you quit the app and reopen it? Does it update then?

I'm afraid not.  Even after a full sign-out and sign-in on iOS, notes
I've updated many times (including this morning!) still show a
last-modified date of March 25.

**Comment by JakeTse1988** [comment]
Did this happen on your iPhone? Have you tested it on other iPhones or **[iPad models](https://www.cfone.net/apple-ipad-models-generations.html)**? I've come across several issues due to compatibility. It just happens to a specific device because it works fine on another device of same model and same iOS version. I guess this has something to do with the device settings that we haven't figured out.

**Comment by mobitar** [comment]
Yeah this issue is bewildering. Is it possible the app is incorrectly displaying the create date instead, and passing it off as the modified date? @cfm can you confirm/deny this theory?

**Comment by mobitar** [comment]
Ah missed that. Still strange though. And you are signed in to an account on the iOS app, right? Because there was an issue I found if you're using the app offline that could cause this. (Or if you have poor network connectivity)

**Comment by cfm** [comment]
@mobitar, I apologize for losing track of this thread this month.   Yes, I am signed in in the iOS app.

**Comment by effieeee** [comment]
Closing temporarily as it's been too long, but can be reopened if the user wishes!
