### ISSUE TITLE
Can't sync over VPN

### ISSUE THREAD

**Issue by ThoughtMonster** [standardnotes/forum#199]
'Can't connect to server' error when using VPN. Is that meant to be a limit?

**Comment by mobitar** [comment]
This definitely isn't anything on our end. Lots of users use us over a VPN without issue. Are you able to access our website when you're connected to the VPN?

**Comment by ThoughtMonster** [comment]
Hi, thanks for the email. Yes, while connected to the VPN, I can log into my account through the website. But the app says it can't connect to the server. It's the same account - I only have the one account. So I don't understand it. But it's useful to know that it's not your restriction. Thank you!
_____________________________
ThoughtMonster
Seattle, WA

“It is better to be hated for what you are than to be loved for what you are not."
—Andre Gide

16. Apr 2018 20:02 by notifications@github.com <mailto:notifications@github.com>:

**Comment by mobitar** [comment]
Well if you can log in, then you should be able to sync. It's the same server. There might be something else going on. And it's only when the VPN is enabled that you see this issue?

**Comment by philiptruax** [comment]
It's actually very common for VPNs to block ports as a measure of protection against spam. So if SN uses either a non-standard port or something aside from standard web ports it's very likely blocked by the VPN provider.

**Comment by mobitar** [comment]
We only use HTTPS (443) for our server..

**Comment by davidmarchal** [comment]
Get the Fastest VPN for 2018 that allows you to access blocked and restricted content from anywhere in the world. Stream and Download with complete anonymity and security. FastestVPN service provider offers secure access and high speed.

**Comment by alincarter** [comment]
Buy FastestVPN Service with a 7-Day Money Back Guarantee at a 92% Discount. Purchase a VPN now for just $0.83 per month. Cancel anytime you want.

**Comment by zaidalikhan9** [comment]
Syncing over VPN can be done through different ways. By turning your device on to airplane mode and linking directly to a stable Wi-Fi connection you are permitted to perform an effective sync exposing the device and/or joining does not break. Follow https://www.bulletvpn.com to learn a lot more now. On Windows 10, it can be done by tapping on Network Icon in System Tray, choose Network and Internet settings and pick VPN and toggle left to turn it off. Now choose Wireless Icon in System Tray, pick Airplane Mode and choose Wi-Fi network so you could connect. That’s all you need to do for syncing over VPN and I hope you would be able to do it successfully.
