### ISSUE TITLE
Problem after moving the .AppImage file to a different directory

### ISSUE THREAD

**Issue by LorinRicker** [standardnotes/forum#2]
I discovered Standard Notes here:
http://www.techrepublic.com/article/how-to-get-private-encrypted-notes-with-standard-notes/?ftag=TRE4e2523d&bhid=23962314077606345295986770978101
and installed it using the author's recommendations (on Ubuntu/Linux, Trusty).  After running & evaluating it, I'm all in!

However, rather than leaving the .AppImage file in the (temp-files) download directory, I've moved it to a more permanent and logical spot:  $HOME/standard-notes/standard-notes-1.1.1-x86_64.AppImage

Now, when I activate it there, I get a popup window saying (see attached file): "There was an issue loading your offline database.  This could happen for two reasons:  1. ... 2. You have two windows of the app open at the same time.  Please close any other app instances..."

A ps command does not reveal the earlier app/instance, so I can't kill this.  I'm betting that a laptop reboot may resolve this, but shouldn't the app handle this more gracefully?

Looking forward to using Standard Notes -- I heartily approve and endorse your privacy policy and the larger context of your business plan.  Many thanks for what looks to be a great product!
-- Lorin

![standard-notes-popup-warning](https://user-images.githubusercontent.com/1362449/27988554-4cdd2b04-63e1-11e7-9550-66be68f93da4.jpg)

**Comment by LorinRicker** [comment]
My surmise about rebooting was wrong -- that didn't make the "evaluation instance" go away, I still get the warning dialog box whenever I (re)start Standard Notes.

How can I clear this up?  Thanks!  -- Lorin

**Comment by mobitar** [comment]
Hey Lorin, did you get this figured out?
