### ISSUE TITLE
"Standard Notes is trying to add a new helper tool."

### ISSUE THREAD

**Issue by dalaeance** [standardnotes/forum#20]
Anytime I make edits in Standard Notes, this pops up. How do I stop this?

![screenshot 2017-07-19 16 43 39](https://user-images.githubusercontent.com/30301418/28389210-2d03c35e-6ca3-11e7-8b9e-79f0c20581bb.jpg)

**Comment by mobitar** [comment]
Strange, I think this has to do with Electron. See if any of these threads help:

https://www.reddit.com/r/Slack/comments/5l5crw/slack_is_trying_to_install_a_new_helper_tool/
https://apple.stackexchange.com/questions/267685/repeatedly-try-to-add-a-new-helper-tool-on-each-restart-for-same-applications

Seems like the solution is to change ownership of the app.

**Comment by dalaeance** [comment]
I saw something like this when searching before posting here. It seems the problem's gone now, though, after updating to enable verification. Thanks for your help! I think, for me, I can mark this resolved.
