### ISSUE TITLE
Feature Request: Add a trash bin and set expiration time

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#201]
Sometimes I’m worried if I accidentally deleted a note and it’s gone forever. I think there should be a trash bin with expiration timer to set. On top of that, maybe also add a pop up message before deletion just in case.

**Comment by mobitar** [comment]
You do get prompted to confirm before deletion. The trash bin is really just the Archive section, so you're better off Archiving in general instead of deleting.

**Comment by n0bodyBod** [comment]
Alright, I’ll do that. Thanks mobitar!
