### ISSUE TITLE
Progressive Web App with Service Worker

### ISSUE THREAD

**Issue by christiankaindl** [standardnotes/forum#2040]
Progressive Web Apps are the future. Microsoft announced that they will display PWAs in the Windows Store, Google announced also that they will show PWAs in the Play Store (and they even made a Google Maps version - "Google Maps Go"). Edge and Safari - the last remaining big browser - have both started developing and shipping Service Workers in their browsers. 

The World Wide Web will become a gigantic space that can give you thousands of apps and experiences at no time. It's an "App Store", but without the "Store". I think this is an opportunity to make Standard Notes a first class citizen in that space. (I don't know your focus, but with _only_ a PWA your app can be listed in the Windows Store and the Play Store - and potentially even more place in the future - besides it being available through the web (in the end it is still a "website"))

There are plenty of success stories from big companies who switched to PWAs and increased user engagement, usage and revenue - most recently Tinder, but also Starbucks and others already jumped on the train.

---

I use Standard Notes as a Web App on my desktop (through GNOME Web - thanks to the manifest.json). This means that, although I use the web version, I can use and switch between it like a normal desktop app - it has it's own window. 

But when - for whatever reason - my internet connection fails, I am out of luck with this method because there is no offline capability with Service Workers and then _I can't make any notes_.

On MDN: https://developer.mozilla.org/en-US/Apps/Progressive
Some cool ones: https://pwa.rocks/

**Comment by christiankaindl** [comment]
Oh yeah, maybe I should give a bit more context. The term Progressive Web App was coined to summarize a set of new web technologies that together can create native-like experiences. These technologies include the manifest (a JSON file that describes the app), Service Worker and other new web APIs, such as background sync and (push) notifications. But Service Worker is the big one. It gives the developer complete control and everything that happens.  With Service Worker, IndexedDB and the Web Storage API one can make offline first (ideally convergent(responsive)) apps that are nearly/completely indistinguishable from their native counterparts. 

And: Through setting `"display": "standalone"` in the manifest the user can "install" the app and use it on their device *without the browser UI*.

PWAs are meant to be the future because, especially for start-ups, they run everywhere where a browser exsists. Windows, macOS, Android, Linux, and systems that do not even exist yet - where a browser there your app. Small businesses can't afford to have 3 or more code bases - one for Android, iOS, Web, Windows, ...
So with PWAs they only have to manage one code base.

---

Here's how it looks like using Standard Notes as a desktop app through GNOME Web:

![screenshot from 2018-01-02 10 57 30](https://user-images.githubusercontent.com/15364860/34480345-1c246c3c-efac-11e7-8fa8-353470e5092d.png)

As you can see from the screenshot, SN has its own window and also its own icon in the taskbar. I can search it independently from other apps and it *seems* like any other native app. GNOME Web is a WebKit based browser for Linux. When you "install" a website as an app the GNOME Web basically puts a shell (wrapper) around it. Note that the browser UI is not there! Also, you can't navigate to a different website (like an app).

Not only GNOME Web offers this "install" possibility. Chrome for both Android and desktop also support it, Firefox for Android ships it soon in version 58 (On Android "install" add an icon of the app to the homescreen of the device). Microsoft Edge will also allow it in near future (when their Service Worker implementation is ready). 

Here is Standard Notes as a desktop app "installed" through Google Chrome (on Linux):

![screenshot from 2018-01-02 11 10 00](https://user-images.githubusercontent.com/15364860/34480576-80c77408-efad-11e7-8625-d0b469a94972.png)


Google has a great website that gives an overview on what PWAs are: https://developers.google.com/web/progressive-web-apps/

---

Now, the reason why I use the web app and not the native one: On the Linux installation page I can download an AppImage and have to run 2 commands. So, just think about it given two options: 1) Download ~60 MB and figure out the installation, or 2) download nothing and don't figure out the installation, while having the same app experience.

I think that summarizes my reasoning: convenience and accessibility. In general PWAs are *much* smaller in download size and I can use a convenient and *familiar* method of getting it: the browser; It don't fear the command line, but it's just a better experience.

app.standardnotes.org only downloaded ~200kB and was ready to be used within 2 (!) seconds. 

![screenshot from 2018-01-02 11 39 01](https://user-images.githubusercontent.com/15364860/34481363-06dddaec-efb2-11e7-9bcf-e2ce44e2bcf8.png)
![screenshot from 2018-01-02 11 44 02](https://user-images.githubusercontent.com/15364860/34481413-53a8c9cc-efb2-11e7-9e11-72b718fdea21.png)
*Measures from the Firefox Developer Tools*

I think the advantage to a native app is now clear :)

Wish you a happy New Year! 🎉

**Comment by tmke8** [comment]
It would solve my issue in standardnotes/forum#2067 .

**Comment by christiankaindl** [comment]
Good question 🤔

I don't know from which domain the editors are loaded, but a Service Worker registered in a folder can controll all children. E.g. If you would install a SW in `sn.com/extended/` it will control pages like `sn.com/extended/editorXY`. That SW could very well just serve the cached editors when it is embedded in a WebView.

But: Judging from [this issue on iOS](https://github.com/facebook/react-native/issues/18697), registering a Service Worker from the domain of the editors (or a directory within that domain like shown above) would not work, because Service Worker functionality is [not available in iOS' WKWebView](https://webkit.org/blog/8090/workers-at-your-service/) (see the update at the top of the link). So such a Service Worker would do nothing at all (if used in a WKWebView).

Although _it is available_ in `SFSafariViewController`, but I don't know which is used by Standard Notes or React Native. In case the used WebView is `SFSafariViewController` making the editors PWAs might actually work. Android's WebView [supports Service Workers](https://chromereleases.googleblog.com/2015/03/android-webview-update.html) for a while already.

If `SFSafariViewController` is not used, but `WKWebView` instead, this means a Service Worker is not really an option, because it would not work on iOS. As an alternative I found [react-native-offline-cache-webview](https://www.npmjs.com/package/react-native-offline-cache-webview) which, from reading the readme, sounds like something similar to your use case. As far as I understand, this package uses native storage mechanisms from each platform to store a cached version of the WebView pages (or Extended Editors in this case).

**Comment by bolvanq** [comment]
Hi, is there any update on this? The current desktop apps are written in Electron, which is terrible. I installed it on Linux (Ubuntu) and I experienced poor performances, high RAM usage, and in a few days I had the [blank window bug](https://github.com/standardnotes/forum/issues/3363). Rather than leaving SN altogether, I decided to give the web app a chance. I've been using it for almost one year and it works **so much better** than the Electron app. It also has basically the same features, with some minor exceptions that are not a deal breaker for me. Not to mention the security advantages of not having to install any app. I can also add it to my start menu, so it just looks and behaves like a standalone app.

Moreover, I now pay for a Professional plan so that I can use an entirely different account at work. I can't install any app on my work laptop, so SN is a great solution.

However, the lack of service workers / offline support is a big issue, because I'm not even be able to open my work notes if there's no network, e.g. because I'm flying. This is almost a deal breaker for me. Can you please reopen this issue and share any plans to implement offline support in the web app?
