### ISSUE TITLE
Icon on mac not show

### ISSUE THREAD

**Issue by Jayuda** [standardnotes/forum#206]
Hello guys,
On my mac, icon on desktop not show. I am already reinstall.
Any information about this ?
Thanks

![screen shot 2018-04-27 at 2 43 31 pm](https://user-images.githubusercontent.com/1973447/39351768-c2feb898-4a2c-11e8-82d3-60aee9874b39.png)

**Comment by mobitar** [comment]
Hmm that's strange. Does the icon appear in the dock when the app is running? Or only in this view? Also, what version of Mac are you on?
