### ISSUE TITLE
Feature request: Batch export by tag, search, or manual selection

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#207]
I need be able to export individual notes by tag, search, or manual selection. Eg, export all notes tagged journal.2018.

The ability to export notes like this removes any concerns of being locked-in to SN. The export function right now is for all notes or none. I need something in between.

Also, I would like the exported file names to *not* have the long alphanumeric identification string appended to the file name.

Connected to this batch export request, I also need the function to batch delete notes by tag, search, or manual section. Eg, after exporting all notes tagged journal.2018, I'd like to delete these from SN.

Love the app! Thanks!

**Comment by mobitar** [comment]
Hey @comitt, thanks for the feedback. I do like some of these ideas, especially as related to tagging, and plan to, at some point, beef up the Batch Manager to be able to handle some of this stuff.

**Comment by trevormeier** [comment]
Hi there—is there still no way to export a single note or a small group of selected notes? If so, I'd love to see this feature!

**Comment by effieeee** [comment]
It's now possible to export selected notes or notes of a selected tag using multiple selection on desktop and web! :)
