### ISSUE TITLE
iOS: "Export Data" seems to do nothing

### ISSUE THREAD

**Issue by ce-go** [standardnotes/forum#208]
Hi there,
I'm using the ios app for taking notes, however to have a non-ios-backup, i tried to export my notes using the Account->Export Data button, but nothing happens? The [FAQ](https://standardnotes.org/help/14/how-do-i-create-backups-of-my-standard-notes-data) only mentions the backup strategy for the web app, but do i miss something here? My account settings are empty because i'm only using my phone, so do i have to have a account to be able to backup my data?
Best, Chris

**Comment by mobitar** [comment]
Hey Chris, it should work as expected, even without an account. Do you have the Mail app set up on your phone? Also, do you have lots of notes? Perhaps give it 10 seconds or so and see if it does anything? If not, please let me know what app version and iOS version you're using.

**Comment by ce-go** [comment]
Hi @mobitar, yes the Mail app is setup for two of my mail accounts and works when tested from other apps. Lots of notes? Mh, well about 120 or so, i'll try to keep a kind of diary ;)
When i press the "Export Data" button, "Preparing data" shows up (greyed out) and nothing happens, even if i wait for 10 minutes with no screen lock in between. My setup: Standard Notes 2.1.28, iOS 11.3.1. No encryption activated.
I tried to disable the fingerprint lock to see whether this might solve the isssue but no success.
Love your app btw :)

**Comment by mobitar** [comment]
Hmm strange. I just tested on 11.3.1 and it works just fine. Are you adamant about using the app without a sync account? I highly recommend you have some sort of backup in place. I can't be sure what the issue is until I can reproduce it myself, which so far I have been unable to do. An unusual step, but perhaps try restarting your phone? Perhaps something with the Mail integration is off..

**Comment by ce-go** [comment]
Restarting didnt work either. As for your suggestion, I created a account and synced my notes. The export button works now, hey ;)
Maybe to reproduce the error: There was no account given at any time, so i guess it could be called a setup from scratch? Thanks for your support!

**Comment by mobitar** [comment]
I did try that though..export without an account. Still worked. Strange. Will investigate more. Thanks!
