### ISSUE TITLE
How to remove desktop intergration?

### ISSUE THREAD

**Issue by p9lly** [standardnotes/forum#209]
I googled on how to do this and people recommend:  "Additionally you may want to remove menu entry by deleting the desktop file from $HOME/.local/share/applications/", but that doesn't seem to work because my Ubuntu computer says there's nothing in that directory. 

I'm trying to re-install standard notes so I can put the appimage somewhere else rather than the downloads folder on my computer.

**Comment by mobitar** [comment]
Try clicking Help -> Open Data Directory, then delete everything in there.

**Comment by p9lly** [comment]
okay, i figured it out:
sudo natilus
show hidden files
then proceed to go to .local/share/applications/
and there it was appimagekit-standard-notes.desktop
delete and re-iinstall
we all good, thank you.
