### ISSUE TITLE
How do I delete my account?

### ISSUE THREAD

**Issue by scottjl** [standardnotes/forum#21]
how do I delete my account? can't seem to find a way. thanks!

**Comment by mobitar** [comment]
Please send an email to reset@standardnotes.org from your account email to delete account.

**Comment by mobitar** [comment]
Update: You can now visit https://standardnotes.org/reset to delete your account.

Btw, if you're deleting your account and leaving for good, please reach out to me at mo@standardnotes.org to tell me how we could have done better. Would be very helpful!
