### ISSUE TITLE
Feature Request: Static Symbolic Link to AppImage

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#211]
_Please_ consider using a symbolic link with a static name that is updated to point to the new location of the AppImage when the application auto-updates. I was initially using the following script:

#!/bin/bash
notes=$(ls /home/user/apps | grep standard)
/home/user/apps/./$notes

and mapping that to a keyboard command in order to launch the application. However, after a recent release, (a) the AppImage no longer contains any reference to the name of the application, and (b) multiple versions of the AppImage linger in my application folder. For example, I currently have "installer-2.1.26.AppImage" and "installer-2.1.30.AppImage" in my applications folder.

Please also consider resuming the former policy of including a reference to "standard notes" in the AppImage name. Since the AppImage functions as an independent executable, identifying it as an installer is incorrect, yes? Additionally, it seems that failing to identify the name of the application in its executable is simply.... not the right way to do things. Executables should be easily identified, unless there's a profoundly good reason that they should not be. This is a matter of personal philosophy, but I have yet to encounter any debates on this subject.

Please also consider utilizing a stable naming system for AppImage releases. I personally do not like _any_ surprises in my binary executable folders, no matter how small, and I'm sure that I am not the only person who feels this way.

**Comment by mobitar** [comment]
Hey @anjeriou, thanks for the feedback. Though I'm not sure I'm following: we do use a consistent naming scheme for our releases: https://github.com/standardnotes/desktop/releases

Is it the autoupdate files that are incorrectly named? What are you seeing there? We use [electron-builder](https://github.com/electron-userland/electron-builder) to handle autoupdates, so there's going to be a limited amount of control we can have there. But perhaps we can file an issue with them if there's some sort of inconsistency here.

**Comment by anjeriou** [comment]
Yeah, in my applications folder, my standard notes executables are currently named "installer-2.1.26.AppImage" and "installer-2.1.30.AppImage". This was not the case until a recent release, I'm not sure precisely which one. Previously, I would only have one AppImage in my executable folder, and their naming was consistent with your releases.

**Comment by mobitar** [comment]
This should be fixed in 2.1.32, which is now available.
