### ISSUE TITLE
Automatic lock ?

### ISSUE THREAD

**Issue by alpha139866** [standardnotes/forum#213]
Hey everyone,

Is there an option to make Standard Notes automatically lock down after a period of inactivity?

I love the program... I use it everywhere and I have a tendency to leave the app running, unprotected.

Thanks!

**Comment by mobitar** [comment]
Hey @alpha139866, this isn't currently offered, but is an interesting option. Perhaps we could add something like this in the future. There's also the little lock button in the bottom right corner that you can press at any time to immediately lock the app.

**Comment by xmenage** [comment]
Hi,

I have the same issue. I would like the app to automatically lock after left unattended for some time (I use both Android and Webapp).
On Android, there is no lock button. However, if left unattended for some time (not sure how long), then switching back to the app shows an empty white screen, then after about 30seconds, it asks for the password (I activated password lock on quit). So this is about what I'd like although I am not sure whether this is a feature or a side effect. It would be nice to be able to control timeout before it locks, or just set some standard timeout that will work for everyone.

Thanks

**Comment by mobitar** [comment]
@xmenage you're referring completely to Android right? So you have passcode lock set to immediate, but you're seeing a 30s delay? That's unusual. How many notes do you have total?

**Comment by mobitar** [comment]
> it shows that white display with top red border and nothing else, no button, no request for password. Then after about 30s, it requests the password. 

Hmm that's very strange. Haven't heard this issue before. Any way to capture a screen recording of this?

**Comment by xmenage** [comment]
Here is a snapshot. In that particular case the request for password never showed up, I had to close the app and restart it.



    On Monday, June 11, 2018, 10:02:13 PM GMT+4, Mo Bitar <notifications@github.com> wrote:  
 
 

it shows that white display with top red border and nothing else, no button, no request for password. Then after about 30s, it requests the password.


Hmm that's very strange. Haven't heard this issue before. Any way to capture a screen recording of this?

**Comment by mobitar** [comment]
No files attached in your message..

**Comment by xmenage** [comment]
And now ?


    On Wednesday, June 13, 2018, 7:28:51 PM GMT+4, Mo Bitar <notifications@github.com> wrote:  
 
 
No files attached in your message..

**Comment by mobitar** [comment]
No, I don't think you can include attachments to GitHub when replying from an email. You have to use the web interface.

**Comment by mobitar** [comment]
Autolock is implemented in 2.4.0-beta1, which you can download from here: https://github.com/standardnotes/desktop/releases/tag/v2.4.0-beta1

**Comment by ThorgeL** [comment]
What tier is this available in? Can't find it in the free one.

**Comment by moughxyz** [comment]
Preferences > Security > Passcode lock. After enabling, you'll see options for autolock.

**Comment by ThorgeL** [comment]
Thanks! I think I had to restart the app for the option to appear.
