### ISSUE TITLE
Third party keyboards on ios affected by auto save

### ISSUE THREAD

**Issue by smking** [standardnotes/forum#214]
I've been trying Standard Notes on ios 11 with the SwiftKey keyboard.  After typing only a couple of words, auto save saves my changes and immediately interrupts the typing experience.  As soon as auto save saves the changes, the screen flashes very briefly and the text moves down a line or two so I can't see the insertion point.  Also, if I'm in the middle of typing a word using swipe-style typing, the swipe gets interrupted and I have to swipe the word again.  This behaviour also happens when using Google's Gboard keyboard. Very frustrating. 

Note that I don't have any trouble with the built-in ios keyboard.  

Thanks!

**Comment by mobitar** [comment]
This has something to do with the encryption that occurs after every key stroke. Please see here: https://github.com/standardnotes/mobile/issues/14

Hoping to investigate a solution soon.

**Comment by mobitar** [comment]
Turns out, this had nothing to do with the encryption and everything to do with the "Saving..." / "All changes saved" subtitle that appears in the nav bar. This has been fixed, and will be deployed in the 2.2 update some time this month :)
