### ISSUE TITLE
TimeStamp In Note

### ISSUE THREAD

**Issue by alazare619** [standardnotes/forum#215]
is there an option to add a timestamp with a keystroke in a note would be useful for note taking in a meeting and like a blotter

**Comment by mobitar** [comment]
Not yet, but I'm planning on adding that to the Action Bar (as a button). Hopefully soon.

**Comment by vrakam** [comment]
Hi, any update on this please ?

**Comment by mobitar** [comment]
Yes you can use the Action Bar action called "Copy date" which will copy the current timestamp to the clipboard, at which point you can paste it anywhere in the note.
