### ISSUE TITLE
Decrypted ZIP file produces folders when a / is in the note title

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/forum#216]
Using either the Windows desktop app (via export as decrypted ZIP) or decrypt.html on Windows (by decrypting a previously exported encrypted TXT file) creates a ZIP file with folders and broken note titles anytime a note title contains a forward slash "/" character.

E.g., if a note called "Work / Jobs" exists, the exported ZIP will contain a "Work" folder with a note called "Jobs"

**Comment by mobitar** [comment]
Noted thanks. Will need to investigate this.

**Comment by MorgothSauron** [comment]
I encountered the same thing. I had a note with a date in it (e.g. 25/05/2018). 

The ZIP file contains a folder structure with the first 2 parts of the date with the note with the year as filename.

```
├── 25
│   └── 05
│       └── 2018-xxxxxxx.txt
```

Similar behavior with a note containing a URL in the title (chrome://settings/cleanup):
```
├── Using chrome:
│   └── settings
│       └── cleanup-xxxxxx.txt
```

**Comment by mobitar** [comment]
This will be fixed in the upcoming desktop release, sometime early next month.

**Comment by virtuallyvlad** [comment]
Tested both the desktop app's decrypted ZIP export and decrypt.html, and both are no longer breaking notes or creating folders.  Thanks
