### ISSUE TITLE
Notes are not available in Offline Mode (iOS mobile)

### ISSUE THREAD

**Issue by idcristi** [standardnotes/forum#2162]
**Describe the bug**
The notes are not available/(loading) when using the app in offline mode.

**Screenshots**
Attached you can find the screenshots from the app.
<img src="https://user-images.githubusercontent.com/17257053/193234427-0c11fbad-a2a7-4b53-91ed-66e2f131868b.jpg" width="250"/>

<img src="https://user-images.githubusercontent.com/17257053/193234443-6dc020a7-a199-48ec-9ec4-e5f43cd4f1c8.jpg" width="250"/>

**Smartphone (please complete the following information):**
 - OS: iOS 16.0.2
 - Version 3.36.18

**Comment by effieeee** [comment]
Hi @idcristi, I was unable to reproduce this on v3.41.3, can I ask you to check on this version as well?

**Comment by idcristi** [comment]
Hi @effieeee, I've checked on v3.41.3 and the issue/bug still exists. I also updated to the latest version which is v3.43.5 and there are not any changes. What I have noticed is that when WiFi or LTE on my phone is enabled, it takes some time (less than 1s) to decrypt the notes, which I think here is the issue. Perhaps an internet connection is required for decryption. In older version < 3.36 I was able to use Standard Notes in offline mode.

**Comment by effieeee** [comment]
Hmm, an internet connection is definitely needed to download and decrypt the notes for the first time, but after that, the app should be able to load the local copies for you when you're offline. May I know if you've already tried reinstalling the app as well? In case you use iCloud for backup up app data, please also try removing Standard Notes there before reinstalling the app, as instructed here: https://docs.standardnotes.com/troubleshooting/reset-apps/#ios

**Comment by idcristi** [comment]
I tried reinstalling the app and got the following issue when I logged in. Restarted the app and notes loaded successfully but still still not able to get access in offline mode.
<img src="https://user-images.githubusercontent.com/17257053/196517971-4362f90c-7546-40d0-8ec5-58fe2dd3adff.jpeg" width="550"/>

**Comment by idcristi** [comment]
The problem is fixed within version 3.46.5
