### ISSUE TITLE
can't logon/continue from the password service access info on Linux Mint 21 (snap)

### ISSUE THREAD

**Issue by thob** [standardnotes/forum#2164]
No "Continue" button
![2022-10-02_12-18](https://user-images.githubusercontent.com/755337/193449282-aa1dbeb8-0683-44f0-8899-fc9a519ff28e.png)

Appimage works

**Comment by effieeee** [comment]
Hi @thob, just wanted to ask if this is still occurring on the latest version of the snap?

**Comment by thob** [comment]
Worked for me, I believe I didn’t understand that the word was hyperlinked ;-)
