### ISSUE TITLE
[android app] Stuck forever on "Generating Keys"

### ISSUE THREAD

**Issue by dok-prog** [standardnotes/forum#2165]
**Describe the bug**
When trying to log in (for the first time) on a new android device, I'm stuck at "Generating Keys" and cannot access to my notes.

**To Reproduce**
1. go to settings fill email and password 
2. Click on 'Sign In'
3. The app freezes at "Generating Keys"

**Expected behavior**
To be able to log in.

**Screenshots**
Doesn't seem necessary

**Smartphone (please complete the following information):**
 - Device: tablet ASUS MeMO Pad (ME103K)
 - OS: Android 5.0.1 Lollipop
 - StandardNotes app from F-droid version 3.36.13
 - the apk directly from standardnotes was also tested.

**Additional context**
1) If I type the wrong password, I receive the message "wrong password", normal
2) I tried uninstalling the app and reinstalling it : no success
3) I tried to install the APK directly from the standardnotes website instead of f-droid : no success
4) I also tried the "remove data". After removing the data I can launch again StandardNotes and try again to log in but without any success.
5) I changed my password and tried again, without any success
6) I use StandardNotes on my desktop, no problem
7) I use the StandardNotes android app on my smartphone (Android 9) without any problem.

**Comment by effieeee** [comment]
Hi @dok-prog, if you're still encountering this issue, may I know if this happens even when you switch to the new mobile view on the latest version of the app? (v3.41.3)

**Comment by dok-prog** [comment]
I just made the test by switching to the new mobile view and sadly it's not working. I am on a freshly installed v3.41.1 from f-droid. Same problem, it gets stuck indefinitely.

**Comment by effieeee** [comment]
I see, though the f-droid package should also retrieve the one that's directly on our repository, may I know if it makes any difference if you download the apk directly from [our repo](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fmobile%403.41.10)? Please also try to [clear the app data](https://docs.standardnotes.com/troubleshooting/reset-apps/#android) if the issue persists!

**Comment by dok-prog** [comment]
Effieeee, I just installed 3.41.10 from your repo. The behaviour is exactly the same. I do frequently clear the app data because after trying to log in (unsuccessfully) it is impossible to launch again the app if I do not do it.

I don't know if this is of any help but after trying to log in, I can see in android's app info that there are 4.4Mb of data downloaded and 296Kb in the cache.

**Comment by effieeee** [comment]
Thanks for testing out the apk from our repo. What about when you sign into the web app through your affected device's browser? Does it also get stuck at generating keys when you sign in from there?

**Comment by dok-prog** [comment]
It works fine in the browser (in several browsers even) and that is exactly what I do.

**Comment by myreli** [comment]
Hi @dok-prog! I'm currently triaging older issues. Are you still facing this problem?

**Comment by dok-prog** [comment]
Hello myreli,
Yes, I am still facing this problem. But now I see that the last compatible version for my old tablet is the 3.45.5 (3000601) from 2022-11-01 on FDroid, so I suppose that it's over :-) .

**Comment by myreli** [comment]
Thanks for replying @dok-prog. I see 🙁

Unfortunately it's hard to maintain older android SDKs as multiple breaking changes, specially towards security, are made. But hopefully the web version still works on your tablet.

**Comment by dok-prog** [comment]
I totally understand. :-)
