### ISSUE TITLE
Standard Notes opens with blank screen then disappears

### ISSUE THREAD

**Issue by morriwe** [standardnotes/forum#2167]
Will no longer open on my iPhone. Contains many files I need. Is there anyway to access the files from the iphone file system? Please help! 

I have offloaded app and reinstalled - no go - just opens to a blank white screen then goes away. It is apparently running in background but when I select it from open windows/running apps it goes full screen and then drops off main screen. It can still be seen when scrolling through running apps  - just will not allow me to enter my password.

Is there an app available that will allow me to download my files?

**Comment by morriwe** [comment]
any way to download previous version on iphone? I suspect the latest build is the problem/

**Comment by morriwe** [comment]
anyone have any ideas?

**Comment by effieeee** [comment]
Hi @morriwe , I sent you an email from our help inbox with some initial instructions. Please do check it out when you can! 🙏

**Comment by k8oi** [comment]
I have a similar issue - not quite sure if it's the same...

To recreate problem:
1. Reboot phone
2. Open SN - works fine
3. Switch away from SN
4. Open SN again - white screen; no content
5. Switch away from SN
6. Switch back to NS - still white screen; no content
7. Kill NS (Swipe UP) app
8. Switch back to NS - works fine.

IOS 16.0.2 - iPhone 12
SN v3.37.14 (207)

**Comment by effieeee** [comment]
Hi @k8oi, a potential fix for this is coming up in the next update for iOS, still pending for approval on the App Store 🙏
