### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by morriwe** [standardnotes/forum#2168]
Iphone app opens briefly with white screen - never takes me to the login screen. Where can I download and install earlier versions of software. I have important info in my app that I cannot access since upgrade.

HELP

**Comment by morriwe** [comment]
Anyone there?

**Comment by Universal-Igloo** [comment]
I have nothing to do with the Standard Notes team and my suggestion may be wrong. I just highly doubt you will get a response from them, so am attempting to help:

The easiest thing to do would be to sign in to the standard notes web app on either your iPhone or your computer, that works just like the standard notes app, so you have all your info there.

**Comment by effieeee** [comment]
Fixed here! https://github.com/standardnotes/forum/issues/2167
