### ISSUE TITLE
iphone standard notes app not syncing new notes

### ISSUE THREAD

**Issue by weaweast** [standardnotes/forum#2169]
**Describe the bug**
Since a few days: Apple iphone app don't sync new notes that are made with apple computer app. Old notes are syncing good.

**To Reproduce**
1. Make a note in standard notes app on apple computer
2. open iphone standard notes app
3. the last notes don't appear in iphone app

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Computer MacBook Pro (2019) 
 - Mac montery 12.6 
 - 21G115

**Smartphone (please complete the following information):**
 - Device:  Iphone SE (old)
 - OS: 14.8.1

**Additional context**
On iphone: Did logout of standard notes app and removed the app. Download app again and login. The same problem.

**Comment by effieeee** [comment]
Hi @weaweast, may I know if you still encounter this issue on the latest app, and if it occurs even when using the new mobile view?

**Comment by weaweast** [comment]
Hello Effie, it is working 👍🏻
