### ISSUE TITLE
Inviting another person doesn't work, if they don't have an account. (Standard Notes Professional)

### ISSUE THREAD

**Issue by Barnados** [standardnotes/forum#2172]
**Describe the bug**
If the E-Mail Adress has no Account and creates an account afterwards the invitation failes and you get an error message.
(Retried in the Webapp and on the andoid application. Bug is still there)

**To Reproduce**
1. **User A** Go to _Preferences -> Account -> Subscription Sharing_
2. **User A**  Invite a **user B** via E-Mail
3. **user B** Click on the invitation
4. Error: 
`{"meta":{"auth":{},"server":{"filesServerUrl":"https://files.standardnotes.com/%22%7D%7D,%22data%22:%7B%22success%22:false%7D%7D`

**Expected behavior**
For **User B**: Go to a new account screen, if no account has already that e-mail.
For **User A**: An option to resend the invitation link.

**Desktop (please complete the following information):**
 - OS: android
 - native Application
 - Version Latest: 3.23.198

**Smartphone (please complete the following information):**
 - Device: Android 12, OnePlus Nord
 - native application

**Comment by effieeee** [comment]
Hi @Barnados, thank you for your report! Though the subscription sharing feature really does require an account for the invited email at the moment, User A in your scenario should now at least be able to cancel an invite and resend the invite to User B!

**Comment by Barnados** [comment]
@effieeee I got it working with another e-mail adress. The only issue remains, that my current used e-mail is "blocked": Resending the Invitation doesn't resend the invitation link to that e-mail on my case. Is that an issue, that you could replicatee?

**Comment by effieeee** [comment]
I see, I can have this checked for you on the backend in that case. Can you send us a message at help@standardnotes.com? Please indicate your main account email that holds the subscription, as well as the account email that you were trying to send an invite to!
