### ISSUE TITLE
How do I switch back to classic view on iPhone? Not happy with mobile web view

### ISSUE THREAD

**Issue by ggfaulkner** [standardnotes/forum#2173]
I opted to switch from classic view to the new mobile web view and I am not happy with it. It's not usable. How do I switch back to classic?

**Comment by ggfaulkner** [comment]
Please help. StandardNotes web view interface renders the app so clunky its virtually useless on my iPhone. I need to get the classic view back ASAP. I don't have time to deal with this. I need to be able to use my StandardNotes on my phone. Someone, please help. Thanks!

**Comment by Universal-Igloo** [comment]
I have nothing to do with the Standard Notes team and my suggestion may be wrong. I just highly doubt you will get a response from them, so am attempting to help:

The easiest thing that should hopefully work - uninstall and then reinstall the app. Does that fix it?

**Comment by effieeee** [comment]
Hi @ggfaulkner, I recall responding to a similar issue in the help inbox, but apart from the suggested method above, if you're still in the new mobile view, you can find the option to switch back as described here: 

1. Tap on the **top left menu icon**, then on the **Open preferences** icon on the bottom right. 
2. Once you're in the Preferences menu, switch to the **General** preferences using the list at the bottom
3. Under **Defaults,** you will find the option to switch back to the Classic Mobile Experience

Please feel free to reopen this if you encounter any other issues with switching back! 🙏
