### ISSUE TITLE
Theme not persisting

### ISSUE THREAD

**Issue by drohm** [standardnotes/forum#2174]
**Describe the bug**
I'm selecting a built-in theme from the quick settings menu, the theme then gets applied.  If I then restart the application, I get a dialog in the lower right asking me to either "keep the current theme" or go back to the default.  If I don't answer it within the time constraints (5secs) it automatically goes back to default.  I don't understand this behavior.  I manually selected a theme and I have to confirm the theme every time I start the application?  I'm guessing this isn't a bug and is by design, but why?

**To Reproduce**
1. Open the Quick Settings menu
2. Select any theme besides the default theme
3. Restart the application
4. Observe the dialog in the lower right asking about the theme

**Expected behavior**
The expected behavior is when I select a theme, it sticks until I select another theme.

**Desktop (please complete the following information):**
 - OS: Fedora 36 KDE
 - Browser Brave v1.44.108
 - AppImage 3.23.193

**Comment by drohm** [comment]
Is this  behavior happening due to the "Use system color scheme" option in settings?  Its enabled by default.  I just turned it off and I didn't get prompted after restarting the application.  If that's the case, it might be helpful to mention this setting in the dialog that pops up when this option is enabled as it wasn't very intuitive.

**Comment by effieeee** [comment]
Hi @drohm, yup, that dialogue appears if you have "Use system color scheme", and your currently selected theme doesn't match the one that is indicated there for your system's current color scheme, apologies for the confusion! 🙏
