### ISSUE TITLE
[Help Wanted] Huge indent in plain text

### ISSUE THREAD

**Issue by vstepaniuk** [standardnotes/forum#2176]
**Describe the issue**
Why there is such a huge indent in plain text notes?

**To Reproduce**
1. Create new **plain text note** on the web or in the opted-in new mobile experience.
2. Type a character

**Expected Results**
Normal indent like in Apple Notes or Google Docs

**Screenshots**
Web
![Standard Notes web](https://user-images.githubusercontent.com/24701640/194895076-fcc63d89-28bf-4315-bcc2-1ae9b6ef4e8d.jpeg)
 
App (new)
![Standard Notes app](https://user-images.githubusercontent.com/24701640/194897673-231f01ba-7d8a-4369-825d-a84985e1fd56.jpeg)

Apple Notes (for comparison)
![Apple Notes](https://user-images.githubusercontent.com/24701640/194894894-98b62139-5962-4a4c-95d7-824c77026af1.jpeg)

Google Docs (for comparison)
![Google Docs](https://user-images.githubusercontent.com/24701640/194897074-9b3fcbf3-a13c-4ac9-9561-3bff73ea4582.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.6.1
 - Browser: Safari
 - Version: 3.41.4

**Extra**
Same issue on the Desktop

**Comment by vstepaniuk** [comment]
This happens when typing longer lines:
![D6AB4CE7-E5B2-4FA9-84BB-621AA7932DC9](https://user-images.githubusercontent.com/24701640/194923505-2313570d-73fd-40a1-abb1-f4f760df1d1c.jpeg)

![AF08506E-3262-4C80-BCA3-130F3470C6B6](https://user-images.githubusercontent.com/24701640/194923513-db025011-d6cc-4cfb-a9fe-4917bdef11e5.jpeg)

![0E23F3F6-B9E0-4778-A87A-69ABB8FC1E43](https://user-images.githubusercontent.com/24701640/194923517-b8916327-0314-4f53-b609-12543aa0a14a.jpeg)

Then after reopening the note:
![1F9428A6-46C6-4FF2-945F-320F7BCF50B4](https://user-images.githubusercontent.com/24701640/194923519-f1e62d22-c463-4fa9-b0ee-1f3fd0185e2a.jpeg)

![0B358FD3-2BBD-4968-966C-4011FE7B783F](https://user-images.githubusercontent.com/24701640/194923521-d1e08033-e320-4230-a531-8a13effb502b.jpeg)

**Comment by effieeee** [comment]
Hi @vstepaniuk, hmm, I'm afraid I haven't been able to reproduce this on iOS so far :( Is the indent only present on the new mobile view? I noticed your reproduction steps mentioned that you can try to create the note from the web app as well, so I was wondering if you perhaps see this indent on the web app too?

**Comment by vstepaniuk** [comment]
Only on the new, the old one is ok:

![FCEDF90A-9E68-4FFE-AB7A-ECF14DE3DD47](https://user-images.githubusercontent.com/24701640/195151692-148633af-b3f7-428c-8484-70d27e133283.jpeg)

![0353BFE7-7216-4026-957F-320FB966C67F](https://user-images.githubusercontent.com/24701640/195151652-c55a383e-1d89-4d82-9b29-c4eabe137b7b.jpeg)

**Comment by vstepaniuk** [comment]
Also I have a free account, and in my account the indent is present - both in the new mobile and web - but in the demo (professional account) - it's not:

![BDFAEC03-970B-42D1-A2A1-7E13012E9CF9](https://user-images.githubusercontent.com/24701640/195154750-be5b2e96-310f-4c8c-b51d-710e0e3c7d7d.jpeg)

![11971400-CD9F-407F-A7D5-28A3B8941542](https://user-images.githubusercontent.com/24701640/195154732-41d8cec0-03af-4e65-be7b-f00836f4cb9d.jpeg)

**Comment by effieeee** [comment]
I see, quite odd, I tried to test this out on a free account too, but I wasn't able to replicate it for the new mobile UI and the actual web app on iOS either :( Does the indent stay even after continuing to type text on the note?

**Comment by vstepaniuk** [comment]
It's Margin Resizers..

**Comment by vstepaniuk** [comment]
try enabling them

**Comment by effieeee** [comment]
Hi @vstepaniuk, I'm sorry that I wasn't able to get back to you at the time, but indeed it was the [margin resizers](https://github.com/standardnotes/forum/issues/2206#issuecomment-1281195202) that was causing this. Currently the mobile apps don't respond to this functionality in the preferences menu by default, so it should no longer be an issue moving forward 🙏
