### ISSUE TITLE
[Help Wanted] web app requirement for Chrome OS?

### ISSUE THREAD

**Issue by ElTopo** [standardnotes/forum#2179]
**Describe the issue**
Hello,
I am wondering what's the oldest version of Chrome OS that still works with Standard Notes web app (https://app.standardnotes.com/). 

I have an old ChromeBook which Google stopped supporting several years ago, the Chrome OS' version: 
Version 76.0.3809.102 (Official Build) beta (64-bit)

I have been using the ChromeBook to access https://app.standardnotes.com. The web  app worked well until recently it stopped working with an "Unable to sync" error message at the bottom right, with 0 notes displayed. I am still logged in with the correct email, 

So my question is: is Chrome 76.0.3809.102 too old for the web app?

**To Reproduce**
1. go to https://app.standardnotes.com/, log in an account with notes
2. the web app does not show any notes, there's an error message saying "Unable to sync".

**Expected behavior**
the web app shoud sync and show my notes..

**Desktop (please complete the following information):**
Chrome OS, Version 76.0.3809.102 (Official Build) beta (64-bit)

**Comment by effieeee** [comment]
Hi @ElTopo, while I'm not entirely certain if your ChromeOS version would matter for the web app, I wanted to ask when you last recalled the web app working properly on your device? You mentioned that it used to work until recently?

**Comment by ElTopo** [comment]
@effieeee I am not 100% sure, the last time (might be 6 months ago, but definitely earlier this year) it worked without problems. I found it started showing "Unable to sync" 2 weeks ago.

**Comment by effieeee** [comment]
I see, may I know if you've tried to clear the site data for the web app as well? You'll find some instructions for that in [this link](https://docs.standardnotes.com/troubleshooting/reset-apps/#web) if needed!

**Comment by myreli** [comment]
Hi @ElTopo, are you still facing this issue?

**Comment by 1ibno** [comment]
I, too, am having an issue with app.standardnotes.com on my old Chromebook (Build 84.0.4147.136 (Official, 32-bit)). I can access the web page, but cannot log in, instead getting an 'Unknown login error' when attempting to do so. Fortunately, I am still able to use the playstore app.

**Comment by effieeee** [comment]
Hi @ibdubbya, I apologize for the very late response, but in case you might still be encountering issues with the web app on your Chromebook, please contact us at help@standardnotes.com with your account email, since this might involve account related investigations. I'll also be closing this thread for now 🙏
