### ISSUE TITLE
Desktop shortcuts

### ISSUE THREAD

**Issue by justinmoon** [standardnotes/forum#218]
The Ubuntu instructions say "If you're prompted to create desktop shortcuts, choose Yes."

I saw this prompt but accidentally closed it. It seems this would [these sorts of files](https://wiki.archlinux.org/index.php/Desktop_entries) allowing the app to be visible using [dmenu](https://wiki.archlinux.org/index.php/dmenu) in i3?

Right now I'm not sure how to launch to app without using the command line ...

**Comment by superquest** [comment]
I tried that, but get a prompt second time.

I'll try again.

**Comment by mobitar** [comment]
> but get a prompt second time.

Get or don't get?
