### ISSUE TITLE
Experimental Feature: Advanced Checklist not working

### ISSUE THREAD

**Issue by glenn-holmgren** [standardnotes/forum#2181]
**Describe the bug**
Cannot open my advanced checklist, even after reinstalling it from https://github.com/standardnotes/plugins

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/73921126/195246438-d098d4e8-8371-4094-a417-eb5ff51d850a.png)

**Desktop (please complete the following information):**
 - Device: Laptop
 - Browser [APP]
 - Version 3.23.207

**Additional context**
Viewing an existing Advanced Checklist or making a new one will pop out this error.

**Comment by atmoio** [comment]
Should be fixed now, see https://github.com/standardnotes/plugins/issues/4.

**Comment by glenn-holmgren** [comment]
Its working now. Problem solved. Thank you very much @moughxyz

**Comment by glenn-holmgren** [comment]
Issue Solved.

**Comment by glenn-holmgren** [comment]
@moughxyz , sorry to disturb, but it seems to be broken again. :(

**Comment by effieeee** [comment]
Hi @glenn-holmgren, is it appearing broken only on the desktop app? If so, can I ask you to try out the following:

1.  Click on the top left menu of the app, then choose **Help > Open Data Directory**
2.  Once the directory is open, go to the **Extensions** folder
3.  Look for a folder labelled, `com.sncommunity.advanced-checklist` 
4.  Delete that folder, then attempt to reinstall the Advanced Checklist again using the install link in the [community plugins repo](https://github.com/standardnotes/plugins)

**Comment by alanthemarmot** [comment]
Hi, I'm currently getting this error on web/desktop/mobile for this extension. Was working fine a couple of days ago. I can open a separate issue if required.

<img width="550" alt="Screenshot 2022-10-17 at 21 02 48" src="https://user-images.githubusercontent.com/3315948/196272251-9f22537b-1496-43ab-8ab0-2c3ccc4b1dc9.png">

**Comment by glenn-holmgren** [comment]
> Hi @glenn-holmgren, is it appearing broken only on the desktop app? If so, can I ask you to try out the following:
> 
>     1. Click on the top left menu of the app, then choose **Help > Open Data Directory**
> 
>     2. Once the directory is open, go to the **Extensions** folder
> 
>     3. Look for a folder labelled, `com.sncommunity.advanced-checklist`
> 
>     4. Delete that folder, then attempt to reinstall the Advanced Checklist again using the install link in the [community plugins repo](https://github.com/standardnotes/plugins)

@effieeee, strange that it must be done manually, but it works. Thank yo very much!

**Comment by alanthemarmot** [comment]
> Hi @glenn-holmgren, is it appearing broken only on the desktop app? If so, can I ask you to try out the following:
> 
>     1. Click on the top left menu of the app, then choose **Help > Open Data Directory**
> 
>     2. Once the directory is open, go to the **Extensions** folder
> 
>     3. Look for a folder labelled, `com.sncommunity.advanced-checklist`
> 
>     4. Delete that folder, then attempt to reinstall the Advanced Checklist again using the install link in the [community plugins repo](https://github.com/standardnotes/plugins)

Tried this as well as upgrading to latest version and it worked as well. Had to uninstall the Beta Advanced Checklist via the Advanced options as well for it to kick in though. Thanks.

**Comment by effieeee** [comment]
Glad it helped! Indeed it's quite strange that the local directory wasn't removed for the Advanced Checklist editor, so I've taken note of it for investigation 😢

**Comment by tx71** [comment]
Just wanted to mention that I had the same issue, but re-adding the plugin fixed it for me as well. 

I got one small issue though after this fix: in the Android app, advanced checklist notes are always in white theme, they won´t change to any other theme. No issues with other notes, also no issues on desktop app (AppImage).

**Comment by effieeee** [comment]
@tx71 Thank you for mentioning this! I was able to reproduce this on Android as well, so I've opened it as an issue on the community plugins repo: https://github.com/standardnotes/plugins/issues/6#issue-1424346544
