### ISSUE TITLE
[Android] Unable to attach file to note

### ISSUE THREAD

**Issue by frodomo** [standardnotes/forum#2187]
**Steps to reproduce**
Open a note (markdown in my case) and press on the attach files icon (paperclip).
Press the "Attach files" button.
The application selector opens and I select the "Files" application
I select the files I want to attach 

**Behaviour**
Nothing happens. I stay on the file browser or sometimes go back to the main screen of the phone

**Versions**
StandardNotes : 3.41.10 with the new mobile experience enabled
Android 10

**Comment by myreli** [comment]
Hi @frodomo! Are you still experiencing this issue?

**Comment by frodomo** [comment]
Hi @myreli,

I just tried to reproduce the issue, it does not happen anymore.
Thanks for the follow up.
