### ISSUE TITLE
Unable to create a new note in desktop experience & window application (page is stuck)

### ISSUE THREAD

**Issue by SrinivasanPJ** [standardnotes/forum#2188]

**Comment by few4i** [comment]
Me too - I'm stuck on desktop.  I usually log in via chrome.

"The note you are attempting to save can not be found or has been deleted.  Changes you make will not be synced.  Please copy this notes text and start a new note."

**Comment by few4i** [comment]
More information - I don't really belong on github as not much of a programmer so appreciate the group.

Chrome on PC:  106.0.5249.119
Window 10 pro

Actions taken:  Sign out of account, empty cache in browser

It seems to me that I get stuck when creating a new note where I inherit tags from another.  It seems to me in fact that it tries to also inherit attached files if I am in my file tree.  When I have this stuck behavior the program is not trying to keep in sync - I don't see the green checkmark in the upper left.

Work-around:  Start new note from untagged "Notes" view.  Maybe with some voodoo of typing a bit first in an untagged note.  With this I can start a new note and  get green checkmark and all normal behavior.

Appreciate indulgence of group.  Many thanks

**Comment by ccrowner** [comment]
I have the same problem - unfortunately the Work-around does not work for me. I can't create a note anywhere without
"The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this notes text and start a new note."

**Comment by effieeee** [comment]
Should be fixed in the latest versions!
