### ISSUE TITLE
SN Crashing iOS 16 beta 5 and iPadOS 16 beta 6

### ISSUE THREAD

**Issue by jjulius50** [standardnotes/forum#2189]
**Describe the bug**
I have upgraded my iPhone 13 to iOS 16 beta 5 and my iPad to ipadOS 16 beta 6.  On the iPhone, every time I try to create a new note or open an existing note the SN app crashes. On my iPad, SN crashes every time I open the app.
**To Reproduce**
1. Go to ' the app on iOS 16 beta 5 or iPadOS 16 beta 6.'
2. Click on 'Click on the app and it crashes'

**Expected behavior**
The apps to open and be able to open and create notes.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPone 13/iPad 12.9 inch-4th generation
 - OS: iOS 16 beta 5 and iPadOS 16 beta 6
 - Browser [e.g. Brave, safari]

**Additional context**

**Comment by balashx** [comment]
This crash actually occurs on iSO 16.0.3 and iPhone 14 Pro.   Try to open or create a note with of any type other than plan text and the application crashes. 

It's possible to view or create notes as plan text.  But use any other format and the application crashes.

**Comment by jjulius50** [comment]
balashx, thanks for the heads up. I made the change to the iPhone version, and it allows me to access my notes, though not in the format I would like, as you know. I cannot apply this temporary fix to the iPad version, since the app crashes before opening.

**Comment by balashx** [comment]
In iOS changing the preference from “Classic mobile experience” to new mobile experience (Preferences -> General -> Defaults) will stop the application from crashing on RTF. It seems they've stopped testing the classic more already.

**Comment by jjulius50** [comment]
Balash, thanks for this solution.


Jeff

Jeffrey Julius

***@***.***

Notice: This communication is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential or exempt from disclosure. If you have received it in error, please advise the sender by reply email and immediately delete the message and any attachments without copying and/or disclosing the contents. Thank you.



________________________________
