### ISSUE TITLE
Is there any way to make sure that the page https://app.standardnotes.org/ is original?

### ISSUE THREAD

**Issue by dyura** [standardnotes/forum#219]
Many organizations are using man-in-the-middle TLS interception on their proxy servers for monitoring user activity.  I am sure these solid organizations don't do anything else, than decrypting https traffic and logging it. However,  when the authentication certificate  is not original, it is possible to inject JavaScript into any page and steal credentials. Is there a way to identify when https://app.standardnotes.org/ is not original?

Thanks,
Yury

**Comment by mobitar** [comment]
There's no easy way to do this. I have seen some experiments using browser extensions and service workers, but this is still very nascent.

**Comment by dyura** [comment]
I have another related question about privacy. Currently I work on a company's computer under company's network with installed HTTPS monitoring system. So, HTTPS traffic is not encrypted inside the company. The idea that I cannot control which hands are touching my data makes me feel uncomfortable. Well, I don't worry about phishing, but reading logs could be pretty feasible. Standard Notes encrypts data on the client side. However, as I understand (I didn't read sources) the generated private key is stored on disk. So, it is hack-able. Or does passcode lock also encrypt the private key?

**Comment by mobitar** [comment]
On desktop/web, your private keys are stored on disk. However, if you add a Passcode Lock, this will encrypt your private keys on disk.

On mobile, private keys are stored on your devices secure keychain, with or without a passcode.

And on both, no sensitive (non-encrypted) data is ever sent through the wire, so it shouldn't matter too much that your traffic is being watched. The only exception is when you first login/register, a one-way hash of a key derived from your password is sent to the server for authentication.

**Comment by dyura** [comment]
Thank you for the explanation!
