### ISSUE TITLE
Can't create notes in Chrome web app

### ISSUE THREAD

**Issue by ccrowner** [standardnotes/forum#2190]
any attempt (in top level Notes or subfolder) to add new note produces:
The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this note's text and start a new note.

1. on main Notes view
2. Click on add + button
3. either change default title or add text to note body
4. pops up "The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this note's text and start a new note."

Expect to successfully add a note

chrome browser

v3.74.0

Google ChromeOS Version 105.0.5195.134 (Official Build) (64-bit)

Have repeatedly cleared site data - no change

**Comment by ccrowner** [comment]
fixed in v3.76.0 thanks

adding issue with tags

**Comment by effieeee** [comment]
Tag issue: https://github.com/standardnotes/forum/issues/2193
