### ISSUE TITLE
[RESOLVED] Android SN app crashes when opening NON-"Plain Text" notes.

### ISSUE THREAD

**Issue by Brody-Wood** [standardnotes/forum#2192]
**Describe the bug**
- While using the SN app opening a Plain Text note will work as expected.
- When opening any other type of note it will load for a moment and the crash to the home screen with a Android OS pop-up asking how you want to handle the crash. 
- Switching the note back to Plain Text allows me to open it.
- No issues are seen when using desktop.
- I can not technically confirm that "All" other note types crash but I have specifically confirmed that Authenticator, Spreadsheet, Code, Basic Checklist, Alternative Rich Text, Classic Rich Text, and Basic Markdown all result in crashes

**To Reproduce**
- I am unsure of how to reproduce the behavior.
- I don't believe this was caused by an app or OS update as it happened mid-day after I had already successfully used the app multiple times that day. My phone did not restart in-between. 

**Smartphone**
 - Device: Samsung Galaxy Note 9
 - OS: Android Version 10
 - App Version: 3.41.10 (I just re-installed)

**Additional context**
- I have, in this order, force closed the app, uninstalled the app, restarted my phone, and then re-installed the app. There was no change. I then performed a soft-reset on my phone and there was still no change.
- I have noticed that sometimes before a Classic Rich Text note crashes it will display the ribbon at the top of the screen that would allow you to change font, highlight or bold text, change text alignments, etc. It then quickly crashes.

**Comment by balashx** [comment]
In iOS changing the preference from “Classic mobile experience” to new mobile experience (Preferences -> General -> Defaults) will stop the application from crashing on RTF. Give that a try.

**Comment by grantcooksey** [comment]
I'm having the same issue here on a Galaxy S8 and went through the same steps (uninstall/reinstall) without any luck,

**Comment by effieeee** [comment]
Hi @grantcooksey, were you also able to try enabling the new mobile experience as described above? If the app crashes before you can even get to the settings menu, you can try to [clear the app data](https://docs.standardnotes.com/troubleshooting/reset-apps/#android) first, but please take note that you can only do this if you have been syncing notes to your account online.

**Comment by Brody-Wood** [comment]
> In iOS changing the preference from “Classic mobile experience” to new mobile experience (Preferences -> General -> Defaults) will stop the application from crashing on RTF. Give that a try.

I have just tried exactly this, with no further steps, and it has resolved the issue. 
NOTE: The path to this setting (While using Android and Classic mode SN) is just Settings (Gear Icon) and then one of the top options is New Mobile Experience Preview.

Thank you! I actually hadn't even realized that "New Mobile Experience Preview" so that looks really interesting to try and I've been using SN a lot recently so having this fixed is very helpful.
