### ISSUE TITLE
tagging notes has faulty search

### ISSUE THREAD

**Issue by ccrowner** [standardnotes/forum#2193]
drop down when entering tags now includes searches within titles of notes as well as existing tags
if there are existing tags then they will come first in drop down
however, I found case where when entering first letters of existing tag only the note titles with those letters and not the existing tags show in drop down (i.e. search missed existing tags with those first letters)

In note enter tag

I don't see how searching note titles are useful for tagging?. However, there is a bug in the search.

ChromeOS
v3.76.0

**Comment by effieeee** [comment]
Hi @ccrowner, can you provide a sample tag name and note title to replicate the issue?

Also, the note titles that appear on the drop down are actually a new note linking feature 😊 If you select a note title from the list, you'll then be able to directly jump to that note by double clicking on it from the tag/link entry box

**Comment by ccrowner** [comment]
1. create tag "Poems"
2. create note with "poet" or "poem" in title
3. create new note and when assigning it a tag enter "poe" - 
4. ? is the existing tag in the list? 
5. how about when you enter "poem"?

pretty sure something is wrong with the search that populates the drop down - search seems straight-forward, so it's odd

thanks for explaining the new note linking feature - I tried it and can see the usefulness of it. Just would like existing tags to always successfully make it to the top of the list.

**Comment by effieeee** [comment]
Thanks as well for the repro steps! I've been trying this out, though I'm afraid I haven't yet encountered an instance where either the "Poems" tag, or the note name were not included in the drop down list:
![image](https://user-images.githubusercontent.com/54989748/195987488-b1cea535-dcae-4615-a78d-2fd03489aed6.png)

I'll keep an eye out for this behavior though!

**Comment by ccrowner** [comment]
perhaps its because of the number of matches?

here are some screen shots

[image: image.png]

[image: image.png]

**Comment by effieeee** [comment]
Hi @ccrowner, it looks like the images were not properly uploaded 😅

**Comment by effieeee** [comment]
A workaround for this was made, such that at least 5 results of each type are included in the linking dropdown list now!
