### ISSUE TITLE
New mobile UX layout complaint

### ISSUE THREAD

**Issue by dogugotw** [standardnotes/forum#2196]
**Describe the bug**
Entry format for checklist displys only part of each entry. App is running on Samsung S22 Ultra, latest rec of OS and Standard Notes

**To Reproduce**
Enter a set of checklist items. Items display with proper justification and word wrap.
Exit the app
Reopen app.
Reopen entered list. Word wrap is gone. List also has a massive lest gutter so not the full width of the phone screen is used.
Change type for entry to rich text.
Exit note.
Reopen. Note, it diplays properly.
Change type back to checklist.
Exit note.
Reopen note. It displays properly.
Exit note and app.
Reopen app and note. Massive left gutter is back, word wrap is gone.

**Expected behavior**
UI displays the expected layout, no wide gutter, checkboxes, and test is left justified with word wrap. Each line uses the full width if the screen.

**Screenshots**

Problem
![image](https://user-images.githubusercontent.com/65558337/195928128-5c7b928c-9889-4ca2-9b41-0735235deb28.png)

What it should look like
![image](https://user-images.githubusercontent.com/65558337/195928206-aefb9b73-f34c-419d-a150-32515afcd459.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Standard Notes App using new ui
 - Version 3.41.10 (3002237)

**Smartphone (please complete the following information):**
 - Device: Samsung S22Ultra
 - OS: Android version 12
 - Browser Brave
 - Version 1.44.05

**Additional context**

**Comment by effieeee** [comment]
Hi @dogugotw, may I know if you also have the **Margin Resizers** enabled on the app at the moment, as described in [this comment](https://github.com/standardnotes/forum/issues/2206#issuecomment-1281195202)?

**Comment by dogugotw** [comment]
Margin resizers are enabled.  I turned it off and recovered the real estate
on the left.

I still have the issue of the text in checkbox entries not word wrapping.
See attached screenshot.

**Comment by effieeee** [comment]
Good to see that disabling the margin resizers helped at least! Do you happen to see the same word wrapping issue while viewing this checklist on the desktop or web app, with the app window minimized such that the similar mobile view is activated?

I also wanted to ask if newly created checklists on your mobile app produce the same issues

**Comment by dogugotw** [comment]
New checklist on the Android app retains word wrap.

All checklists display properly on the Windows app.

All checklists disolay properly on the web app in both full screen mode and
when the window width is shortended to push tab into 'phone' dispay.

Interestingly, the app is now retaining word wrap. Version 3.43.5.  I
cannot say if the version today is identical to when I submitted. Gaaaaaaa,
debugging software is magic! Bad magic.

**Comment by dogugotw** [comment]
Confirmed, the version on my phone today is different from the initial
submission (3.43 today vs 3.41 at submission). Youse all fixed it! Pizza
for everyone!
