### ISSUE TITLE
Unable to switch to classic mobile experience

### ISSUE THREAD

**Issue by Betadawg** [standardnotes/forum#2197]
The latest update 3.43.5 loads the new mobile experience byv default, however, attempting to switch to the classic mobile experience from the General tab only causes the app to return to the authentication screen.

**Comment by effieeee** [comment]
The old UI is no longer accessible on v3.43.5, as we're steadily beginning to implement the new UI as a replacement. If you have certain feedback or bug reports on the new UI, please feel free to open another issue, or email us at help@standardnotes.com!
