### ISSUE TITLE
iPhone app crashes when loading any non-plain text note

### ISSUE THREAD

**Issue by chengp3** [standardnotes/forum#2198]
**Describe the bug**
iPhone app crashes when loading any non-plain text note since 3-5 days ago. The app loads, and after tapping on a note, it says "Loading [something something... it's too fast for me to read]" and then crashes a split second later. I have tried logging in and out and reinstalling the app with no change in behavior. I also tried making a new plain text note, which loads and saves fine. When I change it to any other type of note, it crashes. 

Web app, PC, and MacBook all load notes as expected. 

**To Reproduce**
See above

**Expected behavior**
See above

**Desktop (please complete the following information):**
 - OS: iOS
 - Version: 3.41.10

**Smartphone (please complete the following information):**
 - Device: iphone 13 mini
 - OS: iOS 15.6.1
 - Version: 3.41.10

**Comment by twizzayy** [comment]
Having this same issue on IOS 16 with iPhone SE 2

Probably related to [#2185](https://github.com/standardnotes/forum/issues/2185)

**Comment by chengp3** [comment]
@twizzay-code Go into settings and hit "Opt in to new UI experience" or something similar and it will solve the issue!

**Comment by twizzayy** [comment]
> @twizzay-code Go into settings and hit "Opt in to new UI experience" or something similar and it will solve the issue! 

That has been working so far. Using it about a week.
