### ISSUE TITLE
amazonian

### ISSUE THREAD

**Issue by blackedtin** [standardnotes/forum#220]
Is there an option to 'sync' to my own Amazon s3 account/bucket?  Or digital ocean

I would prefer a service whose business model is not Privacy Raping as is google's.

**Comment by mobitar** [comment]
Two way sync will have to require custom server code. No way around that. One can either self host, or for one way sync (backups), use the cloud providers we have integrations built for, or build their own integration.

[https://github.com/standardnotes/web/issues/206#issuecomment-393744307]
