### ISSUE TITLE
Archived note spontaneously closes when opened from a smart folder.

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#2200]
**Describe the bug**
**bug A)** When an archived note is open, the note closes spontaneously after several seconds (~15 sec) and the interface displays the first note in the current folder.
Sub-bug: The above behavior happens quicker (<10 s) if the note options menu is open.

**bug B)** related bug:
When selecting a toggle (prevent editing, show preview, password protect) for an archived note, the interface closes the note and opens the first note in the current folder.

**To Reproduce**
_Preparation_
**i)** create smart folder with archived notes:
```
!["testfolder", "ignored", "and", [ 
["title", "matches", "^test"],
["", "or", [
["archived", "=", true], 
["archived", "=", false]
] ] 
] ]
```

**ii)** create a note to that matches the smart folder search criteria
```
Note title: test note 001
Content: some text. it doesn't matter. it's a test
```

**iii)** archive the note
 
.

**bug A)**
- Go to a smart folder/tag that contains archived notes.
- open any archived note that is not the first one
- wait 10-20 seconds
--> active note closes, and first note in the folder opens

**bug B)**
- open an archived note, as above
- open note options menu
- select a toggle (protect, preview, pin, etc)
--> active note closes, and first note in the folder opens

**Expected behavior**
The note that is opened by the user should stay open until user decides to navigate away from it.

**Desktop:**
 - OS: Linux (Archlinux)
 - App Version 3.23.1001

**Smartphone:**
 - Device: Android
 - OS: 11
 - App version 3.43.5

**Comment by myreli** [comment]
Hi, @quartertone. Are you still facing this issue? 

I wasn't able to reproduce it (the provided JSON isn't valid, but I tried to replicate it).

**Comment by quartertone** [comment]
I think somewhere along one of the updates this issue went away. I haven't encountered this behavior in a while and I can't seem to recreate it either.
