### ISSUE TITLE
iPhone new mobile UX does not save which note is open after screen lock

### ISSUE THREAD

**Issue by rouspreda** [standardnotes/forum#2204]
**Describe the bug**
I am on an iPhone SE2 running iOS 16.0.3. Just got the 3.43.5 (249) update, but this issue was in the previous update as well. I go shopping, I open up Standard Notes, I go to a specific note that has my shopping list, I hit the power button to screen lock, I find my item, I unlock my phone to open up Standard Notes to check my shopping list note, I am back on the main Standard Notes page, as if I never opened up my shopping list note. I have to go back to my shopping list note, I let my phone lock itself, same thing occurs. My shopping list is a checklist note, but this issue happens w/ any note. Previously, the classic mobile experience never gave me this issue, but [#2197](https://github.com/standardnotes/forum/issues/2197) keeps me from going back to classic. I've already tried to log out, uninstall, soft boot, & re-install, but I am now forced on the new UX experience.

**To Reproduce**
I open up Standard Notes on my iPhone SE2
I go to a specific note
I hit the power button to screen lock - or - I allow my phone to auto screen-lock
I unlock my phone to open up Standard Notes to check my specific note
I am back on the main Standard Notes page, as if I never opened up my specific note
I have to go back to my specific note

**Expected behavior**
I open up Standard Notes on my iPhone SE2
I go to a specific note
I hit the power button to screen lock- or - I allow my phone to auto screen-lock
I unlock my phone to open up Standard Notes to check my specific note
I am back on the specific note I was on before I screen locked my iPhone

**Screenshots**

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 - Device: iPhone SE2
 - OS: iOS 16.0.3

**Additional context**
I originally went to the new UX experience due to Issue [#2185](https://github.com/standardnotes/forum/issues/2185). Checklist notes do work for me & are formatted correctly; just the issue listed above makes it frustrating.

**Comment by rouspreda** [comment]
New information - 

After trying unsuccessfully to go back to the classic UX experience mentioned above, I logged back into my Standard Notes app on my iPhone to re-create my issue, & now the issue is resolved. I can now go to any note, screen lock, unlock my iPhone, & the note I was last on is still open & available.

**Comment by effieeee** [comment]
Hi @rouspreda, good to hear that the issue was resolved somehow 🙏
