### ISSUE TITLE
unable to create new note in tagged folder from desktop application (windows 10)

### ISSUE THREAD

**Issue by SrinivasanPJ** [standardnotes/forum#2205]
It is  getting some popup message " The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this note's text and start a new note". It is getting stucked.

1. Go to notes desktop application
2. Click on any folders in left side menu
3. create new note in tagged folder
4. read the error

Laptop:
 - OS: windows 10 pro
 - Standard Notes Application Version [v.3.23.212]
 - Model - Dell Inspiron 15 3000
 - Processor - i5-11th Gen
 - system type - 64 bit Operating system

Please fix the bugs in Latest version.

**Comment by effieeee** [comment]
Hi @SrinivasanPJ, I can't seem to replicate this on [v3.23.218](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.23.218) in particular, may I know if you've tried updating to this one?

**Comment by effieeee** [comment]
Can confirm that a fix for this was pushed a few days after I commented above
