### ISSUE TITLE
[Help Wanted] New Mobile Experience has giant margin that wastes more than 1/3 of the screen!

### ISSUE THREAD

**Issue by ggfaulkner** [standardnotes/forum#2206]
**Describe the issue**
This morning, to my dismay, I found that the classic mode is no longer available and when I open a note in the new mobile experience on my iPhone there is a giant margin on the left that wastes more than 1/3 of the screen! I have been unable to find any setting that can be adjusted to fix this serious problem. I am hoping that there is some kind of easy fix that I just have not been able to figure out because I can't believe that you would eliminate the classic mode when the new mobile experience has a problem this serious. Is this an unusual problem I am having? I love Standard Notes, but I am deeply disappointed and frustrated by this disruptive change which is a complete deal-breaker as is. 

**To Reproduce**
1. Log in to the Standard Notes on iPhone
2. Tap a note

**Expected behavior**
I expect there to be a small reasonably sized margin in the text area so that most of the screen width can be used for notes.

**Screenshots**

![IMG_38905F847947-1](https://user-images.githubusercontent.com/115290239/196180500-5ea5c1a3-d214-4292-86e0-21a19ca30599.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 16.0.2 (20A380)
 - Browser ? I don't know. I'm logging into Standard Notes App, not a browser.
 - Version: Version of what?

**Comment by effieeee** [comment]
Hi @ggfaulkner, hmm, have you also checked **Preferences > General > Tools** in case the **Margin Resizers** are enabled? The margin resizers still aren't well adapted for the mobile view, so you may need to turn this off if it's still enabled on your account.
![image](https://user-images.githubusercontent.com/54989748/196241650-94829056-2cb4-46b6-af7b-ca1a7b95d991.png)

**Comment by ggfaulkner** [comment]
That did it! Thanks! I knew there must be an easy solution, I just couldn’t find it.

From: Effie Beldia ***@***.***>
Reply-To: standardnotes/forum ***@***.***>
Date: Monday, October 17, 2022 at 1:17 PM
To: standardnotes/forum ***@***.***>
Cc: Greg Faulkner ***@***.***>, Mention ***@***.***>
Subject: Re: [standardnotes/forum] [Help Wanted] New Mobile Experience has giant margin that wastes more than 1/3 of the screen! (Issue #2206)


Hi @ggfaulkner<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ggfaulkner&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=ow97cKQHOpUVlWq8h8kmAR4zJVe5XIv9nadU5aW-fRc&m=7_ABVQMIRAl4tGI8gM2GnSHmhtqmidwfoVnF9IeWRSA&s=Y1hZWmOfI-XAW-4Vs8SCLE8drrdYFRkV4fTZyPWVqYk&e=>, hmm, have you also checked Preferences > General > Tools in case the Margin Resizers are enabled? The margin resizers still aren't well adapted for the mobile view, so you may need to turn this off if it's still enabled on your account.
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_54989748_196241650-2D94829056-2D2cb4-2D46b6-2Daf7b-2Dca1a7b95d991.png&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=ow97cKQHOpUVlWq8h8kmAR4zJVe5XIv9nadU5aW-fRc&m=7_ABVQMIRAl4tGI8gM2GnSHmhtqmidwfoVnF9IeWRSA&s=e0X-wJRwuY9RsbcuFBiVFcp2ImVklGd0eqDULLZax4g&e=>
