### ISSUE TITLE
Switch to Classic Mobile Experience does not work on iOS

### ISSUE THREAD

**Issue by hectour3** [standardnotes/forum#2208]
**Describe the bug**
I wanted to try out the new interface a couple days ago, this went fine. However now that I want to switch back the app does not quit and the user interface stays the same. Reinstalling the app does not help either.

**To Reproduce**
Press "Switch"
App gives a white screen for a split second
The app appears as if you just opened it, but with the same interface

**Expected behavior**
Getting the old interface back.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini
 - OS: iOS 16.0.3

**Comment by effieeee** [comment]
Hi @thomasfchang, I'm afraid that switching to the old UI has really been disabled on v3.43.5, as we're also steadily implementing the new UI to replace the old one 🙏If you have any feedback on the new UI though, please feel free to open another issue here, or comment on any existing feedback that might be similar to yours!
