### ISSUE TITLE
No longer possible to swipe from left edge to return to main notes list

### ISSUE THREAD

**Issue by nevadaperry** [standardnotes/forum#2209]
**Describe the bug**
It is no longer possible to swipe from the left edge to go back to the main notes list, as of the Oct. 17, 2022 update to the iPhone app.

**To Reproduce**
1. Go to any note's text
2. Swipe from the left to go back to the main list
3. App no longer goes back

**Expected behavior**
The app used to go back. Now the user has to click the back button in the top left, which is inconvenient.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 15.6.1
 - Browser: Native app
 - Version: (can't check currently because this page is open in the in-app help&support modal). Likely the Oct. 17, 2022 major UI update.

**Additional context:**
This is frustrating because I switch between notes rapidly in my day-to-day routine and reaching up to hit a small button each time is inconvenient to do one-handed.

**Comment by effieeee** [comment]
Indeed the swipe gesture is no longer active on the latest version, though this would be one of the things we'll have to consider to make the new UI more mobile friendly. We've decided to track these points in this particular thread (swipe gestures are also mentioned here!) https://github.com/standardnotes/forum/issues/2203
