### ISSUE TITLE
New UI on Android Jumps in Initial Scrolling as Menu Disappears

### ISSUE THREAD

**Issue by jaredyates1** [standardnotes/forum#2214]
There have been some big changes to the app and it is much less good. I'm on version 3.43.5.

The worst new problem relates to scrolling down from the top of a note. While fully at the top, there is a menu available:
![Screenshot_20221019-081956](https://user-images.githubusercontent.com/116171956/196689085-9c0b45ce-7397-4732-b23c-a8fe32302ec4.png)
As I begin to scroll down, the menu disappears and then the note jumps down and skips the first several lines. 
![Screenshot_20221019-082007](https://user-images.githubusercontent.com/116171956/196689340-322854e2-3e21-4d7c-9cd2-93c66227d4d7.png)
If I scroll back up, the note jumps back down.
This makes it very difficult to interract with the top several lines of the note.
First choice to fix it: make there be no menu there. I don't use it anyway. An option in settings would be great.
Second choice: Once the menu disappears, keep the note where it was rather than having it jump up the height of the now-gone menu.

**Comment by catwithbanana** [comment]
I am experiencing the same issue.

**Comment by effieeee** [comment]
Can confirm this behavior on Android and iOS, we're keeping track of this along with other recently reported issues on v3.43.5 🙏

**Comment by effieeee** [comment]
Hi all, the menu on top of the note now persists on the latest update, so the note scroll position no longer jumps abruptly. The update is already out for Android, but still pending on the App Store for iOS 👍
