### ISSUE TITLE
[Help Wanted] How to share subscription with Private Username

### ISSUE THREAD

**Issue by jmason888** [standardnotes/forum#2219]
**Describe the issue**
I don't see a way to share my subscription with a private username

**To Reproduce**
1. Go to 'Account Settings'
2. Scroll to Subscription Sharing
3. Invite
4. System asks for "Invitee Email"
5. Private Usernames _don't have_ an email address

**Expected behavior**
1. Allow the user to enter a Private Username (or the related hash) in this box
2. Give the user the invite link *directly* rather than emailing it (since the invitee has no email address)

**Additional context**
If you can think of any other way to do subscription sharing between a regular account and a private username, that would work too.

**Comment by effieeee** [comment]
Indeed we still need to work on having subscription sharing work for private workspaces 😞We're keeping this in mind!

**Comment by pwseo** [comment]
@effieeee is this on your plans for the future? It is indeed a very useful feature, because one often uses private usernames as a way to divide notes into separate namespaces / workspaces.

**Comment by effieeee** [comment]
Hi @pwseo, while it's not on the current priorities yet, this is still in consideration, since the subscription sharing feature should also understandably be applicable for private workspaces too 👍
