### ISSUE TITLE
[Help Wanted] huge margins

### ISSUE THREAD

**Issue by Nho2000** [standardnotes/forum#2225]
IAll my notes have a huge margin that I cannot get rid of. Other accounts that I’ve tried do not have this issue.  I’ve resigning into my workspace and also reinstalling the app. 

![ADDE7E26-4613-4E5F-8F21-63F1243ECCD0](https://user-images.githubusercontent.com/116478784/197375854-5783468c-12c6-484b-8a08-154b02282dd3.png)

**Smartphone
 - Device: iPhone 13 Pro
 - OS: 16
 - Browser Firefox
 - Version 106

**Comment by effieeee** [comment]
Hi please see [this comment](https://github.com/standardnotes/forum/issues/2206#issuecomment-1281195202)! 🙏
