### ISSUE TITLE
Cannot access folder list on iPadOS 16.1 & 3.43.28

### ISSUE THREAD

**Issue by rouspreda** [standardnotes/forum#2231]
**Describe the bug**
I have a 6th gen iPad & just updated to iPadOS 16.1. Also updated the Standard Notes app to 3.43.28. In either portrait or landscape mode, there's no way to see my folder list. On my iPhone, there's a "burger" icon on the top-left of the app that I can access my folder list. There is no "burger" icon on the iPad version to tap. Already tried to sign out, un-install app, soft reset, re-install & sign back in, but the problem persists.

**Comment by myreli** [comment]
Hi @rouspreda. Are you still facing this issue? 

I'm sorry about the late reply. I'm currently triaging older issues.

**Comment by rouspreda** [comment]
Hello @myreli. No, the issue was fixed within a couple days of my post. Thank you for the follow-up.

Here's a SS from my iPad running iPadOS 16.3.1 & Standard Notes 3.149.4 while in Portrait Mode. 

The "burger" icon shows up properly in the top-left & allows me access to all my notes.

![IMG_0103](https://user-images.githubusercontent.com/115921344/221407035-72a867b5-0381-4b2a-8629-5a9db4f9aa86.jpg)

**Comment by myreli** [comment]
I'm glad to hear that @rouspreda. Thank you for letting me know. 🙂
