### ISSUE TITLE
Multitasking/Screenshot Privacy Protection does not work an Android

### ISSUE THREAD

**Issue by xthrk** [standardnotes/forum#2232]
**Describe the bug**
Even if the multitasking/screenshot privacy protection is enabled, screenshots can still be created on Android. If you deactivate the protection once and then activate it again, it works and no screenshots can be taken. However, after each app restart, this error occurs again.

**To Reproduce**
1. Open Standard Notes App on Android
2. Create Screenshot

**Expected behavior**
Multitasking/Screenshot Privacy prevents creating Screenhots

**Screenshots**
![grafik](https://user-images.githubusercontent.com/116081825/197978136-b1acc614-faf5-4185-bbba-6adf43e8a4e0.png)

**Smartphone (please complete the following information):**
 - OS: Android 11
 - Version: 3.44.3

**Comment by effieeee** [comment]
Can confirm this issue. Will report accordingly, thanks! 🙏

**Comment by effieeee** [comment]
This has been fixed so far on v3.45.4!
