### ISSUE TITLE
Is there a way to change editor fonts?

### ISSUE THREAD

**Issue by adlersantos** [standardnotes/forum#224]
Hi! I'd like to use preferred monospaced fonts for most of the editors (code, vim, and markdown). Is there a way to change editor fonts? Nonetheless, I hope this will be part of the roadmap. Thanks!

**Comment by mobitar** [comment]
Editors are independent extensions, and generally behave as they want, without influence from the containing app. So SN can control monospace for the plain editor, but not for the external editors. For this, themes can be used. None of our themes do this, but it might be possible for one to [make their own theme](https://docs.standardnotes.org/extensions/themes.html) to handle this.
