### ISSUE TITLE
Input field is not recognized as a text field on Android

### ISSUE THREAD

**Issue by m3thm4th** [standardnotes/forum#2240]
A few updates ago the input field stopped being recognized as a text field in the Android app, that means no more dictionary predictions or next word suggestion for example.

**Comment by effieeee** [comment]
Closing as this seems to be closely related to this issue: https://github.com/standardnotes/forum/issues/2217

**Comment by m3thm4th** [comment]
Fine if you want to close it, but I don't think it's the same because I don't have next word suggestions, it's as if it were considered some kind of password or username input, where you don't have suggestions. I also have an app for undoing text which doesnn't work anymore, it used to work until a few updates ago.
