### ISSUE TITLE
Note properties can't be unset on Android

### ISSUE THREAD

**Issue by m3thm4th** [standardnotes/forum#2241]
On Android it's impossible to unstar, unpin or unprotect a note

**Comment by effieeee** [comment]
Hi @m3thm4th, may I ask what version of the app you're experiencing this on? This sounds like an issue that was fixed from v3.43.28 onwards 😦

**Comment by m3thm4th** [comment]
Version 3.44.4, apparently it's working again now, don't know what changes but the bug certainly hapened after the version number you provided. I will update in case of any news.
