### ISSUE TITLE
iOS: Passcode input off centered with screen zoom enabled

### ISSUE THREAD

**Issue by Private-Fragrance** [standardnotes/forum#2242]
**Describe the bug**

**To Reproduce**
Settings > Display & Brightness > (Display Zoom) View > _Larger Text_ (vs Default) 

**Expected behavior**
The window should look the same regardless of zoom level

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.1 (also affected previous version(s))
 - Version 3.45.4 (also affected previous version(s))

**Additional context**
The core app is not adversely affected when screen Zoom is set to Larger Text. It's just the passcode screen. Furthermore, previous versions would fix themselves when rotating the device to landscape and then back to portrait. However it appears that rotation is no longer supported. 
![Zoomed](https://user-images.githubusercontent.com/115682189/198843433-5d0414f2-d6b0-45a4-9cb9-e62bef93a42a.jpeg)
![Default](https://user-images.githubusercontent.com/115682189/198843434-626c9bfd-86aa-43d5-84d5-cbec350bbeb7.jpeg)

**Comment by effieeee** [comment]
Hi @Private-Fragrance , I've also noted that this happened to some menus on Android with screen zoom initially, though we're doing our best to correct these as we continue working on the new UI! 🙏

**Comment by myreli** [comment]
Hi @Private-Fragrance! Several improvements were made to the new UI it looks like this is no longer an issue. Can you confirm? 

Tested on Android 12. 

![Screenshot_2023-02-25-17-40-45-450_com standardnotes](https://user-images.githubusercontent.com/17554234/221378843-7067d0e9-99d0-4216-a17a-f8155f58f91c.jpg)
