### ISSUE TITLE
Menus are messed up on desktop

### ISSUE THREAD

**Issue by julianfairfax** [standardnotes/forum#2243]
**Describe the bug**
For some reason all the menus are messed up. They have extra spacing on top.

**To Reproduce**
1. Open the app
2. Click the three dot menu on a note

**Expected behavior**
A menu without extra spacing on the top should show up

**Screenshots**

![image](https://user-images.githubusercontent.com/43753131/198850603-51defb52-6116-4074-87e5-5004b4e4e174.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 3.23.257

**Additional context**
I'm using the Flatpak, but I have confirmed this is also an issue with official packages.

**Comment by effieeee** [comment]
Hi @julianfairfax, took note of this issue on Windows as well, thank you for reporting! 🙏

**Comment by effieeee** [comment]
Hi @julianfairfax, this will be fixed in an upcoming update. You may reopen this issue if ever you find that the issue persists! 😊
