### ISSUE TITLE
Revert current behavior where folders collapse/open when clicked

### ISSUE THREAD

**Issue by solaraeon** [standardnotes/forum#2244]
So this happened on the 4th last update and I don't get why it's still here. Do others not use nested folders?

Why does selecting a folder now cause the tree to collapse/open? That is what the arrow on the side is for. I want certain trees I use often to be open and others closed. And I navigate between them for different notes. Now there is no way to do that without having to keep opening and closing different trees...?¿

**Comment by effieeee** [comment]
Hi @solaraeon, this behavior was an intended change, though we've received similar feedback that it doesn't feel very nice/intuitive. We'll try to consider reverting it in a future update!

**Comment by effieeee** [comment]
This behavior was reverted from [v3.23.273](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.23.273) onwards!
