### ISSUE TITLE
custom domain name

### ISSUE THREAD

**Issue by janvaniperen** [standardnotes/forum#225]
Any plans making custom domains like on [bitar.io](https://bitar.io) available to extended members?

I love the simplicity and it would be the perfect companion in order to have private and public notes.

**Comment by mobitar** [comment]
Definitely have plans for this :) Hopefully this year.

**Comment by janvaniperen** [comment]
[I am up for it](https://listed.standardnotes.org/@janvaniperen), put me on the short-list! (just signed up for the 5-years plan)

**Comment by mobitar** [comment]
Beautiful blog!

**Comment by mobitar** [comment]
Custom domains are now available :) Open your author settings to configure it.

**Comment by janvaniperen** [comment]
>Before submitting this form, please create an "A" record with your DNS provider with value .
It seems that the ip to point to is missing.

**Comment by mobitar** [comment]
Sorry, please refresh.

**Comment by janvaniperen** [comment]
🚀
