### ISSUE TITLE
[Help Wanted] "Attached Files vs File Safe"

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#2251]
I'm sorry if this is a very basic question, I'm just very confused - how is the "attached files" icon at the top of the editor related to, or distinct from, file safe?

Thank you!

**Comment by effieeee** [comment]
Hi @tiddesk, FileSafe was our previous means of attaching files to notes, though this was only usable with Alternative Rich Text notes, and its reliance on 3rd party cloud storage APIs made it difficult to maintain whenever there are changes to how tokens are stored or handled. We've now deprecated FileSafe in lieu of the new file attachment feature you see on the top of each note now :) The new file attachment interface can now be accessed from every note though we have yet to work on getting it to display images or other attachments inline on the note.

**Comment by tiddesk** [comment]
Thank you!

1) Adding inline display would be awesome with the new system
2) If the new system doesn't rely on 3rd party storage, where are our files and how to we manage our available storage space?
3) Do they remain encrypted in the same way?
4) How are attachments now handled by exports/backups?

Thanks again!

**Comment by effieeee** [comment]
The uploaded files also benefit from e2e encryption, and they're stored encrypted in our servers just like your notes :)
You can manage your uploaded files through the **Files** section on the navigation panel:

![image](https://user-images.githubusercontent.com/54989748/200338653-6c3c32a3-94c1-41ae-bb5e-869479e01d0c.png)

Files are handled separately from notes in terms of export/backups. Currently, only the desktop app is able to manually backup and restore individual files, but we hope to improve on this in future versions as well

**Comment by tiddesk** [comment]
Thank you!
