### ISSUE TITLE
Crash while trying to 'Upload and Link' and choosing the Camera

### ISSUE THREAD

**Issue by IgiMar** [standardnotes/forum#2254]
The crash happens after having shot a photo and accepted the result. The crash shows as the screen becoming indefinitely white. The Standard Notes apps has to be closed and reopened to keep on working. No upload happened after the crash.
Selecting an already existing picture instead of opening the Camera works fine, instead.
So the issue is just the interaction with the Camera, I presume. 
It happens on Android (Samsung S21 phone).

The same feature works well on iOS (iPad).

**Comment by effieeee** [comment]
Hi @IgiMar, I'm afraid I couldn't reproduce this so far on an Android 12 device :( Is this happening on the latest version of the app (v3.45.4), and have you also tried [clearing the app data](https://docs.standardnotes.com/troubleshooting/reset-apps/#android) and signing back in to test the feature again?

**Comment by IgiMar** [comment]
Hello, it worked. After your procedure AND after a re-start. Thank you.
