### ISSUE TITLE
search within standard notes and see results highlighted

### ISSUE THREAD

**Issue by anarchator** [standardnotes/forum#2256]
hi there,
i am using the windows app and also https://app.standardnotes.com/
When using the windows app and searching my notes, it highlightes the found results (which is great).
But when i am using web app (https://app.standardnotes.com/) then the found results won't hightlighed, which makes it really hard to find the phrase when it's withing a very big note. Is there a way to also see the results highlighted when using the web app?

**Comment by effieeee** [comment]
Hi @anarchator, we're sorry that the highlight feature doesn't trigger on the web app as well, though as a workaround in the meantime, you may use the **Ctrl+F** function on your browser and type in the same search term. This should highlight all results in the same way as the desktop app! 🙏
