### ISSUE TITLE
Drag-and-drop notes to folders to assign tag

### ISSUE THREAD

**Issue by jdefleur** [standardnotes/forum#2257]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

Yes

**Is your feature request related to a problem? Please describe.**

My workflow involves frequently moving notes between folders. Currently I need to open the note, click and delete the existing tags at the top, and then click and type in the tag of the folder I'd like to move it to (MacOS client).

This is a lot of clicks and keystrokes just to move a single note from one folder to another.

**Describe the solution you'd like**

I would like to be able to click and drag a note to another folder's name on the list in the left panel, and upon dropping it have the note automatically removed from the existing folder and added to the folder I dragged it to.

This is standard functionality with other note apps that have a folder structure (Evernote, Joplin, etc.)

It would also be nice to be able to select multiple notes and drag them all to the same folder simultaneously.

**Describe alternatives you've considered**

The alternative is to continue doing things in the cumbersome way I described and deal with a lot of friction in my daily workflow, or to use a different notes app.

I like the mission behind Standard Notes, so am trying to make it work as my primary notes app. The lack of this feature is the primary thing that's making that difficult for me right now.

**Comment by effieeee** [comment]
I'll incorporate this into https://github.com/standardnotes/forum/issues/2258 since they're two related suggestions 😊
