### ISSUE TITLE
Error syncing (changes saved offline)

### ISSUE THREAD

**Issue by thebrowser** [standardnotes/forum#226]
Hello Team,

A few days ago I edited one of my notes using the web app, and saved the changes. These still appear today without a problem even after clearing cookies, cache, temp files, etc in my browser and PC. The problem is the changes do not reflect in the Android app, and when I open the note there is this message: "Error syncing (changes saved offline)". I waited for a few days, restarted phone, tried to refresh within the app but it doesn't work. I haven't tried to log out and back in yet as I wanted to ask here first (it would be really inconvenient to keep logging out/in all the time for syncing).

Thank you, cheers.

**Comment by mobitar** [comment]
Hey @thebrowser, is it possible you changed your password but forgot to sign out and back in on Android?

**Comment by thebrowser** [comment]
Hi @mobitar, I'm afraid that's not the case. I'm using a password manager and I can see the last update on my password was 2 days before this issue, and it was working well so far with other notes. I just went ahead and made some more changes to the note to test and noticed the option "Resync All Items". I did use this back a few days and again just now, in case if it has something to do with it. 

Again, I suppose it's a lot easier to simply log out and back in and not waste too much time with this but maybe this was a known issue. Please let me know if I can try something else, otherwise I'll just report back if it happens again.

**Comment by mobitar** [comment]
So on Android, does it say Error syncing for absolutely any edit you try to make, on any note, new or existing? And does it pull in any changes that you make on the web?

If it's not pulling in changes you're making elsewhere, then it's something with your credentials not being valid for some reason. Without more clues/reports from other people, I won't have enough to perform a thorough investigation. So your best bet is logging out and back in.

If however new changes are being pulled, but changes you make in Android are not being pushed, then that would be interesting. Let me know if that's the case.

**Comment by thebrowser** [comment]
It seems it was an issue with the credentials then as no changes sync at all in either device. So I've just log out and back in, and it all works normally again.

Thanks again for the quick help!

**Comment by mobitar** [comment]
Ok great! If this happens again for whatever reason, please let me know.
