### ISSUE TITLE
The number of notes in the Navigation Panel (Counting) is incorrect

### ISSUE THREAD

**Issue by xthrk** [standardnotes/forum#2261]
The number of notes in the Navigation Panel (Counting) is incorrect. I don't know since when this has been the case, but I noticed it when I saw a different number in the Encryption section of the Security menu in Settings. I then counted the notes and indeed the number seen in the Settings in the Security menu is correct, the number shown in the Navigation Panel to the right of Notes is not correct.

**Comment by xthrk** [comment]
I just uploaded a new file to an existing note and saw that subsequently the counting of Notes in the Navigation Panel increased by 1.

**Comment by effieeee** [comment]
It looks like the current counter on the navigation panel includes uploaded files as well. I've raised this matter with the team!

**Comment by myreli** [comment]
Looks like this has been fixed now. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
