### ISSUE TITLE
Open Note in a New Tab/Window Multi Note editing

### ISSUE THREAD

**Issue by aryanrajseo** [standardnotes/forum#2262]
Hi, is it possible to offer the feature to open a note in new tab window to allow editing multiple notes at the same time? I takes multiple notes and then need to categorized but i have to copy and then go back to the different note to copy/paste.

Or maybe a double click on a note open as a .txt note or something like that if the current default note editing window is not supported.

Thanks.

**Comment by effieeee** [comment]
Hi @aryanrajcom, this is something that we had planned in the future versions of the app, though it isn't yet part of our immediate roadmap. It's currently being tracked as a feature request here: https://github.com/standardnotes/forum/issues/958
