### ISSUE TITLE
Option not to have themes synced across platforms

### ISSUE THREAD

**Issue by mcinel** [standardnotes/forum#2264]
When you choose a theme on any given platform (desktop or mobile) that specific theme is synced across respective platforms automatically. But an option to be able to have different themes for different platforms would be very useful.

**Comment by myreli** [comment]
Duplicates https://github.com/standardnotes/forum/discussions/2630

**Comment by dramaticviewfinder** [comment]
This has been marked as completed but there is still no option to keep separate themes on different platforms
