### ISSUE TITLE
Listed ghost posts

### ISSUE THREAD

**Issue by JeremyJaydan** [standardnotes/forum#227]
Hey so I seem to have broken my page on Listed.

Two of my posts duplicated (init, style.css), then I deleted the posts, however the "ghost" duplicated posts stayed. 

I assume it's because I deleted instead of clicking the Unpublish button. 😬 

https://listed.to/@JeremyJaydan

**Comment by mobitar** [comment]
Should be good now. Yup, don't forget to unpublish before you delete :)

**Comment by mobitar** [comment]
Also, you should republish your theme after the reset.

**Comment by JeremyJaydan** [comment]
Awesome, thanks!
