### ISSUE TITLE
Bug: macOS Download Links Broken

### ISSUE THREAD

**Issue by anonmouse1** [standardnotes/forum#2270]
**Describe the bug**
When trying to download the .dmg file for macOS (problem exists for both the arm and intel download links), the webpage returns a 404 error and the .dmg is not downloaded. As a result, cannot install standard notes on macOS currently. Windows and Linux downloads working correctly.

**To Reproduce**
1. Go to https://standardnotes.com/download
2. Click on either the intel or apple silicon download links
https://github.com/standardnotes/app/releases/download/%40standardnotes/desktop%403.23.282/standard-notes-3.23.282-mac-x64.dmg
https://github.com/standardnotes/app/releases/download/%40standardnotes/desktop%403.23.282/standard-notes-3.23.282-mac-arm64.dmg

5. See 404  error

**Expected behavior**
.dmg file should download

 - OS: [e.g.macOS]
 - Browser [firefox ]
 - Version [105.0.3]

**Comment by anonmouse1** [comment]
Issue seems to have been resolved on Wednesday 9 November and download links are working again

**Comment by danilichti** [comment]
Download links are dead again. Both links don't work!

**Comment by effieeee** [comment]
Upon checking now, this has been fixed for both Intel and M1 versions of
the installer 👍
