### ISSUE TITLE
[Help Wanted] Import of backup file results in many "Conflicted Copy" errors

### ISSUE THREAD

**Issue by velardevines** [standardnotes/forum#2271]
**Describe the issue**
Import of backup file results in many "Conflicted Copy" errors/messages. 

**To Reproduce**
1. Open Preferences in lower left corner
2. Click Backups from menu on left side of screen
3. Click Import Back'
4. Select the backup file from yesterday

**Expected behavior**
A copy of the data as represented in the backup file. 

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser: Brave
 - Version [Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)](https://brave.com/latest/)

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android latest (don't have phone with me) 
 - Browser Brave, Firefox
 - Version Latest versions

**Comment by effieeee** [comment]
Hi @velardevines, I see, though for context, I wanted to ask why you needed to import a backup file from the previous day?

Also were you able to take note of how many conflicting copies were produced, and if there's any pattern to which notes generated conflicting copies?

**Comment by velardevines** [comment]
Hello @effieeee, 

Thanks for responding. 

A bit more context. I use Standard Notes on Windows laptop, ubuntu laptop, Android phone. On both laptops, I use the Desktop app and the web app (Brave, Firefox, Chromium browsers). However, only one instance of Standard Notes is open at a time. I do not open concurrent instances of Standard Notes; the exception might be if Standard Notes is open on the phone and a laptop. 

I imported a backup because there were so many Conflicted Copies of notes that I thought it simpler to start fresh with a backup even though a few notes would be missing. Clearly that was not the best decision I might have made :-)  

I could not identify any pattern in the conflicted notes. Both note content and note tags were different for conflicted notes. 

Over the past few days I have resolved most of the conflicted copy issues with the backup copy I loaded. It's strange to me that a 'clean backup' would again result in conflicted copies of note. But clearly there is a lot I don't understand about how sync works or about how to refresh from a backup copy.  

At this point I am using Standard Notes on phone, Windows laptop Desktop app and ubuntu laptop Desktop app. I am not using the web app due to an account issue explained in the next paragraph...

At some point during the past few days, the web app started telling me I did not have a Pro account. So, I decided to stop using the web app until I was able to resolve the conflicting notes problems. Now, I would like some help to resolve this account problem with the web app without creating further problems with conflicting notes or other note sync issues. 

Thank you again. Let me know what other information you may need.

**Comment by effieeee** [comment]
I see, I'm sorry to hear that you thought to import a backup because of conflicted copies in the first place :( I actually consulted on a similar case with the team, though I'm afraid it looks like this may have been caused by some server performance issues that were noticed this week 😞You may have imported your backup file during the peak of the server issue, resulting in the many conflicted copies you had to manage. The team is doing its best to fully resolve the issue, and we'll do our best to provide an update here once we've confirmed that all is well again, though  so we're very sorry for the trouble so far 🙏

**Comment by velardevines** [comment]
Thanks for explaining. Good to know the cause of the problem is understand.

**Comment by effieeee** [comment]
Hi @velardevines, the situation with the server was remedied just recently, so just let me know if there's anything else I can help you with here! 🙏

**Comment by velardevines** [comment]
No further help is needed. Thank you @effieeee 

The web app account identification problem seems to be resolved. also
