### ISSUE TITLE
Android app no longer working

### ISSUE THREAD

**Issue by meghprkh** [standardnotes/forum#2275]
**Describe the bug**
The Android app has recently stopped working. I tried deleting storage, installing all versions on fdroid and play store. This might have to do with 2FA being enabled and certain self-hosted plugins.

It gets stuck on generating keys or a whitescreen after launch or keychain corrupt message

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot_20221109-194126](https://user-images.githubusercontent.com/5979605/200972417-7831095d-23ba-47bb-a961-3aeba266f968.png)

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 13
 - Browser stock
 - Version 3.45.23

**Additional context**

**Comment by effieeee** [comment]
Hi @meghprkh, I wanted to ask if you encounter the same issue while trying to access your account on the desktop app or [web app](https://app.standardnotes.com/)? Also, does this still occur on v3.45.4 of the Android app?

**Comment by meghprkh** [comment]
Yes I tried that version from play store too. I can access my notes on the web site

**Comment by meghprkh** [comment]
Version 3.46.22 works. Thanks! :)
