### ISSUE TITLE
RE: Is this package available on debian/devaun Linux

### ISSUE THREAD

**Issue by Raj2032** [standardnotes/forum#2279]
Hi I am using a Devaun based distro (which is based on Debian) and I was wondering if there was any repo available for devaun/debian based distro without snap or appimage etc?

**Comment by effieeee** [comment]
Hi @Raj2032, not sure if this is exactly what you're looking for, but each release has a .deb file on the repo as well. See the assets under the [latest release](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.23.273) for example!

**Comment by Raj2032** [comment]
@effieeee Hi, I was looking for a specific deb package couldn't find it. But yeah thanks man.
