### ISSUE TITLE
Layout broken on app.standardnotes.org

### ISSUE THREAD

**Issue by B9x3n** [standardnotes/forum#2285]
I tested with both Brave and Firefox and the layout is not quite right, it's hard to explain, here's a screenshot:

![standardnotes](https://user-images.githubusercontent.com/100185928/201982744-f1ba6adf-2fa3-480a-97c6-84669d43c8b8.png)

The notes section is very small, and there is a lot of white space below the footer (that has the SIGN UP TO SYNC button). 

Brave
```
[Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (64-bit)](https://brave.com/latest/)
```
Firefox
```
102.4.0esr (64-bit)
```

**Comment by meixger** [comment]
@B9x3n I have the same error on https://app.standardnotes.org
It works for me on https://app.standardnotes.com

**Comment by effieeee** [comment]
Yup, I noticed this on the .org domain as well, though we do encourage users to sign into the .com domain moving forward, as this is the current domain to which we push the latest updates 🙏

**Comment by B9x3n** [comment]
Thanks @meixger and @effieeee! :smile: I wasn't aware of the .com site! :blush: :facepalm: :joy: Good to know, thank you!
