### ISSUE TITLE
Web app doesn't enable scrolling down to see all notes

### ISSUE THREAD

**Issue by r-i-v-a** [standardnotes/forum#2287]
**Describe the bug**
Web app doesn't enable scrolling down to see all notes. Scrolling stops after about a page and a half of notes, though I have more notes that can be accessed via the native and mobile apps.

**To Reproduce**
- Have a collection in the low hundreds of notes
- Login to the web app, using Chrome
- Try to scroll down the page

**Expected behavior**
I can keep scrolling down and view all my notes in the web app.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Version 107.0.5304.110 (Official Build) (x86_64)

**Comment by effieeee** [comment]
Hi @r-i-v-a, just wanted to ask if you might have been using the .org domain for the web app instead of the .com domain? Please see this comment as well!
https://github.com/standardnotes/forum/issues/2285#issuecomment-1316599041

**Comment by r-i-v-a** [comment]
Yes, it's working fine on the `.com` domain. Closing issue.
