### ISSUE TITLE
Note previews don't render HTML (Plus Editor)

### ISSUE THREAD

**Issue by skrizzles** [standardnotes/forum#229]
The screenshot says it all: 
![image](https://user-images.githubusercontent.com/22671272/41128555-31468ad0-6a74-11e8-9da9-571fa47b8f9c.png)

I should note that I'm using the Dynamic theme in the web app version (Chrome on Windows 10)... So maybe the screenshot doesn't say it all.

**Comment by odyon01** [comment]
Hi Skrizzles, there's already an issue raised about this point: https://github.com/standardnotes/forum/issues/158. But I agree, I also would like to see this happening.

**Comment by mobitar** [comment]
This should now be fixed. (Update your app and extensions and edit the note at least once).
