### ISSUE TITLE
App never seems to update itself

### ISSUE THREAD

**Issue by mattieb** [standardnotes/forum#2291]
**Describe the bug**
On my Mac running Ventura (but also on past macOS versions), Standard Notes often says "(1) Update Available" in the menu bar, but I don't remember the last time it has successfully updated itself.

After a week or so of this I usually end up manually updating by downloading a new release.

**To Reproduce**
1. Wait for a new desktop app version to be released
2. Observe the menu bar indicating "(1) Update Available"
3. Leave Standard Notes open for awhile, close it and reopen it later, nothing seems to clear this status
4. Try "Check for update" menu option; but the dialog only says "A new update is available (version 3.xx.xxx). You can wait for the app to update itself, or manually download and install this update."

**Expected behavior**
It's clear the app is updating itself at some point, or it says why it isn't updating itself.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 3.23.279 and many past versions

**Comment by effieeee** [comment]
Apologies, we're keeping track of reports of the issue, though we'll be keeping just this [one thread](https://github.com/standardnotes/forum/issues/1714) open to track them all as we look into it🙏

**Comment by mattieb** [comment]
> Apologies, we're keeping track of reports of the issue, though we'll be keeping just this [one thread](https://github.com/standardnotes/forum/issues/1714) open to track them all as we look into it🙏

No, _my_ apologies! I didn't find that. Thanks 😊
