### ISSUE TITLE
Unable to upgrade to paid plan.

### ISSUE THREAD

**Issue by AthenaDelta** [standardnotes/forum#2296]
I had an annual subscription that recently lapsed. I went to renew and it gave me error code “Your purchase was canceled or failed. Please try again.” 

I have now started two more accounts and tried to subscribe and the same thing happens every time. 

I have tried on the new iPad Pro and iPhone XS both operating current iOS.

Any help much appreciated as I am currently locked out of all my notes…

**Comment by effieeee** [comment]
Currently assisting over email!
