### ISSUE TITLE
No more daily or weekly backups to Email

### ISSUE THREAD

**Issue by SpaceRaccoonFluff** [standardnotes/forum#2298]
**Describe the bug**
One day a couple weeks ago out of the blue, daily email backups stopped coming in. I have checked my spam settings, enabled and disabled it, and even switched it over to a new email address. Nothing has worked. I use Protonmail btw. 

**To Reproduce**
Enable daily or weekly email backups.

**Expected behavior**
Send daily backup as email.

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 16.0.3

**Comment by effieeee** [comment]
Hi @SpaceRaccoonFluff, can you send me an email at help@standardnotes.com and let me know your account email? I'll continue assisting you with this from there 🙏
