### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by gharley-vertex** [standardnotes/forum#2300]
Says an existing request is already in progress. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by effieeee** [comment]
Hi @gharley-vertex, please send us an email at help@standardnotes.com, and indicate the email address you were trying to use for the account! I can help you look into this from there 🙏
