### ISSUE TITLE
Implement navigation between matching keywords in the search results

### ISSUE THREAD

**Issue by X1SDNA** [standardnotes/forum#2301]
I have been a Standard Notes pro user for a few years (2 or 3 I believe).

I love it, and can't live without it. I recommend it to everyone. But there's an issue that I'd really appreciate a fix for ASAP.

I'm sure this has been brought up before, but it is a real problem that I deal with every day, to the point where unfortunately it pretty much defeats the purpose of having my notes encrypted.

I have many notes, some are long with lots of information. When I search for a term I need to find, SN will show me a list of notes in which that term exists. But that is where the search ends. I am not taken to the search terms in the notes. I need to manually scroll through all the information in the notes, and be on vigilant lookout for the yellow highlighted term. Because this is not realistically possible unless I'm sure what I'm looking for is at the very beginning of a note, I must select all, copy, open a text document in whatever desktop OS I am in, paste in in, run the search, be taken to the search term, and view/copy my information from that. Of course, I don't do this on the Android app, so I know I can't use the Android app if I need to search for something.

The obvious problem is that I am copying often sensitive information to the clipboard of my operating system all the time, which is why I mentioned that this largely defeats the purpose of having notes inaccessible to the OS.

Is there a better search function planned, one with which I can navigate to the location of each instance of the search terms found? And just in case some people are thinking it: Please don't tell me to make all my notes short, or other such workarounds.  I'd just really appreciate knowing why this doesn't work at all, or inconsistently (yes, I think remember an occasion or two where I have been taken to a search result in a note, but the last occurrence of that is not even in my memory, so maybe I simply can't recall.  I use SN on Linux, W10 and Android, so have been observing this for years now.

If searching can work like it does in Notepad, the Standard Notes will be pretty much perfect.

**Comment by effieeee** [comment]
Improvements to the search functionality have been surprisingly difficult to implement over the years, especially in light of the variety of note editors that can be loaded onto your notes 😞 We're keeping track of these requests on the forum though 🙏

**Comment by X1SDNA** [comment]
Hi - thanks for your reply. Can you implement it for one good markdown editor? I use Markdown Pro for everything, as it seems best suited to the type of note program that Standard Notes is.

It sounds like this situation is not likely to change anytime in the known future, and TBH that worries me. Needless to say, a good search function is fundamental to all data management and should be an absolute priority IMHO..
