### ISSUE TITLE
On super notes, adding an inline image prevents collapsible from open/close

### ISSUE THREAD

**Issue by jrcacd** [standardnotes/forum#2302]

**Comment by myreli** [comment]
Hi @jrcacd! I'm afraid I can't reproduce this. Are you still having this issue? 

 

https://user-images.githubusercontent.com/17554234/221390158-88219aa2-db26-4673-ab9d-672e4f7ed0ef.mov

**Comment by jrcacd** [comment]
You're right. It became fixed a few weeks ago.
