### ISSUE TITLE
Super Notes feature requests

### ISSUE THREAD

**Issue by jrcacd** [standardnotes/forum#2303]
- [ ] Add option to highlight text (yellow color)
- [ ] Ability to resize images

**Comment by effieeee** [comment]
@chloeso (https://github.com/standardnotes/forum/issues/2306)
- [ ] LaTeX math equations

**Comment by ashutoshsaboo** [comment]
Big +1 for LaTeX math equations. Greatly missing those from the milkdown editor. From Lexical's playground (https://playground.lexical.dev/), Looks like lexical has already built out of the box support as well for LaTeX - both by the menu popup (like tables) as well as by entering equations within `$` placeholders for a more faster experience - exactly similar how Milkdown also supports it already. If both can be enabled for SN super notes, that'd be really _super_ awesome! :) @effieeee

**Comment by shompoe** [comment]
Ability to convert supernotes back to markdown or html without having to export to an external text file.

**Comment by shompoe** [comment]
Horizontally scrolling tables which auto-size to content rather than screen size.

**Comment by viharsheth** [comment]
Listed doesn't show an image if a Super Note is published to the blog. Would love for Super Notes to show up as written on Listed.

**Comment by shompoe** [comment]
"Show Markdown" option does not convert tables.

**Comment by cuathro** [comment]
- [ ] Search (with highlighting) within the note

**Comment by PovilasID** [comment]
OICD or LDAP auth for selfhosted option

**Comment by effieeee** [comment]
[Supernotes: Change the "add link" button's behavior](https://github.com/standardnotes/forum/issues/2372)

**Comment by WearyHead** [comment]
- [ ] The ability to record and and easily replay voice messages
- [ ] Make it easier to permanently delete an image from within the editor (without having to go the 'linked items panel' or the 'files tab'). This prevents cluttering up your storage when uploading/editing a batch of photo's.
- [ ] Automatically make all the uploaded files in a note private when the note itself is made private.

**Comment by THEOCKID** [comment]
Android Widgets.  Kind of deal breaker, sorry

**Comment by danielcolquitt** [comment]
Word count, reading time, and other stats for Super Notes.

**Comment by erlandh** [comment]
- [ ] Add or remove rows or columns in a table
- [ ] Resize columns in tables

**Comment by yolier** [comment]
Embedding images via URL
comparable to Markdowns: `![alt](https://host.org/my-image.png)`

(Or am I just to stupid to do it? It seems so basic)

**Comment by jomra** [comment]
This isn't available in any of the alternatives I've tried, but in-note links, such as to a reference in a citations section, would be super useful for decluttering notes. Otherwise, you have to either link inline (which is an issue because of link rot), manually add numbered footnotes, or clutter up the note with inline references.

Edit - When I say references, I don't necessarily mean a formal academic citation. Just something with more info than a bare URL.

**Comment by shompoe** [comment]
Ability to adjust paragraph spacing so as to eliminate the need for extra line breaks.

Presently the spacing between list items is defined by the line spacing setting in preferences, this should also be defined by a separate setting for paragraph spacing.
