### ISSUE TITLE
Desktop app cannot toggle 'Views'

### ISSUE THREAD

**Issue by cviorel** [standardnotes/forum#2314]
**Describe the bug**
In the desktop app the 'Views' is collapsed (from the web app) and it cannot be restored.
I need to go to the web app to be able to restore the Views, and then the desktop app shows it, as well.

**To Reproduce**
1. Go to web app
2. Drag/resize/toggle the Views until it's not visible anymore
3. Go to desktop app
4. Cannot restore the Views

**Expected behavior**
We shoul be able to restore/resize the Views.

**Screenshots**
![image](https://user-images.githubusercontent.com/125662/204364589-caad0f65-6358-478a-b118-a1597116f7a0.png)
In the web app, the Views can be toggled/resized correctly

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [3.100.17]

**Comment by effieeee** [comment]
Hi @cviorel, if the Views/Tags panel becomes hidden that way, you can also restore it by clicking on the **Quick Settings** icon on the bottom left, then clicking on the toggle for **Show Tags Panel**. You may also use the shortcut indicated next to this option!

![image](https://user-images.githubusercontent.com/54989748/204834054-5f77ce5d-fe24-49a9-82ad-a65d27574ae8.png)
