### ISSUE TITLE
After selecting Super Note, the note type list still shows the last editor used as the selected note type

### ISSUE THREAD

**Issue by BobWs** [standardnotes/forum#2317]
When I select Super Note than the Markdown Alternative shows as selected, but the super note is active! See screenshot.

![Screen_Shot 1](https://user-images.githubusercontent.com/5485820/204815642-7a7d9a54-3553-426d-809a-b57758adbd70.png)

**Comment by effieeee** [comment]
It seems to select the **last editor** that was set on the note in particular. Will update the issue title accordingly!

**Comment by viharsheth** [comment]
Any update on this? Still having the same problem. The only way I can get a Super Note to self identify 😁 is to have it be the default note type on mobile (Android) and create a new note. I can not change a note type to Super but all the other types work.

**Comment by myreli** [comment]
Hi @viharsheth, are you still experiencing this issue? 

It looks like it has been solved in one of the latest updates.

**Comment by viharsheth** [comment]
I think it's okay. The icon doesn't match exactly, as the colors are
inverted, but the switching occurs as predicted.
