### ISSUE TITLE
[Help Wanted] How to delete entry in task list

### ISSUE THREAD

**Issue by abelliae** [standardnotes/forum#2322]
**Describe the issue**
In the 3.116.0 Linux App, I don't seem to be able to find a way to delete task notes entries.

**To Reproduce**
1. Go to a task note
2. Add a new entry
3. Delete the text of the entry entirely
4. Click backspace one more
5. Nothing happens

**Expected behavior**
Pressing backspace or delete on an empty task entry would delete the entry.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional context**

**Comment by effieeee** [comment]
Hi @abelliae, hitting **Enter/Return** after deleting the text contents will delete the open task, though we'll try to keep this in mind as feedback on making the task editor actions more intuitive 🙏

**Comment by abelliae** [comment]
> Hi @abelliae, hitting **Enter/Return** after deleting the text contents will delete the open task, though we'll try to keep this in mind as feedback on making the task editor actions more intuitive pray

Understood, thank you!
