### ISSUE TITLE
v3.110.1 - UI broken on Firefox

### ISSUE THREAD

**Issue by dennisstewart** [standardnotes/forum#2326]
**Describe the issue**
A change has broken Standard Notes webapp UI on Firefox. UI works as expected (how it has previously) in a Chrome Incognito window (107.0.5304.122). Firefox Screenshots below:

**Screenshots**
![image](https://user-images.githubusercontent.com/7216549/205515315-957bf2a0-6f97-4f41-89e5-1e64fe7aa87d.png)
Hovering over the sidebar so it expands, and selecting Notes, I do not see the list of notes.

![image](https://user-images.githubusercontent.com/7216549/205515569-0b61fa93-39b7-4e58-96b7-0297a513a226.png)
Selecting a tag/folder, I can see the list of notes under that, but don't have a way to go back (other than refreshing the page). Rather than the expected note/editor being opened in the right panel, it's opened below. I cannot resize it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 107.0.1
 - Standard Notes Version: 3.110.1

**Comment by dennisstewart** [comment]
I did not notice this issue until today; I was able to use Standard Notes earlier this week without issue.
I have also tried deleting local storage, cookies, etc. and this issue persists.

**Comment by effieeee** [comment]
Hi @dennisstewart, I noticed your web app version looks rather outdated compared to the current web app version, so I just wanted to verify if you're visiting the web app through the old ".org" domain, rather than the newer ".com" domain? (https://app.standardnotes.com/)

**Comment by dennisstewart** [comment]
Yeah, that fixed it. https://app.standardnotes.com gives me 3.119.1. Sorry I didn't know about that!

**Comment by jpgill86** [comment]
> Hi @dennisstewart, I noticed your web app version looks rather outdated compared to the current web app version, so I just wanted to verify if you're visiting the web app through the old ".org" domain, rather than the newer ".com" domain? (https://app.standardnotes.com/)

Huh. I was just about to post about this issue, and then I saw @effieeee's post about the .com change. That fixed it for me too. I wonder if it would have also fixed #2294 for me had I known about it two weeks ago. Why, oh why, doesn't the .org site redirect to the .com site? Where was the memo about this change? I completely missed it.

EDIT: I opened an issue suggesting an automatic redirect. #2329
