### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by algatern** [standardnotes/forum#2327]
**Describe the issue**
Standard Notes on Android does not auto-correct spelling mistakes. There are no next word suggestions on the keyboard. As such, the app is almost unusable. Note entries become illegible from so many typos and is extremely frustrating to use. This issue is not present on any other apps on my phone.

**To Reproduce**
Type a note.

**Expected behavior**
The keyboard should have next-word suggestions, and typos should autocorrect themselves as I type.

**Smartphone:**
 - Device: Pixel 5
 - OS: Android 13
 - Version 3.45.42

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/2217
