### ISSUE TITLE
Should app.standardnotes.org redirect to app.standardnotes.com?

### ISSUE THREAD

**Issue by jpgill86** [standardnotes/forum#2329]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes! 💖

**Is your feature request related to a problem? Please describe.**
[I gather](https://github.com/standardnotes/forum/issues/2326#issuecomment-1338227223) that the web app URL https://app.standardnotes.com is now favored over https://app.standardnotes.org. When I first subscribed to Standard Notes in August 2021, I only ever saw the .org link, and I have been using it ever since. I never caught wind of this URL change, despite trying to pay attention to newsletters. I have been so puzzled by the recent Super Note announcements, since that note type doesn't even exist on the .org site! Is the .org site deprecated? It has become buggy recently (#2326, and possibly #2294). Why not redirect users from the .org site to the .com site automatically?

**Describe the solution you'd like**
Redirect users from the .org site to the newer .com URL automatically. This would help users like me who had missed the news that they should switch.

**Comment by atmoio** [comment]
Yes .org is deprecated. We can't do a redirect because app storage is bound to the domain (.org) and will be lost if redirected to .com. What we're going to do soon is present a full screen banner on .org instructing not to use the site anymore in favor of .com.

**Comment by jpgill86** [comment]
Thank you for the explanation, @moughxyz! The banner sounds like a great idea. Since you already had plans for this, I will close this issue.
