### ISSUE TITLE
[Feature Request] Disable auto-opening of Extension Editors on mobile

### ISSUE THREAD

**Issue by toddfraser** [standardnotes/forum#233]
In the product's current state, if I have a note that was edited with Advanced Markdown Editor on Desktop, and then open that same note on my mobile device, I am first shown the unformatted version and then a modal appears with the editor.

If this were a preference, I could turn this off so I could prioritize quick views rather than immediately heading into "Edit Mode" (which could be a call-out a the bottom, indicating which editor was used and a button to open it).

Small thing but it does affect a workflow that I'm currently used to (aka. 1 person's anecdotal evidence).

**Comment by toddfraser** [comment]
You are right that it mostly only makes sense with Markdown. The option would just work in my particular use case (mobile is for read/recovery whereas desktop is for write/input).

Since most folks prefer the current system, this probably doesn't need to be high priority on your backlog!

**Comment by mobitar** [comment]
Got it thanks! Will keep this in mind.

**Comment by Dutch-in-Seattle** [comment]
I actually agree completely with toddfraser. I would also prefer notes in the mobile apps to be opened in view mode, or at least be given that option. When I open a note in my mobile app, it automatically opens in the editor, with all associated HTML code, whereas I mostly just want to see the content of the note. It has really prevented me from using anything the but text-only editor for my notes.
Like toddfraser, I also use the mobile app mostly for viewing notes, and I add/edit notes on my laptop.
It would be great if we could be given the option of defaulting to either viewing or editing notes in the mobile apps.
Thanks for considering!

--Ron

**Comment by mobitar** [comment]
@Dutch-in-Seattle but if you're using the Plus Editor, without the editor on mobile, you'll only see raw HTML, which you won't be able to either read or edit naturally in plain text mode. Or are you using a different editor?

**Comment by effieeee** [comment]
On the new UI, notes load notably faster and without having to show the unformatted version first!
