### ISSUE TITLE
Has anyone been able to activate Supernotes or anything in Labs [Help Wanted]

### ISSUE THREAD

**Issue by pouchofsilver** [standardnotes/forum#2330]
The blog mentioned Supernotes in early December. I found the word "Labs" in Preferences/General, but there's nothing there. Wrote to customer service and got a tip to download the latest version, which I did. Still nothing in Labs, though.
Side note: the "latest" version was 3.120, which is curious, because the version I had installed was 3.23.209. 

Could this be because I'm on an old desktop? (~2014 year Mac mini running High Sierra)

**Comment by viharsheth** [comment]
I have. I believe there was an option in the Labs section. It's active now and there are no options to do anything in Labs now, including uninstalling Super Notes. The editor has bugs but it's nice, especially for handling images.

**Comment by effieeee** [comment]
Hi, sorry for the confusion! As of v3.120, Super Notes is now permanently on the list of note types, so you needn't go into the Labs section to see it 🙏

![image](https://user-images.githubusercontent.com/54989748/206227560-2ec5d046-5c69-42b7-abbf-4ead80308076.png)
