### ISSUE TITLE
Linux snap app can't be moved on the screen, or re-sized

### ISSUE THREAD

**Issue by apmcgregor** [standardnotes/forum#2334]
The snap app delivered through the Ubuntu software store is unable to be moved on the screen or to be able to be re-sized using the edges of the window on Ubuntu 20.04.
The Ubuntu software store is currently delivering version 3.122.0
If I downloadand run the AppImage from the standard notes website, version 3.101.2, this issue isn't there.

**Comment by effieeee** [comment]
Hi @apmcgregor, is this still the case even with v3.125.0 of the Snap? If it persists, have you also tried to clear the site data for the app as instructed [here](https://docs.standardnotes.com/troubleshooting/reset-apps/#desktop)?

**Comment by apmcgregor** [comment]
Hello effieeee,
I couldn't find the 'clear storage' button on the application tab.
So, i deleted the snap and re-installed the snap to the 3.125.0 version.  
This has fixed the issue.
Thank you for your quick response and help.
 :-)
