### ISSUE TITLE
Cannot change default note type

### ISSUE THREAD

**Issue by dvor** [standardnotes/forum#2335]
**Describe the bug**
I would like to change the default note type to the new Super note, however I cannot find an option to change note type anymore. I checked all options in Settings, and checked [this instruction](https://standardnotes.com/help/69/how-do-i-make-an-editor-my-default-editor). There is no **New Note Defaults** section anymore.

**To Reproduce**
Open StandardNotes on macOS or iOS, try to change default note type. 

**Expected behavior**
There is no menu to do that.

**Screenshots**
<img width="696" alt="Screenshot 2022-12-08 at 16 17 27" src="https://user-images.githubusercontent.com/1132979/206484327-d4ee979b-ba38-44ca-a86b-26cf6f29db2c.png">

**Desktop:**
 - OS: macOS client
 - Version 3.121.1 (3.121.1)

**Smartphone:**
 - Device: iPhone 11 Pro
 - OS: iOS
 - Version 3.120.2 (393)

**Comment by BobWs** [comment]
Same problem can’t find the settings for changing the default note anymore!

**Comment by effieeee** [comment]
Hi, it's now located in the dropdown menu above your notes list 🙏
![image](https://user-images.githubusercontent.com/54989748/207633734-33f4f3dc-f92c-4b6c-8495-dac52f5c79c5.png)
