### ISSUE TITLE
After Search, Focus in Note List Not Following Mouse Click

### ISSUE THREAD

**Issue by kennethb22** [standardnotes/forum#234]
Still having some issues with search. I've attached a screen cast to show what's happening. First, I do a search, then hit enter. SN finds notes that contain the search term and highlights the term. So far so good. When I click on any note in the list, however, SN moves focus in the list to the note after the previous note that had focus. No matter where I click, focus in the list  just moves one note down. At one point in the video, I scroll way down in the list, click a note, and the list bounces back up to the previous note that had focus. User error or bug? Thanks!

http://www.filedropper.com/2018-06-1210-42-09

**Comment by mobitar** [comment]
Oh no, good catch. I'm able to reproduce this. I feel like this was fixed at some point, no? Have you noticed that it came back, or was it never actually fixed?

**Comment by kennethb22** [comment]
I don't recall it ever being fixed, but that doesn't mean it wasn't at some
point. I'm getting less trusting of my memory as time goes on. :)

**Comment by mobitar** [comment]
Thanks, will investigate this for the next update.

**Comment by mobitar** [comment]
Can you try version 2.2.1 and see if it's fixed for you? I tested on Mac and Win and it looked fixed, although I thought the same thing last time around too, so just want to make sure.

**Comment by kennethb22** [comment]
That appears to have fixed the issue. Many thanks!

**Comment by mobitar** [comment]
Ok great!
