### ISSUE TITLE
Tags Panel only visible when in Dynamic Panels mode (Mac desktop)

### ISSUE THREAD

**Issue by pouchofsilver** [standardnotes/forum#2345]
I'm on a Mac Desktop running High Sierra and the latest SN (well, v 3.12)

I have toggled back and forth between dynamic panels and fixed, usually preferring fixed.
I also made the tags panel invisible while in dynamic mode, as it kept popping up when I didn't want it, moving the body text to the right and giving me eye strain.

I just noticed that I can't get the tags back in fixed panels mode. I can see it's technically there, but only 2mm wide on my screen. Can't actually see any tags. They do come back in dynamic mode.

Unfortunately I don't know if I switched to fixed first or removed the tags panel first. I just know the tags are gone in fixed.

**Comment by effieeee** [comment]
Hi @pouchofsilver, are you certain that it's on v3.12? If so, that's actually quite an old version.

Can I first ask if you're able to sign into the web app (app.standardnotes.com), then check if you can disable Dynamic Panels and toggle the **Show Tags Panel** option as shown below?

![image](https://user-images.githubusercontent.com/54989748/207644451-898ee447-63fc-49fa-b472-f43cc40eced9.png)

**Comment by pouchofsilver** [comment]
Sorry, v3.120.0 :-) 
Logged in to the app, Edge for Mac browser. Same experience. I can view tags in dynamic, but in fixed mode the tags panel appears as a millimeter or 2 of vertical space with no tags in site.

**Comment by effieeee** [comment]
I see, are you also unable to manually resize the tags panel by clicking and dragging on its margin between the notes panel?

**Comment by pouchofsilver** [comment]
Yes, that’s right. I tried several times to click and drag.
I also tried toggling the Tags Panel visible/hidden option with keyboard commands instead of the cursor, in case that was changing things. No difference.

**Comment by effieeee** [comment]
Thanks for clarifying those details. Can I now ask you to send us a message at help@standardnotes.com using your account email, and also include a screenshot of how the app appears when you sign in at the moment? I'll also try to assist you further there 🙏

**Comment by pouchofsilver** [comment]
Effie, after some time away, I was able to resize the nearly invisible panel. For some reason, it let me do it yesterday. Thank you for reading and for all your help!
