### ISSUE TITLE
Cannot escape from Super note code block

### ISSUE THREAD

**Issue by dcharalambous** [standardnotes/forum#2350]
When adding a code block in a super note (after pressing / and selecting code block), once you start entering text in the code block it is not possible to escape, e.g. in order to ordinary text or anything else after the code block. 

You can escape the code block and add text before it but not after. 

This applies to the latest Windows x64 and Android versions.

**Comment by effieeee** [comment]
Currently, hitting the **Enter/Return** key thrice will close the code block and move the cursor to the line just after the code block 🙏
