### ISSUE TITLE
Cannot delete lines in Code Editor on Android (SN App v3.125.0)

### ISSUE THREAD

**Issue by xthrk** [standardnotes/forum#2351]
**Describe the bug**
I try to delete a line in a "code" note by pressing the backspace key, but the line is not deleted. Instead, the keyboard is closed. I have tested different keyboards, always the same effect. I don't know if this effect was there before, because I've only used the code editor on the desktop so far.

**To Reproduce**
1. Open or create a note and change the editor to code
2. Create some lines
3. Try to delete an empty line
4. Line not deleted, Keyboard is closed.

**Expected behavior**
Empty line will be deleted by pressing backspace.

**Smartphone (please complete the following information):**
 - OS: Android 11
 - Standard Notes App Version: 3.125.0

**Comment by jmason888** [comment]
@xthrk I've noticed the same problem for months.  There is a workaround: enter a character in the blank line, then hit backspace twice to delete the character and then the formerly-blank line.

**Comment by xthrk** [comment]
@jmason888 Thank you. I tried this workaround, but unfortunately this does not work for me. I first insert a character and then hit backspace twice. The first time I hit backspace the character disappears, the second time I hit backspace the keyboard closes. I have tested different keyboards and it's the same behavior with all of them.

**Comment by effieeee** [comment]
No longer reproducible on v3.160.17
