### ISSUE TITLE
[Help Wanted] Javascript error when launching Windows app

### ISSUE THREAD

**Issue by pdvfcdkaoc** [standardnotes/forum#2352]
Hi to all. I tried to install Standard Notes on my Windows 10 desktop. But whenever I try to launch the app, I get this error message. I tried to download Standard Notes again and reinstall, but the issue remains the same. I'd appreciate any suggestion how to fix it. Thank you!

![standard_notes_error_windows](https://user-images.githubusercontent.com/120907614/208288384-305e29e6-6bd0-4507-85c1-3a87ae96ae4b.jpg)

**Comment by effieeee** [comment]
This was fixed for the latest installers 🙏
