### ISSUE TITLE
Internal links to files and other notes

### ISSUE THREAD

**Issue by sebastianjacobs** [standardnotes/forum#2356]
I would like to have internal links to my notes and files I have uploaded to Standard Notes. So that I can embed images and link to other notes and files directly inside a note.

**Comment by shompoe** [comment]
Hi,    this feature is already available in the Supernote editor.    But that editor is still a work in progress.

**Comment by sebastianjacobs** [comment]
Nice! But I use markdown. Is this feature also planned for the markdown editors?

**Comment by shompoe** [comment]
Hi,

I am just a user like you, but gauging from everything I have ever read from the devs, I really doubt they will do much to change existing editors, which have been ported from other open source projects. But the Supernote editor seems to be their own implementation for better integration with the app.

Also, as native markdown doesn't support the features you are requesting, implementing those features in those editors would mean they wouldn't be markdown anymore. 
There is an option already in supernote to export the note contents back to markdown, albeit lacking anything not supported by markdown.
---


23 Dec 2022, 12:34 by ***@***.***:

**Comment by sebastianjacobs** [comment]
With internal urls this feature could be implemented without losing the markdown syntax.

For example in markdown the link would look like this:
`[Note title](standardnotes://458769487569456)`

These links wouldn't work outside Standard Notes and wouldn't behave like a normal link inside Standard Notes but you still have the markdown syntax.

They could also be added with an optional dropdown activated with `@`.

**Comment by jmason888** [comment]
+1 from another die-hard markdown user...
