### ISSUE TITLE
[Help Wanted] Reordering Smart Views

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#2358]
**Describe the issue**
I can't figure out how to reorder smart views on either the desktop or mobile clients. Can this be done?
Thanks all!

**Comment by effieeee** [comment]
Hi @tiddesk, unfortunately these cannot be rearranged manually at the moment, so they'll always be displayed alphabetically

**Comment by tiddesk** [comment]
Got it. Thank you!
