### ISSUE TITLE
Unsupported Account (iOS)

### ISSUE THREAD

**Issue by superhu4** [standardnotes/forum#236]
After doing the security update, I am able to login via the Mac app and online. 

However, when I try to login to the iOS app, I receive the following error:

![img_1679 1](https://user-images.githubusercontent.com/40218684/41321090-60a67524-6e70-11e8-8857-4235315db938.jpg)

When I visit the URL, it just leads me to the main standardnotes.org page. 

I've restarted the app and the phone, but to no avail.

Any thoughts?

**Comment by mobitar** [comment]
What version of the app is this? Be sure it’s 2.2 otherwise sign in
won’t work with older versions after you’ve done the security update.

**Comment by superhu4** [comment]
Thank you. The app version was out of date.

Downloading the most current vision fixed it!

**Comment by mobitar** [comment]
Ok great!
