### ISSUE TITLE
Enter your account password as it was when you registered undefined

### ISSUE THREAD

**Issue by endopa** [standardnotes/forum#2360]
Have an issue with desktop version on macos after entering my passcode. I get the msg "Enter your account password as it was when you registered undefined." "Your account password is required to recover an encryption key." Not sure what this is asking (the registered undefined part). I enter my account pw and its not accepted. I get a msg "Unable to recover your key with the attempted password. Please try again." Other desktop apps (same account) do not have this issue nor the issue below. I was having other strange problems on my desktop app so I uninstalled and reinstalled the latest version, which fixed the other strange issue (had no access to my data) and then the issue above started. If I x out of the account pw request window I still have access to my data and account settings. 

Other issue when diving into account settings, not sure if it is related or not. Under the security tab there is a msg- Error Decrypting Items ⚠️ 1 items are errored and could not be decrypted. Gives me two options: Export all ; Delete all. Right below it is the Encryption key created on (date code today) with Item ID: (hex codes) and Last Modified: Wednesday, Dec 31, 1969, 06:00 PM
and three options Attempt Decryption ; Export ; Delete 

Any help is appreciated :)

**Comment by effieeee** [comment]
Hi @endopa, hmm, if you're still able to properly sign into your account on the other desktop devices, may I know if you also cleared out the data directory when you first uninstalled the app on your affected device? If not. can I ask you to try it out as instructed in [this link](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes), then try reinstalling the latest version again?

**Comment by endopa** [comment]
Well my desktop version is back to fully functioning. I made no (known) changes. And no I did not clear out the data directory. If this issue returns I will try your suggestions, thank you.
