### ISSUE TITLE
[Feature Request] support moving child tags to topmost/root level 

### ISSUE THREAD

**Issue by berkano** [standardnotes/forum#2362]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

Yes

**Is your feature request related to a problem? Please describe.**

I created a tag hierarchy a while back and have changed my mind for certain tags which I'd like to be top-level/parent tags again. However there is no apparent way to move these back to the top level.

**Describe the solution you'd like**

When right-clicking on a subtag in the Folders panel I'd like a menu entry that says "Move to top level" / "Convert to parent tag" or equivalent.

**Describe alternatives you've considered**

My workaround for now is having a blank top-level tag and moving my subtags under that. 

**Additional context**

The context menu in question where it would be great to have a new option:

![image](https://user-images.githubusercontent.com/628547/209646845-a35a7bdc-3861-4173-9808-f2bd609081f7.png)

My current workaround:

![image](https://user-images.githubusercontent.com/628547/209646956-0eaf9b1c-e61d-4daf-9b22-7d752261e649.png)

**Comment by effieeee** [comment]
Hi @berkano, while there isn't a way to move them back to the root level from the right click menu at the moment, you can drag the selected tag to the very bottom of your current list, where there will be a space to drop the tag to return it to the root level!

**Comment by berkano** [comment]
Amazing, thank you @effieeee ! That's more than enough for me, I can live without a right-click menu option 😄
