### ISSUE TITLE
Blank screen when done editing a note on iOS 16 /iPhone 13

### ISSUE THREAD

**Issue by laurasue** [standardnotes/forum#2366]
In the iOS app when I tap “Done” after I’m finished editing a note, rather than the screen going back to my list of notes it goes completely blank. It does save my edits and I can get back in only by quitting the app.

**Comment by feinersaft** [comment]
I think it relates to https://github.com/standardnotes/forum/issues/2309

**Comment by effieeee** [comment]
Hi @laurasue , yes it may be related to the issue linked in the comment above. Can I ask you to try the workaround described in [this comment](https://github.com/standardnotes/forum/issues/2311#issuecomment-1360851482)?

**Comment by laurasue** [comment]
Thank you! Toggling the Reduce Motion setting on iOS did the trick. How weird. :)
