### ISSUE TITLE
[Google Play 12-29] Blank white screen on launch

### ISSUE THREAD

**Issue by CosineP** [standardnotes/forum#2368]
**Describe the bug**
I received an automatic update yesterday from Google Play.   Since then, the app displays a blank white screen on launch, persisting even through app restart.

**To Reproduce**
1. Update to latest Google Play version
2. Launch Standard Notes

**Expected behavior**
A list of my notes, or at least an error message

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - OS: Samsung Android 12
 - Browser Firefox
 - Version 108

Thanks for all your help

**Comment by CosineP** [comment]
Possibly related to #2354?  But, Google Play doesn't claim to have a more recent version for me

**Comment by effieeee** [comment]
Hi @CosineP, may I know if the issue persists even when you reset the app for Android as instructed in [this link](https://docs.standardnotes.com/troubleshooting/reset-apps/#android)?

**Comment by CosineP** [comment]
Ope, thanks for the link, deleting cache worked
