### ISSUE TITLE
Is it unwise to write really, really long notes?

### ISSUE THREAD

**Issue by weird-o** [standardnotes/forum#237]
Is there any practical ceiling on the length of a note? If I write an incredibly long, novel-length note, will I encounter performance issues or any other problems? If it is unwise to make a note too long, what should I limit myself to?

**Comment by mobitar** [comment]
There isn't a technical limitation, but there might be some performance limitations, especially on mobile. It's best to just play it by feel on your end.

**Comment by weird-o** [comment]
Thank you.
