### ISSUE TITLE
Auto expanding preview column

### ISSUE THREAD

**Issue by shelty22** [standardnotes/forum#2370]
It's not a problem per se but Is there a setting to toggle the auto expanding behavior of the note preview column? I can't seem to find it, if it doesn't exist it sure would be nice, for some reason I find it extremely annoying. A small preview expansion box when hovering as an alternative would be better imo.

**Comment by effieeee** [comment]
Hi @shelty22, by the note preview column, were you referring to the Notes Panel in the middle, where your notes are listed out? If so, the auto expanding behavior sounds like what the **Dynamic Panels** option would do:

![image](https://user-images.githubusercontent.com/54989748/210396006-cdeb2396-ae4d-44c9-963f-1dd8a24057c1.png)

**Comment by shelty22** [comment]
That's it! It was driving me nuts, thank You!
