### ISSUE TITLE
Unknown Error when logging in via Desktop App on macOS

### ISSUE THREAD

**Issue by spookfish** [standardnotes/forum#2374]
**Describe the bug**

I cannot log in via the Standard Notes desktop app, get an 'Unknown error' message.

**To Reproduce**

1. Open Desktop App
2. Click 'Sign in'
3. Enter email & password
4. Click 'Sign in'

Get an 'Unknown error' message. 

**Expected behavior**

Log in and all my notes / settings load.

**Screenshots**

![image](https://user-images.githubusercontent.com/1780613/210152677-d3f58dc8-3392-4b61-9c3a-8770e1b45fac.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Browser: n/a
 - Version: 12.6
 - Desktop App Version: 3.131.0 (Mac Arm64)

**Additional context**

I am not self-hosting. 

I can log in via the Android app and the web app using Firefox. 

I cannot log in via the standard notes desktop app, checking the dev. console in the app I see the below errors logged:

```
Error: Unknown error.
    at SignIn.tsx:96:23
(anonymous) @ SignIn.tsx:102
Promise.catch (async)
(anonymous) @ SignIn.tsx:100
(anonymous) @ SignIn.tsx:128
Te @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Rr @ react-dom.production.min.js:105
Fr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cc @ react-dom.production.min.js:274
Ne @ react-dom.production.min.js:52
Vr @ react-dom.production.min.js:109
zt @ react-dom.production.min.js:74
Gt @ react-dom.production.min.js:73

POST https://api.standardnotes.com/v2/login-params net::ERR_CERT_AUTHORITY_INVALID
(anonymous) @ snjs.js:43294
runRequest @ snjs.js:43290
runHttp @ snjs.js:43250
request @ snjs.js:43663
getAccountKeyParams @ snjs.js:43688
await in getAccountKeyParams (async)
retrieveKeyParams @ snjs.js:44504
performSignIn @ snjs.js:44570
signIn @ snjs.js:44549
signIn @ snjs.js:38885
signIn @ snjs.js:40483
(anonymous) @ SignIn.tsx:93
(anonymous) @ SignIn.tsx:128
Te @ react-dom.production.min.js:54
Ue @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Rr @ react-dom.production.min.js:105
Fr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cc @ react-dom.production.min.js:274
Ne @ react-dom.production.min.js:52
Vr @ react-dom.production.min.js:109
zt @ react-dom.production.min.js:74
Gt @ react-dom.production.min.js:73
```

**Comment by effieeee** [comment]
Hi @spookfish, I see, do you also receive the same error even after performing a reset of the desktop app as described in [this link](https://docs.standardnotes.com/troubleshooting/reset-apps/#desktop)?

**Comment by spookfish** [comment]
@effieeee Opening the dev. tools and clearing site data fixed it. Thank you!
