### ISSUE TITLE
iOS app not syncing

### ISSUE THREAD

**Issue by pmonks** [standardnotes/forum#238]
Title says it all.  Difficult for me to test on any other physical devices, though both the Standard Notes "desktop" (Electron) app, and https://app.standardnotes.org/ are showing the same data, so to the extent that there's any syncing between those two, syncing appears to be working.

**Comment by mobitar** [comment]
Please don’t forget to sign out and sign back in on mobile after the
security update. It should work after that.

**Comment by pmonks** [comment]
Thanks @mobitar - that was it.
