### ISSUE TITLE
Authenticator is broken on Desktop app

### ISSUE THREAD

**Issue by Saldef** [standardnotes/forum#2382]
**Describe the bug**
Authenticator editor unable to load, stating, after more than 10 seconds of load time, that "There was an issue loading Authenticator". This happened after I updated the app. It has been like that for the last two days.

**To Reproduce**
Just open the Authenticator app on a Desktop Windows App. 

**Expected behavior**
Open the note. 

**Desktop**
 - OS: Windows 10 20H2
 - App Version 3.132.2

**Note**
I have faced a lot of issues since I regrettably updated the Windows app, this issue though is quite critical, as I can no longer access the daily used 2FAs form the Desktop.

**Comment by effieeee** [comment]
Hi @Saldef, as an initial step, may I know if you’ve tried reinstalling the Authenticator as instructed below:

1. Sign into the latest version of the desktop app or the web app (app.standardnotes.com)
2. Click on the **Open Preferences** icon at the bottom left of the app
3. Click on **General** on the left hand side, then click on the **Advanced settings** dropdown menu
4. Uninstall the **Authenticator** there, and then relaunch or reload the app.

**Comment by Saldef** [comment]
Yeah, That fixed it, Thanks @effieeee!!
