### ISSUE TITLE
Define theme per device - e.g. light on e-ink tablet, dark on desktop

### ISSUE THREAD

**Issue by bugrasan** [standardnotes/forum#2384]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?** yes

**Is your feature request related to a problem? Please describe.**
- I have installed the Android app on e-ink device (black & white only).
- Using by default the dark theme on desktop/phone/etc
- However the dark theme is unreadable on e-ink devices
- Switching to light theme on e-ink device switches also to light on other devices

**Describe the solution you'd like**
Per device definition of theme (e.g. light theme on e-ink device, and dark as default theme on other devices)

**Describe alternatives you've considered**
Current workaround is using light theme as default for all devices.

**Additional context**
n/a

**Comment by xthrk** [comment]
Yes please. For example, on my mobile device I would like to use a dark theme, while on the desktop I would like to use a light theme.

**Comment by myreli** [comment]
Duplicates https://github.com/standardnotes/forum/discussions/2630
