### ISSUE TITLE
[Help Wanted] Login Fails

### ISSUE THREAD

**Issue by mark-schuegraf** [standardnotes/forum#2385]
**Describe the issue**
Login via the MacOS desktop client v.3.136.3 fails with error message "Unknown Error."

**To Reproduce**
1. Install the client. I tried downloading directly from GitHub releases both the ARM64 build and Intel build (which I subsequently emulated using Rosetta 2). I also tried [installing via homebrew](https://formulae.brew.sh/cask/standard-notes).
2. Open the client and use the login form to attempt sign-in. To this end, I tried the credentials of my work and private standardnotes accounts. The same credentials work when using desktop clients on other machines and the web client on this machine.
3. See error "Unknown Error"

**Expected behavior**
After providing valid credentials, I am logged in to my account and can sync notes.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey v.12.6
 - Chip: Apple M1 Pro
 - Browser: Mozilla Firefox (although this issue pertains to the desktop and not the web client)
 - Version: 108.0.1

**Additional context**
- No firewall is enabled
- Other devices in the same network are able to successfully log in using Android, Windows, and web clients
- I have not tried other versions of standard notes
- No self-hosting, which [appears to frequently trigger "Unknown Error"](https://github.com/standardnotes/forum/issues/1825)

**Comment by effieeee** [comment]
Hi @mark-schuegraf, can you contact us at help@standardnotes.com using your Standard Notes account email? I can continue assisting you from there as well!
