### ISSUE TITLE
corrupted timestamp after import of items

### ISSUE THREAD

**Issue by rhessmann** [standardnotes/forum#2387]
After import of items timestamp is truncated.

**Screenshots**

<img width="805" alt="2023-01-08_StandardNotes_bug_01" src="https://user-images.githubusercontent.com/46458096/211265480-7257047f-d7da-4585-8ea0-75624084d32a.png">
<img width="942" alt="2023-01-08_StandardNotes_bug_02" src="https://user-images.githubusercontent.com/46458096/211265483-4dee96bf-cb1c-4fd2-93b2-927abe6b2302.png">

**Desktop**
- Desktop: macOS  Ventura 13.1
- Web: Firefox 108.0.2
- Standard Notes Version 3.131.0 (3.131.0)

**Smartphone**
 - Device: iPhone11 Pro
 - OS: iOS16.2
- StandardNotes v3.135.0 (448)

**Comment by effieeee** [comment]
HI @rhessmann, was this item imported from an external app, or was this imported from a previous backup file?

**Comment by rhessmann** [comment]
I imported plaintext files over the file picker in the import pane. After that I've made a backup to find the relevant timestamps.

<img width="663" alt="Bildschirm­foto 2023-01-12 um 18 56 58" src="https://user-images.githubusercontent.com/46458096/212143665-896377a3-9116-40a1-a44e-8b143ae8ad98.png">

**Comment by effieeee** [comment]
Thanks for the clarification, though I'm afraid I wasn't able to reproduce this with a plain text import so far. May I ask if this is still the case regardless of the text file you use, and also regardless of the current updates to the app?

**Comment by rhessmann** [comment]
Yes, it is still the case with SN-Version 3.138.6 (3.138.6)

Today, I created at 09:14:35 a "simple-text-file.txt" which I imported at 09:23:29. 
After import one could see the correct timestamp "Mittwoch, 18. Jan. 2023, 09:14" at 09:23:39. But after seconds at 09:23:55 the timestamp was magically changed to "20. Jan. 1970, 10:00". Does this happen after syncing? 
See the attached screen shots.
<img width="1073" alt="Bildschirm­foto 2023-01-18 um 09 23 39" src="https://user-images.githubusercontent.com/46458096/213130284-e136d2f3-c63a-44c2-a785-fc498dd1254e.png">
<img width="1073" alt="Bildschirm­foto 2023-01-18 um 09 23 55" src="https://user-images.githubusercontent.com/46458096/213130295-555b6c5a-89eb-48d5-9399-9486bd41d5b8.png">

**Comment by effieeee** [comment]
Hi @rhessmann, I apologize for the delayed response on this, though so far, I was only able to replicate a similar issue when importing a JSON file exported from SimpleNote. The issue has been raised with someone on the team for further investigation, and I'll also see if I can reproduce this with Plain Text files 🙏

**Comment by effieeee** [comment]
Fixed in v3.154.1 🙏
