### ISSUE TITLE
Support of digital pen

### ISSUE THREAD

**Issue by kaemmievision** [standardnotes/forum#239]
Dies standard Notes Support digital pen? I am using standard Notes with a Samsung note  s3 and the pen of this tablet.

**Comment by mobitar** [comment]
Hey @kaemmievision, Standard Notes focuses on plaintext notes, so drawing is mostly out of the question. I don't think this is likely to change, but who knows, maybe in the future another developer creates an extension that would allow this in some form.

**Comment by kaemmievision** [comment]
I am a friend of hand writing notices.  So this would be an interesting Extension for me.

**Comment by Chabulga** [comment]
Is there any news on this? is it going to be implemented?

**Comment by JaspalSuri** [comment]
Hi @Chabulga, this is currently not part of our currently short-term or long-term plans, given our primary focus on text editing. That said, we plan to provide support for the ability to natively view images and upload files from within the apps, so it's possible that someone from the community might create an editor that allows for drawing images.

**Comment by Chabulga** [comment]
Hi @JaspalSuri, okay thank you for your quick response. That's sad to hear.

I have a view an that as a replacement of OneNote or iOS Notes to have a way of quickly and secure take hand written notes or small hand drawings like a small electrical circuit or some mechanical drawing and sync them with the PC. since all the new iPads support pencil input this is like a major use case. At least for me. 

May be you reconsider in the future or someone else helps out with this issue.

**Comment by JaspalSuri** [comment]
It's not that we disapprove of the idea, but rather that it would require some substantial changes on our part and we currently don't have the development bandwidth to support features like it at the moment (but may in the future!).

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/820

**Comment by jiaoshui87** [comment]
If you want to take lots of handwritten notes with a stylus, OneNote, EverNote, Google Keep, and Squid android note taking apps may suit your needs.
for more details: https://www.xp-pen.com/forum-5583.html

**Comment by haplopatrynz** [comment]
As someone who works extensively with digital illustrations, I understand how crucial reliable pen support is for your creative workflow. @ [VibeRantzDesigns](https://viberantzdesigns.com), we use these pens constantly to make our mushroom creature art :)

**Comment by julian-alarcon** [comment]
@effieeee https://github.com/standardnotes/forum/issues/820 doesn't exist any more.
