### ISSUE TITLE
New user (subscribed), cannot find how to create repertoires and sub-repertoires of notes (main reason for subscribing)

### ISSUE THREAD

**Issue by timothycarlson** [standardnotes/forum#2390]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Parkertg** [comment]
@timothycarlson please provide additional details. With the current amount of information the question is unclear.  
Best practice is to use the issue template by replacing the default text with information that is relevant. Please edit your section and replace the default text

**Comment by timothycarlson** [comment]
Hello, This query has already been satisfactorily answered, thank you. 

In the meantime I was waiting for a response on a problem creating Smart Views, but I solved it. 

All is good, thanks, 

Timothy 

De: "Parker" ***@***.***> 
À: "standardnotes/forum" ***@***.***> 
Cc: "Timothy Carlson" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mercredi 18 Janvier 2023 04:59:12 
Objet: Re: [standardnotes/forum] New user (subscribed), cannot find how to create repertoires and sub-repertoires of notes (main reason for subscribing) (Issue #2390) 





[ https://github.com/timothycarlson | @timothycarlson ] please provide additional details. With the current amount of information the question is unclear. 
Best practice is to use the issue template by replacing the default text with information that is relevant. Please edit your section and replace the default text
