### ISSUE TITLE
Android reauthenticate dialog: cursor jumps from password box to e-mail address box after each typed character

### ISSUE THREAD

**Issue by initiator1** [standardnotes/forum#2400]
During the Android app's forced "You need to reauthenticate to continue" sort of popup dialog, the cursor jumps from password box to e-mail address box after each typed character of the password. 

Had to click back into the password box over and over and over and over to type the next character of account password.

Cursor should not leave the password box and jump up to the e-mail address box upon each typed character.

 - Device: Pixel 6 Pro
 - OS: Android 13, security update: November 5, 2022
 - Standard Notes Version 3.138.0

**Comment by effieeee** [comment]
We've noted this and other issues with the current modal windows on the mobile apps, so we hope to fix this in future updates 🙏

**Comment by mrankine** [comment]
I noted this bug today on the Windows app. 3.131.0.

A security issue, because until the user spots the bug, they are typing their password in the clear in the email field.

**Comment by svr2** [comment]
This is also an issue with the Linux and Mac version for me.

**Comment by effieeee** [comment]
I believe this was fixed [here](https://github.com/standardnotes/app/commit/9be4f5b4cd9092550063ef67bb5ea86d91a6432c)
