### ISSUE TITLE
Share specific sets of notes via public subscription link

### ISSUE THREAD

**Issue by WinstonSmith73** [standardnotes/forum#2405]
**Describe the solution you'd like**
I would like to be able to share an entire collection of notes via a public link, in such a way that the collection is updated for subscribers as I update. In Notes on iOS I was able to send links to contacts (iOS only- boo) and my notes were automagically added to their own and would update as I updated mine.

**Describe alternatives you've considered**
A Listed blog for each note collection would work as an alternative, and maybe a better one since it would not require the person I am sharing with to use Standard Notes.

**Comment by myreli** [comment]
Duplicates https://github.com/standardnotes/forum/discussions/2652
