### ISSUE TITLE
[Help Wanted] Daily Notebooks Feature

### ISSUE THREAD

**Issue by sp2220** [standardnotes/forum#2408]
In the December blog update the "Daily Notebooks" feature was announced (see excerpt below). How and where do you find this in Standard Notes? I'd like to use it and can't find any other reference to it or find it in the UI. 

"We've also added Daily Notebooks, which is a great way to keep a daily journal. A new note is created every day, so you can capture your thoughts and experiences as they happen. And if you want to highlight certain notes, you can star them and make them appear in a special "Starred" section, which means you don't have to clutter up your main feed with pinned notes."

https://standardnotes.com/blog/introducing-super-notes-moments-and-offline-file-access

**Comment by Parkertg** [comment]
Each tag has the option to have unique viewing settings such as sorting & this daily notebook view. 
1. Select a tag you'd like to use this feature with. 
2. At the top of the notes column, there is the title of the selected tag and, to the right, view settings (looks like a sort button). Click it
3. By default it may show the default global view settings. Click on the tab to make unique settings for this tag.
4. Down the list you should find the dailynotes feature. Along with other possibly useful viewing options

**Comment by sp2220** [comment]
Awesome. Thank you!
