### ISSUE TITLE
drive backup: please support scoped tokens

### ISSUE THREAD

**Issue by philips** [standardnotes/forum#241]
The Google Drive backup extension requires full permissions. Please create scoped tokens like the Dropbox integration!

**Comment by mobitar** [comment]
Hmm..I thought this wasn't the case. I'll have to recheck this. Thanks for the heads up.

**Comment by philips** [comment]
Looking at the API it seems that you can't scope the AuthZ to a specific folder. How silly! The closest thing is the App Folder API but that won't give non-programmatic access to the backups. 

https://developers.google.com/drive/api/v3/about-auth

**Comment by philips** [comment]
Closing this issue due to Drive not supporting scoping.

**Comment by mobitar** [comment]
The scope we request is `https://www.googleapis.com/auth/drive.file`, which is:

>  Per-file access to files created or opened by the app. File authorization is granted on a per-user basis and is revoked when the user deauthorizes the app.

So I believe the permissions are correct..
