### ISSUE TITLE
Bulk-update of editor type (multi-select notes)

### ISSUE THREAD

**Issue by pbryant-phew** [standardnotes/forum#2414]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes.

**Is your feature request related to a problem? Please describe.**
The context is after having imported a large number of notes from an Evernote .enex export.  All notes imported from .enex by the SN Evernote import tool get placed into the SN Notes view/list and tagged with #evernote (the user has no choice or control around this).  Evernote uses HTML as the note storage format.  Although the SN import tool knows this, it nevertheless associates each imported Evernote note with the Plain Text editor type, making the imported notes essentially useless to the SN user until each note is updated to use the Rich Text or Super Tool editor.  According to documentation and SN Support, the only way to update the editor type for a note in the app is to select each note and manually change its editor type, one by one.  That's unworkable across potentially thousands of recently imported notes.

**Describe the solution you'd like**
Allow multi-selection of notes and bulk-update of the editor type associated with the multi-selected notes.
Ideally provide this option for notes returned in a search filter results list as well as random multi-select from any other notes list view.
Alternatively, and less favourably, SN could automatically associate imported Evernotes with the Rich Text or Super Tool editor type after importing them.

**Describe alternatives you've considered**
SN Support confirmed that there are no alternatives to the described problem. 

**Additional context**
None.

**Comment by fra-gadio** [comment]
Yes, I agree.  I just imported thousands of notes from Evernote and going through them one by one and change them to rich text is an incredibly time-consuming task that I'm not even going to attempt.

**Comment by pbryant-phew** [comment]
@fra-gadio It's just not a task for a human; code can do that a tiny bit quicker.  If that meets the Longevity policy, of course lolz

**Comment by effieeee** [comment]
This is already being considered for development 😊

**Comment by effieeee** [comment]
Hi all, this now doable on [v3.141.0](https://github.com/standardnotes/app/pull/2180)! After selecting multiple notes, click on the note type menu on the top right of the app, and you should find that choosing a note type from the list will apply it onto all of the selected notes! 👍
