### ISSUE TITLE
Listed and self-hosting

### ISSUE THREAD

**Issue by deljones** [standardnotes/forum#2418]
**Describe the issue**
Thanks to all for the hard work in bringing this excellent software to the community. I'd like to take advantage of **Listed**, however I am not able to connect or create a Listed account when self-hosting

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://listed.to/
2. Follow instructions and create an author in the app
3. In the app go to >> Preferences >> Listed
4. Click 'Create New Author'
5. 'Create New Author' goes grey for a few seconds. No new information is presented

**Expected behaviour**
Click 'Create New Author' should feedback that your author has been created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Ventura 13.1
 - Browser Brave
 - Version [Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (arm64)](https://brave.com/latest/)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 16.1
 - Browser Safari
 - Version 

**Additional context**

**Comment by effieeee** [comment]
Hi @deljones, I apologize that no one was able to respond to your request here. Are you still experiencing problems with this and #2419?

**Comment by LimeDrive** [comment]
Hi, I got the same issues.

Both on app.standardnotes.com with a free account and on desktop app ( mac ) connect to my selfhosted instance with an offline subscription activated.

Browser : 
- Brave
[Version 1.52.122 Chromium: 114.0.5735.110 (Build officiel) (x86_64)](https://brave.com/latest/)

Desktop app : 
- MacOS Ventura 13.4 (22F66)
- Desktop 3.160.19

I don't know witch log file to check to give you more details.

**Comment by effieeee** [comment]
Hi, my apologies for not updating this any further. However, I was able to confirm that self-hosted users are really not able to create Listed blogs from their instances of the app 😞 For these cases, users are advised to create separate accounts on the official server where they can create a blog and publish notes.
