### ISSUE TITLE
Avoid syncing

### ISSUE THREAD

**Issue by morenogo** [standardnotes/forum#242]
Hello,

Is there a way I can sign up, and avoid having my notes synced to the server? I don't want to store information in the cloud. Alternatively is there a way to open up the app without having the "Register/Sign in" window?

Thanks in advance.

**Comment by mobitar** [comment]
You can use the app without a server, but currently the sign in window will open by default. You can also self host a server. I'll try to think of a solution for offline only usage and the sign in window.
