### ISSUE TITLE
Menus in app are invisible yet still clickable, among other issues

### ISSUE THREAD

**Issue by madameblueberryxo** [standardnotes/forum#2422]
**Describe the bug**
There are menus in the app that are there and can be clicked on yet cannot be seen. Also, when typing in a note, clicking “done” to the right of the keyboard produces a blank screen which requires that the app be restarted. 

**To Reproduce**
1. Go to main page before signing into the app
2. Click on random space somewhere on the middle right of the screen and open help and feedback
3. Switch to Account and select sign in
4. See error, which the error is there are things that cannot be seen. 

**Expected behavior**
I expect to be able to see the things I am clicking on. For the keyboard, I expect that clicking some on the keyboard would collapse the keyboard and nothing else. As for the passcode, I expect to see notes after clicking submit and not just a blank screen. 

**Screenshots**
The problem is best explained with screen recording since half the issue is that things are invisible. I have put the recordings and photos into a Dropbox folder since I was not able to add the video here directly https://www.dropbox.com/sh/c06nspee86rxb78/AACMKmVe5d8Zone3B9hDU9p6a?dl=0

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16.2
 - App Version 3.140.0

**Additional context**
The issue of not seeing what is there is applicable on the sign in page before logging into the app as well as after signing in and going to the sidebar where all of the tabs are. When I click on the head icon at the bottom of the screen for the account options, nothing shows but there is stuff there that is clickable. 
I also managed to set a passcode in the app even with all of these issues and now cannot use the passcode to log into the app at all because after submitting the passcode, the notes do not show and there is nothing clickable just a blank screen which is also what happens after clicking “done” on the keyboard and the app must be restarted.

**Comment by effieeee** [comment]
Hi @madameblueberryxo, while I'm not certain if it's entirely related, I noticed that part of your issues included how the app just stays as a blank screen after you provided your passcode for authentication. May I ask if you've tried the instructions in the comment below, to check if it might help, in case your issue is also related to the app animations?

https://github.com/standardnotes/forum/issues/2311#issuecomment-1360851482

**Comment by madameblueberryxo** [comment]
@effieeee, This has solved most of the issues! Thank you very much! I am now able to log onto the app and use the “done” button on the keyboard with no problem. 

However, unless the Reduce Motion setting remains off on my iPhone, I am unable to access the account settings menu at the bottom of the tabs screen. 
![0F756814-FA2F-475C-94B1-A08EB368A7E4](https://user-images.githubusercontent.com/116027894/214366344-e090d939-ca03-45a3-96d5-45c4ca848844.jpeg)
All of the buttons in the red box are unusable to me when reduce motion is on. If I click on one while reduce motion is on, the same issue of things that I cannot see yet can click on randomly around the screen still happens. I cannot click on what I can see but I can click on something that I cannot see which will then show up as shown in the photo below. 

![032FB8B6-174E-44F8-8578-D72789B22FC7](https://user-images.githubusercontent.com/116027894/214367368-f3bab120-9624-418d-8273-ce5908e01cb7.png)

To get this sign out option, reduce motion was on, and I clicked on the little account head icon and nothing was shown but then I randomly clicked around the screen and this appeared. When this happens, I must restart the app to get back to writing (even if I select cancel and do not sign out I must still restart) and, if I want to use the settings, I must turn reduce motion off.

Thank you for your help! Now that I know what to do it is easy to work around and I will be able to use the app easily.

**Comment by effieeee** [comment]
Glad to hear that the workaround helped in some way, and this does give some needed info on what's causing this. Thank you for trying it out as instructed! 🙏
