### ISSUE TITLE
Editing an imported a note changes date to 1970/01/20 10:12

### ISSUE THREAD

**Issue by sonjoonho** [standardnotes/forum#2426]
**Describe the bug**

When I import a note, the creation date is correctly set to the current date. When I edit that note (including adding/removing a tag), the date changes to 1970/01/20 10:12.

Note history shows correct time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Import a note
2. Edit the note
3. Observe creation date

**Screenshots**

https://user-images.githubusercontent.com/20669173/214827358-d5b966d4-3680-4849-bbe5-f85b389df0f3.mov

**Desktop (please complete the following information):**
 - OS: 13.1
 - Browser: Chrome
 - Version 109.0.5414.87 (Official Build) (x86_64)

**Comment by sonjoonho** [comment]
Oh this actually looks like a duplicate of https://github.com/standardnotes/forum/issues/2387.

**Comment by effieeee** [comment]
Hi @sonjoonho, please see [this comment](https://github.com/standardnotes/forum/issues/2387#issuecomment-1406402603) on that issue for an update on this as well 🙏
