### ISSUE TITLE
Super: Characters from both the left and right of the cursor are deleted on Android

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#2428]
Hitting the erase button on the Android app erases both letters on the left and right of the cursor, which is very frustrating. It's having a pretty negative impact on my user experience and productivity.

I hope this issue will get fixed asap. 🙏🏽

I'm mostly using Super type of note on a Oppo Reno8 Lite 5G.

**Comment by effieeee** [comment]
The fix for this issue is coming up on [v3.160.17](https://github.com/standardnotes/app/commit/0cb73b5d18ece035e2fce904c859d548b8657053), please look out for the update on the Play Store!
