### ISSUE TITLE
Download links not working (Mac)

### ISSUE THREAD

**Issue by danilichti** [standardnotes/forum#2429]
Describe the bug
When trying to download the .dmg file for macOS (problem exists for both the arm and intel download links), the webpage returns a 404 error and the .dmg is not downloaded. As a result, cannot install standard notes on macOS currently. 

To Reproduce

Go to https://standardnotes.com/download

Click on either the intel or apple silicon download links
https://github.com/standardnotes/app/releases/download/%40standardnotes/desktop%403.142.2/standard-notes-3.142.2-mac-x64.dmg
https://github.com/standardnotes/app/releases/download/%40standardnotes/desktop%403.142.2/standard-notes-3.142.2-mac-arm64.dmg

See 404 error

Expected behavior
.dmg file should download

OS: [e.g.macOS]
Browser [arc ]
Version 0.86.0 (36828)

**Comment by core-code** [comment]
i can confirm the issue

**Comment by effieeee** [comment]
Upon checking now, this has been fixed for both Intel and M1 versions of
the installer 👍

**Comment by core-code** [comment]
downloads are offline again

https://standardnotes.com/plans?downloaded=mac-intel
=>
404

**Comment by core-code** [comment]
@effieeee again the download links for macOS are offline. can you do something against this happening all the time?
