### ISSUE TITLE
[iOS] Crash on opening the app

### ISSUE THREAD

**Issue by aramisf** [standardnotes/forum#2437]
**Describe the bug**

The iOS app (build 1.345.1) is crashing on iOS 14.4.2 on an iPhone Xr. The issue was first observed on build 3.142.8.

It also happens if I try the browser version on the phone. That's not actually my main use case, but I decided to give it a try in order to gather more information.

I've tried on Firefox 109.0 (25841) and on Brave 1.46.2 (23.1.10.20), and they both bring me a blank screen when I visit app.standardnotes.com. It doesn't matter if I use the private mode, the issue happens on both sides.

Could it be related to the iOS version?

**To Reproduce**
1. Install the app, if it is not installed already
2. Tap on it's icon to open it
3. See a completely blank screen

For browser mode:
1. Open the browser and enter app.standardnotes.com in the URL input field.

**Expected behavior**
The app opens normally as expected.

**Screenshots**

https://user-images.githubusercontent.com/452174/216582806-f1489d77-0a15-4c69-b3d0-c5a04999b9cf.mp4

https://user-images.githubusercontent.com/452174/216582814-3105e424-f23f-482c-88df-28021297d185.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 14.4.2
 - Version 1.345.1

**Additional context**
I've tried using wifi, data, turning VPN on and off. Network does not seem tobe related.

**Comment by BobWs** [comment]
Same problem with standardnotes on iOS 14.4.2 also only a blank screen when opening the app. Reinstalled it a few times but it still isn’t working!

**Comment by zzzpppzzz** [comment]
I am also having this exact same issue. iOS 14 as well..

Really would love a fix as app is completely unusable for me at the moment.

**Comment by atmoio** [comment]
Thanks for reporting, this is now fixed here: https://github.com/standardnotes/app/commit/088804dee1764ee18893d7f1b809075cb68b1f57

The fix will be available on the web app (https://app.standardnotes.com/) in about one hour, and will be available on the mobile apps as an update early next week. Note that the web app and mobile app are exactly identical.

**Comment by aramisf** [comment]
@moughxyz thank you so much for the quick response and resolve the issue.
The new version is working great! I'm very happy to be able to use the app again :D
