### ISSUE TITLE
Add an option to deactivate the automatic date in the title for new notes

### ISSUE THREAD

**Issue by shamiqua** [standardnotes/forum#2445]
Often I just quickly write something down and it gets hard to find when there a a ton of notes just with the date in the title. It just got less easy to find the notes I’m looking for. I loved that it took just the first line of a note as the title, back in the day. 

Any option to do this?

**Comment by affvalente** [comment]
You can change that in the preferences - global or by tag

![image](https://user-images.githubusercontent.com/25633523/217819351-b1ee23ec-4673-4b4d-bc52-55668201bb04.png)
