### ISSUE TITLE
Scroll to search term found 

### ISSUE THREAD

**Issue by fra-gadio** [standardnotes/forum#2446]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

**Is your feature request related to a problem? Please describe.**
I have long notes and if I search a word it will find the right note but it won't scroll to the position where the word is.  That means I have to manually scroll until I see the highlighted word and it's difficult and time consuming.  Sometimes, I have to copy  the note to a text editor to find the term there. 

**Describe the solution you'd like**
When clicking the note/s with in the search results, automatically scroll to the right position where the term is found. 

**Describe alternatives you've considered**

**Additional context**

**Comment by infold** [comment]
I'd love a more comprehensive search feature like this too. Wouldn't mind a web browser-style ctrl+F bar where you can tab through each time that string appears in-text.

**Comment by effieeee** [comment]
An in-note search function which navigates to each search term on the note is now available on the **Super** note type! 🙏
