### ISSUE TITLE
Blank White Screen on App Launch (iOS)

### ISSUE THREAD

**Issue by zzzpppzzz** [standardnotes/forum#2449]
**Describe the bug**
Whenever I open the app in iOS, all I get is a completely blank white screen and nothing else. I am not able to do anything in the app as there is nothing displayed and no way to click or do anything. Just a completely blank white screen and that's it. 

**To Reproduce**
1. Open the app in iOS

**Expected behavior**
App opens normally

**Screenshots**
(not necessary - imagine a blank white screen with nothing else..)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 12 Pro Max]
 - OS: [e.g. iOS14.2] - I noticed another use with the same problem was also on iOS14 - possibly an iOS 14 issue?
 - Version [latest version of iOS app]

**Additional context**
Problem has been occurring for at least a week now. App is completely unusable at the moment..

**Comment by atmoio** [comment]
Thanks for reporting, this is now fixed here: https://github.com/standardnotes/app/commit/088804dee1764ee18893d7f1b809075cb68b1f57

The fix will be available on the web app (https://app.standardnotes.com) in about one hour, and will be available on the mobile apps as an update early next week. Note that the web app and mobile app are exactly identical.

**Comment by zzzpppzzz** [comment]
Awesome. Thanks for the quick fix.
