### ISSUE TITLE
Super note: Cannot fully cycle through block selection menu using up/down keys

### ISSUE THREAD

**Issue by xthrk** [standardnotes/forum#2452]
In browser and desktop app (did not tested on mobile) in a super note, after typing /, I cannot fully cycling through the available options. The selection cycles through the available options, but the selected option is not shown, after the selection left the visible area.

**Comment by myreli** [comment]
I can [replicate](https://www.loom.com/share/f7ccc20ce2ab434f8de9ff3efaef20ac) this navigating with the keyboard arrow keys, while scrolling works fine.
