### ISSUE TITLE
Standard Notes changes font size (also bolder?) when the app or browser window is dragged smaller

### ISSUE THREAD

**Issue by xthrk** [standardnotes/forum#2453]
Perhaps related to #2247.

I dragged the default Notes window smaller on my Windows device today because I want to show two windows side by side. I noticed when I did this that the font changes, seeming to get slightly larger and bolder.

Not easy to see because GitHub is enlarging my screenshot here. But definitely noticeable on my device.
On the left the font with a maximized window, on the right with a smaller window:
![grafik](https://user-images.githubusercontent.com/116081825/218308609-9e8a4176-35b9-4476-b514-b3225c120c0b.png)

**Comment by effieeee** [comment]
This no longer seems to be the case on v3.161.1
