### ISSUE TITLE
Startup Maximize Issue

### ISSUE THREAD

**Issue by infosisio** [standardnotes/forum#248]
I am on Ubuntu 18.04 with Gnome and if I set the application to full screen, then I exit and re-launch I get a really ugly effect of loading/maximizing the application. This could be fixed for the best experience of all users.

**Comment by mobitar** [comment]
Thanks for the heads up, I'll have to test this. If you can create this on the Desktop repo that would help me track it better. https://github.com/standardnotes/desktop
