### ISSUE TITLE
Rendering Glitch When Switching Between Markup And Standard Notes

### ISSUE THREAD

**Issue by infosisio** [standardnotes/forum#249]
When you are viewing a Markup note and then you click on a Standard note, it loads the note in a sort of sloppy way, it's not instant rendering. I think this is something that could be figured out by adding debouncing - it is certainly worth it to look into.

**Comment by mobitar** [comment]
Hmm..I'm not seeing this. Which editor are you referring to?

**Comment by infosisio** [comment]
@mobitar Simple Markdown editor and then Regular editor, I clearly have it here.

**Comment by mobitar** [comment]
Ah do you mean going from a plain note to a Simple Markdown Note? In that case I see what you mean. Do you have the action bar enabled? I don't see this behavior if I have that disabled. What's happening is that the Action Bar momentarily moves up while the editor loads, then is pushed back down.

**Comment by infosisio** [comment]
@mobitar No, I was going to report that too but that is not the issue I am referring to now. What I am talking about is that you see some effect in which the text in the Plain editor seems to kinda increase size momentarily. If you switch between markdown notes, you do not see anything like that and it would be ideal if this was the same case for plain notes.

**Comment by infosisio** [comment]
@mobitar I can confirm that this is not happening in the web version by the way.

**Comment by mobitar** [comment]
By sponsoring do you mean some kind of bounty? Maybe. But for issues like this it would likely involve getting deep into the codebase, which I don't think the casual contributor will have time to do. Strange it's not happening on web. It's the exact same codebase. Although desktop would probably just load the editors quicker since they're locally on disk.
