### ISSUE TITLE
did i loose a note or was it user error + tag sync issue

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#250]
setup
  linux desktop app (not using browser interface) v2.2.4
  android phone v2.2.11
  android tab v2.2.11

lost a note but recovered from backup

the other night i was looking at previewing different versions of a note by copying the text  inrto a file and diffing them.  i didn't finish and this afternoon i was going to go back and finish but before i did, i made a test note and made chages that i could view in versions to see if i restored a version if i could revert.  answer was yes.  

after i tested my notes, i went to open the original note that i was working on last night and saw that it was gone from the desktop and my phone.  i opened my tablet (android) which has a macro that turns off wifi when it leaves the sid and it was on the tablet (no syncing).  

are there any logs that i can view to see if there was user error?
i did the open console, but didn't find anything and ditto for data directory
does the mysql db have user actions recorded?

do you restore the the encrypted auto backup  from the account import backup?

---------------------
fast forward to today:
I entered a note on my phone last night
today i went to look for it in the family tag. not there, also not on desktop
I see it on my tablet who's wifi was off since this morning (mod time of jul 8  9:33pm)
I backed stuff up and turned on the wifi, did not show up on phone or desktop nor delete from tablet.
I searched for the note and found it with no tag
i re-tagged it and now it's on my phone in the family tag and on the desktop in the family tag
   but, and it's a big butt  (the date on the 3rd line of the title, which i think is modification time)
   phone mod is jul 9 11:03p
   desktop mod jul 8 9:33p
   tab mod jul 8 9:33p

in addition i have  a note of funny things my kids did and
   desktop feb 19 2018 2:26pm
   phone jul 7 2018 9:55p
   tab feb 19 2018 2:26pm

I id a refresh on all devices
Is this post clear? I'm rushing a little

thx

**Comment by mobitar** [comment]
Hey @WCJLJZUBTSC, thanks for the writeup. I'm having a little bit of a hard time following along with all the details. I read it a few times but struggling to juggle all the factors in my head. If possible, can you help me understand this via the context of "what I expected vs. what the result was". i.e "I wrote a note on desktop, and on my phone with an active internet connection, I expected it to appear, but it did not." Also, eliminate any details that aren't necessary if possible.

Essentially I'm just trying to distill this down into one or two sentences I can loop in my head so I can really diagnose the situation.
