### ISSUE TITLE
[Feature request] Reverse sorting order for notes

### ISSUE THREAD

**Issue by rivol** [standardnotes/forum#253]
ATM the notes can be sorted by title or added/modified date, but the sorting is always ascending.
I'd like to be able to sort the notes in descending order as well.
My use case is similar to #67 - I keep the 'date' of the note in it's title (e.g. `2018-07-11 - Some meeting` or `2018-07 - Standard Notes`) and want the latest notes to be at the top of the list.
UI-wise, for me the most natural way would be if I could click on the selected sorting order choice (e.g. `Title`) again, and that would reverse the sorting.

**Comment by greiggy** [comment]
I use reverse dates in titles as well -- same purpose, to order notes. Click on order button to toggle ascending/descending would be ideal. Two levels of sort, e.g. date created/modified then title, would be really good.

**Comment by mobitar** [comment]
Yeah, definitely a useful feature, hope to add this in at some point in the near future.

**Comment by fmaiabatista** [comment]
Any updates on this?

**Comment by mobitar** [comment]
In next release.

**Comment by mobitar** [comment]
Reverse sorting is available now across all platforms (since v3 release).
