### ISSUE TITLE
[Feature request] different cursor when overtype mode is active

### ISSUE THREAD

**Issue by rivol** [standardnotes/forum#254]
When toggling between _insert_ and _overtype_ modes with Insert key on the keyboard (https://en.wikipedia.org/wiki/Insert_key), text editors often use a different cursor (basically highlighting the next character) to indicate that the overtype mode is active.
Standard Notes doesn't seem to support this ATM (tested on native Linux app, and on the web demo account). Would it be possible to add support for it, or would it be too much work given the webkit-based rendering?

**Comment by mobitar** [comment]
Hey @rivol, not familiar with these modes. The plain editor will just use an HTML textarea. Do you know if they support it? I would doubt it. If they don't, then I don't think there's a solution for this, short of some external editor solution, like the [Vim editor](https://standardnotes.org/extensions/vim-editor).

**Comment by rivol** [comment]
Yeah, with HTML textarea, it's extemely doubtful (save for browser-specific support perhaps, but that's out of your reach).
Might be doable in the fancier editors, e.g. simple-markdown-editor. Feel free to close the issue though, or move to editor component as you see fit.

**Comment by TheodoreChu** [comment]
I don't think these are available with HTML textarea. Searching "overtype" in MDN web docs produces no results: https://developer.mozilla.org/en-US/search?q=overtype
