### ISSUE TITLE
Opening note from notes list

### ISSUE THREAD

**Issue by greiggy** [standardnotes/forum#255]
in iOS, when I go from the 3-line notes list in iOS to the full note, the note opens in an editor.

When referring to notes from synopsis to detail, like giving a presentation or in a discussion, the appearance of the editor is a real nuisance.

I think it should open in a 'read' view, with an option to edit. Which is probably what was intended!

**Comment by mobitar** [comment]
I agree it could be annoying when it's not what you want. I'll explore adding a preference for this, or some other solution.

**Comment by greiggy** [comment]
Apple Notes, Bear, Evernote etc show a similar behaviour.

- Note synopsis (from list) opens in read view

- Touch and move will scroll note

- Touch without moving will open editor -- keyboard appears

Personally I would prefer to double tap to open editor. The reason is, while scrolling a long note to the right place (as in discussion or presentation or just reading) I don't want to have to get rid of the keyboard if it appears!

For what it's worth....

--IanG

Ian Greig

**Comment by greiggy** [comment]
From a bit more testing, it appears that a note _composed on the device and in SN_ behaves what I would term 'normally' i.e. opens in read view without the editor appearing.

Notes where content _has been pasted in_ produce the editor when the note is opened.

**Comment by mobitar** [comment]
When you say editor, you mean like one of the editor extensions, like the Plus Editor? Or do you mean just the plain editor in edit mode?

**Comment by greiggy** [comment]
As far as I can tell, it depends which editor is "set" for that particular note. So I have seen the Plus editor and also the plain editor.

**Comment by Clarin83** [comment]
I think this is the hardest issue with SN
It's so frustrating open any note with extension in IOS app.
Take alot of time and is so leaging.

This experience with the paid version is disappointing...

the solution proposed by greiggy seems to me the right one.

Show the note WITHOUT the editor and if you want press a button to open the edit.

As all the other note apps do: Like Joplin for example

Tankyou for your time.

**Comment by mobitar** [comment]
The problem is "the button". There isn't any space for a single button in the current view. I can jam it in somewhere, but I'm afraid it'll look bad. Need to play with it some more.

**Comment by greiggy** [comment]
Some others work with varieties of swipe left/swipe right. Best for user
reference is where note list and expanded note are both partly visible –
can go either to list or to full expanded note. Edit can be a variation on
the swipe...


On 20 July 2018 at 16:01:49, Mo Bitar (notifications@github.com) wrote:

The problem is "the button". There isn't any space for a single button in
the current view. I can jam it in somewhere, but I'm afraid it'll look bad.
Need to play with it some more.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/forum/issues/255#issuecomment-406627670>,
or mute the thread

**Comment by mobitar** [comment]
Hmmm..that's actually a neat idea. A horizontal scroll view to switch between editors. Swipe back and forth. I'll have to test that out! Pretty sure it's going to create a bunch of complications, but if it works, it might just be the right way to do this.

**Comment by effieeee** [comment]
On new UI, notes and editors load much faster 😊
