### ISSUE TITLE
Delete single checklist Item

### ISSUE THREAD

**Issue by fra-gadio** [standardnotes/forum#2562]
Hi, 
There should be a way to delete a single checklist item without having to use the 'delete all completed' button. 
I don't want to delete all completed checked items, I just want to delete one.

**Comment by jpgill86** [comment]
Use backspace/delete to clear the contents of the item, and then press return/enter. That will remove it from the list. It was quite some time before I discovered this as well!

**Comment by fra-gadio** [comment]
Thank you so much!  I would have never realized it would work that way! :)
