### ISSUE TITLE
Published notes automatically interpreted as Markdown

### ISSUE THREAD

**Issue by nicolasduteil** [standardnotes/forum#257]
Hi
Would it be possible to indicate the formatting when publishing a note ? If I want to publish a plain text note which happens to contains markdown tags, formatting will be messed up
For example, here's the content of my plain text note :
```
Test with some_multiple_underscores
# I don't want to see it as markdown
```
And here's the result after publishing :

![image](https://user-images.githubusercontent.com/5278949/42697591-d8e95520-86bb-11e8-9825-9e84e80817a3.png)

I suppose I could just wrap the notes with \``` \``` but the whole point was to have a plain text note :)

Other than that, I'm an happy subscriber

**Comment by mobitar** [comment]
Hey @nicolasduteil, you're referring to publishing with Listed right? Listed is currently Markdown by default. You can probably escape Markdown using some combination of `\` or `/`, but that might be cumbersome too. I'll keep this in mind, but this is a relatively rare request (you're the first).

**Comment by nicolasduteil** [comment]
Hi, yes I was referring to Listed. I understand this is a rare request. In fact I didn't notice it before I tried to use StandardNotes as a replacement for pastebin to share code sample or config file

**Comment by TheodoreChu** [comment]
Probably the best thing to do is to put the note into code fences:

`````
````plaintext

text

```js
const foo = bar;
```
````
`````
