### ISSUE TITLE
Change language for spell checker

### ISSUE THREAD

**Issue by pmagdon** [standardnotes/forum#258]
I am missing an option to change the language of the spell checker.

**Comment by pmagdon** [comment]
Hi @mobitar , thankyou for the reply. I guess the option to set the language would be important for anyone how uses a system local langues different from the notes (e.g. as in my case English notes on a German local system).

**Comment by guydog** [comment]
I second this request, I think it is a crucial one: nowadays it is common for most people to write in different languages, I hope you could offer it very soon or at least provide with a workaround.
Thank you.

**Comment by JGallus17** [comment]
^^^ is there a way to change it so it can spell-check my spanish? (On PC, on my phone I can just use the spanish keyboard and have no problem)

**Comment by mobitar** [comment]
Hey @JGallus17, not currently. However we hope to explore this feature in a future release.

**Comment by Sib0t** [comment]
No update on this? How the default selection is made ?

**Comment by baptiste-grob** [comment]
This feature is coming soon to the desktop app 👍

**Comment by meow464** [comment]
Is this possible now? I can't find the option.

**Comment by meow464** [comment]
I found it. Top menu > Edit > Spellchecker language.
StandardNote seems like a great app so far!
