### ISSUE TITLE
Choice of editors for Android

### ISSUE THREAD

**Issue by JPL1** [standardnotes/forum#26]
Will a choice of editors be available for Android? If I create a note on my PC in, say, Plus Editor and then view it on my Android phone I see all the encoding. Only basic notes or those created with the Code Editor are rendered in a readable format.

**Comment by mobitar** [comment]
Editors for mobile is a whole other beast of an engineering challenge, and not one I'm ready to take on yet. Would make the mobile apps very complex. But maybe one day..
