### ISSUE TITLE
[Features Request] (Plus Bug found) - IOS Notes Exporting

### ISSUE THREAD

**Issue by s0ftwhere** [standardnotes/forum#261]
Hello,

I am sorry if someone talked about this already. I could not find it.

I would like to request a feature where the IOS app asks for your notes password before it exports decrypted notes (or even encrypted notes too).

Also when I try to export notes from the IOS app: If I choose "Encrypted" it opens the email app with the file as expected. However, if I choose "Decrypted", all I get is "Preparing Data". This message just stays and nothing happens. Not sure if I am doing something wrong or it is a bug.

Thank you so much for your work!!! :)

**Comment by mobitar** [comment]
Hey @s0ftwhere, thanks for the feedback. Your suggestion is an interesting one, however, would be a little tricky. A lot of people forget their passwords, and use their mobile app as a backup where they can export their data safely. If we request the account password before export, it would lock a lot of users out of their final recovery option.

The best solution to this is to use the Passcode Lock option. This protects against unwanted physical access of your device. 

As for the bug, that's strange. What version of the app is this?

**Comment by mobitar** [comment]
Hmm..that's an interesting idea.

Thanks for the heads up on the export issue. This is fixed in 2.3.2 (pending approval by Apple).

**Comment by s0ftwhere** [comment]
No problem. Thank you for the good work!
