### ISSUE TITLE
search behavior

### ISSUE THREAD

**Issue by surfchaser** [standardnotes/forum#264]
I use mobile mostly and instead of using "tags" I use a combo of unique number letter combinations. I find it quicker and less cross platform quirky.  For example.

And search works
7is 7fl 7gaf 
would find 
someone who is an installer, and in florida, and uses GAF products

+++++

what would be nice to have working

is the Negative search
7is 7fl -7ec 7gaf 
an installer, and in florida, NOT in escambia county, and uses GAF products

and also some way to implement the OR search
7is 7fl 7ec "or" 7src 7gaf 
an installer, and in florida, in escambia county OR santa rosa county, and uses GAF products

thanks

**Comment by mobitar** [comment]
Advanced search is not likely something that will be included in the core product, but instead delegated to an extension. There are no plans right now for this sort of extension, but I'm sure we'll see it at some point in the future.

**Comment by surfchaser** [comment]
OK.  Thanks for the reply.  
Curious if you know (or could reveal) the average amount of notes on your service per user.  I currently am running about 4300.  It seems the more notes you have ...the more you rely on search.

**Comment by mobitar** [comment]
I only know figures like these based on what people reach out to me with when asking for help. 4300 is definitely on the high end. You can use Smart Tags to help create filters to find notes quickly: https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes
