### ISSUE TITLE
How can I set the default sync server URL in self-hosted web app?

### ISSUE THREAD

**Issue by jeremykraft** [standardnotes/forum#266]
Where can I set the default sync server domain/sync server URL?

I have my own standardfile server setup and on the standardnotes web app, would like to set the default sync url so clicking, "advanced options" and entering in the url is not necessary.

E.g., https://app.standardnotes.org/ has the default set to https://sync.standardnotes.org/.

Thanks much!

**Comment by mobitar** [comment]
You can set `SF_DEFAULT_SERVER` in your .env file.

**Comment by jeremykraft** [comment]
Worked perfectly, thank you!
