### ISSUE TITLE
Import Custom Extensions

### ISSUE THREAD

**Issue by PhilipWhiteside** [standardnotes/forum#267]
Is there an option to import custom extensions? Mostly so that I can download one of your themes, tweak it a bit, and suggest updates back to you. 

I can live edit the page, but I don't know how those edits are reflected back into the source, until I play around and find it. For example, on the Folders extension, I'd like to move the side to side scrollbar to the bottom. To do this I know I can do 

```css
.ng-scope {
    height: 100%;
}
```

But I don't know how this plays with the rest of the elements, or how to place new tags for better css selection.

**Comment by mobitar** [comment]
Yeah, you can download our themes from [here](https://github.com/sn-extensions/) and import them per the instructions [here](https://docs.standardnotes.org/extensions/publishing.html).
