### ISSUE TITLE
Can't remove post from listed if note deleted in standard notes.

### ISSUE THREAD

**Issue by ceiphr** [standardnotes/forum#269]
Hi,
I was testing your syntax highlighting and wrote some CSS for it so that it functions better in dark mode. When I deleted the test note from Standard Notes it didn't remove the post on [my listed blog](https://blog.ceiphr.com). I don't see any way I can now remove that post. Please help. Thank you.

**Comment by mobitar** [comment]
Sorry about that, I've went ahead and deleted your test post. Currently a limitation of the system that you'll need to unpublish before deleting the note.

Sweet theme btw!

**Comment by ceiphr** [comment]
I will unpublished before deleting from now on.
Thank you for removing the post and for the complement!
