### ISSUE TITLE
Web App Won’t Load in Safari on iPhone

### ISSUE THREAD

**Issue by armstrong360** [standardnotes/forum#270]
The Standard Notes web app won’t load in Safari on my iPhone.  It will load using another browser, and it loads in Safari on Mac and iPad.  On the iPhone, the page (https://app.standardnotes.org) comes up blank in Safari. It’s an iPhone 8 running iOS 11.4.1.
Any ideas?
Thanks.

**Comment by mobitar** [comment]
Hmm just tested using iPhone X on iOS 11.4.1 and it works for me. But the general answer is that the web app is definitely not optimized for mobile, and you're going to have a hell of a time using it on a small screen.

Are you opposed to using the native iOS app from the App Store?

**Comment by mobitar** [comment]
Can you try clearing your Safari cache, and also try a private window?
