### ISSUE TITLE
Make it easier to manage tags in desktop apps

### ISSUE THREAD

**Issue by kslstn** [standardnotes/forum#271]
My issues with the current design are:

1. Tags are not visible where the are added. If you don't know yet that they're shown above a notes title in the notes list (or don't remember!), it's like the words you type into the _Add tags_ field just disappear.
2. I don't know how to remove tags from a note. 

I'm on Version 2.3.2.

**Comment by mobitar** [comment]
You remove tags by editing the the tags text.

Not perfect, but you can look to the Quick Tags extension for better tags management.

**Comment by kslstn** [comment]
The tags themselves are not clickable though:
<img width="622" alt="screen shot 2018-08-07 at 09 09 01" src="https://user-images.githubusercontent.com/5889799/43760167-97951f04-9a21-11e8-93df-67d98e8d53a0.png">

Perhaps this is a 2.3.2 bug? I want to update, but haven't managed to make a backup and sign out the other clients yet.

**Comment by mobitar** [comment]
Indeed there was a bug with 2.3.2 where removing tags from old notes didn't take effect. But only for old notes (pre-July 2018). Tags in Quick Tags should be click-to-remove.

You don't need to sign out of other clients when you update the app. Only when you update the security version for your account (very rare event).

**Comment by kslstn** [comment]
Got it. It wasn't clear to me the security update was separate from the software update. I did the latter and the tags are back. Thanks!
