### ISSUE TITLE
Zombie Note

### ISSUE THREAD

**Issue by weird-o** [standardnotes/forum#272]
I made the mistake of editing the same note on two different devices before it had a chance to sync. (I think one of the devices was offline at the time.) This created a conflict, so Standard Notes duplicated the note, one with the changes I'd made on my first device and the other with the changes I made on my second device.

So I looked at the differences between the two notes and reconciled them. Then I deleted the second, now-superfluous note.

Unfortunately, it hasn't stayed deleted. No matter how many times I delete it, it keeps popping back into my list of notes. Sometimes only one zombie copy reappears. But sometimes two, three, or four zombie copies reappear.

Can I do anything to keep these zombie notes dead or can this issue only be fixed by the devs?

If it matters, I'm using the Android app, the Windows app, and occasionally I open the web app.

**Comment by mobitar** [comment]
I'm hearing more and more of this issue. Must be a regression in the 2.3 release. How long after you delete the note before its zombie appears? Right away, or seemingly randomly the next day or so?

**Comment by zedgoat** [comment]
Had a similar issue between Linux Desktop 2.3.3 and Android Client 2.3.3, I had a few observations from this:
- Duplicates of the same note after editing from mobile.
- Zombie note was missing the edit button (tag icon) on Android.
- Would sometimes also generate empty notes (no title / content) as a result of edits from mobile.

Tried a few actions so far:
- Uninstall / re-install of android app.
- Purged all notes and re-imported backup.

But seem to be encountering it again. Additionally, after deleting history and importing backup I lost some tags, associated notes were there but untagged.

**Comment by weird-o** [comment]
In the beginning, the zombie note reappeared almost right after I deleted it. Now it takes a few hours or so.

**Comment by AdamVig** [comment]
Same issue here. For me, it seemed to correlate with turning on note version history, but persisted even after turning it off.

I have tried logging out of all apps but one, deleting the zombie note on the remaining one, then logging back in, but the zombie note still appears. I currently have four copies of the zombie note.

For what it's worth, the zombie notes always have the exact same content; an older version of my to do list note. I was able to edit the zombie note and see changes appear in the client on another platform, but then deleted that copy of it and new zombie notes are back to the same old content.

**Comment by mobitar** [comment]
Hmm..very strange. What if you were to try this:

1. Download a backup of your notes.
2. Open an incognito/private tab in your browser. Make sure you're not signed in. 
3. Import the backup file.

Does the zombie note appear there? And if you delete it there, does it go away for good? Or does the same issue persist?

If the issue persists there, then that can be good in getting this to replicate on my end. In that case, we can edit the backup file to only the troubled notes, and we could use that file for diagnosis. Let me know if anyone here can try this.

**Comment by zedgoat** [comment]
Unfortunately missed the opportunity to reproduce this, it seems to have cleared up after the following action yesterday:
- Log out everywhere.
- Log into the web app in incognito.
- Export an encrypted backup.
- Purge all notes and tags.
- Ensure sync has completed, log out.
- Log into the web app in a new incognito window.
- Import backup.

The final import looked OK apart from a handful of conflicted notes, aside from that all edits and updates are behaving as expected, e.g.: no phantom notes or duplicates.

**Comment by mobitar** [comment]
Gotcha. Sorry you had to go through all those steps to clear this up! These unreplicatable bugs will be the end of me.

**Comment by mobitar** [comment]
Was able to replicate and fix this. Fix incoming in 2.3.4 (Android today, iOS whenever Apple feel like).

**Comment by zedgoat** [comment]
@mobitar all good, glad you could still reproduce and fix!
