### ISSUE TITLE
Data Backups settings should not be in the menu bar

### ISSUE THREAD

**Issue by DarkArc** [standardnotes/forum#2722]
Currently there's a UI divergence between File Backups and Data Backups.

File Backups are managed in preferences. Meanwhile, Data Backups are handled in the "Backups" menu of the menu bar. These seem like almost the exact same thing from a "conceptual" UI/UX stance (at least IMO), so I really think they should be handled the same way.

It's worth noting, if you _hide_ the menu bar, it's even less clear what the UI means as it says "Backups are automatically created on desktop and can be managed via the "Backups" top-level menu." The only way to get the menu bar back is the `Alt + M` shortcut (perhaps this should be in the Appearance menu, like "Show Tags Panel", "Show Notes Panel", etc).

Additionally, having the menu bar hidden for a while and not paying too much attention to my home directory, I was a bit surprised to stumble upon a Standard Notes Backups directory; I _knew_ I'd looked in the Backups options recently, and at that time I'd thought "I should probably turn that on eventually", but never realized it was actually on from the current UI in preferences.

**Comment by effieeee** [comment]
All backups settings are now grouped together in **Preferences > Backups**!
