### ISSUE TITLE
Feature Request: Keyboard Shortcuts to switch between notes

### ISSUE THREAD

**Issue by aandotherchars** [standardnotes/forum#273]
Using SN as the primary code(text) editor, I often need to switch back-and-forth between two notes checking for member names etc. It'd be nice to have a keyboard shortcut tied to at least switching between the present and the previous note (plus others if possible); click-switching breaks the flow. 

(A quick search on the help page found no mention of shortcuts.)

**Comment by mobitar** [comment]
Keyboard shortcuts are a [popular request](https://github.com/standardnotes/forum/issues/39), and while we don't have them now, we do have future plans for them. Can't really say when though..

**Comment by aandotherchars** [comment]
Closed as Duplicate.
