### ISSUE TITLE
Security scanner reports reputation issue

### ISSUE THREAD

**Issue by enijeboer** [standardnotes/forum#274]
My Norton Security detected "'WS.Reputation.1" in installer for Windows installer-2.3.3.exe.
The exe downloded from the site https://standardnotes.org 
Fortunately I found elsewhere installer 2.3.2 which is clean.

**Comment by scottwernervt** [comment]
[WS.Reputation.1](https://www.symantec.com/en/uk/security-center/writeup/2010-051308-1854-99) is a false detection and does not mean the installer is infected:

> WS.Reputation.1 is a detection for files that have a low reputation score based on analyzing data from Symantec’s community of users and therefore are likely to be security risks. Detections of this type are based on Symantec’s reputation-based security technology. Because this detection is based on a reputation score, it does not represent a specific class of threat like adware or spyware, but instead applies to all threat categories.

Virus Total reports the installer as clean: https://www.virustotal.com/#/file/e30ea5bbb4ac8da3eeb619a38431b95bd8871cfde31f3905d17f844e05836474/detection

**Comment by zedgoat** [comment]
+1 on false positive, WS.Reputation.1 is a garbage classification - there's no real "reputation score" behind it, it just means Norton's hasn't seen enough instances of the application via Endpoint Security clients and flags it.
See: [](https://support.symantec.com/en_US/article.HOWTO80989.html)

> Insight reputation ratings
> Symantec Insight determines each file's level of risk or security rating. The rating is also known as the file's reputation.
> Insight determines a file's security rating by examining the following characteristics of a file and its context:
> - The source of the file
> - How new the file is
> - How common the file is in the community
> - Other security metrics, such as how the file might be associated with malware

IMO quarantine is the wrong response for this, it should be set to Warn. Any application that goes through frequent binary releases triggers it.
