### ISSUE TITLE
Images don't load without internet connection in super editor on the windows desktop app

### ISSUE THREAD

**Issue by girishzalke** [standardnotes/forum#2744]
When a screenshot is added to a super note, it gets uploaded to the service (I think). If you disable the internet connection, the images in the note don't load. 
If you bring back the internet connection, the images still don't load until you restart the app.
It will not be helpful if images are unavailable without an internet connection.

**Comment by effieeee** [comment]
Currently (v3.160.19), images inserted in-line on Super notes will also appear offline, though you must ensure that they've been loaded while the app is online at least once
