### ISSUE TITLE
Export data not working on Android 8.0.0

### ISSUE THREAD

**Issue by northern-arizona** [standardnotes/forum#275]
My wife has Standard Notes (basic, not extended) on her Android 8.0.0. 

We tried exporting data, using both the encrypted and decrypted options. Standard Notes successfully sent the emails, but the emails had no data and no attachments.

How can we export her note data?

**Comment by northern-arizona** [comment]
SOLVED: I just thought to try sending the email via a different mail app. BlueMail did not work; it resulted in the empty emails. Gmail was able to send the data as a json file.

I guess the blame goes to Bluemail.

**Comment by mobitar** [comment]
Yeah, only the default mail app I believe will work, or any app that respects the same configuration as the Gmail app. Ideally in future versions we'd save the backup file to disk, but that will take some work. Glad you got it sorted!

**Comment by davebrny** [comment]
can you not just broadcast to other apps that will save the file to disk and then let the user choose? it would be better than having to give gmail access to your storage

**Comment by davebrny** [comment]
@mobitar ah i see. no worries

**Comment by TheodoreChu** [comment]
I'm closing this because sharing notes is much easier in recent app versions (v3.5+). Please comment if you have further issues.
