### ISSUE TITLE
[Feature Request] Keep Standard Notes Running in Background in Laptop

### ISSUE THREAD

**Issue by PunnyBoi** [standardnotes/forum#277]
Is it possible to add an option of 'Keep Notes Running in Background when Closed'? While running, the program consumes around 150 MB of RAM. So, to save some memory, I usually close the program. When I open it again, it takes some time to show up. But if the application is running in the background and consuming somewhat less memory (it would be great if it consumes less memory when running in the background), then it won't take long enough to open up.

**Comment by mobitar** [comment]
Yeah, experimenting with this now on Windows. There's no "consume less memory" background option. The only solution is to hide the window programmatically on our part.

**Comment by TheodoreChu** [comment]
Closing this because the latest version of the desktop app (v3.5.14) seems to use much less memory when in background. When the app is locked, it consumes about 40MB.
