### ISSUE TITLE
Links opened in Standard Notes

### ISSUE THREAD

**Issue by foorb** [standardnotes/forum#279]
Hi,
when i klick on a Link in simple markdown editor (preview) the link is opened in standard notes. Not sure if others are affected.

![bildschirmfoto 2018-08-20 um 14 56 47](https://user-images.githubusercontent.com/14993807/44341801-4d59b680-a489-11e8-9362-ec697f3e931e.png)

![bildschirmfoto 2018-08-20 um 14 53 50](https://user-images.githubusercontent.com/14993807/44341766-2bf8ca80-a489-11e8-8b24-4e59fa3b759a.png)

greetings

**Comment by mobitar** [comment]
Hmm thought I fixed this. Thanks for the heads up. Will take a look when I get the chance.

**Comment by mobitar** [comment]
This has been fixed in Simple Markdown Editor 1.1.5. Click Extensions, and then "Update" next to the editor to get the change.

**Comment by foorb** [comment]
Works, thank you!
