### ISSUE TITLE
Shareable link for notes

### ISSUE THREAD

**Issue by sergeydgr8** [standardnotes/forum#28]
I frequently find myself wanting to share a note with a friend, and without any export to PDF or sharing capability it's rather difficult to do so with Standard Notes.

Could it be possible to have a feature to get a shareable link for a note, and maybe even for a certain tag?

**Comment by mobitar** [comment]
You can do this with the Share extension: https://standardnotes.org/extensions/share

**Comment by sergeydgr8** [comment]
Thanks! Is there a bulk share feature, such as share a certain tag/folder?

**Comment by mobitar** [comment]
No not currently.

**Comment by nimdajitam** [comment]
But this shares the selected note by publishing it unencrypted. Correct me if I am wrong.

**Comment by mobitar** [comment]
Right, it shares it unencrypted as it's for public sharing.

**Comment by nimdajitam** [comment]
How's with sharing/syncing notes between two users in encrypted way? Is it planned to be implemented (by using PKI approach, may be)?

**Comment by mobitar** [comment]
That's not currently in scope. Collaborative encryption and key sharing is definitely not something I want to get into right now :)

**Comment by naveensrinivasan** [comment]
@mobitar How do I share the note? I don't see the share extension. Thanks

**Comment by mobitar** [comment]
Please see here: https://standardnotes.org/help/17/how-do-i-share-a-private-note

**Comment by bong0** [comment]
> You can do this with the Share extension: https://standardnotes.org/extensions/share

This is not available anymore it seems, I'm just redirected to the front page :/

**Comment by mobitar** [comment]
That comment is outdated. We use Listed now: https://listed.to
