### ISSUE TITLE
Choose from a list of tags (not print) while assigning a tag to a note

### ISSUE THREAD

**Issue by grvsd** [standardnotes/forum#281]
I'd like to be able to choose tags from a list, not print them, while assigning tags to a note, in the desktop app. 
I see this feature in the mobile app. Would be logical to have it on desktop too.

**Comment by mobitar** [comment]
You can do this with the Quick Tags extension: https://standardnotes.org/extensions/quick-tags

(Although you'd have to type at least one letter to see autocomplete results)

**Comment by effieeee** [comment]
Currently possible on the right click context menu :)
