### ISSUE TITLE
Auto-export (and import) of all notes to a LOCAL file (once every day)

### ISSUE THREAD

**Issue by pstein** [standardnotes/forum#2836]
I am currently evaluating Standard Notes App for Android 

After installation I searched for a way to AUTOMATICALLY backup (e.g. once every day) all my current notes (and restore them later).
Backup+Restore should NOT be done to cloud.

Instead I want to let Standard Note auto-export them to a local folder on my Android Smartphone.

I f necessary I should be able to import it again in furture.

How can I achieve this?

If this is currently not possible: Could this feature be added in the next release?

**Comment by myreli** [comment]
Hey @pstein, thanks for trying Standard Notes! 🙂

I'm afraid this is not currently possible for notes, but it's definitely under the teams' radar. This is how it's done to backup files, so notes will follow up. 

Currently you can backup to cloud providers or email, daily and weekly (on both options the backup is completely encrypted).
