### ISSUE TITLE
Filter notes by tags

### ISSUE THREAD

**Issue by fra-gadio** [standardnotes/forum#2837]
Hi,
How do I filter notes by tags?

For example I have city tags:  #new_york, #chicago, #atlanta    and then I have these tags:  #restaurants,  #local_markets, #properties etc.....
I want to display all notes that have both the tags #chicago and #properties.

How do I do that?

**Comment by effieeee** [comment]
Hi @fra-gadio, I apologize that no one was able to answer your question at the time, though I will still leave my answer here in case it's needed.

You'll need to set up a **Custom (JSON)** Smart View for this. When you go to **Preferences > General** to create a new Smart View, you can choose **Custom (JSON)** to set up a view which is based on tags. The custom builder has an example of how to set this up, so you will just need to edit it accordingly by adding more copies of the conditions to include all the tags that you need to filter by:

![image](https://github.com/standardnotes/forum/assets/54989748/239e1e3b-1e54-454e-96f6-6ab481bc31c7)
