### ISSUE TITLE
Sessions Refresh Prompt - Concern?

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#2838]
I've been prompted to "Please enter your account email and password. Your credentials are needed for foo@bar.com to refresh your session with the server." twice in two days on my desktop client. Should I be concerned?

**Comment by jmason888** [comment]
I had the same thought, especially since  I have *never* seen that prompt before, nor was there a blog post announcing a change in the sync or auth protocol that would require reentering credentials (like the shift from V2 to V3 encryption way back when).

**Comment by tiddesk** [comment]
> I had the same thought, especially since I have _never_ seen that prompt before, nor was there a blog post announcing a change in the sync or auth protocol that would require reentering credentials (like the shift from V2 to V3 encryption way back when).

So the same thing is happening to you?

And yes, if this is expected because of backend work it would be nice to know.

**Comment by djwyman** [comment]
I am having this same thing happen on the Linux electron app, inside the browser and on the iOS app.  It is annoying to have to log in, go to my 2fa app and get that code, and then enter it when I am trying to get in quick to jot something down or read a note I wrote.  Especially because this was not how it used to work before.  Then on top of it, I then have to get an email that lets me know I logged into a device that should have already been logged into.

**Comment by jmason888** [comment]
> So the same thing is happening to you?

Yep. So far, twice in the Android app (which is annoying because I need to switch apps to get the 2FA code) and once in the Web app.

**Comment by myreli** [comment]
Hi! You don't need to worry about the safety of the account, but the inconvenience is being fixed. This behavior isn't intended like this. 

It seems a recent change to invalidate older sessions is causing this. As soon as a patch is done I update here. 

Quoting Mo,

> We invalidated a class of sessions last week to decrease their overall access age (from 60 days to 12 hours—after 12 hours now, they automatically renew with the server based on the refresh token which expires in 90 days). It should have been seamless but seems some clients prompted for reauthentication. It should be only once. 

> Ok, I'm seeing an issue where on launch with an expired token the first 3 requests can all fail together and cause 3 refresh requests, only the first of which succeeds of course. Investigating..

Thanks for reporting @tiddesk

**Comment by tiddesk** [comment]
> Hi! You don't need to worry about the safety of the account, but the inconvenience is being fixed. This behavior isn't intended like this.
> 
> It seems a recent change to invalidate older sessions is causing this. As soon as a patch is done I update here.
> 
> Quoting Mo,
> 
> > We invalidated a class of sessions last week to decrease their overall access age (from 60 days to 12 hours—after 12 hours now, they automatically renew with the server based on the refresh token which expires in 90 days). It should have been seamless but seems some clients prompted for reauthentication. It should be only once.
> 
> > Ok, I'm seeing an issue where on launch with an expired token the first 3 requests can all fail together and cause 3 refresh requests, only the first of which succeeds of course. Investigating..
> 
> Thanks for reporting @tiddesk

Thank you!

**Comment by sethmad** [comment]
I'm also experiencing the reauthentication issue in the Windows desktop client 3.150.0, but along with it I'm experiencing unexpected syncing behavior. I get the red Sync Unreachable notice, but the Account Menu shows a green check with last synced as the time of the last edit. Are the reauthentication and sync issues related?

**Comment by elias-pap** [comment]
I second https://github.com/standardnotes/forum/issues/2838#issuecomment-1445270670. I'm having the same issue on Android, being forced to reenter credentials after a day. Thanks for working on this.

**Comment by dekstop** [comment]
I'm also experiencing this on desktop on macOS (app version 3.131.0 on Big Sur 11.7.4), I'm using the desktop app every few days or so and seem to need to log in almost every time due to an expired session. Otoh the mobile app on Android (version 3.151.9) works fine with the same account.

It's especially an issue as the desktop app login form doesn't pre-fill username and password -- so I need to enter them manually every time. Would be nice if they could be saved in the Keychain.

Thanks for all your efforts!

**Comment by effieeee** [comment]
@dekstop This is issue should have been addressed in the latest versions, so you'll want to update your app on Mac to v3.152.0 by downloading the installer from our website and directly replacing your older version 🙏

**Comment by dekstop** [comment]
@effieeee thanks for the pointer, I've updated the macOS app earlier this week and have been running it fine without any login prompts for a few days now! The ticket can probably be closed as resolved. Excellent work!

(As an aside -- evidently I was completely blind to the update notification in the menu bar... Don't think I've seen this approach before.)
