### ISSUE TITLE
Exporting decrypted ZIP file via decrypt.html creates additional files versus desktop export

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/forum#284]
Using decrypt.html ([source](https://standardnotes.org/offline)), the decrypted ZIP file that is produced has empty notes for every tag in the database, plus an "Extension" file that seems to relate to the Listed extension.  Exporting a decrypted ZIP via the desktop app does not produce these.

**Comment by mobitar** [comment]
Hmm interesting. The decrypt.html is most likely running older code. Will need to investigate this more. Thanks for the heads up!

**Comment by mobitar** [comment]
The decrypt script has been updated. It will now create folders for every content type. So notes will be in their own folder, and extensions will also be in their own folder. This behavior is now probably ahead of the desktop app behavior, so in the future, the desktop app will likely also be updated to behave in this way.

**Comment by virtuallyvlad** [comment]
Thanks for updating.  Tag files were empty before but looks like they have note IDs in them now.  Liking the folder organization too!  Hope app gets the same functionality.

**Comment by mobitar** [comment]
The latest desktop/web update should now have matching functionality.
