### ISSUE TITLE
impossible to open side bar

### ISSUE THREAD

**Issue by andy-goryachev** [standardnotes/forum#2871]
Once collapsed, it is impossible to open the side bar on Windows desktop app version 3.150.0.
Double-clicking on a margin does not open the side bar.

Please see https://github.com/standardnotes/forum/issues/1724

**Comment by andy-goryachev** [comment]
![2023-02-25 10_25_21-Standard Notes](https://user-images.githubusercontent.com/5430849/221373496-3740a106-d83f-4081-91d5-b2327b352307.png)

**Comment by effieeee** [comment]
Please open the **Quick Settings** menu and toggle the **Show Tags Panel** option to reveal the leftmost side bar!

![image](https://github.com/standardnotes/forum/assets/54989748/c4d41dbc-1953-4047-9540-bcddaac6cf34)

**Comment by andy-goryachev** [comment]
thank you so much!

**Comment by andy-goryachev** [comment]
The issue is not fixed (3.160.19 on Windows 10).

Enabling the Tags Panel should also set the tags panel width to a reasonable value.  If the panel was initially collapsed, it gets enabled with a zero width, and again - impossible to resize with the mouse.

Created a new ticket https://github.com/standardnotes/forum/issues/3151.
