### ISSUE TITLE
[Feature Request] Sketch editor

### ISSUE THREAD

**Issue by holzi-x** [standardnotes/forum#289]
users would be able to insert simple sketches into a note, similar to what is available in the iOS editor.

**Comment by mobitar** [comment]
By sketches do you mean like a canvas based editor which you can draw to with a smart pen or something of the likes? If so, I'm not sure of the feasibility of this, but it is an interesting idea. Probably something reserved for very far down the road.

**Comment by hillbilly3456avk** [comment]
Yes exactly, you got it. looking forward to see the ‚standart notes style‘ of such a funtionality.

**Comment by alejandrogutierrez12** [comment]
this would be awesome!!!! I would REALLY love this feature because I'll be an insane experience on the tablet. I think this would be the first privacy-oriented note taking app with this feature.

**Comment by chrootlogin** [comment]
Please add this feature. It would be awesome to use the Apple Pencil to create Notes. Because often i rather want to use my pencil than my keyboard.

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/820
