### ISSUE TITLE
Change date of entry

### ISSUE THREAD

**Issue by lazyCrab** [standardnotes/forum#29]
Hey guys,
Is there any way to change the date a note is listed under? Have it be something other than the moment of creation?

**Comment by mobitar** [comment]
No way to do this I'm afraid other than exporting your data, and modifying the JSON entries manually in a text editor, then importing them back in.

**Comment by TheodoreChu** [comment]
Date changes are available as described [here](https://docs.standardnotes.org/listed/how-do-i-specify-a-custom-date-for-a-post-or-set-the-canonical-url):
```
---
created_at: 2017-11-20 17:08:05
canonical: https://mysite.com/blog/1/post-im-importing
---
Your story...
```
This is an old issue, so I am closing it. Please open a new issue if you have any more problems. :wave:
