### ISSUE TITLE
desktop-file-install is missing. Skipping /tmp/.mount_standakB3fRy/AppRun

### ISSUE THREAD

**Issue by edvinasurbasius** [standardnotes/forum#290]
I am using Kubuntu 18.04 LTS. I just downloaded AppImage for Linux. I use terminal to run it with ./ but in a terminal I desktop-file-install is missing. Skipping /tmp/.mount_standakB3fRy/AppRun error. It loads the software, don't get me wrong. The issue is: if I pin it, so it has an icon in my task bar, but if I close the Standard Notes and try to press it on the icon, I get the same error. So I can only run through terminal. When I used Ubuntu, it worked. You pinned it to the task bar and it integrated without any flaws. It's not a big of a deal, it's just maybe a bug or something? Thanks!

**Comment by mobitar** [comment]
Were you prompted initially to create desktop shortcuts? Can you see if a .desktop file exists in /usr/share/applications or /local/share/applications?

**Comment by edvinasurbasius** [comment]
Hello. I was prompted to create a shortcut, because by the default it's issued in Ubuntu or Kubuntu, but after I checked /usr/share/applications it wasn't there.

**Comment by mobitar** [comment]
Any chance you can search your system for .desktop files? This is the script responsible for creating the .desktop file: https://github.com/electron-userland/electron-builder/blob/f966f1a22bd7577e493595ac261e4b38ec0ce233/packages/app-builder-lib/templates/linux/AppRun.sh Looks like `$APPDIR` would be the directory of the desktop file.

**Comment by mobitar** [comment]
Sorry, not entirely sure what the issue could be. It's a long shot, but maybe @probonopd can help?

**Comment by probonopd** [comment]
Is the `desktop-file-install` command available on the Kubuntu 18.04 LTS target system?

**Comment by mobitar** [comment]
Ah, good call. Didn't even realize that was a command. I think @edvinasurbasius noted this issue wasn't actually affecting launch, only some minor GUI issues.

**Comment by edvinasurbasius** [comment]
Hey! E: Unable to locate package desktop-file-install, but I did some digging and found desktop-file-utils package instead for KDE. I reinstalled my Kubuntu OS today, then installed the package I mentioned and it looks awesome now. Desktop shortcut creates itself. I cannot verify 100% that especially this package solved the problem, but it's highly likely.

**Comment by probonopd** [comment]
Yes, the the `desktop-file-install` command is in the `desktop-file-utils` package and the desktop integration script needs it to be there on the target system (it normally is).

**Comment by mobitar** [comment]
@probonopd good to know!

**Comment by infosisio** [comment]
@mobitar Just faced this situation and thankfully found this issue. Would be good to look into a way that works in more distros.

**Comment by probonopd** [comment]
Which distribution does not have `desktop-file-install` out of the box @infosisio? We could also bundle it inside the AppImage if needed. But anyhow, the desktop integration bash script is considered deprecated. We recommend to use something like the optional `appimaged` daemon if you like system integration.

**Comment by infosisio** [comment]
@probonopd kubuntu
