### ISSUE TITLE
[Feature Request] Calendar

### ISSUE THREAD

**Issue by PunnyBoi** [standardnotes/forum#292]
Is it possible to add a small calendar in the app? I mean a calendar in which we can mark special or important events.

**Comment by tej** [comment]
Bump, Highly underrated request.
Need something similar to a Calendar extension or Agenda/Time-based to-do list

it would be nice if I could import external calendar feeds like Google Calendar or Outlook Calendar, but I'm assuming that would cause security issues or something like that so idk.
