### ISSUE TITLE
Paste Image from Clipboard does not link Image to Note

### ISSUE THREAD

**Issue by SuppenGeist** [standardnotes/forum#2943]
**Describe the bug**
When pasting an image from my clipboard into a Supernote, the image is uploaded and displayed correctly, but not linked to the note.

**To Reproduce**
1. Copy image to clipboard
2. Paste Image in Supernote (Strg+V)

**Expected behavior**
Image is linked to note.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 3.150.0

**Comment by Peltiloota** [comment]
I tested this scenario in Ubuntu with version 3.150.45, and it works.
