### ISSUE TITLE
[Help Wanted] How to run and build the server on my local development environment.

### ISSUE THREAD

**Issue by drtobbyas** [standardnotes/forum#2948]
**Describe the issue**
Can someone provide me with a guide on how to run and build the server on my local development environment?

**Expected behavior**
Run and build the server and app on my local development environment

**Smartphone (please complete the following information):**
Ubuntu 22.04

**Comment by Peltiloota** [comment]
I trust that you've read this: https://standardnotes.com/help/self-hosting/docker.
