### ISSUE TITLE
[Help Wanted] Where can I find the installation URLs for the editor extensions? 

### ISSUE THREAD

**Issue by velardevines** [standardnotes/forum#2949]
**Describe the issue**
Want to install the Rich Text editor. Where can I find the installation URL? I have searched Help but cannot find a list containing the URLs for any of the extensions.

**To Reproduce**
Nothing to reproduce

**Expected behavior**
Expect to be able to easily find a list of URLs to use to install editor extensions.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: ubuntu 
 - Browser Chromium, Firefox, Brave
 - Version Whatever is the latest installation version

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: latest Android
 - Browser Brave, Firefox
 - Version: latest for each

**Additional context**
Apologies for being so dense that I cannot find the URLs.  Thank you for helping.

**Comment by jackyzy823** [comment]
Rich text editor is a premium feature. You need a subscription.

**Comment by jackyzy823** [comment]
Some community extensions (provided by the official)  could be found [here](https://github.com/standardnotes/plugins).

Others could be found [here](https://github.com/jonhadfield/awesome-standard-notes#editors)

**Comment by velardevines** [comment]
Thank you @jackyzy823 for the links.  Yes, I do have a premium subscription.

**Comment by jackyzy823** [comment]
You could just switch to Rich Text Editor by "Change Note Type" button in each notes' settings.

There's no need for you to manually install it by URL.
