### ISSUE TITLE
Images not showing on imported notes from Evernote

### ISSUE THREAD

**Issue by fra-gadio** [standardnotes/forum#2950]
Hi guys,

I have a bunch of Evernote notes with images that I've imported.
The text shows fine but the images aren't there.
Has anybody been able to import notes from Evernote with the images showing correctly?

thanks in advance

**Comment by effieeee** [comment]
Hi, unfortunately, images cannot be automatically transferred over from Evernote at the moment, so these will need to be reuploaded manually into your notes.
