### ISSUE TITLE
Changing default note type

### ISSUE THREAD

**Issue by jphalip** [standardnotes/forum#2951]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

Yes

**Is your feature request related to a problem? Please describe.**

All new notes appear default to plain text, which would not be my preference. In my case I'd like all new notes to be Markdown.

**Describe the solution you'd like**

Add a setting where the user can select their preferred default type.

**Describe alternatives you've considered**

No alternatives that I can think of. Currently one has to change the type manually, which is an extra step for each note.

**Comment by KMnO4s** [comment]
You can already change the default note type! Read this: [How do I make an editor my default editor?](https://standardnotes.com/help/69/how-do-i-make-an-editor-my-default-editor)

**Comment by dhohmeyer** [comment]
> You can already change the default note type! Read this: [How do I make an editor my default editor?](https://standardnotes.com/help/69/how-do-i-make-an-editor-my-default-editor)

I have read the "how to", but the instructions don't appear to work for version `3.159.0`. I don't see any "New Notes Default" section. The change note type doesn't have an item to change the default note type. 

![image](https://github.com/standardnotes/forum/assets/25014394/293a78c3-a431-4ede-97ce-61cdcacc8b69)

**Comment by effieeee** [comment]
Hi @dhohmeyer, looks like you've accessed the wrong dropdown menu, please have a look at my screenshot below! 🙏

![image](https://github.com/standardnotes/forum/assets/54989748/9cc8d066-2ef5-415d-9b47-6e048b135bd9)

**Comment by dhohmeyer** [comment]
Thank you @effieeee ... however, now I face an even more urgent issue. After updating my preferences for the "New Note Defaults" _and_ the "Title Format", I am unable to view the preferences (screen comes up completely blank) and cannot create a new note. 

I've tried removing the application and all of the associated files, installing a fresh copy, and signing in to my account... but it appears the bad preferences have been synchronized to my account. 

Any suggestions? I'll reach out to support too!

**Comment by dhohmeyer** [comment]
> Thank you @effieeee ... however, now I face an even more urgent issue. After updating my preferences for the "New Note Defaults" _and_ the "Title Format", I am unable to view the preferences (screen comes up completely blank) and cannot create a new note.
> 
> I've tried removing the application and all of the associated files, installing a fresh copy, and signing in to my account... but it appears the bad preferences have been synchronized to my account.
> 
> Any suggestions? I'll reach out to support too!

Just a follow up @effieeee , I was able to get my Mac and Android phone working OK. Not sure what the issue is. I've contacted support.
