### ISSUE TITLE
Odd layout issue after deleting new note

### ISSUE THREAD

**Issue by jphalip** [standardnotes/forum#2957]
**Describe the bug**

If you create a new note, then delete it right away, the note list panel expands to the right and fills up the screen.

**Desktop (please complete the following information):**
 - OS: Max OS Ventura 13.2.1 (22D68)
 - Version 3.150.11 (3.150.11)

**To Reproduce**

Create a new note:

<img width="1572" alt="2023-03-03_21-00-35" src="https://user-images.githubusercontent.com/68544/222877010-d7735f4d-b45c-4ef7-9bbe-3d06c0d70d4f.png">

Type in some text:

<img width="1573" alt="2023-03-03_21-01-14" src="https://user-images.githubusercontent.com/68544/222877017-cd7921c3-0819-4fb4-85ac-15db4f4fb3f1.png">

Delete the note you just created:

<img width="1225" alt="2023-03-03_21-01-53" src="https://user-images.githubusercontent.com/68544/222877027-175659e1-976e-4b89-bb18-0384d7004a0e.png">

The note list panel expands out and fills up the screen:

<img width="1569" alt="2023-03-03_21-02-20" src="https://user-images.githubusercontent.com/68544/222877044-242b67a2-4bd9-460f-949b-e09a655472e4.png">

**Comment by effieeee** [comment]
Fixed in v3.159.7 🙏
