### ISSUE TITLE
Export of individual note not working in Android

### ISSUE THREAD

**Issue by ahkole** [standardnotes/forum#2959]
**Describe the bug**
If I try to export an individual note I get an error message that I have to give storage permissions but I never get a popup to allow storage permissions and it's also not listed in the possible permissions in the app info. See the attached screenshots. 

**To Reproduce**
1. Go to a note
2. Click on the hamburger menu
3. Click on export

**Expected behavior**
I expect the export to function and if it needs storage permissions for the app to ask for them.

**Screenshots**

![Screenshot_20230305-223020](https://user-images.githubusercontent.com/35299166/222987115-2e851dee-2217-4ef9-b802-f16d3a1ddd90.png)
![Screenshot_20230305-222731](https://user-images.githubusercontent.com/35299166/222987130-3a18ce11-4aa8-49b4-8a87-2f855ae46739.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: GrapheneOS (Android 13)
 - Browser: Brave
 - Version: Version 3.150.7

com.standardnotes
versionCode 3002535

targetSdk 33
minSdk 28

Installed: 20 Feb 2023; 14:48
Updated: 4 Mar 2023; 15:41

**Comment by Matias314** [comment]
I'm having this same issue when trying to download a backup of all my data.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A71
 - OS: OneUI 5.0 (Android 13)
 - Browser: Firefox Nightly
 - Version: 3.150.7

**Comment by Rochey** [comment]
I have the same issue when trying to download a file from the files section of the app. I get the error:
Storage permissions are required in order to download files. Please acce...

If I go to the permissions of the app on android there is no "Storage Permission" to enable to allow this functionality.

Did you want me to raise a new bug?
Or is it a similar issue regarding permissions?

**Comment by jaden** [comment]
Same issue here trying to preview a file.

Smartphone (please complete the following information):

Device: Google Pixel 5a
OS: Android 13
Browser: N/A
Version: v3.150.54 (3002583)

**Comment by Matias314** [comment]
Finally fixed for me in 3.159.0
