### ISSUE TITLE
Duplicate Tags and Notes

### ISSUE THREAD

**Issue by armstrong360** [standardnotes/forum#296]
All of my tags and notes are doubled both in the app and on the web.  See scree shot. And they aren’t syncing.  I’ve tried closing the app and widows on all my devices then relaunching the app. That didn’t work.  Any ideas how to fix this?
<img width="403" alt="screen shot 2018-09-12 at 9 53 12 am" src="https://user-images.githubusercontent.com/12838072/45433877-bd1b2580-b672-11e8-87b3-69439a0cbc4b.png">

**Comment by mobitar** [comment]
Hey @armstrong360, sorry about that. What version of the app were you using when this happened? And were you using the mobile app too? We had a brief issue in a recent version (~2.3.3) where this would happen and the notes would not delete, but this should be fixed. Make sure you're running the latest versions on every platform if you're not already.

As for cleaning this up, you can use the Batch Manager's detect duplicates option. You should use the web app for this, as it recently got an update to the Batch Manager that the desktop app did not yet get which makes handling duplicates a little smarter.

**Comment by armstrong360** [comment]
Thanks Mo. I'm running 2.3.4 on the desktop, which is apparently the latest.  2.3.6 on the iPhone and 2.3.5 on the iPad.  Should I update the iPad? Any special instructions for doing so.  Do I need to close down the other open apps? Also, where do I find the Batch Manager?

**Comment by mobitar** [comment]
The Batch Manager can be found on the web app via Extensions. Click Open on Batch Manager, and you should see an option to detect duplicates. 

Yeah, I would upgrade the iPad app via the App Store. No special upgrade instructions, just the usual. Here's some more info on duplication btw: https://standardnotes.org/help/33/how-do-i-clear-duplicates

**Comment by whdmike** [comment]
I think one of the problems is the way notes are functioning - usually when you have a program like that, once you create a tag, when next time you start to type it, it appears automatically and you just confirm it, i couldn't find the way to do it with free version of Notes. I think the purpose of tags is that you can use same tag many times that you can find the right content, but if you need to type each time all over again, can cause confusion. I hope developer can implement this in a otherwise very good and nice products.

**Comment by mobitar** [comment]
@whdmike not sure what you mean. If you create a note within the selected tag, that tag will automatically be added to the note.

**Comment by whdmike** [comment]
Thank you. Happy to hear that. What about if I need multiple tags?

**Comment by bryvin** [comment]
@whdmike You can definitely add multiple tags to any note you'd like right underneath where you change the Title of the note at the top of the app. There is a separate line there with the current tags associated with that note, and you can just click there and type in new ones with the hash in front "#newtag".

If you're an Extended user you can also get the [Quick Tags](https://standardnotes.org/extensions/quick-tags) Extension which helps greatly with this.

Whenever you goto a tag using the sidebar on the far left, if a Note has multiple tags it will automatically appear in each of the tags associated with it.

**Comment by whdmike** [comment]
This quick tag extension is doing what I had in mind.
