### ISSUE TITLE
View jump-scrolls on entering a newline

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#2961]
**Describe the bug**
Entering a newline causes the page to jump-scroll to place the cursor at the top of the page. This behavior seems to be extinguished temporarily after it occurs, but comes back after scrolling again (sometimes). It consistently occurs after re-opening the note.

**To Reproduce**
1. Create a note with enough content to require scrolling a couple screens down
2. Scroll down so that at least the first few lines go out of view.
3. Enter a newline.

**Expected behavior**
View should not scroll when entering newline.

**Screenshots**
[Video of behavior](https://github.com/quartertone/bugfiles/blob/main/98fa94be-d207-4516-bae3-f64fff91fa9f.mp4)

**Smartphone (please complete the following information):**
 - Android app v3.150.14

**Additional context**
This bug was present in an earlier version but went away (I think) for a couple versions.

**Comment by vladimir-sol** [comment]
Am also affected by this (on macOS Ventura, StandardNotes Version 3.153.12 (3.153.12)). It had been a problem around the time of this issue https://github.com/standardnotes/desktop/issues/564, then disappeared. It is now back, please fix.

**Comment by effieeee** [comment]
This is unfortunately a known issue with textarea on Chromium, so we'll have to wait for the fix on their end. Please see the bug report we've filed with them below:
https://bugs.chromium.org/p/chromium/issues/detail?id=1433217
