### ISSUE TITLE
v2 Self-hosted Docker server does not provide access to Tag folders or Encrypted File Storage with Offline Subscription

### ISSUE THREAD

**Issue by pete3n** [standardnotes/forum#2962]
**Describe the issue**

Whenever I attempt to use Tag folders or Encrypted File Storage, I am prompted to Enable Advanced Features by upgrading my current plan. It is my understanding that there is only one plan available for self-hosting, and that the offline subscription plan _is_ the professional plan, so it should enable all features. 

I purchased a self-hosted subscription and followed instructions found here: [Can I subscribe to a paid plan with a self-hosted server?][offline-subscription], here [Self-hosting with Docker][self-host], and here [Subscriptions on your self-hosted server][self-host subscription] to configure my server and activate my subscription. All other features and functions seem to work correctly. My account shows an active subscription ending in 2243 with an offline subscription key. I can access formatting features such as Markdown and Rich Text, however Tag folders and Encrypted File Storage still appear to be blocked behind a paywall.

**To Reproduce**
1. Self host Standard notes server
2. Follow provided instructions to purchase and activate a self-hosted offline subscription
3. Attempt to use Tag folders or Encrypted File Storage features
5. This issue is the same for both Android app and web interfaces

**Expected behavior**
I expected to have access to Tag folders and Encrypted File Storage, or at least receive errors related to misconfiguration. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 Kernel 5.19.0-32
 - Browser Firefox 110.0.1 (64-bit)
 - Version v3.150.3

**Smartphone (please complete the following information):**
 - Device: Galaxy S20
 - OS: Android 13 
 - Browser Firefox 110.1.0
 - Version v3.150.7 (3002535)

---
[offline-subscription]: https://standardnotes.com/help/48/can-i-use-extensions-with-a-self-hosted-server
[self-host]: https://standardnotes.com/help/self-hosting/docker
[self-host subscription]: https://standardnotes.com/help/self-hosting/subscriptions

**Comment by pete3n** [comment]
This issue is no longer appearing for me. I do not know what changed.

**Comment by MFYDev** [comment]
Hi I met the same problem, I purchased the offline subscription and the local app still tells me that I should enable advanced features, I have already activated it
