### ISSUE TITLE
Standard notes desktop (windows) not opening

### ISSUE THREAD

**Issue by PunnyBoi** [standardnotes/forum#297]
The standard notes is not showing up on windows, although it is running in the background (I can see it in the task manager). I tried reinstalling it but it didn't help. I am using the latest version of the software, i.e. 2.3.4.

**Comment by mobitar** [comment]
Hmm never heard this issue before. Can you try restarting your computer? Not sure what else it can be.

**Comment by PunnyBoi** [comment]
The '90s solution still works. Turning it off and on again solves the issue. Sorry to bother you.

**Comment by mobitar** [comment]
Haha ok great :)
