### ISSUE TITLE
swipe right = accidental note exit -

### ISSUE THREAD

**Issue by kyhXX** [standardnotes/forum#2970]
— ! Very annoying issue — using th app on iPhone newest update -  when u open a note   if u accidentally swipe towards th right even if simply trying to copy and paste a section of th text on display it completely shifts th screen and page fully exiting u out of th note u were just typing and working on etc -  this is very annoying please fix - as well as repositioning th bottom right hand “ close keyboard “ button that blocks th entire bottoms right section for cursor placement of any kind etc- - this is also “ very annoying “-  3.17.23 ^^ / /

**Comment by effieeee** [comment]
Hi there, I apologize for the very late response. You may turn off the swipe gestures under **Preferences > General**, as shown below!

![Screenshot_20230520_200119_Standard Notes](https://github.com/standardnotes/forum/assets/54989748/d434c172-d518-441d-be13-badf5186aafc)
