### ISSUE TITLE
[Help Wanted] Super note with image, published to Listed, image does not show in Listed

### ISSUE THREAD

**Issue by ploguus** [standardnotes/forum#2980]
**Describe the issue**
Created a Super note. Added an image, which displays fine. Published the note to Listed, but in blog view, the image doesn't display.

**Expected behavior**
I expected the image to appear in the blog post.

**Desktop (please complete the following information):**
 - OS: Windows
 - FIrefox

**Comment by effieeee** [comment]
Images on Super are only displayed inline via a direct reference to the encrypted file on your cloud storage with Standard Notes. Unfortunately, this means that the in-line display only works within the app, so you'll only see the reference link in text when you try to publish it to Listed
