### ISSUE TITLE
Ability to rename files from mobile

### ISSUE THREAD

**Issue by shompoe** [standardnotes/forum#2983]
At present it seems that on mobile the only way to rename a file is to first attach it to a document and then go in and rename it in the links modal for the document.

Can we not have the ability to rename files without this extra step like we can on desktop?

**Comment by affvalente** [comment]
You can edit by pressing the name on the top. It's not very intuitive or easy, but you can do it

**Comment by shompoe** [comment]
Thanks.   Now that you pointed it out it seems obvious but I never would have realized.
