### ISSUE TITLE
Checklist Glitching on Android

### ISSUE THREAD

**Issue by gabriel-berardi** [standardnotes/forum#2984]
**Describe the bug**
When editing a checklist on the Android app, a lot of glitching occurs. Different checklist items get merged into one and when trying to edit this, the app scrolls down automatically. This is a bit hard to describe, so I added a video of it here: https://user-images.githubusercontent.com/54224251/229295901-3280a17b-34d8-4f96-acfa-424dd6eb4979.mp4

**Screenshots**
Please see the video here: https://user-images.githubusercontent.com/54224251/229295901-3280a17b-34d8-4f96-acfa-424dd6eb4979.mp4.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A71
 - OS: Android 13

https://user-images.githubusercontent.com/54224251/229295901-3280a17b-34d8-4f96-acfa-424dd6eb4979.mp4

**Comment by effieeee** [comment]
@gabriel-berardi I've referenced this issue on the tracker, though please let me know if you still experience this until now!

**Comment by gabriel-berardi** [comment]
Hi @effieeee, I just updated the app to the newest version and there seems to be no glitching anymore!

**Comment by effieeee** [comment]
Awesome! 😊 Closing this now!
