### ISSUE TITLE
import from Evernote

### ISSUE THREAD

**Issue by metropical** [standardnotes/forum#299]
I have exported as per directions on EN, .enex.
When I try to import the notes or a single note into SN, I get this error.
"Unable to open files.  Be sure it is a proper JSON file and try again."
Any assist?
Coming from EN v 6.8 on Mavs to current SN on Sierra.

**Comment by mobitar** [comment]
Be sure you're importing the export file the converter generates, not the .enex file. If you have a .enex file, first convert it to Standard Notes format here: dashboard.standardnotes.org/tools.

If you've already done that, can you tell me the file size of both the enex file and the resulting output file from the converter?

**Comment by monaxle** [comment]
Does the extended add on facilitate full import of notes with attachments?

**Comment by mobitar** [comment]
@monaxle no, file attachments would not be imported over. They're required to be run separately through the encryption and upload function, which the converter does not do.

**Comment by monaxle** [comment]
Thanks. That's a shame. Makes this an impracticable option for me.

**Comment by i3games** [comment]
How to import the converted file? I don't see any option in the App (Mac, v. 2.3.13).

**Comment by metropical** [comment]
https://dashboard.standardnotes.org/tools

**Comment by mgresko** [comment]
@mobitar is there any way to automate the process of attaching a file or must it be done through the interface?  The only thing stopping me from using standard notes is getting all of my notes from Evernote which most contain attachments.  Thanks!

**Comment by JaspalSuri** [comment]
As far as I know, attachments must be manually uploaded to each note. Hopefully this is a process that the team can streamline in the future!
