### ISSUE TITLE
Notes Show Blank with Markdown Editors on iOS w/Lockdown Mode

### ISSUE THREAD

**Issue by bobmatyas** [standardnotes/forum#2990]
**Describe the bug**

Notes show blank when editor mode is set to Markdown options. Switching to plain text makes note visible

This only started recently (perhaps with iOS 16.4 update?)

**To Reproduce**

1. Enable "Lockdown Mode"
2. Open note created with Markdown editor
3. Observe that note contents will not be visible
4. Switch to Plain Text and see you can view contents
6. Switch back to Markdown
7. Turn off "Lockdown Mode"
8. Open note again and contents will be visible

**Expected behavior**

Markdown view should work on mobile device

I thought it might have a similar fix to this, but I'm not given the option to turn off Lockdown Mode for Standard Notes:

https://github.com/standardnotes/forum/issues/2218

**Screenshots**

Markdown:

![signal-2023-04-10-201432_002](https://user-images.githubusercontent.com/45246438/231024096-b6aa3fd3-5bed-495c-b378-321659156830.jpeg)

Plain Text:

![signal-2023-04-10-201432_003](https://user-images.githubusercontent.com/45246438/231024099-56dea163-5b01-49f1-93ca-e3319c22c690.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd Gen)
 - OS: 16.4
 - Latest App Version

**Additional context**

**Comment by effieeee** [comment]
Hi @bobmatyas, I've also noted similar reports of how these features are restricted when lockdown mode is enabled. For comparison though, I wanted to ask if you're able to use the editor properly on the web app in your phone, if you add app.standardnotes.com and api.standardnotes.com as exceptions for Safari?

**Comment by effieeee** [comment]
Will continue tracking Lockdown Mode issues here
https://github.com/standardnotes/forum/issues/3051
