### ISSUE TITLE
How Do I Highlight Text on SuperNotes like the other editors? 

### ISSUE THREAD

**Issue by SpaceRaccoonFluff** [standardnotes/forum#2993]
I can't seem to figure out how to highlight text using the Super Notes Editor. Highlighting notes is an extremely important function once you have a lot of text to skim over.

**Comment by effieeee** [comment]
I'm afraid this isn't possible on Super notes yet, but it's already part of the [feature requests thread](https://github.com/standardnotes/forum/discussions/3008)!
