### ISSUE TITLE
StandardNotes 3.150.54 App not working on M1 Max arm 

### ISSUE THREAD

**Issue by sfnemis** [standardnotes/forum#2998]
Dear Standard Team,
 
 am really struggling with using StandardNotes. It has become quite a challenge for me. The latest update which is released on Github Desktop 3.150.54 macos_arm it’s not working ! One thing more, why u couldn’t make an update on the software!? Why always i need to go and download again and again.

I couldn’t use my StandardNotes Application right now on my Mac M1 Max.

![Google Chrome-Releases · standardnotesapp · GitHub-2023-04-15 at 14 03 @2x](https://user-images.githubusercontent.com/78266266/232210761-e31a692f-18c7-414a-a8db-5e3465323313.png)

**Comment by effieeee** [comment]
Hi @sfnemis, I'm closing this for now since I'm currently assisting you with this over email!
