### ISSUE TITLE
Drag and drop don't work

### ISSUE THREAD

**Issue by bepolymathe** [standardnotes/forum#3]
Hi,

Thanks for you great work.
I have a problème with file attacher extension. When i click to add a file in dropbox, it work. When i drag and drop the same file, it doesn't. 

![capture](https://user-images.githubusercontent.com/29939805/28024777-ebbaf7b8-6591-11e7-9b7f-7a64f12c7cff.PNG)

It's not a big problem for me but it's for signal it. 
Regards

**Comment by mobitar** [comment]
Hmm strange. Is this with Firefox? Can you try Chrome/Safari and see if the issue still occurs there?

**Comment by bepolymathe** [comment]
Yes. 
I test it the first time with firefox 49 (i think... i can check now) on windows 7 pro.
A new test with firefox 54.0 (on an other computer) on ubuntu... same problem.
It works with chromium Version 59.0.3071.109 on ubuntu.

**Comment by mobitar** [comment]
Ok, I'll have to investigate this when I get the chance. Thanks for the heads up.
