### ISSUE TITLE
Windows client doesn't remember window dimensions?

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#30]
The following issue may exist only because Windows 7 is so stupid when it comes to handling a second terminal attached to a laptop. If so, let us all throw rocks at Windows 7. Yay!

But if not, every time I start the Standard Notes client for Windows, the window is wide and short. So I *always* have to grab the bottom of the window and make it taller.

IF this is yet another deficiency in the virtually infinite list of Windows' deficiencies, never mind. If instead there's a way for the Standard Notes' Window client to remember previous width and height, then perhaps add that to the Windows client(?)

Cheers, thanks, & hope this helps,
RBV
SFO

**Comment by mobitar** [comment]
It definitely should remember window size, as that was built in. I can confirm it works for Mac. I have been considering making the default window size larger. Does it start off too small?

**Comment by WritingSolutions2020** [comment]
As I said, this may be a Windows 7 problem, or *my* Windows 7 problem, or my laptop's problem.

Per the following screenshot, IF I open the *Standard Note* desktop client into the monitor attached to my laptop, the client is always a bit too short:

![2017-07-24 09_58_06-greenshot](https://user-images.githubusercontent.com/3333327/28535127-0f0130c2-7058-11e7-8719-6cfaad189b41.png)

IF I grab the bottom of the window, make it taller, work on a note, then close the client, THEN when I reopen the client it once again needs to be made taller. (Or wider. The default width isn't bad but IF I make the client window wider, that width setting will be lost between sessions, too...)

Also NOTE that IF I didn't have a large monitor attached, THEN I wouldn't want the window too big for my laptop's built-in display.

SO I wouldn't worry too much about this -- it's just a small quirk. If a solution doesn't leap out and offer to implement itself, don't throw away valuable cycles on it...

Cheers, thanks, & hope this helps,
RBV
SFO

**Comment by mobitar** [comment]
Cool, thanks for the details. Will have to investigate this when I get the chance.

**Comment by mobitar** [comment]
I've tested this on Windows 10 and Mac and it works perfectly. I don't have Windows 7 lying around to test it though. Might be a Windows 7 issue. If anyone else on Windows 7 experiences this issue, please let me know.

**Comment by WritingSolutions2020** [comment]
Yeah, that's fine. I've always wondered if it was something specific to my system. Ah yes, Windows -- it inevitably degrades in a "death by a million small cuts" ways over time. And no two life cycles of degradation are the same...

**Comment by Tomandreson** [comment]
I am using the Windows 7 and I am facing this problem for a long time. I have heard that it is fine with the windows 10 and I get to know about this from https://microsoftsupport.co/microsoft-support-canada If any solution is there for Windows 7,let me know.

**Comment by effieeee** [comment]
Old issue, no longer occurring with latest versions
