### ISSUE TITLE
-

### ISSUE THREAD

**Issue by marintoo** [standardnotes/forum#300]

**Comment by mobitar** [comment]
Interesting idea. Would have to investigate what's involved. A simple button is likely a complex arrangement of a lot of code and dependencies. Would like be an external project to Standard Notes that would make this possible. If anyone has any resources on this and would like to keep this discussion going please feel free to share.

**Comment by marintoo** [comment]
Is it possible to integrate the "web" server into the PC app so one can start a server from the mac?
One would then simply just use localhost:3030 (or whatever the port is) as their sync server.
That's what I was suggesting with the post, not necessarily a difficult external project :D .

**Comment by mobitar** [comment]
Well you can easily run the server project independently on localhost. It's located here: https://github.com/standardfile/ruby-server Instructions are provided there as well, which shouldn't be more than a few steps for just local deployment.

**Comment by marintoo** [comment]
True, but I've tried over and over and it's way too complicated.
I'd really like something like 1Password does, which is very easy and doesn't require to run a whole server with MySQL etc...
Simple Wi-Fi sync from mac to phone and phone to mac would be amazing.
