### ISSUE TITLE
Is there any extension that lets me note down mathematical symbols?

### ISSUE THREAD

**Issue by makarandh** [standardnotes/forum#301]
Windows 10
Standard Notes 2.3.5
I am using the Plus Editor Extension. 

When I copy notes from OneNote with mathematical symbols such as matrices, determinants, vectors, to Standard Notes, it copies them as an image and the images themselves are in temp folder that gets over written.

I tested most of the other editor extension and none of them could copy the mathematical symbols properly. Is there any way to note down mathematical symbols in Standard Notes?

**Comment by mobitar** [comment]
Yes, the Fancy Markdown Editor support LaTex: https://standardnotes.org/extensions/fancy-markdown-editor

**Comment by TheodoreChu** [comment]
Update: the Fancy Markdown Editor is now called Markdown Math: https://standardnotes.org/extensions/markdown-math
