### ISSUE TITLE
Self Hosted

### ISSUE THREAD

**Issue by ithinkmatt** [standardnotes/forum#302]
I just started using Standard Notes cloud. I really like it, but have thought about self hosting on our dedicated server.

I have some questions based on the documentation available.

Would I need Standard Notes Server? Or Standard Notes web app?

Can the Android app be reconfigured to load the information from my self hosted version?

Or does it only work with the Standard Notes hosted cloud version?

Thanks,

Matt

**Comment by mobitar** [comment]
For self hosting, there are two components: the web app, and the syncing server. The web app is optional in terms of self-hosting, unless you really want to self host your own web app. The syncing server is what most people usually self-host. After that, you can configure the desktop, mobile, and web app to point to this server.

You can do this in when signing in by clicking "Advanced options". This will allow you to specify your server url.

**Comment by leonklingele** [comment]
@mobitar what's the reason for requiring users to log in before being able to access the `Advanced` settings?

**Comment by mobitar** [comment]
Advanced settings are part of signing in. You access them before signing in, not after.
