### ISSUE TITLE
Password not working after IOS Update

### ISSUE THREAD

**Issue by Backyardpool** [standardnotes/forum#3022]
Hi all,

Last night I updated my MacBook to the latest apple software update (IOS 16.4.1).
Right after the update, my password stopped working. "Invalid authentication, please try again."
I am certain that I am using the correct password, as I log in every single day.
Anyone know what might be the problem?

**Comment by effieeee** [comment]
Currently assisting over emails

**Comment by tg5hKVHPyX** [comment]
Have you been able to log in to your account again? I've had this problem for over a year but on android and web. I try again with each app update and it still shows me the same error.
