### ISSUE TITLE
I can't figure out how to use the offline decrypt script.

### ISSUE THREAD

**Issue by DrownedStarfish** [standardnotes/forum#3029]
Hi!

Please give me detailed instructions to use the decrypt file.  Please tell me in what format to save it and anything else I need to know.

Thanks.

**Comment by Kefaku** [comment]
The decrypt file is an html file (`decrypt.html`). You should be able to open html files with most browsers (can confirm it works with Edge, Firefox, Google Chrome). If the file doesn't open in a browser by default, but in a text editor instead, simply right-click on it and select "Open with..." or a similar option, depending on your OS. Once opened, it should look something like this:

![image](https://user-images.githubusercontent.com/114934849/234824215-a184d667-861a-4e80-b8ac-282e2ad4ccaa.png)

Then you can simply select the encrypted backup file, which you want to decrypt in step **(1)**. After that enter your account password in step **(2)**. Then you will be able to download the decrypted files in step **(3)**.

**Comment by DrownedStarfish** [comment]
Thanks, Kefaku!

I never did find any other way to do it, but after I downloaded a new copy of the script and did your right-click thing, it seemed to work just fine.  (I only tested it to the stage where it asks for my password; I'm not _that_ obsessive.  After all, SN may last longer than I will!)
