### ISSUE TITLE
Connection to ec2 amazonaws.com

### ISSUE THREAD

**Issue by frps** [standardnotes/forum#303]
What's the purpose of silent connection to amazonaws server when the program starts on win32 platform?
Automatic updates disabled, account is not created yet and I've not signed in for stats collections.
Could you please comment? Thanks.

**Comment by mobitar** [comment]
Autoupdate has two components: one that pulls the update metadata from our website (standardnotes.org, which is hosted on AWS), and the other which pulls the actual update data from Github. The metadata aspect is enabled by default, and currently does not have the option of being disabled (as it instructs users if their version is out of date). This request in particular is made here: https://github.com/standardnotes/desktop/blob/master/app/javascripts/main/updateManager.js#L121

**Comment by frps** [comment]
Thank you for your reply.
Since the privacy is your main selling point, I think you should not add ANY network transfers without explicit permission to do so from the user. 
The silent network activity have a bad reputation these days. So I guess a good practice could be
1) Disable option - a must.
2) Clean and clear statement what kind of data is transmitted and logged on the server side for this specific outbound session - ie client IP, software version, OS version, installation guid etc.
It would be a perfect match to the product concept.

**Comment by mobitar** [comment]
Good point, perhaps an initial window that asks the user whether they want to automatically check for updates would make sense. Will keep this in mind!
