### ISSUE TITLE
Stacked layout when using 'themed menu bar'

### ISSUE THREAD

**Issue by Kefaku** [standardnotes/forum#3031]
**Stacked layout when using 'themed menu bar'**
When the 'Use Themed Menu Bar' option is enabled, the menu bar and title are stacked ontop of each other in the settings, therefore the upper part of the title ('Your preferences for Standard Notes') is hidden under the menu bar and not readable.

**To Reproduce**
1. Go to 'View'
2. Enable 'Use Themed Menu Bar'
3. Click on 'Open Preferences'
4. Select any Section.

**Expected behavior**
The title should be readable and below the menu bar.

**Screenshots**
While using themed menu bar 'Your preferences for Standard Notes' is covered by the menu bar:
![image](https://user-images.githubusercontent.com/114934849/234821311-488f25d6-8f85-4054-afdb-c12369328ff9.jpg)

Properly working without themed menu bar:
![image](https://user-images.githubusercontent.com/114934849/234821408-a4c5dd10-b838-41d8-9a54-a02d9c2933b6.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Standard Notes: 3.153.0

**Comment by amanharwara** [comment]
This has already been fixed. Please use the [latest version](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.153.12)

**Comment by Kefaku** [comment]
thx for fixing it this fast
