### ISSUE TITLE
extensions.standardnotes.org domain is not resolvable

### ISSUE THREAD

**Issue by maxgashkov** [standardnotes/forum#3034]
**Describe the bug**
`extensions.standardnotes.org` is `NXDOMAIN` which prevents any cloudlink functionality (backups) from being set up.

**To Reproduce**
```
; <<>> DiG 9.10.6 <<>> extensions.standardnotes.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 9177
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;extensions.standardnotes.org.	IN	A
```

**Expected behavior**
Domain name resolves properly.

**Comment by effieeee** [comment]
Hi @maxgashkov, we've unfortunately had to disable the cloud backup function recently:

> Hello,

> This message is to inform you that due to relatively low adoption and increasingly complex APIs necessary to integrate with multiple third party cloud providers, we will no longer be offering our daily backup service to third party cloud providers such as Dropbox, Google Drive, and OneDrive.

> There are still many great ways to get backups of your account data, including daily email backups, automatic desktop backups, and backups you download directly via the desktop, web, or mobile application.

> For more information on how to create and import account backups, visit our [help center](https://standardnotes.com/help/14/how-do-i-create-and-import-backups-of-my-standard-notes-data).

**Comment by jpbaril** [comment]
I had to recently reinstall my self-hosted server and then my reaction was: "Where is the cloud backup feature? What did I mess-up in my reinstall?"
Daily email backups is annoying and automatic desktop backups, well, you have to use the desktop app...
The server should be able to backup the notes of a user.
Could you at least keep the WebDav backup mechanism ?
