### ISSUE TITLE
Changing default note type bug

### ISSUE THREAD

**Issue by ajgraves** [standardnotes/forum#3036]
**Describe the bug**
Changing the default note type will actually change the note type, however, the options still show "Plain Text" as the default. Thus, you are unable then to set your default back to Plain Text.

**To Reproduce**
1. Expand display options menu above notes list
2. Change default note type to something other than Plain Text (I used Super in my testing)
3. Close the options menu, and re-open it
4. See the default note type is set to Plain Text again
5. Create a new note, and confirm the editor is actually what you selected before (I typed a forward slash, which triggers the pop-up menu as expected in Super)

**Expected behavior**
Changing the default note type should show you what is actually set instead of always showing Plain Text

**Screenshots**
Will provide if necessary, however the steps above have been reproducible by several people in the Discord server

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1 (22E261)
 - Browser n/a (using desktop app)
 - Version 3.153.11

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 16.4.1 (20E252)
 - Browser n/a (using app)
 - Version 3.153.0

**Comment by amanharwara** [comment]
Fixed in latest release https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.153.12
