### ISSUE TITLE
Deal with accent when performing a search

### ISSUE THREAD

**Issue by frego** [standardnotes/forum#304]
Hi,

I have my notes both in English and French. When doing a search, the letter "e" is different than "é" for instance, which is usually never the case. Is it possible to have a accent agnostic search?

Regards,

**Comment by mobitar** [comment]
Are you saying you'd like e and é to be treated the same in search? I'm not sure how we would do that, from a technical, JavaScript perspective. They are very independent characters. I'll have to investigate this a little more.

**Comment by frego** [comment]
Exactly.

I found some hints over there: 

https://stackoverflow.com/questions/5700636/using-javascript-to-perform-text-matches-with-without-accented-characters

and 

https://alistapart.com/article/accent-folding-for-auto-complete

**Comment by mobitar** [comment]
Ok, looks feasible at first glance. Will keep this in mind for a future release.

**Comment by TheodoreChu** [comment]
Closing because this is the current behavior on the latest desktop apps: https://standardnotes.org/download
