### ISSUE TITLE
Preferences panel select on mobile is broken

### ISSUE THREAD

**Issue by ajgraves** [standardnotes/forum#3040]
**Describe the bug**
The selection list for navigating to different sections of the preferences on mobile is broken, it seems to only work once each time you enter the preferences screen.

**To Reproduce**
1. Go in to preferences on mobile
2. Select the drop down to change to any other preference panel from the default Account panel.
3. Note that the list of available panels pops "up" from the bottom, as expected. Select any of the preferences panels available.
4. Once you've gone to another panel, select the drop down again to attempt to change to another panel/section of the preferences screen.
5. Note that the selection list pops "down", thereby hiding it off the bottom of the screen, making it impossible to select any other preference area.
6. Also note that the drop down arrow does nothing when the selection list is displayed. Typically you should be able to use the arrow/carat icon to open/close the selection list without making an actual selection.

**Expected behavior**
You should have a consistent selection list behavior, and be able to open/close the selection list using the arrow/carat icon without needing to make a selection in the list.

**Screenshots**
Screenshot showing list behaving properly:
![IMG_4296](https://user-images.githubusercontent.com/11450420/235696093-4f735df8-ff87-40b1-a7d0-b0fe37f8d79b.jpeg)

Screenshot showing list displaying "down" and off the bottom of the screen:
![IMG_4297](https://user-images.githubusercontent.com/11450420/235696292-46aaa894-0450-4f19-9dc2-99f535b2abb8.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.4.1 (a)
 - Browser N/A (using iOS mobile app)
 - Version 3.153.12 (612)

**Comment by effieeee** [comment]
Hi @ajgraves, this should be [fixed](https://github.com/standardnotes/app/commit/c9d8a686ff44b8259e4ccb414ddf3d8a9b9e267a) in the next release!
