### ISSUE TITLE
Desktop Update 3.157.0 Makes Standard Notes Unusable/0 Notes Shown 

### ISSUE THREAD

**Issue by zzzpppzzz** [standardnotes/forum#3048]
Just updated to Desktop Version 3.157.0 from 3.156 or 3.156.4 and now Standard Notes is unusable. It shows 0 notes despite there being thousands and the note screen is blank and just says "Loading..." but nothing every happens. None of the notes that should be there ever load, even if I wait a while and/or relaunch several times. 

Everything was fine/working normally prior to the update, so it must be something with 3.157.0 that triggered this.

Also, it appears all my notes are still there as I can access them all normally on my other devices, like my iPhone. 

This is on:
Laptop
Windows 10 w/all latest updates
Occurred after relaunch from update of 3.156.x to 3.157.0

**Comment by effieeee** [comment]
Hi @zzzpppzzz, is this still the case even after updating to the [latest version](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.159.0) for desktop? Please also check if resetting your desktop app helps with this:

1. Click on the menu button on the top left of the app.
2. Click on the **View** dropdown menu.
3. Click on the **Toggle Developer Tools** option.
4. Expand the window until it reveals a button for tab named **Application**.
5. Click on **Storage**.
6. Click on **Clear site data**.
7. Relaunch the app, and sign in again.

**Comment by zzzpppzzz** [comment]
> Hi @zzzpppzzz, is this still the case even after updating to the [latest version](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.159.0) for desktop? Please also check if resetting your desktop app helps with this:
> 
> 1. Click on the menu button on the top left of the app.
> 2. Click on the **View** dropdown menu.
> 3. Click on the **Toggle Developer Tools** option.
> 4. Expand the window until it reveals a button for tab named **Application**.
> 5. Click on **Storage**.
> 6. Click on **Clear site data**.
> 7. Relaunch the app, and sign in again.

Yep. Just updated and confirmed the same issue.

When I launched Standard Notes today, it had updated to the problem version. I then updated to the latest version (3.159 I believe) and relaunched and am still having the exact same issue.

I haven't yet tried resetting the desktop app, but I have tried downgrading to the prior version and it fixes the problem. (3.154.1 - works/has no problems once I downgrade to it). But once I update to 3.157 or 3.159 = same issue.

**Comment by effieeee** [comment]
I see, though please do try out the reset instructions 🙏 So far this has worked with someone who was experiencing similar issues in the help inbox!

**Comment by jasteele12** [comment]
I have a similar problem after upgrading to 3.159, but I imported my notes from a backup on my local drive. But, once the notes were recovered, I could not change any of the Global preferences like Date modified, nor turn off Show note preview and Show date. But after restarting, it came back with no notes again.

I tried again with 3.158 but had the same problems. I've had several weird update problems on Windows 10 (fully updated) in the past. Mostly involving lost global settings such as dark mode, monospaced font, etc. I'm getting afraid to update.

I went back to 3.150.28 and everything is working again. Unfortunately, I no longer have a menu button on the top left of the app. Seems it got lost in one of those glitched updates. Is there a way to get it back?

**Comment by effieeee** [comment]
Hi @jasteele12, perhaps you're using the non-themed menu bar on Windows? In that case you can try unhiding it using **Alt + M** on your keyboard. You should also be able to access the **View** dropdown there and open the developer tools 🙏

**Comment by Schiocco** [comment]
I have the same problem. How to solve it? All my notes are lost!

**Comment by Schiocco** [comment]
After importing a backup, if I restart Standard Notes, all notes are disppaeared again, including settings.
Also all notes are in SAVING.... status and never got saved.

**Comment by Schiocco** [comment]
I confirm 3.154.0 fixed the issue, all newer version had it

**Comment by jasteele12** [comment]
> Hi @jasteele12, perhaps you're using the non-themed menu bar on Windows? In that case you can try unhiding it using **Alt + M** on your keyboard. You should also be able to access the **View** dropdown there and open the developer tools 🙏

Well, being a developer I just pressed Ctrl-Shift-I - but the lost notes are still a problem. I'm sticking with 3.150.28 since I'm obviously not the only one having problems with the newer releases...

**Comment by Schiocco** [comment]
Hi I confirm I solved the issue also on latest version by resetting and
clearing the site data as explained above. Thank you!





[image: SCHIOCCO] <https://schiocco.com/>
