### ISSUE TITLE
Filesafe

### ISSUE THREAD

**Issue by ely-see** [standardnotes/forum#305]
Congratulations and thanks for the new Filesafe extension! That's really a great work! :-)

I have 2 questions:

- Do you have an offline script allowing to decrypt the files when Standard Notes disappears similar to the Standard Notes decrypting script?

- Do you plan file name encryption? At the moment, the cloud provider is able to see the file name and to make conclusions to the content of the file.

Thanks and continue the good work!

Ely-see

**Comment by mobitar** [comment]
@ely-see thanks, glad you're enjoying it!

1. FileSafe uses the same encryption as Standard Notes, so it will be the same script. Also, the FileSafe client extension is open source, so you can just drag and drop an encrypted file on it and it will decrypt it.

2. Maybe in the future, but for, it's best for the user to name their files as necessary for the desired level of privacy. Encrypting file names will make it difficult to find the files if one wanted to browse their cloud storage for manual verification.

**Comment by kevinlai80** [comment]
Very useful stuff.
about the 2 : if somebody find one encrypted file and the decrypted same file,
is he capable to guess the key and decrypt all the corresponding encrypted files ?

**Comment by mobitar** [comment]
No, seeing the plaintext and ciphertext of an encryption algorithm's input and output does not allow you to guess the key.

**Comment by trevormeier** [comment]
I didn't realize FileSafe did not encrypt file names! Obfuscating file names is a pretty important privacy feature—could you consider adding this in the future?

Perhaps there could be an extension or script of some kind for browsing / verifying the files.

**Comment by mobitar** [comment]
Yeah, we could add this option in the future. We didn't add it by default as a sort of "longevity" measure—if you stop using SN or FileSafe, we still want you to be able to find your files inside your cloud folder. If everything's encrypted, you'd be lost. But we can definitely make this an option for people who want this.

**Comment by mobitar** [comment]
All metadata related to encryption/decryption is stored in the .json file itself. Technically, the current offline SN decryption script would be able to decrypt individual files, but it just wouldn't download it in the correct format. We do want to get an offline decryption script for files soon. You can also drag and drop an encrypted file to your FileSafe area and it will decrypt it.

The relay server is open here: https://github.com/standardnotes/filesafe-relay. Servers never see file contents. They see the filename as they are explicitly given that as part of the custom metadata.

**Comment by FiloSottile** [comment]
I looked at some FileSafe files, and noticed their `auth_params` key is empty, so I initially thought they weren't self-contained, until I realized `003` encrypted strings carry the `auth_params` base64 encoded at the end.

1. this is not documented at https://standardfile.org/encryption and I feel like it should be
2. FileSafe files then probably shouldn't have an `"auth_params": null` key at all

Finally, this means that the user email is exposed in plaintext to the cloud storage, which might be unexpected, and is not apparent from just looking at the file.

**Comment by mobitar** [comment]
Indeed, SF documentation needs updating. Have made a note of this. Auth params need to be self-contained in a decrypted state, as you won't be able to decrypt files in an isolated environment without them. (i.e, if you can't access your SN account but need to decrypt the files).

**Comment by scottbourne** [comment]
+1 on encrypting filenames.  Not encrypting the filenames will force me to rename files in order to obscure the contents - which will not end well for me 6 months down the road - I won't remember the new, made up name anyway.  This is working against me and is kind of a FileSafe killer for me.  I have to have a tool to decrypt the contents, won't it also decrypt the filename.

**Comment by effieeee** [comment]
Must close unfortunately, as FileSafe has been deprecated
