### ISSUE TITLE
After editing a note on iOS, app is blank until closed and restarted

### ISSUE THREAD

**Issue by karldw** [standardnotes/forum#3054]
**Describe the bug**

After I open a note and edit it, when I go back to the list of notes, the Standard Notes app is totally blank.

After I close and restart the app, I can see my notes again. Switching apps is not sufficient; I need to actually close Standard Notes. Edits made before the screen goes blank are saved successfully. 

I run into a similar issue when I search my notes. After typing in the search bar, I can see the filtered search results, but as soon as I select a note, the whole app is blank.

**To Reproduce**
1. Open any note
2. Make an edit
3. Try to to back to list of notes
4. See error: app screen is totally blank

**Expected behavior**
Expected screen not to be blank, but instead show the list of notes.

**Smartphone:**
 - Device: iPhone SE
 - OS: iOS 16.4
 - Standard Notes Version: 3.159.2
 - Issue occurs both with and without lockdown mode turned on

**Comment by effieeee** [comment]
Hi @karldw, there was a past issue which led to blank white screens on the app, so in case it might help with this as well, can I ask you to try the workaround described in the link below?

https://github.com/standardnotes/forum/issues/2311#issuecomment-1360851482

**Comment by karldw** [comment]
That works for me, thank you! And sorry for the duplicate issue.
