### ISSUE TITLE
Super editor overrides MacOS Cmd-H shortcut

### ISSUE THREAD

**Issue by nevadaperry** [standardnotes/forum#3057]
**Describe the bug**
In the Super editor, the MacOS system shortcut Cmd-H (Hide window) does not work. Instead, it opens the SN find-and-replace dialog.

**To Reproduce**
1. Open a Super note in the MacOS SN app
2. Press Cmd-H
3. The system hide-window behavior does not occur.
4. SN opens a find-and-replace dialog

**Expected behavior**
The window should hide and the find-and-replace dialog should not open.

The find-and-replace shortcut should likely be Option-Cmd-F. This would match the conventional MacOS shortcuts used in TextEdit and VSCode.

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.5 Monterey
 - Browser: SN native MacOS app
 - Version: SN 3.159.2

**Comment by maciekberry** [comment]
Let me chime in. This is the same kind of problem that the one mentioned here:

https://github.com/standardnotes/forum/issues/2365

Guys - I like your product. But overwriting the absolutely standard shortcuts on any platform (not only MacOS) is million times forbidden.

Instead of appreciating the application, you make your users frustrated. And worse: you do not even react to our (mine and this one) requests here.

**Comment by effieeee** [comment]
Hi @nevadaperry, unfortunately Option-Cmd-F is already taken up by Focus mode on the app, though we'll try to consider updating this. 🙏

@maciekberry I understand your frustration, and I've responded separately on your original issue 🙏

**Comment by Thibaut** [comment]
Hi there - I'm a longstanding user of Standard Notes and wanted to note that this issue is a deal-breaker for me to be able to use the rich editors. I Cmd+H to switch between apps; Standard Notes stealing the shortcut completely breaks my flow. System shortcuts should not be overridden.

**Comment by amanharwara** [comment]
The Super note shortcut for Replace will be changed to `Opt+Cmd+F` on macOS in the next build (v3.187.2)

**Comment by Thibaut** [comment]
Thank you!

**Comment by maciekberry** [comment]
Yes  - thank you - it works and it's a good first step. Now, please #2365  needs the fix as well :(
