### ISSUE TITLE
Sync unreachable

### ISSUE THREAD

**Issue by cezarnik** [standardnotes/forum#3060]
**Describe the bug**
Several month ago, there are periods when note can't be synced from my desktop to storage.

**To Reproduce**
1. Go to some note
2. See red status on the top 'Sync unreachable'.

**Expected behavior**
Note is synced and updated version becomes visible on another device.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Version: v3.153.14

**Additional context**
Is it possible to see the sync error message?

**Comment by effieeee** [comment]
Hi @cezarnik, may I ask if this still occurs even after updating your app to [v3.159.0](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.159.0)?

**Comment by cezarnik** [comment]
Yes, it still does in v3.159.0, at least in mobile version.

**Comment by effieeee** [comment]
I see, if it's only happening on the mobile app for now, please [export a backup](https://standardnotes.com/help/14/how-do-i-create-and-import-backups-of-my-standard-notes-data) of your notes from there first, then try signing out and signing back into your account on both mobile and desktop as an initial step! 🙏

**Comment by cezarnik** [comment]
I exported a backup. But after signing out from desktop, I can no longer sign in - after entering the password, I see "Unknown error" message and that's it.
![Screenshot from 2023-05-22 22-44-49](https://github.com/standardnotes/forum/assets/20155967/613f9543-d59e-4397-b3a3-ed26d5efbd11)

**Comment by cezarnik** [comment]
It happens both in 3.159.17 and 3.160.8

**Comment by effieeee** [comment]
I'm sorry to hear that, though are you still able to sign into your account on other app platforms like your mobile device, or the web app on a browser? (app.standardnotes.com)

Have you also tried the steps below to reset the desktop app?

1. Click on the menu button on the top left of the app (if using the themed menu).
2. Click on the **View** dropdown menu.
3. Click on the **Toggle Developer Tools** option.
4. Expand the window until it reveals a button for tab named **Application**.
5. Click on **Storage**.
6. Click on **Clear site data**.
7. Relaunch the app, and try to sign in again with U2F.

**Comment by cezarnik** [comment]
I can sign in on my mobile (on sign in it says that it can't write to local DB and asks to reload the app, but that's fine), but can't do that nor via browser (Yandex Browser) nor via desktop app on any ubuntu laptop so far. The error is the same - Unknown error

**Comment by cezarnik** [comment]
I got it - the reason is my wifi. I thought about that after i looked at Network in Developer Tools and saw login-params didn't work. After connecting via phone hotspot, everything went smoothly. I think the reason is related to blocking on whoever's side.
