### ISSUE TITLE
Super note - hyperlinks not working

### ISSUE THREAD

**Issue by Romasz** [standardnotes/forum#3061]
**Describe the bug**
If I recall corretly a month ago hyperlinks in Supernote were clickable - now they are not.

**To Reproduce**
1. Edit Super note - paste hyperlink
2. Try to click it to open it

**Expected behavior**
Should open hyperlink in default browser.

**Desktop:**
 - OS: Windows 11
 - Browser Firefox

**Smartphone :**
 - Device: iPhone 14 
 - OS: iOS 16.4.1

**Comment by scode** [comment]
For what it's worth, as far as I can tell this is fixed. It does take two clicks (first clicks opens the pop-up menu with the clickable link), but there is no longer any need to copy and paste.
