### ISSUE TITLE
Small bug in Advanced Markdown Editor extension

### ISSUE THREAD

**Issue by paintedsky** [standardnotes/forum#307]
Hi there,

First off- thanks for your hard work on Standard Notes, it's a great application and I really appreciate having such a full-featured option that is open source and privacy-centric.

Now, the bug: I noticed when testing out Advanced Markdown Editor, that putting a numbered list directly after a bulleted list (with one line break in between) breaks the formatting of the numbered list in Preview and Split views.

Adding an additional line break (so two line breaks in between the two lists) fixes the problem.

See the attached screenshots for an example of what I mean. First screenshot is with one line break, second is with two.

This is a small bug so I understand if you'd rather prioritize more important features, but thought I'd mention it so you can fix it when you get a chance.

Thanks!

<img width="685" alt="lists_with_one_line_break" src="https://user-images.githubusercontent.com/10351660/45706858-3498fb00-bb32-11e8-9eb2-e2311453cf7a.png">

<img width="667" alt="lists_with_two_line_breaks" src="https://user-images.githubusercontent.com/10351660/45706887-47133480-bb32-11e8-9a78-469a16ba0e6a.png">

**Comment by mobitar** [comment]
Hey @paintedsky, thanks for your support, and glad to hear you're enjoying SN! The Advanced Markdown Editor is based on the open source SimpleMDE editor (https://github.com/sparksuite/simplemde-markdown-editor), and it definitely has its quirks, like what you see here. Some of the editors we develop ourselves (like the Simple Markdown Editor and Task Editor), but for this one, our best bet of getting this resolved is opening up an issue with the developers directly and seeing what they say. If they provide a fix, we can then pull this into our version of the editor.

**Comment by paintedsky** [comment]
Thanks for your speedy reply- it seems that [SimpleMDE editor is no longer being maintained](https://github.com/sparksuite/simplemde-markdown-editor/issues/685), so the possibility of having it fixed on their end seems unlikely.

Might be better to rework the extension based on a better editor? Obviously that's more work, but probably the best option in the long run. It looks like there's a fork of SimpleMDE called [Inscryb](https://github.com/Inscryb/inscryb-markdown-editor) that promises to be a drop-in replacement and might be worth looking at.

**Comment by mobitar** [comment]
Ah interesting, didn't realize it was no longer maintained. Inscryb looks like it maintains it, but only stuff related to the wrapper, and not really deep code stuff. Yeah, will have to find another open source editor we can fork.
