### ISSUE TITLE
Can’t revoke the session iOS 16.4.1

### ISSUE THREAD

**Issue by zakdon** [standardnotes/forum#3074]
I can’t revoke other sessions from my iPhone. Biometrics are successful and then the screen freezes. I can’t do anything on the screen. I can’t change protected access time, can’t put the passcode. I can’t even cancel the page. It just freezes. On Safari browser, there’s no problem. 
![IMG_8038](https://github.com/standardnotes/forum/assets/35498250/5341ad2b-121a-42d1-a9f4-976f0875e4b6)

**Comment by effieeee** [comment]
Hi @zakdon, does tapping on the **Submit** button also give no response on iOS?

**Comment by zakdon** [comment]
The issue is resolved for me. I deleted the app and reinstalled it which resolved the issue.   
  
Thanks for the contacts
  
  
  
  
  
  
  

  
  
>
