### ISSUE TITLE
Backup files appear in a directory named "[object Promise]"

### ISSUE THREAD

**Issue by Jamesits** [standardnotes/forum#3077]
**Describe the bug**
Local backup is created under a directory named `/Users/username/Documents/[object Promise]`

**To Reproduce**
I'm not sure if it is reproducable as I only had this problem on one of my computers.
Just randomly logged into 2 accounts and enabled local backup.

**Expected behavior**
There should be a meaningful directory name for the backups.

**Screenshots**
<img width="465" alt="image" src="https://github.com/standardnotes/forum/assets/1297257/efddd2e0-16ab-4327-a354-0354f0da8033">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.4
- Standard Notes 3.159.0 installed with brew cask

**Additional context**
N/A

**Comment by amanharwara** [comment]
Should be fixed in [v3.160.19](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.160.19).

Once you upgrade, you can either manually change it or sign out then sign back in.
