### ISSUE TITLE
FileSafe can't upload to WebDAV

### ISSUE THREAD

**Issue by semioticrobotic** [standardnotes/forum#308]
I'm attempting to connect a WebDAV server to FailSafe using the extension's built-in "Integrations" menu. I can configure the connection, but when I attempt to attach a file I receive a red-fonted message that reads "Error uploading file." I receive no additional details about the error or what's prompting it.

I'm _assuming_ I'm just not configuring the integration properly, but I can't quite determine what I need to do differently.

**Comment by mobitar** [comment]
Can you describe who your host is, what URL you're using, and additional detail? Some users using Nextcloud have been using the dashboard link directly when instead they should be using base_url/remote.php/webdav.

**Comment by semioticrobotic** [comment]
I'm attempting to connect to my WebDAV drive at [DriveHQ](https://www.drivehq.com). It's a standard WebDAV implementation.

I prefer not to post the URL because it's unique and contains a private key. But you can view [DHQ's general instructions for creating and mounting WebDAV drives](https://www.drivehq.com), which provide the gist. Note that these are Mac instructions but I'm on Linux (working from a GUI).

**Comment by mobitar** [comment]
I spent some time with a free DriveHQ account, and it looks like the concepts it toys with are very different from traditional WebDAV. We should be getting a URL, username, and password. Instead, DriveHQ seems to have a concept of a unified URL that combines all this into one, resulting in a single URL. However, this URL seems only applicable within the DriveHQ ecosystem. With traditional WebDAV, you should just be able to enter the URL in the browser to view the file directory, but it's clear with DriveHQ, this doesn't work. 

I'm not sure how else to debug this. If I've missed something based on the documentation you've shared, please let me know.

**Comment by samcxjo** [comment]
Apologies for tagging onto this if it's a different issue, but I'm seeing the exact same message/error for FastMail's WebDAV, which does sound like a standard implementation from mobitar's description above.

From my testing, it seems my issue is filesize-related: anything over ~5MB fails whereas smaller files are attached successfully. This seems quite far from the 50MB limit that both FileSafe and FastMail list as their maximum.

I haven't tested with other providers yet, but I'd be interested if you have any idea why this might be failing for larger files.

**Comment by semioticrobotic** [comment]
Ah. Well, darn. But thank you, @mobitar, for all the work you did to investigate this for me. Looks like I will just need to find another way to enjoy FailSafe's WebDAV integration.

**Comment by samcxjo** [comment]
@mobitar well that seems to have solved it! A few test files of 30-40MB working fine now. Thanks for the fast response!

**Comment by mobitar** [comment]
Ok great!

**Comment by mostlyjason** [comment]
I ran into this problem using NextCloud and wanted to share my solution for others. The NextCloud [documentation](https://docs.nextcloud.com/server/16/user_manual/files/access_webdav.html) says to use the URL `example.com/nextcloud/remote.php/dav/files/USERNAME/` however this does not work in StandardNotes. Instead, use the URL `example.com/remote.php/dav/files/USERNAME/`

**Comment by CharlesCage** [comment]
> I ran into this problem using NextCloud and wanted to share my solution for others. The NextCloud [documentation](https://docs.nextcloud.com/server/16/user_manual/files/access_webdav.html) says to use the URL `example.com/nextcloud/remote.php/dav/files/USERNAME/` however this does not work in StandardNotes. Instead, use the URL `example.com/remote.php/dav/files/USERNAME/`

Just wanted to say thanks. This got me going as well. :)

**Comment by flomax** [comment]
Also, in regards to Fastmail WebDAV issues, I found you need to specify the whole URL https://webdav.fastmail.com - swap the @ in your username for a # symbol, and point the path to user.domain.com/files/foldername (assuming foldername already exists)
Using the https://myfiles.fastmail.com URL seems problematic. ymmv.

**Comment by matharuajay** [comment]
hi guys i am still struggling with setting up standard notes with nextcloud 
When i try to register i get server error occurred. 
- I am using the webdav url in the format mentioned above

- Do i have to create a user with that email and password in nextcloud?
- how do i authenticate webdav url? since logging to nextcloud would need username and password

**Comment by mobitar** [comment]
I believe your default account should have it's own URL but I'm honestly not a Nextcloud user so I can't be sure. Can you share more specific details with what you've tried?

**Comment by TheodoreChu** [comment]
@matharuajay, please try the instructions located at https://github.com/standardnotes/syncing-server/issues/132#issuecomment-722995432: 

> Server-URL:
https://{Your domain-/hostname}/nextcloud/remote.php/dav

> Username/Password:
Don't use your actual login credentials, use app-credentials.

> Directory:
files/{Your subfolder}

**Comment by effieeee** [comment]
Closing, as FileSafe has been deprecated
