### ISSUE TITLE
Super: When cursor is placed within a word and Enter is used to start a new line, the new line has an extra space highlighted

### ISSUE THREAD

**Issue by dec0dOS** [standardnotes/forum#3084]
**Describe the bug**
Pressing the enter button in the middle of the word produces redundant space. (GBoard is used)

**To Reproduce**
1. Open any Super Note
2. Write down the word
3. Insert the cursor inside the word
4. Press enter

**Expected behavior**
New line appears without the additional space

**Screencast**

https://github.com/standardnotes/forum/assets/14824142/3d454075-fac2-4d78-8e13-49f578ac665a

**Smartphone (please complete the following information):**
 - Device: S23
 - OS: Android 13
 - Version 3.160.17

**Additional context**
This is particularly annoying when editing lists

**Comment by dec0dOS** [comment]
https://github.com/standardnotes/app/pull/2336 has fixed the backspace issue, but the new line issue is still present

**Comment by dec0dOS** [comment]
Seems to be everything works as expected with the Samsung Keyboard. That is really strange because I haven't experienced any issues with the GBoard in any other app before

**Comment by effieeee** [comment]
Hi @dec0dOS, indeed I can reproduce this on Android using Gboard, though I'm afraid I'm not really sure why the issue only happens with Gboard so far...

**Comment by dec0dOS** [comment]
It seems that GBoard uses multiple events when pressing the "enter button"

https://github.com/facebookarchive/draft-js/issues/2983

> I'm seeing Issue 1 as well. Could be linked to the fact that GBoard on Chrome on Android produces compositionupdate events rather than firing keydown/up with the "enter" keyCode. See discussions [here](https://bugs.chromium.org/p/chromium/issues/detail?id=809107) and [here](https://bugs.chromium.org/p/chromium/issues/detail?id=118639). You can use this tool to see what exact events are fired: https://domeventviewer.com/key-event-viewer-ce.html.
I wonder if https://github.com/facebookarchive/draft-js/pull/1419 would move towards addressing this issue? (Haven't tested.) Unfortunately, that PR seems to have been abandoned. I'd love to hear whether Facebook is currently putting any effort towards Android compatability!
But Why Its working fine if we just edit a space or dot before enter?
@Noushad-web
i don't know about dot but in case on space it is working correctly because in GBoard when you hit space, you actually get out of the composition mode.

It would be awesome to see the fix in the near future, because this bug makes the Super Editor on mobile almost unusable

**Comment by dec0dOS** [comment]
I've found two more bugs. With the GBoard and Samsung Keyboard

I don't know if I should open two new issues, because they seems to have the same root problem.


https://github.com/standardnotes/forum/assets/14824142/272010f0-90d0-4e14-96e5-ab100d9c0a73


https://github.com/standardnotes/forum/assets/14824142/64c6177a-bbe6-4271-a88e-1a3342cd94af

**Comment by effieeee** [comment]
I was able to reproduce those issues, though it is best to have them on a separate thread. I'll be closing this one for now, so please continue tracking the spacing issues on #3103 🙏

**Comment by dec0dOS** [comment]
After closing the current [issue](https://github.com/standardnotes/forum/issues/3084), the new line bug is no longer being tracked.
