### ISSUE TITLE
How to speed up syncing

### ISSUE THREAD

**Issue by lxnow** [standardnotes/forum#309]
Hi! Is there a way to speed up the synchronization process? I think it takes time because of the decryption process (correct me if I am wrong please) *particularly* during startup of the web page or the desktop or even mobile app -- would archiving notes help here?

PS I have not 'archive'd any notes at this time because never saw the need. Thanks.

**Comment by mobitar** [comment]
Archiving notes would not help as those also need to be decrypted. How many notes do you have? Really no way to speed it up at this point. We do incremental loading so that 100 are loaded at a time and you don't have to wait for all of them.

**Comment by lxnow** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} I have 1600+ at this point. Yeah I notice that they load up 100 at a time on web and desktop, and already have notes unencrypted on the Android app. Ah too bad -- maybe will consider as a feature update (not sure how it would be done).                                                                                                                                                                         Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: September 19, 2018 9:46 PMTo: forum@noreply.github.comReply-to: reply@reply.github.comCc: laurence@union.ph; author@noreply.github.comSubject: Re: [standardnotes/forum] How to speed up syncing (#309)  Archiving notes would not help as those also need to be decrypted. How many notes do you have? Really no way to speed it up at this point. We do incremental loading so that 100 are loaded at a time and you don't have to wait for all of them.

**Comment by lxnow** [comment]
> Archiving notes would not help as those also need to be decrypted. How many notes do you have? Really no way to speed it up at this point. We do incremental loading so that 100 are loaded at a time and you don't have to wait for all of them.

Maybe load them by recency? (Or is that already what's happening... )

**Comment by mobitar** [comment]
Not really feasible with our architecture I'm afraid without massive changes.

**Comment by TheodoreChu** [comment]
I'm closing this because syncing is much faster with recent updates to the architecture. Please comment if you have further issues
