### ISSUE TITLE
Super Note Mobile search

### ISSUE THREAD

**Issue by dec0dOS** [standardnotes/forum#3091]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?** yes

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to find something (or check if some entry is already there) on the phone.

**Describe the solution you'd like**
Add the search button on mobile to open up the search in the Super Note

**Comment by effieeee** [comment]
Hi @dec0dOS, the search function can be found on the mobile toolbar! You'll just have to scroll right on the toolbar to find it amongst the other formatting options 🙏

![Screenshot_20230519_235741_Standard Notes](https://github.com/standardnotes/forum/assets/54989748/dbaa4150-efdd-48b5-b922-0f76e87684fa)

**Comment by dec0dOS** [comment]
Oh, thanks @effieeee!

It's not obvious that this bar is scrollable >_<
