### ISSUE TITLE
Login impossible on iOS

### ISSUE THREAD

**Issue by br4yd** [standardnotes/forum#3092]
**Describe the bug**
It is not possible to login to iOS as it is for other apps.

**To Reproduce**
1. Download the app
2. Enter your login details

**Expected behavior**
It should ask for 2FA code and then login

**Actual behaviour**
- It asks for security key even when I didn't had one setup for that account
- I then setup one for the account and can use it on Desktop and web to login
- I can not login with the same security key on iOS
- The iOS dialogue tells me to choose between Passkey and a security key -> Choosing security key shows that no matching key was found 
- Even added the TOTP code to the Yubikey and called it "Standard Notes" but it still says "Standard Notes" couldn't be found on the key.

This makes logging in and reading my notes impossible.

**Smartphone (please complete the following information):**
 - iPhone 13 Pro
 - Standard Notes version 3.160.8
 - iOS version 16.5 (20F66)

**Additional context**
Interestingly I can "create" a new account via my iPhone using my mail that's already signed up. Then it says it's connected and wants me to buy the subscription again. However my actual account with the same mail on Desktop exists and is subscribed

**Comment by jom4337** [comment]
I have an identical issue with Apple hardware.   I am running Linux on an early 2015 Intel MacBook Pro as an alternate system.  When I attempt to log into Standard Notes, even on the web app, it prompts me to "touch the security key".  I never set up a hardware passkey in Standard Notes and this old mac doesn't have a fingerprint reader.  I can not bypass the prompt either so Standard Notes is unusable on this system.

**Comment by effieeee** [comment]
Hi @br4yd and @jom4337, you appear to be encountering our [decoy 2FA prompt](https://standardnotes.com/help/81/why-am-i-asked-for-2FA-even-though-I-dont-have-it-enabled), so I would need to do some account related troubleshooting here. Please reach out to us via help@standardnotes.com, and let me know the email address you've been using to sign in on the app.

I'll be closing this now, but I'll continue assisting you over our help inbox after you send us an email there 🙏
