### ISSUE TITLE
iOS can't paste in Super Note

### ISSUE THREAD

**Issue by northben** [standardnotes/forum#3096]
**Describe the bug**
Unable to paste in iPhone iOS Super Note editor. 

**To Reproduce**
Create a new note on iOS. Super Note is my default. Tap and hold, tap paste (this is the normal way to paste in iOS). Nothing happens. 

**Expected behavior**
Should be able to paste.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 16.5
 - Version 3.160.9

**Comment by effieeee** [comment]
Hi @northben, I'm afraid I wasn't able to reproduce this behavior so far on the latest version for iOS. May I know if you've tried reinstalling the iOS app as an initial step?

**Comment by northben** [comment]
Thanks for your response! I'm not actually able to reproduce the issue today... I see that I now have 3.161.0 installed, so maybe the issue was fixed, or maybe there's some other factor. I'll close the issue.
