### ISSUE TITLE
[Documentation] Merge support?

### ISSUE THREAD

**Issue by matgessel** [standardnotes/forum#310]
First thing I looked for in the [Help/FAQ](https://standardnotes.org/help) docs was whether merge is supported. If so, how are conflicts handled?

**Comment by mobitar** [comment]
Hey @matgessel, we talk about how we handle sync conflicts here: https://standardnotes.org/help/33/how-do-i-clear-duplicates

In short, we duplicate conflicted items, and do not merge.
