### ISSUE TITLE
[Feature] search for tags and autocomplete tags

### ISSUE THREAD

**Issue by RemiDesgrange** [standardnotes/forum#311]
For the moment, we can't search for tags. I have ~150 tags and this feature could be helpful.

**Comment by mobitar** [comment]
Are you talking about in the Folders pane or the editor pane? For the editor pane we have autocomplete tags: https://standardnotes.org/extensions/quick-tags

Filtering in the Folders pane is something on my radar.

**Comment by RemiDesgrange** [comment]
Ok didn't know Quick Tag thanks !! In the folders pane yes. If it's in the pipe, don't hesitate to close.

**Comment by effieeee** [comment]
Tracking this here: https://github.com/standardnotes/forum/issues/231
