### ISSUE TITLE
Links are not clickable in the Super editor

### ISSUE THREAD

**Issue by scode** [standardnotes/forum#3110]
**Describe the bug**

Links appear as such (colored, underlined) but clicking them does nothing.

**To Reproduce**

(These steps involve copy and paste in order to avoid #3109 which is an unrelated issue.)

* Stick this text into your clipboard: `http://www.google.com/` (input should be clean text; such as from a terminal; this is to ensure the link is fully interpreted as a url)
* Watch it be colored/underlined in the editor.
* Left-click the link.

**Expected behavior**

Link opens.

**Screenshots**

Nothing happens.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox, Chrome
 - Version Firefox 114.0, Chrome 114.0.5735.106

**Comment by effieeee** [comment]
This appears to be similar to #3061, so I'll be closing this as a duplicate. Please continue tracking the issue there instead 🙏
