### ISSUE TITLE
FileSafe for Mobile 

### ISSUE THREAD

**Issue by beeshyams** [standardnotes/forum#313]
Mo has replied to me assuring that it is under consideration. Thank you

This is one killer feature that needs to be available on mobile given how much mobile usage is a part of our lives and how often we need to store sensitive data using it 

This issue is raised so that it is on his radar and others who support may please +1

**Comment by mobitar** [comment]
Yeah definitely, would be cool, especially since our photos and videos are mostly taken on mobile and it would be great to encrypt those.

**Comment by trevormeier** [comment]
Would love to see this also!

**Comment by effieeee** [comment]
Closing, as FileSafe has been deprecated
