### ISSUE TITLE
Android: hide keyboard when opening nav drawer

### ISSUE THREAD

**Issue by chilikasha** [standardnotes/forum#315]
1. Tap search field
2. Tap hamburger -> keyboard stays opened

Screenshot from Nexus 5X (Android 8)
![2018-09-21 14 18 51](https://user-images.githubusercontent.com/3147449/45878317-49cb8f00-bda9-11e8-96ae-20d00f83848e.jpg)

**Comment by mobitar** [comment]
Good call, thanks for the feedback @akapitoha.

**Comment by effieeee** [comment]
Old UI deprecated
