### ISSUE TITLE
impossible to open side bar (again)

### ISSUE THREAD

**Issue by andy-goryachev** [standardnotes/forum#3151]
**Describe the bug**
Once collapsed, it is impossible to open the side bar on Windows desktop app version (3.160.19 on Windows 10).
Double-clicking on a margin does not open the side bar.

Please see https://github.com/standardnotes/forum/issues/2871, https://github.com/standardnotes/forum/issues/1724

**To Reproduce**
1. Start with Tags Panel enabled and it's width set to 0.
2. It is impossible to expand the Tags Panel.
3. Disable and re-enable Tags Panel.
4. The expectation is that enabling Tags Panel should set non-0 width, but it does not, the panel width remains at 0.

**Expected behavior**
The user should be able to enable and resize Tags Panel from  *any state*

**Screenshots**
Please see https://github.com/standardnotes/forum/issues/2871

**Desktop (please complete the following information):**
 - OS: Window 10
 - Version 3.160.19 desktop

**Additional context**
I am a paying customer.

**Comment by effieeee** [comment]
Hi @andy-goryachev, I'm sorry to hear that this issue has recurred. To clarify, does your tags panel only behave this way on the desktop app so far? That is, when you sign into the web app on a browser (app.standardnotes.com), does the tags panel also appear with a width of 0?

**Comment by andy-goryachev** [comment]
yes, the desktop app on windows (I have't tried on macOS yet).

in the browser (FF w/uBlock) the behavior is totally different:
1. the tags panel seems to have a minimum width, so it is impossible to collapse it completely by mouse
2. though I expect to see only icons in this minimal width mode, parts of the numbers are visible (see the screenshot)
3. on mouse over, a scrollbar appears in the notes panel, shifting the notes down (due to their height increasing, I suppose).  it's not pretty, but I don't use in-browser app much.

![2023-06-14 08_48_18-Notes · Standard Notes — Mozilla Firefox](https://github.com/standardnotes/forum/assets/5430849/2c0c3e42-1077-4402-9f4e-6694dd72e3ed)

**Comment by effieeee** [comment]
I see, are you able to freely adjust the width of the tags panel on the web app, and have you noticed if it produces any visible changes on your desktop app as well?

**Comment by andy-goryachev** [comment]
I see what you did there.  It looks like the width of the tags panel is bidirectionally synchronized between the desktop and the web apps.  Once I changed the width in the web app, I cannot reproduce the issue in the desktop app.  I am sure someone else might encounter this condition, so a recommended workaround would be to go to the web and adjust it there.

Curiously, Settings -> Show Tags Panel is not synchronized (which is ok).

Also, it looks like the web tags panel, once resized to show icons only, works correctly on the desktop but shows clipped numbers on the web, see the screenshot.  This is a very minor issue, and it might depend on the exact fonts used.

![2023-06-21 14_50_34-Notes · Standard Notes — Mozilla Firefox](https://github.com/standardnotes/forum/assets/5430849/65bc8688-c6db-47d2-9c15-662ca993e880)

**Comment by andy-goryachev** [comment]
thank you, @effieeee !
