### ISSUE TITLE
Any chance of making an auto-update feature for desktop version?

### ISSUE THREAD

**Issue by u84six** [standardnotes/forum#3158]
I've noticed that my current version is way out of date, probably because most apps these days have an auto-update feature, or at least a "check for new updates and install" feature. Is this something that's in the pipeline? It also doesn't seem to be easy to find the current release that's not a "pre-release". How would you recommend I update to the most stable release?

**Comment by effieeee** [comment]
Hi @u84six, there is actually an auto update function on the app, but there is a persistent, [known issue](https://github.com/standardnotes/forum/discussions/2589) with auto updating on the desktop apps, so I do apologize for the trouble. 

When you visit our [app repository](https://github.com/standardnotes/app) on Github though, the **Releases** portion will show you the version that's currently marked as the latest for desktop!
![image](https://github.com/standardnotes/forum/assets/54989748/32f697a8-8a03-45be-91b7-1877ad6a4164)

**Comment by u84six** [comment]
Thank you for the info!
    On Friday, June 23, 2023 at 10:08:06 AM EDT, Effie Beldia ***@***.***> wrote:  
 
 


Hi @u84six, there is actually an auto update function on the app, but there is a persistent, known issue with auto updating on the desktop apps, so I do apologize for the trouble.

When you visit our app repository on Github though, the Releases portion will show you the version that's currently marked as the latest for desktop!
