### ISSUE TITLE
Android: do not hide keyboard when moving from title to note's body

### ISSUE THREAD

**Issue by akapitoha** [standardnotes/forum#316]
1. Start a new note
2. Tap title field -> keyboard opens
3. Enter title
4. Tap note's body area (while keyboard is opened) -> keyboard closes
Need to tap again to start typing
Video: https://jmp.sh/rA0izVt

**Comment by mobitar** [comment]
Thanks for the video, have made a note of this!

**Comment by TheodoreChu** [comment]
@radko93 or @JaspalSuri, is this fixed on the latest versions of the Android app? If yes, then we can close this issue

**Comment by JaspalSuri** [comment]
It appears to be fixed on my end. 🙂
