### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by Unluckyfeet** [standardnotes/forum#3160]
I am getting a 404 error when I try to download Standard Notes for macOS (Apple Silicon). 

I am trying to download the app from this page: https://standardnotes.com/download
When I click on the link it takes me to this page: https://github.com/standardnotes/app/releases/download/%40standardnotes/desktop%403.161.3/standard-notes-3.161.3-mac-arm64.dmg

I am using macOS 13.4.1 on my MacBook Pro

How can I download the Mac app?

**Comment by effieeee** [comment]
Hi @Unluckyfeet, another desktop build was released lately, so you might have been trying to download at the time when the links were updating or redirecting to the new build. You should be able to download the app for macOS (Apple Silicon) on our [website](https://standardnotes.com/) now, by clicking on the **Download for free** button!
