### ISSUE TITLE
Hang during search for certain letter combinations

### ISSUE THREAD

**Issue by gwynm** [standardnotes/forum#317]
I have about 1000 notes totalling about 2.5mb. Most searches happen nearly as fast as I can type, but certain combinations of characters cause the UI to hang for 20+ seconds (before eventually updating and showing search results). I can reproduce this 100% of the time for those combinations (eg "zt" will always hang).

I figure this may be hard to debug given that you don't have access to my data. Nothing shows up in the console during the hang - what can I do to provide more useful info?

**Comment by mobitar** [comment]
Hmm strange. I don't see why that would hang. I tested "zt" on my own instance but no hang. Any special pattern to the results that come back with "zt"? Also, what platform and version of the app is this?

**Comment by gwynm** [comment]
This is Version 2.3.6 (2.3.6) on OSX, but I can reproduce it on the web as well.

I'm guessing that one of the results is slow to render, or something. I'm going to try deleting results one at a time and see if it stops happening.

**Comment by gwynm** [comment]
Aha: It was a bad note. Specifically, I used the import tool to generate an import file from a folder full of .txt files that _also_ contained nvAlt's "Notes & Settings" 1mb binary file (user error). This imported a 1mb binary as a note into Standard Notes... which handled it, but at the cost of "so slow it looks like a crash" performance.

I guess possible fixes would include 1) warn when importing a note >1mb or not-plaintext,  2) warn on startup if DB contains a note >1mb,   or 3) change nothing and expect the user not to do stupid things. I can see a pretty strong case for (3), but this bit me during an "evaluate whether I can replace my existing tool with Standard Notes" session and very nearly led to "not yet, check in again in a few months", so some handholding might be useful?

**Comment by mobitar** [comment]
Interesting point. We could opt for option 3, to display a small warning that notes this large can create slowdowns. Glad you were able to get to the bottom of this!
