### ISSUE TITLE
Android app silently discards unsynced changes when backing out to note list

### ISSUE THREAD

**Issue by quicklybeforeitstoo** [standardnotes/forum#3174]
**Describe the bug**
When editing a note (definitely Markdown notes, possibly others), edits that have not synced by the time one backs out of the note are silently discarded, even though the app is still open. I have never gotten a conflicted copy as a result of this, so it doesn't seem to be saved even locally.

**To Reproduce**
1. Create a new markdown note.
2. Add 150 lines of random text (seems to make it more repeatable).
3. Make identifiable additions and quickly back out to the main note list before the upload cycle and checkmark appear.
4. Re-open the note, and observe that some or all of the last additions are missing.

**Expected behavior**
I expect that additions are saved locally as soon as they are entered, so backing out of the note and reopening it should not change the contents. I would prefer that syncing proceed even after the note has been closed (but the app is still open). If this is not feasible, I would expect a conflicted copy, but I do not expect data that was visibly entered into a note to be silently discarded under any circumstance.

**Smartphone:**
 - Device: Pixel 6
 - OS: GrapheneOS 2023062800
 - Standard Notes Version 3.162.9

**Additional context**
As this seems to be a timing issue, it can be a little tricky to reproduce. For markdown notes of 150 lines, it is fairly reproducible. I think it has happened on plain text documents as well, but much more rarely, and I am not certain of this.

**Comment by pouchofsilver** [comment]
Ah, so it’s not just me. My additions to notes have been vanishing, although i didn’t know it was from quickly returning to the note list until you said it and I did a test.
_ _ _ _ _ 
ipad mini with latest ipadOS
Desktop Mac mini running High Sierra

**Comment by effieeee** [comment]
If I'm not mistaken, the app only opts to save a copy of the changes locally in the event that there is no internet connectivity, so if you experienced this while your device was online, it's technically the expected behavior, though I also understand why you expected the data to be saved locally regardless of whether or not there's an internet connection. I'll duly take note of this!

**Comment by pouchofsilver** [comment]
Thanks, Effie.

I really don’t know what happened. I did get a WiFi6 router this year which caused some strangeness with my Desktop. However, I started using the app only from my ipad these past few days “to be safe” and I still lost some notes. (Not the whole note, just something I’d added to it). I don’t have any connectivity issues at all on the ipad so…. I just don’t know.

I appreciate your response, though.
Dave

**Comment by quicklybeforeitstoo** [comment]
Thanks for following up. Given the intent you mention, I think the most unexpected part for me is that it gives up on syncing when I switch from editing a particular note to viewing the list of all notes. I'd be prepared for lossy behavior if the app were force quit or something, but backing out to edit a few different notes in quick succession seems like a normal workflow, and I don't expect a normal workflow to result in the app giving up on syncing.

If this behavior is hard to change without messing up other things, I wonder whether it might be possible to add a warning in the case of trying to back out to the menu with unsynced changes. It wasn't obvious to me that this would discard data, and even now knowing of this behavior in theory, I often forget to pay attention to the syncing icon when navigating to a different note.

**Comment by effieeee** [comment]
Hi all, thank you for the input so far! For now I'll be closing this particular issue, but I've referenced it in a [discussion](https://github.com/standardnotes/forum/discussions/3220) about this topic 🙏
