### ISSUE TITLE
3.21.0 stable version? changelog.md is out of date?

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#3175]
@effieeee 
* Is 3.21.0 stable version?
* there are lot of pre-releases @ https://github.com/standardnotes/app/releases
* https://github.com/standardnotes/app/blob/main/CHANGELOG.md was last updated in june, 2022?

**Comment by effieeee** [comment]
Hi @jindam-vani, I'm afraid v3.21.0 is very outdated. After we merged the app repositories into one app repository, all builds for desktop and mobile are also placed here.

The latest "stable" version is the one marked as the **latest** for desktop when you check the repository's root page, as shown below:
![image](https://github.com/standardnotes/forum/assets/54989748/50ea5cd0-467f-4399-9c51-528b4575925a)

Each desktop release comes with a corresponding **Mobile** build, so you may locate the corresponding Mobile build with the same version number 👍
