### ISSUE TITLE
Enable screen rotation on Android mobile app. 

### ISSUE THREAD

**Issue by 2ears1mouth** [standardnotes/forum#3178]
I think this is self explanatory. I would love to have this feature, especially when using the app to write with a wireless keyboard (where often it is better to have landscape view for convenience). 

I'm not sure, but I think that the tablet app also doesn't support rotation, which is even more of a priority. 

Thank you :)

**Comment by effieeee** [comment]
Hi there,

While landscape mode has been disabled on iOS due to display issues, it should still be enabled for Android. I wanted to confirm if you're on the latest available version from the Play Store? (v3.162.9)

**Comment by 2ears1mouth** [comment]
Hi,
Thanks for replying! I just noticed I had installed the applet from Chrome,
not the app from the Play Store. With the app the rotation is enabled, but
it is a little odd. There are three panes, which makes the text area very
very small indeed. I think it woul dbe better once in the editor to have
that be larger, definitely.

Thank you :)
