### ISSUE TITLE
Flatpak not starting on new ChromeOS Flex install

### ISSUE THREAD

**Issue by pa-august** [standardnotes/forum#3180]
I'm attempting to run SN on a new ChromeOS Flex install and am getting:

`/app/bin/start-standardnotes: line 13: XDG_SESSION_TYPE: unbound variable`

I'm using the default Linux container which is currently still Debian 11. 
I installed the Backports version of Flatpak but that doesn't seem to have helped.

I have the SN Flatpak running fine on an official Chromebook running vanilla ChromeOS, and have had the SN Flatpak running fine on previous ChromeOS Flex installs so this behavior is new to me.

**Comment by okkei** [comment]
I have the same error message in a normal chromebook. I have not been able to use the flatpak version for several weeks. SN Version 3.165.7. Debian 11.
