### ISSUE TITLE
The new update completely messed up my notes 

### ISSUE THREAD

**Issue by makarandh** [standardnotes/forum#3190]
**Describe the bug**
Instead of notes, there are codes. 

**To Reproduce**
Open onenote and view existing notes

**Expected behavior**
Should show notes as how it was before. 

**Screenshots**

![Screenshot_20230717_073252](https://github.com/standardnotes/forum/assets/38956972/4e2de446-b4cc-49cc-abc5-d94c5dad1def)

**Desktop (please complete the following information):**
Both Windows and Linux Deskop

**Comment by effieeee** [comment]
Assisted via email
