### ISSUE TITLE
[Help Wanted] Notes menu auto-resize issue

### ISSUE THREAD

**Issue by schrades** [standardnotes/forum#3192]
**Describe the issue**
Notes Menu auto resizes; unable to manually resize or turn off this feature

**To Reproduce**
1. Open SN
2. Mouseover separator between Notes menu and individual note.

**Expected behavior**
Want to turn off this feature or otherwise be able to set the width of the Notes menu

**Screenshots**
recording: 

https://github.com/standardnotes/forum/assets/1161899/8daf57e0-5856-412e-9561-4188f4fc608b

**Desktop (please complete the following information):**
 - OS: Mac OS 13 Ventura

**Comment by effieeee** [comment]
Hi @schrades, please check if you have **Dynamic panels** active in your quick settings as shown below:
![image](https://github.com/standardnotes/forum/assets/54989748/202a89f5-93be-4194-bd75-27063bec1741)

**Comment by schrades** [comment]
> 

Thank you, I now see the menu option. I think that was it. Most recent update must have turned it off, so it was a moot.
