### ISSUE TITLE
Certain note types missing in Android app

### ISSUE THREAD

**Issue by jaden** [standardnotes/forum#3198]
**Describe the bug**
Loading notes with the following types fail with an error message:
* Alternative Rich Text
* Basic Markdown
* Markdown with Math
* Minimal Markdown

**To Reproduce**
1. Edit existing note of one of the above types
1. See error message
1. Note content is not shown

**Expected behavior**
All note types supported

**Screenshots**
Example of error with the Basic Markdown note type

![Screenshot_20230717-210343](https://github.com/standardnotes/forum/assets/142353/8095b043-10f7-4c44-9539-15eca79dad95)

**Smartphone:**
 - Device: Pixel 5a
 - OS: Android 13
- Standard Notes v3.167.0 (3002728)

**Additional context**
The issue began as of the last version update and I haven't found a workaround. The same notes load correctly from the web interface.

**Comment by effieeee** [comment]
Hi @jaden, we're very sorry for the trouble. The first thing you can try in this case is to reinstall **Basic Markdown** on your account. Please refer to [these instructions](https://standardnotes.com/help/85/how-do-i-install-third-party-plugins) from our help page, and make use of Basic Markdown's install link below:

https://standardnotes.github.io/plugins/cdn/dist/entries/com.sncommunity.markdown-basic.json

Should the issues persist, please also consult [this comment](https://github.com/standardnotes/forum/issues/3197#issuecomment-1646606543) on another issue for more steps you can try on your end.

**Comment by jaden** [comment]
Thanks for the response, that fixed the problem!
