### ISSUE TITLE
Deleted notes still appear in my listed blog

### ISSUE THREAD

**Issue by martinparkes** [standardnotes/forum#320]
I have been experimenting with Listed, and have the same issue as reported [here](https://github.com/standardnotes/forum/issues/269) in that I deleted notes before unpublishing them. Please could you apply the same fix to [my listed blog](https://listed.standardnotes.org/@martin) and remove all content and CSS from my blog?

**Comment by mobitar** [comment]
Could you email me at mo@standardnotes.org from your account email? I have no way of knowing you are the real @martinparkes :)

**Comment by martinparkes** [comment]
Thanks for resolving.
