### ISSUE TITLE
Hardware security device renamed when adding second

### ISSUE THREAD

**Issue by jonhadfield** [standardnotes/forum#3202]
**Describe the bug**
Adding a second device renames the first one to "Security Key"

**To Reproduce**
1. Go to 'Preferences' -> 'Security' -> 'Add Device' to add your first device and give it a name.
2. Repeat step 1 and the name of the first device is automatically changed to "Security Key"

**Expected behavior**
The first hardware security device's name should persist.

**Screenshots**
This is what is shown after adding one device with name "5C NFC" and then adding a second device with name "Personal".
<img width="472" alt="image" src="https://github.com/standardnotes/forum/assets/843944/baa86533-1891-41f4-af56-f1c7520db515">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1
 - Browser: Firefox
 - Version: 116.0b8 (64-bit)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
Refreshing the app (web) viewing on device, etc. makes no difference after the second device is added. The first key's name is still "Security Key".

**Comment by effieeee** [comment]
Hi @jonhadfield, apologies for the rather late response here, but I wanted to ask if you still experience this on your end?

**Comment by jonhadfield** [comment]
Hi @effieeee,
I've just removed and re-added three devices. Each name is now preserved.  
Thanks!
