### ISSUE TITLE
Unable to sync error [Help Wanted]

### ISSUE THREAD

**Issue by usyboi** [standardnotes/forum#3203]
**Unable to sync error **
I am getting Unable to sync error on all my devices

**Expected behavior**
i expected all the notes to show and be synced on all my devices 

**Desktop (please complete the following information):**
 - Windows
 - Firefox
 - 3.167.9
 
**Smartphone (please complete the following information):**
 - Samsung A52: [e.g. iPhone6]
 - android 13: [e.g. iOS8.1]
 - 3.167.9
 
**Additional context**
![Screenshot (1608)](https://github.com/standardnotes/forum/assets/9163313/212f6d37-20a0-4822-914f-42bc2c63e75f)

**Comment by effieeee** [comment]
Hi @usyboi, sync issues are better handled over email since it may involve some account related details, so please contact us at help@standardnotes.com using your Standard Notes account email, and we'll do our best to assist you from there. I'll temporarily close this for now!
