### ISSUE TITLE
[Help Wanted] - Change default editor?

### ISSUE THREAD

**Issue by CdtDelta** [standardnotes/forum#3205]
**Describe the issue**
Can't find where you set the default editor anymore.

**To Reproduce**
1. Go to https://standardnotes.com/help/69/how-do-i-make-an-editor-my-default-editor
2. Follow steps
3. I don't have a New Note Defaults option

**Expected behavior**
Find the missing New Note Defaults menu option

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux/OS X
 - Version: 3.166.9 and later (I have a separate issue for OS X not having a package for the latest version)

**Additional context**
I may be looking in the wrong place, but I can't find the option anywhere.

**Comment by effieeee** [comment]
Hi @CdtDelta, please see my screenshot below!
![image](https://github.com/standardnotes/forum/assets/54989748/636dce6a-e8ef-4d61-bda5-1f1f2d70d43f)

**Comment by CdtDelta** [comment]
Of course, it was the one place I didn't look because I thought that was just sorting....sigh...
