### ISSUE TITLE
[Help Wanted] filesafe extension url dead?

### ISSUE THREAD

**Issue by jspaetzel** [standardnotes/forum#3206]
https://extensions.standardnotes.org/repos/legacy/filesafe looks like it might be a dead link now? I want to reinstall the extension to decrypt a few dozen files.

`Error downloading package details. Please check the extension link and try again.`

**Comment by effieeee** [comment]
Hi @jspaetzel, you should still be able to access FileSafe through any note that uses **Alternative Rich Text** or the **Bold Editor**. On the editor's toolbar, there is an icon that lets you open the FileSafe interface:

![image](https://github.com/standardnotes/forum/assets/54989748/ee309871-b351-4af4-9955-71d41603ef31)

**Comment by jspaetzel** [comment]
great, that works thanks!
