### ISSUE TITLE
[Help Wanted] Check for Update issue - "code":"ERR_UPDATER_CHANNEL_FILE_NOT_FOUND"

### ISSUE THREAD

**Issue by harrisondesbrosses** [standardnotes/forum#3207]
Hi,

Recently, I noticed that I hadn't got an auto-update prompt in two months, and decided to do a manual check. Upon doing a manual check, I received the message: "An issue occurred while checking for updates. Please try again.
If this issue persists please contact support with the following information: {"code":"ERR_UPDATER_CHANNEL_FILE_NOT_FOUND"}" 

As a first step in troubleshooting, I went ahead and downloaded 3.167.16 from the SN website and did a re-installation. I'm continuing to experience the same problem.

I run Little Snitch and checked if I had accidentally blocked anything to do with SN, but all good there as well. I'm stumped on how to troubleshoot this issue further. Any help would be greatly appreciated, thank you.

MacBook Pro M1
Ventura 13.5

**Comment by thedaveCA** [comment]
I'm seeing the same here, macOS Ventura 13.5, tested 3.162.3 and 3.167.17.
Cannot reproduce on Windows Desktop 3.162.3 or 3.167.17.

**Comment by effieeee** [comment]
Hi all, can I ask you to check for this again on the Mac app? An update to the Github assets and dependencies was made shortly after this issue was opened here 🙏

**Comment by thedaveCA** [comment]
Looks resolved, thanks!

**Comment by harrisondesbrosses** [comment]
Same for me, thank you!
