### ISSUE TITLE
FileSafe errors and cannot minimize

### ISSUE THREAD

**Issue by few4i** [standardnotes/forum#3208]
**Describe the issue**
FileSafe feature is giving error messages which is of concern, but the main problem is that I lose over a third of my note space!  I can't find any settings or information about FileSafe.  And I can't minimze FileSafe.

This is the error message - 

"The page you were looking for doesn't exist.
You may have mistyped the address or page may have moved.
If you are the application owner check the logs for more information."

**To Reproduce**
Open any note in my installation in windows and chrome.  iOS seems fine.

**Expected behavior**
Not have error messages in FileSafe, or maybe more importantly be able to minimize FileSafe.

**Desktop (please complete the following information):**
 - OS:  Windows 10 & 11
 - Browser: chrome
 - Version :  115.0.5790.110

**Smartphone (please complete the following information):**
 - Device:  iPhone 11, all updates installed

**Additional context**
Thanks for any help.

**Comment by effieeee** [comment]
Hi @few4i, please see my comment in this [related issue](https://github.com/standardnotes/forum/issues/3211#issuecomment-1658878452) 🙏
