### ISSUE TITLE
Erroneous message "Your subscription expired in 2024"

### ISSUE THREAD

**Issue by JPL1** [standardnotes/forum#3211]
**Describe the bug**
I'm seeing an error message 2/3 of the way down the note window saying "Your subscription expired in July 2024, Action bar is in a read-only state. There was an issue loading Filesafe"

Obviously this is in the future. It seems to be misreading or ignoring the year.

**Desktop (please complete the following information):**
 - Linux - Mint
 - Version 3.167.14

**Comment by JPL1** [comment]
May be related to https://github.com/standardnotes/forum/issues/3208

**Comment by effieeee** [comment]
Hi @JPL1, the Action Bar and FileSafe are actually already deprecated extensions, so this is likely why you're seeing issues with it even if you have an active subscription. If you perhaps don't use these very often and you'd like to hide them, you can try clicking or tapping on the radio button next to their names, or you can also try deactivating them under the **Tools** section of the **Quick Settings** menu on the lower left of the app:

![image](https://github.com/standardnotes/forum/assets/54989748/40da8603-c0a0-4ada-817c-eda08d030217)
