### ISSUE TITLE
Notes Unreadable on Dark Theme - Mobile

### ISSUE THREAD

**Issue by umahdroid** [standardnotes/forum#3224]
**Describe the bug**
Text is unreadable when I'm using [Scratch Editor](https://dylanonelson.github.io/sn-scratch-editor/) extension on Standard Notes Android with dark theme. It's not a case if you're using light theme, third-party dark theme (I use [this theme](https://github.com/andryou/sn-pure-black-themel)), and Standard Notes desktop (both light and dark theme).

**Screenshots**
### Dark Theme on Android
![Screenshot from 2023-08-06 18-31-23](https://github.com/standardnotes/forum/assets/39919860/9a1c64d8-07c5-41cf-99f8-aa0dcfedfb45)

### Light Theme on Android
![Screenshot from 2023-08-06 18-31-09](https://github.com/standardnotes/forum/assets/39919860/227a9923-b9e3-4235-a06e-662392789e83)

### Third-party Dark Theme on Android
![Screenshot from 2023-08-06 18-31-33](https://github.com/standardnotes/forum/assets/39919860/7a9c282d-6021-4731-af05-39b27a86ccf2)

### Desktop
![Screenshot from 2023-08-06 18-35-27](https://github.com/standardnotes/forum/assets/39919860/6734fc3a-57b6-4ddf-98eb-49504a42cb88)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 3.167.38

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 11
 - Version: 3.167.22

**Comment by effieeee** [comment]
Hi @umahdroid, the issue may also be specific to the Scratch Editor in particular, so I can't quite say if this is something that needs to be addressed on our end in particular. You may try opening an issue in the Scratch Editor's [repository](https://github.com/dylanonelson/sn-scratch-editor) to ask if any changes need to be made for the font to adapt properly on the app's official dark theme 🙏
