### ISSUE TITLE
Be able to highlight text (besides bold, underline, ...)

### ISSUE THREAD

**Issue by jrcacd** [standardnotes/forum#3229]

**Comment by effieeee** [comment]
This is already available when using the **Rich Text** note type 🙏

**Comment by jrcacd** [comment]
I didn't knew. How thant can be done? 
Is there any button to highlight the selected text? 
Is it possible to assign some keyboard shortcut (for example: CTRL + SWIFT + H (which is common in many programs))?

**Comment by jrcacd** [comment]
I mean, in the Super Text.

**Comment by effieeee** [comment]
Ah, I see, in the case of **Super** though, I'm afraid text highlighting isn't available as a function yet. The Lexical framework does seem to support this, though we'll have to test it out further on our end first 🙏
