### ISSUE TITLE
Versioning on Extended?

### ISSUE THREAD

**Issue by DrownedStarfish** [standardnotes/forum#323]
Hi!

If I understood correctly, Extended stores earlier versions of notes.  How do I turn this on, and how do I recover an earlier version?

Thanks.
D.

**Comment by SiGamma** [comment]
On the desktop app, click on Extensions and find and install CloudLink. Once it's installed, run it/activate it and you'll get a window from which you can install Note History. Once that is installed and activated, it'll start versioning notes. You should be able to access it from any note by clicking Actions in the note window, and it'll list out all the saved note versions. Clicking them will allow you to preview and recover an earlier version.

**Comment by DrownedStarfish** [comment]
Thanks!

**Comment by mobitar** [comment]
Thanks for helping out @SiGamma :)
