### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by koviubi56** [standardnotes/forum#3237]
**Describe the bug**
For a few weeks now when I try to open StandardNotes I get a blank black screen and nothing happens.

**To Reproduce**
1. Open StandardNotes

**Expected behavior**
StandardNotes loads in as usual.

**Screenshots**
![Screenshot_2023-08-09_130429.jpg](https://github.com/standardnotes/forum/assets/58398849/4e760459-e062-43a9-99c0-b7f9ea9933e6)

**Smartphone:**
 - Device: Samsung Galaxy A7
 - OS: Android 10
 - Version: 3.167.28 from F-Droid

**Additional context**
I have tried re-installing StandardNotes, but that didn't work.

**Comment by effieeee** [comment]
Hi @koviubi56, can I ask if you've tried clearing the app data as described below?

1. Locate the Standard Notes app in the app drawer.
2. Press and hold the app’s icon until a small menu appears.
3. Tap on App Info.
4. Locate and use the option to delete/clear the app’s data.
5. Relaunch the app and sign in again.

**Comment by koviubi56** [comment]
Hi @effieeee, thank you for the reply. I have tried that but it didn't fix the issue. I can't log in.

**Comment by koviubi56** [comment]
Restarting my phone resolved this issue.
