### ISSUE TITLE
no theming in Minimal Markdown notes on Android

### ISSUE THREAD

**Issue by chaserene** [standardnotes/forum#3239]
**Describe the bug**
the colors of non-default themes don't carry over to Minimal Markdown notes in the Android client.

**To Reproduce**
1. activate any theme other than the default one (e.g. Midnight)
2. create a Minimal Markdown note 
3. open said note

**Expected behavior**
contents of the editor area are colored according to the selected theme.

**Screenshots**

![](https://github.com/standardnotes/forum/assets/64873595/69e50477-1f77-4a3f-92a3-1b1f0fa88758)

**Smartphone:**
 - OS: LineageOS 19.1 (~ Android 12)
 - Version: 3.169.20

**Comment by effieeee** [comment]
Hi @chaserene, indeed this is reproducible on Android, but I'm afraid that Minimal Markdown is now part of the [community editors](https://github.com/standardnotes/plugins) repository, so this is no longer regularly maintained by the team 😞

**Comment by chaserene** [comment]
thank you. I'm very sad to hear that the most efficient markdown editor is no longer maintained...

I'm also marking this as a duplicate of https://github.com/standardnotes/plugins/issues/7.
