### ISSUE TITLE
users paying with crypto are overcharged

### ISSUE THREAD

**Issue by chaserene** [standardnotes/forum#3240]
**Describe the bug**
users trying to buy the annual paid plans are charged an 11% higher price compared to the currently advertised prices (Productivity plan: $90 vs. $81, Professional plan: $120 vs. $108).

**To Reproduce**

1.  enter an account that doesn't have a paid plan
3. click "Unlock features" at the bottom
4. choose any of the paid plans
5. select the radio button next to "Buy with crypto"
6. click on "Buy with crypto"

**Expected behavior**
at the very least, I expect to pay the same price as those who choose and support the legacy financial system, but I actually expect a discount (e.g. Mullvad gives a 10% discount when paying in monero).

**Screenshots**

![image](https://github.com/standardnotes/forum/assets/64873595/e2d43ffc-f9a2-4b5a-826b-b43e0cec5190)

![image](https://github.com/standardnotes/forum/assets/64873595/156b537e-2195-4d02-8aec-be689e81c3f0)

**Comment by effieeee** [comment]
Hi @chaserene, this is unfortunately a limitation at the moment since Coinbase is not able to fetch a price based on custom discounts applied to an account. To pay with cryptocurrency at a discounted price, users may reach out to us at help@standardnotes.com for direct crypto payment options 🙏

**Comment by chaserene** [comment]
@effieeee the $108/year isn't a custom discount applied to my account, it's the currently listed price on the website (https://standardnotes.com/plans) for everyone:

![](https://github.com/standardnotes/forum/assets/64873595/df864bea-ebc4-4de0-bdcc-84c27781850d)

in any event, can you please note this difference during the check-out process as a separate payment method, highlighting that this "manual method" is cheaper? this would incentivize users to not go through a centralized intermediary, and use more fungible currencies for payments, like Monero, which are not supported by Coinbase.
