### ISSUE TITLE
action bar and file safe broken

### ISSUE THREAD

**Issue by ljalmanzar** [standardnotes/forum#3244]
Every os i use the app, this happens when viewing notes. i cant type since i cant see anything when my keyboard pops up. 
![IMG_0572](https://github.com/standardnotes/forum/assets/11850761/d463d638-4a21-4acf-917a-e10516b973b4)

**Comment by effieeee** [comment]
Hi @ljalmanzar, please see [this comment](https://github.com/standardnotes/forum/issues/3211#issuecomment-1658878452) on a related issue for instructions to hide those extensions!
