### ISSUE TITLE
Square blocks appearing instead of letters when changing the automated backups’ location

### ISSUE THREAD

**Issue by guillaume8375** [standardnotes/forum#3245]
**Describe the bug**
Changing the location of the automated backups is impossible because the letters composing the options and the names of the repertories are replaced by empty square blocks.

**To Reproduce**
1. Open ‘preferences’
2. Click on ‘Backups’
3. Scroll down to ‘Automatic Encrypted Text Backups’
4. Click on ‘Change location’
5. See error

**Expected behavior**
I expected to be able to read the characters in the window opened when choosing this option.

**Screenshots**
See the screenshot attached.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04 running the X Window System
 - Browser: Firefox 116.0.2 (the snap version)

**Additional context**
1. I can’t say when this problem began to appear.
2. I don’t have the same problem when I just want to open the backups’ location.

![Screenshot from 2023-08-16 22-28-37](https://github.com/standardnotes/forum/assets/1706313/3fddf641-b2f2-414d-93ed-2cdd2964eef4)

**Comment by effieeee** [comment]
Hi @guillaume8375, apologies for the delayed response here. May I know if you've looked into possible solutions regarding fonts on Ubuntu, such as this one?

https://askubuntu.com/questions/1397208/font-displayed-as-squares-in-ubuntu-20-04

**Comment by guillaume8375** [comment]
Hi @effieeee,

I tried the [solution](https://askubuntu.com/a/1397211/269948) given to the question, but it didn’t work. Same thing for [this one](https://askubuntu.com/a/1228809/269948).

**Comment by effieeee** [comment]
I see, I also noticed that you’re currently using the Snap on your device, is that correct? If so, would you also be able to check if the same behavior occurs when using the AppImage instead?

**Comment by guillaume8375** [comment]
You’re right, I’m using the Snap version. With the AppImage, I don’t get the problem: the menu appears normally. I’ll use the AppImage from now on.
