### ISSUE TITLE
Disabling translucency in the Appearance settings makes the Preferences screen unusable

### ISSUE THREAD

**Issue by neelabhg** [standardnotes/forum#3247]
**Describe the bug**
I was playing around with the Appearance settings in the latest macOS desktop app. I found a toggle switch that mentioned something about "disabling translucency". I enabled it, but now there seems to be a layer on top of the Preferences screen that makes it impossible to use it. Clicking anywhere on the screen takes me back to the home (notes) screen.

This is preventing me from going back into the settings to disable the setting.

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Appearance'
3. Enable the toggle switch for the setting regarding 'translucency' (it is the first setting; I don't know the exact setting name because I cannot navigate to it anymore).
4. See the Preferences page to be disabled:
<img width="282" alt="image" src="https://github.com/standardnotes/forum/assets/846827/fc4f135c-8099-4403-848a-3ce396cb80b8">

**Expected behavior**
The Preferences page should not be disabled and I should be able to access the Appearance settings.

**Screenshots**

Here is how the UI looks for the "disabled" Preferences page:
<img width="1089" alt="image" src="https://github.com/standardnotes/forum/assets/846827/b0c86970-f269-462a-99c8-ca52e1d0280b">
Here is how the UI looks (notes/home page) without the disabling layer on top:
<img width="442" alt="image" src="https://github.com/standardnotes/forum/assets/846827/e8183c90-0c8e-4bb5-8153-cc72e7eb326b">
<img width="169" alt="image" src="https://github.com/standardnotes/forum/assets/846827/183735de-5ca7-42f0-bfd8-c180cc6bdf1a">

**Desktop:**
 - OS: macOS 13.5
 - Browser: Not applicable
 - Version: Version 3.169.32

**Smartphone:**
Haven't tried using the smartphone app.

**Additional context**
None

**Comment by effieeee** [comment]
Hi @neelabhg, apologies for the trouble! A fix for this is coming in the next update 🙏

**Comment by neelabhg** [comment]
Thank you!
