### ISSUE TITLE
In note search

### ISSUE THREAD

**Issue by qnfm** [standardnotes/forum#3249]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Lack in note search/match/highlight

**Comment by effieeee** [comment]
Hi @qnfm, this is currently available via the **Super** note type 🙏

https://standardnotes.com/help/70/how-do-i-search-inside-a-note
