### ISSUE TITLE
On iOS, I’d like the right-hand Tag List to be sorted alphabetically. If you want to assign additional tags to a note, and you bring up the RHS Tag List, you find that it's not sorted alphabetically, so finding the Tag you need is very difficult and time-consuming

### ISSUE THREAD

**Issue by Pendyploo** [standardnotes/forum#3251]
### Discussed in https://github.com/standardnotes/forum/discussions/3105

<div type='discussions-op-text'>

<sup>Originally posted by **Pendyploo** June  4, 2023</sup>
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
</div>

**Comment by effieeee** [comment]
Hi @Pendyploo, as this is a suggestion/feature request, this is better kept within the Discussions page 🙏I'll be closing this now to avoid duplication
