### ISSUE TITLE
Is there any "Undo" and "Redo" command in the iOS version of Standard Notes ?

### ISSUE THREAD

**Issue by Pendyploo** [standardnotes/forum#3253]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by effieeee** [comment]
Hi @Pendyploo, unfortunately there is no physical button for this within the app right now, but the shake gestures on iOS can still work as an alternative in the meantime 🙏

**Comment by Pendyploo** [comment]
Hi Effie,Good to know.  I’d be wary about "Shake" to Undo, because of unforeseen consequences (but I'll try it and see if I can live with it).  Hope it becomes a feature soon.Kindest Regards,  George. iPadOn Aug 23, 2023, at 11:21 AM, Effie Beldia ***@***.***> wrote:﻿
Hi @Pendyploo, unfortunately there is no physical button for this within the app right now, but the shake gestures on iOS can still work as an alternative in the meantime 🙏
