### ISSUE TITLE
In Rich Text Mode, Clicking on text does not disclose its font-size. You must highlight a text string and apply a font-size by trial and error to see whether it will be smaller or larger.

### ISSUE THREAD

**Issue by Pendyploo** [standardnotes/forum#3254]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by effieeee** [comment]
Hi @Pendyploo, currently, when I place the text cursor on a certain word or block of text, the font size indicated on the toolbar of the Rich Text editor will display the current font size of the word where the cursor is placed. Is this not happening on your end, or did you want something different to happen in terms of displaying the font size of the current text?

**Comment by Pendyploo** [comment]
Hi Effie,You are correct. Please accept my apologies. Placing the cursor now on a word DOES display the font Size, on Mac and on iPad.I believe that in the past when I reported, this may have happened because I was using an MS Mouse with my iPad, or that a subsequent update has cured the issue, or that synching paralyzed cursor response for a time. This happens in other contexts quite often.  By the way, can I set synching to be only done manually?Thanks for your prompt and helpful response.Kindest Regards,  George. iPadOn Aug 23, 2023, at 11:20 AM, Effie Beldia ***@***.***> wrote:﻿
Hi @Pendyploo, currently, when I place the text cursor on a certain word or block of text, the font size indicated on the toolbar of the Rich Text editor will display the current font size of the word where the cursor is placed. Is this not happening on your end, or did you want something different to happen in terms of displaying the font size of the current text?

**Comment by effieeee** [comment]
No worries! Regarding your follow up question, no I'm afraid there's no way to sync manually at the moment 🙏I'll be closing this now as well!
