### ISSUE TITLE
Spreadsheet Note Type is not usable.

### ISSUE THREAD

**Issue by Pendyploo** [standardnotes/forum#3255]
After you create a Spreadsheet note type, the Spreadsheet most often does not respond at all. The Keyboard does not appear. Cells cannot be accessed.  Menu icons seem to be active, but don't do anything. Very rarely, sometimes you're able to enter data in one cell, but then you can't edit that data, and can't access other cells.  You are unable to alter column widths. if you add a new Sheet to the Spreadsheet you can enter data in the top RHS cell. The only way to move to another cell is to use Tab or Shift-Tab.  Haven't found a way to move to cells upwards or downwards. You can't enter formulas.  

 - Device: iPad 12.9
 - OS: iOS 16.6
 - Browser Safari
 - Software Update 2023-08-22

**Comment by effieeee** [comment]
Hi @Pendyploo, I'll continue tracking this via the [discussion](https://github.com/standardnotes/forum/discussions/3256) you opened. As mentioned there too, this is not an issue that can be immediately fixed on our team's end, so this is best kept on the discussions page as well 🙏
