### ISSUE TITLE
FileSafe files backup decryption

### ISSUE THREAD

**Issue by amelnikov** [standardnotes/forum#3258]
In one of the recent Standard Notes updates notes with FileSafe files stopped displaying correctly. 

I only now learned that FileSafe was deprecation early last year, as well as other plugins.

I disabled all the plugins in General -> Advanced options in the attempt to recover the operation, but it did not help. How do I restore FileSafe encrypted files? I see that the links found on forum can't install FileSafe back either.

Is there a decryption tool? I have all the SafeFile .sf.json files saved.

Thank you.

**Comment by effieeee** [comment]
Currently assisting via email
