### ISSUE TITLE
Extensions cannot be loaded: "There was an issue loading ..."

### ISSUE THREAD

**Issue by marcopatr** [standardnotes/forum#326]
Hi! No matter which extension I install, this error message appears every time: "There was an issue loading ...". Uninstalling the extension, or the whole program, doesn't change anything. How can this be solved?

**Comment by mobitar** [comment]
Hi @marcopatr, I'd need your email address to look into this, as it's possibly an account issue. Can you email me at mo@standardnotes.org?
