### ISSUE TITLE
Super notes RTL lists padding/margins incorrect

### ISSUE THREAD

**Issue by eadoking** [standardnotes/forum#3261]
**Describe the bug**
Super notes support RTL by direction (RTL/LTR), which is good for normal text in (Arabic, Hebrew or Persian)

But, if the text includes lists, the padding/margins for the lists/sublists is incorrect.

RTL lists are supposed to be margined/padded from the right, not from the left 

in the following photo, you can see the Arabic lists are off and incorrect.

<img width="1005" alt="image" src="https://github.com/standardnotes/forum/assets/441839/125b1deb-a1f8-4eb5-9c51-ba35f3f4356f">

for this note, if we open the JSON file (attached also), we can see, that the direction is set correctly to RTL but not displayed correctly.

<img width="996" alt="image" src="https://github.com/standardnotes/forum/assets/441839/77290eee-27fe-40f9-815e-7377e45545f8">
 

So the problem is with the rendering or styling and CSS

**To Reproduce**
1 - Copy the following content of the JSON file of the test super note

```
{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"اختبار نص لغة عربية يحتوي على تصنيفات رئيسية وفرعية","type":"text","version":1}],"direction":"rtl","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"رئيسية ١","type":"text","version":1}],"direction":"rtl","format":"","indent":0,"type":"listitem","version":1,"value":1},{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"فرعية ١\\١","type":"text","version":1}],"direction":"rtl","format":"","indent":1,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"فرعية ١\\٢","type":"text","version":1}],"direction":"rtl","format":"","indent":1,"type":"listitem","version":1,"value":2}],"direction":"rtl","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"rtl","format":"","indent":0,"type":"listitem","version":1,"value":2},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"رئيسية ٢","type":"text","version":1}],"direction":"rtl","format":"","indent":0,"type":"listitem","version":1,"value":2},{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"فرعية ٢\\١","type":"text","version":1}],"direction":"rtl","format":"","indent":1,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"فرعية ٢\\٢","type":"text","version":1}],"direction":"rtl","format":"","indent":1,"type":"listitem","version":1,"value":2}],"direction":"rtl","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"rtl","format":"","indent":0,"type":"listitem","version":1,"value":3}],"direction":"rtl","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"english test with a list/sub lists","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"main 1","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":1},{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sub 1/1","type":"text","version":1}],"direction":"ltr","format":"","indent":1,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sub 1/2","type":"text","version":1}],"direction":"ltr","format":"","indent":1,"type":"listitem","version":1,"value":2}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":2},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"main 2","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":2},{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sub 2/1","type":"text","version":1}],"direction":"ltr","format":"","indent":1,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"sub 2/2","type":"text","version":1}],"direction":"ltr","format":"","indent":1,"type":"listitem","version":1,"value":2}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"ltr","format":"","indent":0,"type":"listitem","version":1,"value":3}],"direction":"ltr","format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":"rtl","format":"","indent":0,"type":"root","version":1}}

```

2- Create new note anywhere and choose the type as `Plain Text`
3 - paste the content 

<img width="1004" alt="image" src="https://github.com/standardnotes/forum/assets/441839/6c2a8008-c41e-496a-b4b1-603443fecfab">

4- Change the type to `Super`
5- in the convert to suprt note choose `Convert As-IS`
<img width="646" alt="image" src="https://github.com/standardnotes/forum/assets/441839/07ede887-0006-4616-86b7-7733511eae95">
6- confirm
<img width="484" alt="image" src="https://github.com/standardnotes/forum/assets/441839/f6fa8120-00df-487f-b526-dd99c4b3405c">

Then you can now see how the Arabic lists margins/paddins are off and incorrect 

**Expected behavior**
to have the padding/margin correct from the right side for the list/sub lists as the English version 

English uses`LEFT` paddins/margin
Arabic and RTL languages use `RIGHT` padding/margin

**Screenshots**
Added on the description for the affected macOS desktop app + 
browser 
<img width="1061" alt="image" src="https://github.com/standardnotes/forum/assets/441839/a3db0daf-a048-4c38-b313-b2ee682680d4">

mobile 
![image](https://github.com/standardnotes/forum/assets/441839/cbc48027-cabd-4523-babe-5d6d597b4cb1)

**Desktop (please complete the following information):**
 All the environments I have is affected 
- desktop MacOS 13.5
- browser web (chrome + safari + firefox)

**Smartphone (please complete the following information):**
- mobile iOS 16.x, iPhone 13 Pro + iPhone X

**Additional context**

** How to fix **
After inspecting the browser version, we can see for the following correct behaviour for the English list/sub list
<img width="981" alt="image" src="https://github.com/standardnotes/forum/assets/441839/058ccef7-b4ae-4297-bacc-e1b9980e1b31">

and it has correct `margin-left: 16px`
<img width="299" alt="image" src="https://github.com/standardnotes/forum/assets/441839/af436fd4-6e62-4e3f-8dac-7b91b7de50e0">

So, to fix we have to adapt the classes of `.Lexical__rtl` to correct the margin to something like 
<img width="302" alt="image" src="https://github.com/standardnotes/forum/assets/441839/5d3b5642-8a1e-44bc-86a3-caef71185f00">

then we should have the issue corrected and the hidden overflow also should be corrected

<img width="520" alt="image" src="https://github.com/standardnotes/forum/assets/441839/1d336922-dee1-4755-9799-98cb08269223">

**Comment by effieeee** [comment]
Hi @eadoking, thank you for your detailed report and suggestions to fix it! A [commit](https://github.com/standardnotes/app/commit/42321fbe2b861cd1606f8549818ebb7e86165083) has now been pushed to fix this!

**Comment by eadoking** [comment]
Thanks @effieeee, this commit will fix this issue.
