### ISSUE TITLE
RTL Padding/margin are off and incorrect for super notes

### ISSUE THREAD

**Issue by eadoking** [standardnotes/forum#3262]
related to issue #3261, where I explained the reproduction in details for the list/sublists

In addition to what it was in that issue, after a detailed check, all the elements which has `margin-left` or `padding-left` need to be corrected to have the theme work as expected

The following elements are affected
- Lexical__quote
- Lexical__ol1 --> Lexical__ol6
- Lexical__ul
- Lexical__listItemUnchecked

I think most of the changes could be done in this file 
`https://github.com/standardnotes/app/blob/main/packages/web/src/javascripts/Components/SuperEditor/Lexical/Theme/editor.scss`

**Comment by effieeee** [comment]
Please see [this comment](https://github.com/standardnotes/forum/issues/3261#issuecomment-1703812823) with the link to the fix!

**Comment by eadoking** [comment]
Hi @effieeee, I saw the comment. This fixes only the lists, (ol/ul/li) but also need to fix the 
- quote

<img width="983" alt="image" src="https://github.com/standardnotes/forum/assets/441839/b6a4ff6a-374f-46e2-b513-ab1dc65ec584">


the quotes in Arabic or RTL / should also be margined from right for this to be fixed + border + padding 

so after these changes 

<img width="322" alt="image" src="https://github.com/standardnotes/forum/assets/441839/899a7f9b-d948-4a0b-a590-e459cf0b9bdc">

(color should come from theme)

we get the correct display as 

<img width="995" alt="image" src="https://github.com/standardnotes/forum/assets/441839/5b2895ef-cbfc-43da-9804-23563a8efa2d">


@amanharwara please check this comment
Please reopen the issue #3262

**Comment by amanharwara** [comment]
Hi @eadoking, thanks for letting us know, I'll push a fix soon.
Also, there's no need to comment about the same thing in multiple places. Once would've sufficed, thanks 🙂

**Comment by eadoking** [comment]
> Hi @eadoking, thanks for letting us know, I'll push a fix soon. Also, there's no need to comment about the same thing in multiple places. Once would've sufficed, thanks 🙂

Thanks ❤️
