### ISSUE TITLE
Checklist formatting issue, first task not readable

### ISSUE THREAD

**Issue by stefs** [standardnotes/forum#3271]
**Describe the bug**
The first task in a checklist note is not fully visible vertically.

**To Reproduce**
1. Add a new checklist note
2. Add one or more tasks
3. Optional: Reload the note
4. Observe the first task is not readable

**Expected behavior**
All tasks are readable

**Screenshots**
![Bildschirmfoto vom 2023-08-31 21-54-28](https://github.com/standardnotes/forum/assets/7479956/f228f302-d3df-4d32-9668-84e41c14335c)

**Desktop**
 - OS: Fedora Linux 38 (Workstation Edition)
 - Browser: Firefox 116.0.3
 - Standard Notes Version: 3.172.1

**Comment by effieeee** [comment]
Hi, please see the comment from a duplicate issue linked below!

https://github.com/standardnotes/forum/issues/2430#issuecomment-1592006215
