### ISSUE TITLE
Selected text doesn't highlight

### ISSUE THREAD

**Issue by dramm33** [standardnotes/forum#3272]
**Describe the bug**
The selected text doesn't get highlighted. Applies everywhere in the app, from note text to titles to the menus. I tested with different themes to be sure.

**To Reproduce**
1. Go to any note.
2. Click and drag on any text.
3. See error.
4. Can confirm the text was selected by typing something and seeing the selected part replaced.

**Expected behavior**
The selected text should be highlighted to indicate the selection.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - App built from source using [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=standardnotes-desktop)
 - Version 3.172.1 (but this also happens in the previous versions).

**Additional context**
Works fine in Windows 10.

**Comment by effieeee** [comment]
Hi @dramm33, I’m afraid that the team does not maintain the Arch Linux package in the link you sent, so to check if this might be somehow specific to the package, may I ask if you experience similar issues when using the official AppImage or the Snap?

**Comment by LordVlad-Neutral** [comment]
Can confirm, though the appimage does work properly, the AUR version doesn't work (in terms of highlighting). Same version as @dramm33, can't seem to update it from the AUR too, but that's another problem.

**Comment by dramm33** [comment]
It's working properly now. Not sure in which version it was fixed, I skipped a few.
