### ISSUE TITLE
listed.to down [Help Wanted]

### ISSUE THREAD

**Issue by jmason888** [standardnotes/forum#3274]
**Describe the issue**
https://listed.to is down (again); are there user-side mitigations we should consider?

**To Reproduce**
1. Go to https://listed.to (or any blog post hosted there)
2. Get ERR_CONNECTION_REFUSED
3. Go to https://downforeveryoneorjustme.com/listed.to
4. Get "It's not just you! [listed.to](http://listed.to/) is down."

This happens regularly enough that it breaks rich text notes that use stylesheets hosted on listed.to.

**Comment by effieeee** [comment]
Hi @jmason888, we apologize for the rather long downtime of Listed recently. It’s already back online, but again we do sincerely apologize that it took a while to fix over the weekend. We’ve noted similar grievances in our Discord group, and while we’ve taken a number of precautions to prevent issues like this on Rails over the years, we’ve still found that the outages can happen. Nonetheless, we’re doing our best to maintain Listed and look into other solutions to prevent such outages in the future.
