### ISSUE TITLE
Conflicts created whereas the note was modified after last synchronization

### ISSUE THREAD

**Issue by tenflo** [standardnotes/forum#3276]
**Describe the bug**
2 Standard Notes application are open in the same time with the same account on two Ubuntu computers with system clock synchronized. There is no conflict because only one person is behind those two computers and when something is changed on the first computer, the synchronization is working well for several years and today it is working fine during the week but not the week-end.
Since interface was improved to manage easily the conflicts, I'm having around 20 conflicts created by week, only after the weekend. Even if the application is correctly synchronized Friday evening on the both computers, when I'm connected for the week-end on only one of them, all changes on Standard Notes done during the week-end are considered as conflicts for the second computer with Standard Notes. 

**To Reproduce**
See above.

**Expected behavior**
As before, when all changes done are after a synchronization, Standard Notes should not considers them as conflicts. 

**Desktop:**
 - OS: Ubuntu 22.04.3 LTS
 - Version 3.172.1

**Comment by effieeee** [comment]
Hi @tenflo, I’m sorry to hear that, may I know if you’ve already tried signing out and signing back into your account on both devices as an initial step?

**Comment by tenflo** [comment]
Hi @effieeee, I signing out and signing back on all on my devices (smartphone included). When signing back all my notes were lost! So I import them from the last backup. For the moment, it seems to working fine. We will see if that correct the issue.
Weird fact: since I did that, I have 2622 notes on my laptop and 2643 notes on my smartphone.

**Comment by effieeee** [comment]
Alright, I will close this for now, but please feel free to reopen if something recurs!

**Comment by tenflo** [comment]
The issue is still happening (around 30 notes per week that are tagged as conflict whereas they are only new version of notes).

**Comment by effieeee** [comment]
@tenflo I see, though we may need to do further troubleshooting for this. Please send us an email at help@standardnotes.com using your account email, and provide a sample screenshot of one of the notes that were affected and currently appear in your **Conflicts** view. I will continue assisting you through email as well 🙏
