### ISSUE TITLE
Daily Notes folder is replicating

### ISSUE THREAD

**Issue by velardevines** [standardnotes/forum#3283]
**Describe the bug**
The Daily Notes folder is randomly replicating. There are now 3 Daily Notes folders each with a different number of notes.

**To Reproduce**
I have no idea how to reproduce this behavior. It just happens

**Expected behavior**
Only one Daily Notes folder containing all of the Daily notes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 and Linux ubuntu 22.04
 - Browser: Chromium on Linux ubuntu. Firefox on Windows
 - Version: listed abouve

**Smartphone (please complete the following information):**

**Additional context**

**Comment by effieeee** [comment]
Hi there, have you tried signing out and signing back into your account on all devices to see if it can help stop this from happening?

**Comment by velardevines** [comment]
No, I had not tried.

Ok, on the Windows laptop, I signed out then signed back in. No improvement. Another Daily Notes folder was created so now there are four Daily Notes folders.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by effieeee** [comment]
I see, though thank you for trying nonetheless. So far, have you noticed that the duplicate only appears when editing notes from a specific device, or do the duplicates appear regardless of which device you last used to edit or view your notes?

**Comment by velardevines** [comment]
The duplicate appears immediately after I login. It is not device specific.

Thank you

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by effieeee** [comment]
Hi @velardevines, thank you for checking, though in this case we will have to try to look into account related issues. Please send us an email at help@standardnotes.com using your Standard Notes account email, and we'll continue assisting you from there. Will close this for now, to continue tracking your issue via email 🙏
