### ISSUE TITLE
Per-Tag preferences  cannot be modified with offline subscription

### ISSUE THREAD

**Issue by SuppenGeist** [standardnotes/forum#3285]
**Describe the bug**
I cannot change the preferences of a single tag (i.e. enabling the daily notebook) even though I have an offline subscription key. I can use every other premium feature just fine.

I suppose that me having an offline subscription is the issue here as otherwise this bug might have already surfaced?

**To Reproduce**
1. Have an offline subscription?
2. Go to the per-tag preferences of any tag
3. Dont be able to change them

**Screenshot**
![image](https://github.com/standardnotes/forum/assets/10869751/2923dbad-11e7-4c5a-9ae9-1fb40bed1391)

**Expected behavior**
I should be able to modify the per-tag preferences with an offline subscription.

**Additional context**
It does not work across all devices.

**Comment by effieeee** [comment]
Hi @SuppenGeist, I've noted other reports of this as well, but I'm afraid we haven't been able to replicate this successfully so far. May I ask you to send us an email at help@standardnotes.com with the email address you used when purchasing your key? I'll continue assisting you with this issue over email as well, so I'll be closing this for now 🙏
