### ISSUE TITLE
Long loading times on startup

### ISSUE THREAD

**Issue by SuppenGeist** [standardnotes/forum#3287]
**Describe the bug**
I had >2000 notes of which are quite a few spreadsheets. Startup of the app is taking too long. Like ~7sec on mobile. Just taking a quick note is not possible anymore.
I have deleted many of my old notes to increase startup time but I dont think that I should be forced into doing this.
What is most important to me at startup is that all tags are available immediatly. That >2000 notes take their time to be read into memory is clear but the tags should be available immediatly.

**To Reproduce**
1. Have many notes
2. Open the app

**Expected behavior**
I want to be able to quickly select a tag. Not waiting like 7seconds for them to be completly loaded.

**Additional context**
In the desktop app this is no issue. 
The web version is also slow because everything has to be downloaded but it is not as much of an issue there as i do not open the web version to take a quick note. If im at the pc i have time.
The mobile version is where this hits me hard. I want to quickly select a tag and add a note. Or open an existing note.

**Comment by effieeee** [comment]
Hi @SuppenGeist, unfortunately it's known that users with note databases in the thousands will start to experience some delays with loading and decrypting time on mobile, and I'm afraid we have no quick workarounds for this at the moment. Are a number of your notes perhaps **trashed** notes which haven't yet been deleted? Perhaps you can delete the notes in the trash to help speed up the loading time on mobile?

**Comment by SuppenGeist** [comment]
Hi, I'm fine with this issue as long as you know about it. I'm already back to a bearable loading time. But again, my suggestion would be that the tags are loaded first and the notes that belong to the selected tag are loaded with priority. This should at least be technically possible and would solve the issue in my opinion.
