### ISSUE TITLE
Spreadsheets - adding European Union Formats

### ISSUE THREAD

**Issue by Mappi75** [standardnotes/forum#3288]
Hello all, my first time on GitHub.

Is there a way to include European formatting in the spreadsheets for payments and currencies?
This feature is significant for me (and members of the EU I think too).

Instead of 620.00 it is 620,00 in the EU (Germany).
or instead of $0.00 it is €0.00

1024.00 = 1024,00 or much better = 1.024,00
$1000.00 = €1000.00 or better: €1.000,00
USD 1000.00 = EUR 1000.00 or EUR 1.000,00
$1000 = €1000 or €1.000 

Date adjustments would also be nice, but the correct formatting of numbers and currencies is most important.
Thank you.

**Comment by effieeee** [comment]
Hi @Mappi75, unfortunately other currency formats are currently not supported on the official [Kendo UI Spreadsheets](https://demos.telerik.com/kendo-ui/spreadsheet/index) demo either, so I'm afraid this isn't something that we can directly implement ourselves. Should there be an update on their end which adds support for European currencies though, we can certainly update our copy of the extension as well 🙏

**Comment by simetriarota** [comment]
@effieeee I really need this too. Following your Kendo UI link, they seem to support it now, no?
https://docs.telerik.com/kendo-ui/knowledge-base/show-different-currencies-in-the-grid
