### ISSUE TITLE
If during installation you see the issue "Windows cannot access the specified device, path or file"...

### ISSUE THREAD

**Issue by moughxyz** [standardnotes/forum#329]
Please try this: https://support.microsoft.com/en-us/help/2669244/windows-cannot-access-the-specified-device-path-or-file-error-when-you

**Comment by mobitar** [comment]
A user in a restrictive environment also commented that he was able to install the app after some difficulty by running the installer in compatibility mode with the following settings:

- Window compatibility mode: Windows XP (Service Pack 3)
- User Account Control: Run as administrator

**Comment by Kassia666** [comment]
Firstly, check if you have the permission of the file or folder when Windows cannot access the specified path windows 10. 
then you can try to enable the Hidden Administrator Account and ensure the file is unblocked.
If it doesn't work, you can try to recreate the Shortcut File.
Hope it's helpful to you.
