### ISSUE TITLE
[Help Wanted] Google Keep files import fails

### ISSUE THREAD

**Issue by tiloyi** [standardnotes/forum#3293]
**Describe the issue**
Hello :wave:,
I recently discovered **Standard Notes** and I'm looking to migrate my notes from **Google Keep** to **Standard Notes**.

I'm encountering a problem when importing certain notes, the interface tells me via the red icon that the import of this file has failed _(see screenshot)_.
However, I have no explanation as to why the import failed :sob:.

So I wanted to know if there were any logs that would help me understand why the import failed? 
If so, where can I find them?

If there are no logs, how can I find out why the import failed? 
And is there a guideline for properly formatting HTML files to avoid import failures?

**To Reproduce**
1. Follow the procedure described here, in the online webapp => https://standardnotes.com/help/35/how-can-i-import-my-notes-from-google-keep 
2. Import an HTML file like this => https://gist.github.com/tiloyi/ae629dd8074cadb9a043af1d864a9076
3. See the import fails

**Expected behavior**
I would like the import of this type of file to work.
Or if it doesn't, I'd like to know why the import failed.

**Screenshots**
![standard-notes-import-fails](https://github.com/standardnotes/forum/assets/6053330/a45cad0b-9d53-4ba7-87e4-446248d288f8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Google Chrome
 - Version: Version 117.0.5938.92

**Additional context**

**Comment by effieeee** [comment]
Hi @tiloyi, I'm sorry to hear about that, may I ask you to try importing the files just using the **HTML** option on the importer instead? This will also automatically assign them the **Super** note type, which is also capable of rendering HTML.

**Comment by MickaelFontes** [comment]
Hello!

I just started using Standard Notes and I also had some issues trying to import my Google Keep notes.

Like @tiloyi above, following the Standard Notes documentation: https://standardnotes.com/help/35/how-can-i-import-my-notes-from-google-keep
When I do as instructed and try to import a Google Keep HTML export (like [this one](https://gist.github.com/MickaelFontes/cb45e0670d024fc4df2f4ab3de762b78)), I encounter this error:

![image](https://github.com/standardnotes/forum/assets/81414455/55242d35-504a-481d-ba95-8175a3744921)

However, I noticed that if I do not follow the instructions of the documentation and try to import the JSON exports, it works! (even though JSON exports may not contain all content of a note like pictures and formatting, but I'm okay with that - I do not have Super Notes for now).

**Additional content**

I do not have a Standard Notes subscription for now, I hope my issues are not linked to that.

I noticed too late that there was this working tool for Google Keep import (https://standardnotes.com/tools - I tried it after with no problem!), but it was not mentioned in the documentation dedicated to Google Keep imports, it may help others to mention it maybe.

And the basic HTML import what not effective for Google Keep notes unfortunately.

**Comment by effieeee** [comment]
Hi @MickaelFontes, apologies for the trouble, a fix for this was pushed recently, so you can try using your HTML files on the Google Keep import option now, and the import should proceed 🙏

**Comment by MickaelFontes** [comment]
Hi @effieeee, indeed in works perfectly now with the HTMLs now!
Thank you very much for your help 🙏!

**Comment by tiloyi** [comment]
Hi @effieeee ,
My apologies for the very late reply. I'd forgotten that I'd opened an issue here 🤭.

Thanks to @MickaelFontes  for tagging me to remind me 👌.

I've tried again to re-import my files by following [the Google Keep import documentation](https://standardnotes.com/help/35/how-can-i-import-my-notes-from-google-keep). 
And I still have an error on several files 😭.

![import-standardnotes](https://github.com/standardnotes/forum/assets/6053330/91e1fceb-75a2-47c6-8dd7-c1085052d407)

**However**, when I import the files by **choosing the "HTML" option**, I have no problem and all my files are imported correctly! 🤩🎉

I'm finally going to be able to switch completely to **Standard Notes** and give up **Google Keep** for good.

Thanks a lot for your help and updates. 🙏
