### ISSUE TITLE
[Help Wanted] Confused about workspaces

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#3294]
**Describe the issue**
I am confused about how to use workspaces. Are they an organizational tool (as in, _can_ they all belong to the same account) or do I have to have multiple accounts with one account per workspace?

Thanks!

**Comment by effieeee** [comment]
Hi @tiddesk, the latter would be correct. Please see this help article as well for more info!

https://standardnotes.com/help/82/can-i-sign-into-multiple-accounts-at-the-same-time
