### ISSUE TITLE
Android 14 - Restore Keychain +  Storage error

### ISSUE THREAD

**Issue by gionn07** [standardnotes/forum#3298]
**Describe the bug**
After update my pixel 6 to android 14, I am unable to login in my phone.  Previously I had set the login using my fingerprint, but now I am receiving different types of error messages

**To Reproduce**
1. Open the app in Android phone
2. First Error Msg: 
![image](https://github.com/standardnotes/forum/assets/44218414/baa41e3c-fba5-42a9-8cf2-d6eff406825e)
3. After writing the passwd, the app ask again for input the passwd
4. Second Error Msg: 
![image](https://github.com/standardnotes/forum/assets/44218414/b87b27ab-f191-44f7-9999-e42571d62968)
5. Finally, a third error msg is received: 
![image](https://github.com/standardnotes/forum/assets/44218414/ccb4abfa-e9c2-4e58-a285-2c5d36d4c18d)

**Expected behavior**
Open the android app using my fingerprint.

**Screenshots**
Already shared

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: 14
- App Version 3.173.8

**Comment by effieeee** [comment]
Hi @gionn07, apologies for the trouble! A [fix](https://github.com/standardnotes/app/commit/632b06e511072a481258a9f2a8817f4651841cf1) for this has been pushed and will be out on an update for the Android app soon 🙏
