### ISSUE TITLE
Applmage opening in Text Editor on Ubuntu 18.04

### ISSUE THREAD

**Issue by Wolflair** [standardnotes/forum#331]
The first time I downloaded it I got the applmage file in the home directory and a applmage.part file in downloads. I've tried all the combinations of executable permissions and nothing.

How can I resolve this?

**Comment by mobitar** [comment]
Can you share what commands you're running? Also, try downloading the file again. Perhaps it was cut off or something? The .part file sounds unfamiliar to me.

**Comment by Wolflair** [comment]
The .part bit was actually evidence of a failed download. I've a bunch of failed downloads in Firefox and didn't realise it. Its working now that its downloaded properly!

Thanks.
