### ISSUE TITLE
[Help Wanted] GrapheneOS: Login only lasts one session, reauth results in local storage error, so reinstall

### ISSUE THREAD

**Issue by glidingthrough** [standardnotes/forum#3311]
I have been a happy StandardNotes user for a few years now, and ran into this issue about 2 or 3 weeks ago - only getting round to reporting it today as it's still there after recent updates.

**Describe the issue**
I open the app and it asks me to Restore Keychain; I enter my credentials and up pops 'Generating Keys' and a 'Storage Error' flashes onto the screen before it quickly jumps to another prompt asking me to enter my account password as it was when I registered.

Upon entering the password, I am greeted with what I think was the original 'Storage Error' which states: _"We were unable to decrypt your local storage. Please restart the app and try again. If you're unable to resolve this issue, and you have an account, you may try uninstalling the app then reinstalling, then sgining back into your account. Otherwise, please contact help@standardnotes.com for support."_

So I uninstall and reinstall, enter my credentials and all is well. Until, that is, I close the app and re-open it when the whole saga kicks off again.

**Expected behavior**
That StandardNotes remembers my credentials and is able to load my notes upon opening the app.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: Graphene OS, 2023101300, Android 14
 - Version: StandardNotes from F-Droid, version 3.167.25

**Comment by MichaelReineke** [comment]
**Update: It's back on F-Droid and 3.178.0 fixes this problem, but the developer said he makes NO PROMISES he won't stealth-switch the software to a non-FOSS license again in the future... So I'd say jump ship now.**

I am experiencing the same problem, also Android 14 GrapheneOS, but I have a Pixel 7.

Seems updates were broken from F-Droid when they stopped being FOSS, so it's a big mess now even getting an update installed.  Switching to and from an F-Droid build requires uninstalling StandardNotes from all of your guest profiles on your device, and the non-FOSS 3.172-ish update I last tried didn't solve it.

**Comment by glidingthrough** [comment]
Thanks for fixing the issue 👍 I can confirm that it now works
