### ISSUE TITLE
[Help Wanted] No Bulleted List in Super Formatting Toolbar

### ISSUE THREAD

**Issue by jshireling** [standardnotes/forum#3314]
**Describe the issue**
The bulleted list option(s) seems to have disappeared from the formatting toolbar when editing a Super note.

**To Reproduce**
1. Open a note with a type of Super OR change the type of a pre-existing note to Super
2. No bulleted list option appears in the formatting toolbar

**Expected behavior**
bulleted list option appears in formatting toolbar

**Screenshots**
![image](https://github.com/standardnotes/forum/assets/46571736/906babfc-73c5-4886-aace-dd3465bd9da7)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise (22H2)
 
**Smartphone (please complete the following information):**
N/A

**Additional context**
I swear it was there before...

**Comment by effieeee** [comment]
Hi @jshireling, v3.178.18 changed the Super toolbar such that it now appears on top, and certain formatting options are grouped together in drop down menus. For bullet lists in particular, they are under the **Text style** group:

![image](https://github.com/standardnotes/forum/assets/54989748/f72462e5-6ac2-4762-a398-554476720956)
