### ISSUE TITLE
Black window at start on Ubuntu 22.04

### ISSUE THREAD

**Issue by lucamosca1** [standardnotes/forum#3315]
After reinstalling (in hurry) my Ubuntu 22.04.3 I reinstalled standard note via snap, but at first start a black small window appears. I suppose is the one regarding the choice to store password locally or not and tell the user about the command
snap connect standard-notes:password-manager-service
But the application seems stuck.
I restarted my Ubuntu session choosing xorg in login screen, the application works correctly and I was able to login

**Comment by effieeee** [comment]
Hi @lucamosca1 I see, thank you for raising this with us, though another update was released lately, so may I know if you still encounter this on a fresh install of the latest version?

**Comment by lucamosca1** [comment]
Tested today on a fresh installation on virtual machine, issue is not reproducible. awesome
Thx
