### ISSUE TITLE
Login is interrupted by biometrics prompt on iOS during PW entry from PW management app, making login impossible.

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#3316]
**Describe the bug**
While trying to use password manager, or switch to OTP app, during login to iOS app Standard Notes somehow "resets" to the biometric prompt, making it impossible to actually enter requested credentials.

**To Reproduce**

On iOS device with device key enabled, at a time when app is requesting resync with server:

1) Open SN
2) Biometric Prompt Given, enter
3) Application Password requested, use native password manager prompt to open password management app
4) PW management app prompts for biometrics, entered
5) Select Proper Application password in PW manager, it autofills in SN
6) Submit in SN
7) SN prompts for account email and password
8) again select native password manager prompt to enter email/pw combo
9) Again, PW management app prompts for biometrics, entered
10) Before PW management entry can be selected, _while_ in PW management app, SN prompt for biometrics for SN
11) Authenticating here returns to SN, but without being able to enter account email/password -> no syncing
11a) Cancelling here returns to SN, with application locked

There is no way to enter the account credentials

**Expected behavior**

As above, but at step 9, process is not interrupted by second SN prompt.

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 17

**Comment by effieeee** [comment]
Hi @tiddesk, are your biometrics and passcode prompt both set to be required **Immediately**? If so, this would explain why the biometrics prompt resets, since it will be required even if you switch out of the app for just a moment.

**Comment by tiddesk** [comment]
@effieeee That was, in fact, the case! And setting biometrics to "on quit" allowed me to login. However, if "immediately" can cause this loop, could we get an option that's shorter than "on [force] quit" but not quite "immediately"?
Thanks!

**Comment by effieeee** [comment]
We'll note it down as a feature suggestion, though as with other [feature requests](https://standardnotes.com/longevity), I'm afraid I can't make any guarantees about when it would be considered for development 🙏
