### ISSUE TITLE
Use Extensions but prevent syncing notes to cloud

### ISSUE THREAD

**Issue by threevi** [standardnotes/forum#332]
I'm wanting to use Standard Notes in an offline mode, specifically I don't want to sync the notes to the cloud, but I want to be able to have access to the Extensions I've enabled as a part of my Standard Notes subscription. My understanding is, in order to use Standard Notes in offline mode, you have to log out of Standard Notes and then continue to use the app. But, if I sign out, my Extensions are no longer available.

Is there a process for not syncing to the cloud but retaining my Extensions?

Thanks!

**Comment by mobitar** [comment]
Yes, this is definitely possible. Simply stay signed out, then [activate your Extensions](https://standardnotes.org/help/29/how-do-i-install-extensions-once-i-ve-signed-up-for-extended) with your Extended Activation code as usual. Whether you're signed in or out doesn't make a difference.
