### ISSUE TITLE
[Help Wanted] Potentially out of sync ?

### ISSUE THREAD

**Issue by steve02476** [standardnotes/forum#3322]
**Describe the issue**
Both my iPad and iPhone Standard Note apps say “potentially out of synch” in an orange font

**To Reproduce**
I just start the app and it says this. 

**Expected behavior**
I don’t want it to be potentially out of sync, of course. 

**Smartphone (please complete the following information):**
 - Device: iPhone13, iPad 7th gen
 - OS: iOS 17.0.3

**Additional context**
This has been showing for several versions.
It appears to actually be syncing ok, but not positive 
Have already tried restarting apps, and signing out and back in

**Comment by steve02476** [comment]
Just tried the web browser version - it also says Poentially Out of Sync. What’s the deal. Things look basically synced but I can’t trust this situation with that warning. Any ideas?

**Comment by effieeee** [comment]
Assisting via email!
