### ISSUE TITLE
shared between other standardnote user

### ISSUE THREAD

**Issue by whitetornado** [standardnotes/forum#333]
is it possible to share a  note (encrypted) with a other note user(s) ??
as a note is updated, other user can see the updated note etc.. etc..

**Comment by mobitar** [comment]
No, not presently. Not encrypted at least. You can use Listed to share unencrypted notes. Perhaps in the future Listed will be updated to support encrypted sharing.

**Comment by whitetornado** [comment]
ok,but can be customized? when yes, who can i contact for this??

**Comment by mobitar** [comment]
This doesn't exist yet. Just an idea.

**Comment by tmikaeld** [comment]
Any update on this? I get that we can list it, but can't it be encrypted using password that's unlocked on the client-side? This way we could collaborate somewhat.

My team is currently using Notejoy and are looking to switch.

**Comment by TheodoreChu** [comment]
Closing this because it's a duplicate of https://github.com/standardnotes/forum/issues/52
