### ISSUE TITLE
Dynamic Panels can't be disabled, no matter the status of the button

### ISSUE THREAD

**Issue by mzannoni** [standardnotes/forum#3332]
**Describe the bug**
I have the panels "stuck" on dynamic behavior: they resize automatically on mouse hoover.
The slider "Dynamic Panels" on the quick settings has no impact whatsoever.

**To Reproduce**
1. Open Standard Notes
2. Hoover over the panels, they resize automatically.
3. Open quick appearance settings (little palette), disable "Dynamic Panels" (if enabled)
4. No effect, the panels still autoresize

**Expected behavior**
Well, I expect the panels to stop autoresizing.

**Screenshots**
Screen recording:
![Standard_Notes_dyn_panel_bug_2023-11-06](https://github.com/standardnotes/forum/assets/29273478/1221a9d7-3c98-41cd-9663-278d154a0ffc)

**Desktop (please complete the following information):**
 - OS: Manjaro - KDE Plasma
 - Standard Notes: version 3.181.15 installed as flatpak

**Additional context**
I've also tried changing theme, including the default one. Same effect.

**Comment by effieeee** [comment]
Hi @mzannoni, may I ask if this also occurs when you use the AppImage from our [repository](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.181.23)? Please also take note that the flatpak is not officially maintained by anyone on the team 🙏

**Comment by mzannoni** [comment]
Hi @effieeee, thanks for your reply!

I've verified that this happens both on the `flatpak` and with official the AppImage, on 2 different machines with Manjaro. Also, this happens on one machine with Windows, with the official app for Windows.
Moreover, this also happens identically on the web app! I've tried in Linux with Brave (v1.60.114) and with Firefox (v119.0).

I don't know if it can be of any help, but I've also find (in the web app) that the "Dynamic Panels" button actually affects the "Action Bar". When the "Dynamic Panels" button is off, this is in the "Action Bar":
![image](https://github.com/standardnotes/forum/assets/29273478/8ead5459-95af-4e24-acbb-259d3c55841a)

In the desktop app (doesn't matter which, happens in all 5 I've mentioned above), when "Dynamic Panels" is on the "Action Bar" is grayed-out (not showing anything, colored dot is gray); when it is on, the "Action Bar" is as expected.

Please, let me know what I could do. I really (used to...) love StandardNotes, but since I see this issue it's getting often on my nerves... and it really seems I have no clue how to solve...

**Comment by mzannoni** [comment]
I think I've found a solution myself... by accident almost.
In the "Advanced Settings", in the "General" settings tab, I've uninstalled the "DynamicPanels" plugin.
After restarting the app, the dynamic panels now work as expected (when enabled/disabled), but the plugin is not there anymore (in the "Advanced Settings").
Does this makes sense? Should the plugin be there? Did I mess up more?
Now it seems to work... I wonder if my account has even more clutter that I should cleanup, maybe because I have the subscription since many version ago...

**Comment by effieeee** [comment]
Hi @mzannoni, it's good to hear that it was resolved somehow! Indeed, Dynamic Panels is a feature that no longer works like an external plugin, so you would not find it in the Advanced Settings menu anymore. Please also try to check if you see **Rich Text, Spreadsheets, Markdown, Checklist, Code, and Authenticator** in the same menu, and uninstall them if you do 🙏 These also no longer function like external plugins

**Comment by mzannoni** [comment]
Thanks for your help.
When you say to uninstall Markdown, do you mean just the one called exactly like that, or all the plugins that have "markdown" in the name?

**Comment by effieeee** [comment]
Just the one called exactly like that 👍 The remaining editors with "markdown" in their name *do* still function as external plugins

**Comment by mzannoni** [comment]
Thanks for all your help.
It seems solved for me now.

Maybe, one suggestion to solve it in general: you can add, in a future update, something that automatically checks for obsolete and potentially problematic plugins and offers to remove them. :wink:

**Comment by YavuzzzSelimmm** [comment]
> I think I've found a solution myself... by accident almost. In the "Advanced Settings", in the "General" settings tab, I've uninstalled the "DynamicPanels" plugin. After restarting the app, the dynamic panels now work as expected (when enabled/disabled), but the plugin is not there anymore (in the "Advanced Settings"). Does this makes sense? Should the plugin be there? Did I mess up more? Now it seems to work... I wonder if my account has even more clutter that I should cleanup, maybe because I have the subscription since many version ago...

Thanks a lot for this. I had the same issue as you (on macOS), and it was driving me nuts. I couldn't add a new note, because the `+` button was impossible to press as the panels kept resizing. 

Removing the application data in `/Users/<user>/Library/Application Support/Standard Notes` also didn't work. All settings were reloaded, including the annoying panel behaviour. 

I have uninstalled the "Dynamic" plugins via Preferences -> Plugins, enabled and disabled 'Dynamic Panels', quit the application in between, and it worked. I can now use Standard Notes again.

Thanks a lot!
