### ISSUE TITLE
Self hosting extensions 

### ISSUE THREAD

**Issue by arifcatalyst** [standardnotes/forum#334]
I am following this [https://docs.standardnotes.org/extensions/publishing](url) to self-host extensions but I am facing weird behavior.

This is the `json` file for Markdown editor hosted at [https://api.jsonbin.io/b/5bba71409353c37b743e1d61](url)
```
{
  "identifier": "org.yourdomain.my-markdown-editor",
  "name": "Simple Markdown Editor",
  "content_type": "SN|Component",
  "area": "editor-editor",
  "version": "1.1.6",
  "description": "A fully featured Markdown editor that supports live preview, a styling toolbar, and split pane support.",
  "url": "https://raw.githubusercontent.com/sn-extensions/simple-markdown-editor/master/dist/index.html",
  "download_url": "https://github.com/sn-extensions/simple-markdown-editor/archive/1.1.6.zip",
  "latest_url": "https://listed.standardnotes.org/my-extension-json-link",
  "marketing_url": "https://standardnotes.org/extensions/simple-markdown",
  "thumbnail_url": "https://domain.org/editors/adv-markdown.jpg"
}
```

This is the `json` file for **Focus Theme**hosted at [https://api.jsonbin.io/b/5bba71ba9353c37b743e1d95](url)

```
{
  "identifier": "org.yourdomain.my-markdown-editor",
  "name": "Focus theme",
  "content_type": "SN|Component",
  "area": "themes",
  "version": "1.1.0",
  "description": "A Focus theme.",
  "url": "https://raw.githubusercontent.com/sn-extensions/focus-theme/master/dist/dist.css",
  "download_url": "https://github.com/sn-extensions/focus-theme/archive/1.1.0.zip",
  "latest_url": "https://listed.standardnotes.org/my-extension-json-link",
  "marketing_url": "https://standardnotes.org/extensions/advanced-markdown",
  "thumbnail_url": "https://domain.org/editors/adv-markdown.jpg"
}
```

I can't get editor and themes to work concurently. Step to reproduce error -
1) Import the above editor using above link and use it as a default option.
2) Import the above theme using above link and activate it.
3) It will work fine, but the moment you change the editor or change to new theme, editor stops loading and theme doesn't apply.

**Comment by mobitar** [comment]
I don't think you'll be able to get themes to work through GitHub because dist.css is download with content-type text/plain and not CSS, which won't work.

**Comment by mobitar** [comment]
I thought you said the editor works?

**Comment by arifcatalyst** [comment]
> I don't think you'll be able to get themes to work through GitHub because dist.css is download with content-type text/plain and not CSS, which won't work.

Will it work via listed ?

**Comment by mobitar** [comment]
I'm not too sure tbh, haven't tried that..
