### ISSUE TITLE
Markdown Alternative editor disabled even with a SN Pro subscription

### ISSUE THREAD

**Issue by jaherron** [standardnotes/forum#3349]
**Describe the bug**
Even though I have an SN Pro subscription, the Markdown Alternative editor is disabled (it shows the asterisk saying a subscription is required). 

**To Reproduce**
1. Log in as a user who has a Standard Notes Professional subscription (I am a member of a shared subscription, maybe that has something to do with this)
2. Create a note and try to change its type
3. Markdown Alternative is disabled (shows the asterisk requiring a subscription upgrade even though I have the highest tier)

**Expected behavior**
The Markdown Alt editor should be enabled, as I have an SN Pro subscription.

**Screenshots**
![image](https://github.com/standardnotes/forum/assets/40708782/9848599e-7030-4780-a61d-dd2a25aefe5a)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma (14.0) on an M2 MacBook Air (13in)
 - Browser: Standard Notes App
 - Version: 3.181.23

**Additional context**
I also tried signing into SN on a Chromebook (Chrome OS 118.0.5993.124) and the same problem happened.

**Comment by effieeee** [comment]
Hi @jaherron, please see [this comment](https://github.com/standardnotes/forum/issues/3348#issuecomment-1817517988) on a related issue 🙏
