### ISSUE TITLE
Exporting Notes to Individual Text Files

### ISSUE THREAD

**Issue by kennethb22** [standardnotes/forum#335]
I know Standard Notes allows importing notes from individual text files, but is there a way to export selected notes or all notes as individual text files?

**Comment by mobitar** [comment]
You can do this with the Action Bar via the Save action.

**Comment by kennethb22** [comment]
I just remembered how I've done this in the past. Export an encrypted backup file, then use the offline decrypt script to save the notes to zipped text files. Yay!

**Comment by mobitar** [comment]
Or, just export your notes from the app using the Decrypted option. This will also download a zip of your notes in plaintext :)

**Comment by mobitar** [comment]
Btw, you can clear duplicates using the Batch Manager extension. Please see here: https://standardnotes.org/help/33/how-do-i-clear-duplicates
