### ISSUE TITLE
Listed: sizing of header image

### ISSUE THREAD

**Issue by alxtrnr** [standardnotes/forum#3351]
1. What length and width should the header image be in order to fit the container on the front page of my Listed blog?
2. Can the image be made to scale with the screen size such that the entire image is shown regardless of screen size used to view? 
3. Can you share example CSS to illustrate how to do 1 and 2?

I'm guessing it's a pretty simple answer. If you know you know. I don't. Thank you for any guidance given on this.

**Comment by effieeee** [comment]
Hi @alxtrnr, please check the help documentation below, under **Cover Style**, hopefully this will have what you need 🙏

https://standardnotes.com/help/66/how-do-i-change-the-colors-fonts-and-general-layout-of-my-listed-blog
