### ISSUE TITLE
Resetting Extensions, Etc - While retaining notes, files, etc?

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#3353]
I'm having some strange behaviour - for examples, I have two instances of Filesafe under "advanced" settings.

Is there a way I can simply reset all my extensions to the current default options without losing notes/files?

Thanks!

**Comment by effieeee** [comment]
Hi @tiddesk, you should be able to remove your extensions under the Advanced Settings without losing any notes or files. However, if you use any of the **community plugins**, please make sure to install them again using their install URLs in the repository below:

https://github.com/standardnotes/plugins
