### ISSUE TITLE
Can't create a tag/folder

### ISSUE THREAD

**Issue by eino** [standardnotes/forum#3354]
**Describe the bug**
I try to create folders (tags) but when pressing enter, nothing happens, the folder name just disappears

**To Reproduce**
1. Click on + next to Folders on the sidebar
2. Focus comes to the new folder name
3. Type a name
4. Press Enter
5. The name disappears, not clear if not folder or a folder with no name was created.
6. When trying to delete, app proposes to delete a tag ""
7. On refresh, the folder/tag has disappeared

**Expected behavior**
On pressing enter, the folder/tag is created with the expected name.

**Screenshots**

<img width="220" alt="Screenshot 2023-11-20 at 14 00 06" src="https://github.com/standardnotes/forum/assets/4985/efa46aff-189b-4149-8b16-451646fca51a">
<img width="215" alt="Screenshot 2023-11-20 at 14 00 12" src="https://github.com/standardnotes/forum/assets/4985/1633f2fb-cc44-48a0-99a1-ac949e0c081b">
<img width="221" alt="Screenshot 2023-11-20 at 14 00 19" src="https://github.com/standardnotes/forum/assets/4985/bd736f77-d1d6-4c24-bbc4-a6ae3ef84963">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version: Current webapp

Also same behavior on the native Mac app Version 3.181.27 (3.181.27)

**Comment by effieeee** [comment]
Hi @eino, that's odd, I haven't been able to reproduce this on Web or desktop so far. In case this might be related to your subscription, can I ask you to email us at help@standardnotes.com using your Standard Notes account email? I'll also continue assisting you from there!

**Comment by eino** [comment]
Hi @effieeee , actually I posted on discord in between and the issue was fixed in the latest release 👍 So I close with issue. Thanks !
