### ISSUE TITLE
Remove items checklist

### ISSUE THREAD

**Issue by rdemedrano** [standardnotes/forum#3356]
How can I remove items in cheklists notes? It seems like the only option is to mark it as completed and then removed completed items, but it does not make sense there is not an easier way.

This happens in both, android and windows app.

**Comment by effieeee** [comment]
Hi @rdemedrano, on the **Checklist** note type, if you completely delete the text on an item, and hit **Enter/Return**, this completely deletes the item on the checklist 👍
