### ISSUE TITLE
Preview FileSafe files in the extension

### ISSUE THREAD

**Issue by trevormeier** [standardnotes/forum#337]
It would be nice to be able to preview certain files (images, primarily) in the FileSafe extension area. It could be a "preview" button. This would save all the extra steps of having to download the file, choose a save location, locate the file and open it with another app.

Eventually I'd love to be able to link to attached images inline in Markdown notes so they appear during preview, but not sure how this functionality would work.

**Comment by mobitar** [comment]
Indeed, this would be nice. Will probably come in a future release.

**Comment by rstrube** [comment]
I'd also like to second this request.  I have to embed lots of images into my notes, and it's very painful to not have a thumbnail view of the images in the FileSafe browser.
Because the files are encrypted, it's also not possible to preview them on the cloud service itself (e.g. Google Drive).

**Comment by mobitar** [comment]
Files will be reworked completely in [v4](https://blog.standardnotes.org/being-a-quiet-software-company/). Our design specs do include file previews. But we haven't begun development yet so can't say for sure how it will actually turn out.

**Comment by effieeee** [comment]
Files now implemented, previews made possible for most files!
