### ISSUE TITLE
Incorrect align in super notes check lists

### ISSUE THREAD

**Issue by rdemedrano** [standardnotes/forum#3372]
Hi, it seems like checklists are not correctly centered when using super type notes. The text is above the center of the box. Similarly, when marked as completed, the line is almost at the same height than the box top, not centered respect to the text.

![imagen](https://github.com/standardnotes/forum/assets/47191134/33202836-1732-421b-8e79-cf732ace0449)

**Comment by effieeee** [comment]
Hi @rdemedrano, a fix for this is already live on the web app, and it should make its way to another update on the desktop and mobile apps soon 🙏
