### ISSUE TITLE
Suddenly I have multiple copies of all my notes after working on different platforms

### ISSUE THREAD

**Issue by Caldefredo** [standardnotes/forum#338]
Was comparing the Win10 intalled app vs the web app vs android app. Now I suddenly have 4 copies of each note. I plan on working on multiple platforms, which is why I'm interested in this app vs others.

**Comment by ryansytsma** [comment]
I have got this issue as well. It happened this afternoon after I modified a couple notes in the web interface and then later opened the windows app all of my notes duplicated.

**Comment by Caldefredo** [comment]
I also had the tag duplication.

**Comment by mobitar** [comment]
Sorry about this @Caldefredo and @ryansytsma. Duplication is to be expected as part of managing sync conflicts, but mass duplication is still an issue at large. Did any of the steps you took yesterday involve signing in on a new device?

**Comment by Caldefredo** [comment]
Yes, I signed into the windows, web, and android apps for the first time recently. I'm testing out how SN works on the various platforms I would use. Is sync going to be a problem with every new device I sign on with?

**Comment by ryansytsma** [comment]
I signed into my Android and Desktop app that caused the initial duplication of notes and tags. Today, I signed into the web interface at work on another computer and it quadrupled the duplicates.

**Comment by exitnode** [comment]
Same problem here. I left a Linux client open while working on another Linux client. On the Client I left open, I now have nearly all notes and tags two times.

**Comment by exitnode** [comment]
Another thing: Action bars are doubled, too. When I disable the action bar in the extensions manager, only one disapperas (please see screenshot).
![notes](https://user-images.githubusercontent.com/3391263/46718171-a6182500-cc6a-11e8-840e-14ffebe14062.png)

**Comment by exitnode** [comment]
This here also happens:

![notes2](https://user-images.githubusercontent.com/3391263/46718312-1d4db900-cc6b-11e8-88da-7ad7dd07f883.png)

**Comment by mobitar** [comment]
Right yeah, seems to be nondiscriminatory in what it duplicates, and that includes extensions. Sorry about that. Please use the Batch Manager to clear duplicates in an automated way. Still no leads I'm afraid as to what could be causing this, so we'll continue collecting clues on this thread. If there's anything else strange you noticed leading up to this, please feel free to share. Please also include your network connectivity health, app platform and version, and browser version if applicable.

**Comment by ryansytsma** [comment]
Well, this issue has completely demolished my database.

**Comment by kevinclevenger** [comment]
As a data point, I signed in via linux/vivaldi on desktop A, and the same from desktop B. After opening on two desktops I started seeing the duplicates when I next opened SN (AFAIK anyway).

**Comment by mobitar** [comment]
Can anyone comment as to how many notes and tags you have total? I'm trying to determine if this can be related to pagination on the server side.

**Comment by kevinclevenger** [comment]
Hard to say since they're all x3. I manually count 19 tags. When I initially connect to SN it first says 65 notes, then to 142, then 147 - which is odd because it's not x3.

**Comment by mobitar** [comment]
It looks like the issue may just turn out to be: if you press Sign In multiple times while signing in, this issue happens. Does anyone recall if they pressed sign in more than once, perhaps not noticing the loading status? It takes a couple seconds to generate your encryption keys. So perhaps one may have figured pressing it once didn't do anything, at which point they press it again.

**Comment by eb2sk** [comment]
Hi, two days ago I started to experience the same issues described in this thread and some prior one I found in forums. The first day all the notes doubled, then again; I see this based on daily back-up sizes which went from 1.1 MB to 2.2MB to 3.6MB, today I  finally noticed the issue and see four copies of everything, including notes, tags, extensions, failsafe keys. I used the suggested Batch manager to clean up notes; this worked fine. I manually erased the excessive tags and proliferating extensions but I can not clean the references to failsafe keys and multiplying files I uploaded to test the feature. I am sure I could just erase all uploaded files all and start from the scratch, but wanted to add a voice that the bug causing this is real. I started to use the StandardNotes heavily only about 2 weeks ago after some period of "beta-testing". In that time did use the browser app versions on two Macs, two W10 machines, possibly a standalone Mac application, and about two days ago accessed the notes for the first time using an Android App. Thanks for developing this product! Hope this gets resolved.

**Comment by mobitar** [comment]
@eb2sk sorry about the mess this has created. We're narrowing down on the source of the problem, and hope to have it finally fixed in the next release. We'll also need to update the Batch Manager to allow access to FileSafe items so duplicates can be cleared there. For now, and in your case, you'd probably need to download a decrypted backup of your items, then edit that backup file to remove the FileSafe duplicates. That is unless you can just wait for the next release. I'm hoping it will be in the end of next week.

**Comment by mobitar** [comment]
Desktop version 2.3.8 has been released that fixes this issue. It should not happen again. Sorry for the trouble everyone.
