### ISSUE TITLE
iOS: autocorrect removes formatting (bold, italic, underline) from autocorrected word

### ISSUE THREAD

**Issue by munkmode** [standardnotes/forum#3382]
**Describe the bug**
when typing in on iOS, if a word is mistyped and autocorrect corrects it, the formatting is removed from that word..

**To Reproduce**
1. enable bold, italic or underline.
2. purposely mistype a word so that autocorrect corrects it 
3. See that the autocorrected word has had the formatting removed.

**Expected behavior**
words that get autocorrected should stay formatted..

 - Device: [iPhone 13 Pro]
 - OS: [e.g. iOS 17.1.1]

**Screen recording:**

https://github.com/standardnotes/forum/assets/152205713/28f895c4-aa7a-4943-b8b4-4f674f309bb0

**Comment by effieeee** [comment]
This has been fixed on v3.184.5 🙏
