### ISSUE TITLE
Offline Decrypt Script - Export to Text Files - Path too long error

### ISSUE THREAD

**Issue by kennethb22** [standardnotes/forum#339]
When I run the offline decrypt script (Windows 10), I get a "path too long" error when the script encounters a note with a particularly long title. The scripts appends the note uuid to the end of the tile when creating the filename, which may contribute to the issue. Maybe offer an option in the offline decrypt script to not append the uuid to the filename when creating text files? Or add a path length check to the script and trim file names that would exceed the maximum path length? Thanks!

**Comment by mobitar** [comment]
Good point, will probably need to truncate the title.
