### ISSUE TITLE
[Help Wanted] Downgrade 

### ISSUE THREAD

**Issue by Switch2dis** [standardnotes/forum#3391]
Hi everyone, it's my first time around, so bear with me if I'm a bit awkward in approaching this place. :-)

I am interested in upgrading to a paid version of Standard Notes but, before doing it, I'd like to know what happens to the contents created using premium features, if I were to downgrade again next year or later.

In case of formatting, the idea of losing the formatted aspect of the text might still be acceptable in most cases.

But what happens with checklists, or spreadsheets, or similar, created during the premium period?
Do they get cancelled?
Do they simply freeze into unmodifiable notes?
Anyone knows?

Thanks to anyone who wants to help.

**Comment by PASSK3YS** [comment]
Check out this help article on the website: https://standardnotes.com/help/20/what-happens-to-my-data-when-my-subscription-expires
