### ISSUE TITLE
Slow app startup time after update on win10

### ISSUE THREAD

**Issue by biophi** [standardnotes/forum#3398]
**Describe the bug**
After updating to v3.183.9 the app takes more than 20 sec to launch.
I don't think it's related to #3287 because I only have 500 notes and I've never experienced similar issues.
I also tried to have the app minimize to the icon/system tray on close, however even in this way the waiting time remains the same.
When the app is open it works properly, the issue occurs only on startup.

**Expected behavior**
Quick start-up time.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - App: v3.183.9

**Comment by rokfish2** [comment]
Hi biophi
I have Windows 10 Pro 22H2 and installed the latest SN v3.183.9 and do not have a slow startup.
I have 620 notes. Though they are pretty simple notes, mostly less than a page. No pics or attachments either,

**Comment by biophi** [comment]
I also have only plain text notes.
I also noticed that if I click on the icon/system tray the app opens smoothly, when instead if I click on the desktop icon SN.exe it takes ages to launch.

**Comment by effieeee** [comment]
Hi @biophi, can I ask you to try a clean install of v3.183.21? You'll have to follow the [uninstallation instructions](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes) first, then you can download and install this newer version from our website's homepage.

**Comment by biophi** [comment]
Hi @effieeee, I followed your advice and the startup time improved a lot. Thank you!
