### ISSUE TITLE
Phone: Black screen upon launch

### ISSUE THREAD

**Issue by LittleBenjiBoy** [standardnotes/forum#3406]
**Describe the bug**
Black screen on launch.

**To Reproduce**
1. Open StandardNotes app.
2. See black screen immediately. 

**Expected behavior**
White/dark screen about signing in to the application. 

**Screenshots**
![Screenshot_20231109-154802_Settings](https://github.com/standardnotes/forum/assets/43734617/2280ddda-0086-4da1-b866-fd2134858274)
![Screenshot_20231109-154900_Standard Notes](https://github.com/standardnotes/forum/assets/43734617/e935cce3-4c1c-4469-ad74-70f8762ade73)
![Screenshot_20231109-154918_Standard Notes](https://github.com/standardnotes/forum/assets/43734617/54470230-d0e8-4616-9d51-168a63a22926)
![Screenshot_20231109-154941_Settings](https://github.com/standardnotes/forum/assets/43734617/196b817a-6809-4a19-9dfa-9025d933d656)
![Screenshot_20231109-154753_Standard Notes](https://github.com/standardnotes/forum/assets/43734617/77af02f7-88a5-4796-93ae-aeb3d1dbc4e9)

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS: Android 10
 - Browser Chrome
 - Version 96

**Additional context**
An older version of the app, version 3.132.2, worked without issues. Any version around and above 3.181.17 contains this bug. In this version, 3.181.17, the login screen appears for just a moment and then a black screen appears, covering the login page. I have tried and tested versions above 3.181.17, and still get the issue. I have tried the APK version, and have since downgraded to version 3.132.2 to continue using the app on my phone.

**Comment by effieeee** [comment]
Hi @LittleBenjiBoy, I noticed that you've tried clearing the app cache so far in the app settings, but can I also ask you to try using the **clear data** option as well, then relaunch the app immediately? This ensures that the app restarts from its true default state.
![image](https://github.com/standardnotes/forum/assets/54989748/db05ac4a-2a27-46d0-9e3c-7451327177f6)

**Comment by LittleBenjiBoy** [comment]
> Hi @LittleBenjiBoy, I noticed that you've tried clearing the app cache so far in the app settings, but can I also ask you to try using the **clear data** option as well, then relaunch the app immediately? This ensures that the app restarts from its true default state. ![image](https://private-user-images.githubusercontent.com/54989748/290246132-db05ac4a-2a27-46d0-9e3c-7451327177f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2ODkzNTMsIm5iZiI6MTcwMjY4OTA1MywicGF0aCI6Ii81NDk4OTc0OC8yOTAyNDYxMzItZGIwNWFjNGEtMmEyNy00NmQwLTllM2MtNzQ1MTMyNzE3N2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDAxMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YjAzZmQwYTcxMzk5NWM1MjEwZjgzNGJiMmM1MWM5NDYyZmUyYTRiYjdjNGE1NzZjNjZlNDg3MjRmYmI1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uDDvL7qs3a5qdpmrMJkBBKE8VbdGq3p-6vzpNfGxnI)

I have tried clearing the app data, but still get the issue. Thank you.

**Comment by effieeee** [comment]
I see, thank you for trying this out as well. I also noticed that your app version is fairly old, as the newest one available is v3.183.15. Does the issue also occur after updating to this version?

**Comment by LittleBenjiBoy** [comment]
> I see, thank you for trying this out as well. I also noticed that your app version is fairly old, as the newest one available is v3.183.15. Does the issue also occur after updating to this version?

Yes, I see this to be a reoccurring issue for more recent versions of the app, a while after I haven't updated Standard Notes. I am referring to version 3.132.2, which I had kept for a while. Yes, I have tried again with version 3.183.15, and still get this immediate black screen that appears milliseconds after the login/default screen appears.

**Comment by LittleBenjiBoy** [comment]
I also get this black screen bug with my second Android phone. It is an LG G7 ThinQ running Android 9.

**Comment by effieeee** [comment]
I see, how about your [Android System Webview](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US), have you also checked if it's updated? This sometimes causes display issues when it hasn't been updated in a while.

**Comment by LittleBenjiBoy** [comment]
> I see, how about your [Android System Webview](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US), have you also checked if it's updated? This sometimes causes display issues when it hasn't been updated in a while.

Hi Effie,
You got the issue! Thank you! Updating it solved the issue. It was at version 81.0.4044.138, and I updated to version 120.0.6099.43.

**Comment by LittleBenjiBoy** [comment]
I just don't know how to solve it for my other Android LG G7 ThinQ because Android System WebView is disabled and cannot be enabled. I assume that the WebView is inside Chrome after some research and can be solved after an update on Chrome. I will keep you posted to see if that solves the issue.

**Comment by LittleBenjiBoy** [comment]
Yes, updating Google Chrome has solved the issue. I will close the issue as updating Android System WebView solved the issue.

**Comment by Bits-Bytes-354** [comment]
I have the latest Google Chrome and Android Webview version installed but facing the the same issue of black screen
