### ISSUE TITLE
Error Skia shader compilation error and GL_NV_shader_noperspective_interpolation extension: require

### ISSUE THREAD

**Issue by Sylvain-27** [standardnotes/forum#3410]
Hi,
After running for a day, the AppImage displays a completely white screen.
Launched in console mode, to make a long story short, I got the error
`ERROR:shared_context_state.cc(98)] `
and the error
`GL_NV_shader_noperspective_interpolation extension: require`
`
I just updated to version 183.22.
I'm on Opensuse Tumbleweed.

Can you help me ?

**Comment by effieeee** [comment]
Hi @Sylvain-27, I'm not quite sure, but can you check if the advice in the link below might help in this case?
https://support.google.com/chrome/thread/217542144?hl=en&msgid=217558650

**Comment by Sylvain-27** [comment]
Thank you for your reply.
Indeed, I use Brave and the hardware acceleration was deactivated since installation since this option posed a stability problem. Action taken since the option began to appear in the settings.
This is also a recurring question and answer on the Brave forum.

**Comment by Sylvain-27** [comment]
Hi,
What worked in my case was clearing the Standardnotes configuration folder in /home/user/.config/
The graphical interface was displayed normally when the app was restarted.
