### ISSUE TITLE
Table added in Plus Editor almost invisible with Titanium theme.

### ISSUE THREAD

**Issue by mxng** [standardnotes/forum#342]
![image](https://user-images.githubusercontent.com/11084577/46707562-fb553600-cc6c-11e8-9c08-2103def6b284.png)
![2018-10-10 09_14_48-window](https://user-images.githubusercontent.com/11084577/46707578-0b6d1580-cc6d-11e8-99ee-c782a5fe8f7c.png)
The table's colour is not changed in Titanium theme (second image), making it blend in with the background.
It is visible in other themes like Midnight (first image).

**Comment by mobitar** [comment]
Good catch, thanks, will investigate this.

**Comment by Poecilia** [comment]
Hi, I've uninstalled and reinstalled Titanium, but the invisible table issue is not fixed.

**Comment by nauxnim** [comment]
Oh my it's true. It's barely visible to the naked eye.

**Comment by mobitar** [comment]
Sorry about that, this should now be fixed. Please update your Plus Editor on desktop via the Extensions menu and clear your cache on web if necessary to see the latest result.

**Comment by nauxnim** [comment]
Should I close this issue, or keep it open?

**Comment by mobitar** [comment]
Open/close doesn't really matter on the forum :)

**Comment by nauxnim** [comment]
Ah okay ^^
