### ISSUE TITLE
Unable to setup any Super note type

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#3420]
Unable to change note type to Super. 

Error message: Something went wrong rendering this component: Unexpected end of JSON input

Apple desktop M2 silicon running Sonoma 14.1.2. No such issue on iOS.

![Screenshot 2023-12-23 at 17 31 36](https://github.com/standardnotes/forum/assets/154695876/633d7a1d-9c75-4439-a447-2b9cf7c3daae)

**Comment by effieeee** [comment]
Hi @jpwuk19, this has been fixed in v3.183.29, as mentioned [here](https://github.com/standardnotes/forum/issues/2318#issuecomment-1868298105) 🙏
