### ISSUE TITLE
Unable to Start Upload Session

### ISSUE THREAD

**Issue by epoxi1** [standardnotes/forum#3422]
Upon clicking **save image to files** under a linked image in a supernote, on Windows 10 Deskop App, I get these two error messages and the image fails to upload. 

Unable to start upload session
There was an error while uploading the file

<img width="401" alt="Untitled" src="https://github.com/standardnotes/forum/assets/61057799/38573091-1a22-426e-a356-c9f90749be20">

The experimental 'Moments' feature on the Android mobile app also does not work and produced the same pair of error messages. 

I am a subscribed SN user not a self-hosted user FYI.

**Comment by effieeee** [comment]
Hi @epoxi1, we may need to continue troubleshooting this via email, so can I ask you to contact us at help@standardnotes.com using your Standard Notes account email address? I’ll close this for now, as I’ll continue assisting you via email 🙏
