### ISSUE TITLE
On web, scrollbars appearing causing slightly push contents to the left

### ISSUE THREAD

**Issue by jrcacd** [standardnotes/forum#3427]
On the web, when you hover the mouse over the left panel or the notes panel, scroll bars appear. Since there is enough horizontal space to fully display scroll bars, they should not push content slightly to the left when appearing. This causes visual friction.

**Comment by IceFire23** [comment]
This happens on the desktop app as well, it is very jarring. I am currently seeing it on version 3.183.22, but I have seen it for weeks.

**Comment by quartertone** [comment]
The text-wrapping==line break==note list shifting issue happens at the note title, and the date/time stamp. It looks like the preview text ellipsis is adjusted when the column width changes, so the preview text does not contribute to the problem. But the resulting effect is extremely uncomfortable.

Possible solutions:
- Allow custom date display format (but this doesn't solve the shifting titles situation)
- Allow "always visible" scroll bar - I think this is preferrable. it would allow you to see where in your note list you are, without having to mouse hover.
