### ISSUE TITLE
Tags in the left panel are listed multiple times

### ISSUE THREAD

**Issue by kevinclevenger** [standardnotes/forum#343]
This started yesterday 2018-10-09 as far as I know. Screenshot attached.

![sn](https://user-images.githubusercontent.com/484148/46773549-6cd4c900-cced-11e8-9e1d-012e12c9466f.png)

**Comment by mobitar** [comment]
Seems to be related to this: https://github.com/standardnotes/forum/issues/338

If you have any more details on the steps you recall taking immediately preceding this, please sure, as it can help guide us towards the right place.

**Comment by kevinclevenger** [comment]
I updated #338, we can close this
