### ISSUE TITLE
bug:  please upgrade your plan

### ISSUE THREAD

**Issue by few4i** [standardnotes/forum#3433]
**Describe the bug**

Standard notes is not detecting my subscription.  Under account it shows "professional" & the proper renewal date.  But note types like super, spreadsheet and authenticator have a message at top ...

Please upgrade your plan to access Authenticator
Authenticator is in read-only state.
Manage subscription

**To Reproduce**

Open notes and go to a note type like authenticator.

**Expected behavior**

Properly detect subscription

**Screenshots**

I can submit these if helpful

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser:  Chrome
 - Version [e.g. 22]  120.0.6099.130 (official build) (32 bit)

**Smartphone (please complete the following information):**

**Additional context**

Tried signing out & back in.

**Comment by effieeee** [comment]
Assisting via email 🙏

**Comment by adoreparler** [comment]
I am having this same issue

OS: MacOS ARM
Desktop App Version: 3.199.0

I am getting "Please upgrade to Super" even though my subscription is correct and shows up under settings
