### ISSUE TITLE
[bug] The tag sidebar becomes jumpy when cursor moves across the scrollbar in a certain manner

### ISSUE THREAD

**Issue by nauxnim** [standardnotes/forum#344]
Found a problem with the tags jumping up and down.
To reproduce:
1. open lots of tag or have lots of tag so a scrollbar is needed to see all tags.
2. scroll down a bit so you're not at the top of the tag sidebar.
3. move cursor from tag sidebar to the notes area, with a bit of an upward motion when cursor is at the scrollbar for the tag sidebar.

This happens every time the cursor moves up a bit when still moving from the tag to the notes list.

[Video of the bug](https://gfycat.com/DecisiveFlamboyantGermanwirehairedpointer)

**Comment by mobitar** [comment]
Hmm strange. On hover, it should do this, on Windows, as Windows does not provide any elegant way of managing the scrollbar. However, the behavior of it automatically jumping back and forth without any user action is strange. So after some point, it just stays in that repeating state without you having to do anything?
