### ISSUE TITLE
Strange formatting of old notes after updating.[Help Wanted]

### ISSUE THREAD

**Issue by harrisondesbrosses** [standardnotes/forum#3445]
Hi! Apologies in advance for my inexperience with programming languages. Recently, I started to experience formatting issues with older notes of mine. I'm thinking it might have something to do with me removing a plugin or installing an update. I've attached a screenshot showing what a large number of my older notes look like. Obviously, I can manually salvage these notes as needed but I'm hoping that there is a way to bulk correct them.

I'm not sure how to reproduce the issue I'm experiencing.

I expect the notes to be free of this formatting that shows remnants of what I believe to be programming languages.

See attached. 
<img width="649" alt="Screenshot 2024-01-07 at 13 24 16" src="https://github.com/standardnotes/forum/assets/22471894/09f30f4c-a01a-47e8-a17b-6429e43b78f5">

Desktop
 - 14.2.1 (23C71)
 - Version 3.183.43

**Comment by effieeee** [comment]
Hi @harrisondesbrosses, it looks like this note was formatted with the **Rich Text** plugin. If your other notes also have similar formatting markup on them, can you try selecting them on the app, then switch the note type to **Rich Text** as shown below?
![image](https://github.com/standardnotes/forum/assets/54989748/d391d235-5899-4112-bd5d-3f20392efbc8)

**Comment by harrisondesbrosses** [comment]
That worked, thank you!
