### ISSUE TITLE
[Feature Request] Password Protect individual notes

### ISSUE THREAD

**Issue by nukercharlie** [standardnotes/forum#345]
IMO, the only feature missing on Standard Notes that keeps it from being the best note taking app ever.

I use ColorNote on Android just for this feature - they have the "Editor's Choice" tag on Google Play but are vastly inferior to Standard Notes in all other features and general usability!

Even if you want to implement it as an Extended only feature, please enable it! <3

**Comment by mobitar** [comment]
I agree this would be cool. Has been on my mind as well :)

**Comment by TheodoreChu** [comment]
I'm closing this because we can Password Protect individual notes on the latest versions of the app (v3.5+): https://standardnotes.org/help/54/what-does-it-mean-to-lock-or-protect-a-note. Please comment or re-open an issue if you have further issues
