### ISSUE TITLE
[Help Wanted] Preview HTML files

### ISSUE THREAD

**Issue by neurokrish** [standardnotes/forum#3458]
Moved to Standard notes recently. I have HTML files generated from various websites using the SingleFile chrome extension. In Obsidian, there is a HTML renderer for SingleFile, so when I click on the attached file, the page renders. I am unable to do this in Standard notes. When I click on the HTML file, it says that I have to open it externally. Is there a plugin to render these files?

Thanks.

**Comment by effieeee** [comment]
Unfortunately the app does not have an equivalent feature that instantly previews HTML web pages. We do have a [clipper extension](https://standardnotes.com/help/usage/how-do-i-clip-web-pages) that allows you to clip an entire web page to a note, though the results may vary depending on the content of the web pages.  🙏
