### ISSUE TITLE
I just bought Standard Notes.    

### ISSUE THREAD

**Issue by Steve01351** [standardnotes/forum#3459]
I paid - I verified my email - I gave a shipping address - no new features are enabled.
I've restarted my PC.  I've restarted my phone.  No matter how many times I've restarted no new features are enabled.  I just get the message UPGRADE

**Desktop (please complete the following information):**
 Windows 11 Pro
Browser - Microsoft Edge
Version 120.0.2210.144 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Galaxy S23 Ultra
 - OS: Latest Android
 - Browser - I don't use a browser on my phone
 - 

**Additional context**

**Comment by effieeee** [comment]
Hi @Steve01351, I'm sorry to hear about that. Please send us an email using your **Standard Notes account email**, and please provide your purchase invoice if you received one 🙏 I'll continue assisting you over email as well.
