### ISSUE TITLE
security: app occasionally loses passcode lock

### ISSUE THREAD

**Issue by klipspringr** [standardnotes/forum#3463]
**Describe the bug**
Today I opened Standard Notes and realised it had not prompted me for a passcode. In settings, passcode lock had been disabled. I am sure I did not change this myself. This is a serious security problem, my notes were accessible to anyone using my computer. I believe this has happened before. There was no explicit alert, so it is very easy to miss the change and assume notes are still protected.

Possibly the passcode was lost in an automatic upgrade? Or perhaps I had signed out and back in? Every now and then the app has a sync problem and forces me to sign in again - if it is intended behaviour that this removes the passcode, then the user should be prompted to recreate it as it is not obvious/intuitive that one has to do this.

**Expected behavior**
Passcode lock is never disabled without an explicit user instruction to do so.
Signing out and in does not disable the passcode.
Automatic upgrades never disable the passcode.

**Desktop (please complete the following information):**
- app version: 3.184.0
- OS: Windows 10 22H2

**Additional context**

**Comment by effieeee** [comment]
Hi @klipspringr, I'm sorry to hear about this. You did also mention that the app had been experiencing sync problems, so we may need to do some troubleshooting on your account as well. Can I ask you to email us at help@standardnotes.com using your account email? I'll also continue assisting you from there 🙏
