### ISSUE TITLE
no longer possible to type question mark in note

### ISSUE THREAD

**Issue by rnicholas** [standardnotes/forum#3464]
Version 3.187.0 introduces a new "keyboard shortcuts help dialog" feature that is invoked by typing Shift+?. Unfortunately, this means it is no longer possible to type a question mark within a note!

I have reproduced this behavior in the macOS desktop app and in the web app via Google Chrome (macOS, Chrome OS), both with standard US keyboard layouts.

**Comment by stolzlos** [comment]
confirmed with Google Chrome (Windows) and German keyboard layout

**Comment by jboykin-bread** [comment]
confirmed on native macOS app as well with standard US keyboard layout

**Comment by PeterJohnKimatarle** [comment]
Very annoying, i can no longer type a question mark on my laptop keyboard (US layout), instead keyboard shortcuts pops up. Please fix this.

**Comment by amanharwara** [comment]
Just pushed a fix for this, where the shortcut for the popup has been changed to `Ctrl + /`. That will be live soon. Until then, please revert to the previous version. Sorry for the inconvenience.
