### ISSUE TITLE
Disable the Adding of Tags Above the Current Subtag

### ISSUE THREAD

**Issue by LittleBenjiBoy** [standardnotes/forum#3468]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes. It is a very funny Longevity Statement.

**Is your feature request related to a problem? Please describe.**
When I create a new note under a subtag (sometimes with more than one tag above the current subtag), it tags the note with all the tags above the subtag. With this type of behavior, I feel like if my notes collection becomes super big under a subtag, it will dominate the folder/primary tag and I won't be able to easily find my other notes, the minority. It will get a bit disorganized with this type of tagging behavior. When tagging a note, I always prefer one tag attached to the note. Based on the way I organize my notes with tags, notes will contain many tags, in which it becomes overwhelming.

**Describe the solution you'd like**
Create an option or setting to enable or disable the auto-adding of tags above a subtag (subtag meaning, a tag with the lowest rank in the hierarchy of tags) when creating a new note under a specific tag.

**Describe alternatives you've considered**
I have considered not creating any subtags, but this will make my notes viewing more complex. Everything will be sorted in terms of alphabetical order, with my tags not having any type of hierarchy.

**Additional context**
![image](https://github.com/standardnotes/forum/assets/43734617/00a898d1-d764-40f9-bb36-7b1640115b16)
This is the type of complex tag hierarchy that I have to easily organize all my notes with tags. 

I have used Joplin, the popular note-taking software, and I prefer their system of organizing notes better. I only use Standard Notes because it has a web interface: I can use Standard Notes on the browser. If Joplin had browser support, I would be using Joplin over Standard Notes.

**Comment by effieeee** [comment]
Hi @LittleBenjiBoy, you can actually disable the parent tagging behavior under **Preferences > General** 🙏

![image](https://github.com/standardnotes/forum/assets/54989748/1f211402-d10b-4d5b-bc2c-34010178bbde)
