### ISSUE TITLE
Add Ability to Multi-Select Files

### ISSUE THREAD

**Issue by LittleBenjiBoy** [standardnotes/forum#3469]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes.

**Is your feature request related to a problem? Please describe.**
I am worried that if I have many files uploaded to Standard Notes, I won't have any more storage to store my files.

**Describe the solution you'd like**
I would like Standard Notes to have the feature of being able to select multiple files already uploaded to Standard Notes through the "Files" section of the app.

**Describe alternatives you've considered**
There are 2 solutions available. To delete the entire note containing the multiple files uploaded or to delete the files uploaded one by one.

**Additional context**
If Standard Notes provides the ability to upload files, I expect them to make the files uploaded easy to manage.

**Comment by effieeee** [comment]
Hi @LittleBenjiBoy, this is actually already possible on the latest versions of the app, may I know what device or app platform you're using at the moment, where you're not able to select multiple files?

**Comment by LittleBenjiBoy** [comment]
> Hi @LittleBenjiBoy, this is actually already possible on the latest versions of the app, may I know what device or app platform you're using at the moment, where you're not able to select multiple files?

Hi @effieeee, I have tried on most platforms. I have tried to select multiple files on Android, Desktop, and Web.

Thank you,
Benjamin

**Comment by LittleBenjiBoy** [comment]
> Hi @LittleBenjiBoy, this is actually already possible on the latest versions of the app, may I know what device or app platform you're using at the moment, where you're not able to select multiple files?

Hello @effieeee, I have discovered that I can `Ctrl + Click` files to multi-select them. So, nevermind my issue. I will close this issue.
