### ISSUE TITLE
Markdown notes do not display if there is no internet connection

### ISSUE THREAD

**Issue by spookfish** [standardnotes/forum#348]
Issue:

If there is no internet connection, then markdown notes do not display. instead it just displays a blank page. 

plain text notes display correctly.

issue occurs on both android 8.1.0 and macOS 10.14

standard notes app version 2.3.7

I am using the desktop app on macOs.

To Reproduce:

- create and save a markdown note which uses the simple-markdown editor.
- close standard notes
- disable internet connection
- start standard notes
- click on markdown note

Observed Behaviour:

the editor just displays a blank page.

Expected Behaviour:

the note to be displayed using simple-markdown editor with markdown formatting.

**Comment by mobitar** [comment]
Hey @spookfish, thanks for the detailed report. Editors won't work offline on mobile, but they should work on the desktop app. Can you try this:

1. In the desktop app, click Help -> Toggle Error Console.
2. Load a note with the Simple Markdown Editor. You should see in the console output a message with something like "Loading Simple Markdown Editor from..." and a URL that follows. Is the url a `file://` based URL or an `HTTPS` based URL? It should be `file` if it's loading from an offline source.

If not, try uninstalling the editor and reinstalling, and see if that helps.

**Comment by spookfish** [comment]
Hello,

thanks for the reply. I looked in the error console and it is trying to load my notes over http:// regardless if i am online or off. 

I tried clearing the cache and uninstalling the simple-markdown editor, however when i went to re-install it i could not. how can i get the simple markdown editor back? I am not currently a paying customer. When I signed up the simple-markdown editor was there.

**Comment by mobitar** [comment]
Oh..didn't realize you were using the old version of the Simple Markdown Editor. That one does not support offline installation, so it will not work offline. The new ones do. The best way to get it back at this point is to click Backups -> Open Backups Location, find the backup file from before you deleted the editor, then import this backup file using Batch Manager -> Backup Explorer. Find the editor, and restore it.

**Comment by spookfish** [comment]
purchased license. :smiley:

**Comment by mobitar** [comment]
@spookfish awesome :)
