### ISSUE TITLE
Quotes do not adhere to editor font size in Super notes

### ISSUE THREAD

**Issue by jonathanr24** [standardnotes/forum#3481]
**Describe the bug**
When adding a quote to Super notes and then increase the font size, the size of the font of quotes does not increase.

**To Reproduce**
1. Enter regular paragraph text.
2. Add a quote and add some text
3. Go to Preferences -> Appearance -> Editor. Set font size to Medium or Large.
4. The font size for regular text increases. However, the font size for the quote does not increase.

**Expected behavior**
The font size for the quote sizes to match the chosen font size under the preferences.

**Screenshots**

![image](https://github.com/standardnotes/forum/assets/50676696/d8701387-6a00-4005-b790-64622faf035a)

**Desktop (please complete the following information):**
 - OS: Mac
Using desktop app 3.189.0 (according to "What's New" in preferences). Although "About Standard Notes" from the OS "Standard Notes" menu says 3.187.3.

**Comment by effieeee** [comment]
Apologies for the wait! This has been fixed on v3.191.7 🙏
