### ISSUE TITLE
Standard Notes.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by bc-bytes** [standardnotes/forum#3488]
**Describe the bug**
After closing the app, it will no longer open. 

**To Reproduce**
1. Open the application.

**Expected behavior**
Application should open.

**Screenshots**
https://imgur.com/JaJjBwY

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro

**Additional context**
Tried rebooting system, get same error. Tried installing using installer, get same error. Uninstalling then attempting to reinstall - install completes, but when attempting to open the application, get same error.

**Comment by effieeee** [comment]
Hi @bc-bytes, unfortunately the current versions of the app use the updated Electron version, so I'm afraid this version has dropped support for Windows 8.1 and earlier. 

However, you may still access the app on that device through the web app at app.standardnotes.com 🙏

**Comment by bc-bytes** [comment]
OK, thanks for the info. I have downgraded to 3.22.11 and it seems to be working again. However, the devs may want to add something within the app that stops people with Win8.1 from updating as the crash resulted in me losing a days worth of notes which were unrecoverable from the backup.
