### ISSUE TITLE
"FIND" on free version and onwards...

### ISSUE THREAD

**Issue by Demosai** [standardnotes/forum#349]
Hi devs,

Can I ask a small favor? Can you add a find function even on a free version? Please?

**Comment by mobitar** [comment]
You can search your notes using the notes column search bar. This isn't exclusive to the paid version.

**Comment by Demosai** [comment]
Ohh, I sorry I haven't notice that process/way of finding a keyword. Thanks by the way, alot! 👍

**Comment by mobitar** [comment]
No problem!
