### ISSUE TITLE
[Help Wanted] Where is the repo for the self-hosted web app gone?

### ISSUE THREAD

**Issue by Mag1cByt3s** [standardnotes/forum#3499]
**Describe the issue**
I lost my docker-compose config, just seup everything again from scratch and cannot find the docker-compose.yml for the web app anymore.

Can someone tell me how i can self host the standardnotes web app if anything changed there?

All i could find was this repo: https://github.com/standardnotes/snjs
But it is archived and does not seem to provide the web app.

**Comment by effieeee** [comment]
Apologies for the trouble, we're looking into updating the docker image for the web app in due time, especially since it's now needed to self host the web app when signing into custom sync servers 🙏

https://github.com/standardnotes/server/issues/1042#issuecomment-1952856325

**Comment by Mag1cByt3s** [comment]
I see. Thanks for the clarification.
