### ISSUE TITLE
Default Tag on All Clients

### ISSUE THREAD

**Issue by AdamVig** [standardnotes/forum#35]
Instead of the client showing all notes by default, I'd like it to be able to show only notes with a specific tag by default. Filtering is built in on all clients already. This feature would add the option to make a "sticky" filter that is persisted between sessions.

My use case is this:
I use Standard Notes for both my daily lists/notes (#daily) and my long-form journaling (#journal). I don't want journal entries to get in the way when I open the app to look at my to-do list.

I could make this contribution, but want to check first if it makes sense within the feature-set of the application.

**Comment by mobitar** [comment]
I would think the best way to accomplish this is to keep the app open in the background on the tag you want to come back to. That's not always possible on mobile, but on desktop, is more reasonable. But really the real thing you might be asking for is remembering the state of the application when you quit. Which seems reasonable. But I don't know if that's exactly what you're describing.

**Comment by AdamVig** [comment]
Yes, that's a good way to summarize what I'm describing! I mostly notice tris problem on iOS. Filters are not persisted between app launches.

**Comment by mobitar** [comment]
That's something we'd definitely want to build towards.

**Comment by AdamVig** [comment]
Good to know that this is on your radar.

I can close this issue now, but before I do, is there any way I could help take the first step towards getting this implemented?

**Comment by mobitar** [comment]
Well the first step would be just to implement it :) If you're handy with JS you can take a look at both the web app or the desktop app.

**Comment by AdamVig** [comment]
This is still something that would be useful for me, and I thought I would mention another use-case: when the app locks due to the passcode lock timing out, it currently loses all state after I type in the passcode, even if I was actively typing when it locked.

(Obviously, it shouldn't lock when I am actively typing or using the app, but that's a separate issue.)

It would be great if the app would maintain its state after being locked and unlocked.

**Comment by mobitar** [comment]
Yup, this is something we hope to do. Requires better state management in our apps in general, which is something we're working towards in v4.

**Comment by AdamVig** [comment]
I'm going to close this issue since I never worked up the motivation to look into the code and it's already on your roadmap.
