### ISSUE TITLE
[Help Wanted]  share subscription for home server

### ISSUE THREAD

**Issue by dan937** [standardnotes/forum#3500]
I currently have a paid professional subscription (to api.standardnotes.com) and it works fine.

On another machine, under a different email address, I'm experimenting with the home server option.  I have that running and logged in locally with the other email address and it works fine as well.

My question is... can I share one of my 5 invites from the primary professional account to the address I'm using on my home server?  To unlock the app premium feature.  Or would I have to purchase a seprate "offline subscription"?

**Comment by effieeee** [comment]
Hi @dan937, unfortunately you cannot send a subscription sharing invite from an account on our official servers, to an account that's on your home server. For accounts on a home server or self hosted server, you'll need to use an [offline subscription](https://standardnotes.com/help/48/can-i-use-extensions-with-a-self-hosted-server) 🙏
