### ISSUE TITLE
Certain linked files can't be downloaded

### ISSUE THREAD

**Issue by cilki** [standardnotes/forum#3503]
Linked files older than 7/31/22 cannot be downloaded - either through the browser or desktop app. The error message doesn't give any useful information other than "failed". Examining the file details shows the metadata seems correct:
![2024-02-29-073306_313x231_scrot](https://github.com/standardnotes/forum/assets/10459406/d595de8f-9a36-4e1c-826f-ff6ced831d54)

I can download all files newer than that date, but nothing older.

**To Reproduce**
Unknown, but I recall my paid subscription elapsed around the time I uploaded these files.

**Expected behavior**
Linked file is downloaded correctly.

**Screenshots**
![2024-02-29-072452_397x85_scrot](https://github.com/standardnotes/forum/assets/10459406/6e550d14-f52f-4382-ad9d-b6d3a5d99ebf)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 122.0.1

**Additional context**
Also tried on the browser with same result.

**Comment by effieeee** [comment]
Hi @cilki, It looks like we'll need to investigate the items associated with your account at the moment, so can I ask you to send us a message at help@standardnotes.com using your Standard Notes account email? I'll continue assisting you via email, so I'll be closing this for now 🙏
