### ISSUE TITLE
website download contains version that is marked as pre-release on github (macOS v 3.191.12 )

### ISSUE THREAD

**Issue by suschizu** [standardnotes/forum#3506]
**Describe the bug**
the website download contains a version that is marked as pre-release on github
(https://github.com/standardnotes/app/releases/download/%40standardnotes/desktop%403.191.12/standard-notes-3.191.12-mac-x64.dmg)

**To Reproduce**
1. Go to 'https://standardnotes.com/ '
2. Click on 'https://github.com/standardnotes/app/releases/download/%40standardnotes/desktop%403.191.12/standard-notes-3.191.12-mac-x64.dmg'

**Expected behavior**
should be marked as stable on github (?)
or is the latest stable versopn still 3.191.4

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 13.6

**Comment by effieeee** [comment]
Hi @suschizu, apologies for the confusion! The download button on the website is actually configured to fetch the latest available package based on the **web app's.** current version. Technically, this release is also stable. However, the web app actually receives updates quite frequently, so to ensure that existing desktop app users do not have to update the desktop app at the same pace, we opted not to regularly update the "Latest" marked package for the desktop app on the releases page. We only update the "Latest" package if enough significant updates have accumulated in between versions, or if there is a critical change that needs to be rolled out to all platforms immediately 🙏

**Comment by suschizu** [comment]
ok understood - thanks for the explanation :)

**Comment by Adhjie** [comment]
I'm sorry to open this again @effieeee , but could you set up latest for stable version not just for desktop, my question is about mobile version.
Or a way to get stable download link from standard notes download page, to fetch the latest version using Obtainium. Whether it's from standard notes website or straight from GitHub, but latest release must be made a feature first in GitHub.

Case use: I want to download stable/latest release straight from GitHub or stable/latest version from the download link in Standard Notes website download page using Obtainium and opt-out on pre-release or beta, a new way to download stable version from Github like how SN is also available in F-Droid?

Also would I lose some functionalities if I download the google play store version but through aurora store?

A lot of apps have this type of multi version releases:Aves, Obtainium, etc.
I've tried asking this is Obtainium GitHub discussion but I think this must be a feature first from SN.
The discussion in question: https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/107
Or should I actually open this as feature and linked this issue as the reference for the feature request?

**Comment by effieeee** [comment]
@Adhjie I’ve referenced your comment in a new issue 🙏 (#3643 )
