### ISSUE TITLE
Pinning tags

### ISSUE THREAD

**Issue by frego** [standardnotes/forum#351]
I'd like to have the possibility to pin the specific tags I use frequently.

Cheers,

**Comment by mobitar** [comment]
You can do this using current methods by:

- Prefixing pinned tags with an _ to sort them higher
- Using the Folders extension to create a [smart tag](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes)

Not sure this is something we'd be adding natively anytime soon.

**Comment by frego** [comment]
Creating a smart tag does the job for me.
