### ISSUE TITLE
App stuck in credentials and OTP loop

### ISSUE THREAD

**Issue by sajeshcherian** [standardnotes/forum#3510]
**Describe the bug**
App keeps asking for credentials and OTP

**To Reproduce**
App keeps asking for credentials and OTP

**Expected behavior**
It should sync and show my notes

**Screenshots**

**Desktop (please complete the following information):**
iOS 17.4

**Smartphone (please complete the following information):**
iPhone 15 Pro Max

(edit: updated phone model)

**Comment by jphvegas** [comment]
Same problem here, so far only showing up on iPad, iPadOS 17.4.

Tried uninstalling, reinstalling, restarting, etc., all to no avail.

**Comment by tomwassenberg** [comment]
Experiencing this too on iOS 16.7.6.

**Comment by techie-82** [comment]
When trying to log into the application on a new install, I encounter a problem where it keeps asking me to sign in for refreshing credentials. Via their website it encounters an error with NetworkError when attempting to fetch resource.

**Comment by TomWaitsForNoMan1** [comment]
Same problem on my Galaxy S23 Ultra, even after uninstalling and reinstalling the app. Standard Notes keeps asking for my username and password over and over again

App version 3.191.15
Android version 14

But the problem does not occur on my Galaxy Tab S9 running the same version of both the app and android. The webapp also works fine

**Comment by effieeee** [comment]
Hi all, for iOS, please see the comment on [this issue](https://github.com/standardnotes/forum/issues/3507#issuecomment-1986230447)

@TomWaitsForNoMan1 please try out the following steps on your S23 to fully reset the app data and start over from a new session:

1. Locate the Standard Notes app in the app drawer.
2. Press and hold the app’s icon until a small menu appears.
3. Tap on App Info.
4. Locate and use the option to delete/clear the app’s data. (Please note: Do not reinstall the app afterwards.)
5. Relaunch the app and sign in again.

**Comment by TomWaitsForNoMan1** [comment]
@effieeee that worked, thanks a lot

**Comment by modefier2** [comment]
same for me on android miui note 9s unfortunately

**Comment by techie-82** [comment]
Does anyone with this problem have the self hosted version? There was an update that was installed a couple of days.

**Comment by effieeee** [comment]
For those that may still be experiencing this on Android, please update to v3.191.22! A similar update for iOS is also on the way 🙏

**Comment by ishapoval** [comment]
@effieeee Hi! I'm experiencing the sign-in loop with 3.192.1 on Ubuntu 20.04. Any help would be much appreciated.

**Comment by effieeee** [comment]
@ishapoval Hmm, if you haven't yet signed out and signed back into the app since you started experiencing the reauthentication loop, please try doing so now, and let me know if the issue still recurs within this week 🙏

**Comment by ishapoval** [comment]
> @ishapoval Hmm, if you haven't yet signed out and signed back into the app since you started experiencing the reauthentication loop, please try doing so now, and let me know if the issue still recurs within this week 🙏

That solved it all. Thank you!
