### ISSUE TITLE
[Help Wanted] "Manage Subscription" warning still showing on old notes after expiring and then renewing subscription

### ISSUE THREAD

**Issue by 86andyd** [standardnotes/forum#3512]
**Describe the issue**
A clear and concise description of what the issue is.

I had a Productivity subscription that expired, then renewed the same account today with a Professional subscription. The following error is still showing up after renewing. I have signed out, signed back in, selected "clear cache and reload", and even  uninstalled and reinstall the app. I am getting the same error on Mac app, iPhone app, and Web app. 

<img width="546" alt="Screen Shot 2024-03-08 at 4 39 11 PM" src="https://github.com/standardnotes/forum/assets/159659091/2d9a0a08-4723-4216-91aa-36351adc23f2">

**To Reproduce**
1. Get paid subscription
2. Make notes with editors only allowed on paid subscriptions 
3. Let subscription expire to trigger lack of access to features.
4. See warnings on notes that were made with editors that are only allowed on paid subscriptions.
5. Renew subscription
6. Warnings persist on previously made notes but not on notes made from this point forward.

**Expected behavior**
Warnings like the screenshot above should be removed after the subscription is updated.

**Screenshots**
<img width="546" alt="Screen Shot 2024-03-08 at 4 39 11 PM" src="https://github.com/standardnotes/forum/assets/159659091/2ebc5c27-ff26-4093-9a04-0fe9f2ef27ce">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Web app
 - Brave Browser [Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (x86_64)](https://brave.com/latest/)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Standard Notes desktop app
 - Version 3.191.4

**Smartphone (please complete the following information):**
 - Device: iPhone15 Pro
 - OS: iOS 17.3.1
 - Standard Notes mobile app
 - Version 3.191.5

**Additional context**

**Comment by python33r** [comment]
I'm experiencing the same. My subscription auto-renewed and notes created after the renewal date are fine, but notes created in the Markdown editor *before* the renewal date are locked with the message "Your subscription expired on" followed by the date of my next auto-renewal (in 2029).

I can fix by switching the note to the plain text editor and then back again - but clearly I shouldn't have to do that for *every* note...

**Comment by effieeee** [comment]
Hi, please try out the instructions below to reinstall the affected editor as an initial step:

1. Sign into the latest version of the desktop app or the web app (app.standardnotes.com)
2. Click on the **Open Preferences** icon at the bottom left of the app
3. Click on **Plugins** on the left hand side of the Preferences menu.
4. Under the **Manage Plugins** section, uninstall the affected plugin (e.g. Rich Text, Markdown etc), then relaunch the app.
![Manage-plugins](https://github.com/standardnotes/forum/assets/54989748/96d4de20-c4ac-4c23-a05b-9f0bc5ef98d8)
5. After relaunching the app, return to the Plugins menu and reinstall [plugin] in the **Browse Plugins** section.
   browse plugins
![Browse-plugins](https://github.com/standardnotes/forum/assets/54989748/621a875f-36d7-49ce-a5af-67c86961c607)
6. If the affected note still shows the issues, please also try switching them to plain text, then switch them back to the intended editor

If you have multiple notes exhibiting the same issues, you can use **Shift or Ctrl/Command + Left click** to select them all at once, then switch their note types to plain text and back to the desired editor on the note type list. The change will be applied onto all the currently selected notes 🙏

**Comment by 86andyd** [comment]
Rich Text editor did not show up under preferences in the "Manage Plugins" or "Browse Plugins" section... But I was able to change the editor on the notes to another editor and then back again. Worked perfectly. Thank you!

**Comment by effieeee** [comment]
I see, perhaps it might be listed on your end as the **Plus Editor**? This was its old name, so if you do find it there, please also try reinstalling it as Rich Text through the instructions I sent previously 🙏

**Comment by 86andyd** [comment]
Cool! That worked. I uninstalled the Plus Editor, closed application, relaunched, the installed the Rich Text editor. Perfect, thanks so much!
