### ISSUE TITLE
constantly asked to refresh session with the server

### ISSUE THREAD

**Issue by SynapseScribe** [standardnotes/forum#3513]
**Describe the bug**

**To Reproduce**
- go to https://app.standardnotes.com/
- already logged in previously
- quit browser, let some hours pass
- enter passcode as usual // at this point it should unlock my notes, but instead shows prompt to login
"Please enter your account email and password. Your credentials are needed for [foo@bar.com](mailto:foo@bar.com) to -refresh your session with the server."
- login with email + password again
- enter 2fa // a message is shown "Your session has been successfully restored." and notes unlocked, turning icon from red to green (synced)

**Expected behavior**
i am asked multiple times a day email + password + 2fa. a couple of week ago and further in the past this was not the case

**Screenshots**

**Desktop (please complete the following information):**
- Windows 11 23H2
 - Browser: Brave latest Brave is up to date
[Version 1.63.169 Chromium: 122.0.6261.111 (Official Build) (64-bit)](https://brave.com/latest/)
Get help with Brave

**Comment by SynapseScribe** [comment]
similar to https://github.com/standardnotes/forum/issues/2838

**Comment by tonimarmol** [comment]
The same thing happens to me. I use the Standard Notes for Linux client version 3.191.18 on Ubuntu 23.10

It started happening to me today.

**Comment by SynapseScribe** [comment]
this is completely unusable in this state.. how comes this is overseen?

**Comment by effieeee** [comment]
Hi, after the surge of reauthentication issues last week on mobile devices, the team was able to implement some fixes for the reauthentication issues in general (including desktop and web), though those who might still be seeing the reauthentication prompts may need to try signing out and signing back into their accounts on the latest versions of the app 🙏

**Comment by SynapseScribe** [comment]
still happening (right now)
i am using web app, not the desktop app

**Comment by effieeee** [comment]
I see, does it also continue to happen even after clearing the site data for the web app? (see instructions below for Chromium browsers)

1. Right-click anywhere on the web app.
2. Click on **Inspect Element** in the context menu
3. Expand the Developer Tools view that appears until it reveals a button for tab named **Application**.
4. Click on **Storage**.
5. Click on **Clear site data**.
![Clear-site-data](https://github.com/standardnotes/forum/assets/54989748/26f4f938-a5f7-4cf0-904c-5964db7c8ca8)
6. Refresh the web page, and sign in again.

**Comment by SynapseScribe** [comment]
i just cleared site data + empty cache and hard reload + clear cookie
then i logged in again

fingers crossed. will come back with updates these days

**Comment by SynapseScribe** [comment]
happened again, session didn't persist on browser close + restart, but only after a while
if i simply exit browser and restart it, the session persists

the account is remembered however, but asks me to re-authenticate (username+pass+2fa)
what strange is that i can browse my notes offline (it looks like a security issue?)

my browser is set to NOT delete cookies on exit.

**Comment by SynapseScribe** [comment]
hmm in the last 2 days, i didn't get the prompt anymore. i'll keep monitoring it

**Comment by SynapseScribe** [comment]
i am going to close this one. it seems to be solved now. Thank you !!!

**Comment by SynapseScribe** [comment]
the problem appeared again

**Comment by effieeee** [comment]
Hi @Uj947nXmRqV2nRaWshKtHzTvckUUpD, thank you for raising this with us, I've also taken note of similar reports in the forum, so I've notified the team about a possible recurrence of the issue. We'll do our best to keep you posted 🙏

**Comment by effieeee** [comment]
Hi all, the team was able to confirm an issue which affected the active user sessions, though a server wide fix was deployed earlier today. If you are still experiencing issues, please try signing out and signing back into your account, similar to what was done with the reauthentication issues in the past 🙏

**Comment by SynapseScribe** [comment]
seems ok since yesterday. thank you for the fast fix!

**Comment by joaofl** [comment]
It does not seem to be solved actually. I am having the exact same issue. For me it works on the Android app, but not on the Linux Flatpack nor on the online version (both v3.194.11).

And what I realized is that, for each new attempt to authenticate, a new session is created, what I can confirm from the android app:

<img src="https://github.com/standardnotes/forum/assets/8092452/fc398aa0-0719-4c8f-9dab-d91cb59bdc6d" height="500">

**Comment by effieeee** [comment]
Hi @joaofl, It's expected that completing the reauthentication workflow would result in a new session record, as it's meant to create a new, valid session token for the server. However, regarding how the reauthentication issue persists on your end, please see the comment on the thread below! 🙏 

https://github.com/standardnotes/forum/issues/3535#issuecomment-2191635960

**Comment by joaofl** [comment]
Hi @effieeee 
Thanks for the attention. I went through that thread as well, and I actually confirm that re-authentication issue is not there when I use the stantardnotes online services, but the problem is not yet solved for the self-hosted version.

Maybe the docker images are still outdated?

**Comment by effieeee** [comment]
Hi @joaofl, I see, it sounds like you're experiencing the issues described on #3635  , though please see the temporary workaround mentioned in one of [the comments](https://github.com/standardnotes/forum/issues/3635#issuecomment-2201763520) on that thread as well. 🙏

**Comment by firepainting** [comment]
This has been happening on my end again... Quite a long time ago this also happened but the issue disappeared but now it's back. I cleared everything in its container (Firefox), logged in again and after a couple of hours it just asked for my email+password+2FA again.

To reproduce is the same as OP's except that I don't set a passcode. I use the web app.

Desktop OS: Linux Mint 21.3
Browser: Firefox 133.0.3 (64-bit)

Thanks.

**Comment by firepainting** [comment]
@davidsmith91 I've never resolved this issue on my own--it just comes and goes. 

As of this writing I'm not getting prompts for email+password+2FA... It's been... around 1.5 months now? (I don't strictly track this.)

But by my estimates, upon signing in on my PC, it probably takes around two weeks of email+password+2FA prompts and it just...stops.

**Comment by firepainting** [comment]
I just logged in on the web app after clearing my browser's cookies, cache, etc. and as expected, the issue once again is back.

@effieeee

**Comment by Lawlietr** [comment]
I started running my own standardnotes server today.
I had this issue with the web app, but it worked fine on all my mobile devices, (ios, andorid etc..)

**Comment by martincomito** [comment]
Same here, self-hosted on my own VPS. The setup went fine. Once I created an account and logged in, this keeps appearing.
<img width="429" height="561" alt="Image" src="https://github.com/user-attachments/assets/ecb71e45-ef38-4e09-aa3b-24c713a622b5" />
Basically, I can’t log in. I need to use this same account since it has a Professional plan activation key tied to it.
