### ISSUE TITLE
I Accidentally deleted an extension and can't find it now... [Help Wanted]

### ISSUE THREAD

**Issue by 86andyd** [standardnotes/forum#3520]
Under Preferences, Plugins, Manage Plugins, I deleted the extension "2FA". I realized my mistake right away, shut down Standard Notes and restarted the program, then looked under Preferences, Plugins, Browse Plugins, and the 2FA plugin is not listed there... Is there a link that I can paste into the "Install Custom Plugin" field  to reinstall this feature? I also have the same problem with the Rich Text Editor as well.

The issue is present on the desktop app, mobile app, and web client.

**Comment by effieeee** [comment]
Hi, that's likely an old copy of a deprecated version for 2FA, so you shouldn't experience any problems 🙏
