### ISSUE TITLE
[Help Wanted] Custom plugins for paid plan only?

### ISSUE THREAD

**Issue by dataprolet** [standardnotes/forum#3525]
I'm using the free plan of Standard Notes and want to install a custom plugin. When I navigate to Settings -> "Plugins" in the web version and scroll down there is a box in which I can paste a link to a custom plugin. When clicking "Install" I get the following error:
"Error downloading package details. Please check the extension link and try again."

Are custom plugins also only available for paying users? If so, why is the box available in the settings?

**Comment by effieeee** [comment]
Hi @dataprolet, apologies for the trouble, this is a known issue and we'll have to work on a fix, though this only occurred on the newer versions of the app, so if you use [v3.191.4](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.191.4) of the app on desktop for example, you should still be able to install a custom plugin 🙏

**Comment by dataprolet** [comment]
Thanks you, I downgraded my desktop app and was able to install a custom plugin. Afterwards I updated to the latest version and was still able to use the plugin.
