### ISSUE TITLE
All notes, especially protected ones, are visible in Android app overview

### ISSUE THREAD

**Issue by jeffrson** [standardnotes/forum#3526]
**Describe the bug**
I'm using StandardNotes on Android. The app itself is protected (finger print), some notes are protected themselves.

When I open app overview (for switching between apps) an image of the last opened note stays open and can be seen unprotected.

**To Reproduce**
1. Open standard notes, open protected note
2. switch to another app via app overview
3. maybe even turn off the device
4. open app overview  again after some time, slide back to image of standardnotes

**Expected behavior**
Image should be protected (like my banking app does)

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: 14
 - Browser [e.g. stock browser, safari] App
 - Version [e.g. 22] 3.191.22

**Additional context**
As soon as I switch back to the app, it asks for authentication - that's fine. But it should not reveal information while put into background.

**Comment by effieeee** [comment]
Hi @jeffrson, perhaps you're looking for the **Multitasking/Screenshot Privacy** option? You can enable this under **Preferences > Security**:

![Screenshot_20240315_214010_Standard Notes](https://github.com/standardnotes/forum/assets/54989748/7f1b2e99-9935-4091-b0e4-6c6cfb45fa37)

**Comment by jeffrson** [comment]
Hi, thank you for this hint!!!

I'm sorry I had not found it. I just didn't think that could be a configurable option.

Maybe it should be active by default.

Anyway - thanks again! :-)
