### ISSUE TITLE
Desktop app not syncing, says I don't have paid subscription.

### ISSUE THREAD

**Issue by jellenc** [standardnotes/forum#3528]
Desktop app not syncing, says I don't have paid subscription.

In 'Account' under 'Subscription' it says 'You don't have a standard notes subscription yet'. Ever since I've had the desktop app (about a year now) it has always said this but I haven't had an issue using the subscription features oddly enough, until today.

In 'Sign Out' and 'Manage Sessions' it says 'failed to fetch'.

My Notes aren't syncing and I don't have access to my professional subscription features.

On my phone I am logged into SN and don't have any of these issues and are syncing fine. Same as browser on desktop.

Auto update also doesn't work so I downloaded the recent version of SN today after this issue came up, the issue still persists even in the new version.

OS Catalina 10.15.4
 - V 3.192.3

Oddly enough it still says latest version is 3.191.4 (see pic attached)

<img width="276" alt="Screenshot 2024-03-22 at 17 32 33" src="https://github.com/standardnotes/forum/assets/126355085/5f50d648-268b-442b-b9a4-f960049f3497">

**Comment by effieeee** [comment]
Hi @jellenc, sorry to hear about the issues you've been experiencing. For this though, please send us an email at help@standardnotes.com using your Standard Notes account email, if you haven't done so already. This appears to require some troubleshooting with your account and subscription, so we'll need to do that over the help inbox. I'll be closing this now as I can continue assisting you over emails 🙏

**Comment by jellenc** [comment]
@effieeee Ok, thank you!
