### ISSUE TITLE
data protection upon Identify loss.

### ISSUE THREAD

**Issue by charlesinc3** [standardnotes/forum#354]
(more of an inquiry) 

I'm considering use standard notes in place of 1Password-like applications for encrypted notes.

I'm aware that SN's thread model is considering client is safe, the App passcode adds extra layer of local protection. 

What concerns me is that a hacker only needs to `figure out` (brutal force or others) my SN credentials to retrieve and decode all my data.  Ideally, in the unfortunate event, hacker may retrieve my data with my SN credentials, but should not be able to decrypt my data. 

My SN passcode serves both data retrieval and decryption. Is there a possibility to separate these two passwords ?

**Comment by mobitar** [comment]
Part of SN's appeal is the ease of use, and especially not having to remember two passwords. The thing is, "brute force" isn't really an option with secure enough passwords. "Figuring out" is not something that's feasible if your password is secure. One, two, or three passwords won't make a difference regarding peace of mind if you have to enter them in the same place or on the same device anyway. 

In any case, the password you use in Standard Notes never leaves your computer, so as long as you're in a safe environment, and using a secure enough password, "brute force" is out of the question.

**Comment by charlesinc3** [comment]
Well said. 

May I know if SN has protection against wrong password attempts ? e.g, wrong password for a few times, account temporarily locked and account owner notified.

**Comment by mobitar** [comment]
There is no account locking, but there is rate-limiting, so you can only try 1 password per second. It also takes about 2-4 seconds to generate the password on the client side device.

**Comment by charlesinc3** [comment]
ok. thanks for clarifications.
