### ISSUE TITLE
If there is no Internet connection , every time you type in a note , a popup appears "Failed To Fetch"

### ISSUE THREAD

**Issue by SaifLotfi** [standardnotes/forum#3547]
**Describe the bug**
I am signed in , when I turn off wifi , every time I type in a note a popup appears "Failed To Fetch" , ending up with many popups blocking much space of the screen that hides the text behind it.

**To Reproduce**
1. Sign-in into your account
2. Have no internet connection
3. change or add a note
4. a popup appears "Failed To Fetch"

**Expected behavior**
Only one failed to fetch popup should be shown till the internet connection comes back

**Screenshots**
![image](https://github.com/standardnotes/forum/assets/130322757/37270b91-b7ff-4064-86a8-d70e9b917847)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Android 11
 - App version : 3.192.17

**Additional context**
same issue happens on my windows desktop , App version : 3.192.13

**Comment by effieeee** [comment]
Hi @SaifLotfi, that toast notification is now hidden on the latest update to v3.193.2! 🙏
