### ISSUE TITLE
Please enter your account email and password.

### ISSUE THREAD

**Issue by AxelHamburch** [standardnotes/forum#3557]
Why should Standard Notes ask these questions? Have I been hacked?

![2024-04-18 18_46_48-Standard Notes](https://github.com/standardnotes/forum/assets/84231978/87147ce5-24f7-4b54-ac73-7e0a04be1983)

![2024-04-18 18_49_27-](https://github.com/standardnotes/forum/assets/84231978/82364a2d-3dc1-4d57-9c82-4108a02acdf4)

I can click it off, but it keeps coming back.

**Comment by effieeee** [comment]
Hi @AxelHamburch, while this isn't an indication that you were hacked, it looks like you may be experiencing a similar issue as #3513. I'll be closing this for now, so please continue tracking the issue in #3513 🙏
