### ISSUE TITLE
Japanese IME behaves strangely (Android app 2.3.8)

### ISSUE THREAD

**Issue by yoneyajp** [standardnotes/forum#356]
I updated my Android app to 2.3.8, and since then, when I try to edit notes, Japanese IME behaves very strangely, i.e., when I type a character then cursor moves to the 1st column of 1st line.  This is very stressful so I downgraded to 2.3.7 and it is working well. 

FYI, I'm using ATOK for Japanese IME.  I'm not sure if it happens other Japanese IMEs.
https://play.google.com/store/apps/details?id=com.justsystems.atokmobile.service

**Comment by mobitar** [comment]
Hmm strange. We haven't made any changes here. Are you using any editor extensions, or just the plain editor?

**Comment by yoneyajp** [comment]
Hi mobitar,

I'm using plain editor.  During last week end, I tried four more Japanese IMEs on 2.3.8 and three of them showed this strange behavior.
 
Re-occurred IMEs:
Gboard: <https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin>
Google Japanese Imput: <https://play.google.com/store/apps/details?id=com.google.android.inputmethod.japanese>
iWnn IME: <https://www.omronsoft.com/products/product_text/iwnn-ime-for-android/>

No-occured IME:
Swiftkey keyboard: <https://play.google.com/store/apps/details?id=com.touchtype.swiftkey>

From my experiences, when I typed quickly (but normal speed), cursor jumping has happened, and when I typed slowly (painful and impractical), cursor jumping could mostly suppress.

**Comment by yoneyajp** [comment]
Hi mobitar,

Thank you for your great work!
It seems fixed in 2.3.10.
Really great!

**Comment by mobitar** [comment]
Glad to hear that!
