### ISSUE TITLE
Unable to create author account on Listed

### ISSUE THREAD

**Issue by M1ckB** [standardnotes/forum#3565]
**Describe the bug**

I would like to create a blog on Listed, so I'm trying to create an author account but am unable to do so.

When I press the button "Create new author", the button changes text to "Creating account..." and is greyed out. This goes on for thirty seconds and then then the button reverts to its normal state with no change.

**To Reproduce**

1. Go to "Settings" (either using the web app or macOS desktop app)
2. Press the "Listed" section
3. Press the "Create new author" button below the "Get Started" header

**Expected behavior**

I'm expecting to be taken to a page to create a new author account and blog.

**Screenshots**

<img width="759" alt="Screenshot 2024-04-21 at 19 37 42" src="https://github.com/standardnotes/forum/assets/98694606/e22bf291-c0f3-4dc0-a4d4-e311b1931aa3">

<img width="736" alt="Screenshot 2024-04-21 at 19 37 49" src="https://github.com/standardnotes/forum/assets/98694606/4e5f72ef-4d1b-46ce-9d7d-c0d371e62f46">

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser Brave
 - Version: Sonoma 14.4.1

**Comment by binaryronin** [comment]
Same issue here. Tried with iPhone, Tablet, Webapp, and Mac Application. Tried on my local network and on my cellular network just to make sure it didn't have to do with my network blocking.

**Comment by romain-pfund** [comment]
Same here, Try android, windows and webapp (chrome)

on the web app, I look at the DevTool:

Request URL: https://api.standardnotes.com/v1/users/XXXXXX/settings/listed_author_secrets
Request Method: OPTIONS
Status Code:204 No Content

then 

Request URL: https://api.standardnotes.com/v1/users/XXXXXX/settings/listed_author_secrets
Request Method: GET
Status Code: 400 Bad Request

with response
```json
{
    "meta": {
        "auth": {
            "userUuid": "XXXXXX",
            "roles": [
                {
                    "uuid": "XXXXXX",
                    "name": "PRO_USER"
                },
                {
                    "uuid": "YYYYYY",
                    "name": "CORE_USER"
                }
            ]
        },
        "server": {
            "filesServerUrl": "https://files.standardnotes.com"
        }
    },
    "data": {
        "error": {
            "message": "Setting LISTED_AUTHOR_SECRETS for user XXXXXX not found!"
        }
    }
}
```

Request URL: https://api.standardnotes.com/v1/users/XXXXXX/integrations/listed
Request Method: OPTIONS
Status Code: 204 No Content

Request URL: https://api.standardnotes.com/v1/users/XXXXXX/integrations/listed
Request Method: POST
Status Code: 200 OK

```json
{
    "meta": {
        "auth": {
            "userUuid": "XXXXXX",
            "roles": [
                {
                    "uuid": "XXXXXX",
                    "name": "PRO_USER"
                },
                {
                    "uuid": "YYYYYY",
                    "name": "CORE_USER"
                }
            ]
        },
        "server": {
            "filesServerUrl": "https://files.standardnotes.com"
        }
    },
    "data": {
        "message": "Listed account creation requested successfully."
    }
}
```
then again

Request URL: https://api.standardnotes.com/v1/users/XXXXXX/settings/listed_author_secrets
Request Method: GET
Status Code: 400 Bad Request

with response
```json
{
    "meta": {
        "auth": {
            "userUuid": "XXXXXX",
            "roles": [
                {
                    "uuid": "XXXXXX",
                    "name": "PRO_USER"
                },
                {
                    "uuid": "YYYYYY",
                    "name": "CORE_USER"
                }
            ]
        },
        "server": {
            "filesServerUrl": "https://files.standardnotes.com"
        }
    },
    "data": {
        "error": {
            "message": "Setting LISTED_AUTHOR_SECRETS for user XXXXXX not found!"
        }
    }
}
```

hope it can help

**Comment by borkomir** [comment]
+1, experiencing the same problem with an account on Productivity plan purchased.

**Comment by dba-richard** [comment]
+1, same issue as described.

**Comment by traktuner** [comment]
same issue here
macOS 14.4.1
Firefox
Simple Notes App 3.194.0
same for the web app version

**Comment by traktuner** [comment]
Additional informations - the API seems to throw 400 Bad Request errors when clicking the "Create new author" button.
<img width="1405" alt="Bildschirmfoto 2024-04-29 um 14 20 33" src="https://github.com/standardnotes/forum/assets/78533119/123c6400-6e91-467e-b2e9-a67107b8ec0b">

**Comment by tlohde** [comment]
same problem. both on webapp (firefox) and windows app (3.194.0)

**Comment by traktuner** [comment]
I opened a ticket and got word from support (@effieeee) that this is a known issue.
I hope it gets fixed soon :)

**Comment by shem-sargent** [comment]
I'm having the same problem while trying out Standard Notes for the first time since I learned about it through the Proton acquisition announcement. I hope this gets resolved soon!

**Comment by Nizumzen** [comment]
> I'm having the same problem while trying out Standard Notes for the first time since I learned about it through the Proton acquisition announcement. I hope this gets resolved soon!

Same. Listed is one of the reasons I paid up.

**Comment by santiagooo** [comment]
> I opened a ticket and got word from support (@effieeee) that this is a known issue. I hope it gets fixed soon :)

Thanks for asking and sharing!

@Dev/Support team: good luck to you, I hope it's not too hard to solve, thanks in advance :)

**Comment by Gamer10222** [comment]
Same issue for me.

**Comment by effieeee** [comment]
Hi all, apologies for the rather long wait for a fix on this. As of today, the **Create new author** button works properly again, and if you've used the button at the time when the issue was still active, you should find that your new blog should already be created for you 🙏

**Comment by M1ckB** [comment]
The issue has been resolved and I’m able to create an author account on Listed.
