### ISSUE TITLE
Standalone app has seemlingly excessive disk usage (reads/writes)

### ISSUE THREAD

**Issue by increpare** [standardnotes/forum#3576]
**Describe the bug**
Standard notes seems to do excessive disk reads/writes

<img width="934" alt="Bildschirmfoto 2024-04-27 um 00 19 06" src="https://github.com/standardnotes/forum/assets/465632/79d77bce-07e1-49b7-818e-6434bbe3d7ad">

Second column is writes, third column is reads.  (For record, a backup of my notes is 7.4mb, with 1110 notes)

(while writing this note it's gone from 99.59GB to 102.75GB, and counting, if I'm doing nothing it doesn't seem to do much, but if I alt+tab to it that seems to sometimes trigger a write spike.

**To Reproduce**
Just having the app open and taking notes like normal causes this behaviour, sometimes just alt+tabbing causes a write spike (Can be monitored in the "activity monitor" app).

**Expected behavior**
I expect disk usage to be low for plaintext notes.  It seems like it might be saving far too regularly, or writing unnecessarily when no changes were made.   If it was saving individual notes I would expect disk usage to be miniscule.  Maybe there are details of how encryption work that necessitate this? 

**Screenshots**

<img width="934" alt="Bildschirmfoto 2024-04-27 um 00 19 06" src="https://github.com/standardnotes/forum/assets/465632/79d77bce-07e1-49b7-818e-6434bbe3d7ad">

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1
 - Version: Standard Notes 3.192.4 (3.192.4)

**Comment by effieeee** [comment]
Hi @increpare, that's certainly not normal. Is this still the case even if you reinstall the app, ensuring that you remove the [data directories](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes) before uninstalling and reinstalling the app as well?

**Comment by increpare** [comment]
Yeah, that seems to have done the trick. Spooky!  Thanks for the suggestion.  Things seem to be fine now.

I'll close the thread now - I'll open it up should the problem return...
