### ISSUE TITLE
[Help Wanted] Unable to write to local database. Please restart the app and try again.

### ISSUE THREAD

**Issue by arathra** [standardnotes/forum#3579]
On Windows (both through the app and on a browser) I get a message "Unable to write to local database. Please restart the app and try again."

I can still use the app on other devices (tablet/phone) but not on Windows. I have tried multiple times to start, stop, the browser and app; also rebooting the PC, etc.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to sign in and go through the procedure
2. Message at the bottom saying "Sync error: Unfortunately we couldn't handle your request. Please try again or contact support if the issue persists"

**Expected behaviour**
After I log in, I expect to see the notes as usual.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome  or Opera
 - And standalone Standard Notes app on Windows

**Comment by marcusb333** [comment]
Samzies

**Comment by samo-sato** [comment]
I am not able to reach or sync my Standardnotes data since sometime today.

**Comment by jellenc** [comment]
Same here, and a good few people on the subreddit having the same issue

**Comment by JulienDlq** [comment]
Same here, using app on linux (snap or flatpack).
On Android, it tells nothing more than « Syncing… », and it is stuck.

**Comment by DBCerigo** [comment]
Same, getting "Sync error: Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists." on web app, and "Syncing..." indefinitely on the iOS app.

**Comment by MD-Niloc** [comment]
Sync Error iOS, macOS

**Comment by yorkie1000** [comment]
Same issue on Windows 10.  I signed out of my workspeace and logged back in (to see if that would fix it) and was taken to this webpage.  
![page](https://github.com/standardnotes/forum/assets/64734562/bebec287-4aa3-4ba5-a42b-6fa61bf71e8b)

Issue with subrcriptions??

**Comment by samo-sato** [comment]
Do people with paid subscription experience this issue as well?

**Comment by MD-Niloc** [comment]
> Do people with paid subscription experience this issue as well?

Yes

**Comment by Target1123** [comment]
Same issue here.  All devices (iOS, Linux, Desktop) as well as web app.  Can't sync anything.  Paid subscription.

**Comment by firepainting** [comment]
Same here. 

Unable to sync:
- Firefox (web app) on Linux 
- iOS app

**Comment by MD-Niloc** [comment]
At last an acknowledgment https://x.com/standardnotes/status/1784576572952826087?s=12

**Comment by kaktusztea** [comment]
It works for me now again.
