### ISSUE TITLE
Checksums don't match; What is the encoding for the SHA-512 in the release notes?

### ISSUE THREAD

**Issue by VishalRao** [standardnotes/forum#358]
For 2.3.10 release

https://github.com/standardnotes/desktop/releases/download/v2.3.10/latest-mac.yml

The listed SHA-512 sum for the .zip file is the followoing

``
M3TBi4drSR9GC4ZgdczrWdGnfGrt0OUekFpwYh6jyK9dVXkxKpRbsNlrvFWWZxIBGM81c74bvmAy7LVfPKFE5w==
``

doesn't look anything like what I calculated:
``
vishal@MacBook-Pro:~/installer_files/StandardNotes$ shasum -a 512 standard-notes-2.3.10-mac.zip 
3374c18b876b491f460b866075cceb59d1a77c6aedd0e51e905a70621ea3c8af5d5579312a945bb0d96bbc559667120118cf3573be1bbe6032ecb55f3ca144e7  standard-notes-2.3.10-mac.zip
vishal@MacBook-Pro:~/installer_files/StandardNotes$ 
``

When I run the result through base64 using the Mac's base64 utility, it still doesn't match.    

What encoding of SHA-512 is this?
What steps am I missing here? 

Thanks,
Vishal

**Comment by mobitar** [comment]
Please see here: https://github.com/standardnotes/web/issues/216#issuecomment-404903123

**Comment by VishalRao** [comment]
I see...

Trying to do something similar in python:

``>>> x=int("3374c18b876b491f460b866075cceb59d1a77c6aedd0e51e905a70621ea3c8af5d5579312a945bb0d96bbc559667120118cf3573be1bbe6032ecb55f3ca144e7", 16)
>>> print x
2694973492877266342911090329956723833638285326478711515447254822793060951654702834268999311432683725880910723322587916116291682486303306102493717406500071
``

Then take the int and convert it into base64

``
>>> base64.b64encode(bytes(x))
'MjY5NDk3MzQ5Mjg3NzI2NjM0MjkxMTA5MDMyOTk1NjcyMzgzMzYzODI4NTMyNjQ3ODcxMTUxNTQ0NzI1NDgyMjc5MzA2MDk1MTY1NDcwMjgzNDI2ODk5OTMxMTQzMjY4MzcyNTg4MDkxMDcyMzMyMjU4NzkxNjExNjI5MTY4MjQ4NjMwMzMwNjEwMjQ5MzcxNzQwNjUwMDA3MQ=='
``

This still does not match the expected

M3TBi4drSR9GC4ZgdczrWdGnfGrt0OUekFpwYh6jyK9dVXkxKpRbsNlrvFWWZxIBGM81c74bvmAy7LVfPKFE5w==

Any suggestions here?

Thanks,
Vishal

**Comment by mobitar** [comment]
Can't help with other languages sorry. I've only tested with my own instructions.

**Comment by VishalRao** [comment]
@pshelly   I think he still needs you to take the extra step of converting the hexadecimal sha512 into base64.   I have yet to do it successfully myself (tried it in python), but it's a step in your process that you have not done yet.   Keep us posted.

**Comment by mobitar** [comment]
[Right:](https://github.com/standardnotes/web/issues/216)

Open the `latest-{platform}.yml` file, and see the sha512 value. You can verify this manually using:

```
openssl dgst -sha512 standard-notes-2.2.5-x86_64.AppImage
```

The result will be in hex. The published string is base64. So we need to convert hex to base64. We can use node for this:

```
$ node
> new Buffer(hexResult, 'hex').toString('base64') 
```

(Be sure not to directly convert hex as a plain string to base64. You want to convert the hex binary data to base64.)

**Comment by pshelly** [comment]
@mobitar Sorry I forgot about the second part.

@VishalRao Here is the Python 3 version:
```
>>> from hashlib import sha512
>>> from base64  import b64encode
>>> f = open('standard-notes-2.3.11-x86_64.AppImage', 'rb')
>>> bytes = f.read()
>>> hashInBinary = sha512(bytes).digest()
>>> print(b64encode(hashInBinary).decode('utf-8'))
3qSVIfEFx5SMljO5BxSJspwDJK0h0DWB5oBnMn8WCTbDroFWNAZNxkmObuPaRmMJjesrmrC71N1AbDVdnNak5Q==
```
[python docs](https://docs.python.org/3.7/library/hashlib.html)

Explanation:
1. Open file in binary mode and read it
2. Hash file and convert to plain binary
3. Encode in base64 and convert to utf-8 for readable text
Note: no need to convert from HEX since hash is in binary. 
Shell version:
```
$ shasum -a 512 -b standard-notes-2.3.11-x86_64.AppImage | xxd -r -p | base64
3qSVIfEFx5SMljO5BxSJspwDJK0h0DWB5oBnMn8WCTbDroFWNAZNxkmObuPaRmMJjesrmrC71N1A
bDVdnNak5Q==
```
Explanation:
1. shasum outputs the sha512 hash in HEX.
2. xxd reverses the previous output to binary, since base64 only takes in binary.
3. base64 converts binary to readable base64
Note: needs to convert from HEX

**Comment by VishalRao** [comment]
@pshelly   small nitpick, in the python3 script, I think you meant f.close() at the end??

**Comment by pshelly** [comment]
@VishalRao Indeed. Thanks for spotting the error. Just edited it.
