### ISSUE TITLE
Sync shows as completed even when there is no connection

### ISSUE THREAD

**Issue by proailurus** [standardnotes/forum#3580]
**Describe the bug**
When there is a sync problem, the desktop app still shows the sync as completed even though it didn't sync

**To Reproduce**
1. Open desktop app when there is no connectivity
2. Check sync status in bottom left
3. Sync shows as completed

**Expected behavior**
Sync status should show as failed

**Screenshots**
![Screenshot_20240428_120139](https://github.com/standardnotes/forum/assets/17836261/0ceee61e-3f97-486f-979b-2f6eff858b1f)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 124.0.1
 - Webapp 3.194.0

**Comment by diplomendstadium** [comment]
I have the same problem on GraoheneOS (Android 14) with version 3.193.9 (installed via F-Droid).

**Comment by few4i** [comment]
Me too - windows 11, chrome 124.0.6367.79, webapp 3.194.0

**Comment by effieeee** [comment]
Hi, just confirming if this is related to the sync issues in #3582 and #3579 ?

**Comment by proailurus** [comment]
@effieeee the timing would line up

**Comment by few4i** [comment]
I think probably the same as 3582
