### ISSUE TITLE
is the standardnote server down?

### ISSUE THREAD

**Issue by fwwefwefw** [standardnotes/forum#3581]
**Describe the bug**
Cannot sync after login

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diplomendstadium** [comment]
On all my devices (GraoheneOS Android 14 with version 3.193.9 installed via F-Droid | 3.194.0 as Snap on Ubuntu 24.04 | Web app on Ubuntu Snap Firefox 125.0.2) I can still login standardnotes... but I can't sync anymore :-(

**Comment by virtuallyvlad** [comment]
It's down.  In the future, just check the [#sn-discussion channel](https://discord.com/channels/894600255058898974/894600255058898977) of the Discord server.

**Comment by the-a-man-006** [comment]
Yo, is the internet going down???
Why'd you put your servers in Ukraine and Gaza lol.
Please bring the servers up again... It's the single most important app I have...

**Comment by diplomendstadium** [comment]
> It's down. In the future, just check the [#sn-discussion channel](https://discord.com/channels/894600255058898974/894600255058898977) of the Discord server.

A status page on the website would certainly be helpful for similar incidents in the future. Everyone could then see that the server is currently down and that it is not due to their own apps or account. Such a status page would certainly also save a lot of chaos in the Discord chat and some issues here ;)

**Comment by virtuallyvlad** [comment]
> > It's down. In the future, just check the [#sn-discussion channel](https://discord.com/channels/894600255058898974/894600255058898977) of the Discord server.
> 
> A status page on the website would certainly be helpful for similar incidents in the future. Everyone could then see that the server is currently down and that it is not due to their own apps or account. Such a status page would certainly also save a lot of chaos in the Discord chat and some issues here ;)

Yea I requested this back in 2021: https://github.com/standardnotes/forum/discussions/2646
