### ISSUE TITLE
MacOS Desktop Font size cannot be increased v3.194.0

### ISSUE THREAD

**Issue by anayeaye** [standardnotes/forum#3590]
**Describe the bug**
Desktop app on an Apple M3 Pro does not increase font size when settings are changed in the appearance preferences. This is super sad because the default is tiny :( 

**To Reproduce**
1. Open preferences 
2. Navigate to Appearance
3. Change font size to 'Large'
4. Font size in desktop client is not increased after saving, reopening, or restarting and confirming that font size is still set to 'Large'.

**Expected behavior**
Font size can be increased.

**Screenshots**
Font size does not change when adjusted in appearance preferences (it is always small). 
<img width="600" alt="Screenshot 2024-05-16 at 3 24 22 PM" src="https://github.com/standardnotes/forum/assets/3386265/c6a141f2-4185-4518-837f-09536731ea0a">
<img width="600" alt="Screenshot 2024-05-17 at 11 09 42 AM" src="https://github.com/standardnotes/forum/assets/3386265/31193520-85e8-4631-830d-767152f24c5a">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.4 (23E214)
 - Browser N/A font size is adapted when appearance settings are changed in browser
 - Version StandardNotes 3.194.0

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
- N/A

**Comment by effieeee** [comment]
Hi @anayeaye, before anything else, please note that the font size and other font settings here will only affect the text in **plain text and Super** notes. I'm afraid that the app currently doesn't have a setting for the font size of the UI in general. 

However, upon testing this further, I did find that the font size change only doesn't apply for **plain text** notes, but applies normally on Super notes. I wanted to ask if you can confirm that this is also the case on your end?

**Comment by anayeaye** [comment]
Hi @effieeee thank you + sorry for the delay in response! I can confirm that the font size setting affect both the plain text and Super notes for me but not the UI in general. 

Since I opened the issue I have had a chance to check the UI font size on a different mac and found that in the older macbook, the UI font size matches the system settings (i.e. same as the folder names in finder) but on this M3 Pro the general UI settings do not match the system settings. 

So I was wrong about the cause of this being related to the font size selected in Standard Notes preferences--that works as expected! I'm not sure how to report the system font size disagreement so I think this probably good to close.
