### ISSUE TITLE
Released packages files have no Digital Signatures

### ISSUE THREAD

**Issue by EmadFathy** [standardnotes/forum#3599]
**Describe the bug**
Released packages files have no Digital Signatures, so Windows warns about executing the file. Some of the files I've checked

standard-notes-3.194.0-win.exe                              MD5: 6A00AD71AFD746AE47DD2526772C2CBB
standard-notes-3.194.0-win-x64.exe                       MD5: B3AB6DA926AB635BDFCD152FB88BDFF1
standard-notes-3.194.7-win-x64.exe                       MD5: A61CD3A2E793ECDF788DD80AAB65DFFF

**To Reproduce**
Right click the file and check file properties in Windows 10.

**Expected behavior**
Digital Signature tab should be exists.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by EmadFathy** [comment]
Why did you drop digital signatures?? Its an important security feature, personally - and I think many others -I don't install files not digitally signed.

**Comment by stevesbrain** [comment]
The help articles on the main website still suggest the Windows apps should be signed. That they aren't raises questions

**Comment by effieeee** [comment]
Hi all, apologies for the issues with the app signature in recent releases. We've worked out the app signature limit with digicert, so desktop app releases from v3.194.10 onwards will have the proper signatures 🙏

v3.194.10 is also now available by downloading the app from our website's [home page](https://standardnotes.com/), or on our [Github repository](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.194.10)!

**Comment by stevesbrain** [comment]
@effieeee if it's possible, might I suggest the team consider a blog post about how they ensure security in the build chain/supply chain, so we can see how much confidence we can put in that a bad build cannot easily be served up to us (leaking keys/our data/etc)? 🙂
