### ISSUE TITLE
Firefox is blocking standardnotes download as a phishing site

### ISSUE THREAD

**Issue by JPL1** [standardnotes/forum#36]
Any idea why this is?

> Deceptive Site!
> 
> This web page at github-production-release-asset-2e65be.s3.amazonaws.com has been reported as a deceptive site and has been blocked based on your security preferences.
> 
> Deceptive sites are designed to trick you into doing something dangerous, like installing software, or revealing your personal information, like passwords, phone numbers or credit cards.
> 
> Entering any information on this web page may result in identity theft or other fraud.

Edit: this seems to be an issue with Firefox. Other projects on Githup give similar warnings. Doesn't happen with Chrome.

**Comment by mobitar** [comment]
Ya not sure why this is. The files are hosted through GitHub, and it only happens with Firefox.

**Comment by TheodoreChu** [comment]
Update: the Windows application is signed with [Digicert Extended Validation Certificate](https://www.digicert.com/code-signing/ev-code-signing/) as discussed here: https://standardnotes.org/help/52/what-services-does-standard-notes-use-for-daily-operation
