### ISSUE TITLE
iOS App freezes after first sign in

### ISSUE THREAD

**Issue by christianpetty** [standardnotes/forum#360]
iPhone X
iOS 12.0.1
Standard Notes 2.3.8

Standard Notes freezes after first sign in and sync after clean install of App. Any GUI input after freezing immediately crashes it. Subsequent close and reopens of the app leave to an empty notebook and next tap crashes app. 

It has worked flawlessly up until this point. Desktop app still syncs perfectly. 

Phone restart does not help. 

Thanks!

**Comment by strawsa** [comment]
Update: if I press “filters” before swiping and check any or all tags, I can view my notes perfectly. The second I uncheck them the app crashes after clicking “done.”

**Comment by xt88** [comment]
iPhone Xs Max
Latest iOS
Latest Standard Notes.

Same issue. Help fast, I plan my life though the app!

**Comment by mobitar** [comment]
Sorry, 2.3.10 is on the way with the fix! Just waiting for approval by Apple.

**Comment by howfar108** [comment]
As for the iOS app freezing issue, the reaosns behind it could be the app corrupted, software bugs and iOS glitches. To fix it, there are usually 3 ways.
1. Close the app and reopen it.
2. Force restart your iOS device.
3. Fix iOS through related software such as TunesKit iOS System Repair.
