### ISSUE TITLE
How to install a theme on Android?

### ISSUE THREAD

**Issue by tylerburleigh** [standardnotes/forum#361]
How do I install a theme on the Android app?

I'm subscribed to an Extended plan. Under the Themes section in app Settings I see a link to More Themes. When I tap that it loads this page: https://standardnotes.org/extensions, which lists the themes. On this page, the themes have a "Try It" link but that launches into a web-based demo.

**Comment by mobitar** [comment]
@tylerburleigh please see here: https://standardnotes.org/help/43/how-do-i-install-themes-on-mobile

**Comment by Consoledotlog** [comment]
Sorry to open this again, but themes on android seem to be broken right now? I installed several on desktop and they now show in mobile, but tapping on them does nothing, only the two default themes change anything.

**Comment by JaspalSuri** [comment]
Please press and hold each theme and then tap on the "Redownload" option. Let us know if that works! I'm sorry that it didn't work automatically.

**Comment by Consoledotlog** [comment]
Awesome that worked thanks!
