### ISSUE TITLE
App crashes in ubuntu 14.04.1

### ISSUE THREAD

**Issue by sukandula** [standardnotes/forum#362]
App  shows  login screen for a split second and crashes.  This is the first time I have downloaded the app.

System details:
Linux xxxx 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
App version: standard-notes-2.3.11-x86_64.AppImage

Log at the time of  crash:
Checking for updates...
[17:18:44:0614] [info] Checking for update
Finished checking for updates. Latest version: 2.3.11 Current version: 2.3.11
Syncing components: 2
Syncing components: 1
UNINSTALLING COMPONENT 32653111-72f1-4256-9848-fcd58cc398f3
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Syncing components: 1
UNINSTALLING COMPONENT 1a3dd2f8-c6bf-4c03-b4b9-98ec13cde683
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Data backup succesfully saved:  2018-11-05T01-18-45.196Z.txt
Syncing components: 1
UNINSTALLING COMPONENT 32653111-72f1-4256-9848-fcd58cc398f3
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Syncing components: 2
UNINSTALLING COMPONENT 32653111-72f1-4256-9848-fcd58cc398f3
UNINSTALLING COMPONENT 1a3dd2f8-c6bf-4c03-b4b9-98ec13cde683
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Syncing components: 2
UNINSTALLING COMPONENT 32653111-72f1-4256-9848-fcd58cc398f3
UNINSTALLING COMPONENT 1a3dd2f8-c6bf-4c03-b4b9-98ec13cde683
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Syncing components: 2
UNINSTALLING COMPONENT 32653111-72f1-4256-9848-fcd58cc398f3
UNINSTALLING COMPONENT 1a3dd2f8-c6bf-4c03-b4b9-98ec13cde683
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Syncing components: 2
UNINSTALLING COMPONENT 32653111-72f1-4256-9848-fcd58cc398f3
UNINSTALLING COMPONENT 1a3dd2f8-c6bf-4c03-b4b9-98ec13cde683
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Syncing components: 2
UNINSTALLING COMPONENT 32653111-72f1-4256-9848-fcd58cc398f3
UNINSTALLING COMPONENT 1a3dd2f8-c6bf-4c03-b4b9-98ec13cde683
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
Unable to read JSON file /home/xxx/.config/Standard Notes/Extensions/mapping.json
/tmp/.mount_standav3yvZU/app/standard-notes --type=renderer --no-sandbox --primordial-pipe-token=D9A46A0B4AEB0FA57C19B501D498683A --lang=en-US --app-path=/tmp/.mount_standav3yvZU/app/resources/app.asar --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --service-request-channel-token=D9A46A0B4AEB0FA57C19B501D498683A --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101: relocation error: /tmp/.org.chromium.Chromium.IEm6jg: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
[17:18:45:0777] [info] Update for version 2.3.11 is not available (latest version: 2.3.11, downgrade is disallowed).

**Comment by mobitar** [comment]
Hmm strange. Can you try any of these solutions:

- https://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6
- https://stackoverflow.com/questions/36816570/glibcxx-3-4-21-not-defined-in-file-libstdc-so-6-with-link-time-reference
- https://github.com/typora/typora-issues/issues/504
