### ISSUE TITLE
Standard notes not working on windows

### ISSUE THREAD

**Issue by wreckless-omni** [standardnotes/forum#3647]
**Describe the bug**
standard notes gave an error that it wasn't there. when i try and download it again the download simply disappears and says i need permission to download it, yet nothing asks me if i want to grant it permission. It's been completely uninstalled from my system without any action on my part. the app works fine on my android.

**To Reproduce**
1. download to windows desktop

**Expected behavior**
I expected normal behaviour, and expected to be able to reinstall it.

**Desktop (please complete the following information):**
 - OS: windows 11 home
 - Browser Brave.
 - Version  23h2

**Smartphone (please complete the following information):**

**Comment by effieeee** [comment]
Hi @wreckless-omni, may I ask you to provide some screenshots of the errors you would see whenever you try to download the Windows app from our website?

**Comment by wreckless-omni** [comment]
oddly, it didn't work for three days and then all the sudden downloaded and
worked flawlessly. i changed nothing about my sytem, there was no update.
gremlins perhaps? i first noticed that windows said it wasn't installed
when i clicked on the shortcut for it. then when i went to download it, it
said i didn't have permission and autodeleted the download. it did this on
brave and on chrome. works fine now though
