### ISSUE TITLE
Suddenly lost changes to my notes

### ISSUE THREAD

**Issue by jonteamere** [standardnotes/forum#367]
Running android, web, Mac, and iPad versions of the app. Made tons of changes on web and then on android. Mac app suddenly stopped responding. I quit the application and restart it. Suddenly, all of my note changes are gone and this deficient version has been synced to all other versions of the app. How can I restore my lost notes?

**Comment by mobitar** [comment]
It's unlikely that the Mac app would sync old changes, unless you used the app offline, went to your other devices, made changes, came back to Mac app and connected to the network, then synced. At that point, if this was done greater than 20 seconds from the time you made the changes on your other devices, it should create duplicates, keeping both copies. I recommend opening an incognito tab in your browser and signing in to app.standardnotes.org to see what your final account state is. Check to see if there are any duplicates of the mentioned notes.

Another thing to try is Session History on the Mac/web app (if you haven't quit/restarted the apps yet). It will show all changes in the session, and can be found in the editor pane.

Lastly, I don't know your account email, so I'm unable to look into this any further. It's why the public forum is not the recommended medium for account issues. Please email me at mo@standardnotes.org so I can look into this further.
