### ISSUE TITLE
Windows 8.1 install failure - bad DLL? standard-notes-3.194.11-win-x64

### ISSUE THREAD

**Issue by TonyBShepherd** [standardnotes/forum#3673]
**Describe the bug**
Downloaded app to Windows laptop 8.1 Home (also Pro), ran install. May have installed but when attempt to run, error box says:[Standard Notes.exe - Entry Point Not Found] The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library c:\Users\Slow\AppData\Local\Programs\@standardnotesinner-desktop\Standard Notes.exe.

**To Reproduce**
1. Go to URL standardnotes.com (browser is FF)
2. Click on Download for free
3. Execute downloaded program

**Expected behavior**
Step 4 (above) should have been 'enjoy program'   :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1 (2 machines, 1 is home, other is Pro. Same behavior on both. Both up to date)
 - Browser Firefox ESR 115.12.0 (64-bit) (latest)
 - Version see above

**Smartphone (please complete the following information):**
NA - works for me on 3 Android phones + 2 Android tablets + 1 Linux laptop

**Additional context**
No particular urgency - getting by on other devices. Nice app BTW :)

**Comment by TonyBShepherd** [comment]
Oops - should have added - ALL activity began July 2nd, 2024 after 3PM Eastern Standard Time USA. (IE - download was not stale)

**Comment by effieeee** [comment]
Hi @TonyBShepherd, unfortunately the version of Electron on the newer versions of the app can no longer support Windows 8.1, so I'm afraid this is likely why the installation fails 😞 However, it should still be possible to use the web app (app.standardnotes.com) on any browser!

**Comment by TonyBShepherd** [comment]
Thank you for the research and reply. I spent time reading the SN FAQ's and don't recall seeing mention of required OS versions.

My access to the internet is through a hot spot with a less than solid connection. I prefer to work offline with an assortment of files on various machines, then synchronize later to my Proton Drive account. With care, this gives me a resilient environment, with versioning (thanks Proton) that is generally OS and platform agnostic.

When I heard that Proton and Standard Notes were joining forces, the days of careful syncing appeared to be coming to an end. But having to rely on a web-based (online) version of SN makes the cure worse than the disease.

Can you suggest a prior release of Standard Notes that works on Windows 8.1 offline, or other ideas I might try?

Thank you.

Jul 9, 2024 2:12:30 PM Effie Beldia ***@***.***>:

**Comment by effieeee** [comment]
I see, in that case, I believe the last version where Windows 8.1 was supported would be [v3.144.4](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.144.4), though you can also try [v3.133.0](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.133.0).

While syncing won't be an issue since you'll be working offline, please note that because these versions are about a year old, you may encounter some old bugs that have already been fixed in the current versions, and you may find that some newer features may not be present on these versions yet. 🙏

**Comment by TonyBShepherd** [comment]
Again, thanks for your help and suggestions. One day "Real Soon Now" those 8.1 machines will be converted to Linux, and my 8.1 apps will be upgraded / virtualized. I'd rather not take time away from that effort to find bugs in unsupported versions :)

In the meantime I'll continue with more usage of my 'droid and Linux machines.

Thank you.

Jul 13, 2024 1:33:48 PM Effie Beldia ***@***.***>:
