### ISSUE TITLE
iOS super note multi-line pasting

### ISSUE THREAD

**Issue by ningsongshen** [standardnotes/forum#3675]
**Describe the bug**
When I copy multi-line text to be pasted in the SN iOS app in a super note, only the first line is pasted.

**To Reproduce**
1. Copy multiple lines of text
3. Paste in a super note
4. Only the first line is pasted

**Expected behavior**
I expect the entire text I copied to be pasted

**Smartphone (please complete the following information):**
 - Device: iOS 17

**Additional context**

**Comment by effieeee** [comment]
Hi Ningsong! Unfortunately I haven't been able to reproduce this so far on iPad, though can you let us know more information that can help us reproduce it? For example, what app(s) were you copying the text from? Was the content in plain text, or was it formatted with HTML or Markdown?

**Comment by ningsongshen** [comment]
Actually sorry I have not been able to reproduce the issue again.
