### ISSUE TITLE
Question: web edition security compared to clients

### ISSUE THREAD

**Issue by charlesinc3** [standardnotes/forum#368]
Hi mobitar, 

Two questions here,  appreciate inputs.

- is there any difference between web app v.s. client, in terms of security ?  Occasionally want to keep a note on machines I do not own.  Under the hook, I understand clients also runs Electron/Chrome.  Still hope to confirm. 

- Is there a way I can clean local data manually when using Web app. ( I mean manually from disk folders)

**Comment by mobitar** [comment]
The codebase is exactly the same for web and desktop. The only difference is the distribution method. The web app is downloaded from our server every time you want to use it, whereas the desktop app is downloaded once, then run directly from an offline source. 

You can click Account -> Sign out and clear local data to clean your session.

**Comment by charlesinc3** [comment]
Thanks for confirming. On my Mac I notice `~/Library/Application Support/Google/Chrome/Default/IndexedDB/https_app.standardnotes.org_0.indexeddb.leveldb
` persists after I sign off and clean local data.  Just to confirm this is expected.  May I ask which data is expected to be erased ?  (sorry for being paranoid). 

As a side note, it seems web saves data in Chrome folder, and client saves in its own. In case I use two accounts for different purposes. there shall have no conflict of data ?

**Comment by mobitar** [comment]
When you sign out of your account, your local data is cleared, but a new offline session is started as an empty slate. So if you open up that .leveldb folder and sign out of your account, you'll notice the files shuffle around a bit. The new offline session includes some default data which uses IndexedDB, but it's unrelated to your previous session.

**Comment by mobitar** [comment]
You can use different accounts without problem. One per browser, and one per desktop installation.

**Comment by charlesinc3** [comment]
Got it. Great to know.  Thanks for confirming.
