### ISSUE TITLE
Show Tags Panel

### ISSUE THREAD

**Issue by walla336** [standardnotes/forum#3684]
**Describe the bug**
When I have Show Tags Panel enabled and click on a tag, the tag panel disappears. When I go to re-enable it, it is already enabled. I have to click into a different notes, then enable the show tags panel. I would like it to be 'sticky' and keep the panel open at all time. 

**To Reproduce**
1. Go to Appearance and enable Show Tags Panel.
2. Click on a tag.

**Expected behavior**
Tags panel is always displayed.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Version 3.194.11 (1103)

**Comment by effieeee** [comment]
Hi @walla336, I wanted to ask if you might have the **Dynamic panel** option enabled as well? Having this option enabled will cause the tags panel to minimize when your cursor is not placed above it.

![image](https://github.com/user-attachments/assets/2d169c0a-dade-463a-b7a7-de4350a1b795)

If this isn't the issue, can I also ask you to try clean reinstall of the desktop app? You can do this by following the [uninstallation instructions](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes) on our help page, then download and install the latest version of the app for your device on our website’s [homepage](https://standardnotes.com/).

**Comment by walla336** [comment]
I do not have a dynamic panel option there. 

￼

I did a reinstall and have the same behavior.

**Comment by walla336** [comment]
> Hi @walla336, I wanted to ask if you might have the **Dynamic panel** option enabled as well? Having this option enabled will cause the tags panel to minimize when your cursor is not placed above it.
> 
> ![image](https://private-user-images.githubusercontent.com/54989748/348487738-2d169c0a-dade-463a-b7a7-de4350a1b795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDgxNzAsIm5iZiI6MTcyMTAwNzg3MCwicGF0aCI6Ii81NDk4OTc0OC8zNDg0ODc3MzgtMmQxNjljMGEtZGFkZS00NjNhLWI3YTctZGU0MzUwYTFiNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDAxNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMWVhYTM5ZDZkYTVjYTI1MTA5ZDZmYWQ3MWZjNTljYTI1NTk2YjBlMTViOTU2MWE4ZmYwNmQxOWNmYjIwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5K7BrG2wCdZW5ojmQSOSutz0qCrgi61ZKIf_jXh3PIo)
> 
> If this isn't the issue, can I also ask you to try clean reinstall of the desktop app? You can do this by following the [uninstallation instructions](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes) on our help page, then download and install the latest version of the app for your device on our website’s [homepage](https://standardnotes.com/).

This was it! I was downloading it from the app store. It seemed to work as expected once I downloaded directly from the site. Thanks!

**Comment by walla336** [comment]
> Hi @walla336, I wanted to ask if you might have the **Dynamic panel** option enabled as well? Having this option enabled will cause the tags panel to minimize when your cursor is not placed above it.
> 
> ![image](https://private-user-images.githubusercontent.com/54989748/348487738-2d169c0a-dade-463a-b7a7-de4350a1b795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDgxNzAsIm5iZiI6MTcyMTAwNzg3MCwicGF0aCI6Ii81NDk4OTc0OC8zNDg0ODc3MzgtMmQxNjljMGEtZGFkZS00NjNhLWI3YTctZGU0MzUwYTFiNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDAxNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMWVhYTM5ZDZkYTVjYTI1MTA5ZDZmYWQ3MWZjNTljYTI1NTk2YjBlMTViOTU2MWE4ZmYwNmQxOWNmYjIwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5K7BrG2wCdZW5ojmQSOSutz0qCrgi61ZKIf_jXh3PIo)
> 
> If this isn't the issue, can I also ask you to try clean reinstall of the desktop app? You can do this by following the [uninstallation instructions](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes) on our help page, then download and install the latest version of the app for your device on our website’s [homepage](https://standardnotes.com/).

This was it! I was downloading it from the app store. It seemed to work as expected once I downloaded directly from the site. Thanks!
