### ISSUE TITLE
Duplicate Postman's executable files structure

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#369]
Per the following PNG screenshot, one of the reasons it's much easier to upgrade Postman is that Postman uses a link to the executable to avoid the need to update shortcuts and other launchers to include the most current version's version number.

![postmanfolderstructure](https://user-images.githubusercontent.com/3333327/48666482-c7451000-ea77-11e8-9055-56f6eac5335b.png)

SN on the other hand obliges one to update version numbers in desktop shortcuts, dock icons, et cetera.

This plus the fact that Postman updates into the current program file's directory structure is yet another reason Postman is significantly easier to update...

**Comment by mobitar** [comment]
We use a [packager](https://github.com/electron-userland/electron-builder) so we don't have direct control over file structure..
