### ISSUE TITLE
Can't connect to Listed, FileSafe Android message at the bootom of every note[Help Wanted]

### ISSUE THREAD

**Issue by MiloSam** [standardnotes/forum#3692]
Since two days ago I can't connect to Listed part of the Notes. When trying to publish / update my published note, the Listed menue says: No actions available. 

Since then the bottom of every Note displays a FileSafe message: 
file:///android_asset/Web.bundle/src/web-src/components/assets/org.standardnotes.file-safe/disk/index.html could not be loaded because: 
net::ERR_FILE_NOT_FOUND
 
I have a proffesional subscription.  v.3.193.10 on both Samsung and Sony Android 14.

**Comment by baslow** [comment]
I am experiencing what may be a related problem. I tried to start a Listed account today but, after a few seconds of churning, got no feedback that anything had happened -- the "Create New Author" button simply reappeared.

On the chance that an account had actually been created without my being properly notified I tried to post a note to Listed but received the message "No Listed account found".

I have a Standard Notes Productivity subscription and have gotten the same results trying to post from the Linux desktop app and the web app.

**Comment by effieeee** [comment]
Hi @MiloSam and @baslow  It looks like you were affected by the Listed outage last weekend, so we apologize for the inconvenience. Listed should be back up and running now, so you should find that your existing blogs will work properly, and you can also properly create new blogs on the app now.

For the issue with FileSafe though, I'm afraid that FileSafe is a deprecated component of the app at the moment, so it can definitely run into issues like this. If you no longer use FileSafe on your account either, you can remove it on the **Plugins** menu, under the **Manage Plugins** section:

![Manage-plugins](https://github.com/user-attachments/assets/3bf66843-f134-49ac-b3bf-b55383fada04)

**Comment by MiloSam** [comment]
Thank you very much Effie for your support.

I think you mentioned earlier that you're open to suggestions on how to improve Notes. Here are some suggestions / observations in order of how useful (needed) I think they are:

-  option to start at the bottom or at a top when opening a note. Maybe this option could be offered only for long notes or perhaps there could be a "go to the bottom" or a "go to the top" button once the note is opened. Some notes are very long so this is a really needed option
-  find/replace inside individual note
- Listed:  option to sort the blog posts in reverse order (ideally, it would be possible to add new posts in between old posts)
- Listed: option to control the length of a post excerpt (number of words)
- Listed: option to change the post title font and color
- Listed: option to remove the emojis from the bottom of posts

I hope you don't mind me sending these suggestions... Thank you for a great product and I hope that Proton change will only make your life easier!  🌟

Best regards,

Milos
+66860353103

Jul 19, 2024 10:34:06 PM Effie Beldia ***@***.***>:
