### ISSUE TITLE
Advanced Checklist not showing on iPhone mobile app

### ISSUE THREAD

**Issue by hausler89** [standardnotes/forum#3694]
**Describe the bug**
The content of an Advanced Checklist is not displayed on the iPhone mobile app.

**To Reproduce**
1. Create an Advanced Checklist on PC
2. Open on mobile
3. It's empty

**Expected behavior**
It's not empty.

**Screenshots**
![compare](https://github.com/user-attachments/assets/0b42eb46-27c9-4e86-b128-60d2ef38b11a)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 3.194.13

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 17.5.1
 - Version 3.194.11 (1103)

**Additional context**
Doesn't work with any theme.

**Comment by effieeee** [comment]
Hi @hausler89, I'm afraid this is a known limitation on the Advanced Checklist plugin at the moment, and it is also reported on #3609. I will be closing this as a duplicate, so please continue following #3609 instead 🙏
