### ISSUE TITLE
[Help Wanted] Can't un-nest a subtag/subfolder at top level

### ISSUE THREAD

**Issue by justyn** [standardnotes/forum#3696]
**Describe the issue**
I cannot un-nest a tag

**To Reproduce**
1. Go to 'Folders'
2. Drag a top-level folder onto another so that it get's converted to a sub-tag/sub-folder of that folder
3. Try to un-nest it so that it is a top-level tag/folder again
4. Cannot - everywhere you drag it, it becomes sub-tag/folder

**Expected behavior**
Ability to drag or select that the sub-tag be a top-level tag.
Potentially by dragging to top-level "Folder" label, or by dragging left, or by right clicking and being able to select if it is a sub-tag/folder of another.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - AppImage
 - Version 3.181.4

**Additional context**
It is driving me crazy after accidentally dragging a tag onto another tag.

**Comment by effieeee** [comment]
HI @justyn, you can remove the folder from its current hierarchy if you drag it to the bottom of your tag list, as shown below. However, we do understand that this can be tedious for users with very extensive tag lists, so we'll keep it in mind that this needs to be improved on the app's UI 🙏 

![image](https://github.com/user-attachments/assets/4bea521f-76b8-475a-87cb-f0986ff80caf)

**Comment by justyn** [comment]
> HI @justyn, you can remove the folder from its current hierarchy if you drag it to the bottom of your tag list, as shown below. However, we do understand that this can be tedious for users with very extensive tag lists, so we'll keep it in mind that this needs to be improved on the app's UI 🙏
> 
> ![image](https://private-user-images.githubusercontent.com/54989748/350454811-4bea521f-76b8-475a-87cb-f0986ff80caf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDY5MjMsIm5iZiI6MTcyMTQwNjYyMywicGF0aCI6Ii81NDk4OTc0OC8zNTA0NTQ4MTEtNGJlYTUyMWYtNzZiOC00NzVhLTg3Y2ItZjA5ODZmZjgwY2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE2MzAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZTJiMjAzNGRlN2UyMjI1N2U0NTk0MzM2NDgyMDg5YTgxNTQxNTQ5MjY0NWZkZWU5ODQzNmNmZmFkMjFmZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QKQf03f0LLYAgYfc-btCaB08RuO7r9OJqqUqfNAqKwc)

Phew! That works, thanks!
