### ISSUE TITLE
HTML tags not working in published note

### ISSUE THREAD

**Issue by JuneYubin** [standardnotes/forum#37]
Hello,

I'm currently using the Plus Editor for my notes. The editor itself works fine. However, for some reason, the HTML tags disappear once I publish the note: https://listed.standardnotes.org/utNzzhF

The note is supposed to look like this:
![plus-editor](https://user-images.githubusercontent.com/16415014/28568759-487d970c-7137-11e7-9bb2-bbf092ad38ef.jpg)

This only happens with the Plus Editor.

Is this a bug or is it supposed to be like this? Thanks for your help!

**Comment by mobitar** [comment]
Not sure I'm following..the listed extension doesn't understand HTML. It only understands Markdown.

**Comment by JuanjuanYin** [comment]
Ah okay, I didn't know that was the case. I was kinda hoping that I didn't have to use the markdown syntax. I'll use the Advanced Markdown editor then.

**Comment by mobitar** [comment]
If it's not too much trouble, you can use an HTML to Markdown converter found online. Google returns this: https://domchristie.github.io/to-markdown/

**Comment by TheodoreChu** [comment]
I think support for HTML is available now. I tried using the plus editor to highlight text and it's still there when I publish to Listed.
