### ISSUE TITLE
Better MacOS Integration

### ISSUE THREAD

**Issue by nikhiljha** [standardnotes/forum#370]
The default notes app can do a whole bunch of cool things...

<img width="265" alt="Screenshot" src="https://user-images.githubusercontent.com/2773700/48677005-5ce9a980-eb23-11e8-8e7f-0dabe52d98dd.png">

Notably, the ability to insert a photo or scan a document from a phone, and have it appear. The right click menu in Standard Notes doesn't have all the regular things I normally have.

**Comment by mobitar** [comment]
Hi @nikhiljha, please see our [Longevity Statement](https://standardnotes.org/longevity). We plan on being simple indefinitely.

**Comment by nikhiljha** [comment]
@mobitar Wouldn’t not hijacking the right click menu be simpler?

**Comment by mobitar** [comment]
We're not hijacking it. This is Electron out of the box behavior.
