### ISSUE TITLE
FailSafe Attachments Encrypting

### ISSUE THREAD

**Issue by mardomit** [standardnotes/forum#371]
Hi - I have upgraded to Extended after maybe a year of using the OOB SW and happy enough so far.

My issue is i am not yet able to attach anything to my created notes which was the point of upgrading really - i have linked my SN app to my Google account but whenever i attach anything, it just sits there encrypting getting nowhere - nomatter how long i leave it

any ideas anyone?

thanks
matt
<img width="422" alt="attachments hang encrypting" src="https://user-images.githubusercontent.com/29815856/48725321-bfc26a00-ec23-11e8-89f9-1a3cceec063a.png">

**Comment by mobitar** [comment]
Hey @mardomit, how large is the file you're trying to upload? Also, what browser are you using? Files should be limited to 50MB, but if you're on a low-spec computer, even that may be too much. Try testing with a very small file (< 1 MB) just to see if your Google Drive integration is working properly. If same issue, try using another browser for the test. We just want to determine whether it's an integration issue, file size issue, or browser issue.

**Comment by mardomit** [comment]
Hey Mo. Thanks for the reply on this

Browser is Chrome which is latest release. File size tested were between 50k and 3MB

Two different laptops used with one being OOB Lenovo T480s. Lots of resource. 

Just about to jump on a plane so will try your suggestion when I reach my destination and report back

Cheers
Matt

**Comment by mardomit** [comment]
Hi Mo

Okay i have ran the tests again on a Windows 10 box on Lenovo T480 and and Windows 7 box on Lenovo T440s.  I have ran the tests using both my wifi connection through my cisco firewall and with my 4G connection on my phone.  I also removed my IE (sorry it wasn't chrome earlier) connection used to setup up my DropBox link and relinked it with Chrome - issue remains with all tests - program just continually tries to encrypt with only closing the program solving the issue - do you have a test dropbox i could use maybe to rule out my google drive being an issue?  for info, the file i was attempting to attach was under 3kb and was a text file.

regards
matt

**Comment by mardomit** [comment]
Okay Mo i have tried now to attach a file with 3 laptops but this time to my Dropbox account - the two lenovos and my macbook pro - this is a top end MacBook with 1TB ssd 16Gb RAM, i7 CPU - same result - encrypting does not finish - version of standard notes i am using is 2.3.12

regards
matt

**Comment by mobitar** [comment]
Hey Matt, thanks for running these tests. Can you do this on the desktop app:

1. Click Help -> Toggle Error Console. Then make sure the Console tab is the selected one.
2. Attempt to upload another file. Do you see any output there in the console at that point? Anything in red? If you could attach a screenshot that could be helpful.

**Comment by mardomit** [comment]
here you go Mo - only thing i can see on the console is the date and time are wrong - would be a big issue in my line of work with encrypted calls and certs - not sure if this is important - my laptops have the correct date and time
![2018-11-21 21_34_46-](https://user-images.githubusercontent.com/29815856/48869606-c1339400-edd5-11e8-81ad-efff84f7d06d.png)

**Comment by mardomit** [comment]
have you had a chance to take a look at this Mo?

cheers
matt

**Comment by mobitar** [comment]
Indeed, that seems to be the problem right there. Looking at the code, it looks like it's looking for some credential, but it's missing. In FileSafe, under Keys, what do you see? If nothing, try creating a new key via Create New and try again.

If you do see something, try deleting it, and creating a new key. (Make sure you don't have any existing uploaded files with that key.)

**Comment by mobitar** [comment]
Ok great! Will need to find out the underlying cause, but good to know it's at least treatable for now.
