### ISSUE TITLE
Visual glitch on Folders extensions

### ISSUE THREAD

**Issue by amelandri** [standardnotes/forum#372]
When using the Folder extensions on Windows, an horizontal scrollbar is displayed when hovering a tag, even if it's not necessary.

Rasizing the toolbar does not change the behaviour.

![2018-11-20 10_38-notes](https://user-images.githubusercontent.com/140700/48764711-ba5f3100-ecb0-11e8-9399-e3c41da6d9a4.png)

**Comment by mobitar** [comment]
This is a known issue. Hoping to get a fix out soon.

**Comment by TheodoreChu** [comment]
Closing this because it seems fixed
