### ISSUE TITLE
[Feature Request] - Android: copy data from locked note

### ISSUE THREAD

**Issue by kevinm1000** [standardnotes/forum#375]
Currently on Android, when a note is locked, you cannot select text to copy it.  For instance, if I store a password, I have to unlock the note in order to highlight it and copy it.

It would be great if even though the note is locked, you could still copy text from it.

**Comment by mobitar** [comment]
Indeed, a known limitation on Android for now. Keeping an eye out for good solutions for this one.

**Comment by effieeee** [comment]
Already possible on classic and new mobile experience
