### ISSUE TITLE
Toggle "Show Notes Panel" not working

### ISSUE THREAD

**Issue by RamonAbudAlcala** [standardnotes/forum#3754]
**Bug Description**
The toggle "Show Notes Panel" does not work at turning the pannel on when it is off. 

**Expected behavior**
Toggling on the "Show Notes Panel" should make the notes panel visible.

**Web App**
 - Browser: Firefox
 - Version: 130.0.1 (64-bit)
 - Web App: 3.195.3 (Docker Self Hosted)
 - Workaround: Toggle on -> Refresh webpage.

**Desktop App**
 - OS: Linux
 - App: 3.195.1 (Flatpak)
 - Workaround: Toggle on -> Menu -> View -> Reload.

**To Reproduce**
1. Open the app
2. Toggle off: Notes Pannel is hidden.
3. Toggle on: Nothing happens.

**Comment by marcosdiasalves** [comment]
Same on MacOS desktop app. Version 3.195.12.
Once hidden, there is no way to restore Notes panel other than closing and restarting the app or reloading using View & Reload.

**Comment by marcosdiasalves** [comment]
WIll it be fixed on MacOS app too?
A single press of "⌘ ⇧ L" closes Notes Panel, but I have to press it 3 times to reopen the panel; all the time. Easy to reproduce.

**Comment by amanharwara** [comment]
Which version are you using? Should be fixed in [v3.195.13](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.195.13)

**Comment by marcosdiasalves** [comment]
I was on 3.195.12; just upgraded to 3.195.13 and it is perfect now.
Thank you.

**Comment by RamonAbudAlcala** [comment]
Linux (flatpak) and self-hosted web apps seem good to me too :) Thanks!
