### ISSUE TITLE
a question about the plus editor 

### ISSUE THREAD

**Issue by sviii** [standardnotes/forum#378]
Every time I press "enter" button under the Plus Editor,  there will be larger leading present. Could I make the leading between paragraphs just as narrow as that between lines within the paragraph?

**Comment by mobitar** [comment]
Yes, you can do shift + enter.

**Comment by sviii** [comment]
Thanks!


| |
眭润研
邮箱：suirunyan@126.com
|

签名由 网易邮箱大师 定制

On 11/27/2018 16:25, Mo Bitar wrote:

Yes, you can do shift + enter.

**Comment by Spin-Oza** [comment]
Hello !

I had the same problem and found the solution here, thank you @Mobitar !
(It would be great to find this kind of shortcut informations in the StandardNote app itself).

I have another question about tabulations in Plus Editor extension,
You can see that when you do tabulations on the Plain Editor, it's fit automatically to be aligned with other tabulations up or below,

<a href="http://www.noelshack.com/2019-10-2-1551781457-capture-d-ecran-2019-03-05-a-11-22-25.png"><img src="http://image.noelshack.com/minis/2019/10/2/1551781457-capture-d-ecran-2019-03-05-a-11-22-25.png" border="0" alt="1551781457-capture-d-ecran-2019-03-05-a-11-22-25.png - envoi d'image avec NoelShack" title="1551781457-capture-d-ecran-2019-03-05-a-11-22-25.png"/></a>

But in Plus Editor, it's not possible to have a clean centered marging tabulations :

<a href="http://www.noelshack.com/2019-10-2-1551781457-capture-d-ecran-2019-03-05-a-11-22-45.png"><img src="http://image.noelshack.com/minis/2019/10/2/1551781457-capture-d-ecran-2019-03-05-a-11-22-45.png" border="0" alt="1551781457-capture-d-ecran-2019-03-05-a-11-22-45.png - envoi d'image avec NoelShack" title="1551781457-capture-d-ecran-2019-03-05-a-11-22-45.png"/></a>

Is it normal ?
For my kind of notes, it's very binding...
Thank you,
Sorry if my English is not perfect...

**Comment by Spin-Oza** [comment]
> Hmm strange, are you using monospace font in first screenshot?

Yes I was using monospace.

> That might be why. You might need to switch fonts in the Plus editor.

I tried with Arial and Verdana in Plus Editor but it's never as clean as with the Plain Editor...

**Comment by mobitar** [comment]
We'd have to see if it's possible to add monospace to the font selection of the Plus Editor. Paging @bryvin ;)

**Comment by bryvin** [comment]
@mobitar Thanks for the page.

I just tested a few things by using the Inspector and noticed the Plus Editor doesn't really handle 'tab' the same way as the plain editor textarea. Unfortunately the Plus Editor (which is based on Summernote I believe) literally places &nbsp;&nbsp; when you hit tab. This means it doesn't act like the tab functionality inside of the textarea.

Meaning you cannot tab and then go back to the left side and type without effecting the right side of the tab. In the Plus Editor this will literally move the entire line over as it's just adding new characters and not replacing the 'space' from the tab with the characters you're typing.

Let me know if anyone needs clarification on that.

It is definitely possible I think to add a monospace option however. While that will still have the same issue described above, the spaces and characters will obviously be the same width so you can add or remove spaces to make it line up exactly. Let me know if that should be a thing on it's own?

**Comment by Spin-Oza** [comment]
@bryvin , Thanks for the precise reply !
But then,
Why the way that Plus Editor handle the tap function would not be fixed ? making it act like the tab functionality inside of the textarea ? Not possible I suppose ?

**Comment by bryvin** [comment]
@Spin-Oza It may be possible to change the behavior of the tab key, but Summernote is a 3rd party editor that isn't actually build by mobitar. 

I'd have to look deeper into the options there and will see if I can find anything but chances seem slim at first glance.

In the meantime I will try to find some time to add the monospace font option at least.

**Comment by mobitar** [comment]
Good find about the tabbing. Surprised no one has brought that up before. A few people have brought up the font thing though. Especially that, on macOS at least, the editor will initialize with "system-ui" font, but if you change that font, it's no longer available in the dropdown:

<img width="384" alt="screen shot 2019-03-07 at 10 18 01 am" src="https://user-images.githubusercontent.com/3277844/53971336-57a86e80-40c2-11e9-968a-c0c2ff6998f2.png">

If we could figure out a way to add both monospace and system-ui, that could be a solid improvement on the editor.
