### ISSUE TITLE
Safari on iPad - resize columns 

### ISSUE THREAD

**Issue by dw00600** [standardnotes/forum#379]
3 panels when using folders (tags, list of notes, note window).

I resized the folder window quite wide and now can’t seem to figure out how to slim it down again.   Dragging the vertical bar does not seem to work.

I’ve logged out, closed the tab, and when logging back in, no change.

What am I overlooking?

Thanks!

**Comment by mobitar** [comment]
The web app isn't optimized for mobile, so the behavior is as-is for the most part. You might be able to sign in to your account on web/desktop, adjust the panels again, then refresh on mobile safari.

**Comment by mobitar** [comment]
Definitely, it would be great if the mobile app were 1:1 with desktop/web. And perhaps we optimize the web app for tablet at some point. Will just take time :)

**Comment by dw00600** [comment]
Completely understood!

**Comment by dw00600** [comment]
Have an update!
This is an iPad Pro 12.whatever inches it is.
Problem exists in Safari and Firefox.

If I turn on the Dynamic Theme, columns are where you expect them.
When deactivated, the folder column takes 1/2 the width of the screen.

Somehow regular Themes are displaying themselves wrong, but with Dynamic are ok.
If worse comes to worse, maybe we delete my account and start anew?

**Comment by dw00600** [comment]
Still an open issue, I hit the wrong button.  Argh!

**Comment by dw00600** [comment]
Mo's suggestion works!
https://github.com/standardnotes/forum/issues/379#issuecomment-442525543

I swear I tried this.    What I did different this time was log out of all devices, sign into PC version, move, sign out.    

NOW when I sign in on the iPad (Safari browser), we're good.

**Comment by mobitar** [comment]
Glad to hear!
