### ISSUE TITLE
Standard Notes Requires Admin to Launch on Windows

### ISSUE THREAD

**Issue by aaronblair** [standardnotes/forum#381]
This issue is for those who wish to use Standard Notes within the corporate environment where often you cannot install applications that require administrator permissions. Standard Notes seems to install without issue, but on initial launch requires 'wmic.exe', which is an administration cli command.

Is it possible to build the Windows binary such that it doesn't require 'wmic.exe' or other administration functionality? Otherwise, it's just the web interface for those in a locked down environment.

![image001](https://user-images.githubusercontent.com/1298050/49314973-58b97680-f4a9-11e8-9cd5-7bd7d1781eb8.png)

**Comment by mobitar** [comment]
Not sure how much control we have over this with electron-builder. I doubt this would be possible. In general though, the web app is 1:1 feature-wise with the desktop app.

**Comment by aaronblair** [comment]
The odd thing is that I don't get this with any other electron apps, like Todoist and Slack. Maybe the later versions of Electron don't require this.

**Comment by mobitar** [comment]
I wonder if it's related to this: https://github.com/electron-userland/electron-builder/issues/864

Another thing it could be is autoupdate, if you're perhaps installing an older version and it needs to update right away. Just a theory. I haven't seen this before so we'll have to narrow it down to find out exactly what the underlying process is.

**Comment by TheodoreChu** [comment]
Closing this because I think the latest versions of the desktop app (v3.5+) do not require admin to install or use: https://standardnotes.org/download
Please comment or create a new issue if the issue persists
