### ISSUE TITLE
Can extended editors be used offline on iOS?

### ISSUE THREAD

**Issue by christianhans** [standardnotes/forum#384]
Hi,

I saw that this is not possible on Android. Is this possible or planned for iOS?

Christian

**Comment by mobitar** [comment]
This is not possible on mobile currently. Remains to be determined whether it will be in the future. Will have to investigate it more thoroughly.

**Comment by christianhans** [comment]
Thank you for that explanation! Is it possible to use themes offline on iOS?

Best
Christian

**Comment by mobitar** [comment]
Yes, themes will work offline :) At least, the last selected theme, since that's downloaded to disk. If you've never selected a theme before, then it won't work, as it wouldn't have been downloaded.

**Comment by leoboulton** [comment]
> This is not possible on mobile currently. Remains to be determined whether it will be in the future. Will have to investigate it more thoroughly.

Please consider it with priority. Common use case: edit notes from your phone or iPad while on a plane. I personally work during flights, and don’t like a full laptop with me. So an iPad or my phone are great for working on writing notes, reminders, etc. I learned this way that extension editors aren’t supported offline on my last trip: opened a Simple Markdown note and it was blank.

**Comment by IgiMar** [comment]
I second the request of having the possibility of using extensions offline. In whichever way: hardcoded into the app or downloaded and stored to disk but still available even after a re-start or the access to a note NOT using a certain editor. While markdown text may still be intelligible offline, HTML based one not. In this case offline becomes a show-stopper.

**Comment by effieeee** [comment]
Editors now usable offline on new mobile UI
