### ISSUE TITLE
UX feedback

### ISSUE THREAD

**Issue by andaag** [standardnotes/forum#385]
I'm considering moving from simplenotes to standardnotes. Because it looks like the sync in simplenotes is not entirely reliable. This is pretty damn critical, but when switching I'm starting to feel some pain.

I feel like the UX isn't comparable...

![solarized](https://user-images.githubusercontent.com/826023/49571400-6a7f9b80-f939-11e8-81ed-717efbf583ab.png)

This is an example with solarized theme. 

Some things to point out:
- Simplenotes has one title, it's the first line of the document. This seems a lot easier to me than to have a title that's essentially "somewhere else" than the document start. Maybe at least set the note title based on the first line - if a note is without a title?
- The action bar in standardnotes is taking a lot more space, and is a lot more visible. With simplenotes it's far more out of the way, and it puts more focus on the content.
- Same with the all notes list. There's just a lot more colors and distractions in there than there is in simplenotes.
- Hiding the sidebar is a lot more natural in simplenotes. In standardnotes you doubleclick on the resize option, which is akward from a UX perspective. It also produces a single (dark in this theme) line on the side of the screen which is quite ugly. In a lot of the dark themes this line is grey. (See later screenshots)

## Concrete things I feel would improve the UX
- Removing the gap between the note title and the note itself. 
  - For example this the options/editor/actions/session history toolbar items could be changed to icons and be put to the right of the title itself. It's very unlikely I need a title the full width of the screen. And for most things I'd rather focus on the content than this toolbar.
  - Making the title part of the content, like simplenotes does. And moving the toolbar further up, so it's less visible, and feels more separate from the content itself.
- Making a show/hide sidebar a button, instead of the akward doubleclick on resize handle flow.
- Make the tags hidden by default. Most of the time I'm working out of the recent documents. And I don't need this open. It can have less focus by default.

## Screenshot of grey sidebar minimization color:
![midnight](https://user-images.githubusercontent.com/826023/49571515-d3671380-f939-11e8-96ea-35cc8a8f830b.png)

## Screenshot of simplenotes tag view.
![extended sidebar simplenotes](https://user-images.githubusercontent.com/826023/49572664-8c2e5200-f93c-11e8-9da9-cbe0b942a1c8.png)

**Comment by mobitar** [comment]
Hey @andaag, thanks for your feedback. I don't necessarily think that "this app is not like Simplenote" is valid feedback, but good nonetheless to hear your thoughts as a Simplenote transfer. We definitely have a unique design language, and it may not be right for everyone. Best to spend some time with it and not immediately be taken aback by first impressions, especially if you've come from using another app for several years, and only trying ours for a few days.

**Comment by myreli** [comment]
I will close this issue because it has been inactive and/or doesn't fit any more within recent versions. This is an effort of triaging older issues and shifting focus to current reports. Thanks!
