### ISSUE TITLE
Sheet issue? Insert buttons do not work

### ISSUE THREAD

**Issue by mmlmrx** [standardnotes/forum#386]
Hello,
   I know Sheets is in beta, but I wanted to report an issue - the insert buttons do not work.  They all add rows to the bottom and columns to the right.  I was trying to insert rows at the top of a sheet.  I'm on Firefox/Win10 if that helps.

Thanks!

**Comment by mmlmrx** [comment]
Ahh, okay, thanks.  

That leads to a different question then - has anyone proposed a Lists/Sheets extension where each row could be a note that is saved as in JSON format?  I'm not sure how you would invoke a particular tag to display in list/sheet mode though - maybe a special DisplayAsList subtag?  

I wish I had the programming chops to play around with this stuff - maybe someday...

**Comment by mobitar** [comment]
I'm not sure I'm following. So each row would be an actual note that you have in Standard Notes, and modifying the row in the Sheets extension would modify the underlying note in Standard Notes? If so, interesting idea. Seems possible, but why?

**Comment by mmlmrx** [comment]
Hmm.  I guess I was thinking it could be a alternative way to implement sheets than using an external library.  In my limited understanding of Couchbase, each document is an entry, and the JSON contents dictate the columns of data and their values.  The main tag could hold any overhead data like column widths, but it wouldn't have as much functionality as your current library - so it is more of an intermediate lists feature.

I guess the other discussion we had about searching tags would be just as functional, and for anything smaller than that, people would use the Plus editor and create small tables.  So...maybe I just talked myself out of the idea?  :-)

Can I ask what library it is  you are using for Sheets?  Maybe I can do some digging...

**Comment by mobitar** [comment]
It's really the UI intricacies that make spreadsheets hard. Formulas, formats, sizes, colors, etc. We're using. We're using [Kendo UI](https://www.telerik.com/kendo-ui) for the spreadsheet.

**Comment by mmlmrx** [comment]
Well, no surprise I guess, but I couldn't find anything useful. I didn't see any errors in the console to narrow the issue down, and no one on their forums seems to be having issues with inserts either.  It's too bad, because without inserts the Sheet functionality is very limited. But, that is why it is in Beta, right?  :-)  

Anyway, wet me know if you can think of anything I could do to help, as having Sheets would be very useful for me - but I can get by with the tables in Plus editor.  Thanks again!

**Comment by mobitar** [comment]
The best workaround for now is just to copy/paste the entire sheet and move it one line down if you want to add rows to the top.

**Comment by mmlmrx** [comment]
Thanks!  Yes, I can do that with one or two things, but my lists of books and games are both too long for that to be feasible, and I'm struggling with deciding how I can split them up without losing functionality.

**Comment by sambosek** [comment]
Just to second this, loving everything else - being able to add rows and columns would really be useful!

**Comment by JaspalSuri** [comment]
I've taken note of this for discussion by the team at some point in the future. Thanks for bringing it to our attention!
