### ISSUE TITLE
How do I make the app look like your screenshots?

### ISSUE THREAD

**Issue by bdsams** [standardnotes/forum#389]
Hi,

I have installed the Advanced markdown editor, I am trying to make it look like your screenshot (attached) but cannot figure out how to do so? How do I hide the All Notes, Tags, and all the other stuff to make it look like the attached screenshot?

Thanks.
<img width="488" alt="chrome_2018-12-12_08-59-43" src="https://user-images.githubusercontent.com/4255733/49874954-d193c900-fded-11e8-81e0-3084cd993179.png">

**Comment by mobitar** [comment]
Hey @bdsams, the screenshots here are meant to reflect the editors in isolation. However, you can still accomplish what you want using the "No Distraction" theme, which will eliminate most UI except for the editor panel. 

You can also drag or double click the vertical resizers to hide the tags and notes column.

**Comment by bdsams** [comment]
Ah dang, thanks for the response...feat request, enable the option to make it look like the screen shots.

**Comment by mobitar** [comment]
Here's how the app looks with the No Distraction theme enabled:

![screen shot 2018-12-12 at 9 41 39 am](https://user-images.githubusercontent.com/3277844/49880629-2b968d80-fdf2-11e8-9cea-c448a3ac7e5c.png)

**Comment by bdsams** [comment]
This is closer to what I was looking for, the minor issue is that you have to disable the view to regain access to searching navigation. If you could add a button like the attached image that expand the panel, that would probably solve my UI challenges.
<img width="87" alt="simplenote_2018-12-12_10-47-35" src="https://user-images.githubusercontent.com/4255733/49881057-6c46d480-fdfb-11e8-9f6d-4f1fdf99ba64.png">

**Comment by mobitar** [comment]
Yeah for sure, managing themes right now does require a bit of steps. Hoping to make this a 1-click ordeal in the near future.

**Comment by TheodoreChu** [comment]
Closing this because turning No Distraction on/off is available as a 1-click operation. For keyboard shortcuts, please see https://github.com/standardnotes/forum/issues/318
