### ISSUE TITLE
[feature request] Persistent search bar on iOS app

### ISSUE THREAD

**Issue by ben-richardson** [standardnotes/forum#392]
Does anyone else dislike the search bar being pinned at the top of the notes list? 

Often I scroll a few pages down to see if I eyeball the note I’m looking for, or I have been editing multiple notes and am deep down my list. And then I decide to search for something, and have to scroll all the way to the top of the list for the search bar. 

I would prefer either a persistent search bar, locked to the top of the UI, or a button (somewhere between Filter and New?) to bring it in to view, no matter where in my notes list I am. 

Anyone else feel similarly?

**Comment by SiGamma** [comment]
I think that tapping the top edge of the screen to quickly bring you to the top of the list (and reveal the search bar) works just fine, and it's pretty standard iOS behaviour. Most apps that I've used behave like that, including most stock apps (Music and Photos excluded, those have separate tabs for search).

**Comment by ben-richardson** [comment]
Ah yes, my bad, completely forgot that behavior. Guess I’m not using many apps without dedicated or persistent search fields. Thanks for the reminder, that’ll help for now!
