### ISSUE TITLE
Import Issue (# Notes + Labels)

### ISSUE THREAD

**Issue by sahilc0** [standardnotes/forum#393]
Hello, so I just imported a bunch of .md and .csv notes from Notion into SN. However I ran into a couple issues:

1. During the import process, there were 400 files (.csv and .md) but the import process only imported 100, and then the app froze. I had to kill it and restart, and there was only 100 imported. Any ideas? I was thinking maybe SN doesn't support CSV import?

2. With those 100 imported notes, there was no label on them (I wanted to give it a label, like "Archive"  to keep them separate). Would this be possible to label all 100 of these notes?

Thanks!

**Comment by mobitar** [comment]
How did you import the 400 files? The only way that would work is if you used the converter tool at dashboard.standardnotes.org/tools. You have to use the Plaintext -> SN converter, and I don't think that will work for .csv. After that, you'll get one resulting file that you should import into SN. 

There's no way to apply a default tag to imports, but this is something I hope to add in the near future.

**Comment by effieeee** [comment]
See also: https://github.com/standardnotes/forum/issues/181
