### ISSUE TITLE
Capture and swallow ctrl+s

### ISSUE THREAD

**Issue by g-harel** [standardnotes/forum#394]
I have a habit of obsessively pressing `ctrl+s` when I'm writing text, and it makes the "Save page" dialog come up. Google Docs has a feature where it just gets ignored, which would be nice to also have in Standard Notes.

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/1511

**Comment by atmoio** [comment]
This is done in the latest release. 

Keyboard shortcuts are now available: https://github.com/standardnotes/forum/issues/1511#issuecomment-1322276205
