### ISSUE TITLE
Any Free Plans for Open Source Non-Profit Organization?

### ISSUE THREAD

**Issue by CodingPurple** [standardnotes/forum#395]
Any Free Plans for Open Source Non-Profit Organization?

It would be great if you provide us one!

We are Open Source https://gitote.in
Source Code: https://gitote.in/gitote/gitote

**Comment by mobitar** [comment]
We don't necessarily have any kind of structure set up for this. Best to email me about this, as it can be easily mistaken for self promotion ;)
