### ISSUE TITLE
Highlighting problem with Code Editor

### ISSUE THREAD

**Issue by nauxnim** [standardnotes/forum#399]
https://imgur.com/a/of2pC1N

Highlighting in the code editor won't show on lines with text in it. Problem is when I highlight a small part within the area with text, I can't tell where is highlighted.
If I highlight many lines I can still see from the empty highlighted spaces at least which lines are included in the highlight.

This happens for themes Futura and Titanium, and the default themeless view. For Midnight and Solarized dark, the text area is highlighted white while the non-text area is highlighted as the theme colour.

**Comment by mobitar** [comment]
This should now be fixed in Code Editor 1.2.5. Be sure to update from the Extensions menu on desktop and clear your cache on web, if it doesn't take effect automatically.

**Comment by nauxnim** [comment]
Oh yea it's fixed! Thank you. I cleared cache immediately after the new update but saw this issue, so didn't think it was the update. I should have given it more time.
