### ISSUE TITLE
There is a free extensions to install?

### ISSUE THREAD

**Issue by NESTicle** [standardnotes/forum#4]
Hi guys.

I need to know if standard notes has free extensions to install?, thank you so much

**Comment by mobitar** [comment]
No, no free extensions. But you're free to create or host your own: standardnotes.org/developers.

**Comment by mobitar** [comment]
The Share extension is now free: https://standardnotes.org/extensions/share

**Comment by junghoocho** [comment]
I am trying to learn how to create and host my own extensions following the tutorial at <https://github.com/sn-extensions/docs/blob/master/Components API Documentation.md>

I am able to run my SimpleHTTPServer, and access the component through my browser. But when I try to import the extension through the URL <http://localhost:8000?type=component&area=editor-stack&name=Word Counter>, the Mac desktop app says "Extension successfully installed" but it does not show any new extension. 

What am I doing wrong? Thanks!

**Comment by LuxoftAKutsan** [comment]
It is not obvious if extensions are applicable for ios and android applications.

**Comment by mobitar** [comment]
Only editors and themes are compatible on mobile. Actions and other extensions aren't.

**Comment by LuxoftAKutsan** [comment]
@mobitar thank you for the answer
