### ISSUE TITLE
Eliminating the note title

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#40]
Instead of having a title selection. Have the first line of the note itself be the title (this would only apply to some editors), would be much more convenient. 

Also made a post in [#130](https://github.com/standardnotes/web/issues/130)

**Comment by mobitar** [comment]
This could come in the form of an external editor. For the built in editor, it's best to do it the standard "file name" and "file contents" that's universally understood.

**Comment by ClarkeCC** [comment]
@mobitar yeah maybe have a separate editor with this feature. Very good point, haven't thought about if the notes get exported.

**Comment by midi** [comment]
Standard Notes on iOS skips straight to the note content, I would love to see the same behavior on the desktop app.
I'm aware of the philosophy around feature requests. 
Right now it is inconsistent. Please don't force note titles on iOS now :)

The behavior of the iOS app is pretty nice I think, it's still possible to set a dedicated title if you want, but by skipping directly to the content, data entry is faster. There's no note title then really and a logic to use the first line of the content as title, if no dedicated title is entered could strike a middle ground. But even without that, I really like the current behavior.
I'd argue that not having a separate field for note titles is actually more simplistic :)

**Comment by mobitar** [comment]
There is note title in iOS. You're probably seeing the external editor popup, which doesn't have a title. I don't think we'll be removing the title field..
