### ISSUE TITLE
How to fully self-host Standard Notes?

### ISSUE THREAD

**Issue by alexbakker** [standardnotes/forum#400]
First of all, thank you for Standard Notes! I subscribed to Extended and am very happy with it so far.

I'm interested in fully self-hosting Standard Notes on a private network, where connections to the internet are blocked for clients. So far, I've gotten the file server and web application up and running. The only missing piece of the puzzle is extensions, because clients reach out to the internet to retrieve and update them. I saw that the extensions server [was open source in the past, but was made private because many users were running into issues](https://github.com/standardnotes/web/issues/38#issuecomment-284019807). Have you looked into opening it up again since then?

After a quick look, it seems like the Extended activation code is just a base64 encoded URL that points to a JSON file. I think I can infer enough information from that to write my own private implementation of the extensions server, but I'd rather not waste time on keeping that up-to-date.

I understand that the Extended subscriptions fund your work on Standard Notes and that making the extensions server easily self-hostable could potentially have a negative impact on that, so I'm interested to hear your thoughts on this.

Thanks, and happy holidays!

**Comment by mobitar** [comment]
Hey @alexbakker, thanks for your support! Glad to hear you're enjoying it. Indeed, an extensions server is basically the same set of instructions found on [docs.standardnotes.org](https://docs.standardnotes.org/extensions/local-setup) for publishing one extension, but just publishes multiple extensions. The rest is just business logic to handle subscriptions and expirations, etc. Extensions are our main source of income, so you're right in that it's a sensitive area for us. Apart from the fact that it's still not currently in a state to be self-hosted, it's not clear how this would affect our business long-term. It's still too sensitive a topic. Once we outgrow that sensitivity where losing would-be paying customers to the self-hosted world would be negligible, I'm sure I'll have less resistance to working on a public implementation.

**Comment by alexbakker** [comment]
Fair enough, that's totally understandable. Thanks!
