### ISSUE TITLE
Posting to Listed.to – unexpected link name

### ISSUE THREAD

**Issue by greiggy** [standardnotes/forum#401]
My account allows extensions and I have installed the Listed extension and posted to it.

I have attempted to set it up to use the URL/username
listed.to/@iangreig

However, posts appear, but at a default address which I didn't choose, and which is not shown in the list of authors
listed.to/authors/4840

I have attempted to uninstalled/reinstall the extension, and set the preferences for Listed,  but clearly I am missing something. How can I set a meaningful username?

**Comment by mobitar** [comment]
Do you have two different Listed installations by any chance? You can check in Extensions to see if you have Listed appear multiple times. If so, click the ... next to each one and rename it something unique. This way, you can identify which one points to which blog, and delete the one you don't use anymore.

**Comment by greiggy** [comment]
Hi Mo,

I have one Listed extension installed.

When I click on the ... I get "This extension does not support local installation"

I get an option to rename, which seems to affect the name which is 'Listed'.

None of which makes any sense to me.

Thanks for your help so far. --IanG

Ian Greig

**Comment by mobitar** [comment]
What you should probably do is just update your Settings for the Listed installation you do have access to, via the Actions menu. I can tell you that you do indeed have two separate accounts. /@iangreig is a totally different account than authors/4840. If you've lost access to your original, I can restore that for you if you shoot me an email at mo@standardnotes.org. Otherwise, you can update the one you do have access for to the settings you like.

**Comment by greiggy** [comment]
On the Actions menu, I have attempted to update my settings (to username and display name 'iangreig') on the form, followed by 'Save'. I have attempted this a number of times. The changes are not applied – which is basically why I have applied to the forum for help.

Mo, if you can change it for me, please feel free. There's nothing of value on there yet, nothing confidential. 

Ian Greig

**Comment by TheodoreChu** [comment]
Hi Ian, I visited your listed blog and the link behavior I see is expected. In the Settings, the display name is the name of your blog and the name that will appear on the Listed.to front page. Your username is @iangreig and is used for post URLs. Please let us know if you have any more issues. 🙂
