### ISSUE TITLE
Mac Desktop App Always Disappears

### ISSUE THREAD

**Issue by macpatrick** [standardnotes/forum#402]
Love the app, but on Mac Desktop, the app is nowhere to found and I have to redownload it.  I've done this four times.  My notes sync have I download the new version but it's frustration that it disappears.  I even put it in the dock and upon restart it shows a "?"

**Comment by mobitar** [comment]
Strange. Can you describe the exact steps you take after you download the app? What you should do is after you download the app, drag and drop it to your Applications folder. It could be that you're keeping it in the temporary mounted location that would go away after restart.

**Comment by macpatrick** [comment]
Ok I’ll try that.  Thanks
