### ISSUE TITLE
Quick tag issue

### ISSUE THREAD

**Issue by mxng** [standardnotes/forum#403]
https://imgur.com/3kYbu91

After inserting a tag, newly typed tag in the input will have the first couple of characters removed.
For example, if I inserted a tag 'account' and typed 'singapore' very fast, 's, i' may be deleted and I end up typing 'ngapore'.

**Comment by mobitar** [comment]
Yeah, I see what you're saying. I can replicate this behavior. Thanks for the heads up!

**Comment by effieeee** [comment]
No longer occurs with native version of quick tags
