### ISSUE TITLE
If first note in the list is protected it causes the passcode popup to appear every time

### ISSUE THREAD

**Issue by mxng** [standardnotes/forum#406]
As per title. Currently, I have a pinned protected note. Every time I launch the app or click any tags that will show my notes with the first note in the list being a protected note, it will show the passcode prompt. 

Is there a way to stop the prompt from coming, and only when we click on the protected note?

This is probably happening because the viewer needs to show the content of the first note when I launch the app or click any tag, but since the first note is a protected one the passcode prompt will keep showing. For now I am just pressing 'cancel' every time it comes up when I do not need to view the protected note.

Still glad you added the protected notes feature though! :)

**Comment by mobitar** [comment]
Will have to think of a workaround. For now, you'll either have to find a way to make the note not the first one in the list, either by changing the sort order or unpinning. You can also choose to Remember For 1 hour so that it only asks you once in a given session.

**Comment by iedd** [comment]
Related, if a note is pinned (but not protected), and a protected note is also pinned (but second in the list according to most recently modified), this issue can happen. Leads to requiring user to enter passcode twice then automatically selecting the pinned+protected note. Thanks for all your efforts!

**Comment by effieeee** [comment]
Fixed, if first note(s) is/are protected, app opens succeeding note instead
