### ISSUE TITLE
Sync issue: some notes won't sync Android vs Web

### ISSUE THREAD

**Issue by lxnow** [standardnotes/forum#408]
Use web version, windows client and android client. At least two notes haven't sync'd properly between the web version and the android client. However, some notes do sync, i.e. new note on Android showed up on the web version. But those two aforementioned notes (about a week old) did not update (or show up in the case of the first note since it was newly created on the web app).

**Comment by lxnow** [comment]
Signed out from Android app and signed in again. Resynced all notes. Seems complete. Will see if this happens again

**Comment by mobitar** [comment]
Hmm strange. Usually if there is an error syncing, those items will be queued up for the next sync. It will keep trying until it successfully syncs. Also, I've had a few users who thought they had sync issues but ended up that they were in the wrong tag, or sorting by title or date modified, when they were expecting date created. Did you happen to change your password recently, or any other unique circumstances? And was it any particular problem that seemed to miss syncs? Or was it bidirectional? That is, did notes you create on web not show up on Android, or did notes created on Android not show up on web, or both?

**Comment by lxnow** [comment]
>  Did you happen to change your password recently, or any other unique circumstances? 

Nope.

> And was it any particular problem that seemed to miss syncs? Or was it bidirectional? That is, did notes you create on web not show up on Android, or did notes created on Android not show up on web, or both?

A note created *and* a note modified on the web app did not update on the Android app. Weirdly, newer notes that I created on the Android app updated fine on the web app. I also use a Windows client if that helps.

**Comment by mobitar** [comment]
Hmm..could be network issues on the phone. Or, perhaps, if you did a sync, then closed the app while it was downloading a heavy set of changes, that may cause some inconsistency. We don't have background saving privileges currently, so the app has to be in the foreground to successfully complete a sync. That may be what happened here. A sign out and sign back in would fix this. I haven't heard this issue before, so I'm only speculating. Would require more reports to really form a picture of how this could happen.

**Comment by TheodoreChu** [comment]
Closing this because sync was greatly improved in the 3.5 update. Please comment again or create a new issue if you have more problems with sync
