### ISSUE TITLE
'Session expired' block prevents opening on Windows 10

### ISSUE THREAD

**Issue by greiggy** [standardnotes/forum#411]
On my Windows 10 installation I am prevented from getting into SN by a persistent flickering pop-up with "Your session has expired... please log in..." which I cannot OK, kill or cancel in any way. It also prevents me getting into the account area. To kill SN via the Task manager is the only recourse.

I have tried deleting and making a clean installation, with Windows restarts in between.
I have ensured no other instances are running on my Mac and iOS devices. The same account works fine on Mac and iOS.

**Comment by mobitar** [comment]
Have you changed your password recently? Not sure why the alerts are incessant. Should be one and done. For now, what you can do is clear your local app data directory. You can find this in %USERPROFILE%\AppData\Roaming\Standard Notes. Just delete the whole thing, and restart the SN app, and you should now be presented with a blank slate with the ability to sign in.
