### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by camedgell** [standardnotes/forum#412]
As of 4 Jan 2019 am unable to login or sync. Have tried a few devices. Error messages as follows.

AlephNote:
AlephNote.PluginInterface.Exceptions.RestStatuscodeException: Server sync.standardnotes.org returned status code: 503 : Service Unavailable

Chrome:
app.standardnotes.org says
A server error occurred while trying to sign in. Please try again.

Firefox:
A server error occurred while trying to sign in. Please try again.

Internet Explorer:
https://app.standardnotes.org shows blank window.

**Comment by thinkgrizzly** [comment]
Same for me for chrome and firefox

**Comment by r-i-v-a** [comment]
This is what I see in Chrome console when trying to log in:

compiled.min-e7d877894b3c432010a38a791c7c48b0f7090b3ebab343edc58165508e1aab0f.js:20 GET https://sync.standardnotes.org/auth/params?email=<my email> 503 (Service Unavailable)

(index):1 Access to XMLHttpRequest at 'https://sync.standardnotes.org/auth/params?email=<my email>' from origin 'https://app.standardnotes.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mobitar** [comment]
Should be all better now. Sorry for the inconvenience. There were a few hung processes on the server causing some congestion.

**Comment by petermierau** [comment]
I'm getting the same error now.
Sync error <h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>

Along with this error:
POST https://sync.standardnotes.org/items/sync 503 (Service Unavailable)
_callee20$ @ compiled.js:59921
tryCatch @ compiled.js:62
invoke @ compiled.js:296
prototype.(anonymous function) @ compiled.js:114
step @ compiled.js:58924
(anonymous) @ compiled.js:58924
compiled.js:59901 Request error: <h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>
(anonymous) @ compiled.js:59901

**Comment by torpax** [comment]
I continue to be unable to log in.  Still getting the same error message.

**Comment by ajh3** [comment]
I never log out, so I am not having problems logging in, but I am experiencing intermittent failures to save changes to the server.

**Comment by mobitar** [comment]
Sorry about that. Here's an update on our server issues: https://twitter.com/StandardNotes/status/1081288524773634049

**Comment by meghprkh** [comment]
I am having a similar issue
![image](https://user-images.githubusercontent.com/5979605/54081426-d6074980-432a-11e9-81c5-365fdf03c4d2.png)

Though I am already logged in Firefox and the desktop app.

**Comment by mobitar** [comment]
Looks like the error you're getting is "ERR_SSL_VERSION_INTERFERENCE". I haven't encountered this before, but appears to be a local issue on your end. I'd do some searching around to see what some solutions could be.
