### ISSUE TITLE
Searching word doesn't highlight text for notes using an editor extension

### ISSUE THREAD

**Issue by edzed42** [standardnotes/forum#415]
Search text feature acts weird with notes that have an editor installed on windows app. (Haven't tested this on mobile). 

Searching for a word will find the notes that have that word, but it won't highlight that word inside the note if it has an editor. (Doesn't work with Advanced Markdown or Simple task from what I've tried.) This is not the case for notes that don't use an extenstion editor.

Let me know if anything I've written is unclear!

**Comment by edzed42** [comment]
Oh interesting! I have different notes I tend to swap between that use different editors, so I'm not sure if even just opening and closing a note from another with a different editor is also a part of that bug.

Glad to hear that a solution seems possible! Should I close this issue? Or do I wait until whenever that update comes up to close it?

**Comment by mobitar** [comment]
You can leave it open, I'll hopefully update this thread after the fix. Btw, as a workaround, you can just focus into the search field, then immediately press enter, and it will rehighlight the page. Do this if you're switching between notes with editors after you've performed a search.

**Comment by edzed42** [comment]
Sounds good. And thank you for the workaround!
