### ISSUE TITLE
Extension editors prevent text from being highlighted on iOS

### ISSUE THREAD

**Issue by edzed42** [standardnotes/forum#416]
While on iOS, if have an extension like the advanced mark down editor, I cannot highlight any text. It keeps snapping back to the beginning of the text I try to highlight. Having an extension editor enabled also seems to override the default iOS keyboard, so i have to manually capitalize the first letter of a new sentence and press the up arrow button to type the rest in lowercase. This is not the case with the Plain Editor. I listed it both issues here because they seem related since the keyboard is up for both.

Btw, I got one of the Extension plans during the holidays and am really enjoying note taking, using the editors, and resting easy knowing that all my stuff is backed up, secured and accessible from pc and mobile! I have some more bugs that I've encountered so you might see more reports from me these days. I'm making sure they haven't been reported already.

**Comment by mobitar** [comment]
Hey @edzed42, the selection issue is currently known. Hoping to look into this one further soon. As for the autocaps, I'm not seeing the same behavior. It does indeed have correct sentence capitalization. Are you using a custom keyboard? And are you saying that the editor always resorts to the system keyboard, rather than a custom keyboard you may have, like the SwiftKey keyboard or something?

Glad to hear you're enjoying SN!

**Comment by mobitar** [comment]
Strange, thanks for the info. I'll have to look into this one further.

**Comment by StuartMorrisAU** [comment]
Hi @mobitar, any update on iOS text selection? Editing text on mobile using anything but the plain editor is, unfortunately, absolutely horrendous, and takes away from the potential joy of using what's otherwise a solid multi-platform app.

**Comment by mobitar** [comment]
Won't be the answer you're looking for, but text selection with editors is controlled by the system webview, not the individual editors. The plain editor is native, so behaves as you'd expect, whereas other editors are wrapped in a web view, so it's like using a complex editor in Safari. There's only so much we can do here.

More here: https://standardnotes.org/help/77/what-are-editors

**Comment by StuartMorrisAU** [comment]
Hi @mobitar, sorry, I must’ve missed that article when I was originally looking at StandardNotes. It makes sense, and, now that I know, I’ll just use Markdown Basic (at least on mobile). Thank you.

**Comment by TheodoreChu** [comment]
It looks like text selection for the Advanced Markdown Editor (now known as Markdown Pro). Can anyone confirm? @JaspalSuri ?
