### ISSUE TITLE
FileSafe attachments not syncing cross-device

### ISSUE THREAD

**Issue by jdotjdot** [standardnotes/forum#418]
I use Standard Notes across a few devices&mdash;two different Macbooks, as well as an iPhone.

I've started to use FileSafe to add attachments to certain notes, and I authenticated it with an external store (Google Drive and Dropbox), created a new encryption key, and then uploaded a file on one of the Macbooks.  However, when I then opened the same note in Standard Notes on the other Macbook, even after syncing the note, FileSafe shows absolutely nothing: no keys and no attachments. I am 100% sure I am in the correct note and that it is fully synced.

![image](https://user-images.githubusercontent.com/1328961/50744138-30324400-11ee-11e9-93b3-3067f9eb997c.png)

Does FileSafe not sync cross-device? That would remove a lot of the benefit of being able to upload encrypted attachments to notes, if the attachments themselves are limited to the device they were uploaded on.  I could see it not working on mobile, but cross-laptop surprises me.

**Comment by mobitar** [comment]
Sorry about that, we had an issue with the FileSafe extension not communicating properly with the app. This is fixed in desktop version 3.0.2, which was released a few days ago. Please update to that, and I believe you should no longer see this issue.
