### ISSUE TITLE
App crashes on Android while loading

### ISSUE THREAD

**Issue by thinklog** [standardnotes/forum#419]
Standard Notes 2.3.8 on Android 9.0
As of two weeks ago the app begins to load the notes and then suddenly exits. Used to work without problems.

**Comment by mobitar** [comment]
Can you try version 2.3.10 and see if that helps? If not, can you go backwards in versions and see if any of them don't have this issue? 2.3.10 is the latest Google Play build. And all of our APKs can be downloaded manually from here: https://github.com/standardnotes/mobile/releases
