### ISSUE TITLE
"Error Decrypting" messages as a NEW user

### ISSUE THREAD

**Issue by AdamFo** [standardnotes/forum#42]
I am the new user. I've downloaded windows desktop app and iPhone app TODAY and registered TODAY for the FIRST time.

When I make a note in iPhone it shows me, after syncing, "error decrypting" message on my desktop app version. AND when I make a desktop note it shows me, after syncing, "error decrypting" message on my iPhone.

I've also signed out from every device and made sure that I have the newest version and logged in again. It didn't help.

I hope this issue will get done fast because I am eager to try this app!

**Comment by AdamFo** [comment]
It miraculously started to work with new notes, but the notes that I've created in the first 3 hours after account creation I still cannot enter. Maybe it's connected with how new account is.

**Comment by mobitar** [comment]
Hey Adam, that's strange. You downloaded the Windows app from standardnotes.org, correct? So it should have been version 1.2.1, correct?

**Comment by mobitar** [comment]
Can you also send me an email with your account email to mo@standardnotes.org. Which platform did you register your account on?

**Comment by mobitar** [comment]
😵 Just confirmed that if you create notes offline on iOS, then register, and then sync to desktop, you will see this issue. Investigating now. Thanks for bringing this up.

**Comment by AdamFo** [comment]
Do you still need my email?

**Comment by mobitar** [comment]
Yes please

**Comment by mobitar** [comment]
Actually, need your email urgently. The issue may actually be benign, but I need your email to verify my theory. Let me know when you get a chance to send it.

**Comment by AdamFo** [comment]
Sure, it will be sent in 5 minutes.

**Comment by AdamFo** [comment]
WHat is "bengin"?

**Comment by mobitar** [comment]
Meaning not as bad as I thought..

**Comment by AdamFo** [comment]
I've sent the email.

**Comment by mobitar** [comment]
Ok, we've gotten bottom to the issue and fixed the underlying bug. There was an issue with the iOS app where when you signed out of an account, it would not properly clear your keys. What happened in this case is that if a user creates an account, signs out, and signs in to another account, the wrong keys will be used. This issue corrects itself after you close the app and open it again. Which is what happened in this case.

This issue is patched in version 1.3.1 of the iOS app, which was just submitted to the App Store.

**Comment by AdamFo** [comment]
Thank you for fast response and great support.

By the way, app is great! Keep it up!

**Comment by mobitar** [comment]
Anytime, thanks @AdamFo!
