### ISSUE TITLE
Installing extensions on self-hosted

### ISSUE THREAD

**Issue by moso** [standardnotes/forum#422]
I'm aware that installing extensions on self-hosted instances are a DIY thing. I'm just having trouble getting it to work.

As the documentation doesn't specifically mention how this works, I'm gussing this is the workflow I'm supposed to use:

- Self-host Standard Files
- Install desktop app
- Login, and point to self-hosted url in advanced to sync to self-hosted instance
- Click extensions in desktop app
- Click 'import' in lower right corner
- Paste URL from component/theme running on `localhost`

As per https://docs.standardnotes.org/extensions/local-setup I'm supposed to point the import-dialogue in the desktop app (I'm guessing here) to `http://localhost:port` - IF the component/theme I'm trying to import actually have a webserver built in. While I know how to do one quickly if there isn't one ([advanced markdown editor](https://github.com/sn-extensions/advanced-markdown-editor) doesn't have one, just to throw an example on the table), as per the link, the `ext.json` doesn't exist. Creating one in `dist/` myself on the fly and then pointing the import dialogue to `http://localhost:port/ext.json` just doesn't work, and if I browse the url, I just get an error: `Cannot GET /ext.json`. No luck after rebuilding either. Pointing it to the root url, or the `"sn": { "main": " " },`-file from `package.json` (usually `index.html` or `dist.js`) just gives me a blank import window like [this image](https://i.imgur.com/z6r6Gec.png).

While I do get why the documentation doesn't mention how exactly how this is done, as SN probably rather want people to subscribe instead, it got me thinking: am I supposed to self-host the webapp too if I want the open-source extensions to work? Or am I doing something wrong in the process of importing them?

Thanks.

**Comment by mobitar** [comment]
For self-hosting your own extensions, you don't need to self-host either the web app or Standard File. These are all completely independent. As for the webserver for the extension, we do talk about it in the link you shared. `http-server -p 8001 --cors`. You would run that command from within the extension directory. Then, if ext.json is in the root of that directory, localhost:8001/ext.json should just work.

In your screenshot, the link you enter shouldn't be dist.js, it should be the ext.json link.
