### ISSUE TITLE
[Feature request-ish] Redundant label in Editor menut

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#424]
The Note Editor menu on the desktop version (currently using Windows SN version 3.0.2) is labeled as "Editor" and then has a menu subtitle "Note Editor". I guess this is consistent with the other menus that have multiple subcategories (eg in the Options menu, "Note options" and "Global display") but it doesn't really make sense when there is just the one category. Before I realized how it was being displayed, I have selected "Note Editor" a bunch of times thinking that it was the plain text editor, only to be kicked out of the menu.

So "feature" request - could that redundant subtitle be removed so it's less confusing?

![image](https://user-images.githubusercontent.com/492588/51141074-13c28700-1840-11e9-8793-8b30a24714df.png)

**Comment by mobitar** [comment]
Agreed that it's redundant, but all menus need to have a header, otherwise would look out of place/awkward. Will keep this in mind.

**Comment by quartertone** [comment]
That makes sense. It's less confusing now that I know it's there. Maybe a more distinct appearance could set it apart from the rest of the menu? Font size/type or different color maybe. Low priority of course.
