### ISSUE TITLE
Vim editor's markdown highlighting should ignore underscores in words

### ISSUE THREAD

**Issue by kyletolle** [standardnotes/forum#426]
Not sure if this is an issue in SN or a dependency.

I use the vim editor with Markdown highlighting.

Can I request that italics ignores underscores in the middle of words?

I often refer to file names in my Markdown notes, like spec_helper.rb, but the underscore is treated as the beginning of italics text. See the screenshot for an example. Also happens when there are multiple underscores in the words. Parts of the longer filename are rendered in italics.

![image](https://user-images.githubusercontent.com/260869/51214758-d831c680-18ec-11e9-8758-6db3741e1a9f.png)

**Comment by kyletolle** [comment]
The italics text gets really bad when I am keeping a checklist of file names I need to go through.

![bad italics](https://user-images.githubusercontent.com/260869/51215293-6a869a00-18ee-11e9-8817-23d2d6333d33.png)

**Comment by mobitar** [comment]
This would get us into editing core CodeMirror code. Unless there's an update available for it that fixes this issue, I don't think we'd want to fork it and make our own changes. Agree though that this would be nice.

**Comment by kyletolle** [comment]
I was figuring this behavior would be outside of your control, but wanted to report it to make sure.

**Comment by kyletolle** [comment]
I did just find a note here: https://github.com/codemirror/CodeMirror/issues/2307 that mentions

> The Markdown mode has a property called modeCfg.underscoresBreakWords which indicates whether underscores in the middle of works cause italics or bolding after them.

Is this a property you already set?

**Comment by mobitar** [comment]
Ah interesting, don't think we're using that. I'm a bit tied up with the mobile release right now, but if you want to play around with that and see if that makes a difference, the codebase is here: https://github.com/sn-extensions/vim-editor

**Comment by myreli** [comment]
Tested it again on `3.149.5` and this is no longer an issue.
