### ISSUE TITLE
Advanced Markdown Editor keyboard hides part of the note when open

### ISSUE THREAD

**Issue by DanielNetoP** [standardnotes/forum#428]
Hi, I've just started using Standard Notes, and I was editing a long note on Android usign Advanced Markdown Editor, and when I go to the bottom of the note and start to edit it, the keyboard covers part of the note, I can't even select the bottom of my note, and what happens is that it duplicates the word that I selected when scrolling down with the keyboard open, ending up having something like this "andandandandandandandandandand" in the middle of the text.

**Comment by mobitar** [comment]
Hey @DanielNetoP, thanks for the heads up. The keyboard issue is known, and I hope to investigate a solution for this. Someone actually posted a similar issue here: https://github.com/standardnotes/mobile/issues/128 

The selection issue, that's strange. I'll have to investigate that further.

**Comment by effieeee** [comment]
No longer an issue in recent versions and with the new mobile UI :)
