### ISSUE TITLE
Linking notes/ Footnotes/ References

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#43]
As the title says linking notes as well as footnotes / references to a section (sentence or paragraph).

**Comment by mobitar** [comment]
Ya would be neat..haven't gotten around to it just yet. Though if anyone is reading this, this might make a good candidate for a pull request :)

**Comment by DaveWalk1** [comment]
In the same vein, I always liked linking notes together in Notational Velocity using [[double brackets of the other note's name]]. But it needed the other note's exact name, so some kind of tab-completion would be helpful, too...

**Comment by russlipton** [comment]
Linking between notes is a must-have for my work, i.e., to make this my ... standard ... note-taking tool.

**Comment by Philiphlop** [comment]
>  using [[double brackets of the other note's name]]. But it needed the other note's exact name, so some kind of tab-completion would be helpful, too...

Tab completion could also help duplicate names, by showing the folder/tag to which it belongs. If someone has 2 notes of the same name and same folder/tag... they're mad 

> Linking between notes is a must-have

I do agree, it allows us to keep our notes clean, referring to other notes for further information. This is the power of a Wiki, but unfortunately it's difficult to run a synchronised, local, secure mediawiki

**Comment by trevormeier** [comment]
I wonder if this could be extended with the new FileSafe feature—to be able to link to attached files within the note? So for example, a markdown note being able to use ![image](url) syntax to be able to show the attached image in the rendered preview.

**Comment by mobitar** [comment]
Files uploaded with FileSafe are stored encrypted in your configured cloud, making that two steps further away from getting an embedded link:

1. They'd need to be decrypted.
2. We'd need to generate a shareable URL from your cloud provider.

This would be really tricky. We'd need to find some elegant workaround to get embedded images.

**Comment by trevormeier** [comment]
If there’s a “preview file” option in the FileSafe extension, it could work similarly? Something like
1. Download and decrypt the file inside Standard Notes
2. SN generates an SN-only URL to the decrypted file
3. URL can be used inside markdown notes in SN

The blogging plugin would need a different implementation with a shareable URL, but perhaps this could be a start?

-- 
Trevor Meier

On October 9, 2018 at 12:07:18 PM, Mo Bitar (notifications@github.com) wrote:

Files uploaded with FileSafe are stored encrypted in your configured cloud, making that two steps further away from getting an embedded link:

They'd need to be decrypted.
We'd need to generate a shareable URL from your cloud provider.
This would be really tricky. We'd need to find some elegant workaround to get embedded images.

**Comment by TheodoreChu** [comment]
Closing this issue because it's duplicated elsewhere (https://github.com/standardnotes/forum/issues/324) and the original poster has deleted their account, so it doesn't appearing in search
