### ISSUE TITLE
Feature Request: insert From URL when copying/pasting from website

### ISSUE THREAD

**Issue by clc14** [standardnotes/forum#430]
OneNote inserts the From URL where you copy/pasted from. It would be really useful to have this feature to refer to where you got the note/snippet from.

**Comment by mobitar** [comment]
How does OneNote know where a particular snippet came from if it's just generic text on the clipboard?

**Comment by clc14** [comment]
I don't know. I just checked with Evernote, and it does it as well.

**Comment by clc14** [comment]
Is this feasible?

**Comment by mobitar** [comment]
I don't think so. Not sure if clipboard information contains source, generally speaking.
