### ISSUE TITLE
[Pipe dreams / feature request] Text search of attached images/files

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#432]
So this is something I'm sure will be low on the list of priorities at this point, but it would be so great to have.
I would love to see some sort of extension or, more likely, an enhanced version of FileSafe that can parse appropriate attached files (PDF, documents, spreadsheet, slides, images) for recognizable text to be indexed for search. Optical character recognition (OCR) of images for text would be amazing as well.
An alternate option would be to parse/search the attached file and import the discovered text into the note for search.

But I dream.

**Comment by mobitar** [comment]
This would be extremely difficult. FileSafe files are all encrypted. Any kind of in-file search would also need to be done on the client side to avoid sending sensitive contents to a remote server. So, to search, we'd have to decrypt all files, then do OCR client side. Client-side OCR is very, very poor compared to server-side. The tech just isn't there yet..

**Comment by opie4624** [comment]
I was just thinking about this, too. Is there a way to denote text that's normally hidden in a note? You could import the ocr'd content into that space, which would allow you to search the notes, then pull down the attached file if it had what you wanted.

**Comment by mobitar** [comment]
You're saying you want to have a hidden segment of text inside of a note just for the sake of it being searchable? This isn't possible. Interesting thought though.
