### ISSUE TITLE
[Feature request/suggestion] User-definable autolock timer

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#434]
The passcode auto lock feature is great. However the timer could use a little refinement. Current options include: immediate, 1 minute, 5 minutes, 1 hour.
That's a big gap between 5 minutes and 1 hour. It would be great to have a way to specify a custom timeout value. Sometimes I want 15 minutes, sometimes 2 hours.

thanks!!

**Comment by effieeee** [comment]
See this as well: https://github.com/standardnotes/forum/issues/629
