### ISSUE TITLE
Change email without creating a new account

### ISSUE THREAD

**Issue by mxng** [standardnotes/forum#435]
Sorry if this is asked too many times. I can't find any specific answers regarding this.

Will there ever be a time where we can change our registered email for the notes account without having to create a new account and importing from the old one?

I have a lot of notes and tags and using the import function from the backup explorer will result in all imported notes becoming untagged. Using the import function from the 'account' menu on the desktop app will result in loading issues and multiples of duplicated tags and a few duplicated notes. I even have 1 tag duplicated 9 times among all the others I find it too troublesome to spring-clean so it's deterring me to use my newer, more permanent email address for the notes account for now. (My current email address might not exist any more before my 5 years of standard note subscription ends).

So I'm hoping for either an easier way to change the notes account email, or maybe just have the backup and import work perfectly...

Thanks for your time!

**Comment by mobitar** [comment]
How many notes/tags are being imported? I would recommend deleting all current data from your account before importing the file, if you're seeing some conflicts.

**Comment by nauxnim** [comment]
I import into a new account. I have 787 notes and 205 tags. When I try again in the next few days, I will make sure to clear the account.

**Comment by mobitar** [comment]
Hmm..that is a relatively large amount of tags for that number of notes. Can't say I've tested with that kind of ratio. Also, there have been some improvements made in v3.0.3 related to this area. When you try again, please try with that version.

**Comment by nauxnim** [comment]
Will do!

**Comment by nauxnim** [comment]
Okay, managed to have everything move over nicely this time. :)

**Comment by effieeee** [comment]
Already implemented! :)
