### ISSUE TITLE
Keyboard won't pop up and the headers are too tall

### ISSUE THREAD

**Issue by weird-o** [standardnotes/forum#437]
I just updated to 3.0.0 on Android 7.1.1 and the keyboard won't pop up when I try to edit the body of a note. It will pop up when I try to edit a title, do a search, or even when I create a new note. Oddly, it will also pop up when I leave the cursor in the body of a note, switch to a different app, then switch back to Standard Notes. (So it *is* possible, though cumbersome, to edit my notes right now.) But if I simply try to edit a note, the keyboard won't appear. I've tried using a different keyboard, but the problem persists.

On an unrelated front, the headers in notes are very tall, taking up a lot of valuable screen space. On my 5" screen, the app has 3 7/8" of usable vertical space, excluding Android's status bar and navigation buttons. The header, which I'm counting as the top line that says "Note" and the line below it that says the note's title, wastes 3/4" of space.

I think a few things could be done to free up more vertical space:

1. Stop making the note's title persistent. I don't need to constantly be reminded of the title. If it's only at the top of the note, that's fine.

2. Replace the word "Note" in the top line with the note's title. This would free up the same space as suggestion 1 and still let you keep the note's title persistent.

3. Shorten the top line that includes "Note," the back arrow, and the hamburger icon. It takes up 3/8" and it could stand to be shorter.

4. A more radical approach, which I'd prefer, would be to hide the header in most circumstances. When you scroll up, it would pop back into view, letting you access the back button and hamburger icon. Most mobile browsers do this. It's a great way to maximize vertical space while maintaining the functionality of a header.

**Comment by mobitar** [comment]
Regarding the title taking up space, can you share a screenshot of how it looks on your device?

**Comment by weird-o** [comment]
With Gboard at normal/default height: https://i.imgur.com/AL1kZ5J.png

With Gboard at mid-short height (what I normally use): https://i.imgur.com/P2cXXH5.png

Without keyboard: https://i.imgur.com/bhULFM7.png

Also, to avoid creating a new issue, I'm having trouble with scrolling while the keyboard is present. Sometimes I can't quite scroll to the bottom of a note, as though the app thinks the keyboard isn't there and I can see through it. So I have to minimize the keyboard to get all the way to the bottom.

I haven't figured out a way to replicate this bug, but it happens somewhat often. And a couple times I couldn't quite scroll to the top of a note until I minimized the keyboard. This variant of the bug is rare, though.

**Comment by weird-o** [comment]
I found a somewhat reliable way to replicate the scrolling bug: Paste a large-ish block of text (maybe ten lines) in a note that's already long. Then you should be unable to scroll all the way to the bottom of the note until you minimize (or maximize) the keyboard.

But for some reason the text has to be copied from an outside source (such as this thread), rather than from Standard Notes. (Perhaps it has something to do with the formatting in the copied text.)

Also, I've found that the keyboard doesn't actually have to be present to induce this bug.

I believe I've also encountered this bug under other circumstances, but this is the only one I've been able to replicate.

**Comment by mobitar** [comment]
Noted about title height. We'll have to explore some solutions. The other issue is well documented here: https://github.com/standardnotes/mobile/issues/130

No good solutions as of yet, though this is an important one as well.

**Comment by effieeee** [comment]
Closing in light of improvements on latest version and the new mobile UI
