### ISSUE TITLE
Allow notes to be archived.

### ISSUE THREAD

**Issue by ryanpcmcquen** [standardnotes/forum#44]
This was a killer feature of Google Keep for me. Allowing a note to not show in the normal view, but having it still exist when I searched for it. I'm guessing some modification of the current tagging system would allow this to work without too much hackery.

**Comment by mobitar** [comment]
Archiving isn't outside of the overall scope of the app, but not something currently prioritized. Hopefully one day.

**Comment by isaacsu** [comment]
Hi I would also really like to have a concept or "archiving" a note. In SimpleNote, I used to be able to "delete" a note and it would be sent to Trash where it is still searchable and accessible but not editable.

I like keeping my list of "current" notes clean by archiving or deleting, but also would love the feeling that i can find something in my archive if i need it in the future.

**Comment by mobitar** [comment]
Archiving is available in v2.

**Comment by secretfork** [comment]
What is meant by v2? I can't seem to find this feature in the latest version, and a search for simplenote v2 gives me nothing

**Comment by ryanpcmcquen** [comment]
@secretfork do you mean Standard Notes (not simplenote)?

**Comment by secretfork** [comment]
I'm awfully sorry, you're right, i misread thinking this was a simplenote thread. On the bright side, i've never heard of standardnotes tho. Looks super interesting i must say! Again, sorry for the noise

**Comment by ryanpcmcquen** [comment]
@secretfork, it is great, you should give it a try!

**Comment by ithinkmatt** [comment]
I am new to Standard Notes and am loving it. I like the idea of Archiving notes. However, I can't seem to find where to view, unarchive or retrieve a note once it is archived. I probably missing something simple. Can someone provide the process or steps needed?

**Comment by isaacsu** [comment]
@ithinkmatt there's an "Options" below the search field that allows you to make archived notes visible in the notes list.

**Comment by mobitar** [comment]
Another place you'll find Archived notes is:

- in the Tags view, the last item will "Archived". It will be a little faded out. This will show all archived notes.
- If you're using the Folders extension, you'll need to create a smart tag for it. [Instructions here](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes).

The Options route for display is to view archived notes wherever you are (like All, or a tag), rather than in its dedicated location.

**Comment by ithinkmatt** [comment]
Thanks for the heads up about the Smart Notes. I added some. Just the smart notes feature to allow for smart filters makes me like Standard Notes better than Evernote.

**Comment by mobitar** [comment]
@ithinkmatt glad to hear that!
