### ISSUE TITLE
[Web/Desktop] Flashing red "Saving" annoying when editing a note offline

### ISSUE THREAD

**Issue by christianhans** [standardnotes/forum#442]
Often times I'm offline when editing notes (e.g. on airplanes, trains, etc.). Is it possible to to make the warning about a note not being synchronized less distracting? First of all it shouldn't switch from "Saving..." to that warning message and back (it's flashing and very distracting). Then I don't think the top right part needs to be colored red as the bottom left Account status indicator already turns red  when editing a note offline.

**Comment by mobitar** [comment]
It can be a little less obtrusive. The important part is that the user see it at least once. But after that, we can possibly tone it down.

**Comment by effieeee** [comment]
Tracking here https://github.com/standardnotes/forum/issues/492
