### ISSUE TITLE
New [Pinned] label taking up too much space

### ISSUE THREAD

**Issue by superfreeman1989** [standardnotes/forum#447]
The new [Pinned] label takes up an entire line above note's title, creating lots of wasted space. This is even a worse problem on mobile app as screen real estate is more precious. I would suggest simply using a colored line on the left side of the pinned note, or even just a small pin icon ahead of entry title. 
![note](https://user-images.githubusercontent.com/15226945/52105784-1b16be00-25be-11e9-8441-8a1cddc3877d.png)

I think my suggestion would fit more in line with the minimalist design style of the application. The current [Pinned] label looks really out of place.

**Comment by mobitar** [comment]
That still wouldn't solve the problem for other flags, like Locked or Protected. We actually save space by putting them all on the same line.

**Comment by bschlagel** [comment]
I was just about to open a similar issue when I found this :)

I currently have 8 pinned notes, and even on a 27" screen, and with note preview / date / tags display off, these 8 notes take up more than half the vertical space of the notes list. On mobile, nearly the entire height.

Playing around with some CSS in the web app I hit on a very simple tweak that I think addresses this pretty well and makes the spacing of the notes list feel a lot more optimized.

```
#notes-column .note .note-flags, .notes .note .note-flags {
  float: right;
  margin-left: 10px;
}
```

And…that's it! Reduces vertical height by at least ~35% and makes pinned posts look a lot nicer. Works fine for archived / deleted notes as well. On desktop, at least, even works for notes with multiple flags (the title just wraps if necessary).

Hacking around with a theme I was able to get this mostly working, but I think a change in core would be better for a couple reasons:

First, my change does not seem to work on mobile (I did press and hold to re-download); not sure if mobile uses different CSS for notes / flags.

Second and more importantly, I think the *better* solution would be, as suggested above, using icons instead of words for these flags. Pinned could be a pin; locked could be a padlock; trash and archive have common icons too…I think they'd all translate pretty clearly as icons. And this way 'float: right' would work even with several flags on a single note without reducing space for the title too much (better for mobile in particular).

**Comment by mobitar** [comment]
Can you post a screenshot of how your css changes look? Also icons are more subjective generally, and may have a hard time looking good and staying ageless across Mac, Windows, and Linux. Plus we have too many flags to have an icon for each one. How would a locked, protected, pinned, and archived note look? Just 4 icons next to each other? Would seem to be overwhelming.

**Comment by bschlagel** [comment]
Sure! Here's before modification:

<img width="506" alt="Screen Shot 2019-07-20 at 4 18 16 PM" src="https://user-images.githubusercontent.com/1237539/61640018-95b9bf80-ac6a-11e9-9a5e-7113d6be7168.png">

And after:

<img width="511" alt="Screen Shot 2019-07-20 at 4 18 00 PM" src="https://user-images.githubusercontent.com/1237539/61640027-9c483700-ac6a-11e9-9f15-98c6cc3d79ad.png">

And an example of what it looks like when a note has many flags:

<img width="505" alt="Screen Shot 2019-07-22 at 10 21 20 AM" src="https://user-images.githubusercontent.com/1237539/61640074-b08c3400-ac6a-11e9-8118-602992fa2e0f.png">

Yes I imagine a note with four flags could have four icons instead…maybe a bit overwhelming, but you could probably say the same about that # of words too. Also, and of course you'd know better than me, but I imagine that many flags on one note is pretty rare in practice? In my ordinary use so far I don't think I have any notes with more than two. I totally see how this can be a tricky balance though, particularly if lots of users actually do regularly have 3-4 flags on a given note.

(FWIW I'm actually not totally sure what the difference is between 'locked' and 'protected' without reading the manual; ambiguity here may be conceptual + more of a power user thing anyway so not sure switching to icons would change that.)

Here's an example that came to mind — Discourse uses icons to the left of the title in the main topic list to indicate various statuses like pinned, bookmarked, archived, unlisted, solved…not sure if there's a max # but here's what it looks like with three at once. (Very rare in practice for a topic to have more than 1-2 at a time, in my experience). Somewhat visually cluttered but I think once you get used to the software it's pretty clear what all the icons mean:

<img width="1131" alt="Screen Shot 2019-07-22 at 10 34 12 AM" src="https://user-images.githubusercontent.com/1237539/61641115-89cefd00-ac6c-11e9-9de7-3d4c838ee4b8.png">

All that said, I think it could still be a good compromise to float the flags over to the side, even with the full words. Not sure how that'd work w/ the mobile apps (as I mentioned my above change didn't seem to make a difference on mobile) but it does seem workable on desktop.

A slightly more complex but maybe better solution (and still not a *huge* change) might be for title and flags to be separate flex elements within the row, and set a max width for the flags element such that if a note had say > 2 flags, they'd stack…would better handle the "tons of flags" edge case while still optimizing spacing for note with just one or two flags.

**Comment by mobitar** [comment]
Interesting, doesn't look bad. The differences in title width could be visually disruptive. But yeah, I'm sure we'll iterate on this in the future. The text-based flags also allow us to have a visually consistent experience on mobile. Whereas if we used icons, what looks good on Android may not look good on iOS, may not look good on web, may not look good on desktop. Text helps solve that.

**Comment by superfreeman1989** [comment]
> Interesting, doesn't look bad. The differences in title width could be visually disruptive. But yeah, I'm sure we'll iterate on this in the future. The text-based flags also allow us to have a visually consistent experience on mobile. Whereas if we used icons, what looks good on Android may not look good on iOS, may not look good on web, may not look good on desktop. Text helps solve that.

On iPad the left column takes up ~40% of screen width in landscape mode, which is excessive. Please make it smaller!

**Comment by cyb3rz3us** [comment]
Curious, is having icons for all of these traits not possible or if possible, then not desired?  For example, the thumbtack for "pinned", lock for "locked", and then maybe a shield for "protected"?

The devTeam is pretty savvy so I presume they've kicked this around but I still thought worth the ask...

**Comment by JaspalSuri** [comment]
Perhaps @zsoltszilvai can share their thoughts on this matter. :)

**Comment by zsoltszilvai** [comment]
@cyb3rz3us good questions:) I did some research on this with a couple of users in the past and found that while using icons might make sense for some of the above-mentioned labels, it wouldn't be the best idea to completely get rid of all text labels. Based on my research, having a prominent text-based "Protected" label seems to be preferred (and the same goes for "Deleted" and "Archived").

I've been exploring which icons could potentially replace some of the labels but it's still a work in progress. As @mobitar mentioned, it's been a challenge to find a solution that is consistent and also works across all platforms. I'm confident that we'll find the balance here though 🤞

Thanks again for all your ideas! @bschlagel @superfreeman1989

**Comment by cyb3rz3us** [comment]
@zsoltszilvai --- Thx for the info.  Also, quick question...

Is it worth considering a user-selectable knob that allows the user to choose between icon or text labels: **(a)** for all elements; **(b)** individually for each element (i.e. text for LOCKED and then icon for PROTECTED.

As an aside, if you opted to go with "b", then you could also make those individual knobs movable so the user could customize the order in which the labels are shown.  Yeah, I know --- likely way too much here but just tossing it out... :=)

**Comment by superfreeman1989** [comment]
@zsoltszilvai Honestly I'd be happy if they just changed the width of the left column, which still takes up 40% of the whole screen in landscape mode on iPad.

> On iPad the left column takes up ~40% of screen width in landscape mode, which is excessive. Please make it smaller!

**Comment by zsoltszilvai** [comment]
@cyb3rz3us interesting. We do want to enable our users to customize their app to their liking, so I'm going to think about your idea. Thanks! :)

**Comment by zsoltszilvai** [comment]
@superfreeman1989 Thanks for the feedback! Improving our tablet UI is also on our to-do list. We're probably going to incorporate new design principles in SN v4.

**Comment by effieeee** [comment]
The "pinned" indicator is now indeed a small icon 😅
