### ISSUE TITLE
Support for Markdown Anchors?

### ISSUE THREAD

**Issue by ryanl888** [standardnotes/forum#448]
I understand anchor link syntax is not specified in markdown, but just wondering if there is some way to get them working in Standard Notes? Have tried a variety of combinations with the <a> (a name, a href) tag - always opens a new window in SN...

**Comment by mobitar** [comment]
Not sure about this one. By default editors don't handle their own URLs, but perhaps there can be some editor that exists that does. If you find an open-source one that does, let me know.
