### ISSUE TITLE
Ubuntu Mate: How to force log out

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#449]
Hey guys,
As I deleted my previous account in order to create a better password I forgot to log out on my devices. So now when I open standard notes on Mate it tells me: "Your session has expired..." if I press OK it keeps popping up right after. So I actually cannot navigate to logging out of the app.

My question is there a terminal command to either uninstall the app completely or force a logout? I already tried it by simply trashing the Appimage with no success :).

**Comment by mobitar** [comment]
Strange. The 'your session has expired' message should eventually go away at app launch. Maybe it would appear a couple times at most, but see if you can eventually dismiss it (at worst, try opening the app offline without a connection). If not, you can delete the app data manually by pressing the top level Help menu option (within the menu in the top left), then delete all the data inside the directory that opens when you click "Open Data Directory".
