### ISSUE TITLE
iOS app: Occasionally, auto saves seem to be reverting to previous saved versions

### ISSUE THREAD

**Issue by sts10** [standardnotes/forum#45]
This bug is a bit tricky to describe but it's become a show-stopping one for me using Standard Notes, so I'll do my best. 

**Steps to re-create:**
1. Using the iOS app (version 1.3.1.1), while using 3G rather than wifi, create a new note with a title and a tag or two. 
2. Begin typing, say, a to-do list with multiple short lines. 
3. From time to time, the Standard Notes app will attempt to automatically save (or "write") your note to its servers. Occasionally, though, the app seems to revert to your previous automatic save, which, to the users, means that their changes written since that last automatic save _will be deleted_ right before their eyes. So for example, let's say I write 10 words and then my note is automatically saved. Sometimes when I type my 11th and 12th words, rather than perform another automatic save (a "write"), my 11th and 12th words will suddenly disappear. My guess is that the app is reverting to the saved version of my note when it had 10 words.

Hope I'm describing this bug well enough. I've had better luck when my iPhone is connected to a good wifi network, so that might be a clue? Anyone else experience this, or able to reproduce it? If need be I can try to take a video of it happening but that'd be tricky for me.

**Comment by mobitar** [comment]
Ah interesting, I just tested this using a network filter to increase my latency, and can replicate it. Let me take a look and see what's causing it.

**Comment by mobitar** [comment]
Ok turns out this was actually related to a server update I made yesterday. I've found the issue and deployed the fix. This it's a server-side fix so no need to update your app. I just tested and confirmed that it fixed the issue. Let me know if you discover otherwise.

**Comment by sts10** [comment]
Cool-- thank you for the quick response! 

I did a quick test just now and it seems to be better, so that's great. However I'm a little skeptical of your fix only because (and I should have noted this) I've been experiencing this problem for at least 10 to 14 days. 

I'll keep trying to reproduce it this week and will report back.

**Comment by mobitar** [comment]
I just tested with the equivalent of an Edge connection and was not able to reproduce the issue ;) But if you see it again do let me know.

**Comment by sts10** [comment]
I haven't had this problem since this fix (yay!), so I'm going to close this issue. Thanks!

**Comment by judgej** [comment]
Hmm. Just happened to me. Made several updates to the top comment on an issue, and the last save suddenly jumped back about three saves, losing all my updates. Never seen that before, and cannot explain what may have happened.

**Comment by mobitar** [comment]
What version of the app are you running?
