### ISSUE TITLE
Table Functionalities

### ISSUE THREAD

**Issue by hanct** [standardnotes/forum#451]
Hi,
Would like to enquire, with standardnotes, is it possible to create table 

1. with merged/splitted cells (just like in excel) 
2. background color of specific table cells
3.  table/cell border width with specific color

simply with one or two click of mouse?

**Comment by mobitar** [comment]
You can do all this with the Standard Sheets editor :) It's available to Extended subscribers. You can try it out in the demo here: standardnotes.org/demo.

**Comment by hanct** [comment]
Hi, Thanks for replying.
Before i post this question, i did try out the different extension editors, with the feature to create table. But i realize it can only create table, and provide interactive way to add rows or delete rows. But I could not find an interactive way to merge 2 cells, set background color, or set table/cell border width.

**Comment by mobitar** [comment]
Try creating a new note, then click Editor in the notes panel, and choosing Standard Sheets. You should see this:

<img width="710" alt="screen shot 2019-02-07 at 11 14 24 am" src="https://user-images.githubusercontent.com/3277844/52429443-aa920480-2ac9-11e9-9163-67815db558c9.png">

**Comment by hanct** [comment]
Thanks! 

My original thought is to have a table (with the aforementioned features) in a non-spreadsheet editor, But this spreadsheet editor also can achieve what I want and even goes beyond it (i like that it has multiple sheets). 

Btw, can i query that if i purchase the extension, this standard sheet editor will appear in the android version of standard note with the exact same features as what i see on the web browser?

**Comment by mobitar** [comment]
Yes, the spreadsheet editor will also work on Android. Keep in mind it will still be web-based on Android, so it won't necessarily feel perfectly native, but that will just depend on your hardware.

**Comment by hanct** [comment]
Thanks. Btw, when i try the plus editor, i notice there are interactive ways to create and delete rows/columns, etc, but will there be any plan to do the same for merge/split cells in the plus editor? Currently, to do that, i have to manually switch to code view, and add colspan="5", for example to achieve the cell merge.
For those not code-savy users, having buttons to do the merge/split cells will be a great feature to the plus editor

**Comment by mobitar** [comment]
The plus editor is based on an open source component called Summernote. We don't make changes to this directly. However, in the future, we'll introduce other editors which will be based on different components, which may perhaps offer this option.
