### ISSUE TITLE
Can't return to default theme

### ISSUE THREAD

**Issue by yenson-lau** [standardnotes/forum#452]
Using the Linux app (v 3.0.4) on Manjaro:

After installing the Futura theme, I created a Sync account, which unfortunately seemed to interfere with my LaTeX editor and other extensions in a bad way.

After restarting the app and reloading my extensions, things seem to work fine except the default theme seems to be corrupted; here's a [screenshot](https://imgur.com/5zXOAvJ) of what happens when I turn my themes off (it doesn't matter which theme I was using prior).

Is there at least a way to do a clean reinstall so I can fix this?

**Comment by mobitar** [comment]
You should just be able to activate a theme from the bottom right, then quickly deactivate it by pressing the circle again. That should reset the app state to no theme. I've encountered this issue once before but could not replicate it. But that was the solution I found.

**Comment by yenson-lau** [comment]
Unfortunately, the screenshot I showed is what happens exactly after I followed those steps. Not even a reinstall seems to fix this, but that might just be because I don't know where the preferences, etc. are stored.

**Comment by mobitar** [comment]
At this point I would just try signing out of your account and signing back in.

**Comment by yenson-lau** [comment]
Ahh that worked. Thank you very much for the suggestion!
