### ISSUE TITLE
Format Painter

### ISSUE THREAD

**Issue by hanct** [standardnotes/forum#453]
Hi,
I would like to suggest a very useful features that even evernote has been missing all these while:
**Format Painter Tool** (akin to that in Microsoft word), which allow us to copy formatting from one existing text to another. It will be a nice updates to include this in each and every editor.

**Comment by mobitar** [comment]
This would be an editor independent option. Unlikely we'll add this ourselves, but in the future, we may incorporate other editors that may offer this option.

**Comment by hanct** [comment]
ok. noted. thanks
