### ISSUE TITLE
Access extensions with no internet connection on iOS/Android

### ISSUE THREAD

**Issue by GastroGeek** [standardnotes/forum#455]
When running a self-hosted instance with extensions installed. The Android app can only make use of extensions when connected to the internet. Sadly this is a deal breaker for me as I often want to add tasks/edit markdown when en route to work with no wifi/internet connection.

My feeling is it should not be too difficult to 'bundle' extensions on the server during install, and then unbundle locally inside/deploy bundles to each client. These could then also be 'synched' whenever updates occur or at users discretion.

This way, the extensions would still work without internet access...

**Comment by mobitar** [comment]
We do this with the desktop app (download extensions locally), but haven't yet taken up the challenge to do this on mobile. I'm not quite sure yet if this will even be possible. Will need to look into it further.

**Comment by effieeee** [comment]
Now possible on new mobile UI :)
