### ISSUE TITLE
Quick Actions (3D Touch on iOS)

### ISSUE THREAD

**Issue by CashewCow** [standardnotes/forum#458]
Coming from Apple Notes I’d like to be able to use Quick Actions.
I'd go for the following layout in comparison with Apple Notes:

|  **Apple Notes** |  **Standard Notes** | 
|---|---|
|  Scan Document / New Photo | New Photo<sup>1</sup>  |   |   |   |
| New Checklist  | New Checklist<sup>2</sup>  |   |   |   |
| New Note  | New Note  |   |   |   |

<sup>1</sup> handled by FileSafe
<sup>2</sup> activates Simple Task Editor directly

![img_4726](https://user-images.githubusercontent.com/47604787/52726135-da9e4380-2fb2-11e9-802d-389cdcb93911.PNG)
![img_4729](https://user-images.githubusercontent.com/47604787/52726322-454f7f00-2fb3-11e9-9c1d-d949d9444b38.PNG)

**Comment by mobitar** [comment]
Would be neat! This is not something we're actively focused on, but definitely something to keep in mind for the future.

**Comment by christianhans** [comment]
See also #439 

I would suggest keeping it simple and including only the 2 shortcuts:

* Search
* New note
