### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by kevinhowbrook** [standardnotes/forum#46]
Is there any interest in a CLi version for the app? I really like using the UI but as a quick listing/CL interaction, it would be nice to integrate it.

Not sure if this is planned or the security implications of connecting, is there any method available for me to start connecting and building something out?

Thanks

**Comment by mobitar** [comment]
This isn't something we would build officially, but you're welcome to explore it. I'm sure others would be interested. There's a client development guide here: https://github.com/standardnotes/doc/blob/master/Client%20Development%20Guide.md

You can also use the SF JS library to take care of the encryption aspects: https://github.com/standardfile/sfjs
