### ISSUE TITLE
screen goes blank on desktop after a few minutees, account can't sync

### ISSUE THREAD

**Issue by githubaccountforme** [standardnotes/forum#460]
I've had two issue lately with Standard Notes: 

1. On desktop after leaving the app open in the background for only a few minutes when I come back the entire app screen is grey with nothing else displaying.  Nothing is clickable and I have to close/reopen the app to show my data again. 

2. Concurrently when I open the app again my account isn't syncing and I see a new completely red-background note with a lot of text about <html> <head><title>413 Request Entity Too Large</title></head> <body=bgcolor="white"... etc about my settings, finally followed by: 

   which is repeated 6 times.

Any ideas?

I'm running 3.0.5.

**Comment by mobitar** [comment]
Hey @githubaccountforme, sorry, must have missed this message in my inbox. It sounds like you have a note or two that are way too large (~1MB or greater). Here's what you should do:

1. Click Account, and download a Decrypted backup of your data.
2. Open the resulting zip file, and open the Notes folder.
3. Sort the note by file size. 
4. See what the largest notes are. If there's anything in the megabyte range, that would be too large to sync. 1MB would be an overwhelmingly large note to begin with. It's best to split those up into multiple notes.

I think issue 1 and issue 2 are related. Please let me know if the above helps the issue.
