### ISSUE TITLE
Whats the point having mobile versions?

### ISSUE THREAD

**Issue by hurzhurzhurzhurz-oik** [standardnotes/forum#461]
I'll love the SN project, love the desktop and web version, but, hell yeah,
whats the point having mobile versions, when the mobile apps even can't do plain text right?

- You can't use extensions OFFLINE
- Extension didn't cached when ONLINE and generate alot of mobile traffic
- Even the plain text editor doesn't support monospaced fonts

Swiching between a spreadsheed and plus editor note genreate at least 10mb mobile traffic,
without writing a single letter. So you can waste up to 1gb a week on mobile traffic.
(In Germany, mobile traffic costs more than a gold bar for 1GB traffic.)

You force your customers to use plain text at all, even on desktop to reach
'feature parity' between all versions. So please do something about mobile versions.

**Comment by mobitar** [comment]
Offline editors on mobile are a well known feature request. Still need to determine feasibility.

**Comment by phipolis** [comment]
I didn't realize this! Extension caching and offline use of extensions would be very desirable.

**Comment by effieeee** [comment]
Now possible on new mobile UI :)
