### ISSUE TITLE
standardnotes.org/demo flashes or refreshes constantly in Microsoft Edge.

### ISSUE THREAD

**Issue by seanrmilligan** [standardnotes/forum#462]
Visiting standardnotes.org/demo directly, or being linked from another page, shows the website for a fraction of a second alternating with a blank white screen.

This was found on Edge (64-bit) version 44.17763.1.0. Microsoft EdgeHTML version 18.17763.

**Comment by mobitar** [comment]
Hmm..haven't tested on Edge to be honest, but, if you're signed in to your main account using the same browser, this might happen.
