### ISSUE TITLE
Spell check not working on Linux desktop release

### ISSUE THREAD

**Issue by York2dot0** [standardnotes/forum#465]
I cannot get the spell check to recognize any spelling errors on the Linux release of SN (just updated to 3.0.5). I have tried clearing cache and resetting to standard views and editors. Spell check shows as active but no errors are reported for misspelled words (i.e. no red underline). Works fine on web version.

**Comment by mobitar** [comment]
Can you click the top-level Help -> Toggle Error Console, and see what the first line reported in the Console is? That will indicate whether it correctly loaded spellcheck or not.

**Comment by York2dot0** [comment]
/tmp/.mount_standabOliy0/app/resources/app.asar/dist/javascripts/render/spellcheck.js:40 
Detected Linux. Using default en_US spell check dictionary

Seems to have loaded correctly, but still no spell check warning for misspelled words (updated to 3.0.6; also using Ubuntu 18.10)

Thanks

**Comment by mobitar** [comment]
Got it thanks. Will need to investigate this further. I've heard other reports of this on Linux, but most users have no difficulty.
