### ISSUE TITLE
Possible to list only notes that contain specific combinations of tags?

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#47]
I've poked at the Windows client to see if I could figure out a way to find notes that contain a specific combination of tags. My objective is to be able to logically AND tags to locate specific subsets of notes.

One hypothetical example:
* I have a *python3* tag.
* I have a *fileIO* tag.

1. I have applied those two tags to a subset of notes. Other *python3* notes may include tags for, say, *PEP8* or some such. 

2. I now want to find notes that contain both the *python3* `AND` the *fileIO* tags. If there are notes tagged with *python3* `AND` *PEP8* but `NOT` *fileIO* I don't want those notes included.

One thought is that rather than implement a potentially finicky U.I. feature (*especially* in the Web client, I think), how about tweaking **Search** so that search arguments prefaced by the octothorp ("#", a.k.a. pound sign a.k.a. hashtag) would list only notes that contain notes with specific tags or combinations of tags? (As of this afternoon that doesn't seem to work in the W7 desktop client?)

Cheers, thanks, & hope this helps,
Riley
SFO

**Comment by mobitar** [comment]
So a query like "#python #security xx" would look for notes that contain the word  "xx" and have the tags python and security?

**Comment by WritingSolutions2020** [comment]
I didn't even think about notes text in conjunction with an enhanced tags search capability -- sounds like a nice enhancement to my original idea.  8^p

My original thought was to be able to make use of combinations of tags to more narrowly focus a list of notes. Per my original example, IF I today click my `#python3` tag, THEN the Standard Notes client lists ALL notes with that tag. If I only want a particular subset of notes pertaining to `#python3`, say notes about Python 3  `#fileIO` but NOT notes about `#java #fileIO`, then I don't believe there's currently a way to do that: I can only use tags to view ALL Python 3 notes or ALL `#fileIO` notes or ALL `#java` notes without additional qualifiers.

That use case is a logical `AND`-ing of tags. Now I'm wondering if logical `OR` could be part of the **Tags Search** feature. (I haven't analyzed whether XOR would make any sense in this context...)

Central point is to be able to use  tags in combination to list specific categories and sub-categories of notes...

Cheers, thanks, & hope this helps,
Riley
SFO

**Comment by mobitar** [comment]
Makes sense, I think that could work. I'll revisit this conversation once I begin to invest more time in the search engine, which I hope can be soon.

**Comment by WritingSolutions2020** [comment]
For what it's worth, there is another notes program whose desktop client GUI enables one to select multiple tags to filter the display of notes:

![notesprogramwithtagssearch](https://user-images.githubusercontent.com/3333327/29005234-352f375c-7a8b-11e7-85ae-e4a8e37f1982.png)

As shown, that search functionality includes the ability to combine both tags and folders in a  targeted search. OK, now consider this -- if a user could save a search under a free-form name or ID, would not that named search provide the equivalent of a quickly accessible customized view? As shown in the screenshot, I could then create a "view" that lists notes pertaining to "A" `AND` "B" `OR` "C", et cetera.

Cheers, thanks, & hope this helps,
Riley
SFO

**Comment by WritingSolutions2020** [comment]
**2017-08-23 update**: As my collection of notes grows, my desire to be able to use combinations of tags to filter a list of notes has become ever more important to me.

I have in the past tried using another notes program's folders to organize notes. What I learned was that folders weren't all that helpful: I sometimes wanted to find or list notes that crossed folder boundaries. And moving stuff around from folder to folder had reached the point of diminishing returns.

The good news was that notes program enabled me to combine tags in a Boolean `AND` search. That became a faster -- and more flexible -- way to manage notes than folders. At that point I moved all my notes out of folders and used tags to in essence create customized views. The only thing I wished I had was the ability to save certain tags-search statements as a way of being able to select a particular "custom view".  (Not incidentally, that program's folder panel enabled one to create separate notebooks. That sounded good at first. But I realized that I could use Boolean tags-search to create the illusion of notebooks without having to actually create them, move stuff in and out of them, et cetera...)

Overall I'm liking Standard Notes. Maybe too much so -- as stated, as the number of notes increases it's becoming less easy to target particular subsets of those notes. Just sayin'...

Cheers, thanks, & hope this helps,
Riley
SFO

**Comment by mobitar** [comment]
Yeah, I get what you're saying and am starting to notice the same thing myself. I hope to get to it at some point.

**Comment by tmchartrand** [comment]
I'd like to second this request!

**Comment by mobitar** [comment]
You can now create dynamic filters with smart tags: https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters
