### ISSUE TITLE
Paste Image into Secured Spreadsheets editor

### ISSUE THREAD

**Issue by hanct** [standardnotes/forum#470]
I am currently using Web version of the standardnotes to test out the Secured Spreadsheet editor.
For Secured Spreadsheets (beta), i am not able to  copy an image from a webpage, and then paste into the spreadsheet cell? Or will this work in desktop version Standardnotes (i cannot test it out, as I have yet to purchase the extensions)?

**Comment by mobitar** [comment]
Images will not work generally across any editor, as we do not support inline attachments currently. You can use FileSafe for attaching non-inline files to your notes. Please see here for more on FileSafe: https://standardnotes.org/help/36/how-do-i-attach-encrypted-files-to-my-notes

You can also try out the various extensions in the demo: https://standardnotes.org/demo

**Comment by hanct** [comment]
Ok. That will mean at current moment, there is no way to display image visually on the note.

**Comment by mobitar** [comment]
Yes that's correct.

**Comment by hanct** [comment]
Thanks. But I just realize that Plus editor allow me to display image visually on the note, but upon switching to the code view, I realize it is just pointing to the image URL. 
I assume this is not considered inline image file. In other word, if the server hosting the image is down, my displayed image will be gone.

Hope my understanding is correct.

**Comment by mobitar** [comment]
Yes, that's correct. All the Markdown editors and Plus editor can embed images hosted elsewhere, but none of them will handle hosting/upload for you.
