### ISSUE TITLE
Can't scroll in the editor on Android

### ISSUE THREAD

**Issue by kirillzh** [standardnotes/forum#473]
Android mobile version doesn't seem to allow scroll the text when it's too long, it goes beyond the keyboard and gets overlapped by it.

**Comment by mobitar** [comment]
@kirillzh there is currently a known issue where when you add text with the keyboard up, the scrollable area does not update. To get it to update, dismiss the keyboard and re-open it. Still haven't been able to find a good solution to this I'm afraid..

**Comment by kirillzh** [comment]
I see. Is there a ticket for this? Would be good linking it here and closing this issue.

**Comment by mobitar** [comment]
Yes please see here: https://github.com/standardnotes/mobile/issues/130
