### ISSUE TITLE
Secured Spreadsheets editor - Add Row/Column not working

### ISSUE THREAD

**Issue by hannah23280** [standardnotes/forum#474]
Hi,
I am trying out the web version of secured spreadsheets editor, and try to select a cell, before clicking Add Row Above, Add Row below, Add column left, Add column right, but they seem not to have any effect. Is this considered a bug?   

Just curious, is this spreadsheet editor a third party plugin developed by another vendor? If yes, I could actually inform this vendor of the "bug" (assuming it is really a bug"). hope they can resolve it.

**Comment by mobitar** [comment]
Yes indeed, this is a known limitation. Kind of frustrating, and I've tried looking for workarounds, but the only one I found is that adding a row or column will add it to the end of the sheet (which is what it does now). It is developed a third party, take a look here: https://www.telerik.com/kendo-ui

**Comment by hanct** [comment]
Hi, thanks for the reply. But strangely, I try their demo spreadsheet located at https://demos.telerik.com/kendo-ui/spreadsheet/index
The function to add row/column seems to work as expected. One of the possibility is that they could have updated their library version to resolve this.

**Comment by bryvin** [comment]
I believe it also worked in the current version that Secure Spreadsheets uses, however there was a limitation with how SN had to store the data as JSON if I remember correctly?

I do have an idea on how to fix this and bring back the expected result, I will see if I can implement it and submit a PR to mobitar. I'll be sure to update this post if I get any progress.

**Comment by hanct** [comment]
Great! Thanks bryvin, and thanks Mobitar!

**Comment by mobitar** [comment]
@bryvin hmm..I'm having trouble recalling exactly what the issue was, but you may be right. Doesn't seem to make much sense though..

**Comment by myreli** [comment]
Duplicates https://github.com/standardnotes/forum/discussions/2470
