### ISSUE TITLE
Theme Toggle for 'No Distraction' not visible

### ISSUE THREAD

**Issue by trvllngmn** [standardnotes/forum#475]
Hi

On [No Distraction](https://standardnotes.org/extensions/no-distraction) extension page, you have a quick toggle for this theme on the status bar In the Demo.

After closing/updating, I can't seem to make this appear in the Desktop App, or browser.

Could you give a steer?

**Comment by bryvin** [comment]
I believe it's most likely a caching issue. If you go to the Extensions panel and just uninstall and re-install the No Distraction theme it should re-download the newest version and give you the quick toggle.

**Comment by trvllngmn** [comment]
Worked a charm! -- Thanks
