### ISSUE TITLE
Google Drive backups placed in wrong folder

### ISSUE THREAD

**Issue by AboveMyPaygrade** [standardnotes/forum#478]
Not sure what's causing this issue, or if I'm opening this issue in the correct location; feel free to move it, if necessary.

I'm on the paid version of SN (have been for about a year, which is relevant), and have enabled the daily backups to Google Drive.  The folder convention is as follows:  Standard Notes > [YYYY] > [Month] > [Backup file, named 'March 5 2019' for example].

I'm not sure if I started adding the files to their own [YYYY] folder or if the backup utility did (if this isn't behavior by the app, please close the ticket, as I probably did it and forgot), but after I had one year of backups, I noticed that backups of the following year were mixed in to those of the prior year.  For example, starting in February, I noticed that the [Month] folder contained backups for both 'February 28 2018' and 'February 28 2019'.

I assume the expected behavior is for each year to be in its own folder, and each month within to be much the same.

Personally, I'd prefer if the backup naming convention were to follow ISO 8601, which may even remove the need for multiple subfolders.

Thanks for the work!  Excellent product!

**Comment by mobitar** [comment]
You know, strange, you're the second person to mention this. I took a deep look at the code after the first person, and couldn't find anything out of place. But there must be something going on. I'll have to take another look. For the record, this issue does not happen to me, and backups are stored in the correct location. Do you recall if you tinkered with your folders at all in Google Drive in the recent past?

**Comment by AboveMyPaygrade** [comment]
> Do you recall if you tinkered with your folders at all in Google Drive in the recent past?

Recent past, no.  However, I _do_ recall doing something to the folder structure right after I enabled the daily backups (right around a year ago), though I'll be damned if I remember exactly what it was.

Tell you what - I'm going to disable the daily backups, move what's currently there to another location, and essentially leave a totally bare folder for SN to drop backups into.  I'll then re-enable the backups to see how SN behaves.  If anything, I can also delete the current backup settings and start from scratch, to see how that affects behavior (this will likely be my second step, if issues persist).   It may well be that SN isn't too happy with directory changes once the backup regime is in place.

I can keep an eye on this for a bit and let you know what's up; the backups are _there_, which is the important part...they're just being filed in a slightly inconvenient way, which I can live with.  I also can't immediately rule out user error on my part, so I'm fine with just sitting back and watching for a while to see how this shakes out.

I'm good for now, so if you want me to close the issue, let me know.  I figure I can reopen it if I get more information.

**Comment by mobitar** [comment]
Ok great, let me know if you see any changes in behavior. I do want to explore this in more detail very soon. Just wrapping up a few other projects. Feel free to leave this issue open so that others can find it if they are experiencing something similar.

**Comment by AboveMyPaygrade** [comment]
@mobitar 

I'm back, with a small update.  I'll walk you through what I did, in the hopes that you can spot any errors on my part.

1. As I understand, once I enable the backups, the Standard Notes app (SN) will create a folder on Google Drive (or any other supported service, presumably) named 'Standard Notes', into which subsequent backups will be placed.

2. With that in mind, I created a new folder in Drive, naming it 'SN Historical', and moved everything that was in the SN-created 'Standard Notes' folder into 'SN Historical'.  The 'Standard Notes' folder was now entirely empty, as if it had just been created by SN.  Here's how the folder structure looked:  

- My Drive
  - Standard Notes

The stuff that was previously in the folder was moved to:
- My Drive
  - SN Historical
    - 2018
      - [2018 Month]
    - 2019
      - [2019 Month]

3. Recall that the 2019 directory and [2019 Month] subdirectory was created by me when I noticed that SN was saving backups for 2019 in the 2018 folders.

4. I then waited a few days, and checked on the folders.  I expected that SN would start saving subsequent backups into the 'Standard Notes' folder it had initially created in Drive.  This was not the case.

5. The 'SN-created 'Standard Notes' folder was empty.  Backups for 2019 were still being placed in the 2018 folders, in the 'SN Historical' folder.

6. I left the 'SN Historical' alone.  I disabled the backup in SN, and deleted the SN-created 'Standard Notes' folder.  I also deleted SN's permissions for Google drive.

7. I re-enabled the backups through SN.

8. A new 'Standard Notes' folder was created by SN, and subsequent backups were correctly placed by SN in:
- My Drive
  - Standard Notes
    - 2019
      - [2019 Month]

From what I can tell, it appears that SN does not like it when you mess about inside of the 'Standard Notes' directory it creates.  I recall that I either moved some things around, or added a folder within the initial 'Standard Notes' folder after I enabled the backups some time ago.  This likely caused the issue, but it wouldn't have been noticed until the year rolled over.

Hope this is helpful.

**Comment by mobitar** [comment]
Hmm, very interesting. Thanks for the detailed report. This might be a good clue:

> The 'SN-created 'Standard Notes' folder was empty. Backups for 2019 were still being placed in the 2018 folders, in the 'SN Historical' folder.

Looks like it's searching by some kind of reference, rather than literal location. I'll take a closer look at the code when I get a chance. Thanks again!

**Comment by mobitar** [comment]
Good news, this issue has now been fixed. You can trigger a backup manually to verify by going into the CloudLink extension and clicking Perform Backup under Google Drive.
