### ISSUE TITLE
Encrypted images questions

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#48]
Few questions about encrypted images:

1. When will it be available?

2. Are the images uploaded to the Standard Notes server or do I need to connect Google Drive / Dropbox?

**Comment by mobitar** [comment]
No date yet on that. It's a pretty difficult challenge. Images uploaded using the file attachment ext are uploaded to your Google Drive/Dropbox.

**Comment by ClarkeCC** [comment]
@mobitar Could images also be hosted on GitHub? I've seen one other note software do this, though the images are not encrypted. Thank you for the information, best of luck!

**Comment by mobitar** [comment]
I'm sure it's possible, if you link up a repo or something. But doesn't sound ideal.

**Comment by rsnitsch** [comment]
For me, this is the only important missing feature in Standard Notes. Are there any updates on this yet?

**Comment by mobitar** [comment]
This feature will require lots of careful work, and right now I'm still focusing on the fundamentals. I don't imagine there'll be any new updates on this for a while.
