### ISSUE TITLE
FileSafe - Keys Export Option Question

### ISSUE THREAD

**Issue by luisborba** [standardnotes/forum#482]
In notes where I have uploaded files to FileSafe, when I expand the FileSafe menu, under Keys I see the option to export all the files. It exports to one JSON file. Since I'm a noob can someone explain what the purpose of this is? Is it an export of all my file attachments and can I somehow decrypt them offline? 

What happens if I delete the key?
Cheers.

**Comment by mobitar** [comment]
The export only exports your keys, and not your files. It's just a peace-of-mind measure for people that want to physically see their keys, so that it doesn't seem like a black box. But otherwise, your keys are stored in Standard Notes the same way your notes are—encrypted, and included in any backups you download.

**Comment by luisborba** [comment]
In the future will there be an export all option for all FileSafe files (encrypted or decrypted) like we currently have for notes, that we can then access with the offline tool?

**Comment by mobitar** [comment]
You can drag and drop encrypted files on to the FileSafe interface, and it will decrypt them. As for export all files, I'm not sure that would be feasible, technically. It might work for a handful of files, but if you have a hundred files, it might take hours to download and decrypt all those files in the browser. In any case, the files are stored in your own storage provider, and not with us, so you'd have to make your own backups by just copying and pasting the files to other locations.

But I'm sure we'll make improvements in this area over time. I'm just not exactly sure what shape or form that will take.

**Comment by luisborba** [comment]
I'm using the standalone Mac app. I see what you mean, kind of. I can drag a file **onto** the FileSafe interface and it will **encrypt**, but I don't see any way to **decrypt** like you described.

**Comment by mobitar** [comment]
You would drag an encrypted file from your Dropbox/Google Drive onto FileSafe, and it will decrypt it and download it. If it doesn't seem to work for you, be sure FileSafe is up to date from the Extensions menu.
