### ISSUE TITLE
Android App Import Export

### ISSUE THREAD

**Issue by hp6730** [standardnotes/forum#484]
Hey everyone!

I'm a standard notes newbie and now after some hours a little bit more crazy than before.

I want to use the Android App without an account. 

First problem: The backup-export-to-disk fuction doesn't work.

I'm using a Galaxy Tab A 10.1 2016 Android 8.1 and there is no way to find the export-path which standard notes shows with Total Commander or the Samsung files App. I think standard notes means the android folder and then com.standardnotes but the folder is empty.

Second problem: I can't find an import-button.

I hope anyone understands what I mean and how to solve it!

Thank you for your help!

**Comment by asdfghgit** [comment]
I myself spent some time researching those problems and this is how I understand it.
Regarding first problem:
The export path, in my device anyway, is not in the "android" folder, but in the "data" folder, and this one is not accessible by the user, unless the device is rooted. Mine is not rooted, but I managed to save the exported file to an accessible place anyway. The thing is, the export function suggests to open the file, so i opened it in a text editor and saved in a place I wanted. Later I successfully imported it to the desktop version.
Regarding second problem: there isn't any import in the android app, although the author has plans implementing it. I have no idea if or when that happens.

**Comment by hp6730** [comment]
Thank you for your research-work!!!

I hope the problems will be fixed soon, because without this features standard notes is maybe the wrong app for me.

The only way could be an own standard-notes-server at my Windows 10 PC which only works in my home-wireless-LAN, but I have no idea how to realize it.

Please could you write me which text editor you used?

I wish you a nice evening and a good start for the next week!

**Comment by asdfghgit** [comment]
> Please could you write me which text editor you used?
> 
In "Choose Export Method" dialog I tap on "Save to Disk", "Backup Saved" dialog shows up, in which I tap on "Open File". The next dialog is the "Open with" one. I choose "Totalcmd-Editor".

**Comment by mobitar** [comment]
The issue related to where backups are saved on Android should be fixed in the next release. There is no import function on mobile, and it's not yet clear when we'd add that. The mobile app is largely a companion app to the web/desktop app, so some of the advanced functionality will be deferred to those apps.

**Comment by hp6730** [comment]
Sorry for my very late answer - many, many thanks to asdfghgit .

@ mobitar: Thanks for fixing the Export in the next release. I would be really really happy about the Import-function. I would use the app for, among other things, taking notes of conversations with people who have fled from other countries. They trust in me and I don't want to disappoint them - no matter how good the encryption is, outsourcing data to a server is too hot for me. 

Have a nice week!
