### ISSUE TITLE
Opening multiple Standard Notes windows on OSX

### ISSUE THREAD

**Issue by frego** [standardnotes/forum#485]
It'd be great to be able to open Standard Notes multiple times on OSX to work on different notes at the same time.

Multiple windows should be the easiest to implement.
Multiple tabs would be awesome too.

**Comment by mobitar** [comment]
There is a hard limit of 1 process accessing the local database at a time. Multiple windows would not work. A multi-note editor could be a possibility in the future.

**Comment by bumper314** [comment]
+1

I've been desperately trying every note app I can find as a viable Evernote replacement, and yet virtually zero of them allow opening two windows at the same time!  This makes no sense to me.  Could you imagine using a web browser and only being allowed 1 window, no tabs?!  Ludicrous.  I have 84 Evernote windows open at this moment.  Multiple windows is absolutely critical to any real research or knowledge management workflow.

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/958
