### ISSUE TITLE
"Unable to locate account for email"

### ISSUE THREAD

**Issue by glow12121** [standardnotes/forum#488]
Hi,

I am getting this error when logging into S. Notes on Android. Sign-in on Linux app and web interface is without a problem, though.

**Comment by thumos333** [comment]
Really strange: On Android, I was able to create another account with the same email.

Ended up creating a completely new account.

**Comment by mobitar** [comment]
Note that the email field is case sensitive, so that could have been the issue.

**Comment by thumos333** [comment]
Again, it's strange but I've just been able to enter the old account, with over 700 notes. A day ago, I tried this to no avail maybe a dozen times or so. But now it works.

Anyway, thanks for making S. Notes.

**Comment by mobitar** [comment]
I can't imagine this part of the software acting non-deterministically, but if you email me at hello@standardnotes.org with your account email, I can check to see if there's anything unusual with your account setup.
