### ISSUE TITLE
Lack of documentation on installing extensions

### ISSUE THREAD

**Issue by LINKIWI** [standardnotes/forum#489]
While there is detailed developer documentation for [building and maintaining an extension](https://docs.standardnotes.org/extensions/building-an-extension), there is a frustrating lack of documentation on how to deploy official [SN extensions](https://github.com/sn-extensions) end-to-end.

For example, I host my own Standard File server and Standard Notes web client. Let's say I want to install the official Simple Task Editor extension on my self-hosted instance. At the time of this writing, there is no official documentation detailing step-by-step how to do this, the same way there exists step-by-step documentation on [hosting Standard File on cloud infrastructure](https://docs.standardnotes.org/self-hosting/self-hosting-with-ec2-and-nginx).

That said, however, the extensions architecture is clean enough that I was able to deploy the official extensions on my instance after an evening of hacking around. Is https://docs.standardnotes.org accepting documentation PRs? I am willing to contribute detailed instructions to save headaches for other users. Alternatively, I'm happy to contribute a Docker image (or similar) with all official extensions pre-installed, as an easier "one-click" deployment solution.

**Comment by mobitar** [comment]
I wouldn't necessarily call it intentional, as it's just not something I've gotten around to, but quite honestly, there's no incentive for us to make a very easy guide to self-hosting **our** extensions. If everyone did that, we'd be in trouble. Instead our guides focus on deploying generic extensions.

> Alternatively, I'm happy to contribute a Docker image (or similar) with all official extensions pre-installed, as an easier "one-click" deployment solution.

This doesn't sound so much like a contribution as it does something that would dissuade users from supporting the project ;) Unlike our core suite of applications and server, the extensions don't have an open-source license. They're just "public source" as in you can read the code, but there are no rights granted.

**Comment by LINKIWI** [comment]
That's unfortunate, as it seems Standard Notes is very popular within the self-hosted community. Since there doesn't seem to be any interest in first-party support for deployment of official extensions, I'll document the procedure elsewhere.

**Comment by mobitar** [comment]
Extensions are our paid product. If self-preservation is "unfortunate", then so be it. A LOT of the ecosystem is completely free and open-source, including the desktop app, the web app, the mobile app, and the sync server. That's a lot of code and countless years of work, out there, completely free, with no expectation. But we need a small part of it behind a paywall, or else we fail and disappear, and none of this exists. Who else will subsidize our work if not our paying customers?

**Comment by LINKIWI** [comment]
I don't have any concerns about the paywall or business model. Those concerns are outside of the scope of this issue anyways; here I'm just raising issue about the lack of deployment documentation for users who want a fully self-hosted solution for end-to-end data ownership.

But anyhow, I've closed this issue since there's nothing actionable here for first-party support.
