### ISSUE TITLE
Using # to create tags 

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#49]
It would be much more convenient to write # in the note itself to create a tag. The current tag section could be used to display and have a number count of how many and what tags you have written in the note.

**Comment by mobitar** [comment]
This would be a job for an editor extension.

**Comment by ClarkeCC** [comment]
@mobitar could it be added to a already existing editor extension?

**Comment by mobitar** [comment]
It could, but I don't currently have the time to do so..
