### ISSUE TITLE
Nested Lists

### ISSUE THREAD

**Issue by gio-cefalu** [standardnotes/forum#490]
I can't seem to get Standard Notes to create a nested list.  Something like:
1. Section 1
    a. sub-section 1
    b. sub-section 2
    c. sub-section 3
2. Section 2
3. Section 3
    a. sub-section 1
        i. sub-sub-section 1
        ii. sub-sub-section 2

Someone else had this issue as well, but there was no real resolution.  It just started "working" for them.
https://www.reddit.com/r/StandardNotes/comments/9ypjj1/nested_lists_in_markdown/

I paid for extensions and have tried several editors including Simple Markdown editor and Advanced Markdown Editor, but neither of them give the expected behavior.

Thanks.

**Comment by mobitar** [comment]
By nested do you mean alternating between numbers and letters for bullets? Because using the Advanced Markdown Editor, I do get nested lists if I tab on a new line. It doesn't change the line bullet lettering, to go from say `1.` to `a.`, but I'm not sure which MD editor in general would do that. Do you have examples of a markdown editor which does this?

**Comment by gio-cefalu** [comment]
Using the Simple Markdown editor, I can't get a list at all.  There's no menu item for a bulleted or numbered list.  If I start typing with numbers (1. Heading1), then it just thinks I'm typing a number.  There's no list at all (it's not smart enough to start a list, but there's no manual option to start a list either).

If I use the Advanced Markdown Editor, I can select the option in the menu to start numbered list, which works, but as soon as I hit the TAB key, it just pushes the number over a bit and removes the bold.  It does not re-start the numbering, nor does it alternate numbers and letters; based on your response, It sounds like the last part is expected behavior.  In the Advanced Markdown Editor, it looks like the following:

**1.** Test
  2. stuff
     3. more stuff
**4.** Test 2
**5.** Test 3

Even if it doesn't alter numbers or letters, I would at least expect the following:

1. Test
    1. stuff
        1. more stuff
2. Test 2
3. Test 3

Also, I'm using Windows 10, and the version 3.0.6 of the app.

**Comment by mobitar** [comment]
Gotcha. Yeah, the Simple Markdown Editor offers no formatting frills at all, so that sounds right. As for alternating or restarting numbers, that would be a nice to have. I don't believe any of the editors offer this. Our editors are all based on open source software however, so if you find an external MD editor that's open source that does this, we can take a look at incorporating it within SN.

**Comment by gio-cefalu** [comment]
I'm confused at the Advanced Markdown Editor, then.  It's not possible to ever have a sub-section?

According to the Reddit link above, they were able to at least get it to do...

1.Stuff
        1. more stuff
         2. even more
2. another heading
3. yet another
        1. another sub-section
         2. and another
4. back to base level

I'm not seeing that behavior, but I think that should be pretty standard for a numbered list.

**Comment by gio-cefalu** [comment]
Arg, it's not showing the proper spacing or tabs when I comment, but each time it starts numbering at "1" again, it should be tabbed over.

**Comment by bryvin** [comment]
I just gave this a shot in a number of online Markdown editors and they all appear to have the same functionality regarding indenting and nested lists. It auto increments the # but it does not reset back to 1 on children nodes (as you would expect). I also Google'd around and it seems there is mixed conversation on this exact thing.

Have you found any specific Markdown editors that act as expected? As Mobitar has said the Markdown Editors in SN currently are 3rd party projects that have been integrated as an extension but if there are better options new Extensions _could_ be created.

**Comment by gio-cefalu** [comment]
According to this post, it should be working in Standard Notes:
https://www.reddit.com/r/StandardNotes/comments/9ypjj1/nested_lists_in_markdown/
They even show a screenshot of it in action:
https://imgur.com/a/xCFocbX

And they are doing this in the Standard Markdown Editor. According to that poster, Pfoeber, this type of behavior is supported by markdown editors.

I'll do some digging of OpenSource markdown editors to see if I can find one that works as the Reddit link suggests.

**Comment by gio-cefalu** [comment]
So, MarkText works as I would expect with the new numbering on each line.
https://marktext.github.io/website/

I'll do some digging for others.

**Comment by mobitar** [comment]
I can replicate Pfeober's results in the Simple Markdown Editor. You'd just have to manually tab to indent, and it handles numbering for you:

<img width="501" alt="Screen Shot 2019-03-13 at 11 38 50 AM" src="https://user-images.githubusercontent.com/3277844/54297302-9b98e900-4584-11e9-8967-7102c6c1f4a2.png">

**Comment by gio-cefalu** [comment]
That still doesn't work for me.   How do you get it to start a list to begin with?  I can't get the Simple Markdown Editor to create a bulleted or numbered list in any manner.  I've tried on multiple PCs, both with version 3.0.6.

**Comment by mobitar** [comment]
You have to manually insert the numbers. In the left, I typed all those characters manually. There's no autocomplete, in that editor at least.
