### ISSUE TITLE
use in Tails over TOR network

### ISSUE THREAD

**Issue by surfchaser** [standardnotes/forum#491]
Can't get the desktop app to connect to standard notes server over TOR.  Is there a way to control the app proxy settings?  Using Linux (debian based) Tails connecting over the TOR network.  thx
related docs - 
https://tails.boum.org/contribute/design/Tor_enforcement/
https://tor.stackexchange.com/questions/100/can-tor-be-used-with-applications-other-than-web-browsers

**Comment by mobitar** [comment]
The desktop app doesn't currently support custom proxy config. On the radar though.

**Comment by davterra** [comment]
Is tor connectivity any closer?

**Comment by baptiste-grob** [comment]
Afraid not… The app should now respects system-defined proxies though.
