### ISSUE TITLE
[request] saving indicator very distracting

### ISSUE THREAD

**Issue by rschouwenburg** [standardnotes/forum#492]
I find the "saving" and "all changes saved" indicator very distracting when I am typing - both on mobile as on the desktop app. I am unsure what the purpose is of this indicator. In general, I would expect an indicator to show if something is wrong, but maybe I am missing something. Anyway, I would appreciate if you could make it less visible, hide it or whatever you think is best.

Thanks for making Standard Notes. I love it.

**Comment by mobitar** [comment]
Perhaps a preference in the future might make everyone happy. For the record, < 1% of people have problems with the saving indicator. Most people get used to it. In the mean time, you can make a custom theme that hides the indicator for web/desktop.

**Comment by rschouwenburg** [comment]
I will not dispute that. Making my own custom theme piqued my interest. Can you give me some pointers on how to accomplish that?

**Comment by mobitar** [comment]
Please see here: https://docs.standardnotes.org/extensions/themes

**Comment by Simon-Sohrt** [comment]
I just wanted to say that the sync-status drives me nuts as well. I think a preference button is a good idea. 
Thanks for the tip with the themes and thanks for creating standard notes in the first place. It is awesome!

**Comment by effieeee** [comment]
Now tracking here due to the new appearance of the saving indicator: https://github.com/standardnotes/forum/issues/2227
