### ISSUE TITLE
Blog Posts - Trashed Items Do Not Unpublish

### ISSUE THREAD

**Issue by luisborba** [standardnotes/forum#493]

**Comment by luisborba** [comment]
As I was typing this I saw others had similar issues. I created a bunch of test posts, then Trashed them. Emptied the Trash folder but they are still present. Not sure what to do now.

**Comment by mobitar** [comment]
You'd have to unpublish items before you delete them. At this point, I'd have to manually delete posts from your Listed blog. Please email me at mo@standardnotes.org with your blog details and which posts you'd like to delete.

**Comment by rothconnect** [comment]
I have the same problem with this posting:
https://listed.standardnotes.org/@rothnotes/5157/listed_styles-css

**Comment by mobitar** [comment]
The Listed author Settings page now contains an option to delete any post. Simply open your Settings via the Action menu in Standard Notes, and scroll to the All Posts section, and you choose any post to delete, even if it's already been deleted in SN.
