### ISSUE TITLE
No way to navigate spreadsheet editor

### ISSUE THREAD

**Issue by kathytu** [standardnotes/forum#494]
I added a sheet using the Secured Spreadsheet editor, and I'm not able to get it to open properly in Android. I tried to look at different parts of the spreadsheet, but navigation doesn't seem to register and I am having a hard time selecting specific cells.

**Comment by mobitar** [comment]
The spreadsheet editor is indeed complex, and full mobile support is still wanting. We don't develop this software ourselves, but we'll be pulling in updates from the developer every year. My hope is that they'll continue to make progress on this very impressive piece of software, but for now, it's definitely web/desktop focused.
