### ISSUE TITLE
After search, note list does not update in mac desktop app

### ISSUE THREAD

**Issue by zarazum** [standardnotes/forum#496]
I search for text in tagged notes. Total number of notes with that tag is 50+ and 7 notes were found.

After I clear search query, note list displays only 7 notes even when I switch to **All notes** or **Archived**. Content of 7 notes changes but no additional notes become visible. 
At this moment I'm really starting to panic. Clicking Refresh does not help.

I found that I have to _reduce window height_ so that scrollbar appears in note list — after that app starts to update list on scroll and reveals all the notes.

Please rectify that behaviour.

System info:
macOS 10.14.3 (18D109)
Standard Notes 3.0.6

**Comment by mobitar** [comment]
Hmm, I can't seem to replicate this. Here's what I tried:

1. Choose a tag with around 50 notes.
2. Do a search such that the number of results is less than the height of the screen (that is, no scrolling is required to see all the results).
3. Remove the search by pressing X, or by clicking All notes.

At this point, I can scroll the list as usual.

If you have a different set of steps that can replicate this issue, please share.

**Comment by zarazum** [comment]
I reproduced the issue at least three times before writing here. 
Sequence of steps is the same. I removed the search using X in the input. 
The only difference is that first time I resized window before removing the search. Will investigate further.

**Comment by zarazum** [comment]
Couldn't reproduce after relaunching desktop app. Everything works as @mobitar described. Mysterious thing.
