### ISSUE TITLE
Certain options don't work

### ISSUE THREAD

**Issue by bluk00** [standardnotes/forum#497]
- Move to Trash and Extensions do nothing when clicked.
- Manage Privileges simply closes the account menu. (Windows and Web)
- Manage Privileges on ios does nothing.
- Protected notes do not respond when clicked.

This is the same across windows, web, and ios. 
Signing out and back in does not resolve the issue.

All the options work when signed out and I restore a backup. 
However, upon signing in again the options do not work.

**Comment by mobitar** [comment]
Can you email help@standardnotes.org from your account email? This issue is related to having used an older version of the app to process some items. But it would need some intervention on our end to solve for your account.
