### ISSUE TITLE
Importing from backup silently fails

### ISSUE THREAD

**Issue by tmoravec** [standardnotes/forum#498]
Hi!

I'm trying to import a large-ish backup from OneNote. Converted to the SN format using https://github.com/oxhacks/onestandard so I have a JSON file that contains my notes and looks quite reasonable. Importing this JSON file silently fails. Trying the web version (in FF) and desktop version (Linux).

What exactly I do:

1. Open Extensions/Batch Manager.
2. Open Backup Explorer.
3. Upload the JSON file.
4. I get a list of all my notes and tags. Looks reasonable.
5. Select either one note or all.
6. Click Recover 1 Items
7. Confirm the alert window: `Do you want to recover 1 items? Items will be recovered as new items and will not replace any existing data.`
8. Confirm another alert window: `Your items have been recovered. Note that the items' create date is kept to the original value, so may not appear at the top of your notes list if not sorting by date modified.`
9. Close the Backup Explorer and Extensions windows.
10. **The recovered items are nowhere to be found.**

Any ideas what to try next? Any debugging steps I should perform?

Thanks in advance!

**Comment by mobitar** [comment]
Do you have a sample import file I can test out? In the meantime, you can use the built-in import functionality instead, via Account -> Import Backup.

**Comment by tmoravec** [comment]
The built-in import functionality fails in the same silent way, says `Your data has been successfully imported.` but the note is nowhere to be found.

**Comment by tmoravec** [comment]
[single.txt](https://github.com/standardnotes/forum/files/2997177/single.txt)

A sample of a failed backup. Renamed `single.json` to `single.txt` so GitHub accepts the file.

**Comment by mobitar** [comment]
The reason it's failing is `"content_type": "note",` should be `"content_type": "Note",`—the N in note needs to be capitalized. Content types are case sensitive. Technically, the import is succeeding, as the app does not discriminate against any content type. So an item of type "note" is created, but nowhere in the UI are items of type "note" displayed.

If this is an issue with the converter tool, I would notify the author of this.

**Comment by tmoravec** [comment]
If the content type is not what's expected, that's surely an issue for the converter. I'll create one.

As an engineer, I understand the view that the import is technically succeeding, but the user experience is another story.

Additionally, does this mean that I have thousands of items in the app and they are not displayed anywhere? Do they synchronize, too?

**Comment by mobitar** [comment]
> Additionally, does this mean that now I have thousands of items in the app and they are not displayed anywhere? Do they synchronize, too?

Yes, probably, though I have not tested this. They should appear in the Batch Manager extension though, since that one also does not discriminate against content types.

If not, you can always reset your account: https://standardnotes.org/reset
