### ISSUE TITLE
Links in /extensions should be updated

### ISSUE THREAD

**Issue by snnx** [standardnotes/forum#499]
The list of extensions here [https://standardnotes.org/extensions](https://standardnotes.org/extensions) only point to the online demo [https://standardnotes.org/demo](https://standardnotes.org/demo) 

Clicking on Simple Task Editor, for instance, should take you to [https://standardnotes.org/extensions/simple-task-editor](https://standardnotes.org/extensions/simple-task-editor) not the demo.

In the desktop version of SN, beside each extension there is an "Info" button that links to the correct page about the extension. I feel that that's the way the /extensions page should work.

**Comment by mobitar** [comment]
If you click the image, it will take you to the demo. If you click the title of the extension, it will take you to the extension page. The individual extension pages are mostly useless, which is why we link to the demo primarily.

**Comment by snnx** [comment]
@mobitar I didn't realise the title was a link.

I know these are only little things (sorry if I've being picky), but I've found this page frustrating i.e. if I click on the image of the Task Editor it takes me to the demo, which opens up a note using the Advanced Markdown Editor. it's not a good flow.

My suggestions (feel free to ignore):

* Clicking on image opens up /extensions/name-of-extension
* Remove the link on the heading, as it's not clear that it is a link
* Add a link beside **Try It** labeled **Info** that points to /extensions/name-of-extension (**Info** is what you use on the desktop app)

> The individual extension pages are mostly useless

I feel the opposite. The screenshot and extra information about an extension like the Task Editor is a simple introduction that allows the user to get a feel for the extension without diving into the demo.

**Comment by mobitar** [comment]
I'd like to add a little more information to the individual extension pages. At which point I agree, going to these pages would be more useful than a demo, especially if you're clicking multiple links and getting to the same demo every time.
