### ISSUE TITLE
Had difficulty deleting notes...

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#5]
I've been using computers since 1981 and I'm hugely confused by the U.I. of both the Web client and the Windows desktop client.

I had one heck of a time deleting items. Only after I installed the Folder extension did I *finally* find some light-grey text that red "Trash". Very well hidden! Might want to make that a bit clearer.

And what if one doesn't have the Folders extension installed? Deleting notes and so on seems WAY too hard. I keep looking for a Delete button or menu item or SOMETHING that enables me to simply get rid of things I don't want.

![standardnoteswindows7client](https://user-images.githubusercontent.com/3333327/28084703-5390833e-662e-11e7-9e72-5ac509224e2f.png)

I found my way to Account > Data Dashboard. I keep needing to delete stuff over and over again. Very confusing. Not only do items seem to magically (re-)appear again and again, but even if all I've tried to do is delete stuff I end up with what seem to be new items. Soooo confusing.

**Comment by NESTicle** [comment]
Try in Menu > Delete Note
![standard notes_2017-07-11_15-41-19](https://user-images.githubusercontent.com/1715022/28089674-66c763a2-664f-11e7-914b-944a2287dd45.png)

**Comment by WritingSolutions2020** [comment]
OK, thanks, that seems to have worked. BUT I looked for that for a LONG time...

**Comment by mobitar** [comment]
@WritingSolutions2020 sorry! Hope it's clear now.
