### ISSUE TITLE
Can't login to Web or Android clients (new user)

### ISSUE THREAD

**Issue by ChesterCode** [standardnotes/forum#50]
I'm are new user. I download PC Client 1.2.2 and register my account "ChesterLife@yandex.ru"
After add notes I install Android Client 1.4.3.

When I try login to Android or Web clients I get this message:
The protocol version associated with your account is outdated and no longer supported by this application. Please visit standardnotes.org/help/security-update for more information.

I try logoff from all accounts (PC only), change password. Unfortunately.

**Comment by mobitar** [comment]
Hey sorry about that, we did a migration yesterday and any accounts created during this brief period will have seen this issue. I've just updated your account, you should be all set now. Please give it another try.
