### ISSUE TITLE
Problem with headings in Plus editor

### ISSUE THREAD

**Issue by hrh1951** [standardnotes/forum#501]
When I attempt to use headings (1, 2, 3, etc.) in the Plus editor it works the first few times but after a few times in a given note it no longer works (i.e. selecting text and then clicking on Style / Header 2 for example doesn't change the text to Header 2.
If I just try to select Header 2 and then type text, that doesn't work either (text typed stays in Normal style).
Using current version of Standard Notes on Linux.

**Comment by mobitar** [comment]
I couldn't replicate this. Can you provide a set of steps which I can follow that would lead to this issue? Or a sample note of some sort?

**Comment by hrh1951** [comment]
Thanks for your reply.
What I do is I have some normal text, hit Enter to start a new line and
then either
1) Type some text and use the menu to set it to Header 2, or
2) Set the style to Header 2 and type some text

Here's what the HTML looks like when I ask it to email the note:
<h2><p style="font-size: 16.94px;">Text</p><p style="font-size:
16.94px;">Text</p><p style="font-size: 16.94px;">Text</p><p
style="font-size: 16.94px;">Text</p><h2 style="font-size: 16.94px;">This
was set to Header 2</h2><h2 style="font-size: 16.94px;">This was selected
and then set to Header 2</h2><h2 style="font-size: 16.94px;">Here's
another.</h2><p style="font-size:
16.94px;"><br></p><h2><br></h2></h2><p><br></p>

And I've attached a screenshot.

**Comment by mobitar** [comment]
The screenshot did not come through. But with issues like these, one has to be real specific about replication steps. You'd be the first to report this issue, which speaks to its rarity. So what we'd need are steps that start with "create a new note", and then the exact steps that lead to your issue.

**Comment by hrh1951** [comment]
It's puzzling. I can reproduce it sometimes but not others. The only thing
I can think of is that the note where I first noticed this had some sort of
"invisible" character that was preventing the style change. This is
possible because I sometimes paste in text from other applications such as
Libre Office.
thanks for your help - I'd say we can drop this ticket
Harry

**Comment by mobitar** [comment]
Ah I see, that could definitely cause some complications. If you're able to read raw HTML, you can always switch to the code view and inspect it to see the raw input, and clean up any discrepancies that way.
