### ISSUE TITLE
Windows - Open Multiple Instances?

### ISSUE THREAD

**Issue by metal450** [standardnotes/forum#502]
I'm looking at StandardNotes as a replacement for OneNote.  I noticed that trying to open multiple instances of the Windows client, all but the first instance say "There was an issue loading your offline database."

Is this expected, and is there any way around it - to permit multiple instances (showing different notes) of the application to be open at the same time?

Thanks in advance :)

**Comment by mobitar** [comment]
There's no way around this as far as I know. Only one instance can be opened at a time. What you can do as a workaround is open multiple instances of the web app (https://app.standardnotes.org) in different browsers (or incognito windows).

**Comment by metal450** [comment]
Bummer.

The browser workaround isn't really viable, as I work offline a huge percentage of the time.

Hopefully some way around this will present itself in the future :/

**Comment by effieeee** [comment]
Tracking here https://github.com/standardnotes/forum/issues/958
