### ISSUE TITLE
Self-Hostable Extensions: Version History & FileSafe?

### ISSUE THREAD

**Issue by metal450** [standardnotes/forum#503]
I'm hoping to move my (giant) collection of notes from OneNote to StandardNotes, & would like to self-host its whole "ecosystem," if possible.  I understand that StandardNotes, its storage, and *some* (but not all) of its extensions can be self-hosted (https://github.com/standardnotes/forum/issues/122).  I'm wondering about two in particular, which I didn't find on https://github.com/sn-extensions:

Can Version History (which I believe is called "CloudLink") and FileSafe be self-hosted, along with a self-hosted instance?

Thanks in advance :)

**Comment by mobitar** [comment]
Hey @metal450, FileSafe can be self-hosted. It requires both the client and server to be self-hosted. They are available in our main organization account: filesafe-relay and filesafe-client. Version history and CloudLink are not available to self-host, as they are not public repositories.

**Comment by metal450** [comment]
>>They are available in our main organization account: filesafe-relay and filesafe-client.

Ah yeah, there it is - thanks!

>>Version history and CloudLink are not available to self-host, as they are not public repositories.

So just to clarify: this means/implies that having version history like OneNote is _not_ actually possible in a self-hosted scenario? :/

Thanks again

**Comment by mobitar** [comment]
You can have local version history via Session History. Just press options in that menu and choose the option to enable saving history to disk. As for cloud history, no, I don't believe that would be possible without a custom built extension.

**Comment by metal450** [comment]
Aha - excellent, glad I asked!!  Yeah, I guess it doesn't need to be synced - I was just looking for some sort of long-term version history, to prevent accidental data loss due to use mistake or other.  Looks like Session History is just that :)

**Comment by BobWs** [comment]
Is there any documentation on how to self-hosted FileSafe?
