### ISSUE TITLE
Feature Request: "Empty Trash" button in Trash folder

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#508]
Can we have a way to empty all the trash at once when viewing the trash folder? It would be nice if I could press a button, get a confirmation, and empty all the trash at once. Much like an email client.

**Comment by mobitar** [comment]
You can do this by selecting a note in the trash, opening the side menu, and choosing to empty trash. A bit too many steps, I agree, but perhaps we'll make this more accessible in the future.

**Comment by Riotous** [comment]
@mobitar I find it faster to press and hold a note in the trash list, and press "delete permanently" to get rid of it, but yeah, an "empty all trash" is much faster, and definitely helps people like me who have a lot of notes, including smaller notes that serve no long term purpose and need to be thrown away so I can sort through important notes more easily. I personally delete notes every week so my trash can pile up pretty easily. Thanks for considering this option. It will definitely help speed things along.

**Comment by effieeee** [comment]
"Empty Trash" option now appears as part of the context menu :)
