### ISSUE TITLE
Feature request: position holding between notes (and another request for "find" dialogue)

### ISSUE THREAD

**Issue by paulwhaley** [standardnotes/forum#509]
Hi there! I am enjoying using Standard Notes as it addresses a lot of the issues inherent in other note-taking platforms. The nested tagging and markdown is particularly useful, and I like the encryption.

However, there are some issues with navigating long-form notes and cross-referencing between notes.

I realise that having multiple instances open at once is not currently achievable, except for the web app workaround (I'd be interested to know why, as I have a friend I could potentially direct at the problem, who enjoys this sort of thing).

However, if when moving between notes it would be possible to preserve the position one was in when one left (when I leave and come back, I am returned to the top of a note, which is a problem if I was editing half-way down a 2000-word draft of something), that would at least make going to another note and coming back a bit less awkward.

Also, and I may be being totally thick here, there seems to be no find function - it would be great if I could press ctrl+f to get to a specific location in a long-form note. Find/replace would also be handy. (Using the web app is a workaround for this, I appreciate that.)

That's it, thanks for the great work!

**Comment by mobitar** [comment]
Hey @paulwhaley, glad to hear you're enjoying SN! 

For maintaining position: this might be doable were it not for having to support not just the plain editor, but all of the Extended editors as well, who had have to implement custom behavior to offer this. One might say just having it in the plain editor would be better than not having it all, but in my experience, users are most frustrated by inconsistency over a missing convenience feature. All that to say, I'm not sure when and if we'd build this, but I agree it has utility.

As for find in note, there are many issues on this, but it comes down to: you can use the middle panel note search on desktop, and it will highlight all instances. On web you can use built in browser search. And if you have Extended, the Minimal Markdown Editor has in-note search via the usual ctrl/cmd + f shortcut.

**Comment by paulwhaley** [comment]
Hi @mobitar - thanks for your note! 

Maintaining position is kind of a big deal when moving between notes; I would probably just use the editor which had this behaviour. I don't think I would see inconsistency on that between editors as a deal-breaker (the editors are pretty inconsistent anyway). 

Also (because I am a jerk) I would just, erm, "ask" the Extended editors to implement this - Standard Notes is not the cheapest option out there, and this is a pretty basic feature, so there is an argument that keeping the customers happy with an industry-standard feature set is good for everyone's wallet. (I can't be the only one who has notes of 2000 words or more in length - how do the coders manage this? And as the only realistic long-form note-taking software on the market, it surprises me that Standard Notes doesn't have more long-form specific features.).

At this stage the benefits of Standard Notes definitely outweigh the inconveniences, but speaking as a customer it's pretty tight - if Evernote didn't insist on such horrific RTF formatting standards, then I would probably have stuck with them, and kept confidential stuff out of their ecosystem. Of course, I changed to you guys, so you won that argument. :)

Anyway, keep up the good work! These are only minor niggles / feature requests, I am not complaining at all.

**Comment by mobitar** [comment]
I hear you. The note space is pretty competitive. We started with a blank slate, focusing only on simplicity and encryption. Almost nothing of what you see in Extended was in our initial offering. So when you start with that, it begins to make a little more sense why we don't have these "convenience" features. But we build out over time. Not everything makes the cut. I can't even say with certainty whether this one will. It's definitely a compelling use case, but as are so many. And if we began to squeeze them all in, we know [what happens](https://standardnotes.org/longevity). Nonetheless, I appreciate your feedback, and hope we make the right design decisions over the long term to protect stability and longevity, while keeping users happy.

**Comment by paulwhaley** [comment]
Completely understand, you guys a doing a great job. If there is anything I can do to help spec out long-form note-taking features which are consistent with your ethos, just give me a shout. (I'm no programmer, but I write a lot and take a serious interest in the software I use to support my processes.)

**Comment by mobitar** [comment]
Thank you @paulwhaley, appreciate it!

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/276
