### ISSUE TITLE
Calendar Extension

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#51]
Would it be possible to have calendar like extension? To create a note on the day you need or set a reminder (more of just to show the task) for whenever you need it (week, month, year, etc).

**Comment by mobitar** [comment]
Not really sure what you mean..

**Comment by ClarkeCC** [comment]
Evernote has a feature called [reminders](https://help.evernote.com/hc/en-us/articles/208314338-How-to-use-reminders) "Reminders are a great way to keep track of notes that contain time-sensitive information or notes that you need in order to accomplish tasks."

**Comment by mobitar** [comment]
Ah, reminders are tricky. Not sure how it would work. But these would be a super luxurious feature that we could possibly add once we have super luxurious resources ;)

**Comment by TheodoreChu** [comment]
Closing this issue because the original poster deleted their account, which prevents the issue from appearing in search. Please see https://github.com/standardnotes/forum/issues/292 instead
