### ISSUE TITLE
Cloudlink not writing files by correct year

### ISSUE THREAD

**Issue by jspaetzel** [standardnotes/forum#514]
See attached image. Is this part of cloudlink? I couldn't find code to try fixing this myself.
<img width="654" alt="April" src="https://user-images.githubusercontent.com/828108/55633509-345a0780-57c5-11e9-893b-28edb95660fc.png">

**Comment by mobitar** [comment]
Sorry about that! This issue should now be fixed. You can trigger a backup manually to verify by going into the CloudLink extension and clicking Perform Backup under Google Drive.

**Comment by jspaetzel** [comment]
It looks like that fixes new files but existing ones are not being modified. I'm guessing reinstalling the extension will probably fix it but do you want to retroactively fix them?

**Comment by jspaetzel** [comment]
Actually. I just did some testing and it's not working. It created the correct folder but didn't put the file into the correct folder. So I now have a 2019/April/ folder with nothing inside.

**Comment by mobitar** [comment]
It won't fix old files I'm afraid. That would just have to be done manually. But the folder has to be created by the API. It won't work if you create the April folder yourself. I recommend deleting the April folder, then deleting it from the trash as well. Then go into CloudLink and choose Perform Backup, and it should create the April folder and place the file in the correct location.

**Comment by jspaetzel** [comment]
There it goes, I think I might have just not waited long enough. Thanks!
