### ISSUE TITLE
[Feature Request] Templates

### ISSUE THREAD

**Issue by RemiDesgrange** [standardnotes/forum#515]
Hi,

I'm using more  and more standard notes and two things that bloc me are:
* keyboard shorcut (which are already address)
* templates

Template could be a simple note, with the tag "template", and then we could load this template note in a new notes. Really helpful for meetings or recurring note taking.

**Comment by mobitar** [comment]
Templates sound interesting, but definitely not something that we would include in core. Maybe an extension. But even then, we sound very far from that, unless a third party takes on development of the extension.

**Comment by RemiDesgrange** [comment]
Ok thanks for clarity. Closing ?

**Comment by mobitar** [comment]
Open/close doesn't matter too much on the forum..

**Comment by jmason888** [comment]
@RemiDesgrange I use templates by keeping a tag of my templates then "cloning" the one I want using the Action Bar.  It works fine, except that the (a) creation date of the new note gets set to be the same as the template, and (b) the new note is still tagged as "template". I suppose I could just copy-paste the template contents.

In terms of writing an extension, the hard part for me would be figuring out what the UI should look like.  I would want to the ability to select which template I am using (I might have different templates for different use cases, for example) without adding too much cruft into the main UI.

**Comment by mobitar** [comment]
For building the UI, I recommend using [StyleKit](https://github.com/sn-extensions/StyleKit). It will remove the need to think about design or write any custom CSS. This is what we use for all extensions.

But if the only issue is that it uses the same creation date and keeps the tag, perhaps we can consider a new action to Action Bar. Maybe "Clone" in addition to "Duplicate". Clone will make a new note and copy over just the title and text, and not dates and tags.

Feel free to consider a PR in that case: https://github.com/sn-extensions/action-bar

**Comment by Wintercypher** [comment]
Just wanted to add on to this request and templates are incredibly valuable for reoccurring 1:1 meetings and project check in meetings for example. Sorry for the necro. Just about to pull the trigger on buying this software but I would love this feature.

**Comment by JaspalSuri** [comment]
Hi @Wintercypher, thanks for the feedback! Does @jmason888's aforementioned suggestion work for you? It involves using the **Action Bar** extension and the **Duplicate** feature. You can tag notes that serve as templates with a unique tag to make them easier to find. The Action Bar doesn't currently exist in the mobile apps at the moment, but is available for the web and desktop apps.

**Comment by effieeee** [comment]
Current workaround is to use the **Duplicate** feature, now found as an integral part of the note options menu:
![image](https://user-images.githubusercontent.com/54989748/198840938-04e03253-800a-4f18-86c0-49a6c2ab7b33.png)
