### ISSUE TITLE
[Feature Request] Some Editor supporting checkboxes

### ISSUE THREAD

**Issue by lost-carrier** [standardnotes/forum#517]
I would like to be able to create some text and freely insert checkboxes. Similar to the Task List Editor but not so strict in the task-list use-case.

Also not with Markdown Editor, where I have to code  "- [ ]" or "- [x]", but freely checkable checkboxes.

![Bildschirmfoto 2019-04-10 um 00 25 18](https://user-images.githubusercontent.com/3090579/55839319-bb8ddf00-5b27-11e9-9b87-2e451410f538.png)

**Comment by mobitar** [comment]
Don't think we'd build this out any time soon, unless there is an open-source project that already does this. What app is this screenshot from?

**Comment by lost-carrier** [comment]
Open-source not sure, but Evernote does it. OneNote, too. Screenshot is from Synology NoteStation/DS Note...

**Comment by effieeee** [comment]
Now possible via Markdown Alternative
