### ISSUE TITLE
Snoozing notes

### ISSUE THREAD

**Issue by lilred** [standardnotes/forum#519]
I used Google Inbox to organize my life until it closed a week ago. Since I now have to rethink my workflow, I think this is a good time to transition to privacy-focused tools outside of the Google suite of services.

I'm looking at StandardNotes to replace Inbox reminders. Is it possible to snooze a note until a given time? That was really the killer feature of Inbox.

**Comment by mobitar** [comment]
Hey @lilred, I'd say reminders and notifications and the like are definitely out of scope for us. We're more a safe repository for notes than anything. I think it would be very unlikely that we work on a feature like this any time soon, or at all. (Unless someone figured out a way to do them via extensions, but that sounds unlikely as well, given this kind of feature would need "top-level" access to the app.)
