### ISSUE TITLE
Are there any plans for shared notes?

### ISSUE THREAD

**Issue by wittjosiah** [standardnotes/forum#52]
Are there any plans for shared notes? By a shared note I mean note that multiple people have access to. I realize this is more difficult given the end-to-end encryption of the notes, but I did see that you had done some work on a collaborative editor.

**Comment by mobitar** [comment]
No immediate plans for this. But definitely something we'd wanna do in the future.

**Comment by devzsolt** [comment]
@mobitar are you still considering this? Did you perhaps start developing it since last year? Thanks

**Comment by mobitar** [comment]
No, have probably moved further from this. Please see here: https://standardnotes.org/help/50/can-i-collaborate-with-others-on-a-note
