### ISSUE TITLE
Keep previously selected view or tag after unlocking

### ISSUE THREAD

**Issue by christianhans** [standardnotes/forum#522]
Currently after unlocking the “All notes” view is selected regardless of which view or tag was selected before the application was locked. It would be nice if the application keeps the current view or tag selected even after locking/unlocking.

**Comment by mobitar** [comment]
Note and tag state persistence could indeed be useful.

**Comment by effieeee** [comment]
There is now a preference for this, selecting the last viewed note will also have the app relaunch with the last viewed tag:
![image](https://user-images.githubusercontent.com/54989748/198841076-5ea69de3-d7c8-4556-85b1-f0c877524b3f.png)
