### ISSUE TITLE
x notes optimized?

### ISSUE THREAD

**Issue by chanclr** [standardnotes/forum#523]
Does anyone know what it means when it says "X notes optimized"? I saw it on the bottom bar of Standard Notes for Web.

**Comment by mobitar** [comment]
We talk about this in the [release notes for 3.0.8](https://github.com/standardnotes/web/releases/tag/3.0.8):

- Optimizes note-tag relationships to minimize chance of duplication in sync conflicts. This optimization will run once when you first launch the app, and a status message will display in the footer. Notes and tags created before July 2018 typically had a bi-directional relationship. That is, notes referenced tags, and tags referenced notes. This optimization transfers items with this old structure to the modern structure, where only tags reference notes.
