### ISSUE TITLE
Is there a way to close the side pane? what is the purpose of margin resizes?

### ISSUE THREAD

**Issue by wisdomlight** [standardnotes/forum#527]
1. How cn i close the two side panes
- the one with the heading saying Views
- and the one with the heading  sayinng All Notes

2. in the editor under Options -> margins resizers 
- what is the purpose of this function??

Cheers

**Comment by mobitar** [comment]
You can close the tags and notes pane by hovering over the right side of the respective panel, and either double clicking the vertical bar that appears, or dragging it to the left.

Editor margin resizers server a similar purpose, and allow you to adjust the editor margins. Hover over the left or right of the editor to adjust its margins. This is particularly useful in fullscreen mode.

**Comment by wisdomlight** [comment]
@mobitar 
Thank you
I am still not sure about the usage of the resizers but i guess it is useful for some people in some situations. 
cheers
