### ISSUE TITLE
Missing views "Last Day" and "Untagged"

### ISSUE THREAD

**Issue by hurzhurzhurzhurz-oik** [standardnotes/forum#529]
The SN "Demo" website shows two new views "Last Day" and "Untagged".
This is very useful, but I miss this in all current Versions (Desktop, IOS, Web).
I also enabled all available extensions, just in the case this is created by a extention.
But this views are still missing.

**Comment by mobitar** [comment]
These are custom views that you can create: https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes

**Comment by MustachedMario** [comment]
Ahh I see, it's a part of the folder extension.
(So this also unavailable by mobile apps.)
Thanks for the info.

**Comment by mobitar** [comment]
That article may need updating actually. The way it works is that you can create smart tags only using the Folders extension, but once created, you do not need the Folders extension to view them. And they will appear on both desktop and mobile in the Views section.

**Comment by MustachedMario** [comment]
So, i understand this correctly, this is only a "special named" tag.
So why we can't create this without the folders extension?

**Comment by mobitar** [comment]
It's not a specially named tag—it's an entirely separate construct that just shares some characteristics with tags. Initially only the Folders extension was capable of creating, parsing, and reading "smart tags"/views. But later the apps were updated to allow reading. Creating and parsing them still requires specialized code that only the Folders extension has.
