### ISSUE TITLE
How to add tag to note on Ipad

### ISSUE THREAD

**Issue by 4bob1** [standardnotes/forum#531]
On the Windows desktop program, there is a line for the tag under the note title. But on the Ipad app, there does not appear to be a line. I tried pressing enter at the end of typing in the title but that just exits the enter title mode. 

TIA

Bob

**Comment by SiGamma** [comment]
In the top right corner, there's a "hamburger" button, tap it and there you can select tags to tag the note with, or add a new one by tapping on the blue button in the bottom right.

**Comment by 4bob1** [comment]
Thanks. Do you know of an online manual/tutorial that answers basic user questions like this?

**Comment by mobitar** [comment]
@4bob1 there are some topics here that can help: https://standardnotes.org/help

**Comment by 4bob1** [comment]
Please correct if the following is not correct.

You can also create a tagged note by doing a search for a pre-existing tag. While in the search results page any new note added will have the tag.

**Comment by mobitar** [comment]
Yup, that's correct. When you add a new note when browsing a tag, that tag will be added to the new note.
