### ISSUE TITLE
[Markdown Editors]: Insert 2 spaces when pressing Tab and Cmd+[

### ISSUE THREAD

**Issue by christianhans** [standardnotes/forum#533]
Minimal Markdown editor already inserts 2 spaces when pressing Cmd+[. I would prefer it when all Markdown editors (most importantly Advanced Markdown since that's the one I am using) would insert 2 spaces both when pressing the Tab key and when pressing Cmd+[.

This would be consistent with Mobile where at least on iOS no Tab key is available. I usually insert 2 spaces on mobile instead.

**Comment by mobitar** [comment]
What does the Advanced Markdown Editor do for tabs? Tab characters? I agree that consistency would be nice to have, but these are out of the box behaviors for all these editors, and sometimes, it's not trivial to override this behavior. The only editor where we custom handle the tab character is the Simple Markdown Editor.

**Comment by christianhans** [comment]
Yes, it inserts a Tab character.

Best
Christian

**Comment by effieeee** [comment]
Minimal Markdown is now deprecated, so likely won't be worked on anytime soon: https://github.com/standardnotes/plugins
