### ISSUE TITLE
Not synched update ends up in incomplete data swipe

### ISSUE THREAD

**Issue by holzi-x** [standardnotes/forum#536]
The workflow is a a bit clumsy to describe:
I had SN open on a machine i dont use frequently. The session was timed out, but I just wanted to check something so it didn't bother. After wards I updated the application to 3.0.8 - I think I had 3.0.6 before. After the update the session was of course still out of synch, so I decided to re-login, and clicked to "clear all local data". Bar one note, all notes were purged, but I am a bit unhappy to see, that this one note is still sticking around in the app. After a second "clear all local data", the note is gone.

**Comment by mobitar** [comment]
Hmm..so basically you hit Clear all local data, and after that completed, 1 note still remained? That's strange. How many notes total? My guess is it has something to do with the "Session Expired" alerts you may have kept seeing. Those alerts may have blocked execution of a task for a short amount of time. Another thing that could cause this is if you hit Clear local data while the app is still loading your data. Behavior then can begin to take an undefined shape. A good solution would be to block the clear button until all data has loaded. Do you think the latter theory is what may have happened?

**Comment by hillbilly3456avk** [comment]
I think it was due to the Session expired alerts. The data was completely loaded, I am pretty sure about that. But I had a ton of these Session Expired MsgBoxes that I clicked away.
It was just the one note remaining - the one that had the focus at the time

**Comment by mobitar** [comment]
Got it, thanks. I'll have to spin up a test environment to see if I can replicate this.
