### ISSUE TITLE
"Sort By" feature is in the wrong order

### ISSUE THREAD

**Issue by Milenavel** [standardnotes/forum#538]
A few months ago my standard notes switched the order for sorting - instead of showing the most recently updated/added at the top, it shows the oldest notes first. I can't figure out how to switch it back, changing the "Sort By" option doesn't make any difference. Any ideas?

**Comment by bryvin** [comment]
You can reverse the sort order but using the little reverse arrow (as shown below) that is in the menu that you select the "Sort By" method. 

![Screenshot from 2019-05-01 14-57-47](https://user-images.githubusercontent.com/5969300/57036243-b4875780-6c21-11e9-8c70-a16dbad1c145.png)

**Comment by Milenavel** [comment]
ohhhhhh.... for some reason I never saw that button. thanks!
