### ISSUE TITLE
iOS Notes show HTML Code

### ISSUE THREAD

**Issue by linuxrx01** [standardnotes/forum#539]
If i want change my notes it shows me HTML Code.

**Comment by mobitar** [comment]
Hey there, notes created with the Plus editor will use HTML as the underlying format, so you'll need to always use the Plus editor with those notes. If you switch to the plain editor, you will see raw HTML. If you want rich text without HTML, I recommend using any of the Markdown editors, which is more plaintext compatible.

**Comment by linuxrx01** [comment]
Thank you! Is it possible to set one editor global? I have 300 Notes and i dont want to change every single one.

**Comment by mobitar** [comment]
Yup, on mobile, press and hold on an editor in the list, and a menu should appear with the option to set the editor as default. On desktop/web, first select the editor from the list, then open the list again, and you'll see an option to set it as default next to its name.

**Comment by linuxrx01** [comment]
Thank you for the answer. Maybe you could make the setting easier to find?
