### ISSUE TITLE
[Feature Request] Better handling when pasting URLs

### ISSUE THREAD

**Issue by simonhurtz** [standardnotes/forum#542]
First of all, one quick remark: thanks so much for your work, @mobitar! I've been testing and switching note taking apps for years – until I finally discovered Standardnotes some weeks ago. Loving it so far!

But there's always room to improve: Most of the time, I use the Advanced Markdown Editor, and I need to create a lot of links within my notes. My workflow looks usually like this: I copy the URL of a certain tab in my browser, switch to SN and mark the text that should link to the website. Then, I press Ctrl+k in order to create a link.

The shortcut creates the markdown syntax perfectly fine – but the handling of the cursor doesn't make sense to me. Instead of leaving the focus on the text, it would be better if the https:// part could get marked. Like this:
Currently: [**text**] (https://)
Preferred: [text] (**https://**)

When using Ctrl+k after selecting text, you normally don't want to change the text again but paste the URL from your clipboard or type it manually. Either way, it would be better if the cursor could be placed within the () instead of the [].

Maybe that's not possible due to technical limitations of the Advanced Markdown Editor. If so, could you give us an opportunity to deactivate the automatic insertion of https:// within the brackets? Then, I could just move the cursor with the arrow key and paste the link from the clipboard instead of deleting the prefilled text before.

(I know that it sounds like a trifle, but I really paste a lot of links. A little change could greatly improve my workflow.)

**Comment by mobitar** [comment]
Hey @simonhurtz, thanks for the feedback. Glad to hear you're enjoying the app! I'll say generally that we have little control over the internals of most editors, given they're based on open-source components. The Advanced Markdown Editor is based on https://github.com/Ionaru/easy-markdown-editor, which luckily, is being maintained. But as for overriding specifics in the editor, we typically don't go that deep into the code, because it causes us to branch off from the parent project, and makes pulling in updates more difficult over time. It may be worth opening the issue in that repository if you think the behavior is generalized enough to warrant a global update, or a preference. But agreed, these small things can definitely add up in your workflow when you're trying to do things quickly.

**Comment by simonhurtz** [comment]
Thanks for your quick response! I'll open an issue in the repository of the Advanced Markdown Editor. That's a good idea.

**Comment by simonhurtz** [comment]
Unfortunately, it seems as they won't change the behavior. At least, I didn't receive any reply [to my request](https://github.com/Ionaru/easy-markdown-editor/issues/85). They probably just have more important things to work on.

But for me, this is a total killer. I write [my newsletter](http://socialmediawatchblog.de) with Standard Notes before converting it into HTML (btw: it would be great if SN could convert or export Markdown to HTML) and pasting the code into Mailchimp – and I really use a lot of links. The behavior of the button and the shortcut just doesn't make sense to me.

Is there any way to change it in SN's Advanced Markdown Editor without completely messing up with future updates of the Easy Markdown Editor?

**Comment by mobitar** [comment]
I'll admit it's a really niche issue and why it's hard to prioritize. I have the same use case as you, in terms of writing newsletters, and I've done it with the Plus Editor in the past. I would now use the Bold Editor. You can toggle the HTML view to get the raw HTML once you're ready to transfer it.

Also the LaTeX/Math Editor is a Markdown editor that has an option to view your input as HTML. See if any of those solutions can be a good workaround for now.

**Comment by simonhurtz** [comment]
I totally understand that you don't have the resources to resolve such a minor issue. For my newsletters, I'll probably look for another Markdown Editor like QOwnNotes or Writemonkey (but I'll stick with SN for all the other notes, of course).

I've tried both the Bold and the Math Editor. None of them really works for me. The downside of the Plus editor is its lacking of any support for Markdown. Plus, the raw HTML often gets a bit messy if you use a lot of different formats (e.g. toggle the bold tag on and off repeatedly). The Math Editor doesn't support shortcuts and is hardly usable on my mobile devices because you can't disable the preview panel (admittedly, the Advanced Markdown Editor doesn't really work either).

In the long term, it would be great if we could get a first party, fully mobile compatible Markdown Editor with support for shortcuts and an option to export/convert to HTML. But as I said: It's probably a niche issue, and it's perfectly fine if you prioritize other things. Thanks for your work!

**Comment by mobitar** [comment]
Fair enough, I'll keep this in mind!
