### ISSUE TITLE
Issues with pinned tab in Firefox

### ISSUE THREAD

**Issue by louno** [standardnotes/forum#546]
Hi all,

While pinned tab were perfectly working with Google Chrome, every morning Firefox display an error and all my notes will be blank until I refresh standardnotes tab. Do you have any idea why ? Am I the only one to face this issue (Extensions related issue maybe ?)

Thanks for your help,

![2019-05-07 08_01_39-Notes — Standard Notes _ https___app standardnotes org_](https://user-images.githubusercontent.com/50353735/57275888-191e3880-70a0-11e9-9419-4e7c0e476ea1.png)

**Comment by mobitar** [comment]
Strangely enough someone just mentioned this 2 days ago: https://github.com/standardnotes/web/issues/240#issuecomment-489457745

I personally haven't been able to replicate it though. It seems like some kind of elapsed time is required. Can you try to describe your replication steps?

**Comment by johnny243** [comment]
This issue is fixed with [#356](https://github.com/standardnotes/web/pull/356).
