### ISSUE TITLE
[Feature Request] Vim mode for all editors

### ISSUE THREAD

**Issue by sensen** [standardnotes/forum#548]
Vim Editor is awesome!

Is there a possibility to "integrate" all functionalities in Vim Editor to other editors (except Plus and Spreadsheets, probably)? 

For my case, I'd like to be able to preview notes written in Markdown format while using Vim Editor.

**Comment by mobitar** [comment]
Hey @sensen, I don't think this would be possible. It might be for any Code Mirror based editor like the Code Editor, but not amongst general editors. It's a niche feature for sure, so would rather keep it confined. The Vim Editor does have Markdown mode though. No preview feature however, besides the inline previews it renders.

**Comment by sensen** [comment]
Thanks @mobitar!
