### ISSUE TITLE
No password created during subscription

### ISSUE THREAD

**Issue by markwalkom** [standardnotes/forum#55]
First up, great app and I'm already recommending it to others!

My question is around the account side of things. I subscribed without any problems but I was never asked for a password. When I want to login to the dashboard it sends me a link which works fine.

However I can't add my login details to either the macOS app or the Android app to sync things as during the payment process it never asked me for a password. I also cannot reset my password, which I understand as a design decision, which is fine.

How can I go from where I am now to having an account with a password?

**Comment by mobitar** [comment]
Hey @markwalkom, thanks for recommending SN :) There are two different accounts:

Your notes account, and your Extended account. These two are separate. Your Extended account doesn't use a password and uses email instead. Your notes account uses a password.

You probably just signed up for an Extended account. To register for an encrypted notes account, use any of the SN apps (or the web app at app.standardnotes.org) and just register.

Hopefully that should clear things up.

**Comment by markwalkom** [comment]
Awesome, thank you :D
