### ISSUE TITLE
Local / Offline Storage of Files

### ISSUE THREAD

**Issue by profimler** [standardnotes/forum#550]
Is it possible to locally store and access files?

I'd love to also use Standard Notes to organize notes and files and notes about files, but the FileSafe addon makes me download the file each and every time I want to open it.  This makes things difficult when I'm working there the wifi is slow or not present.  It also adds to the time for each and every use of a file.

**Comment by mobitar** [comment]
Cross-platform availability is a huge part of the Standard Notes philosophy, so local files is likely out of question. The web and mobile apps would be unable to access any local files, were we to move in that direction. But a good solution might be setting up a local WebDAV server and integrating that with FileSafe. Might be a good idea for us to do a write up on that one day.

FileSafe will get embedded attachments soon, so you won't have to download to view them.

**Comment by jayb-g** [comment]
Should be reopened since filesafe is deprecated ?
