### ISSUE TITLE
Later note revision intermittently overwritten by earlier revision

### ISSUE THREAD

**Issue by evanchaney** [standardnotes/forum#554]
## Summary

When interleaving edits to a note from two devices, one online and one offline, the latest revision is intermittently overwritten by an earlier revision.

The issue occurs about 2 in 3 times.

## Steps to reproduce

Given 2 devices (A and B) which both begin with an active network connection:

1. From device A create a new note. Fill in the body of the note with “- Item one”.
2. From device B refresh the list of notes. Confirm the new note appears and reads “- Item one”.
3. Disconnect device B from the network so it cannot contact Standard Notes’ sync service.
4. From device B add to the note body “- Item two” so the note reads:

- Item one
- Item two

5. With device B still offline return to device A and prepend “- Item three” to the note so it reads:

- Item three
- Item one

6. Reconnect device B to the network and wait for it to sync with Standard Notes’ sync service.
7. Wait for device A to sync with Standard Notes’ sync service.

## Expected behavior

When device B reconnects to the network it saves its copy of the note as a duplicate leaving conflict resolution up to the user. (https://standardnotes.org/help/33/how-do-i-clear-duplicates)

Alternatively, when device B reconnects it merges the changes together to produce one revised note reading:

- Item three
- Item one
- Item two

## Actual behavior

The last edit to the note (addition of “- Item three”) is overwritten by device B’s copy of the note which is an earlier revision. The final note reads:

- Item one
- Item two

“- Item three” is lost.

## Environment

- Device A: Standard Notes 3.0.9 for macOS
- Device B: Standard Notes 3.0.7 for iOS

**Comment by mobitar** [comment]
Hey @evanchaney, thanks for the detailed report. The main thing to note is that the server has a constant called `min_conflict_interval`, which is set to 20 seconds. If two conflicting changes are made within 20s of one another, we process the change as a regular save, and don't create a conflict.

That means if you reconnected your offline device and made a change within 20 seconds of your other device change, it wouldn't create a conflict. If you try your example again but wait ~30 seconds before step 6, you should see a conflict.

However, I was actually experimenting with lowering this threshold just yesterday, to about 7 seconds. The threshold itself is likely legacy behavior from when the server used to be in charge of duplicating items (the client does it now), so the goal would be to remove it altogether at some point. But it just needs to be done carefully.
