### ISSUE TITLE
Can't copy&paste blog / private links

### ISSUE THREAD

**Issue by clayt0nk** [standardnotes/forum#555]
This is may be a bit of a nit since I am probably the only QubesOS (virtualized desktop) user here, but by design I don't HAVE a web browser in the Linux virtual machine where standard notes is running. So after turning on the "listed" extension, if I hit "open blog" under the "actions" menu, nothing happens. (Ditto private links.) I need to be able to copy those links to the clipboard, and I don't see any way in the standard notes UI to do that.

**Comment by mobitar** [comment]
Hmm..that's a tricky one. And I don't think there's a solution for a "Copy Link" action with the way Actions are implemented. The only solution I can think of is to click Help > Toggle Error Console. Open the Network tab. Then, when you open the Actions menu, a network request will be made to retrieve available actions for your Listed account. Do a search within the response tab for "Open Private Link" or "Open Published Link", and see the corresponding link value.

**Comment by TheodoreChu** [comment]
The private links to your posts are accessible from the Settings page, so one option is to open that page to retrieve the private links every time you publish a new private post. The Settings page has its own secret URL, so you could keep it in your passwords manager / secrets vault.
