### ISSUE TITLE
Can't logout of app and delete notes for good on Android

### ISSUE THREAD

**Issue by raev33** [standardnotes/forum#556]
As the title says does my notes reappear, although they should have been deleted.
I did the following on two different android devices and used F-droid for install and uninstall:

1. Deleted a account with the reset tool.
1. Signed out of the app.
2. Uninstalled the app.
3. Reinstalled the app.
4. Opened the app.

Now I thought that I would be met with a clean install. Instead the app asks for my password, and following all my notes are intact, as if nothing had happened. Only difference is that the app naturally can't sync to the (deleted) account anymore.
The app behaves as intended, if I uninstall and install from the Play Store.

So I suspect that somewhere some files are left behind if you use F-droid.

**Comment by mobitar** [comment]
Very strange. Definitely an F-Droid issue. I was able to replicate via F-Droid, but not via Google Play. I posted [a comment](https://gitlab.com/fdroid/rfp/issues/379#note_172823762) on their repo to see if they have any ideas. There may be some sort of uninstall hook that's not being run.

**Comment by raev33** [comment]
First I installed the app from Play Store, later from F-droid. So your probably right, that this causes some sort of issue.

**Comment by mobitar** [comment]
Update on this: it's caused by the "Automatic restore" feature of Android system-wide backups. Settings > System > Backup > App data.

Detailed writeup here: https://github.com/standardnotes/bounties/issues/30#issuecomment-503770678

We'll have to determine if there's a nuanced solution to this.
