### ISSUE TITLE
File Attachments, FileSafe and Mobile

### ISSUE THREAD

**Issue by rjnole** [standardnotes/forum#560]
I've had an offline conversation with @mobitar, and I think some of the things I learned during that conversation will be helpful to other users. Specifically:

- FileSafe and file attachments **are** supported on mobile devices, with the caveat that you aren't currently able to download those file attachments through the app on mobile devices.
- The Bold Editor supports inline file attachments, i.e. file attachments such as images that are directly inline with your notes. Inline file attachments aren't supported by other editors. *These inline file attachments work perfectly on mobile devices*.
- Mo and the team are gathering feedback on the file attachments feature and are determining next steps, including possibly adding inline file attachment capabilities to other editors.

As has been stated elsewhere, Mo has been fantastic in answering my questions and addressing my concerns. I had even asked for a refund (which was quickly granted) before I understood the above, and my misunderstanding is a big part of the reason why I decided to share this information. Now that I know the above, I've re-subscribed to Extended and will be giving everything a much longer look.

Happy to answer any questions that anyone has (if I can!) regarding these capabilities.

-Ryan

**Comment by mobitar** [comment]
@rjnole Yup, you got it! The Bold Editor release marks a milestone in encrypted embedded attachments for us, and works nicely on all platforms, including mobile. On mobile, using the Bold Editor, you can upload photos and files from your library, but you can't save previously uploaded FileSafe files to your mobile library (you can however insert them into the current editor so you can preview their contents, for example for photos and videos).

**Comment by TheSielo** [comment]
So the bold editor allows to add an inline attachment (image, video, audio, etc.) without using FileSafe and avoiding the need to download the images everytime? How do you do that? Is that functionality still present? I can't find any way to add an image other than with FileSafe.. Any help would be much appreciated.
