### ISSUE TITLE
Login bruteforce, no captcha ?

### ISSUE THREAD

**Issue by 42aroger** [standardnotes/forum#561]
Hello, 

I noticed there is no captcha at login, there is a checkbox for "strict login" but the explications link is broken

https://standardnotes.org/help/security

So is there any protection against bruteforce ?

**Comment by mobitar** [comment]
Thanks for the heads up about the broken link, this has been fixed now. With regards to bruteforce protection, there is currently rate limiting in place, and this week, we'll be releasing exponential backoff as well, which locks the account exponentially after each failed attempt, up to 1 hour.

**Comment by 42aroger** [comment]
Great this sound promising, I will follow the ruby-server project
