### ISSUE TITLE
Feature Request: Move all Archived notes to Trash

### ISSUE THREAD

**Issue by issmirnov** [standardnotes/forum#566]
Standard Notes has an "Empty Trash" option available through the Options menu of a note in the trash.

Would it be possible to add a "Trash All Archived" option in a similar manner to notes in the archive?

My general note lifecycle is:
1. Write notes
2. Archive them
3. Move to trash when I know I won't need it
4. Empty trash to keep syncs small

This would be very helpful when clearing a few hundred notes from the archive to the trash. 

I defer to @mobitar to enforce the ethos of a lean app - I trust you to balance requests of users vs app bloat.

Thanks so much!

**Comment by effieeee** [comment]
Multi select now available!
