### ISSUE TITLE
Add markdown link to local file or directory

### ISSUE THREAD

**Issue by msmart** [standardnotes/forum#568]
I would like to add a link to a local file or directory in markdown.

When clicking on the rendered version of this (on version 2.3.4/Ubuntu)

`[abc](file:///home/test/file.pdf)`

a new empty Standard Notes window is opened:
![grafik](https://user-images.githubusercontent.com/85249/44407391-494b9880-a55e-11e8-98fb-db06aa3037b9.png)

I suspect this use case is not yet supported by Standard Notes and no correct handler for outgoing links has been defined. However, it might be a nice feature to have.

**Comment by jed84** [comment]
The issue is still valid.
I am unable to link a folder/file on Win10.

I just joined Standard Notes and I am afraid this bug is an ultimate killer.
Any fix?

![ScreenClip](https://user-images.githubusercontent.com/47121522/60627680-c08cc280-9de6-11e9-9a28-9729e57c02ce.png)

**Comment by mobitar** [comment]
The white screen issue must be new. I'll have to investigate this. Don't think there's an immediate resolution for you @jed84.

**Comment by ncharchut** [comment]
Surprisingly, I'm having the same issue with the following setup:
- macOS Mojave 10.14.6
- Advanced Markdown editor.

Have you found any causes/fixes? I also get a white window but it automatically asks me if I'd like to save the file as if I were downloading it.

**Comment by mobitar** [comment]
File links were disabled in a previous update due to security reasons. We're still needing to investigate a good workaround.
