### ISSUE TITLE
Login issue on web client on self-hosted instance

### ISSUE THREAD

**Issue by padenot** [standardnotes/forum#57]
A couple days back, I started having trouble to log in from the web client to my self-hosted instance of the `ruby-server` (that is running the current git tip):

> The protocol version associated with your account is outdated and no longer supported by this 
> application. Please visit standardnotes.org/help/security-update for more information.

This link goes to the home page, so I can't actually have more information, and I don't know how to fix this.

Curiously, the Android client still works fine (maybe it's because I haven't been disconnected there?).

**Comment by mobitar** [comment]
Sorry about that. Please do the following on your self-hosted instance:

```
git pull
rails db:migrate
bundle install
```

Then restart your server.

**Comment by padenot** [comment]
Everything works fine now, thank you very much!
