### ISSUE TITLE
[Feature request] don't update modification time after setting options/flags

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#570]
Currently it seems that the modification time for the note gets updated whenever any of the flags are set (Pin, Archive, Lock, Protect). If the actual content the note is not changed then really the timestamp shouldn't change. As a specific example, "Lock"ing a note would mean conceptually "freeze this note the way it is" - so the timestamp should reflect the last time the note was edited, not when it was locked.

**Comment by mobitar** [comment]
Yup, this will actually be the behavior from 3.0.10 onward. 3.0.10 is currently [in beta](https://github.com/standardnotes/desktop/releases).

**Comment by chanclr** [comment]
It seems this is happening again with 3.5.11
