### ISSUE TITLE
Unclear connection instructions for self-hosting with Heroku.

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#571]
https://docs.standardnotes.org/self-hosting/self-hosting-with-heroku
Hello, I'm a beginner user. I've followed this entire tutorial and I saw no errors. But the article did not provide clear instructions on how to connect to the server with the web app after setting up the server. I tried copy and pasting the jawsdb connection string into the web app's sign in screen. Nothing happened. I'm at a loss of what to do.

**Comment by mobitar** [comment]
So once you have the server set up and on an endpoint, you would click Advanced Options under the Account panel before you sign in. There you specify the endpoint of your server.

And sorry, you're right, the Heroku doc doesn't give usage instructions. We talk about it at the very end of the other posts though: https://docs.standardnotes.org/self-hosting/self-hosting-with-ec2-and-nginx
