### ISSUE TITLE
[Feature Request]: Calendar

### ISSUE THREAD

**Issue by someguynamedmatt** [standardnotes/forum#572]
It would be a really nice feature if there was a calendar tab (? unsure of how it would be displayed in the UI) that had an indicator for days that a note was written. 

This could be used (in one way) to keep track of tasks or to use as a daily journal so to speak. Selecting a day would show notes written on that day.

**Comment by mobitar** [comment]
Unlikely we'd build this, unless it were an extension, but you can do something similar with Smart Tags: https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/292
