### ISSUE TITLE
Can't activate extensions. "Cannot read property 'concat' of undefined".

### ISSUE THREAD

**Issue by yansern** [standardnotes/forum#574]
When the "Activate Extension" popup shows up, clicking "Continue" doesn't do anything.
Opening up the Console shows that everytime I click on "Continue", the error logged was "Cannot read property 'concat' of undefined.'.
![2019-06-05_15-59-07](https://user-images.githubusercontent.com/1287077/58962329-3b909800-87ab-11e9-8d8b-f76556d9e062.png)

**Comment by mobitar** [comment]
Sorry about that. This one is actually fixed in the upcoming desktop release 3.0.10, which is currently in [beta](https://github.com/standardnotes/desktop/releases). The release is slated for sometime today or tomorrow.
