### ISSUE TITLE
Tagging plaintext import files

### ISSUE THREAD

**Issue by chrisglawley** [standardnotes/forum#575]
I would like to import my 500 text files into SN such that they all get tagged with a given tag.
That is to say every imported file gets the same tag.
This would allow me to easily segregate the imports from my existing SN notes.

I suspect this is not actually possible and, given it isn't a thing a person is likely to do more than once, is probably not worth a feature request.

Looking at a backup file it appears that a note doesn't contain a tag. Rather a tag is a special 'note' that has a list of associated notes which doesn't make this request easy.

It does suggest to me a simple(?) way for a note to have a link to another note, a bit like a wiki

chris :-)

**Comment by mobitar** [comment]
Hey Chris, this isn't currently possible, but it is something that has been requested before, and something that I think would be worth implementing, perhaps in the conversion tool itself. I can't say exactly when we'd get to this, but it's definitely on the radar.

**Comment by chrisglawley** [comment]
Definitely in the conversion tool - it's a one time thing which also raises the "is it worth doing" question.
Painful though it is, I've now tagged al my imports and that's it.

Possibly, to keep things simple, add a default "import" tag to the imported files so the resulting notes are easy to collect in one place. Then after they are assigned their correct tags the user deletes the "import" tag and life is hunky dory.

Any way; I'm a happy bunny and this thread can be considered closed
chris :-)

**Comment by mobitar** [comment]
That's actually what we do with the Evernote converter—we put all the notes in an "evernote" tag. We just need to do the same with the other converters. Glad you got your notes sorted!

**Comment by mvance** [comment]
I'm considering converting from Simplenote as well (I've noticed data getting lost, so I need to find another platform). I tried exporting my 1,400+ notes and importing them into Standard Notes; however, all of my tags from Simplenote seem to be lost. I noticed that all the imported notes did get tagged with a date stamp tag ("6-4-2020-import") but none of the tags from Simplenote itself got pulled over.

Do any of the other supported formats (Evernote, Apple Notes, or Google Keep) support tag importing? It would be kludgy, but I'm wondering if I might be able to export to one of those platforms as an intermediate step, to get the tags in.

Or are there any other suggestions?

Thanks!

**Comment by JaspalSuri** [comment]
You could try using this [unofficial importer](https://github.com/edas/simplenote2standardnote). Please let us know if it works for you!

**Comment by mvance** [comment]
@JaspalSuri Thanks for the tip.

That said, I just tried running the script and I get an [error reported previously by another user here](https://github.com/edas/simplenote2standardnote/issues/1). Any ideas?

Thanks again!

**Comment by johnny243** [comment]
Hi @mvance!

Please see my reply on [this issue](https://github.com/edas/simplenote2standardnote/issues/1#issuecomment-640918604), and let me know if that helps.

Thanks!
