### ISSUE TITLE
HOW do you log in? 

### ISSUE THREAD

**Issue by ExpandingFoam** [standardnotes/forum#576]
Hello, 

I just found out about this project/service, and it seems to come highly recommended. My problem is that using the [web interface](https://app.standardnotes.org/) I **cannot** figure out how to log in! I feel stupid even asking this, but, well, I have to. Here is what I can see:

![Screenshot 2019-06-05 at 10 20 08 PM](https://user-images.githubusercontent.com/51429315/59002625-0d2daf80-87e1-11e9-9b64-0d7bd274ab75.png)

I can create a passcode but there is nowhere for a username to go. I guess the passcode stays in the browser? None of the words like "account" "register" or "sign in" are links. I was able to create an account in the mobile app... but how do I log in on this device?

It almost looks like there should be something in the blank space under "to-end encryption". I tried using "incognito" to check an extension wasn't blocking something but everything looks the same. 

Please someone help me figure out what I'm missing. 

Chrome 76.0.3807.0 (Official Build) on ChromeOS.

**Comment by mobitar** [comment]
Hey @ExpandingFoam, so sorry, not sure how I missed your post. There seems to be a unique issue with Chromebooks and ChromeOS that causes the sign in buttons to render without height. I've yet to manage to get a dedicated environment set up to test this. However I'll try to elevate priority on this as this is the second report I hear regarding this issue.

**Comment by ExpandingFoam** [comment]
Thank you for validating my experience ;)
Thought I'd let you know this seems to have been resolved. 

(I am new to this but I think I will put the rest of my reply in the thread you link above. Is that correct? Or harder to follow?)
