### ISSUE TITLE
Simple Markdown Editor : monospace font gone ?

### ISSUE THREAD

**Issue by DavBE** [standardnotes/forum#577]
Hello,

Running version 3.0.9, the font in edit mode is no longer a monospace font in the Simple Markdown Editor.

Is this by design ?

Regards,

David

**Comment by mobitar** [comment]
I don't believe it was ever a monospace font with the Simple Markdown Editor. Only the plain editor supports that as a native option.

**Comment by DavBE** [comment]
It definitely was as I have just noticed the alignments of the titles in my notes are skewed.

See https://i.imgur.com/68LH780.png (a note i took 2 months ago)

**Comment by mobitar** [comment]
I'm not sure I understand—the font in that screenshot looks like a regular, non-monospace font? Although, looking at the code, there has been a change in the font from `sans-serif` to `-apple-system, BlinkMacSystemFont,
    "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans",
    "Droid Sans", "Helvetica Neue", sans-serif;`

This means it will use any fonts that appear in that list if your system has them, otherwise falls back to default sans-serif. So it's possible the editor used another font previously, but it definitely couldn't have been monospace.

**Comment by DavBE** [comment]
> the font in that screenshot looks like a regular, non-monospace font? 

That's right. That is now.

It used to be like that :

https://i.imgur.com/1ukqHNd.png

So is there any way to force a font ?

**Comment by mobitar** [comment]
Hmm..this just isn't reflected in the code history. So if it was monospace for you, that was unintentional. Only the Plain Editor supports monospace (in addition to the Plus Editor and Bold Editor via the font selection menu). In any case, my hope is to make this easier to customize with a custom theme builder in the future.

**Comment by DavBE** [comment]
In the plain editor options, there's a an option for enabling a monospace font (on/off). Could this be added to the simple markdown editor ?

**Comment by mobitar** [comment]
This option is only for the plain editor, which is native and has access to your user preferences. The external editors however do not have access to these preferences so cannot read these values.

I definitely want to solve this problem in general, but will not be sure what form the solution will take on until I really get in there.

**Comment by DavBE** [comment]
Ok thank you. I'll use the plain editor in the meantime and switch back to the simple markdown editor for preview.
