### ISSUE TITLE
Text selection in android note standard

### ISSUE THREAD

**Issue by pswartout** [standardnotes/forum#579]
I've noticed that selecting text within android client is a hybrid experience compared to all other apps (the selection 'start' and 'end' indicators are like bold teardrop shape. This makes it somewhat difficult to select text.

What would it take to ensure standard notes android app used standard android text selection mechanism?

**Comment by mobitar** [comment]
You're most likely using one of the Extended editors, which are hybrid in nature (they are presented in webviews). The plain editor is native. As for what can be done to resolve this, I'm not sure there is much we can do, given we don't control this behavior on the webview level in general. But it's something I'm keeping an eye out for.
