### ISSUE TITLE
[Feature Request]: Auto login

### ISSUE THREAD

**Issue by zdugi** [standardnotes/forum#580]
It will be really nice if there is an option for enabling auto-login (auto-unlock) on program startup.

**Comment by mobitar** [comment]
What do you mean by auto unlock?

**Comment by zdugi** [comment]
Sorry for lack of details. I put passcode lock because I want to protect some of my notes and that's brilliant, but each time when I open the application, window popups requiring to enter my passcode again to unlock app. I think it will be nice to put some checkbox or something, to skip that extra prompt.

**Comment by mobitar** [comment]
Hmm still not sure what you mean. For the passcode, you can control when you are asked for it in the Account Menu:

<img width="368" alt="Screen Shot 2019-06-10 at 9 07 10 AM" src="https://user-images.githubusercontent.com/3277844/59201042-275bea80-8b5f-11e9-8c47-4f1bf84596e7.png">

If you're talking about the window for accessing a Protected action, then you can also set that to remember for up to a week:

<img width="720" alt="Screen Shot 2019-06-10 at 9 08 20 AM" src="https://user-images.githubusercontent.com/3277844/59201118-4e1a2100-8b5f-11e9-9005-da944dea6abc.png">

**Comment by zdugi** [comment]
I'm talking about this one, that appears on application startup:
![Capture1](https://user-images.githubusercontent.com/6282450/59201445-bd613680-8b9a-11e9-9872-bd879063b389.PNG)

**Comment by mobitar** [comment]
You want an option that says "Remember me"? For how long? You can already do up to 1 hour from the Passcode options.

**Comment by cyb3rz3us** [comment]
Along the "Remember me" idea, it would be great to add a field for a user-specified duration so the user can enter a value other than the pre-set quantities such as 18m or 25m.

**Comment by JaspalSuri** [comment]
Thanks for the feedback; we've had similar suggestions made to us. I'll keep note of this for when the team works on the 4.0 update!
