### ISSUE TITLE
Action extension for desktop scroll position?

### ISSUE THREAD

**Issue by trevormeier** [standardnotes/forum#581]
It would be nice to have an extension that would configure the desktop viewer to have the currently-typing line be somewhere more in the middle of the screen, instead of at the very bottom. Especially when in full-screen, it's ergonomically pretty hard on my neck to always be looking down at the very bottom of the screen.

**Comment by mobitar** [comment]
I don't think we'd build this ourselves. You can always create a bunch of empty newlines at the bottom of the note so that where you're typing ends up being vertically centered.

**Comment by superfreeman1989** [comment]
> I don't think we'd build this ourselves. You can always create a bunch of empty newlines at the bottom of the note so that where you're typing ends up being vertically centered.

Any chance for ability to retain scroll/typing position for individual entries?

**Comment by mobitar** [comment]
Definitely something worth considering.
