### ISSUE TITLE
Backup file format (import from custom CSV)

### ISSUE THREAD

**Issue by nikolaykhodov** [standardnotes/forum#584]
Hi @mobitar,

I need to import some big pile of notes from the single CSV file. I think to build a custom convert script.

Any chance to see some official documentation on the standardnotes backup format or a piece of real code?

Thanks

**Comment by mobitar** [comment]
Hey @nikolaykhodov, there's some info about the backup format here: https://standardfile.org/#import-export

But the best way would probably be just to create some dummy data in the app, then download a backup file and study its format. It's pretty simple JSON. Also take a look at our [sntools repo](https://github.com/standardnotes/sntools), which features converters from various formats like Evernote, Keep, and plaintext.
