### ISSUE TITLE
Issue loading extensions

### ISSUE THREAD

**Issue by braladin** [standardnotes/forum#586]
Hi, on a windows PC if I start SN without first authenticating to the network proxy, all extensions stop working and I get the message "There was an issue loading ...". Restarting SN after authentication doesn't help despite account being able to sync. The only way to get the extensions working again is to re-install them.

**Comment by mobitar** [comment]
The main thing to check is Help > Open Data Directory > Extensions. You want to make sure this directory has folders, and not just zips. If just zips, it means there's a permission error with extracting. What do you see?

**Comment by braladin** [comment]
I see just zips with 0KB in size.

**Comment by mobitar** [comment]
This sounds like a permissions issue. I would try uninstalling the extensions and re-installing, and see if that helps. If not, try extracting the zips manually and see if the system lets you.

**Comment by braladin** [comment]
Uninstalling and reinstalling extensions makes them work again but the issue comes back often. Whenever I install an extension, SN creates an empty zips so there is nothing to extract. If it was a permissions issue, wouldn't it be impossible for SN to create zips at the first place?

**Comment by mobitar** [comment]
Hmm strange. I have seen other people who have this issue, and the zips are created, but they can't extract them due to a permissions issue. What's your OS version btw? And are you in an enterprise or personal environment?

**Comment by braladin** [comment]
Windows 10, enterprise environment behind a proxy. Once re-installed and working, the extensions keep working after restarting SN and even after signing out then in. The problem only occurs when I start SN and the proxy session runs out for inactivity (~10min). The message "Your session has expired. New changes will not be pulled in. Please sign out and sign back in to refresh your session." is displayed then all extensions stop working and only reinstall fixes them.

**Comment by mobitar** [comment]
I'll have to figure out how to replicate this environment. You may have better luck in the meantime using the web app, if you're able to access that without restriction.
