### ISSUE TITLE
Evernote import formatting issue

### ISSUE THREAD

**Issue by harrywind** [standardnotes/forum#587]
I converted the Evernote .enex file to the evernote-to-sn.txt file and imported it via web-import in Standard Notes.
I noticed that in all notes line breaks are missing. Sentences are simply connected and this makes notes unreadable, especially if a bulletted list suddenly becomes a long list of words/sentences without the list structure.

Anybody has that problem as well?
I use Windows Evernote to export the .enex and use the website to import.

**Comment by mobitar** [comment]
Did you have `Remove formatting` checked or unchecked? And which editor did you load the notes with, Plain or Plus?

**Comment by harrywind** [comment]
Thanks @mobitar .

I did have the checkbox Remove formatting checked. If I don't then there is all the HTML code in there.
I want it to be plain text (or have Markdown formatting). 
Removing the formatting is perfect in every way, except that many enters/linebreaks are removed.
Is there a way I can fix it?

**Comment by mobitar** [comment]
If you can share with me a sample .enex file that contains your formatting, I could try replicating this. From what I know it should convert html newlines into plaintext newlines. But if you want to keep the HTML, you can use the Bold Editor or Plus Editor.

**Comment by orelogo** [comment]
@mobitar, I have the exact same issue. Here is a video of me describing it: https://youtu.be/-E7aIjGqcW0

Here is my evernote enex file: https://pastebin.com/y6pFanHn
Here is the standard note conversion file: https://pastebin.com/jL0vQQtP

**Comment by JaspalSuri** [comment]
Hi @orelogo, sorry to hear that; we'd like to resolve any issues surrounding the export conversion tools where possible. Thank you so much for providing a video and for those pastes. I'll take note of the issue with Firefox as well. 

Unfortunately in the video, the screen recorder is focused only on Chrome, so the exports aren't displayed. While I think we should be able to determine the problems from the exported texts, another video would be greatly appreciated just so that we don't accidentally overlook anything. 🙂

**Comment by orelogo** [comment]
@JaspalSuri, sorry about that. I should've checked the full video. I won't be able to re-record the video, but here is what note looks like in Evernote.
![image](https://user-images.githubusercontent.com/15976578/115338391-98a35600-a157-11eb-8fe0-e4f87a1d6a8e.png)

**Comment by JaspalSuri** [comment]
Hi @orelogo, thank you so much for that screenshot! I'll include it in my report.

**Comment by effieeee** [comment]
Fix mentioned here: https://github.com/standardnotes/sntools/pull/27#issuecomment-823790602
