### ISSUE TITLE
Feature request: Tag Suggestion

### ISSUE THREAD

**Issue by HansCronau** [standardnotes/forum#589]
Typing the name of a tag I often find myself wondering: "Is this how I spelled it?" "Did I use capitals or not?" etc.
In fear of unintentionally creating a new tag I then have to check the existing ones.
I think this could ve solved by suggesting existing tags while typing, much like the suggestions one gets while typing the name of a contact in many modern mail clients.

**Comment by mobitar** [comment]
The Quick Tags extension does this.

**Comment by HansCronau** [comment]
@mobitar Thanks! I overlooked that.
I'm subscribed to Extended so for me this is solved now. For others I wonder if it's something that maybe should be available in the standard version. I guess one could argue that it fixes the UX of an existing feature.
