### ISSUE TITLE
Desktop and iOS encrypted number bug

### ISSUE THREAD

**Issue by ClarkeCC** [standardnotes/forum#59]
I changed my password and I needed to logging off my account, when I logged back in I noticed:

On my desktop it says 16/16 encrypted notes. (Correct number of notes)
On my iPhone it says 19/19 items encrypted.

Software and app are all up to date. Nothing is missing or duplicated. I tried logging off and on again but still the different note numbers.

Any ideas?

**Comment by mobitar** [comment]
On the desktop it only counts actual notes, while on iOS it counts all items like notes, tags, extensions, editors, etc. I need to change the desktop to have the iOS behavior. I've made a note of this, thanks.

**Comment by ClarkeCC** [comment]
@mobitar ah I see, yeah that matches up. Thank you for the clarification!

**Comment by mobitar** [comment]
Fixed in v2.
