### ISSUE TITLE
[Feature request] iOS swipe menu

### ISSUE THREAD

**Issue by igorkulman** [standardnotes/forum#591]
On iOS it is common for apps to implement a "swipe menu" in list. In the list of all notes, the user would be able to swipe from right to left on any note and select Archive or Move to trash without having to open the note and invoke the top right menu.

**Comment by mobitar** [comment]
We use long press to accomplish an actionsheet menu.

**Comment by igorkulman** [comment]
I missed that, long press is not really discoverable on iOS.
