### ISSUE TITLE
[Feature request] Free grey dark theme

### ISSUE THREAD

**Issue by HeyPapito** [standardnotes/forum#593]
Standard grey dark theme for all free users and pure dark black theme for only extended (paid) users. 

Would be great as most users only need the dark theme and not other features in the subscription. (like myself who is having eye issues with white light)

**Comment by mobitar** [comment]
To be quite straightforward with you, we give so much away in the free product, that we can't afford to subsidize any other features. The line we draw is that you get free encryption and sync on unlimited devices (which many other apps charge for), but for everything else, you have to pay your fair share.

**Comment by HeyPapito** [comment]
I get where you’re coming from but because paid users already have access to dark theme and extensions to make their own theme. Adding just a simple grey theme for free users would probably encourage more people to join Standard Notes, as many users have had to change to Simplenote because of this. Hopefully I can check back in a year or so and see if the free version is improved a bit.
