### ISSUE TITLE
[Issue] Support mail is opened in Microsoft "Mail" instead of system configured standard mail application

### ISSUE THREAD

**Issue by bluescreenfun** [standardnotes/forum#595]
In the windows desktop version in the top-level menu under "Help" there's an option labeled "Support". When clicked, this button opens the windows "Mail" application. I guess this is supposed to work like a "mailto:" link, but it opens windows "Mail" even though my system configured standard mail application is outlook. 

![image](https://user-images.githubusercontent.com/47524656/59916809-77b92f00-9420-11e9-89f9-31ac8095f7e7.png)

![image](https://user-images.githubusercontent.com/47524656/59917040-16459000-9421-11e9-9b0c-b61a39dca021.png)

I can't use this support button because I don't have my email account configured in windows Mail. 

It would be better if this button opened the configured default mail application, and not just windows "Mail".

**Comment by mobitar** [comment]
It's just a mailto link, and will open whatever you have configured in your system as the default to handle mailto links.

**Comment by bluescreenfun** [comment]
Hmm strange. On my home PC it does use the system default, but on my work PC it didn't. Oh well, can't test it anymore because this was actually my last day at work.
