### ISSUE TITLE
[Change request] Don't show notes while opening app

### ISSUE THREAD

**Issue by bluescreenfun** [standardnotes/forum#596]
Situation:
Currently, when the app (desktop, mobile and web) is opened it defaults to the "All notes" view. It loads the notes and you can see them flying by as more are loaded. 

Requested change:
Don't show any notes until the user clicks either a tag or the "All notes" view. The screen should remain blank or some welcome page should be show. 

User story:
The user is sitting at his computer at work, showing something to his colleague. The user wants to show something on a website where he has to login. He opens standard notes because it is his password manager, or because he has the link to the site he wants to show there. Standard notes opens in the "All notes" view and starts loading the notes. As the notes are being loaded, the co-worker sees a note titled "p*rnhub login" (or "resignation letter draft") passing by. Awkwardness ensues. 
This happened even though the user was careful enough to put the notes that he didn't want others to see under a separate "private" tag, because the default view when opening standard notes is "All notes".

**Comment by mobitar** [comment]
It's a fair use case. I think the solution is some sort of "Hide" option for notes, where you can hide them from the All notes view.
