### ISSUE TITLE
[Issue] Website problems in Microsoft Edge

### ISSUE THREAD

**Issue by bluescreenfun** [standardnotes/forum#597]
In Chrome the https://standardnotes.org/ site looks like this:

![image](https://user-images.githubusercontent.com/47524656/59918872-45123500-9426-11e9-8279-dfc0062d738a.png)

In Edge it looks like this:

![image](https://user-images.githubusercontent.com/47524656/59918905-5c512280-9426-11e9-9ff4-97ed71052643.png)

Notice that the text in the download button is off-center. This is the case for all buttons with this style. 

In Chrome the downloads section looks like this:

![image](https://user-images.githubusercontent.com/47524656/59918980-86a2e000-9426-11e9-94c4-ea28c0d698cf.png)

In Edge it looks like this:

![image](https://user-images.githubusercontent.com/47524656/59919019-9fab9100-9426-11e9-91b9-eac8393d461a.png)

Note that the symbol shown for the web version is the symbol for Chrome in Chrome, and the symbol for Safari (!) in Edge.

**Comment by mobitar** [comment]
Thanks for the heads up, will take a look at this when I get the chance.
