### ISSUE TITLE
Increase Payment Options

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/forum#598]
I was an extended user a couple of years ago and coming back now, I'm unable to use any of the available payment options to subscribe. This isn't a problem with any of the available options but the cards that I have access to presently and I was wondering if it is possible to add support for debit cards (especially RuPay).

**Comment by mobitar** [comment]
@lokesh-krishna welcome back :) Does Stripe not accept debit cards? What about crypto—is that not an accessible payment option?

**Comment by lokesh-krishna** [comment]
Managed to subscribe with my mom's debit card so I was wrong about that. Closing the issue now :)
