### ISSUE TITLE
Action bar disappeared after I clicked "Email"

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#6]
In Firefox 53 I installed the Action Bar extension, then in the Action Bar clicked **Email**. The Action Bar's text completely disappeared. (And no Email related activity seemed to occur.)

I tried Disabling and re-Enabling the Action Bar. That didn't restore its text. I then reloaded the entire Standard Notes page. As the page reloaded I saw that Standard Notes (re-)loaded extensions. At which point the Action Bar's text returned.

I performed those steps twice to ensure that clicking Email in the Web client does indeed cause the Action Bar to become an empty rectangle. This isn't a show-stopper at present -- just lettin' ya' know...

**Comment by bepolymathe** [comment]
Hi,

Are you using windows or Linux ? 
I don't have the same problem...

**Comment by mobitar** [comment]
I think I know what happened. When you hover over the action bar, on the right, an X icon appears, which allows you to remove the action bar for the current note.

Since the email is all the way on the right, if your window is small, you might accidentally click X. If this happens, click Menu -> Restore Disabled Components to restore.

**Comment by WritingSolutions2020** [comment]
> "Since the email is all the way on the right, if your window is small, you might accidentally click X.
> If this happens, click Menu -> Restore Disabled Components to restore."

Nope that wasn't it. I did learn 'bout that earlier, though...

I'm on Windows 7 64-bit. But wait -- the disappearing text problem seems to have disappeared.

For what it's worth I'm experiencing quite a few hiccups with the u.i., in the Web client via Ffox 53, Vivaldi browser (based on Chrome), and the Windows client. One such hiccup was that I ended up with two Action Bars at the bottom of some but not all Notes. As is the case with similar Standard Notes quirks, I can usually click and reload my way out out of these problems. At least eventually. So I seem to have unsnarled the problem, whatever it was.

I still receive nothing if I click *Mail*, though. But no big deal -- I'll worry 'bout that later.

So for now I'd just say that it's an early-release issue. Or even user error (I ain't perfect...)

Cheers & thanks all for your help...

**Comment by mobitar** [comment]
Hmm strange. Let me know if you're able to reproduce any of the issues.

**Comment by bepolymathe** [comment]
Hi, I had the problem once with the email button that did nothing. I resolved it re-selecting a default mail application. Do you use a web mai or a mail client (thunderbird, outlook, other) ?
Regards

**Comment by WritingSolutions2020** [comment]
> "I resolved it re-selecting a default mail application. Do you use...?"

"Re-selecting" how? I use one or another Web mail client via a browser. Mostly GMail although I have other Web mail accounts. Do you mean re-selecting in Standard Notes? If yes, I can't find where in the u.i. that would be done. Thx...

**Comment by mobitar** [comment]
For the record, try pasting this link in your browser and see what happens:

mailto:hello@standardnotes.org

Does it open an email client? If not, you might need to set it up somehow.

**Comment by WritingSolutions2020** [comment]
> "Does it open an email client?"

Yeah -- I'll investigate what I can do to "connect" the button to something. For example, I recall there's a small utility that makes GMail via a browser one's default email client. Thx 'gain...
