### ISSUE TITLE
Any news regarding the React Native apps for Android and iOS?

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/forum#60]
Has been a while since I've heard anything about them. Has there been any development on that front? Would love to be able to check the status of that project and would love even more to beta test the Android app if you need someone for that.

**Comment by mobitar** [comment]
Haven't gotten anywhere far with this. Other pressing things came up. Still considering if it's the best way to go.

**Comment by OriginalFannibal** [comment]
Just hope that whatever direction you choose, Markdown support is taken into consideration.
