### ISSUE TITLE
Scroll in split view is not working properly

### ISSUE THREAD

**Issue by rsau** [standardnotes/forum#600]
I am using 3.0.14 on Ubuntu 18.04.02 LTS 
Editor is Simple Markdown Editor. 

Scroll is working fine when Edit or Preview is enabled but broken in Split view.

**Comment by rsau** [comment]
I have 1.3.6. 
I just reinstalled the editor. 
Updated StandardNotes to 3.0.15 AppImage
Page Up/Down keys are working fine but split scroll is painfully slow. 

I had to use scroll button 65 times to scroll 1.5 page which  can be scrolled with one scroll motion when in Edit or Preview mode. 

There are no errors or warnings in console.

**Comment by mobitar** [comment]
How much memory and CPU do you have available when doing this?

**Comment by rsau** [comment]
I have Intel® Core™ i7-4770K Processor, 16GB memory. 

I used https://trackthis.link/ and used all four categories to open 400 tabs in 4 windows and scroll was working fine.   System was struggling as 4 vagrant vms are also running with total of 8.5GB allocated to them. VMs were sitting idle for test purposes. 

Scroll issue is not deal breaker but it is annoying. 

Which other editor has edit/split/preview mode?  
I'll test it

**Comment by mobitar** [comment]
How long is the note btw? And does performance differ based on note size?

**Comment by rsau** [comment]
It is happening on all notes but the one I tested for previous comment was 1.5 page. 
Same behaviour irrespective of note size

**Comment by mobitar** [comment]
Ok thanks. We'll need to wait and gather more user reports on this. So far you're the only one to mention this (after the initial performance fix was made).
