### ISSUE TITLE
Feature Request: A Shortcut Key for Closing/Opening the left side panel windows

### ISSUE THREAD

**Issue by TK42DAN** [standardnotes/forum#601]
Unless there is already a way to do this (I'm struggling to find much on hot keys), I would love to be able to close the two left panes without having to get out my mouse and click and drag two different edges over. It's too cumbersome. 

As I just noted in a different thread, this would be irrelevant if we could just double click our note and have it pop up in its own window without the two panes, as in Apple Notes. Adding this would kill two birds with one stone.

**Comment by mobitar** [comment]
There are two ways you can do this:

1. Double click on those vertical resizers, and it will automatically collapse or expand.
2. Use the No Distraction theme. It will create a shortcut in the bottom right corner of the dock.

**Comment by TK42DAN** [comment]
Good to know! Thanks.

**Comment by HansCronau** [comment]
>     2\. Use the No Distraction theme. It will create a shortcut in the bottom right corner of the dock.

I have seen this button in the web demos, but it's missing from my desktop clients (Windows/Linux). Am I doing something wrong?

**Comment by mobitar** [comment]
Try uninstalling your themes and reinstalling if you don't see the dock.

**Comment by HansCronau** [comment]
Thanks! Uninstalling and reinstalling all themes did it!

Observation: I had just installed Standard Notes fresh on a new machine. Despite the fresh install, it was missing the theme buttons just like my other machine was. Is that a clue that my account synced the issue to the new machine? Curious.

**Comment by mobitar** [comment]
It's not that it was an issue, it's that if you had the themes installed prior to the dock feature release, you wouldn't get the dock until you uninstalled and reinstalled them. Then the dock would sync to your other devices.
