### ISSUE TITLE
[Feature Request] Microsoft Store version for Windows

### ISSUE THREAD

**Issue by nluck** [standardnotes/forum#603]
Electron-build also supports creating an [AppX package](https://www.electron.build/configuration/appx) for Windows which can be distributed via the Microsoft Store. This would still be an Win32 application, just using the desktop bridge feature.

This would enable Windows S mode support and central deployment options.

**Comment by mobitar** [comment]
On desktop we don't go through stores currently. Helps us control distribution and reduce overhead. This includes Apple App Store, Snap store for Linux, and Microsoft Store.

**Comment by nluck** [comment]
Ah, that makes sense. Thank you for clarifying though!
