### ISSUE TITLE
Standard Notes uninstalling itself and unpin to task bar

### ISSUE THREAD

**Issue by TuWHe** [standardnotes/forum#604]
Hello, I have an issue with the program where it uninstalls itself on my laptop, and unpins on both laptop and tower.

I have Standard note on my tower, smartphone and laptop, all with the same account.
Standard Notes has been uninstalled without my permission a few times on laptop already, and the taskbar pin on both devices disappear regularly. Smartphone has no issues.
I don't mind that much, but it's interesting that it keeps happening. It has to be me, right? Firewall maybe?
I'm on windows 10. Help me figure it out please? Thank you.

**Comment by mobitar** [comment]
Sounds like it may be the autoupdate. It uninstalls the old copy, and installs the new one. If you're not seeing a new one being installed, then it may be being blocked by your firewall.

**Comment by TuWHe** [comment]
> 
> 
> Sounds like it may be the autoupdate. It uninstalls the old copy, and installs the new one. If you're not seeing a new one being installed, then it may be being blocked by your firewall.

thank you.
