### ISSUE TITLE
[Windows] Auto-delete empty tags?

### ISSUE THREAD

**Issue by WillRieske** [standardnotes/forum#606]
Since I don't have to type the '#' for the first tag of a note, it's inconsistent to have to type '#' for additional tags. So if I forget to, it creates a false tag of the form '#tag1 tag2', which sticks around after I correct my mistake until it's deleted. This could be solved by requiring the first '#', using a different tag delimiter, or auto-deleting empty tags.

**Comment by mobitar** [comment]
Well, the rule is that it should have a #, but assume the user just starts typing without the #—are we to show an error? We just took the route of interpreting their intention. Autocomplete is available via the Quick Tags extension. Auto-deleting empty tags is a possibility, but it may surprise the user.

**Comment by WillRieske** [comment]
Could insert the # into the text field if the user doesn't start with that.
That'd make it clear that following tags should have the #. Currently
showing a faded # before the user starts typing is useful as a reminder of
which character to use, but disincentivizes typing the initial #. (Which is
useful, just confusing for adding additional tags.)

A prompt to delete an empty tag, with a checkbox to "remember choice" & a
toggle in Settings, would reduce the impact on users whose workflow
includes preserving empty tags (e.g. to-do categories).
A study of user tagging behavior via the web app might be possible.

**Comment by mobitar** [comment]
Good points, appreciate the feedback.

**Comment by myreli** [comment]
Closing this as it doesn't reflect the current tagging experience with the new UI (which prevents empty tags).
