### ISSUE TITLE
[Windows] Selected note disappears when changing list sort

### ISSUE THREAD

**Issue by WillRieske** [standardnotes/forum#607]
If the user is viewing a note and wants to see its Date Modified or Date Added, the user has to change the sort and scroll to find the note again. This is difficult when the user has many notes.

This could be remedied by displaying the date in the selected note pane, or by keeping the list in sync with the currently selected note when the sort changes.

**Comment by mobitar** [comment]
The sort order of notes change when you change the view. It might make indeed make sense for the app to scroll back to the current note. For now, you can use the Action Bar extension which will display the note's created and modified date under the note at all times.

**Comment by WillRieske** [comment]
Thanks for pointing me to that extension.
A possible problem with autoscrolling to the selected note on sort change is that it'd require loading the surrounding notes in the list view too, and perhaps the entire list up to that point. I could see that being burdensome for a user with many notes who's just trying to quickly check the note's other date value.

**Comment by mobitar** [comment]
Ah right, that would be really bad for performance, especially if we have to load 2,000 notes to get you back to where you were.
