### ISSUE TITLE
Road map and note links redux

### ISSUE THREAD

**Issue by russlipton** [standardnotes/forum#608]
Without expecting overmuch detail, are you able to share your tactical (features ...) vision for the next year or two going forward? My serious adoption of standardnotes and, quite likely, Listed, still awaits some sort of implementation for links between notes. Exposure of UUIDs to facilitate a Zettlekasten-style of note-taking would also be super. Sigh.

**Comment by mobitar** [comment]
SN is very much a what you see is what you get app. I wouldn't hold out for anything new. We take our sweet time shipping features, and make sure not to do that too much. Linking in particular has been discussed before and stands as an "interesting idea" but nothing more currently.
