### ISSUE TITLE
[Issue] Tabbing (in note body) shows up differently in Firefox vs. Vivaldi(Chromium-based browser)/Desktop

### ISSUE THREAD

**Issue by WildManiac** [standardnotes/forum#609]
Tabbing (indenting) shows up differently between Firefox and Vivaldi/Desktop (both Chromium-based, I think?).

Examples below:

As viewed in Vivaldi (as well as on Desktop):
![vivaldi](https://user-images.githubusercontent.com/11233971/60466759-925e8580-9c22-11e9-8b05-26df86ad6ef7.jpg)

As viewed in Firefox:
![firefox](https://user-images.githubusercontent.com/11233971/60466773-9be7ed80-9c22-11e9-8165-1e7b4c7238f6.jpg)

What I found was the following:
- Tabs typed while in Vivaldi/Desktop show up as 
    - 2 spaces while in Vivaldi/Desktop
    - 8 spaces while in Firefox
- Tabs typed while in Firefox show up as
    - 4 spaces while in Vivaldi/Desktop
    - 4 spaces while in Firefox

Testing was done with the following:
- Firefox Nightly (Latest update as of midday 7/1)
- Firefox Stable (67.0.4)
- Vivaldi Snapshot (1587.4)
- Vivaldi Stable (2.6.1566.44)
- Standardnotes Desktop (3.0.15)

**Comment by mobitar** [comment]
We use the `tab-size` CSS property with a [value of 2](https://github.com/standardnotes/web/blob/master/app/assets/stylesheets/app/_editor.scss#L116). Perhaps some browsers require a custom prefix?

**Comment by WildManiac** [comment]
It would appear so, at least in Firefox.
See: https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size

At this time, to use `tab-size` in Firefox you would have to use `-moz-tab-size`. But just changing that doesn't truly resolve the issue, as seen in the below testing.

When viewed in Firefox, no code change
![viewed_in_firefox](https://user-images.githubusercontent.com/11233971/60523690-2b3fe000-9cb9-11e9-8d7e-3ed3a6282dbe.jpg)

When viewed in Firefox, after changing `tab-size` to `-moz-tab-size`
![viewed_in_firefox_changed_to_-moz-tab-size](https://user-images.githubusercontent.com/11233971/60523577-f764ba80-9cb8-11e9-8685-e9554cceea55.jpg)

When viewed in Firefox, after changing `-moz-tab-size` to `4` instead of `2`
![viewed_in_firefox_changed_-moz-tab-size_to_4](https://user-images.githubusercontent.com/11233971/60523879-870a6900-9cb9-11e9-83f4-94c2d6b7f7f3.jpg)

When viewed in Vivaldi, no code change
![viewed_in_vivaldi](https://user-images.githubusercontent.com/11233971/60524020-cafd6e00-9cb9-11e9-9211-c6ae13f299cb.jpg)

When viewed in Vivaldi, after changing `tab-size` to `4` instead of `2`
![viewed_in_vivaldi_changed_tab-size_to_4](https://user-images.githubusercontent.com/11233971/60524339-5ecf3a00-9cba-11e9-96cc-c9e6fb7f24a0.jpg)

My conclusions from the above tests:
- Tabs created in Firefox are 4 spaces, regardless of what we set as `-moz-tab-size`
- Tabs created in Vivaldi are 8 spaces by default, or whatever is set by `tab-size` (Chrome) or `-moz-tab-size` (Firefox)

**Comment by mobitar** [comment]
Interesting, thanks for the summary!

**Comment by WildManiac** [comment]
Another interesting tidbit (and the reason why a tab is _always_ 4 spaces when typed in Firefox) is that hitting tab _creates_ 4 spaces.  This is the reason why it is not affected by `tab-size` or `-moz-tab-size`.

In Vivaldi/Desktop, a tab is a tab. Which is why when you change `tab-size` (or `-moz-tab-size` when viewed in Firefox) the spacing changes.
