### ISSUE TITLE
Action Bar's Duplicate button non-functional?

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#61]
For both Windows desktop client 1.2.4 and Web client via Firefox 53.

In the Action Bar, the **Duplicate** button seems to be non-functional. Clicking it produces no response. I can but suppose that it was meant to create a copy of the note currently being viewed?

The **Copy to Clipboard**, **Save** and **Email** buttons work.

Cheers & hope this helps,
Riley
SFO

**Comment by mobitar** [comment]
Thanks, will take a look at this.

**Comment by mobitar** [comment]
I just deployed a fix to this issue. Note that depending on your sort order for notes, you might not see the duplicated note in the current scroll position. A duplicated note will have create date and update date set to {now}, as opposed to the date the original item was created.

**Comment by WritingSolutions2020** [comment]
Yep -- confirmed that clicking **Duplicate** not creates a copy of the note AND adds the note's title as a new tag. (Glad this was actually an issue rather than another one of my inept fumblings....)

**Comment by mobitar** [comment]
Oh sorry, the whole "creates a tag with note title" issue was also fixed but not deployed. I just deployed it on the web app now, deploying to desktop by EOD.

**Comment by WritingSolutions2020** [comment]
Ooops, maybe not quite yet.

* In the Windows desktop client, **Duplicate** creates a new note but does NOT include the original note's tags.

* In the Web client via F'fox 53, the **Duplicate** seems to have gone dead again -- nothing happens good or bad...

Cheers & hope this helps,
Riley

**Comment by WritingSolutions2020** [comment]
I've left some real-time comments in a private Slack thread. Seems like changes are moving fast, but in a circle...

**Comment by mobitar** [comment]
Good catch on the missing tags. I've just deployed that fix to the web app (not yet desktop app).

Duplication should be instant. Please try disabling the ActionBar component then re-enabling it to make sure you aren't loading from cache.

Then, after duplicating a note, make sure you check the top of the notes list as it won't necessarily be where your current scroll position is.

**Comment by WritingSolutions2020** [comment]
OK -- per my preceding message things seems to be sorting out on the Web side. Desktop client to be continued...

Cheers,
RBV
SFO

**Comment by mobitar** [comment]
Ok, I've deployed the update to desktop v1.2.5. After upgrading, you'll most likely need to click Help -> Clear Cache and Reload to reload the extension from source.

(The way to verify you're running the correct version of the Action Bar in this case is that Duplicate will append "(copy)" to the end of the duplicated note's title.)

**Comment by WritingSolutions2020** [comment]
Yep -- verified in both Windows desktop client and Web client via F'fox 53.

Cheers & thanks for your help,
Riley
SFO

**Comment by franzliedke** [comment]
Hmm, probably slightly related:
When I "Duplicate" a note via the Action Bar, the tag first seems to be copied along; but once I reopen the app, the tag is gone. In addition, the editor is reset to the default editor. :confused:

**Comment by mobitar** [comment]
Oh, good catch! Can replicate that issue. Will get it fixed.
