### ISSUE TITLE
Q: Decrypted export. What can be done with this file?

### ISSUE THREAD

**Issue by ExpandingFoam** [standardnotes/forum#611]
Hi, 

I have been using extended SN for a couple of weeks to see if I want to commit to it. I am concerned with data portability and wanted to test the export before putting even more data in. 
**Short question:** other that SN, how to I open/edit the export files?

**Longer:**
I exported a decrypted backup and tried to [import it](https://www.notion.so/Importing-Guides-18c37b470e8941789548b68049af750b) as markdown (is that correct?) into [notion.so](https://www.notion.so). This gives me a totally unhelpful, non verbose error (their problem, not yours, I understand). Changing the extension to .md makes no difference. if it matters, I primarily use the Spreadsheet and Plus editors cause I like fancy documents. 

So I am trying to figure out where the problem is. I took one of my favourite slightly sprawling Plus editor documents, copied the markdown into a .md file and imported as above. This WORKS. 

Short of going through each file one-by-one is there any way to find the problem? I can't see anything between saving _all_ of the notes and manually saving only a _single_ note via text editor.

To narrow down the source of the problem I wanted to load it into another program, but it seems that developers are the primary end users for these and I am by no means a developer

- Chrome extension called [Markdown Preview Plus](https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl) which didn't work (it loaded the markdown as plain text). 

- [grip](https://github.com/joeyespo/grip), but apparently I exceeded [their limit](https://developer.github.com/v3/#rate-limiting) on the second attempt, and the instructions for fixing it didn't work. 

- I _was_ able to import both the complete backup and the single file somewhat successfully into [crypt.ee](https://crypt.ee). The information is there but there is lots of code that shouldn't be visible, visible. For example:

`",
 "title": "190602 Backup record",
 "references": [],
 "appData": {
 "org.standardnotes.sn": {
 "clientupdatedat": "2019-06-15T00:40:27.469Z"
 },
 "org.standardnotes.sn.components": {
 "6d9573b5-3790-44b9-b873-7f49d4ef7b83": {}
 }
 },
 "previewplain": "
"preview_html": null
 }
 },
 {
 "uuid": "cd568047-09c7-4505-a1e2-9b2209eae811",
 "content_type": "Note",
 "created_at": "2019-06-22T15:17:54.502Z",
 "updated_at": "2019-06-22T17:20:25.103Z",
 "content": {
 "text": "`

All that to say I have made some effort to work on this on my own, but tbh a lot of this looks-like-it-should-be-doable stuff goes zooooom way over my head. 

Thank you for anyone who read enough of this to attempt to make sense of it. I apologies for how difficult it is to follow.. I have done my best. Constructive criticism about how to write something like this is welcome, it's not something I have experience with.

**Comment by mobitar** [comment]
When you export a decrypted backup, you'll have two resulting files:

- a JSON based .txt file. This file is to only be read by SN in the future if you decide to import back the data. You can also open the file yourself with an editor just to view it for yourself.
- A zip archive containing plaintext files of all your notes. These files are much more portable, and these you should be able to import anywhere that accepts plaintext files.

We talk a little more about this here: https://standardnotes.org/help/14/how-do-i-create-and-import-backups-of-my-standard-notes-data

**Comment by ExpandingFoam** [comment]
Thank you for your response. 

I tried again and did get 2 files like you said. I am a bit puzzled because I'm 99% certain there was no .zip last time. Everything above I was trying to do with the .txt file, which makes sense why it didn't work! I searched with Spotlight for the file and manually checked the places I thought it might be hiding but can't find any evidence of the .zip or its contents. 

I have no explanation for what may or may not have happened and the issue (whether my error or something else) seems not to be duplicable at the moment. 

I did read the link above but I still don't know (other than Standard Notes) what can I use to reliably open these files to preserve formatting? 

Thank you!

**Comment by iamtomodev** [comment]
@ExpandingFoam It can be easy to miss the .zip file, as SN will show you two separate dialogues - the first for the .json export, the second for the .zip. I've accidentally cancelled the second one a few times during this sequence.

On the preservation of formatting - do you mean with the text exports or with the .json file? .json is inherently a data-storage format, it isn't intended to be imported directly to a notebook application such as Notion as "text". If you wanted to consume it you would need to use a json parser to translate the metadata and notes into some other format, such as markdown.

If you are using Notion the shortest rout would be to import the /Note/ directory within the exported zip file - it contains the note, stored in the format relevant for the editor you have chosen. E.g., most editors produce Markdown, however some may store as HTML (plus editor) or json (e.g, secure sheets editor).

Having a quick play with Notion.so, you would be able to use the Import -> Text & Markdown, or Import -> HTML to consume notes from the directory above. You should be close to parity on formatting at that point.
