### ISSUE TITLE
Inconsistency with tagging - quick tags vs. create new note from tag

### ISSUE THREAD

**Issue by bschlagel** [standardnotes/forum#612]
I notice that when adding a child tag, e.g. `parent.middle.child`, using the quick tags interface, it also automatically adds any parent tags (e.g. `parent` and `parent.middle`). This makes sense for tag filtering reasons and I understand is the expected behavior.

However when I click a nested tag e.g. `parent.middle.child` and create a new note from there, the note is *only* given that tag, and not any tags in the parent hierarchy.

I'd expect it to behave the same way in both cases, so a bit confused by the inconsistency; I think this could lead to unexpected behavior with notes not appearing when you click to a parent tag view even though a child tag is present.

**Comment by mobitar** [comment]
A tricky issue in that the native app does not discriminate against tags with a "." in them, whereas Folders and Quick Tags do because they are extensions that speak the same language. But in any case we might be able to make an exception here so that the behavior is more consistent.
