### ISSUE TITLE
[Feature Request] IOS Dark Mode

### ISSUE THREAD

**Issue by Marco1097** [standardnotes/forum#613]
Now that IOS 13 supports Dark Mode, it would be nice to be able to use a basic Dark Mode (no customizable themes or other more customizable things) even without a premium subscription (Extended). 
Having the Dark Mode active on the phone and then opening an all white app is really bad

**Comment by mobitar** [comment]
Not sure yet how native dark mode will play with React Native.

**Comment by christianhans** [comment]
Does this help?

https://medium.com/akveo-engineering/how-to-implement-dark-mode-in-react-native-app-7f22a47a1fef

With the release of iOS 13 coming soon this would be a very neat feature.

For setting light and dark themes, the current dialog asking to confirm Redownload of a theme (when long-pressing a theme in the side bar) could be replaces with a menu like this:

![](https://i.redd.it/ymbabb9hmsd01.jpg)

It would have three options:

- Set as light theme
- Set as dark theme
- Redownload theme

**Comment by mobitar** [comment]
Interesting..that could be one way to do it. It's not clear from the article though how iOS notifies the application of a system wide theme change. I'll need to scan the docs for this.

**Comment by Marco1097** [comment]
Do you have any update?

**Comment by JaspalSuri** [comment]
Hi Marco, this feature currently exists in the mobile apps. Simply press and hold a theme and select is as your light or dark theme. 

You can grab a dark theme by supporting us with [Extended](standardnotes.org/extensions) and/or choosing one [from here](https://github.com/jonhadfield/awesome-standard-notes#themes).
