### ISSUE TITLE
Conflicted copies happen even when only using phone

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#615]
When using my phone client on a connection with intermittent access, I frequently end up with conflicted copies. I assume this shouldn't happen if I'm only on one device?

Steps to reproduce: edit a note several times over the course of an hour or so, generally in a location with spotty internet access (gym, concrete building, etc).

**Comment by jelhan** [comment]
I'm running into the same issue regularly. Using StandardNotes in German trains I end up with multiple conflicted copies. 😬

I guess root issue is the bad mobile internet in Germany. But StandardNotes would work much better in these cases if preventing "conflicts" when only using one device by design.

> If requests are being dropped, then it may be that the server begins to have different timestamps than the local value, thus causing conflicts in future saves. This would seem to happen if the server successfully performs a save but the client drops the response that would keep its item in sync.

Maybe client could generate the identifier for a specific version instead of using server-generated timestamp? A client would than be able to provide a list of all maybe-saved revisions as base of an update.

**Comment by atmoio** [comment]
> A client would than be able to provide a list of all maybe-saved revisions as base of an update.

Elaborate? (the verb not the adjective 🙂)

**Comment by jelhan** [comment]
> > A client would than be able to provide a list of all maybe-saved revisions as base of an update.
> 
> Elaborate? (the verb not the adjective slightly_smiling_face)

Disclaimer: I have no idea how the conflict detection is implemented currently. All the following thoughts are abstract. You know way better if and how they could be applied to StandardNotes.

One option to implement conflict detection is using [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) and [`If-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match) HTTP request header. Every revision of a resource is identified by an `ETag`. The client specifies the `ETag` of the version, which should be overwritten by the upgrade using the `If-Match` HTTP request header.

The `If-Match` header allows to list _one to many_ `ETag` values by using a comma separated list. A client could use this to specify all _potential_ versions at the server, which the client is aware of. In the case discussed here that list would contain of two kinds of version:

1. The latest version, which the client _knows_ that it has been saved successfully. E.g. that could be the version the client fetched from the server. Or the latest upgrade, for which the client received a success message from the server.
2. All versions, the client attempted to save afterwards but got neither success not failure notification from the server.

This issue tries to address the case in which the client does not know the result of an operation triggered by itself. Therefore it is critical that the client could generate a valid ETag for a resource itself. Using a client-generated UUID as version reference (and `ETag`) is one way to achieve this. Using a hash of the content itself is another one.

**Comment by atmoio** [comment]
Interesting, thanks for describing 👍 Indeed, a content-based hash or etag could improve the current setup a bit, but I'd have to really mull it over to see exactly how well this can fit into our infrastructure. Will keep you updated as we dedicate more time to this!

**Comment by jelhan** [comment]
@effieeee Would be great if you could leave a comment why you closed this issue. Hast been addressed in a recent release?

**Comment by effieeee** [comment]
Hi @jelhan, after much infrastructure changes and the release of the new mobile UI, I've noticed a lot less reports of conflicting copies from users, though if you are still experiencing this frequently on your end, just let us know, and we can reopen this issue and revisit the topic!
