### ISSUE TITLE
Self-Hosted App and Extended

### ISSUE THREAD

**Issue by iamhazel** [standardnotes/forum#616]
Hi there, I'm hosting my own copy of the app at notes.website.com, and it's working BEAUTIFULLY! I love Standard Notes, thanks for everything you do!

I decided to buy a five-year subscription for extended but when I go to my local app and click extensions, it says the requested URL was not found. When I go to app.standardnotes.com and try there, it says "the page you were looking for no longer exists."

I just spent lots of money but can't seem to access the extensions. Any help would be wonderful!

**Comment by iamhazel** [comment]
I accidentally closed this! Reopening!

**Comment by mobitar** [comment]
Hi Hazel, glad to hear you’re enjoying it! For the Extensions manager to work with your self hosted setup, make sure you follow the steps in the readme under “Extensions Manager and Batch Manager”: https://github.com/standardnotes/web

It should work on our official app.standardnotes.org. What browser did you try with? Please try with another browser as well just so we determine if the browser is the issue.
