### ISSUE TITLE
UI annoyance when deleting the last note with a tag

### ISSUE THREAD

**Issue by jbrains** [standardnotes/forum#618]
The UI keeps adding a new/empty note when I try to delete the last note with a given tag. I have to return to the "All notes" view in order to delete that note. Here's a case where the UI is trying to be helpful, but instead it's creating a problem.

Steps:

1. Pick a tag and look at only the notes with that tag.
2. Delete all the notes with that tag.

When I delete the last note, the UI creates "Note 1" with that tag. I can't delete this without the UI creating another one in its place.

**Comment by mobitar** [comment]
Placeholder notes are intentional. Most users don't mind but a minority do. Note likely we'll change this anytime soon, but it may help to know the logic: if number of notes == 0 in a view, create placeholder note. 

You don't have to delete this. It's not a real note, just a placeholder. It will go away when you navigate away.

**Comment by jbrains** [comment]
The important part for me is this:

> It's a not a real note, just a placeholder. It will go away when you navigate away.

I couldn't tell that this is the case, because it looks like a note. My focus at that moment is in the editor pane and I don't notice that the number of notes with that tag remains at 0. It might help to do something in the UI (different background color? Self-describing text instead of "Note 1"?) to signal that this looks like a note but is not _yet_ a note. Otherwise it becomes one of those things that looks wrong even if it's right.

Thank you.

**Comment by mobitar** [comment]
Hmm yeah maybe. Will have to experiment with this more to see what feels right.

**Comment by jbrains** [comment]
I understand. If something happens to leap to your mind that fits very well, then that might help future users. Thanks.
