### ISSUE TITLE
Unexpected behavior of simple Markdown hyperlink...

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#62]
Per the attached PNG screenshot, for either the Web client in Firefox 53 or the Windows desktop client, a simple hyperlink becomes a very long link to a seemingly empty _Extensions Server_ page.

![2017-08-21 17_48_37-notes standard notes](https://user-images.githubusercontent.com/3333327/29544296-f7b84252-869b-11e7-9fa3-a4309600a6fe.png)

As shown in the attached screenshot of the Web client, I used the the _Simple Markdown_ editor to create the hyperlink:

 `[http://pygments.org/docs/cmdline/#generating-styles]()`. 

In the right-side panel containing the rendered Markdown, on hover that link link resolves to:

`https://extensions.standardnotes.org/b12f34dd29bfa5cc9ac18e1f1e2f89346f689db2a04035a18bf7acadd8c81e92/[MY EMAIL ADDRESS]/editors/simple_markdown?type=editor&name=Simple%20Markdown`

In the Windows desktop client, the link resolves to the same value.

Clicking that very long link displays a seemingly empty *ExtensionsServer* page.

Egads! Even if I incorrectly formatted the link I wouldn't suppose this would be the result(?)

Cheers & hope this helps,
Riley

**Comment by mobitar** [comment]
I'm not sure if this is the cause, but I believe that `[https://google.com]()` is not valid Markdown across all parsers. In my experience, I've had to put the URL in the parenthesis as well, even if it's the same value. Can you see if this is the cause?

**Comment by WritingSolutions2020** [comment]
OK, so copying the URL into the parentheses does remediate the issue.

Interesting...

Cheers & thanks,
Riley
SFO
