### ISSUE TITLE
Bold editor: File attachments can't be opened

### ISSUE THREAD

**Issue by ely-see** [standardnotes/forum#620]
Hello,

I can't open file attachments in the Bold editor, not on Windows, not on mobile (Android).

On Windows, I click on the link and then only a blank windows appears, on Android there is the message "Unable to open".

Please advise.

Thanks.

Andreas

**Comment by mobitar** [comment]
Can you try opening the file via the FileSafe interface itself and not via a link, and see if that works?

**Comment by ely-see** [comment]
Thank you for your answer.

In Filesafe, everything works.

**Comment by mobitar** [comment]
On Android downloading files is not supported. You can only insert files into the editor.

On Windows, which button are you pressing that results in a blank window?

**Comment by ely-see** [comment]
Okay, thanks.

On Windows, I click on the URL and then on the blob:file:///... Then the blank window appears.

**Comment by mobitar** [comment]
Thanks, can confirm this is a known limitation with the desktop app. Was made this way as a security measure, we'll need to find a safe workaround.
