### ISSUE TITLE
##### Leads to several duplicates

### ISSUE THREAD

**Issue by Fohroer** [standardnotes/forum#623]
I often write thoughts divided by ##### in one note.

Thought 1

#####

Thought 2

#####

And more

#####

and more

And them combine them to one.
After copying and pasting I get one note with text duplacated inside in resulted note.
This bug only shows itself when someting with ##### is pasted.

So In resulting note I have someting like:

Thought 1

#####

Thought 2

#####

Thought 2

#####

And more

#####

and more

#####

And more

#####

and more

**Comment by mobitar** [comment]
Which editor is this with?

**Comment by Fohroer** [comment]
> Which editor is this with?
Plain text.
