### ISSUE TITLE
Search searches inside search filed

### ISSUE THREAD

**Issue by Fohroer** [standardnotes/forum#624]
Ubuntu Linux 16.04 LTS with latest SN PC version.
Also on Debian 9 with latest SN PC version.

Expected behaviour:
Seach seaches notes.

Behaviour observed instead:
Search immediately starts to search notes and also inside search field which blocks text entering.

**Comment by mobitar** [comment]
> and also inside search field which blocks text entering.

Not sure what you mean by that.

**Comment by Fohroer** [comment]
![Search](https://user-images.githubusercontent.com/6697344/61181291-03dc0200-a62d-11e9-941f-8bbcbe280fe2.png)
Look at attack.
Text has orange bleeding because search tried to search text which I have entered inside text box where I need to enter text which I need to search.

**Comment by mobitar** [comment]
Ah I see, no way to prevent that currently, as it's a global underlying source code search for the string.

**Comment by Fohroer** [comment]
> Ah I see, no way to prevent that currently, as it's a global underlying source code search for the string.
Web version has not got this bug. Possibly you could use the same solution.
