### ISSUE TITLE
Scrolling does not work correctly

### ISSUE THREAD

**Issue by Fohroer** [standardnotes/forum#625]
Android 9 PIE Resurrection Remix Xiaomi Redmi 5 A.
Premium version.
Scrolling in tags list works let's say normally.
Scrolling in notes list does not work. It's not accelerated at all. As I roll my finger, list moves. When I stop my finger, scrolling stops. I can't roll list from top to bottom fluently.
It's a bug.
I believe that you can fix it if you provide the same algorhytm as for scrolling tags to main notes list.

Expected behaviour:
The notes list scrolls along.

Behaviour observed instead (always):
The notes list does not scroll along. At all.

Pity bug this makes app close to unuseful.
If you need logs, contact me via email buranek@ya.ru

**Comment by mobitar** [comment]
A user has reported this once and said restarting the app fixes it. Otherwise it's not reproducible on my end.

**Comment by Fohroer** [comment]
> A user has reported this once and said restarting the app fixes it. Otherwise it's not reproducible on my end.
Restarting app and restarting Android doesn't do anything with this bug.
Tags scrolling inside note view works well. You could try apply the same algorhutm to other lists. Maybe it will work?

**Comment by Fohroer** [comment]
Any ideas?

**Comment by mobitar** [comment]
I can't replicate this issue, sorry. If you can provide a video of it happening that could be helpful.
