### ISSUE TITLE
FileSafe, WebDAV and Seafile

### ISSUE THREAD

**Issue by 2agr6v9u7mxu** [standardnotes/forum#626]
Hi,

I cannot get Filesafe with webdav to work with Seafile and their webdav implementation.

I run the Seafile server with nginx, I have tried with and without fastcgi; however the upload always results in an error.

I have tried a number of configurations within the link integration page and non of them work; the basic setup I have tried is as follows:

```
https://<url>:<port>
<username>
<pass>
seafdav/<foldername>
```

I do not know how to debug this issue?

**Comment by mobitar** [comment]
Hmm, not sure about Seafile. One thing you can try is connecting to your remote server via https://github.com/mar10/wsgidav and see what kind of results you get. This way you'll at least be able to see detailed error messages.
