### ISSUE TITLE
Two instances on the same computer?

### ISSUE THREAD

**Issue by arcanecode** [standardnotes/forum#627]
Is it possible to have two instances of StandardNotes installed on the same computer, such that you can have them open side by side with a different login on each?

There are two situations where I can see this being useful.

First, in a situation where you want to migrate some of your notes, but not all, to a different account. In my case I'll be creating a work based account and want to copy some notes from my personal over it it.

This is also something I can see doing on a regular basis. I find some new cool technique for doing something while at work, and make a note of it. But later I may also want to have a copy and store it in my personal account. 

And yes, I can think of a dozen different ways to get the info between accounts, but a simple copy paste direct from one instance of Standard Notes to a second seems the most simple, and it vastly minimizes the risk of that data leaking out during a transfer via another medium.

In the second situation, I could see someone who has one account for their day to day, and wants the convenience of just opening the program and having their notes ready without having to login. But they may also have some data that they want to keep really private, and will logout after each use. 

This would let them use their main account in an easy manner, without logging in and out all the time, but still have a second super-duper-uber-secret account and have it open at the same time as their regular main account. 

I'm kind of doubtful this would be doable on tablet based devices, but on PCs I would think it might work. 

Is this possible now, and if so anything we need to know to make it work? Or is this idea not possible under the current architecture?

**Comment by mobitar** [comment]
This is not possible with the desktop app. What you can do however is open multiple browser windows to the web app at app.standardnotes.org. Each browser can only have 1 open instance in the main session, and another in an incognito tab, so you can use the desktop app in conjunction with multiple browsers.

**Comment by arcanecode** [comment]
Thanks, that's a great idea. And if you have 4 different browsers, each with a regular and incognito mode, add desktop and that makes 9 instances! Epic. 

Not that I need anywhere near that many, but just sayin'.     ;-)

This actually helps with something else too. Makes it easy to have the desktop on my work machine hooked into the work account, but still be able to open up my personal via the web browser on the occasion when I need it. And vice versa.

**Comment by stevesbrain** [comment]
Check out [Firefox Container Tabs](https://support.mozilla.org/en-US/kb/containers) for unlimited sessions in one browser :D

**Comment by mobitar** [comment]
Oh interesting!

**Comment by davidlee321** [comment]
I'm surprised one cannot have two offline installations of SN. For example, the installer (.exe) doesn't let you install SN to different paths. I have notes in 2 different directories that I keep separate due to these 2 notes having different access privileges. This is the only thing stopping me from migrating to using SN.

**Comment by effieeee** [comment]
Tracking here https://github.com/standardnotes/forum/issues/958
