### ISSUE TITLE
Same text, different tagset

### ISSUE THREAD

**Issue by lucasgonze-smp** [standardnotes/forum#628]
Once a day I create a #daily tag in the desktop app. Some days, like today, the note with that tag is is added a tag set called #daily. Other days it is added to a tag set called #daily. Yes, right, they are identical text but different sets.

Maybe there is some textual difference in the tags, but I haven't been able to find it. I even copied and pasted the tag from a note in one tagset to a note in the other tagset.

They exist side by side:
![Capture d’écran 2019-07-15 à 09 17 10](https://user-images.githubusercontent.com/37877558/61231778-a5249000-a6e1-11e9-854f-c2dc7a97a507.png)

This is in one tagset:
![Capture d’écran 2019-07-15 à 09 17 28](https://user-images.githubusercontent.com/37877558/61231764-9f2eaf00-a6e1-11e9-85ad-06df13fca262.png)
This is in the other tagset:
![Capture d’écran 2019-07-15 à 09 17 23](https://user-images.githubusercontent.com/37877558/61231765-9fc74580-a6e1-11e9-99c8-e74a76f7239f.png)

**Comment by mobitar** [comment]
This might just be a sync conflict where the tag got duplicated. It's safe to delete one or the other.

> Once a day I create a #daily tag in the desktop app

How do you go about doing this?

**Comment by lucasgonze-smp** [comment]
Two ways.

1. Click on #daily in the list of tags in the Views nav, then click "+" next to "daily" in the center nav.
2. Click on All Notes in the Views nav, then click + in the center nav, then enter "daily" in the #tags line in the right nav

**Comment by lucasgonze-smp** [comment]
BTW I am technical and can run a debugger if that's helpful.

**Comment by lucasgonze-smp** [comment]
You said it's safe to delete one or the other. However this is not a workaround, because the ones in the set where I delete the tag will all need to be retagged manually, and the set is too large for that to be feasible.

**Comment by mobitar** [comment]
Ah so you create a new note once daily in the #daily tag. In this case it's definitely just a sync conflict with that tag. My recommendation is deleting the tag with the lower number of notes. (Deleting a tag does not delete any notes).

**Comment by lucasgonze-smp** [comment]
My issue will continue to arise for all dedicated users. Do you have
thoughts on methods to reconcile the sync conflict without accumulating so
many errors over time?

Simply deleting a tag is not helpful for a heavily used category with 100+
notes, since that means having to manually retag each note, and with the
potential for a sync conflict each time.

**Comment by mobitar** [comment]
I'm not sure I'm following why deleting one tag would mean you would have to retag each note? That's not the case. You have 392 notes in one of the daily tags and 388 in the other. If you delete the 388 tag, then 392 notes will still have the original #daily tag with 392 notes.

**Comment by lucasgonze-smp** [comment]
I see your point. I've done as you suggest. Thanks for taking time.
