### ISSUE TITLE
Non-default themes change first-level bullet text in Minimal Markdown editor

### ISSUE THREAD

**Issue by raritet** [standardnotes/forum#63]
I use the Minimal Markdown editor because of some personal preferences (I don't really like how tight the text is in the Simple Markdown editor, I'd prefer monospaced text in the entry area, etc.).

However, when I use anything but the default theme, it changes the blue monospaced text of at least first-level bullet points to a regular font in what appears to be the theme highlight color.

This is on the macOS native app, but I believe it happens in the web interface elsewhere, too... Just checked on Chrome on Windows 7 and indeed it's the same thing.

**Comment by mobitar** [comment]
This is unfortunately not something that's easily solvable given that modifying the internal Markdown's editor's colors for every theme would be near impossible. I don't have any alternative solutions other than to find the editor that works best for a given theme, or using the standard theme. If this changes in the future, I'll follow up here.

**Comment by raritet** [comment]
The bigger issue for me (I understand font is barely an "issue") is that the text changes font to a non-monospaced type. It seems reasonable to me that first level bullet color would be the active theme highlight color or something like that. But it feels like the themes are taking over some--but not all--of the editor's visual aspects, most notably, while the default theme doesn't take over (or if the default theme does too, it does so in a different way).

I guess enabling themes is not just replacing the overall app's default stylesheet. If it is, it seems like the theme stylesheets do things a little differently than the default.

If that's the case I'll just close this issue... though I would like to ask where can I fork the themes (default and others) to play around with them if I'm feeling fancy one day? I took a quick look around and didn't see.

**Comment by mobitar** [comment]
Can you attach a screenshot to make sure we're looking at the same thing?

**Comment by raritet** [comment]
Sure. Here it is with the default theme:

<img width="844" alt="screen shot 2017-08-23 at 1 23 24 pm" src="https://user-images.githubusercontent.com/8404519/29629417-b720e610-8806-11e7-8843-c1e8df4a2373.png">

And here is the same text with Titanium:

<img width="838" alt="screen shot 2017-08-23 at 1 24 22 pm" src="https://user-images.githubusercontent.com/8404519/29629424-c2145098-8806-11e7-9167-fd47d3c5c580.png">

Note the first level bullets in the editor. Blue monospaced versus purple sans serif. Monospaced vs. sans serif is the main thing I'm talking about.

I've grown used to the default theme. It's nice and consistent and classy. But sometimes I want something a little darker, that's all. But the different fonts bother me. Again, it's not a huge deal by any means, but I figured I'd mention it since it seems inconsistent.

**Comment by mobitar** [comment]
Hmm that's strange. Will take a look at this.

**Comment by effieeee** [comment]
Closing since this editor is deprecated
