### ISSUE TITLE
[iOS] Screen flicker when typing note title

### ISSUE THREAD

**Issue by pipitone** [standardnotes/forum#633]
I'm new to Standard Notes, and I've looked around the forum and the slack group but haven't found this issue reported. I'm using an iPhone 6, iOS 12.3.1 with the App version 3.0.10. 

While typing in the note title text field I will, seemingly at random, get a full screen flicker. Here's a screen recording demonstrating the behaviour:

![out](https://user-images.githubusercontent.com/509382/61499122-12f7e280-a994-11e9-99f7-19d6879759e3.gif)

This happens reliably with new notes and existing notes. I am signed into a private account, but I don't have Extended.  I've changed the theme to Red, but it happens with Blue also. This is over Wifi. Doesn't happen in any other App.

**Comment by mobitar** [comment]
Strange, haven't seen that before. But an iPhone 6 is really much older than we test with, and I'm guessing React Native tests with as well, since that's what framework we use.

**Comment by pipitone** [comment]
Agree, it’s strange. Not a huge deal as it only happens when editing the titles. File this under #wontfix
