### ISSUE TITLE
S3-compatible storage?

### ISSUE THREAD

**Issue by stevesbrain** [standardnotes/forum#634]
Hey guys, in FileSafe, I notice there's an S3 option. I don't see any place to specify endpoint though - is there any support for this? I.e. I don't use AWS - but I do have Minio which uses an AWS-compatible API. I'd like to be able to utilise this so I can store my files in my own backends that are not supported already :)

**Comment by dagjaneiro** [comment]
Interesting. The S3 integration is a fairly new one and we only support integration with Amazon right now. That being said, from a quick search, it seems it wouldn't be too hard to integrate with Minio so it's definitely something worth considering.

**Comment by stevesbrain** [comment]
Would definitely appreciate it if it did happen :) Whilst I love the integrations that are currently offered, I would definitely love to be able to make use of my own infrastructure for this too through minio (also opens up "bridges" to anything that minio supports - i.e. could be storing on Backblaze B2 as a backend, but due to minio, the "client" - filesafe - only has to support the S3 API and minio handles the rest) :)

**Comment by jaxtherogue** [comment]
I also use an provider with an AWS-compatible API, Wasabi. Integration would be great.

**Comment by joshcsullivan** [comment]
+1 for Wasabi and BackBlaze Support.

**Comment by JaspalSuri** [comment]
Thanks for the suggestion! I'll add it to our list for review!
