### ISSUE TITLE
[Enhancement Request] Always use dark keyboard for dark themes on iOS

### ISSUE THREAD

**Issue by christianhans** [standardnotes/forum#635]
On iOS the plain editor is switching to a dark keyboard when using a dark theme:

![IMG_3147](https://user-images.githubusercontent.com/355541/61585065-3e5c0800-ab21-11e9-95ec-0b8545a914da.png)

When using any extended editor, the default keyboard is used:

![IMG_3148](https://user-images.githubusercontent.com/355541/61585067-487e0680-ab21-11e9-8add-cc481d95fee9.png)

**Comment by mobitar** [comment]
We use dark keyboards in dark themes for the plain editor, but there doesn't seem to be a way to choose keyboard types for webviews, which is how external editors are presented.
