### ISSUE TITLE
Cannot install extensions when installing on Linux with existing account

### ISSUE THREAD

**Issue by cedewey** [standardnotes/forum#636]
I registered for Standard Notes on my MacBook. I recently bought a ThinkPad and am running Elementary OS on it. 

I installed Standard Notes on the ThinkPad and signed in with my existing account. I have the Minimal Markdown extension with my paid account. Standard Notes automatically tried downloading the extension, but is not able to. The same is happening for "No Distraction Mode"

In the terminal I see a log message repeatedly, 

```Installing component No Distraction https://github.com/sn-extensions/no-distraction-theme/archive/1.2.2.zip
File download not 200 https://github.com/sn-extensions/no-distraction-theme/archive/1.2.2.zip
File download success https://github.com/sn-extensions/no-distraction-theme/archive/1.2.2.zip
Syncing components: 1```

In the Standard Notes UI I get the message, "There was an issue loading Minimal Markdown Editor."

**Comment by mobitar** [comment]
Might be a permissions issue on your OS with extracting the downloaded archives. Can you click Help > Open Data Directory > Extensions, and tell me what you see? You should see folders, and not just zip files. If just zip files, then likely the app doesn't have sufficient privileges to extract these files. Can you try changing the privileges/ownership for the app or that directory and see if that helps?

**Comment by cedewey** [comment]
Hi, sorry for such a late response. I forgot I hadn't actually responded that the issues resolved itself somehow. I am able to use both of my extensions as expected.

**Comment by JaspalSuri** [comment]
That's great to hear; thank you for letting us know! We hope you enjoy the recent updates. 🙂  Please don't hesitate to reach out to us with any questions.
