### ISSUE TITLE
Dynamic Filters: Untagged notes doesn't update from mobile

### ISSUE THREAD

**Issue by stevesbrain** [standardnotes/forum#637]
Hey there,

I used [this page](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters) to create an "untagged notes" view. I have been sorting out some old imported notes this way - including tagging from mobile. The view works correctly on mobile - I can add a tag from either desktop or mobile, and it disappears from untagged view.

However, on the desktop, if I've added a tag from mobile, it won't disappear from that view (and if I click on the note, I can see a tag exists). If I add an extra tag, or remove and re-add a tag, that note disappears from this view - desktop client doesn't seem to pick up the existing tags that have been synced though (for this view). Let me know if you need anything further :)

**Edit:** As an aside to this, any tags entered by mobile cannot be removed by desktop in this view by clicking on them. Any additional tags added by desktop can be removed by clicking on them. Any tags added by mobile can be removed in standard view by clicking on them. 

Also, any item viewed for the first time as a tagged or untagged item from the all items view, before being viewed in untagged view, seems to behave normally. As far as I can tell, it looks like the item has to not be viewed by main desktop client first, edited from mobile, then viewed from desktop in order to replicate - I've been tagging old imported items. It could also be that this only happens to old notes, or imported notes as well.

**Edit 2:** Somehow in amongst it all the untagged view has updated... I'll leave this here because I have experienced it twice - not sure if you'll want any more debugging from me, or if this seems like an edge case. Let me know!

**Comment by mobitar** [comment]
Hmm, interesting. And to be sure, you manually clicked Refresh on desktop anytime you were expecting changes? The app syncs every 30s otherwise.

**Comment by stevesbrain** [comment]
I did yeah - confirmed everything was in sync (as I could see those tags that I'd created on the mobile listed on the note in the Untagged view), and even subsequently created new notes which did appear as well.

**Comment by mobitar** [comment]
So I just tested this myself with the same Untagged smart tag, and if I have a note that appears in the list on desktop, then add a tag to it on mobile, then refresh on desktop, the note disappears from the list on desktop, but stays open. The stays open part is expected behavior. Could be a race condition, given you saw the issue once but not again..

**Comment by stevesbrain** [comment]
Yeah, the staying open part I totally understand. Perhaps it was just a once off then - unlikely I'll be doing the same again anyway (given I'm done sorting my imports), but if I do notice it happen again, I'll get a backup from beforehand and try replicate reliably with video etc. Will close for now - cheers!
