### ISSUE TITLE
[Windows] Can't bring menu bar back

### ISSUE THREAD

**Issue by isaacsu** [standardnotes/forum#639]
Hi, first of all apologies if there's a manual that I should be looking at but I've gotten my standard notes into a particular configuration that I can't seem to get out of .

1. Changed menu from "themed" menu to traditional windows menu.
2. Restarted. Showing traditional horizontal windows menu.
3. Activated "hide menu bar" (under `View` I think).

Now I can't figure out how to bring it back.

Could someone help please?

**Comment by mobitar** [comment]
The shortcut to toggle hide should be Alt + M.

**Comment by isaacsu** [comment]
Worked. Thanks. I wonder if there's a way to make this more obvious in the product.

**Comment by mobitar** [comment]
We do communicate the shortcut in the menu itself, but once it's hidden, there's no good way to communicate it currently.
