### ISSUE TITLE
 Your subscription is expired or cannot be found. 

### ISSUE THREAD

**Issue by bbabel** [standardnotes/forum#64]
Hello, recently I have been seeing this message in all my notes, even the new ones I create.

I don't remember having and extended account or anything, so I don't know what's this about. Any thoughts?

**Comment by mobitar** [comment]
Hey sorry about that, please see this thread: https://github.com/standardnotes/forum/issues/56

You'll need to disable the editor you're using and use the plain one.

**Comment by bbabel** [comment]
Yes, that solved the problem. Thank you.
