### ISSUE TITLE
[ android ] tap tag: view list of protected notes

### ISSUE THREAD

**Issue by leela52452** [standardnotes/forum#640]
version: 3.0.12 [ fdroid ]

present behaviour: 
tap foo tag
only archived and locked notes list is displayed

desired behaviour:
tap foo tag
display protected notes

**Comment by mobitar** [comment]
I'm not sure I'm following. Why would tapping a random tag show only protected notes?

**Comment by leela52452** [comment]
| note name | tag |
| --- | --- |
| note 1   |        foo |
| note 2     |      foo |

note 1 is locked & archived
note 2 is locked, archived & protected

tap hamburger on left
tags
tap foo

current behaviour:
only note 1 is displayed

desired behaviour:
note 2 is displayed

**Comment by mobitar** [comment]
Archived notes in general should not be visible in any view besides the Archived view. I couldn't reproduce this in any case. If you can attach a video recording that would be very helpful.

**Comment by leela52452** [comment]
archived
today archive lock
test archive lock protect
tag: epub

tap tag:epub
only test note visible

![issue](https://user-images.githubusercontent.com/52065244/62257750-7eab6800-b3f6-11e9-815d-b1fd0fc7b9ee.gif)

**Comment by leela52452** [comment]
> Archived notes in general should not be visible in any view besides the Archived view.
understood
