### ISSUE TITLE
When searching on Mac, everything gets stucked 

### ISSUE THREAD

**Issue by Thenorneron** [standardnotes/forum#641]
When performing the search first time after app start it starts searching and displaying notes but after couple of letters search gets stuck and it highlights search for first couple of letters in some notes and those same letters in search field. At that point I can't continue typing. I have to then click X to clear search field and make a new search. That other search works fine. Issue is with first search after app start. This seems only on desktop both Mac and Windows and I thing editors might be the issue. When there is note with editor in the list of searched notes that note somehow throws off search.

**Comment by mobitar** [comment]
Yeah, this issue can occur if when searching, the note that is selected has an editor that requests autofocus. So the cursor moves from the search box to the editor. I believe the Simple Task Editor is the most prevalent one that autofocuses right away. We'll need to find a good solution to this.

**Comment by Thenorneron** [comment]
Do you have any plans for implementing in-note search? I know some markdown has it and web-version but I would really like it like an add for every editor or just separate option like ActionBar or FileSafe and that it works in iOS. Simplenote has great search.

**Comment by mobitar** [comment]
In-note search is made a little trickier for us because of the extended editor support. This will be a huge challenge to solve but one I do think we'll undertake at some point.
