### ISSUE TITLE
Auto-capitalisation is broken in editors in iOS 

### ISSUE THREAD

**Issue by Thenorneron** [standardnotes/forum#642]
So when using editors especially Markdown, first letter capitalisation is broken. Letters are all lower key and when I turn on shift for first capital letter it just keeps them capital. It's really annoying rendering editors on ios useless for me...

**Comment by mobitar** [comment]
The Advanced Markdown Editor has this issue for sure, and it's something we're hoping will be fixed by the vendor (it's based on an open source project). Which other editors have you seen have this issue?

**Comment by Thenorneron** [comment]
I see it in Minimal Markdown, Andvaced Markdown, Plus editor, Bold editor  (doesn't auto-capitalize). I really like Standard notes and have 5-year subscription but this issues are kinda annoying...
