### ISSUE TITLE
Print notes

### ISSUE THREAD

**Issue by phifa** [standardnotes/forum#644]
Ctrl+P on the desktop app should trigger a print view. Markdown text could be processed. Thoughts?

**Comment by mobitar** [comment]
Please see here: https://standardnotes.org/help/57/how-do-i-print-a-note

**Comment by phifa** [comment]
ok, so it remains on the roadmap, i assume. i guess for markdown notes i could write a parse-to-print extension. side-loading the extension (without releasing it officially) is possible, since it's open source, right?

**Comment by mobitar** [comment]
Yeah, you should be able to write an extension for this. Maybe something similar to the [Action Bar](https://github.com/sn-extensions/action-bar).
