### ISSUE TITLE
using alt shortcuts silently switches to "Delete permanently" button

### ISSUE THREAD

**Issue by chanclr** [standardnotes/forum#645]
ive noticed on Web and Desktop that while typing a note, if a press an alt shortcut (like Alt-Tab), the Move to Trash button would silently switch to Delete Permanently, even if the Options menu isn't open

**Comment by mobitar** [comment]
How do you know it switches to Delete Permanently if the menu is not open? Or is it that when you open the menu, it's stuck on Delete Permanently? What OS?

**Comment by chanclr** [comment]
Ah, it shows that it's switched the next time I open the menu. It's as if the menu was in focus even when not open. Pressing alt brings it back. OS is Windows 8.1.

**Comment by mobitar** [comment]
I can't replicate this on Mac, but will test on Windows when I get the chance.
