### ISSUE TITLE
[Feature Request] Batch actions (tagging, archiving, protecting, etc)

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#647]
This must have been mentioned/requested previously, but I think we need a way to manipulate multiple notes. The only notes-related function of the "Batch Manager" extension is to delete multiple or duplicated notes. There needs to be a way to do the following to multiple notes at a time:

delete
archive
protect
lock
pin
preview on/off
add tag
remove tags
move to folder

As far as I can tell, the only way to (for example) archive multiple notes is to do them one at a time. This is extremely cumbersome if you have hundreds of notes that you want to do this for.

**Comment by mobitar** [comment]
Indeed, something we're keeping in mind for a future release.

**Comment by claudiojulioferraz** [comment]
That's the only thing left for the app to be the best note writing solution.

**Comment by quartertone** [comment]
Any updates on this feature? Manually archiving 2000 notes is kinda cumbersome.

**Comment by ackstorm23** [comment]
Any updates on this feature? Manually archiving 1000 more notes since last year is beyond cumbersome.

**Comment by JaspalSuri** [comment]
Currently the dev team is working on stabilizing the 3.5 update for all of our users and then will work towards version 4.0, which will focus on overhauling the UI and UX for the app.

**Comment by effieeee** [comment]
Closing, already implemented :)
