### ISSUE TITLE
Docker image problem

### ISSUE THREAD

**Issue by MarcS1975** [standardnotes/forum#648]
Hi - I am trying to install the Docker image on a OMV (Openmediavault) server. The server supports Docker but I cannot find any documentation on how to configure the image correctly.
It installs without errors though. Its just configuration that is missing.
Any ideas please?

**Comment by mobitar** [comment]
Are you trying to host the web app or the sync server? 

There's some instructions here:

https://docs.standardnotes.org/self-hosting/self-hosting-with-docker

https://github.com/standardfile/ruby-server/tree/master/docker

**Comment by MarcS1975** [comment]
I am trying the sync server.
These instructions did not work.

**Comment by mobitar** [comment]
You'd have to share what went wrong..

**Comment by MarcS1975** [comment]
I cannot access the server. I think it's supposed to have a gui on port
3000 but no Web screen comes up.

Also when I try to register my host server on the standard notes Web page
an error message comes up
