### ISSUE TITLE
Install everything into a specific folder?

### ISSUE THREAD

**Issue by HCyberViper** [standardnotes/forum#649]
Hello, is it possible to install every single related standard notes files and data into a specific folder in my hard drive? I would like to not have standard note in my app local or programs folder or any related standard note files (I don't mean my notes I create) anywhere but a specific folder I have.

**Comment by mobitar** [comment]
This is not possible yet but something we hope to investigate in the future.

**Comment by CyberLustHD** [comment]
Will be looking forward to that! 👍
