### ISSUE TITLE
Simple Markdown editor: Some way to correlate position in left and right views?

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#65]
------
For Standard Notes' _Simple Markdown_ editor, it would be very handy if there was some way to quickly synchronize the vertical position of the left-side input and right-side rendered views.

Some of my notes require vertical scrolling. Especially when the Simple Markdown editor's two views are narrow because the _Notes_ and _Tags_ panels haven't been hidden via _Menu_ > _Toggle Fullscreen_. As shown in the following screenshot, because the left-side and right-side views scroll completely independently, it's not always easy to determine the corresponding portion of text in the companion view.

![standardnotesdesktopclientsimplemarkdowneditor](https://user-images.githubusercontent.com/3333327/29695891-32ebb934-88fa-11e7-8520-f2b14210fc6d.png)

That makes finding the equivalent position in the two views a bit time consuming and perhaps even derails one's train of thought. So it would be great if there was some way to more easily get the two views synched up. I wouldn't mind if double-clicking a word to select it in one view would select it in the other view. At least then I could easily spot the selected word as I scrolled the opposite view. Maybe even line numbers. I don't need something sophisticated, just a quick way to get the two views lined up without searching through text...

Cheers, thanks, & hope this helps,
Riley
SFO

**Comment by mobitar** [comment]
This would be neat. I'll have to look at ways of doing this, or finding an open-source editor that does this out the box.

**Comment by guydog** [comment]
I second this request

**Comment by WritingSolutions2020** [comment]
Take a look at StackEdit Version 5 (beta):

https://stackedit.io/app

By default the editor's left-side Markdown source and right-side rendered text scroll together. In the divider bar are several icons including, near the bottom, one labeled **Toggle scroll sync**.

And while the features set of StackEdit 5 may exceed that of soi-disant a _simple_ Markdown editor, I must say it provides a very pleasant Markdown editing environment...

**Comment by mobitar** [comment]
Yup, this is a pretty sweet editor. I'll take a look at what it takes to bring this in the SN ecosystem.

**Comment by effieeee** [comment]
Closing since this editor is deprecated
