### ISSUE TITLE
What does Passcode option do?

### ISSUE THREAD

**Issue by webcaptcha** [standardnotes/forum#650]
Thank you for developing this application.

I'm interesting in option "Add an app passcode to lock the app and encrypt on-device key storage."
What does it exactly mean? Without this option enabled local database stays unencrypted?

If yes what does e2e encryption means?

**Comment by mobitar** [comment]
The local passcode allows you to add a lock screen to the app, and also encrypts your keys. If you don't add a passcode, your data is stored locally encrypted with your account keys, but your account keys are stored locally not encrypted (since we don't have a key to encrypt them with). Adding a local passcode will then encrypt the account keys.

**Comment by webcapcha** [comment]
Sorry for stupid question, but does this mean that if somebody steal my storage it can decrypt database with key? Because key itself is unencrypted.

**Comment by mobitar** [comment]
If you don't have a local passcode, and someone is able to gain physical access to your device, then of course they will be able to see the data just like you're able to see it without additional verification. If you add a local passcode, then this will prevent that.

**Comment by webcapcha** [comment]
Oh sorry I might be put it badly. Of course I understand that without passcode anyone could open application and see notes like i'm able to see it without additional verification.

My question is little different.
Without passcode as you said starnardnotes database in encrypted but account key is not.

Imagine situation that for experiment i will send my database and account key for bad guy. Can he decrypt database using account key (which is unencrypted)?

**Comment by mobitar** [comment]
Yes, database can be decrypted with account key. If you want protection from physical theft or access, local passcode is the only way to go.

**Comment by mobitar** [comment]
Take a look at this article: https://listed.to/@sn/824/your-unencrypted-data-never-touches-a-hard-drive-with-device-storage-encryption

**Comment by TheodoreChu** [comment]
To answer the question about what end-to-end encryption means, please see this post: https://standardnotes.org/knowledge/2/what-is-end-to-end-encryption

It looks like this issue is solved, so I'll be closing it out 👋
