### ISSUE TITLE
2FA token limit length of 16 character?

### ISSUE THREAD

**Issue by mfa777** [standardnotes/forum#654]
I see there's many websites who support Google authenticator their 2FA token is much longer than 16.

Here if I use Tokenvault it limit token size to 16. If token longer or shorter than 16 it will not be saved.

Version: 3.0.15

**Comment by mobitar** [comment]
Can you give an example of a website and their respective secret key?

**Comment by mfa777** [comment]
![deb812c8e5e3cb6ee8710f3ea8a68559.png](https://286.im/images/2019/08/08/deb812c8e5e3cb6ee8710f3ea8a68559.png)

The system is based on Mastodon: https://github.com/tootsuite/mastodon

**Comment by mobitar** [comment]
Indeed, doesn't submit correctly. cc @dagjaneiro

The key is CYYV 4NMM S6XZ O25Y HI5I CJTQ YRAG BGGP

**Comment by dagjaneiro** [comment]
The only limit that we have in place is that the token must be at least 16 digits. 

Are you inserting the token including the white spaces? That indeed will not work.

Try entering the code like this: CYYV4NMMS6XZO25YHI5ICJTQYRAGBGGP.

**Comment by mfa777** [comment]
@dagjaneiro 

![imgurl](https://i.imgur.com/4JYtPLv.png)

**Comment by simonhurtz** [comment]
I've ran into the same problem when I tried to add a token for my Google account. All the others (Slack, Twitter, Facebook, Instagram, Paypal, Amazon, Dropbox, 33Mail) worked perfectly fine, but the Google token somehow couldn't be processed.

What worked for me: I switched to the plain text editor and pasted the token like this (just look at the other tokens and copy the format):
{
    "service": "",
    "account": "",
    "secret": ""
  },

**Comment by MorgothSauron** [comment]
I think it is "common" for site to give the secret key with spaces in it. When adding, why not simply remove spaces ? This way if a person forgets to remove the space the application would still be able to add the new token.

**Comment by dagjaneiro** [comment]
@mfa777 oh I see thanks for the example. The problem there is that it expects the code to be uppercase, It seems it's not converting the code when reading from a QR Code, I'll issue a fix for that, meanwhile, you can type a letter and delete it to force the code to be properly formatted.

@MorgothSauron yeah I'll make that change to avoid any confusion when copy-pasting codes.

**Comment by mobitar** [comment]
This issue should now be fixed and available in 1.0.5 of the TokenVault.
