### ISSUE TITLE
[Feature Request] FileSafe note attachment indicator

### ISSUE THREAD

**Issue by MorgothSauron** [standardnotes/forum#656]
Hello,
I recently started to use FileSafe with S3. Nice feature and simple to configure :)

However there is something missing. Unless I expand the FileSafe section of a note I have no indication if there's an attachment or not. When I tested FileSafe I added an attachment to a random note: it was a little bit annoying to check notes individually to find the one with the attachment.

I would be nice to have an indicator/icon in the note list to quickly identify notes with attachment. Or have the possibility to add a view that would filter on notes with attachment.

Thanks.

**Comment by mobitar** [comment]
Showing some kind of indicator of number of files in the notes list is not a bad idea. I'll keep this one in mind.

**Comment by joshcsullivan** [comment]
I agree some type of indicator is necessary in the note list.

Or in the FileSafe area, where you can see all of the attachments, when you click on the attachment, it should give you an option to bring to note along with the other options:

![image](https://user-images.githubusercontent.com/5774100/74112381-34a3fb80-4b6a-11ea-8d48-27aa215a9f8e.png)

For now, I'm using a FileSafe tag to easily check which notes have attachments.

**Comment by baptiste-grob** [comment]
v4 is currently in the design phase and we are indeed thinking about this (among _many_ other things, but no spoilers 😄)
