### ISSUE TITLE
[Feature Request] MacOS Keyboard Shortcuts & AppleScript

### ISSUE THREAD

**Issue by mvandermeulen** [standardnotes/forum#658]
Requesting keyboard shortcuts in MacOS and ideally AppleScript support.

Would appreciate if AppleScript support included:

- New note creation
- List notes, tags, etc
- View note

Regarding keyboard shortcuts I see requests already open outlining the kind of shortcuts which would make people happy. None of the requests are difficult or unreasonable however despite some requests being outstanding more than 2 years they still are not implemented. If development team genuinely have an appettite to implement such a basic request (it doesn't need to be complex particularly to begin with) then I would request at the very minimum some kind of realistic timeline to implement by. If there is no appetite however, I'd at least like to know so I can write off the investment and look toward a product which might actually meet my requirements.

l think it would be fair for me to take any closure of this request as demonstration of intent.

**Comment by mobitar** [comment]
Please see here: https://github.com/standardnotes/forum/issues/288#issuecomment-506744618
