### ISSUE TITLE
[Feature Request] Backup to S3 ?

### ISSUE THREAD

**Issue by MorgothSauron** [standardnotes/forum#659]
It would be nice if I could configure to backup my notes to S3. A new S3 "destination" could be configured for those who'd like to have separate bucket for FileSafe and Backups. 

To be honest, the less I rely on cloud storage like Dropbox for critical data, the better I feel.

What do you think ?

**Comment by mobitar** [comment]
We'll likely add this at some point, since we added it for FileSafe.
