### ISSUE TITLE
FileSafe - How to backup/decrypt attachments ?

### ISSUE THREAD

**Issue by MorgothSauron** [standardnotes/forum#660]
The current backup contains "only" the notes, but what about the attachments ? I tried the offline decrypt tool but I did not get anything. 

How tow to decrypt the attachments ? Files in S3 are just a bunch of JSON files.

Thanks.

**Comment by mobitar** [comment]
You can decrypt FileSafe files by dragging and dropping them onto the the FileSafe interface. It will decrypt and download. We do want to include FileSafe decryption as part of the offline script at some point.

**Comment by heymo** [comment]
Hey @mobitar - which "FileSafe interface" are you referring to - just the one inside of SN?

So we need SN to decrypt the attachments, at least until the offline script has support for decrypting the attachments?

**Comment by mobitar** [comment]
Yup that's correct.

**Comment by heymo** [comment]
Thanks for the clarification @mobitar - and thank you so much for your work on SN!!

**Comment by MorgothSauron** [comment]
I must be missing something because I don't get it. "dragging and dropping them onto the the FileSafe interface" just attach the file to the current note that is opened

**Comment by monaxle** [comment]
Hi @mobitar I have a bunch of encrypted files and the exported key file for them. None are now in SN but I still have SN with extended benefits. If there is a way how do I go about using the key file to decrypt the files? An odd situation that came about by issues with a Nextcloud install and me not thinking logically. Thanks for any pointers you can provide.

**Comment by JaspalSuri** [comment]
Have you tried the method mentioned above? That should work in your case as well.

**Comment by mobitar** [comment]
There's no way to import key files currently. They would have to be contained in your Standard Notes global backup file. Do you have a backup file that contains those keys? If not, you'd sort of have to do manual surgery where you download a decrypted backup, study the format for content_type "SN|FileSafe|Credential", and duplicate that entry to add your key data.

**Comment by monaxle** [comment]
Thank you @mobitar. Do you mean like this...

`#original content of the current backup file...

"content": {
        "keys": {
          "pw": "some original key data here",
          "mk": "some original key data here",
          "ak": "some original key data here"
        },


#duplicate the above but with data from key file added like so...

"content": {
	    "keys": {
	      "pw": "some key data here pasted in",
	      "mk": "some key data here pasted in ",
	      "ak": "some key data here pasted in"
    },`

**Comment by mobitar** [comment]
Yup exactly.

**Comment by alejandrogutierrez12** [comment]
Hi! is there a new update regarding a feature to decrypt fail-safe files offline? Thanks!
