### ISSUE TITLE
Minimal Markdown Editor: Decrease Indent When Pressing Shift + Tab in Highlighed Text

### ISSUE THREAD

**Issue by ThisFungus** [standardnotes/forum#664]
It is possible to increase indent block of a highlighted text when pressing Tab, but it is not possible to decrease indent when pressing Shift + Tab. Can you take a look at this issue, please?

Thank you.
_________________________________________

**Futher Details**

Platform:
Desktop Version in Windows 10

Steps to Reproduce:
  1. Highlight some block of a text
  2. Press Shift + Tab

Result:
No action happened.

Expected Result:
Decrease indent.

**Comment by mobitar** [comment]
I don't believe this shortcut is supported currently.
