### ISSUE TITLE
no desktop shorcut in Ubuntu 18.04

### ISSUE THREAD

**Issue by jobvanbarneveld** [standardnotes/forum#665]
I installed Standard Notes on various Ubuntu 18.04 systems. On every system I can see Standard Notes in the application list and make a favorite starter for the applicatiion.

Today I installed Standard Notes on another Ubuntu 18.04 system. After installation Standard Notes starts automatically, but I do not see the app in the application list. Neither can I create a favorite starter. What is happening here? 

Note: Standard Notes may have been installed before on the system, of that I am not quite sure. So there may be some interference with a previous install.

**Comment by mobitar** [comment]
Please see if this helps: https://github.com/standardnotes/desktop/issues/345#issuecomment-494816378

**Comment by aysunrhn** [comment]
I am having the same issue with Ubuntu 18.04, I checked the .desktop file, yes it is located where you had previously said, and everything seems to look as it should. 

I also tried deleting the .desktop file and running the application from scratch, but that doesn't solve the problem either :/

**Comment by jobvanbarneveld** [comment]
the solution Mobitar stated worked for me. You say you tried to delete the.desktop file, but did you succeed to delete it?

**Comment by jobvanbarneveld** [comment]
By the way, the file I deleted had the following name: appimagekit-standard-notes.desktop

**Comment by aysunrhn** [comment]
> the solution Mobitar stated worked for me. You say you tried to delete the.desktop file, but did you succeed to delete it?

Yes I had, but nvm I fixed it now. I made a new directory and moved the application there, deleted the .desktop file once again and restarted the application. It works fine now! Must have been an issue with the name of the directory.

**Comment by jobvanbarneveld** [comment]
good to hear! Standard Notes is awesome!
