### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by claudiojulioferraz** [standardnotes/forum#666]
I clone some extensions and the main application, and noticed something very strange and worrying. Typing `npm audit` realizes that app dependencies have critical security bugs. Can we trust such an application? Why not update dependencies?

**Comment by mobitar** [comment]
We do update dependencies, but not every release. I'll do another refresh for the next release to make sure every dependency that can be updated is.

**Comment by p0n1** [comment]
I am also worried about dependency vulnerabilities in Javascript libraries. Any ideas to avoid this in stdnotes?
