### ISSUE TITLE
Longevity

### ISSUE THREAD

**Issue by patrickf3139** [standardnotes/forum#668]
Hi Mo, first off let me say absolutely amazing work on Standard Notes. It is pretty much everything I want and I am seriously considering buying a 5 year subscription after researching many note-taking suites. I am truly amazed and inspired by your business, engineering, product management, customer support, and marketing prowess running (it seems) 99% of Standard Notes by yourself. However, I am a bit concerned about the longevity of SN despite what you've written in https://standardnotes.org/longevity
Even a genius, if by himself, cannot keep this up in the long-run. I mean, the work must be taxing on your health. And even if it isn't, one day you'll have to retire. Who then, will run SN?
I apologize if this is an uncomfortable question and too public of a place to ask you--but what are your succession plans?

**Comment by mobitar** [comment]
It's a valid question. I don't have plans on remaining solo forever. You start somewhere, and build a team over time. Unlike traditional VC-funded startups, we can't do it all at once. It takes time.

And assuming a worst-case scenario where everything implodes, I don't think users suffer except for a one-time inconvenience of having to find a new app. Your data is always downloaded to your local app and there are plenty of backup options.

**Comment by patrickf3139** [comment]
Thanks for responding Mo! That makes a lot of sense!
