### ISSUE TITLE
kolabnow webDAV integration through filesafe

### ISSUE THREAD

**Issue by eteuser** [standardnotes/forum#669]
I am having trouble integrating kolabnow's webDAV server with filesafe. I'm getting a generic "Error uploading file."

When I try to access the share via web I get the following response:

`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
 <s:sabredav-version>2.1.11</s:sabredav-version>
 <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
 <s:message>There was no handler found for this "GET" method</s:message>
</d:error>`

Wondering if anyone has run across this issues. Also am following up with kolabnow in parallel.

**Comment by mobitar** [comment]
What is the host url and directory you're using?

**Comment by eteuser** [comment]
host - https://apps.kolabnow.com/files
path - tried various include '/' '/files' 'Files' and none

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mobitar** [comment]
It's hard to debug these kinds of things. My recommendation is to try to use a general WebDAV client to try to connect to your server and see what happens.

**Comment by eteuser** [comment]
Is there a client you recommend on mac?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by effieeee** [comment]
FileSafe has been deprecated
