### ISSUE TITLE
feature request: entry_date

### ISSUE THREAD

**Issue by mheder** [standardnotes/forum#67]
See my original problem in #66 

I believe it would be good to have a third, user-controlled date field for the entries beside created_at and updated_at. 
Use case: in paper journals and journal/notekeeping apps it is common to have the ability of recording the events of a day the day after. Some maintain their journal once a week, reporting the last 7 days. 

This is currently impossible with standard notes. You cannot back-date entries except if you import them from json and even then they don't work properly (again, see #66).

I believe it would be bad to reuse created_at or updated_at fields for this purpose. It would be better to have an entry_date field which the user could change. It could have the same initial value as created_at. Then, the clients should use this for displaying/sorting the entries.

Without this functionality standard notes is not a complete personal journal application, only good for note taking. It is so close though.

**Comment by mobitar** [comment]
I'm not sure I'm following..entry_date is a user controller field that initially has a blank value until it is set by the user? What would be the UX for this?

**Comment by mheder** [comment]
It could be initially either blank, or, even better same as created_at. I would be happy with the simplest possible UX, like filling in manually the year, month, date, or a simple date picker. 

This way Standard Notes could become a personal journal app, a competitor to Diaro and others.  That would be nice!

**Comment by mobitar** [comment]
Hmm..well the issue of custom sorting can currently be solved through "sort by title", where you can prefix numbers to a note to make it appear first. It's not totally ideal. But I'm still not sure how a custom entry_date would work. Do you have examples of other apps that do this?

**Comment by mobitar** [comment]
Ah interesting, thanks for the detailed report. I can see how this can be handy. I'll keep this in mind. It's tricky since changing the [Standard File](https://standardfile.org) specification is not something to be done lightly. If this were a pure UX/UI change, it would be much easier. Let me think on it some more.

**Comment by mheder** [comment]
Another way could be to provide the ability to change created_at . This would not require changing the file format, only the semantics and would solve the use case. Although maybe this isn't so nice either as this overwrites the actual creation date.

**Comment by mobitar** [comment]
Yeah, that could work too.

**Comment by jnusy** [comment]
Any updates about adding a date picker or to provide the ability to change created_at. I am relatively new to Standard Notes and I would like to import my data from Diaro and other places. This feature would really help me.

**Comment by mobitar** [comment]
You can change this date if you edit the backup file you are importing directly. In terms of changing the built in date, nothing for this yet, but maybe some day in the future via an extension.

**Comment by jnusy** [comment]
Thank you for considering to add it as an extension in the future. It would
very useful for me even when not importing.

For now, how exactly can I edit the date created in the backup file
directly?

**Comment by mobitar** [comment]
You can click Download Backup, choosing the Decrypted option (in the Account menu). Then, in the single file that results (not the zip file), edit the created_at of the notes you'd like to change. Then import the file back in to your account. That should do it. If it doesn't, try the same thing, but deleting your current notes first, so that they don't take precedence.

**Comment by BuzzKnightbeer** [comment]
Are there any news regarding a better journaling support?

**Comment by effieeee** [comment]
Will continue tracking discussion on improvements for journal taking here: https://github.com/standardnotes/forum/issues/987
