### ISSUE TITLE
[Bug] Can't use Polish Programmer's Keyboard with Secure Spreadsheets

### ISSUE THREAD

**Issue by Iffabled** [standardnotes/forum#673]
Polish Programmer's Keyboard uses the AltGr key (the right Alt) to add diacritics to letters (for example: `AltGr+l` makes `ł`, `AltGr+n` makes `ń`). However, the Secure Spreadsheets editor uses this key for keyboard shortcuts (`AltGr+a` opens the Data menu, `AltGr+n` opens the Insert menu), which makes it really hard to use it with the Polish Programmer's keyboard.

**Comment by aaantoszek** [comment]
Oh yes! That is really frustrating. Both SS and AdvMd use Polish shortcuts, makes the app unusable on desktop, have to switch to web.
