### ISSUE TITLE
Updates Question

### ISSUE THREAD

**Issue by DrownedStarfish** [standardnotes/forum#674]
Hi!

How can I tell if the SN version I am using on my Windows Desktop is the latest, or if it should be updated?

Thanks.
D.

**Comment by mobitar** [comment]
You'll be prompted to update if there is an update available. There is also an Updates menu item if you open the top level menu in the top left. There you'll find information regarding your current version and latest version.

**Comment by DrownedStarfish** [comment]
Yup.  Thanks.
