### ISSUE TITLE
New to StandardNotes, have some quesitons

### ISSUE THREAD

**Issue by aaldilai** [standardnotes/forum#679]
I tried looking through the FAQ first, hope this is the correct place to ask.

* How do I create bullet points (not just astricks, but formatted bullet points)
* How do I create headers of different sizes?
* Can I import notes from Dynalist?

Thanks :)

**Comment by arcanecode** [comment]
If you are using the free version, you can't. At its core, Standard Notes is a text-based editor. I hesitated to use the phrase "simple text-based editor", but the text editor itself has the same abilities as Windows Notepad in terms of formatting. 

What it does do that other editors do not, is sync those text-based notes across all of your devices and keep them securely encrypted. Not bad for the cost of free.

If you have a subscription (like I do) you can use add-on editors, one of which is Markdown. In the Markdown editor. you can create bullet points, different header sizes, etc. I actually use the Markdown editor quite heavily.

As to your Dynalist question, I'm not sure, someone else would have to answer that.

**Comment by aaantoszek** [comment]
If dynalist supports exporting to plaintext, then yes: https://dashboard.standardnotes.org/tools
If you're on Extended (highly recommend) you can use various editors to work with bullet points. I personally use the Bold Editor for outlining. 
You can go and check out the Extended demo: https://standardnotes.org/demo to see whether or not you like the editors provided there

**Comment by aaldilai** [comment]
Thanks y'all :) I'm excited to try standrdnotes, might consider extended later after trying it basic for a while.

**Comment by aaantoszek** [comment]
Keep in mind that there's a 30-day refund guarantee, so you can just buy the monthly subscription for one month, and request a refund if you don't like it - just like a "trial"
