### ISSUE TITLE
feature request: night mode for android client

### ISSUE THREAD

**Issue by mheder** [standardnotes/forum#68]
The darkish themes for desktop are great. But it would be even more important to have it on mobile than on desktop. 

Use case: preventing the wakeup of S/O when taking notes at night - when the best ideas emerge.

Inspirational examples: Diaro night mode, Amazon Kindle app night mode, etc.

**Comment by mobitar** [comment]
That would be nice I agree. It's on the list but don't have a definite date yet.

**Comment by mheder** [comment]
Thanks!

**Comment by guydog** [comment]
I second the request; 
I opened a similar issue (#84) which could be closed or merged with this one.

**Comment by mobitar** [comment]
This is coming with the new mobile app :) Putting the finishing touches on it now. Join the Slack if you want to be a part of the beta.

**Comment by mobitar** [comment]
Now available in v2.
