### ISSUE TITLE
sync thru dropbox or onedrive?

### ISSUE THREAD

**Issue by stocksoup5** [standardnotes/forum#680]
Would it be possible to sync thru a cloud service we already use instead of SN's servers? In my paranoid mind it seems safer. Perhaps that's not true?

Thank you, 
~extended user

**Comment by MorgothSauron** [comment]
> Would it be possible to sync thru a cloud service we already use instead of SN's servers? In my paranoid mind it seems safer. Perhaps that's not true?
> 
> Thank you,
> ~extended user

dropbox or onedrive safer than SN ? I barely trust Dropbox to store encrypted backup of my notes (I'm waiting for a possible usage of S3 as a backup destination for SN). IMHO if you were really paranoid you would avoid these cloud providers to begin with ;)
