### ISSUE TITLE
Listed.to private?

### ISSUE THREAD

**Issue by amoratz** [standardnotes/forum#681]
Hi, 
I was wondering whether there is a way to have private groups on listed.to? I love the idea of the blog function and the integration with standardnotes. And I'm not sure whether asking this question is 'advocating for a new feature' - I don't mean to do that, because I appreciate standardnotes sustainability strategy. It just seems to me that having a way to only publish blogposts to a limited group of friends would be in the spirit of standardnotes. So I'm wondering whether this is possible somehow. 

Thanks!

**Comment by mobitar** [comment]
You can publish to a private link. Just choose the "Publish to Private Link" option. You can then share that link privately with others.
