### ISSUE TITLE
Standard Notes on Flathub

### ISSUE THREAD

**Issue by grgnday** [standardnotes/forum#682]
I would really want to see Standard Notes on Flathub and before asking the Flathub community I wanted to ask the developers to submit it there.

**Comment by mobitar** [comment]
We choose not to participate in 3rd party desktop stores currently, as this increases overhead for us and will make it more likely that some stores have outdated versions. This may change in the distant future.

**Comment by grgnday** [comment]
Alright. Thanks a lot for your response...
