### ISSUE TITLE
[Linux] minimize, maximize, close, hamburger menu don't work

### ISSUE THREAD

**Issue by Alfavio** [standardnotes/forum#685]
Hi,

I use [this](https://aur.archlinux.org/packages/standardnotes-desktop/) repository and **v3.0.15**. In a app the buttons for minimize, maximize, close and hamburger menu don't work. Also I have scrollbar in the app.

![index](https://user-images.githubusercontent.com/5478075/64471983-6e01b680-d147-11e9-9ccb-3fa490ae8754.png)

**Comment by mobitar** [comment]
We can't debug unofficial builds. But you can disable the themed menu bar to get the system level menu bar again, via the View menu.

**Comment by mobitar** [comment]
Oh, right, View menu would be inaccessible if hamburger menu doesn't work. I'd recommend downloading the app directly from our website if you're experiencing this issue.

**Comment by Alfavio** [comment]
Thank you. I installed a AppImage version from the [release page](https://github.com/standardnotes/desktop/releases/tag/v3.0.15) and now the app works fine.
