### ISSUE TITLE
Small Enhancement Suggestion: Roll-Over Text for Theme changer buttons

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#687]
Just today became aware that in the lower-right of the SN desktop client there are clickable buttons that change to different installed themes.

![SN_Linux_Desktop_3 0 16](https://user-images.githubusercontent.com/3333327/64735263-10e66780-d49d-11e9-8cca-3bf7d03d56db.png)

It'd be handy if hovering over those theme changing dots would display the name of a given dot's theme...

Cheers & hope this helps,
Riley
SFO

**Comment by WritingSolutions2020** [comment]
I see that this idea has been implemented in 3.0.17. A nice little addition -- glad I could help.

Cheers & thanks,
Riley
SFO

**Comment by mobitar** [comment]
Yup, thanks for the tip!
