### ISSUE TITLE
[Feature Request] Filesafe Sync.com support

### ISSUE THREAD

**Issue by hypopyon** [standardnotes/forum#689]
Hello! Recent purchaser of 5-year Extended plan here, love the features so far. I'd like to use the Filesafe extension, but I'm averse to using cloud storage providers such as Google Drive or Dropbox. I currently use Sync.com, however, it doesn't support the WebDAV protocol. Would you consider adding support for it to the extension, and would it even be possible to interface with their service?

**Comment by aaantoszek** [comment]
From what I know Sync is end-to-end encrypted, meaning no way to access data by a third party app such as SN. I don't use GDrive for anything, only for storing filesafe attachments, which are encrypted, so Google can't read them

**Comment by mobitar** [comment]
Correct, we can't interface with services that are end-to-end encrypted.

**Comment by hypopyon** [comment]
Ok, thanks for responses! I'll just use Google Drive then.
