### ISSUE TITLE
Text non-clickable - 3.0.16, Win10

### ISSUE THREAD

**Issue by balance-wtf** [standardnotes/forum#691]
_(Pasted from Slack)_

While I really enjoy the performance improvements in 3.0.16 on Win10, there is one very nasty bug that's made me go back to 3.0.15:
Every time I edit a line of text (note title, tag name, passcode box, search, not the note content itself), and then click somewhere else, all text becomes not-clickable, thus prohibiting me from editing again. Have to Ctrl+R the app to make it work again.
Is anybody else experiencing something similar?

**Comment by mobitar** [comment]
Any way you can capture a video of this in action? Also be careful when downgrading from 3.0.16 to 3.0.15: only do this if your data is synced to your account. The local storage mechanism gets upgraded when you go to 3.0.16 and cannot then be read by 3.0.15.

**Comment by aaantoszek** [comment]
Hmm... It'll be hard to capture that, as it is very random - I'll try.
Yea, all my data is synced ;) 
I'm now on 3.0.15 still

**Comment by mobitar** [comment]
You mentioned on Slack that it doesn't happen anymore with the official release?

**Comment by aaantoszek** [comment]
@mobitar It did work for like 3 hours, but then I put my computer to sleep, with SN open, turned it on again after an hour and there it was again, but now also in the editor window (only tried with Bold)
