### ISSUE TITLE
Listed private links not working

### ISSUE THREAD

**Issue by aaantoszek** [standardnotes/forum#692]
All Listed private links redirect to the main blog

Tried on 3 different blogs

**Comment by mobitar** [comment]
I can't reproduce this. Are these posts that are newly privately published, or previously privately published? Can you provide sample links?

**Comment by aaantoszek** [comment]
Try this: https://blog.antoszek.eu/p/Kry9GOZXZM

Redirects to main blog in Brave & Edge

**Comment by aaantoszek** [comment]
Happens to all private posts. No matter how old.

**Comment by bryvin** [comment]
What's interesting here is that it seems to work when you remove /p/ from the URL. For example: [https://blog.antoszek.eu/Kry9GOZXZM](https://blog.antoszek.eu/Kry9GOZXZM)

@mobitar Maybe this has something to do with your recent commit to move private posts to /p ?

**Comment by mobitar** [comment]
It looks to be a custom domain issue. Investigating..

**Comment by mobitar** [comment]
Should be fixed now.

**Comment by aaantoszek** [comment]
@mobitar Works! Thanks
