### ISSUE TITLE
Batch selecting notes

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/forum#693]
Presently, I am unable to batch select notes. I'm not sure if I'm missing something here or if this is simply not available. I've tried selecting multiple notes by clicking on them while holding `Ctrl` or `Shift` and each time, it simply selects whatever note I click on, instead of also keeping the previously clicked notes selected.

This can be really helpful when one wants to archive or delete or perform any other action on a rather large collection of notes.

**Comment by mobitar** [comment]
This feature is not presently available.

**Comment by naveensrinivasan** [comment]
@mobitar On a similar note, how can I batch delete all the notes? I have imported notes from Evernote without formatting and now I would like to delete all my 100's notes and reimport with the paid subscription.

**Comment by mobitar** [comment]
You can use the Batch Manager extension to do this. Or if you want to nuke your entire account, you can use standardnotes.org/reset.

**Comment by naveensrinivasan** [comment]
Thank you!

**Comment by effieeee** [comment]
Closing, already implemented :)
