### ISSUE TITLE
Problem launching standard notes.

### ISSUE THREAD

**Issue by arturoemx** [standardnotes/forum#695]
Today I couldn't launch standard notes as I used to. When I tried from a terminar I got the following message:

_[2874:0917/191051.200569:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_standacNRU6R/chrome-sandbox is owned by root and has mode 4755._

(I am running debian buster)

I found on a forum that I should just set a kernel flag (/proc/sys/kernel/unprivileged_userns_clone), which worked for me, but still I feel somehow that I'm making the system less safe.

why is this needed now?, is that the way it should work?

thanks in advance.

**Comment by affe42** [comment]
Hi! Yes, that's the way it's supposed to work. Standard Notes is built on Electron framework and the latest version needs **user namespaces** to implement the security sandbox. So, you did the right thing enabling it.

Here's additional info:
https://equk.co.uk/2018/04/02/forcing-namespace-sandbox-in-chrome-electron

**Comment by mobitar** [comment]
Please see this thread: https://github.com/standardnotes/forum/issues/690
