### ISSUE TITLE
Cannot enter or edit text sometimes

### ISSUE THREAD

**Issue by jrabensc** [standardnotes/forum#696]
Hi,

since about two days I am facing a bug:

When I enter or edit text sometimes no changes happen. Pasting is still working. When I switch to another note editing works fine, but not in the previous note. Waiting or restarting SN fixes the problem. 

OS: Windows 10 Pro
SN: 3.0.16
Editor: Advanced Markdown

**Comment by cliftonfoster** [comment]
I'm having this same issue. It's happened to me three times today. I am editing notes and it's as if the keyboard stops responding. I click on a totally different app and the keyboard works. I come back to SN and there is no response. I just close and reopen it.

OS: Windows 10 Ent
SN: 3.0.16
Editor: Plain Editor

**Comment by mild0d** [comment]
I am having the same problems also.  Its happening on three separate computers.  I have tried clearing cache and reloading but it still happens.  I noticed today that sometimes I will highlight some text and accidentally drag it somewhere else.  I get the message about "Please use filesafe or the bold editor to attach images and files." popup box.  The cursor disappears and I can no longer type an texted anywhere in the program.  After some time passes, a couple minutes, the cursor will start working again.

**Comment by aaantoszek** [comment]
Yes!! @mobitar this is what I was talking about ;) Y'all should go back to 3.0.15: https://github.com/standardnotes/desktop/releases/tag/v3.0.15
That bug gets pretty annoying if you're a speedy user (clicking fast and often)
