### ISSUE TITLE
Towards automations and integrations

### ISSUE THREAD

**Issue by lionsway** [standardnotes/forum#697]
I am a new, happy user of Standard Notes. Understanding that content is encrypted End to End affects my use of digital writing, it frees up my composition in a funny way. THere is a psychological benefit that I am grateful for. Thanks, Mo!

I love automations, like email-to-trello, Zapier, and IFTTT as well as the Android Share integrations that allow you to send from one app to another. They help ease the path to application use. I am curious what paths to this sort of Integration are up for development and I am curious how good privacy practices impinge on the convenience. For instance, email-to-standardnotes or ifttt-to-filesafe would both be awesome, but would pass content through non-encrypted channels, so I think that would no longer be end to end encryption. 

I would love to hear all the thoughts!

**Comment by mobitar** [comment]
Integrations are tricky. Any integrations we do have need to be client-side and not server-side, as the server cannot read contents. This means email-to-standardnotes or any ifttt integrations are out the question. We already have Google Drive, Dropbox, and OneDrive integrations for encrypted backups. And AWS S3 and WebDAV for FileSafe. But there are no further integrations planned. We'd probably leave this to the community. Could be interesting to see if perhaps some kind of client-side bridge could be built that could coordinate between the client and server to perform automated actions.

**Comment by lionsway** [comment]
Thanks for getting back so quick!

It is more about the fluidity to capture information in notes. what about widget extensions to the mobile app? 

Are Andriod and iPhone "share" features server side or on the device? I don't even know.
