### ISSUE TITLE
Note History not showing any history

### ISSUE THREAD

**Issue by deciare** [standardnotes/forum#7]
I installed the Note History extension for the first time tonight, and haven't been able to figure out how to actually view any history.

When I open the **Actions** menu and click on **Note History**, all I see is this:

![screen shot 2017-07-12 at 23 21 47](https://user-images.githubusercontent.com/1689220/28149107-140cf5fe-6759-11e7-85ca-2ba1c0f78705.png)

That's using the Mac desktop client 1.2.0. I've also tried using the Web client with Firefox 54.0.1. Am I missing something obvious?

**Comment by mobitar** [comment]
Hey, the three dots ... means that item is condensed in the UI. Try clicking it again to open it.

**Comment by deciare** [comment]
I did try clicking the 3 dots. Tried clicking multiple times (with an appreciable pause in between), in fact. That seems to just toggle the 3 dots on or off. Here's what I see after clicking on the dots:

![screen shot 2017-07-13 at 11 22 35](https://user-images.githubusercontent.com/1689220/28173821-9a07344e-67bd-11e7-8921-ae3378a86052.png)

**Comment by mobitar** [comment]
Ok, can you try again now by making new changes to a note to see if revisions show up? I checked the logs and it looked like some transactions weren't saving due to the database row being too small, so I expanded it.

**Comment by deciare** [comment]
Revisions are indeed showing up now. Thank you.
