### ISSUE TITLE
Feature request: Update your logo for Android/iOS app

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#70]
Title. Thanks. Again.

**Comment by mobitar** [comment]
There's a distinction between Standard Notes the "entity" and Standard Notes "the apps". The company has the blue logo. The apps have a platform-specific icon depending on what looks right for a notes app on that platform. An "n" with a blue background doesn't look like a notes app. The red and white notes icon however does. It's a specific design philosophy that throws some people off. But it's done to keep the focus on the app and not the company.
