### ISSUE TITLE
How to import without signing to online account 

### ISSUE THREAD

**Issue by ilian007** [standardnotes/forum#702]
Hello is there a way to import to the IOS app ver. 3.0.10 without signing in ? I see only Export option, but there is no import in the IOS app. 

Thank you!

**Comment by jbeldia** [comment]
Hi, I'm afraid import is currently only possible on the desktop app or web app (https://app.standardnotes.org/). To import a backup, click on "Account" on the lower left of the app and choose "Import Backup" in the "Data Backups" portion of the panel.

**Comment by ilian007** [comment]
> Hi, I'm afraid import is currently only possible on the desktop app or web app (https://app.standardnotes.org/). To import a backup, click on "Account" on the lower left of the app and choose "Import Backup" in the "Data Backups" portion of the panel.

Thank you! Do you know after - synchronizing/importing, using online account, how to logout and continue using synchronized notes offline ? Is there a way to keep them on the device only after synchronization ?
