### ISSUE TITLE
"Extended Version" account missing note histories!

### ISSUE THREAD

**Issue by PaulSanders543** [standardnotes/forum#705]
I lost content of a note recently.  So I went to the Session History online, and the only past version of the note that was there was *after* the content was gone.

I have been paying for the Extended Version for 7 months, and the note I created was 6 months old and I had made many changes to it.

What can I do?

**Comment by mobitar** [comment]
Session History refers to temporary changes in the current session. The Extended Note History is available via Actions. If you've had it enabled before the note changes, you should see that revision there.
