### ISSUE TITLE
[Feature request] Option to open to the same note after locking it and unlocking it

### ISSUE THREAD

**Issue by JimmyUX** [standardnotes/forum#706]
I am experiencing an issue where after the app auto-locks after a period of time on desktop (Windows), when I unlock it the app resets to a default position. Is there any way to have it remember where I was? It's got to the point where I have a zillion notes and folders etc so losing my place is quite annoying.

Thanks for all your hard work.

**Comment by mobitar** [comment]
This feature is not currently available, but I agree, it would be nice to have.

**Comment by mechanarchy** [comment]
Hi @mobitar, do you know if there is anything design/technical preventing this? Or is it just a matter of the SN team/a contributor writing code to adjust the behavior?

**Comment by effieeee** [comment]
There is now an option to have the app open your last viewed note on launch :)
