### ISSUE TITLE
Rotate Jpg

### ISSUE THREAD

**Issue by Slumberland** [standardnotes/forum#707]
iPhone images appear to have funky meta that causes the rotation format to be ignored in the Bold Editor (i.e portrait images get laid on their side). To get them to show correctly I had to drop them into the MacOS ImageOptim app first (re-saving in MacOS Preview didn't help).

It would be handy to have image rotate in the Editor, but this is a work around in the meantime.

**Comment by IceFire23** [comment]
I've been having this problem as well with many of my photos (OnePlus 6). Thanks for the tip about there being a workaround - I had tried rotating with Paint and messing around with the metadata, but none of that was working. I tried it again after reading your post, and some combination of using CaesiumPH and rotating with Paint3D seemed to fix the issue (sample size of 1) for me.

**Comment by JaspalSuri** [comment]
Hi @IceFire23, do you run into this issue with all editors?

**Comment by IceFire23** [comment]
As far as I know the "Bold Editor" is the only StandardNotes editor that supports inserting pictures, so I don't think there's any other ones to compare it against.

**Comment by JaspalSuri** [comment]
_Oof_. I overthought things and ended up making myself look cold and foolish. Sorry about that!

I'll report this over to the team. Thanks for the feedback!

**Comment by IceFire23** [comment]
Thanks for doing that!

And no worries, that wasn't my perception at all.

**Comment by effieeee** [comment]
FileSafe and Bold Editor have been deprecated
