### ISSUE TITLE
Is TLS 1.3 on the roadmap?

### ISSUE THREAD

**Issue by user8446** [standardnotes/forum#708]
https://app.standardnotes.org is currently using TLS 1.2. TLS 1.3 is faster and more secure. Is this on the roadmap?

**Comment by mobitar** [comment]
TLS 1.3 is not yet supported by AWS EC2:

https://github.com/awslabs/s2n/milestone/1
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2.html
