### ISSUE TITLE
Feature Request: Vim-Mode

### ISSUE THREAD

**Issue by samarkamat** [standardnotes/forum#71]
Hi Team,
I've been enjoying Standard Notes for a while, and the only missing aspect in my workflow that would make it perfect is support for a vim-mode in the desktop app. This could just be a subset that includes navigation and copy/paste (no buffers, splits, search, replace, etc).

Thanks very much!

**Comment by mobitar** [comment]
Here you go: https://standardnotes.org/extensions/vim-editor

**Comment by samarkamat** [comment]
wait... was this there the whole time!? Thanks!

**Comment by samarkamat** [comment]
This is exactly what i was looking for.
