### ISSUE TITLE
Android: Plus Editor and Bold Editor Icons too Large

### ISSUE THREAD

**Issue by lasscap** [standardnotes/forum#713]
On the SN Android app using the Plus Editor or Bold Editor the Icons for changing the text style are to large (or many) so they take up three lines and thus decrease the space to write if the keyboard is used. The remaining window is similar to a messaging app like Signal.

On the Advanced Markdown Editor the Icons are all in one line and one can slide through them. Maybe that might be a solution for this problem.

**Comment by mobitar** [comment]
Screenshot?

**Comment by lasscap** [comment]
Sure:
![2019-10-10-1](https://user-images.githubusercontent.com/47210775/66568959-d2f76480-eb6a-11e9-8b2d-bd947339f05f.png)
![2019-10-10-2](https://user-images.githubusercontent.com/47210775/66568963-d38ffb00-eb6a-11e9-929f-40aee41dd32c.png)

**Comment by mobitar** [comment]
Ah I see. Yeah, this is something I wanted to configure, but the Bold Editor made this very difficult. Will need to revisit this.

**Comment by effieeee** [comment]
Toolbar icons have been scaled down on the new UI
