### ISSUE TITLE
Mention the online demo in the "is there a free trial" FAQ

### ISSUE THREAD

**Issue by mmiller42** [standardnotes/forum#714]
In the FAQ question [Is there a free trial available for Extended?](https://standardnotes.org/help/40/is-there-a-free-trial-available-for-extended), it's mentioned that there is no trial but you can request refunds.

I think it's worth mentioning and linking here to the fully-featured demo on the website. After all, the reason for downloading a trial is primarily to explore premium features not available in the free client, and you can play with all the available themes and extensions right in the [demo](https://standardnotes.org/demo).

**Comment by jbeldia** [comment]
Fair point, it could be helpful for new users who just want to try out the extensions a little. @mobitar 

The demo is exclusive to the web app though, and it already contains dozens of filler notes for demo purposes. If the user really wants to try and see if the app suits their day to day workflow (without all the other demo notes in the way), I think it would still be better to purchase the app and experience it on all platforms with their own notes.

**Comment by effieeee** [comment]
Link to demo is now visible at the top header of the website
