### ISSUE TITLE
[feature request] allow me to do basic text formatting for free

### ISSUE THREAD

**Issue by h4ku-yuk1** [standardnotes/forum#717]
please allow me to do basic text formatting for free on standardnotes, like making words underlined and bold. the option to have subtags (as well as tags) would also be nice.

**Comment by hillbilly3456avk** [comment]
SN is a great product - even in the free version it served me well over a good amount of time. I think it is fair enough to pay if you needmore functionality. Only if we are willing to pay it will remain what it is now - we shouldn't be unthankful and ask for more free stuff. GAFA showed us clear enough where this *wegiveyoueverythingforfree* leads to. I am happy to pay - think about it too

**Comment by MorgothSauron** [comment]
I tried many application and SN is, IMHO, the best note taking app. It's worth every penny I'm paying for.
