### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by stephantual** [standardnotes/forum#719]
Sorry, didn't find a place to send you this:

a) search sucks, enable crtl+f for a note-wide search (of contents and/or title) and enable shift +ctrl+f for searching in the currently displayed note. Bonus points if you can set your engine to not search the markup if the notes are not in plain text. 

b) allow for multi-instancing on desktop - i don't trust the web version when in coffee shops and not vpned - i need two windows side by side.

c) take into account some of us use your software to take notes, but also to remember passwords ( a bit like dashlane does with 'application notes' or 'safe notes'). Having  note 'formats' adapted to various task would open a larger audience to your software. 

d) for the love of <insert favorite deity here> enable word wrap ooptions - maybe i feel like posting 4096 characters in a row (hint hint) and not see them broken down at the 80 column mark after 10 lines... 

Apart from that, you created the best note taking app on earth right now... so thank you for that.

**Comment by mobitar** [comment]
Thanks for the feedback. All noted. Although not sure what you mean by word wrapping. Which editor are you using? Should not wrap unnaturally.

**Comment by bclouser** [comment]
Came here to +1 making the note titles searchable. Additionally having to click "All Notes" before searching is an annoying extra step, ctrl-f would be a killer feature :)

That being said, Standard Notes is awesome! Much Love from this endpoint of the internet 👍

**Comment by mobitar** [comment]
Note titles should be searchable. You can do cmd + shift + f in the desktop app as well to focus the search field.

**Comment by bclouser** [comment]
whoops, I actually meant being able to search tags, when a global search is performed.

Also ctrl+shift+f doesn't work on linux (regular ole ubuntu 18) for me. cmd+shift+f does indeed work on mac as you mentioned.

**Comment by myreli** [comment]
I'm triaging older issues and while this one mentions different suggestions and approaches, I'll close it as most have been addressed: in-note search, shortcuts, note types, theming, etc. 

Please, start a new discussion if you have other suggestions. Thank you!
