### ISSUE TITLE
Feature request: Option to automatically open the iOS Apps with the same filter set.

### ISSUE THREAD

**Issue by mrtargaryen** [standardnotes/forum#72]
I have contacted the developer about this but thought I'd add the request here.

I love this service and use it everyday. Fully support it, and recommend it to everyone I know.

But I've found the iOS Apps unusual, but I like to use them and want to use them more often & stop using Apples Notes app all together.

My main issue is that when I open the Standard Notes App All of my Notes written with the Extensions activated on the Web UI and Desktop UI display all of the language muddled up with my text. So it makes the iOS App sort of useless for those notes.

So I've made a TAG called "iOS Notes" and all of these notes are written in plain text. And I'd love the option to automatically open the iOS app with the filter always set the "IOS Notes" tag. So I don't see any of the Notes created with extensions. 

It would be more convenient and aesthetically pleasing in my opinion. 

Anyhow, I wonder if others would also like this in an update some time. 

Thanks for a great service. :-)

**Comment by mobitar** [comment]
Totally reasonable, thanks for the feedback Simon. The form it will most likely come in is just that the app should remember its state every time it opens. 

Are you using the Plus editor by default for all your notes?

**Comment by mrtargaryen** [comment]
Yes, thats correct.

**Comment by mobitar** [comment]
This is now the default behavior in iOS v2.
