### ISSUE TITLE
The SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by emaddaou** [standardnotes/forum#722]
Hi guys, Please help.

when I try to run the AppImage from Debian GNU/Linux I got the following error.

imad@toshiba:~$ ./standard-notes-3.0.17-x86_64.AppImage 
[12481:1009/070559.004921:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_standa4zBh1H/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

Thanks,

Imad

**Comment by mobitar** [comment]
Please see here: https://github.com/standardnotes/forum/issues/690#issuecomment-531802728

**Comment by djmcwill** [comment]
Try:
./standard-notes-3.0.17-x86_64.AppImage --no-sandbox

**Comment by bikrambox** [comment]
> Hi guys, Please help.
> 
> when I try to run the AppImage from Debian GNU/Linux I got the following error.
> 
> imad@toshiba:~$ ./standard-notes-3.0.17-x86_64.AppImage
> [12481:1009/070559.004921:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_standa4zBh1H/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap
> 
> Thanks,
> 
> Imad

sudo chown root node_modules/electron/dist/chrome-sandbox && sudo chmod 4755 node_modules/electron/dist/chrome-sandbox



This worked for me!
