### ISSUE TITLE
Ideas for note links / backlinks

### ISSUE THREAD

**Issue by eode** [standardnotes/forum#723]
This is my ideal for note links, but could stand as a general area for discussion regarding note links.

- Linking should be easy
- Linking should be unintrusive
- Linking should be trackable

Towards that end, these are my thoughts:

- Requirements (for my needs)
  - Any note title typed exactly becomes linked to that note in a 'greedy' fashion -- I.e., the longest note title that matches is the match.
  - Any note that is linked to has a list of back-links
  - Link renaming -- if a note title is renamed, there's an option to automatically rename all links.
- Niceties
  - Capitalization is ignored
  - Perhaps a configuration option "Link to Note Titles" that disables linking if unchecked
  - Any link can be long-pressed to be "unlinked" (unstyled, doesn't get followed) (in reality, still tracked, but ignored)
  - A "make links" checkbox after the note title - causes it to default to 'unlinked'.

On the back-end, this can be done quite a few ways -- either as embedded but hidden text, or as a separate "Note -- Links", "Note 2 -- Links" documents.  One simple way would be to have tags embedded in the notes -- but they would have to be parsed for actually viewing the note.  I'm not sure how your underlying structure works.

**Comment by mobitar** [comment]
Thanks for the feedback! Will keep these ideas in mind as we explore linking in the future.

**Comment by eode** [comment]
Awesome.   You really have a great app, and your cross-platform support is
amazing.

**Comment by roaet** [comment]
I would love note linking

**Comment by pmagdon** [comment]
As an evernote user trying to switch to a company which values privacy I just signed up for the extended version of the standard notes app. However, shortly after importing some of my notes I realized that there is no functionality for linking notes. Compared to the old paper notes I used this was one of the major advantages of having digital notebooks. Thus, I strongly support the idea of implementing at least a basic function to link notes.

**Comment by varian93** [comment]
Internal links could be converted to standard markdown links on the fly to help maintain longevity.

**Comment by JaspalSuri** [comment]
Thanks for the feedback, everyone. I can't promise anything, but I've made I will record it in a way that is easier for the developers to reference (and I'm not saying that Mo didn't already do that; our toolset is changing as our team grows).

**Comment by virtuallyvlad** [comment]
There's a larger conversation on this at https://github.com/standardnotes/forum/issues/324

**Comment by effieeee** [comment]
As mentioned, larger conversation is in here: https://github.com/standardnotes/forum/issues/324
