### ISSUE TITLE
Top Menu question

### ISSUE THREAD

**Issue by mild0d** [standardnotes/forum#728]
I was messing around with the menu setting at the top left of the app.  I changed a setting and can't figure out how to set it back to defaults to where the menu drops down, I have no menu now.  I searched around, but at the moment, I am unsure what even to call this menu.  What do I do to set it back to defaults?  I want to install the new update.

**Comment by mobitar** [comment]
What setting did you change? You can press Alt + M to toggle hiding, and if you want to change between themed menu bar vs system menu bar, you can choose that option in the View menu.

**Comment by mild0d** [comment]
Thank you, I knew there was a key combination I was missing.  I Couldn't figure out what it was.  Its working fine now.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
