### ISSUE TITLE
Can not pay subscription

### ISSUE THREAD

**Issue by ChesterCode** [standardnotes/forum#73]
I can not buy a subscription to Extended
 
1. Go to https://dashboard.standardnotes.org/
2. Enter "ChesterLife@yandex.ru" in the field "already member"
3. Turn to "Standard Notes Extended Login Link" from the received letter
4. Click on "Your subscription has expired." Click to renew."
5. Choose the plan and press "Renew"
6. Enter the data of my debit card
7. Click "Pay"
8. The "Pay" button turns green and ... nothing happens

What am I doing wrong? :(

**Comment by mobitar** [comment]
Hmm..I just tested this flow and it works for me. Can you try using a different browser perhaps? Which one are you using now?

**Comment by mobitar** [comment]
Another user had this same issue and reported that disabling his ad blocker fixed the issue (he had uBlock Origin). Not sure what's tripping the ad blocker.

**Comment by mobitar** [comment]
Ok, I installed uBlock Origin and was able to replicate and fix the issue. You should be able to check out now with no problem even with a stringent ad blocker.

**Comment by ChesterCode** [comment]
You were right. Adguard AdBloсker did not allow me to make a payment. It is a pity that I myself did not guess it. This is the second time in my life when an adblocker does worse. Thank you. Subscription is processed.
