### ISSUE TITLE
Not shown 'Extension' at the left corner

### ISSUE THREAD

**Issue by mzch** [standardnotes/forum#730]
Hi,

I installed standardnotes, but 'Extension' button isn't shown.

![FireShot_Capture_009](https://user-images.githubusercontent.com/621178/66887656-9d44f680-f016-11e9-9c4f-4249dfeb8b76.png)

Please tell me how to fix this issue.

**Comment by mzch** [comment]
Yes ,but I reloaded the app many times, but it hasn't appeared...

**Comment by mobitar** [comment]
Is this self-hosted? Or the official app? What platform?

**Comment by mzch** [comment]
Oh, self-hosted. On Debian GNU/Linux 10.1 (buster).

**Comment by mobitar** [comment]
Read the "Extensions Manager and Batch Manager" instructions here: https://github.com/standardnotes/web/blob/master/README.md

**Comment by mzch** [comment]
Thanks, added them, the button came to be shown.
But trying to import an extension, no confirmation dialog shows when pressing enter.
Do you think what the matter is?

**Comment by mzch** [comment]
It seems to be blocked by the browser...

![FireShot_Capture_010](https://user-images.githubusercontent.com/621178/66949797-1afa1800-f092-11e9-81df-f36cee98752a.jpg)

**Comment by mzch** [comment]
Hi, Since I moved extensions from ext.domain.com to domain.com/ext, all issues have been fixed,
Thanks!
