### ISSUE TITLE
[Feature Request] Free dark theme

### ISSUE THREAD

**Issue by sadahadim** [standardnotes/forum#732]
Free dark theme would encourage people to change their note apps to Standard Notes and expose them to your paid features, therefore increasing the chance of them giving money to you. Isn't it what you want? More users, more profit with one simple change.

**Comment by jbeldia** [comment]
I'm not sure if that would really entice people to get Extended...actually, I think that having features like that for free would do the exact opposite: it gives people one less reason to pay for Extended,

The "Extensions" option is still present in the lower left portion of the UI in the free version anyway, and it links people to the list of Extensions and themes you can get with an Extended account, so I think that's good enough exposure. When they do visit the link, each extension also comes with an option to try it out on a dummy account on the Web app.

**Comment by zedgoat** [comment]
Think the core incentive is "free, open-source e2ee notes application". Easy to underestimate that its a huge deal to have that for no cost, compare to other free offerings where you're getting data-mined or under common-key encryption by the vendor.

Nearly everything in Extended is in the category of "nice to have" features - e.g., @mobitar seems genuine about not scumming people for cash by making the core product crap and hiding stuff behind a sub.

**Comment by aaantoszek** [comment]
Oh come on. Standard Notes is not about more users & more profit at all. It's about making an excellent, long-lasting product. If you can't afford Extended at it's current price, check this out: https://standardnotes.org/help/56/what-if-i-can-t-afford-the-price-of-extended

**Comment by Verder** [comment]
> Oh come on. Standard Notes is not about more users & more profit at all. It's about making an excellent, long-lasting product. If you can't afford Extended at it's current price, check this out: https://standardnotes.org/help/56/what-if-i-can-t-afford-the-price-of-extended

The thing that pisses me off is this "software as a service" thinking. Why should I pay every month for software? Companies that make software on Google Play, they offer their products in "buy-once" model and it works. It is really annoying to pay another 150$ after 5 years, just because..

**Comment by zedgoat** [comment]
Can go both ways. Author takes a big chunk of cash up front and loses interest, you're stuck. This model you can sub month-to-month then quit if things change.

In this case @mobitar  is very active both on product and in support / slack, money isn't going into a black hole or mega corp + provides sync infrastructure as a part of product.

YMMV, do what works for you. Boostnote, Notable, Typora, VSCode, many others are free and can be run on your own sync / encryption stack. Sublime has up-front charge + dark mode. If encryption not an issue there's thousands of free alternatives.

**Comment by mobitar** [comment]
Appreciate you all's input! Locking to avoid devolving into endless debate regarding a topic very well covered (and often heated) in many places on the web.

**Comment by TheodoreChu** [comment]
Closing this because v3.5+ of the mobile app comes with a free dark theme and there are plenty of community developed dark themes available for web and desktop that you can use for free
