### ISSUE TITLE
Cut or copy do not send content to clipboard

### ISSUE THREAD

**Issue by amashari** [standardnotes/forum#735]
On Lineage. No cutting/copying within notes or from notes to other apps. Always pasts the last thing sent to clipboard from other apps.

**Comment by mobitar** [comment]
So you press Copy on a text, but the text is not copied? Is this with the plain editor or another editor?

**Comment by amashari** [comment]
Correct. Plain editor. If I cut instead of copy the text disappears but I can't past it.
