### ISSUE TITLE
Theme not recalled after app exit and restart

### ISSUE THREAD

**Issue by iedd** [standardnotes/forum#736]
See screenshot for example. Clicking twice on the currently selected theme button will 'refresh' the theme correctly, or clicking once on another theme.
Signing out and clearing local data does not fix, uninstalling and re-installing themes does not fix. Windows 10, possibly happening on Ubuntu also. Started happening after most recent update a few days ago
![Capture](https://user-images.githubusercontent.com/6758177/67488482-ec55e180-f63d-11e9-95d6-243de2e8b821.PNG)

**Comment by iedd** [comment]
Started happening after most recent update a few days ago

**Comment by imagercaz** [comment]
Yes, this happens to me, but get a kind of half and half view on my Mac running 10.15.  The field where you type the text of a note is dark and the  tags area is white.  Glad it is a known issue and will be addressed.  I love your app, keep up the great work!

**Comment by iedd** [comment]
Seems to be fixed in 3.0.19. Thanks for all your efforts!
