### ISSUE TITLE
Cannot Reopen App from Tasklist in Windows

### ISSUE THREAD

**Issue by hillbilly3456avk** [standardnotes/forum#738]
With 3.0.18 on Win10 I always have to click twice to reopen SN when i minimized it before. By the first click it will come to the foreground for a glimpse but fades away immediately. The Symbol in the tasklist is blinking as it if SN would message me something. After the second click it will get the focus and come to foreground

**Comment by jbeldia** [comment]
This issue was also reported on before on v3.0.17, though it seems they're still looking into it

https://github.com/standardnotes/desktop/issues/409

**Comment by mobitar** [comment]
A known issue without a good fix yet.

**Comment by hillbilly3456avk** [comment]
Duplicate https://github.com/standardnotes/desktop/issues/409
