### ISSUE TITLE
Listed.to comment system?

### ISSUE THREAD

**Issue by spencerwooo** [standardnotes/forum#740]
Is it possible to integrate a 3rd-party comment system into Listed.to, below the post section? Such as [Disqus](https://disqus.com/) or [Gitalk](https://github.com/gitalk/gitalk)?

Also, is it possible to add HTML content directly into Listed.to? I know we can add custom CSS but I didn't see an option to add HTML anywhere. And as far as I know, it's not very elegant to add HTML using CSS.

**Comment by mobitar** [comment]
Listed is meant to be a personal space for authors, and not a way for other people to leave arbitrary comments on posts. Commenting on the internet is an unsolved problem, and not one we're eager to take on. Author-to-reader relationships are handled through the intimate space of email, where readers can reply-to post emails and they will go directly to the author.

You should be able to include HTML content without issue.

**Comment by spencerwooo** [comment]
Thank you for the clarification. I totally agree with getting rid of the comment system. ♥
