### ISSUE TITLE
Switching away-and-back-to the app causes it to lose focus and be hidden again

### ISSUE THREAD

**Issue by iedd** [standardnotes/forum#741]
Windows 10: Hiding the standard notes app behind another application, then clicking on the toolbar icon to make the app appear on the top level will quickly flash the icon orange and hide the app, requiring another click to show. May be related to:
https://github.com/standardnotes/forum/issues/736

**Comment by mobitar** [comment]
Known issue: https://github.com/standardnotes/desktop/issues/409

**Comment by iedd** [comment]
Ah, thanks for the update and all your hard work. It is much appreciated!
