### ISSUE TITLE
Folders and Tags disappear in web app when Folders extension is enabled

### ISSUE THREAD

**Issue by Coolbeans-42** [standardnotes/forum#743]
Hi I just started using Extended and when I open up the web app folders and tags show up for a moment and disappear. There is just a blank space left of "all notes" column. Also this happens when I activate Folders extenstion. When I disable it, tags come right back. I tried disabling my addons on Firefox that make changes on a web page like ublock origin, and privacy badger but it didn't work. Anyone has this problem or know a way I can fix it? Thanks.

![Screenshot from 2019-10-29 11-00-50](https://user-images.githubusercontent.com/51943240/67748277-974e0d00-fa3b-11e9-933a-0819fd3f3d12.png)

**Comment by mobitar** [comment]
Does this happen with other browsers, or with the desktop app?

**Comment by Coolbeans-42** [comment]
No, it doesn't happen on other browsers (I tested on two) or on the desktop app.

**Comment by Coolbeans-42** [comment]
Edit: I found the culprit. Oddly enough it was the add-on Honey! When I disabled it, folders just came back! That's is quite unexpected for me so I would like to know why it causes this just out of curiosity.

**Comment by mobitar** [comment]
No idea, I'd check out the console to see if it says anything.
