### ISSUE TITLE
Password Restrictions

### ISSUE THREAD

**Issue by workmanlike** [standardnotes/forum#744]
Hi,

Just wondering what the password restrictions are on the Standard Notes account and if you get a warning if you try to enter a password that isn't allowed (for example if it is too long or contains unsupported characters)

Thanks

**Comment by mobitar** [comment]
The only restriction is a minimum length of 8 characters.

**Comment by workmanlike** [comment]
Great, thanks. 

Just to confirm, any characters, including spaces are allowed?
