### ISSUE TITLE
Simple task editor: multiple selection and deletion

### ISSUE THREAD

**Issue by HitchRait** [standardnotes/forum#749]
After I have made several tasks in Simple task editor (linux desktop and android app):
1) I cant select text of several or all of them - it allows selection of text only within one task.
2) If I want to delete a task the only way is to mark it as done. If I want to delete it completely I can delete text, but unable to delete the checkbox.

**Comment by mobitar** [comment]
1 is intended behavior. To delete a task, delete all its text, then press enter.
