### ISSUE TITLE
Untagged notes

### ISSUE THREAD

**Issue by thedaveCA** [standardnotes/forum#75]
As someone who uses tags extensively, I'd like to see a feature to find all notes without tags. One option would be to have a virtual "Untagged" tag that would dynamically apply to any note that isn't otherwise tagged.

I use this essentially as a "todo" for items created on the go, often from mobile. Typically the action is just a tag being assigned, although sometimes the note gets transferred out to a more permanent home. To some extent a "Default tag" feature would work too, but finding notes which is untagged has other use cases which aren't fully addressed by a default tag as a default tag can be removed.

**Comment by mobitar** [comment]
I've thought about this before too, and I think it could be a useful feature. I've made a note to do some investigatory work and see how much effort is involved. I like simple changes, but tend to put off any complex changes :) This one seems simple, but you never know.

**Comment by virtualvlad** [comment]
+1

And for the UI, it would make sense to have something like "Untagged" if you have "All".

**Comment by MorgothSauron** [comment]
+1 for a way to see 'untagged' notes

**Comment by virtuallyvlad** [comment]
Wanted to follow up given the addition of Smart Tags in 2.3.0.  While this request is now technically possible, it requires you to create the "untagged" smart tag yourself (provided you know the syntax to do so).

When I read the original request, I pictured this being a part of the tags panel by default, preferably even in the core app (without needing an extension).  To me it seems like a basic part of tagging, just as the "All" option is included by default in the tags panel.

**Comment by mobitar** [comment]
Standard Notes "basic" is already complete. We won't be adding much new features there. Any new feature will be an extension. So untagged being part of Smart Tags is inline with the philosophy. Everyone has their own definition for what qualifies as "core", it turns out.

**Comment by MorgothSauron** [comment]
I thought that it would be a "tag" like "Archived". Well, I'll switched to folder view to check for untagged notes than switch back to normal tag view.

**Comment by virtuallyvlad** [comment]
> Standard Notes "basic" is already complete. We won't be adding much new features there. Any new feature will be an extension. So untagged being part of Smart Tags is inline with the philosophy. Everyone has their own definition for what qualifies as "core", it turns out.

Ha, looks like [it actually did end up in "core"](https://github.com/standardnotes/desktop/releases/tag/v3.12.0).  I always did think it belonged in that panel by default.  Thanks for adding.  :+1:
