### ISSUE TITLE
FileSafe "Attach File" button / multiple file upload

### ISSUE THREAD

**Issue by HitchRait** [standardnotes/forum#753]
Desktop. When I need to attach ~50 files to different notes there is a small inconvinience - jumping left and right "Attach file" button in FileSafe extenesion. It happens because of file uploading status that appears and moves the button to the right. It doesn't feel comfortable when you need to click fast (and opening other file menu instead of attach button) to upload multiple files. So, that would be great to (1) implement multiple file upload or at least (2) make button keep it's place and let upload status appear somewhere else.

**Comment by jbeldia** [comment]
You can upload multiple files without using the attach file button by dragging the files directly onto the File Safe extension window! :)
