### ISSUE TITLE
Load pinned items first

### ISSUE THREAD

**Issue by dietervds** [standardnotes/forum#759]
The issue I run in to with SN the most, is waiting for my >2000 notes to complete the load/sync cycle on my iPhone. I understand though that there's not much one can do about that.

However, it might be mitigated a bit by getting pinned notes loaded and synced first?  
It would greatly decrease the number of times I have conflicted copies, when I start writing something before it's fully synced :-)

(Also: maybe indicating that the note hasn't been synced yet might be helpful to).

Thanks for the incredible work and product Mobitar!

**Comment by mobitar** [comment]
We don't really know if an item is pinned until it is decrypted, so we have to wait for everything to finish loading. We do load items by most recently modified first however. Not a bad idea to indicate that the initial sync hasn't completed yet when you're editing a note. Generally if on desktop you can view this status on the bottom of the app.

**Comment by dietervds** [comment]
That makes sense, thanks!

Do you want me to create a separate item for the syncing-indication on mobile, for easier tracking?

**Comment by mobitar** [comment]
Yes sure!

**Comment by dietervds** [comment]
Done! https://github.com/standardnotes/forum/issues/779

Cheers!
