### ISSUE TITLE
How to create an editor?

### ISSUE THREAD

**Issue by kslstn** [standardnotes/forum#76]
I'm considering creating my own editor based on the default one. I could change the default source code, but I'd expect adding a new editor would be a cleaner way to do this. Is there any documentation on how to create an editor?

**Comment by mobitar** [comment]
Actually there was documentation on the old forum, but I never transferred it over. Here it is:

Building an editor for Standard Notes is pretty straightforward. An editor is basically an iframe that communicates with the main Standard Notes app using the [PostMessage API]().

## Guide

1. Create a simple textarea in HTML:

```
<textarea id='editor'></textarea>
```

2. Notify the parent window (Standard Notes) that we are ready to receive messages:

```
// When testing locally, we sometimes open the editor directly in the browser rather than through being embedded in SN
// We only want to post a message if we detect that we are embedded

if(window.parent != window) {
	window.parent.postMessage({status: "ready"}, '*');
}
```

3. Standard Notes will then send you a message back with the note's ID and initial content. Listen for this message by adding an event listener to your window:

```
  window.addEventListener("message", function(event){
    window.noteId = event.data.id;
		editor.value = event.data.text;
  }, false);
```

4. Add an event listener for when the text changes:

```
var editor = document.getElementById("editor");
editor.addEventListener("input", function() {
	// notify the parent of text change
})
```

5. Inside the event listener, tell the parent of the text change:

```
var text = editor.value;

if(window.parent != window) {
	window.parent.postMessage({text: text, id: noteId}, '*');
}
```

And that's it! Standard Notes will autosave the new data when it receives it. Your editor only needs to worry about sending updated text to the parent. This text can be in any format, whether it's HTML, Markdown, Plaintext, LaTeX, etc.

See the [Simple Markdown Editor](https://github.com/standardnotes/extensions-server/blob/master/app/assets/javascripts/editors/simple_markdown.js) for an example.

**Comment by kslstn** [comment]
That is great, thank you! I assume you meant this post message API: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by mobitar** [comment]
Yup, thanks!

**Comment by raritet** [comment]
@mobitar how about if I want to try to fix perceived problems with an existing editor? I'd like to copy the code of the Minimal Markdown editor and see if I can make it do things a little differently (maybe even as simple as CSS adjustments). Is there a tutorial or some notes around on how to do this? I assume I'd need to get that code and somehow package it as a new extension and give it permission to run on my notes.

**Comment by mobitar** [comment]
Check out the code for the Minimal Markdown Editor: https://github.com/sn-extensions/minimal-markdown-editor

Should be pretty straightforward if you want to fork it and try out some changes.

You can run it locally with `python -m SimpleHTTPServer 8080`

**Comment by mobitar** [comment]
Also, updated docs available here: https://docs.standardnotes.org
