### ISSUE TITLE
Sort By Title

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#760]
Hi:

I like to use the sort by title option but when I use numbers like 1., 2., 3. etc., the number 10 jumps next to number 1., so that the notes are not in order. Could you make it so that the sort by title option also includes numbers?

Also, could you make it so that the sorting option is specific to the particular tag you're in? In some cases, like when taking notes of a book, I like to sort by title but in other cases I like to sort by date added. It'd be helpful if the sorting option was not global. Thanks.

**Comment by TheodoreChu** [comment]
Closing this because sort by title is available: https://app.standardnotes.org
