### ISSUE TITLE
 Kendo excel export throw an exception of "ERROR TypeError: Buffer.isBuffer is not a function"

### ISSUE THREAD

**Issue by AlaaFK** [standardnotes/forum#761]
I need to export grid data to excel sheet. Im using kendo-grid and I followed this link with same data
https://www.telerik.com/kendo-angular-ui/components/grid/export/excel-export/
and then I tried to only export data like the following link
https://www.telerik.com/kendo-angular-ui/components/excelexport/

but both are throwing error at some point about buffering:
ERROR TypeError: Buffer.isBuffer is not a function

No clue of the problem.

**Comment by TheodoreChu** [comment]
It looks like this issue has since been resolved. Please comment if you continue to have issues
