### ISSUE TITLE
Windows 10 Window Focusing Bug

### ISSUE THREAD

**Issue by fractal-mind** [standardnotes/forum#766]
For the past three versions (3.019, .018, and before that), if I want to bring back the focus to Standard Notes, I have to click the icon (or alt-tab switch) one time, let it flash on the screen then disappear, then I have to click or alt-tab switch one more time so the app come into focus and I can interact with it. 

(Win 10 environment)

**Comment by jbeldia** [comment]
They're currently working on a fix for this, hopefully it will be rolled out soon!

https://github.com/standardnotes/desktop/issues/409

**Comment by aaantoszek** [comment]
@fractal-mind it's been fixed with 3.0.21
