### ISSUE TITLE
Automatic Updates: Ask on new update

### ISSUE THREAD

**Issue by dreamflasher** [standardnotes/forum#767]
Currently one still has to look in the update menu to see if there is a new update. It would be great to see the "There is a new update, do you want to update now or later" dialogue box as soon as there is an update found. 
Bonus points: If the app does not have focus, simply install the new update, without asking.

**Comment by mobitar** [comment]
You should see "New update available." in the bottom right corner of the app if one is available.

**Comment by dreamflasher** [comment]
Not reliably. But I actually would prefer an automatic update, as described in the second point.

**Comment by mobitar** [comment]
It already auto-installs when you quit the app.

**Comment by dreamflasher** [comment]
Ah, I didn't notice, because I never quit the app :D
