### ISSUE TITLE
[Feature Request] Save scroll position in editors

### ISSUE THREAD

**Issue by dreamflasher** [standardnotes/forum#768]
It would be great if the current scroll position would be saved and on reopening a note, be restored.

**Comment by bschlagel** [comment]
Agree, this would be super useful. Currently very hard to go between multiple (even just two) long-ish notes when you have to re-find your previous position in the note every time.

Discussed here as well: https://github.com/standardnotes/forum/issues/276

Sounds like it might be a lot of work to implement for all editors. But even if it worked only for the plaintext editor, that could be a good start!

**Comment by dreamflasher** [comment]
I agree it doesn't need to work for all editors at once. But it actually looks relatively easy to implement to me. Getting the scroll position and setting the scroll position is trivial with JS. I'm pretty sure one has access to the DOM in electron? Then it just needs to be saved, and the dataformat has metadata right?

**Comment by dreamflasher** [comment]
@mobitar can you mark this as duplicate of #276?
