### ISSUE TITLE
[Kubuntu] Not asking to integrate with desktop

### ISSUE THREAD

**Issue by andrewrothman** [standardnotes/forum#769]
Hi there,

After opening Standard Notes on a Kubuntu install (KDE) I am not prompted to integrate with the desktop.

This has worked for me before, but it recently stopped showing up in my app launcher. After deleting and reinstalling the app, I am not prompted.

This is quite an annoyance, as I have to open my file browser and navigate to the AppImage to open the program. I could setup an entry in my launcher manually, but it stops working when Standard Notes is updated and the filename of the AppImage changes with the new version number.

Thanks for all the hard work on Standard Notes,
Andrew

**Comment by jbeldia** [comment]
Hi, they've managed to identify the issue and find some workarounds for this, see this post:

https://github.com/standardnotes/desktop/issues/430

**Comment by andrewrothman** [comment]
@jbeldia Installed AppImageLauncher and it worked again. Thanks!
