### ISSUE TITLE
Standard Notes Linux client as Snap or Flatpak

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#77]
When I recommend Standard Notes to (some) people the first thing they says is "Electron". I personally don't mind electron apps, though I do prefer native/ snap or flatpak apps. Maybe switching to snap / flatpak will bring in more user.

**Comment by mobitar** [comment]
Electron is great! https://journal.standardnotes.org/in-defense-of-electron-e7d5b5229b70

**Comment by ClarkeCC** [comment]
@mobitar I see your point of view and again I personally don't mind Electron, but still prefer native/ snap or flatpak apps. Great article!

**Comment by M-Pixel** [comment]
I dislike Electron as well, but I don't think it's worth arguing that since it's pretty clear that the developer is dedicated to it at this point.

That aside, there's a false equivalency being argued here. There are plenty of Electron-powered Snaps and FlatPaks. Snap/FlatPak are alternatives to an _AppImage download link_. I would love to be able to install Standard Notes by running `snap install standard-notes`, and know that it will always be kept up to date.

Knowing, however, how easy it is to download a new AppImage to `/opt/`, and how much effort and ongoing maintenance would need to go into setting up a Snap deployment pipeline, I'd prefer that the developer focus on features and optimizations before working on a Snap. Because of that, I'm holding off on `+1`ing this feature request.

**Comment by mobitar** [comment]
I actually had looking into Snap on my todo after Slack added it for their app. You're saying it requires a lot of work and maintenance?

**Comment by M-Pixel** [comment]
I haven't deployed a Snap myself, yet, but from what I understand, you would need to...

Grok the Snap system, how to package, publish, install, troubleshoot. Then, either set up an automatic Snap deployment on push to master, or manually update Snap whenever app is updated (probably only a few minutes each, but it adds up). Snap is pretty young, so every several months, you'll need to make changes to the deployment process. Then there's a bit more ongoing overhead from additional bugs and issues coming in from users that are Snap-specific.

**Comment by mobitar** [comment]
Yikes, ok. Will do more research on that.

**Comment by VosaXalo** [comment]
More and more apps are coming to the snap system.
It seems that the effort to port standard-notes to snap will pay after all :-)
Anyway, the Appimage solution is valid too.

**Comment by mobitar** [comment]
It's mostly a matter of reducing development and deployment friction. AppImage so far has been entirely frictionless, but of course, is not perfectly ideal for every user scenario.

**Comment by popey** [comment]
@mobitar Hi! I work on snapcraft and snaps. I've recently switched to Standard Notes as my primary note taking app. It's <3. Thank you! 
I'd love for there to be an automatically updated snap of standard notes in the snap store, and would be happy to help you get that working. We've worked with a ton of electron app developers to get their applications snapped. You can probably spot a few familiar names in the [store](https://snapcraft.io/store) :). 

It's essentially a one-line change to your package.json to add snap support. I blogged about it [here](https://snapcraft.io/blog/bringing-electron-applications-to-linux). You can then start building and publishing directly to the store. Once it's in the store and the store page [looks great](https://snapcraft.io/blog/make-your-snap-store-page-pop) we can start promoting it via our social channels and featuring it in the store.

Do let me know if I can help at all!

**Comment by mobitar** [comment]
Thanks for the heads up @popey! Didn't realize electron-builder made this so easy. I'll add this to my queue to look into further and will update this thread with progress.

**Comment by jspaetzel** [comment]
I just tried the snap https://snapcraft.io/standard-notes and it works great, better then the AppImage for me. Thanks!

**Comment by teedeeus** [comment]
Thank you for creating a snap for my favorite note app!  So much better than appimage.

Thank you!
