### ISSUE TITLE
sync unreachable

### ISSUE THREAD

**Issue by modefier2** [standardnotes/forum#770]
I tried signing out and signing in, sync was unreachable on android and desktop (mac) versions, still not working. temporary? configuration issue? thx!

**Comment by makarandh** [comment]
I too am facing the same issue - sync unreachable. 

Standard Notes version 3.0.21
OS: Kubuntu 18.0.4
Error mesage: 500 Internal Server Error

Also facing this issue on Android
Error message: TypeError: undefined is not an object (evaluating 'n.saved_items.map')

**Comment by modefier2** [comment]
Weird on Android it worked for me to sign out and then sign in again (tho I think you lose what you added in the meantime). On desktop I get 500 internal server error (can't copy-paste for some reason tho). I'm on 3.0.21.

**Comment by Cito** [comment]
Same problem here. Seems to be a problem with the sync service.

**Comment by oliversturm** [comment]
Ah! I'm a new user and I was just trying to sync to a second machine for the first time and encountered this error. Hopefully that issue will be fixed soon! It works just fine for me on Android...

**Comment by chanclr** [comment]
have this issue on Android, and on web.

**Comment by kamheric** [comment]
At that moment how i typed some text sync brokes. webapp says "Sync unreachable".
my android' app works, and i can see some part of those text. 
new log-in in web (in private mode) or another android device also says about errors:
" Issue syncing
There was an error while trying to save your items. Please contact support and share this message: TypeError: undefined is not an object (evaluating 'n.saved_items.map')

**Comment by wwfms** [comment]
having this sync issue on all 6 of my devices. took a few steps to reach resolve to no avail. i'm on windows, ios and android

**Comment by chanclr** [comment]
might add that in the year and a half i've used SN, this is the first time i've gotten an issue like this

**Comment by peterhunterdk** [comment]
![Untitled2](https://user-images.githubusercontent.com/57904952/69058091-4f575000-0a13-11ea-8870-39e306ffb7a6.png)


this is my sync message - im having troubles too...

**Comment by mtnwatchdog** [comment]
Ditto - same here - still happening 6:25am PST

**Comment by DBCerigo** [comment]
Confirming that I also get `Error message: TypeError: undefined is not an object (evaluating 'n.saved_items.map')` on Safari v13.0.2. Plus numerous other errors in the browser Console when attempting to sync.

**Comment by bgbarcus** [comment]
Logout/Login did not work for me.  When I logged back in the app was unable to sync leaving me unable to get to existing notes until this issue is fixed.

**Comment by aaantoszek** [comment]
Was down for about 2 hrs for me. Back now

**Comment by JulBor25** [comment]
Back online.

**Comment by mobitar** [comment]
Should be back now. Sorry about that.

**Comment by aslom** [comment]
@mobitar are you going to do RCA? ois there webpage for standardnotes with current status and outages history?

**Comment by NipponBill** [comment]
Looks like the issue has returned
> Sync Unreachable
Hmm...we can't seem to sync your account. The reason: Could not connect to server.
Need help?

I cannot sync from Linux or Win10 desktop, the web app on any browser, or the Android client. Logging out and back in doesn't seem to help.

**Comment by aaantoszek** [comment]
@NipponBill works fine for me. Linux, web & Android

**Comment by bryvin** [comment]
@NipponBill We haven't received any other reports from users regarding sync issues; would you mind trying to visit: https://sync.standardnotes.org

Does this page load for you without issue? Can you also try to use cellular data instead of a WiFi signal and verify that you are still unable to sync?

**Comment by NipponBill** [comment]
Apparently I had some notes that were too large. I'm trying to identify and remove / alter them.

**Comment by tmoravec** [comment]
> Apparently I had some notes that were too large. I'm trying to identify and remove / alter them.

This is a pretty important information (I have some pretty large notes, too). Would you mind opening a new issue for this? With details you find on the size limits? Thank you!

**Comment by NipponBill** [comment]
The **StandardNotes** help people were able to assist me to identify the specific major offenders after I sent them an error screenshot. Removing these has allowed me to sync again.

From the app I downloaded a decrypted backup. In the resulting ZIP file I had to look up some specific note codes. I found the titles of the offending notes, then I had to delete the note contents, before sending the notes to the Trash. After doing that the Sync started functioning again.

It was due to large FileSafe attachments from the looks of it. I am not sure about the exact file size limits, but this is still affecting me in terms of the **CloudLink** extension. I am not able to backup to Google or DropBox, so I likely have more cleanup of large file attachments to do.

**Comment by milynot** [comment]
I also have Sync Unreachable issue.  How did you guys solve this?

**Comment by JaspalSuri** [comment]
Hi @milynot,

Is it still unreachable? If so, please try signing out and back in to see if that resolves the issue. If not, please let me know!

**Comment by NamesNetworkNic** [comment]
I still have this problem (Android 11, Standard Notes 3.9.3, F-Droid).

Has a solution been found yet?

I've been using Standard Notes primarily on my phone recently so I didn't notice until quite recently, and I don't want to sign out and lose a bunch of data if it turns out to not be a long-term solution.

xo - Nicolete Lovejoy
