### ISSUE TITLE
iOS local/offline mode not possible anymore?

### ISSUE THREAD

**Issue by markopy** [standardnotes/forum#772]
I have been using Standard Notes on iOS with only a local password for encryption and no syncing. This has been working fine and without problems.

After trying to install the app on a new device I wasn't able to set this up anymore though. The initial splash screen seems to require login in or signing up with an email address and server.

Is there some trick to bypass the splash screen so I can set up a local password in the settings? If not, can this option be added please?

**Comment by markopy** [comment]
I understand that you don't want people to lose their data and this can't be the default but removing the option entirely seems a bit extreme. Losing data on an iOS upgrade wouldn't be a big deal for me and a tradeoff I can accept for not having my data synced to a server.

I'm not entirely clear what change you made though. If I sign up with an account to get into the app settings, can I still enable local encryption and then unlink from the account again so no sync happens?

**Comment by mobitar** [comment]
> Losing data on an iOS upgrade wouldn't be a big deal for me and a tradeoff I can accept for not having my data synced to a server.

Many casual users who install our app will begin taking notes right away with the assumption that their data is somehow backed up. They don't even think about it.

We may relax these measures in a future update, but we'd need to do it in a way that properly educates the user on their responsibility. The splash screen is a quick fix to prevent any further damage until we can nail a solid educational foundation.

> and then unlink from the account again so no sync happens?

This isn't possible.

**Comment by markopy** [comment]
That's disappointing but thanks for taking the time to explain!

**Comment by DaringDreams** [comment]
Up until recently been able to create unencrypted notes on Standard Notes without an account. According to Standard Notes FAQ:

> Standard Notes can be used totally offline without an account, and without an internet connection.
> - https://standardnotes.org/help/59/can-i-use-standard-notes-totally-offline 

The beauty of Standard Notes over Evernote was the fact that you didn't have an external dependency. A good compromise would be from the splash screen in the advanced link opening an option called "Use Offline at your own risk. OS Updates can potentially delete all device notes".

I manually create backups and travel to places outside of cell reception even with the best cell carrier. Being able to take notes while traveling is extremely valable, Standard Notes was the perfect app for this while being extremely flexible (Android to Linux exports). I understand why more advocation for having to login is in place, but removing the offline option altogether seems a bit extreme.

**Comment by mobitar** [comment]
Yup, was thinking the same. We want to create an advanced mode where users will need to confirm the risks. It's just a matter of building it in.

**Comment by DaringDreams** [comment]
Thank you, extremely happy to hear about interest in having a prompt to proceed.

**Comment by TheodoreChu** [comment]
Closing this because local/offline mode is available on the latest versions (v3.5+) of the iOS app with the warning "Data not backed up. Sign in or register to backup notes" in the home screen
