### ISSUE TITLE
[Mac] 3.0.21 still won't open on Catalina

### ISSUE THREAD

**Issue by trevormeier** [standardnotes/forum#773]
1. Download 3.0.21 Mac release .zip file
2. Uncompress, move to Applications folder
3. Double click and/or right click -> open
4. App can't be opened

Works fine with the DMG download.

**Comment by mobitar** [comment]
I'll need to investigate. You should be downloading the .dmg though. That's the default download from our website.

**Comment by trevormeier** [comment]
I wasn't sure which one to download, good to know. I usually come straight to the GitHub page from the link inside Standard Notes because the "auto update" feature hasn't been working since about 3.0.16 or so

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
