### ISSUE TITLE
[Feature Request] Login notifications/ability to see login IPs

### ISSUE THREAD

**Issue by half0wl** [standardnotes/forum#776]
For security purposes, it would be great if we could be notified when an account is logged in from a different device/IP than usual, or if there are various attempted logins from a single IP - basically an audit log of attempted logins.

**Comment by mobitar** [comment]
We might do this in the future, potentially as an opt-in feature. It would require us to store and email IP addresses, which is not something we presently do.

**Comment by effieeee** [comment]
There is now a login notification feature, though we still do not track IPs.
