### ISSUE TITLE
[Feature Request] I want to know how many notes are in the folder

### ISSUE THREAD

**Issue by browneyedsoul** [standardnotes/forum#778]
<img width="247" alt="Screen Shot 2019-11-22 at 3 43 33 PM" src="https://user-images.githubusercontent.com/56161102/69403820-ec312a80-0d3e-11ea-9a7e-87fd3a32fdb1.png">
<img width="201" alt="Screen Shot 2019-11-22 at 3 43 58 PM" src="https://user-images.githubusercontent.com/56161102/69403828-f18e7500-0d3e-11ea-8585-d043f34169f7.png">

In evernote this feature exist in the desktop version
but standard notes doesn`t have this
If this applied to S.N. it would be much better in seeing at a glance all notes

Regrards

**Comment by browneyedsoul** [comment]
> the

**Comment by mobitar** [comment]
We have this in the core tags view, but not in the Folders extension. However we'll be making modifications here as part of our next major release (not yet begun).

**Comment by MustachedMario** [comment]
> We have this in the core tags view, but not in the Folders extension.

As reported, this also doesn't work, they don't show up, until you restart the desktop app 100 times, or refesh the browser by hammering F5.

**Comment by trey-wallis** [comment]
Sometimes I space on which notes I put where, and for searching, it would be nice to know how many notes were in each folder.

Please continue to work on this.

**Comment by JaspalSuri** [comment]
Hey @trey-wallis! Thanks for supporting us with [Extended](https://standardnotes.org/extensions). I'll pass your feedback along to the team.

**Comment by effieeee** [comment]
Note count now visible even with Folders (new native folders component
