### ISSUE TITLE
Indicate sync status per note

### ISSUE THREAD

**Issue by dietervds** [standardnotes/forum#779]
Particularly on mobile, this would be useful to prevent the user from editing a note before it is fully synced, and causing conflicting copies as a result. 

Thanks!

**Comment by mds08011** [comment]
I would definitely welcome this feature.  I periodically edit unsynced notes while my cell phone is switching internet connections (i.e. WiFi to cellular while leaving a building) and end up with conflicting copies.

**Comment by effieeee** [comment]
Should be less of an issue after we unified the web and mobile apps!
