### ISSUE TITLE
LateX Support??

### ISSUE THREAD

**Issue by Hedronmx** [standardnotes/forum#78]
Is it possible to add LateX support?? Thanks!

**Comment by mobitar** [comment]
I think it would be possible to create a LaTeX editor. I'll need to find an open-source web/JavaScript implementation. If you know of one, let me know!

**Comment by mobitar** [comment]
Thanks! Will take a look at what it takes to build this when I get the chance.

**Comment by Hedronmx** [comment]
Thanks! Also, how can I create my own themes??

**Comment by mobitar** [comment]
Please take a look at the one of the existing themes and just modify them. You can then use Dropbox or a similar service to generate a URL to it and paste it in the Extensions section of the app.

**Comment by mobitar** [comment]
Btw we have this now under the Markdown Math editor :)
