### ISSUE TITLE
Small SN experiment / bad usablility

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/forum#780]
I stopped using SN around 6 month ago, because of tons of problems and bad usability. In it's current state, SN is absloute useless for me, but I follow the development of SN. Because SN is useless to me, this doesn't mean it's also useless to others.
As an IT-Professional, I'am often in a situation to recommend a software/service for problem x,y,z. So I also recommend SN, but never ever seen people using SN for a longer period.

**So I started a small experiment and I'm surprised, they have nearly the same Problems with SN as I has:**

- I share my account with extensions enabled to a small group of 12 people.

- Everyone has excatly 7 days access to the account to play with.

- The 12 people was split in 4 IT-Professional, 4 IT related coworker and 4 friend of mine, without any IT experience.

- I told my 4 friends that I create a privacy notetaking service and they should test my software before it goes live (later I told them that was only an experment and I'm not creating SN), because this is the only way they really using SN in this time.

- 2 of the IT-Professionls was already using the free plan of SN, so they have now access to extended.

- I showed all of them how to use SN, also the MOBILE APP, WEB, DESKTOP APP, and how to use extensions.

**Results:**
- All of them love the clean look (at leaset no one hates it), the idea behind, and the way how you can add additional stuff like editors, themes, functionality.

- They surprisingly also willing to pay for such a service. For 11 people the monthly maximum is around 3$, 1 is willing to pay "as much as it costs".

- All of them don't use the desktop any longer as a maximum of 2 days. They all stick to WEB and the MOBILE APPS. The non-techy user says the desktop app take ages to load or it feels laggy, some also says that the desktop app won't run on workplace (no proxy support). The techy says, "another electron based junk with no proxy support". I told the non-techy people, they can use the WEB Version instead.

- The non-techy user tends to add editors like bold, simple task, plus, spreadsheet, tokenvault, all themes. The techy ones markdown, vim, tokenvault, one darker theme.

- The non-techy user tends to add images to some notes and I show them how they can do this. But they feel uncomfortable with it. The techy user won't use images at all.

- So far so good, until they started using the mobile apps not as an "note-viewer", but as an "editor". Nearly all extensions won't work on mobile, because of tons of UI bugs, they are simple unuseable.

- All of them at this point started to reduce the installed extension, to get something done on the mobile side.

- So far so good, until they realized, that the mobile apps can't handle extensions offline. Non-techy only see "crippled" notes or can't access to amazon, because the tokenvault isn't working anymore. The techy user can handle this better, because there are able to read markdown or html tags. But they also have the "WTF, welcome to the 90's" moment in 2019.

- Both groups are pissed now, and realize that they can't do the same on desktop (with the webapp) and mobile.

- All of them started again to reduce their installed extensions, non-techy and some techy user using now only plaintext and themes, the other techy ones only markdown, no additional themes, because switching themes on mobile crashed often mobile app.

- At this point, 10 of 12 people using plaintext, 2 markdown. So far so good, they are happy now, they started formating plaintext with monofont and symbols like #,+,-,_ .... until they realize, that monofont doesn't exist on mobile. The next "WTF" moment.

- After 7 days, all users are pissed and ask themself, whats the point paying for such service, if all "extra i get is 2FA" compared to the free plan?

- Final Result: 10 people won't use SN anymore, because "2FA is to expensive", 2 continue the free plan as before this experiment.

**PLEASE DO SOMETHING ABOUT SN!**

**Comment by mobitar** [comment]
Lol, thanks for running this unofficial "experiment". For the record I've been running a similar experiment for the last three years, and my findings don't match up with yours. It's ok that this app isn't for you or your friends. And there isn't anything I can do overnight to make this perfect for you. Nonetheless, I'm not oblivious to where we can improve. All takes time.
