### ISSUE TITLE
Extensions break offline

### ISSUE THREAD

**Issue by gwynm** [standardnotes/forum#781]
It seems like, if you're offline, all your extensions silently fail to work (and it's not clear why).

I verified by going online and all my extensions started working again.

This is a very disconcerting experience (especially if the extension in question is a visual theme!).

I think the fix should be:

* "Licence validation", if necessary, should persist, spotify-style. Maybe go online every 3 or 6 months to keep extension access.

* If extensions are disabled due to inability to validate the licence, make the reason extremely obvious.

**Comment by mobitar** [comment]
Platform/OS/Version?

**Comment by gwynm** [comment]
If this isn't shallow / intended behaviour, I'll dig a bit deeper and do a proper bug report! :) This is 3.0.16 on Linux. Will attempt to repro properly tomorrow.

**Comment by SiGamma** [comment]
I‘m pretty sure it isn’t (there’s even a checkbox for offline use of some sort IIRC), mine work just fine offline, on macOS and Windows, though.

**Comment by gwynm** [comment]
Gotcha, this sounds like a me problem :).

**Comment by mobitar** [comment]
For the record, our most recent update migrated offline extensions to using a local server on a local port (instead of using file:// paths). So it might be a firewall issue..

**Comment by eaxillaris** [comment]
Excuse me for turning over a mossy log, but should extensions work offline with the current Android app?
I'm finding that they do not, at least with version 3.5.10 (3000254) on Android 9.

![offline-extensions-error](https://user-images.githubusercontent.com/66443365/101977459-777ca700-3c45-11eb-81e9-bbb845815de5.png)

**Comment by JaspalSuri** [comment]
Hi @eaxillaris,

I'm afraid that editors are inaccessible offline on the mobile apps, but we do plan to make them available offline in future updates.
