### ISSUE TITLE
Moving notes between folders

### ISSUE THREAD

**Issue by bms53** [standardnotes/forum#783]
Signed up for Standard notes today and installed folder extension. I have looked through the documentation, which is limited I must say, but found no way to move a note from one folder to another. I assume it must be there. In Evernote it is a common action to move note from unsorted to the appropriate folder. I am using the MacOS app.

**Comment by PeterBlackledge** [comment]
New user here - signed up yesterday -no drag&drop or menu-type control that I can see in Folders. As far as I can see they are best treated as tags, so use Add tags... below the note title to move item to a new 'folder' or delete a tag to move it out of a folder. Unless somebody else knows better?
Generally the Standard Notes interface seems a bit primitive, but I guess its simplicity is a deliberate choice reflecting the commitment to robustness and longevity.

**Comment by roaet** [comment]
I am able to drag and drop with the folders. Windows 10 Client.

**Comment by bryvin** [comment]
@roaet Dragging does indeed allow you to place tags "within" other tags. However there is currently no dragging and dropping for moving notes themselves in-between different tags.

**Comment by restructor1** [comment]
> @roaet Dragging does indeed allow you to place tags "within" other tags. However there is currently no dragging and dropping for moving notes themselves in-between different tags.

Yes. It is no. But it is very necessary.
You right! +

**Comment by JaspalSuri** [comment]
If you'd like to add a note to a subfolder, simply type "folder.sufolder" in the tags list to place it there.

**Comment by Sjeiti** [comment]
This is still very confusing. I also noticed when using an outdated windows app and the web app side-to-side that tags had simply been renamed to folders. Yet functionality is all still tag-oriented.

Looks like the feature request for drag-and-drop is https://github.com/standardnotes/forum/issues/965

**Comment by atmoio** [comment]
You may be using the outdated Folders extension. Be sure you're using application versions 3.20+ to get the native folders experience.
