### ISSUE TITLE
2FA QR Code and Themes

### ISSUE THREAD

**Issue by MonolithOrchids** [standardnotes/forum#784]
Hello,
So I just subscribed for the Extended (thanks for the Black Friday offer) and tried to scan the QR Code to activate the 2FA, my phone (iPhone) couln't scan the QR Code when using any theme, it only worked when I switched to the default theme.

Cheers!

**Comment by bryvin** [comment]
Can confirm it does not scan when there is a theme active.. thanks for the heads up, will investigate.

**Comment by effieeee** [comment]
Tracking further here: https://github.com/standardnotes/forum/issues/2230
