### ISSUE TITLE
Desktop client for linux: Identify where downloaded update file has been stored

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#785]
At one time an update file downloaded by the Desktop client for Linux (32-bit) could be found at _/home/rbv/.config/Standard Notes_. That is evidently no longer the case?

Regardless, IF SN informs the user that an update file has been downloaded, THEN also include a link to, or at least spell out the path to, that file. The desktop client informed me that an update had been downloaded but I couldn't find it. So I'm compelled to seek out the download file myself. Sigh...

**Comment by johnny243** [comment]
The update file is downloaded in the following path:

![image](https://user-images.githubusercontent.com/5891646/70627380-8547b880-1bfc-11ea-9cb0-74cd3dcda8f1.png)

After the update is installed, the file will be moved to your user's home directory.

**Comment by custom-jonathan** [comment]
How do you install it? I tried finding the downloaded AppImage file, and I didn't know what to do after that.

**Comment by WritingSolutions2020** [comment]
> How do you install it? I tried finding the downloaded AppImage file, and I didn't know what to do after that.

@custom-jonathan  In what operating system?

In Linux Mint, I've been using the BASH command line to start the program in whatever directory I placed the most recent appimage.

That said, updating SN in Linux is a pain in the stizon. "Too difficult to make it easier" says the Ultimate Authority...

**Comment by custom-jonathan** [comment]
Using n00bs right now. Might install Elementary OS or something in the future.

**Comment by WritingSolutions2020** [comment]
At issue isn't the Linux distribution. It's mostly Linux _privileges_.  More specifically the privilege required to make a particular file _exectutable_.

One can use the desktop manager's GUI file utility to do that. Right-click, choose *Properties* -> *Permissions*, then select *Allow executing as program*. After which one should be able to either double-click the file in the file manager, OR better yet start it from the command line...

**Comment by custom-jonathan** [comment]
Right click on the AppImage file? Or anywhere in general and look for system permissions? I double click the AppImage file after enabling permissions? What would be the command line start command? And would I need to be in the parent directory where the program I'm trying to start before running that command?

As you can see, there are no limits to what I don't know about the first things I need to know.

**Comment by custom-jonathan** [comment]
I right clicked on the AppImage file, clicked properties, and next to "execute" I chose "anyone" before clicking "ok"

Then, when I double clicked the icon a second icon with a filename that had unrecognized characters popped up next to the original file I clicked.

Under the General tab it says "Open with:" and it says "Terminal."

**Comment by WritingSolutions2020** [comment]
Do you by chance have the 64-bit installer running on a 32-bit system.
You've describe the behavior I've seen in that situation.

One must hunt down the 32-bit installer for Linux. The SN downloads
site doesn't make that easy. But eventually I found the 32-bit
AppImage. After making that 32-bit installer executable per my earlier
description, I could then get the 32-bit AppImge to start up. After
which I created a Link (in Windows what's called a Shortcut) to enable
me to start the SN desktop client from my desktop...

**Comment by custom-jonathan** [comment]
Funny enough I was able to follow the step-by-step instructions here: https://standardnotes.org/extensions?downloaded=linux

Both the auto download of the 64bit and the one I downloaded manually for the 32 bit gave me the same error both times when I tried to start them via terminal: `bash: ./Standard-Notes-3.0.24.AppImage: cannot execute binary file: Exec format error`

Might be the dummy-proofing that noobs has in place? I'm ordering a bigger memory card so I can install a different operating system.

**Comment by WritingSolutions2020** [comment]
> Might be the dummy-proofing that noobs has in place?

Perhaps that. Perhaps that in my experience running the SN desktop client on Linux is hand-motions intensive. The SN client is a GUI app but installation / update is not at all GUI-ready. Or GUI friendly...

**Comment by custom-jonathan** [comment]
I genuinely appreciate you taking the time to explain what you've shared. I'll keep my phone handy for momentary notes, and try to keep my good ideas to a minimum while I'm playing on the Raspberry Pi4 occasionally.

When I install Elementary OS I'll give it another shot and see what happens.

**Comment by WritingSolutions2020** [comment]
Per @johnny243:
> The update file is downloaded in the following path:

That path == `/home/[user_name]/.cache/standard-notes-updater/pending`

Not intuitive. Not user friendly. But at least findable with that supplemental information. But why is _supplemental_ information necessary?

@mobitar Any chance the downloaded appimage can be made a bit easier to find? A clickable link in both the web and desktop apps? Or something / anything?
