### ISSUE TITLE
Android Not Saving Data Correctly When Syncing

### ISSUE THREAD

**Issue by camdit** [standardnotes/forum#786]
When I add a note on android it states that everything is saved, however it is not display anything more than the creation time when viewing from the Web. The oposite direction works fine.

I can debug the apk and see that it is sending data:

```
D/OkHttp:   "items": [
        {
          "content": "002:529f07c6225f45fa4278523be8e6c6a813907725632459b11a24520513471f95:d1bfeb3f-32fe-43a5-9083-c94b36e7f5c7:de26524bcb3ddd30b9c5ef9cc5f6f7f5:4BTfMkHTYOorLSldDGManA==",
          "content_type": "Note",
          "created_at": "2019-11-27T02:49:11.805Z",
          "deleted": false,
          "dirty": false,
          "enc_item_key": "002:bfc8290c1a7c5664330f4d1b1509418bf7da890f01ac49d5dfcffa8dd147451e:d1bfeb3f-32fe-43a5-9083-c94b36e7f5c7:e6039bffddd6b11ced79be33fb677ca0:GOj39jC8S22OSdb0aTNfai/VNHVkP1yz8/OUV9Pe1IHB4j1cWmkE/oj0dN7pPKrfjAkq9kkb5Skx9FE+Rb5q5mOg/BXTGnhR2YQiCcnK4FggyCLYtPCQf58R5Xr6uSLc/ntmx6e7+SIa8GJM1YEiARGNWWbVrDDkUSY3z5CIL0nxQSrPsZwiNSE8DfoTPLjK",
          "updated_at": "2019-11-27T02:54:20.993Z",
          "uuid": "d1bfeb3f-32fe-43a5-9083-c94b36e7f5c7"
        }
      ]
    }
```

But that data just doesn't populate.

This started happening/or at least I first noticed it today, 11/26/2019

**Comment by bryvin** [comment]
Hi camdit,

Based on the data you provided it looks like your account is using an older version of the Standard File encryption protocol which you can see by checking all the encrypted strings and seeing they are prepended with `002`. The newest version is `003`.

If you login to the web or desktop app again you will be prompted to do a security update at the bottom right of the app. Simply click "Security Update Available" to go through this process. I would also verify that you are using the latest version of the mobile app `3.0.17`

**Comment by camdit** [comment]
Unfortunately, I have a custom app that I use on my device to secure the standard notes along with others apps further. Because it is combined with other apps into a single useful launch point I am stuck using the clasic version of standard notes. I am not sure about updating the protocol in that version.

I will do some testing.

However, it apears that something has changed in the last couple of days that has affected the use of the clasic version.

**Comment by camdit** [comment]
I will close this issue, I think it is a mistake by me, migrating to a different support version I think broke this app.

**Comment by camdit** [comment]
It was caused from not cleaning the project... sigh.
