### ISSUE TITLE
Simple task editor - move tasks to another list

### ISSUE THREAD

**Issue by oliversturm** [standardnotes/forum#787]
I like the basic approach of the Simple Task Editor, but it is quite restrictive to work only within one list. I can create several lists - e.g. one for "today", another for "this week", and a third one for "long term" - but I can't find a way of moving tasks from one list to the other. 

I can copy an individual task's text of course, paste it to the other list, go back to the original one and mark it done - but that's fiddly and misleading because it appears as if the task was completed if I'm looking at the "wrong" list later. 

Is there something I'm missing? Or perhaps this is a feature request?

**Comment by oliversturm** [comment]
Just now it crossed my mind that I can switch editors to apply larger copy&paste operations. Perhaps this is a workaround for me, I'll try it. But I still think it would be nice if there was a more direct approach.

**Comment by bryvin** [comment]
The Simple Task Editor is actually true to its name in that it is relatively simple and doesn't offer some features everyone has come to like about creating Todo lists such as nesting lists, creating multiple within the same document or exporting tasks to another list.

I don't think this is something that will be improved upon for this editor specifically, but it's possible there could be another Task editor in the future that users would then have their choice of using either one.

Standard Notes extensions are also able to be created by the community; if you're a developer and would like some more information you can visit the docs here. https://docs.standardnotes.org/extensions/intro-to-extensions
