### ISSUE TITLE
Key shortcut for markdown strikethrough

### ISSUE THREAD

**Issue by pscholle** [standardnotes/forum#788]
Hey everyone,
i only recently starting using standard notes and after getting the extended version have flooded it with all my notes from OneNote.

I like the concept of using different editors.

Unless I am mistaken there is not a hot key for strike through in mark down.

Could this be added as a feature in the advanced markdown editors? 
typing ~~ before and after a word is tedious, and strikethrough is really ideal for crossing things off a list .

kind regards,
P

**Comment by pscholle** [comment]
tested Ctrl/Cmd + Shift + s but that could be dangerous, __s__ is maybe the wrong one.

how about Ctrl/Cmd + ~, with ~ its clear that is strike through. note I have to press shift to get ~ and for german laptops its Alt Gr

Even a tricky combination of shift and ctrl will be far better than having to type ~~strike~, especially when crossing stuff off a list.

thanks for getting back to me on this one

Cheers

**Comment by BobbyBriQz** [comment]
testing ~~strikethrough~~

**Comment by sonimafs** [comment]
~test~

**Comment by mobash-rasool** [comment]
~~strike~

**Comment by jawadsef** [comment]
dsdsd

**Comment by sschanhee** [comment]
~~test`

**Comment by AbbottLighty** [comment]
~~test~

**Comment by oalicea** [comment]
~~test~~

**Comment by snigdha920** [comment]
I tried cmd + shift + ~ but it did not work. What is the keyboard shortcut that was tested above for this?

**Comment by adityas-zluri** [comment]
~test~

**Comment by geoidesic** [comment]
@effieeee  This was closed with no information about the resolution? I.e. what is the key combination for this?

**Comment by veagul** [comment]
~testing~

**Comment by kaynegraham** [comment]
`test

**Comment by kaynegraham** [comment]
~asdad

**Comment by kaynegraham** [comment]
~~strike~~no

**Comment by aimamir** [comment]
~~strike~
