### ISSUE TITLE
Feature request: Password required every time the app is closed?

### ISSUE THREAD

**Issue by cryptopana** [standardnotes/forum#79]
Hi there.

I don't know if this is a feature already, I've looked for it but I can't find it. What if, to add an additional layer of security to the app, we want it to request the password every time the app is closed?
I know that this might be annoying for some people, but what if anyone wants it? Could be an optional setting or something.

Or... Even a pin code or something, when the app is closed/minimized, so that if someone has access to our device, they can't get into the notes just like that, because we're "already signed in".

Thanks!

**Comment by mobitar** [comment]
Yup, this is something definitely on the list :) No release date yet, but I'm hoping soon.

**Comment by mirsev** [comment]
A temporary workaround: [here](https://github.com/standardnotes/desktop/issues/93#issuecomment-331342878)

**Comment by mobitar** [comment]
This feature is available in v2.
