### ISSUE TITLE
Can't log out or authenticate -- special snowflake edition

### ISSUE THREAD

**Issue by heliostatic** [standardnotes/forum#790]
I had Standard Notes installed on a Pixel 2. I upgraded my device to a Pixel 4, and restored my backup.

On the Pixel 2, I was using fingerprint authentication. The Pixel 4 has no fingerprint reader.

I'm now unable to authenticate (can't change authentication mode) and can't log out, and uninstalling the app and then reinstalling doesn't help.

What is the recommended path forward?

**Comment by mobitar** [comment]
Sounds like you'd have to clear Storage for the app from your Android settings. I believe it's something like Settings > Applications > Storage, or maybe Settings > Storage > Applications. After that, you'll be able to sign into your account.

I believe @bryvin will be investigating how to add Android face authentication in the near future.

**Comment by heliostatic** [comment]
> Sounds like you'd have to clear Storage for the app from your Android settings. I believe it's something like Settings > Applications > Storage, or maybe Settings > Storage > Applications. After that, you'll be able to sign into your account.

That worked, thanks!
