### ISSUE TITLE
how to access file safe attachment from mobile

### ISSUE THREAD

**Issue by Massis1** [standardnotes/forum#791]
I understand that in mobile app the filesafe extension is not available.

Is it possible to see if an filesafe attachment is present in a note and is it possible to download / decode it in some way?

**Comment by jbeldia** [comment]
File safe attachments will load in your notes on mobile, and you can upload attachments as well, but there is just no way to download them to your device on the mobile app.

**Comment by rogister63** [comment]
I’m not seeing any way to Add inline images or upload any attachments from the iOS apps?

**Comment by mobitar** [comment]
Use the Bold Editor on mobile to manage images: https://standardnotes.org/help/71/how-do-i-add-images-to-my-notes
