### ISSUE TITLE
FileSafe AWS S3 configuration with Digital Spaces

### ISSUE THREAD

**Issue by redpay** [standardnotes/forum#792]
Can anybody confirm that any S3 compatible cloud storage service will work with StandardNotes?

I bought the Extended subscription yesterday and I am trying to configure FileSafe to backup the notes to my DigitalOcean Spaces but I keep getting an "Error uploading file" error.

Just to make sure, in the FileSafe integration configuration page, where it says "Region", I enter:

nyc1.digitaloceanspaces.com

Just how it looks like, without any http or sftp is this correct?

Where it says "S3 Bucket", I enter:

mybucketname

Just how it looks like, the name of an existing bucket located in the main root. Would this be correct?

**Comment by mobitar** [comment]
I don't think this will work. The integration is very custom-fitted to raw S3. Region means a value like "us-east", and not a domain.

**Comment by redpay** [comment]
Ok I just assumed that it would work with any compatible S3 cloud storage space. I will have to research if I can use WebDAV in DigitalOcean or as a last resort use Google Drive. 

If I use Google Drive will my IP be hidden from Google during the back ups? I believe there is relay server that does the upload...

**Comment by mobitar** [comment]
Right, your IP won't be sent to Google. It would be our relay server's IP that would be sent.

**Comment by redpay** [comment]
Ok, I will close the issue, thank you for your help.
