### ISSUE TITLE
Add More Autolock Timeout Options

### ISSUE THREAD

**Issue by joshcsullivan** [standardnotes/forum#793]
I would love to see the addition of 10, 15, and 30 minutes timeout options. 1, 5, then an hour is a large jump.

For myself, my main work desktop I would use 10 or 15, then for my home desktop, I would use 30 minutes.

Cheers,
Josh

**Comment by bryvin** [comment]
There was another suggestion for this and we agree adding either more options or a custom option would be the best route. I will make a note of this again but there is no timeline for added customizability here just yet.

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/1674
