### ISSUE TITLE
Entertain the option for prepay a Lump Sum

### ISSUE THREAD

**Issue by x80486** [standardnotes/forum#795]
This is a great option for some people for several reasons...and it's also better for you because you receive the money upfront, for future use.

**Comment by mobitar** [comment]
Please see here: https://standardnotes.org/help/32/does-standard-notes-offer-a-lifetime-subscription

**Comment by x80486** [comment]
That's not what I meant with that. This is to consider putting some _credit in the account_, at any given point in time, to be withdrawn at the time the subscription is due for renewal.

**Comment by mobitar** [comment]
You can do something similar to this by choosing the Extend Subscription option. This will defer your next scheduled payment by the length you extend for. For example, if you have a 1 year plan set to renew in December 2020, doing a one time extension of 5 years will defer your next 1 year payment to December 2025.

**Comment by x80486** [comment]
You are right...I'll close this one.
