### ISSUE TITLE
Linux desktop update does not update Ubuntu whisker menu link

### ISSUE THREAD

**Issue by jonahweissman** [standardnotes/forum#797]
When I updated from 3.0.15 to 3.0.23, the Standard Notes icon in the app picker menu (I think it's called the whisker menu) stopped working. (I'm on Ubuntu 16.04 - GalliumOS 2.1.) It gives me this error:
> Failed to execute command ""/home/jonah/bin/standard-notes-3.0.15-x86_64.AppImage" %U".
> Failed to execute child process "/home/jonah/bin/standard-notes-3.0.15-x86_64.AppImage" (No such file or directory)

Has anyone else experienced this? I'm sure it's possible to manually change the executable that the menu points to, but ideally, this would happen automatically.

**Comment by joshcsullivan** [comment]
See: https://github.com/standardnotes/desktop/issues/430

**Comment by jonahweissman** [comment]
Thanks! Didn't think to look anywhere but the forum, sorry
