### ISSUE TITLE
Is it possible to change the location of the FileSafe uploads AFTER the upload?

### ISSUE THREAD

**Issue by akay64** [standardnotes/forum#798]
I am testing out the flexibility of this system, in case I need to change my cloud provider, which I have done more than once. I have moved from Dropbox to Google Drive to Mega over the last 10 years.

So far I have tried to upload to Google Drive, then say I have a situation where I need to move to Dropbox or another service, so I moved the encrypted json files to the "FileSafe" folder in Dropbox and integrated the service, I did not expect that to work, and... it did not, so I tried to read the backup file and see if I can change the association there and do a re import on rebooted account, but GDrive file ID is some hash while the Dropbox one is a file path so I was not able to make that association work either.

It did not pick up those images, is there a way around this problem? Or if I use FileSafe and bind those attachments to my notes, I am basically tied up with that particular provider only in which case I should use just "Plus Editor" and use imgur.

P.S I am not really using Standard Notes for the "security" anyways.

Ideas?

**Comment by bryvin** [comment]
You are correct; this is currently not possible to move files from one source to another without manually changing the integration and re-uploading through the UI. In the future if this were requested enough we could add to the UI so users can re-upload to another source that they have allowed on their account.

**Comment by akay64** [comment]
@bryvin thanks for taking the time out to reply, will continue to evaluate the extended subscription for my use cases.

**Comment by cirrusflyer** [comment]
Any change in this?  I too would also like to change from my current file location to another.

**Comment by JaspalSuri** [comment]
There haven't been many requests for this feature and we might switch to a native solution that will make files easier to manage (but nothing like a fully blown out file syncing solution, etc).
