### ISSUE TITLE
Received an error when trying to upload my verification tag

### ISSUE THREAD

**Issue by grub-basket** [standardnotes/forum#8]
No specific information was provided to me. I followed the procedure provided on standardnotes.com/verification.

I logged out and signed in again, but the option to reupload it wasn't presented to me.

**Comment by mobitar** [comment]
Can you email me your email address? mo@standardnotes.org

**Comment by zoincs** [comment]
I also received this error. Should I also send my email address?

**Comment by grub-basket** [comment]
Were you able to login afterwards?

**Comment by zoincs** [comment]
Yes, I was able to log out and log in again.

**Comment by mobitar** [comment]
In that case, you should be good to go. Not sure why some users are being shown errors. But if you're able to login afterwards without any alerts, then your tag was successfully uploaded.

**Comment by DeniseDDoe** [comment]
Had the same issue. After seeing the alert saying that a verification tag was not found, i clicked OK, there was the next alert saying "There was an error uploading your verification tag.". I have my data uploaded from the archive but I'm not sure if this verification worked out.

**Comment by mobitar** [comment]
I'm looking into why some users are seeing errors on uploading. But in all cases so far it looks like the upload was in fact a success. To verify that it was a success, you can log out, then log back in. If you don't see any alerts about verification, then it worked.

**Comment by DeniseDDoe** [comment]
So then congrats on all the successful cases!
I did as you said, no alert anymore.

For your notice
[cid:E447F175-CFAC-4286-8DFC-079F8B2896C6@fritz.box]
Am 19.07.2017 um 16:58 schrieb Mo Bitar <notifications@github.com<mailto:notifications@github.com>>:


I'm looking into why some users are seeing errors on uploading. But in all cases so far it looks like the upload was in fact a success. To verify that it was a success, you can log out, then log back in. If you don't see any alerts about verification, then it worked.
