### ISSUE TITLE
[markdown extension] 404 page blocked by Firefox

### ISSUE THREAD

**Issue by Ikkyu-os** [standardnotes/forum#80]
hello

I recently had this issue where I have old empty notes that can't be display in Firefox (version 55.0.3 (32 bits)) when using the simple markdown extension

See attached screenshot
![issue404](https://user-images.githubusercontent.com/695806/30223608-e6cd5638-94cb-11e7-8380-e57a933925e9.jpg)

It says: 
> Blocked by a content security policy
> This page has a content security policy that prevents it from being loaded in this way.
> Firefox prevented this page from being loaded in this way because its content security policy does not allow it.
> 

This URL returns a 404: https://app.standardnotes.org/markdown

**HTTP request header:**
GET /markdown HTTP/1.1
Host: app.standardnotes.org
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://app.standardnotes.org/
Cookie: _ga=AAAAAAAAAAAAAAAA%2Fstandardnotes.org%2Fgetting-started%3Fdownloaded%3Dweb%22%5D; XSRF-TOKEN=XXXXXXXXXXX; _neeto_session=YYYYYYYYYYYY
Connection: keep-alive
Upgrade-Insecure-Requests: 1

**HTTP response header:**
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 404 Not Found
Vary: Accept-Encoding, Origin
Content-Encoding: gzip
Strict-Transport-Security: max-age=631138519
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
X-Request-Id: ace02b1d-4728-4c6c-bff3-bbd11b3233c0
X-Download-Options: noopen
X-Runtime: 0.000953
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src https: 'self'; base-uri 'self'; connect-src *; font-src 'self'; form-action 'self'; frame-ancestors 'none'; frame-src *; img-src 'self' piwik.standardnotes.org data:; manifest-src 'self'; media-src 'self'; object-src 'self'; script-src 'self' 'unsafe-inline' piwik.standardnotes.org; style-src * 'unsafe-inline'
Date: Fri, 08 Sep 2017 17:24:54 GMT
X-Powered-By: Phusion Passenger 5.1.4
Server: nginx/1.10.1 + Phusion Passenger 5.0.30

To give more insights, I enabled markdown plugin before extensions required a subscription, however other non empty notes are working fine

**Comment by mobitar** [comment]
Please email me (mo@standardnotes.org) the extension URL for the editor you're using. You may be using an outdated link. You can find it in the Extensions menu by clicking on the editor and pressing Show Link.
