### ISSUE TITLE
Extra section of whitespace.

### ISSUE THREAD

**Issue by vertika** [standardnotes/forum#803]
There seems to be an extra section of whitespace next to the editing section. 

Some notes about it:
- When I hover over that area the cursor is a pointer (the arrow).
- The separation line only appears if I hover over it.
- I am able to drag the separation line left and right to change the size of the extra whitespace section.
- I've been seeing this for the last few months.

<img width="988" alt="Screen Shot 2019-12-10 at 9 40 23 AM" src="https://user-images.githubusercontent.com/5400516/70554174-83fd8980-1b31-11ea-9217-0f23d5006225.png">

**Comment by bryvin** [comment]
This is actually an intended feature for users who choose to have Margin resizers on. If you wish to turn this off you can goto the `Options` menu right under your Note title and near the bottom you will see `Margin Resizers`. These are meant for anyone with a large screen that would like to control the width of the content (there is also one on the right side).

If I am mistaking what I am seeing and this is actually not the case please let us know and we can investigate further :)

**Comment by vertika** [comment]
Ah that was it. I was able to turn off the margin resizers. Thanks for your help!
