### ISSUE TITLE
Windows 10 Install Error 0xc000007b

### ISSUE THREAD

**Issue by workmanlike** [standardnotes/forum#804]
Hi,

I did have Standard Notes installed but last time I tried to load it it wouldn't load (I think with this same error code).  I decided to uninstall it and reinstall to see if it fixed the issue but I got exactly the same error.  I've tried some of the most common fixes I can find for this particular error but to no avail.  Is there a way to debug the install process?  When I run the installer without elevated privileges this error comes up straight away.  However, when I run it as administrator the installation does start but then the error comes up again.  Some support would be appreciated.

Error:
![Error Message - Standard Notes Install](https://user-images.githubusercontent.com/34632321/70571669-30715700-1b96-11ea-984a-cc5e724eb8e2.png)

Thanks

**Comment by johnny243** [comment]
Hi @workmanlike, could you please provide the following information:

- Windows **version**
- Windows **architecture**

Thanks

**Comment by workmanlike** [comment]
Hi @johnny243,

My windows version is 10.0.18363
Architecture: x64
Trying to install Standard Notes 3.0.23

Thanks
