### ISSUE TITLE
Make scrolling great again for Simple Markdown Editor when in split mode

### ISSUE THREAD

**Issue by x80486** [standardnotes/forum#807]
When using the `Simple Markdown Editor` in "split mode", scrolling is awkward...it looks like something is holding down those bars, not sure what it is.

I'm using the AppImage `3.0.23` on `Arch Linux`. Is this something that only affects me (or Linux)? If not, is it possible to make it work as the rest?

**Comment by bgillesp** [comment]
Also confirming scrolling issues in `Simple Markdown Editor` split mode.  Awkward scrolling is present when interacting by clicking on scroll bar, and also when using a mouse scroll wheel.   Desktop AppImage 3.0.24 on Linux Mint 19.1 (Ubuntu 18.04 base).

**Comment by effieeee** [comment]
Simple Markdown has been deprecated
