### ISSUE TITLE
Doesn't work to indent and outdent in the bold editor with Swedish Keyboard

### ISSUE THREAD

**Issue by Njoselson** [standardnotes/forum#809]
I want to be able to indent forwards and backwards in lists in the Bold editor.

According to the keyboard shortcuts the shortcut should be command + [

On a swedish keyboard for macbook however, the forward bracket is triggered with the option key + 8

Is there a way to make this work to indent forwards and backwards? It would help a lot.

**Comment by SiGamma** [comment]
Just use command + whatever letter is in the spot where [ and ] are on the American keyboard, it works fine on my non-american keyboard.

**Comment by Njoselson** [comment]
Works! Thanks!
