### ISSUE TITLE
Double tap to highlight has sporadic behavior

### ISSUE THREAD

**Issue by bryvin** [standardnotes/forum#810]
User report:
> I’m having some erratic experience with double-tap highlighting in the Advanced Markdown on the iPhone app. iOS 13.3. Sometimes (usually the first time) it works properly and other times it doesn’t. Is anybody else experiencing that? It works fine with the plaintext editor 

It looks like the word is selected but the select handles then quickly start moving inward from both ends, when it meets in the middle there is nothing left selected.

**Comment by TheodoreChu** [comment]
Thanks Bryan. It looks like this issue has been resolved
