### ISSUE TITLE
Raspberry Pi4

### ISSUE THREAD

**Issue by custom-jonathan** [standardnotes/forum#813]
I'm completely new to Linux. Just bought a raspberry pi4 and got it set up. When I went to install Standard Notes the instructions on the page make absolutely zero sense to me. 

I changed my directory to match the parent folder where the downloaded file is. I put in `chmod a+x standard-notes---.AppImage` and got `chmod: cannot access 'standard-notes---.AppImage': No such file or directory`

Where do I go for answers / walk through?

**Comment by bryvin** [comment]
Looks like you have received some help here: https://github.com/standardnotes/forum/issues/785
