### ISSUE TITLE
Browser doesn't open, preventing setup of FileSafe integration and more

### ISSUE THREAD

**Issue by KrishnaKollu** [standardnotes/forum#814]
There are numerous button links in the desktop app that do not work for me. For instance, when I click "Help" on the desktop app, it doesn't open anything. Moreover, when I click Actions -> Download Actions, nothing happens. These aren't a big deal, but what is a big deal is that the filesafe integration doesn't work.

When i click "add new" in the integrations panel, it displays a message "A new tab has opened. After you complete the authentication flow, enter the code you receive below." but no new tab has opened.

What am I missing? Is it some permission that allows standard notes to open the browser?

**Comment by bryvin** [comment]
Can you share some information about which version of app your are using and also what operating system you are running on? Also typically all that is required is for your system to have a default for opening a URL; which browser do you have setup to be your default?
