### ISSUE TITLE
Hide Expiry Banners in macOS App

### ISSUE THREAD

**Issue by mrtargaryen** [standardnotes/forum#815]
Hi,

Is it possible to hide the expiry banners in the macOS app? I can't afford to pay at present as I'm on a Disability Pension but would like to continue using the free features without the banner.

**Comment by mobitar** [comment]
You should be able to just disable whatever extensions that are displaying those messages. For editors, you can just switch to the Plain editor. Also please see here regarding economic assistance: https://standardnotes.org/help/56/what-if-i-can-t-afford-the-price-of-extended

**Comment by mrtargaryen** [comment]
> You should be able to just disable whatever extensions that are displaying those messages. For editors, you can just switch to the Plain editor. Also please see here regarding economic assistance: https://standardnotes.org/help/56/what-if-i-can-t-afford-the-price-of-extended

Thanks for the reply.

I've read the link and I have emailed Standard Notes about economic assistance. 

Thanks @mobitar
