### ISSUE TITLE
Passcode lock not working

### ISSUE THREAD

**Issue by YourExcelGuy** [standardnotes/forum#816]
Not sure why my passcode lock is not working - I did not forget it, because I wrote it down in a secure, encrypted storage space.

I looked through the Standard Notes FAQ first and saw no entries regarding passcode lock.

Does this happen? How do I fix this? 

Thanks for any guidance anyone may be inclined to share.

**Comment by YourExcelGuy** [comment]
Nevermind!

I logged into Standard Notes on another machine and assumed I could use the same passcode lock as I used on my main machine and device. 

However, it appears I had to create a passcode for the new machine. All is working now.

I was going to delete this, but thought I'd leave it in case anyone else has the issue, there's something they can try on their own.

Cheers.

**Comment by bryvin** [comment]
Correct, the Passcode Lock is on a per device/app basis. Glad you got it resolved!
