### ISSUE TITLE
Simple Task Editor checkboxes not centered

### ISSUE THREAD

**Issue by BuzzKnightbeer** [standardnotes/forum#817]
I'm on Windows 10 Pro with Standard Notes 3.0.24 and the checkboxes in the Simple Task Editor are not centered relatively to their line. See attached screenshot.

![tasks](https://user-images.githubusercontent.com/45749699/71379116-17e24300-257f-11ea-9f2e-7522d6674f73.jpg)

**Comment by bryvin** [comment]
Thanks for pointing this out. Little things like this will be on the back burner as it's not critical but we do intend to revisit all the little things like this as we understand they all add together to complete the experience.

:)
