### ISSUE TITLE
Would it be possible to extend the Simple Task Editor with a date/calendar functionality and possibly a reminder function?

### ISSUE THREAD

**Issue by BuzzKnightbeer** [standardnotes/forum#819]

**Comment by bryvin** [comment]
It's certainly possible to add to that editor but it's hard to change or add functionality that not everyone may want. A better option may be to make a more dedicated Task Editor with additional features and have both as an option.

While we don't have a timeline for either of those plans, editors can be developed by the community/users to provide any functionality they may desire: https://docs.standardnotes.org/extensions/intro-to-extensions

**Comment by 4bob1** [comment]
I emphatically second the request for a reminder feature. A reminder is intrinsic to the way I use a notes program. Whenever I enter a note I want to enter a reminder to act on it. 

This function is so important to me that I have returned to the dark side, Google Keep, which does have the function. I still use StandardNotes for sensitive personal information but put a reminder with a nonsense search term  in a Keep note to look it up in StdNotes . That is a PITA so I do not do it often.

**Comment by Falco101** [comment]
This is the only think keeping me from pulling the trigger on a paid sub. I also previously relied on Inbox, moved to Todoist, and want something that is end to end encrypted now. Joplin apparently has the ability to set alarms for notes, but not recurring ones.

**Comment by 4bob1** [comment]
bryvin writes: 

> It's certainly possible to add to that editor but it's hard to change or add functionality **that not everyone may want.** 

Everyone wanting something is an impossible standard. How about having a poll on the StandardNotes website on the number of people who want specific changes?

**Comment by BuzzKnightbeer** [comment]
> change or add functionality that not everyone may want.

Oh, that great argument and innovation killer again...

**Comment by 4bob1** [comment]
See the response by the developer on [this redditt](https://www.reddit.com/r/StandardNotes/comments/en1apb/no_new_features/) about no new features for years Basically tells people who suggest improvements to shove off. So be it. As I mentioned, I have gone back to using Google Keep.

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/292
