### ISSUE TITLE
Highligh search results

### ISSUE THREAD

**Issue by BobTB** [standardnotes/forum#82]
I have been looking at the demo and the first thing I noticed is that standardnots do not highlight the search string in the results. I have a lot of notes which are long, and finding the search string in a note is essential. It almost impossilbe to use this without it. Do I miss some option, can this be turned on?

**Comment by mobitar** [comment]
Not supported currently in Desktop. But the web app supports this via the browser's internal search function.

**Comment by BobTB** [comment]
Thank you for responding. So the search "workflow" is:  

1. Search for the note containing the text using standardnotes.
2. Opening browsers search and search for the same text again for it to highlight.

Not very user friendly :)

I am no programmer but this highlighting thing is missing out on a lot of note taking apps. Is it really so hard to implement? I am looking for something to replace my old simplenote client but it seems nothing is close to its functionality and I checked at least 15 of note taking apps. 

They either dont have editing without "edit" and then "save" which is killing productivity and if you forget to save, everything goes bybye, or they dont have a full text search, and if they have it, they do not highlight the search results. These are really basic things for such a program to do. Sorry for the rant!

**Comment by mobitar** [comment]
It's not about difficulty. We could do anything if we put our resources to it. But that's exactly why it's so dangerous. We need to make sure everything we add is absolutely essential. So we start with the absolute basics and build up from there. Over time, some users tell us "well, this feature you're missing _is_ an absolute basic." Sometimes we agree, other times not. But it's not so rigid. I've changed my mind about features before. In this case, I do agree that search highlighting should qualify to be a basic necessity. So I've added it to the list. I can't say when this will be done as there is so much going on right now, but hopefully not too far in the future.

**Comment by BobTB** [comment]
Thank you!

**Comment by quartertone** [comment]
Bump.
It would be extremely useful (perhaps essential) to have a way to search for a literal phrase rather than keywords. Sometimes I want to find a note that contains a certain set of words in no particular order. Other times I want to find a note that contains a specific phrase. Currently there is no way to search for a phrase. Entering multiple words in the search function treats them like keywords. Please add this feature!!

**Comment by BobTB** [comment]
mobitar - adding a highlight in the web client? Is this getting closer on your list of things to do?

**Comment by mobitar** [comment]
It's supported in the desktop app already using the plain editor, and most other editors. Not supported in the web app.
