### ISSUE TITLE
Web and windows app are not working correctly when tag name contains polish character

### ISSUE THREAD

**Issue by Karklik** [standardnotes/forum#825]
When tag have name like
TESTŃ
Apps will be unable to create notes in them
![image](https://user-images.githubusercontent.com/17294332/71642440-760fd400-2cab-11ea-8de9-fed068cc7d94.png)
Problem confirmed on web and windows apps.

**Comment by johnny243** [comment]
Hey @Karklik thanks for reporting this issue.

Could you please provide steps to reproduce the same?

Also, please specify the following:
1. Windows version
2. Browser name and version

Thanks! :)

**Comment by Karklik** [comment]
Strange, I cannot reproduce that right now on web 3.0.25 and win 3.0.24
