### ISSUE TITLE
Text search on mobile app

### ISSUE THREAD

**Issue by deacl** [standardnotes/forum#826]
Any idea when this will be fixed?
     In-note search is not available on mobile 

I very often need to do text search in standardnote, it's absence is very troublesome.

thank you for any help,
-deac

**Comment by mobitar** [comment]
This feature would be at least somewhat more easy to implement if we didn't have to solve it for each editor that we support. So, we still don't have a good solution for this.

**Comment by deacl** [comment]
Thank you for your reply.  

I’m using the Standardnote app on a Mac, I’m not aware that it uses a 3 party editor.  Can’t search be implemented in the Standardnote app?

Thank you,
-deac
 😎
                                                                                              
                                                                                              





On Jan 28, 2020, at 8:26 AM, Mo Bitar <notifications@github.com> wrote:

This feature would be at least somewhat more easy to implement if we didn't have to solve it for each editor that we support. So, we still don't have a good solution for this.

**Comment by effieeee** [comment]
See this as well: https://github.com/standardnotes/forum/issues/1414
