### ISSUE TITLE
Extensions (editors) on iOS don't work offline

### ISSUE THREAD

**Issue by gabor-meszaros** [standardnotes/forum#827]
I purchased the Extended version of Standard Notes a few days ago and used it successfully at home, mainly the mobile task editor to record my daily tasks.

Today, I traveled the whole day without internet connection and experienced that I cannot use the task editor on my mobile when I am offline (it falls back to the basic one).

After a quick search, I found that this is a [known limitation](https://standardnotes.org/help/59/can-i-use-standard-notes-totally-offline):

> The desktop application does not require an active internet connection (past the initial setup) for extensions to run. This means that editors and themes will work seamlessly when offline. The mobile application, on the other hand, does require an internet connection in some scenarios. On iOS and Android, an active internet connection is required for Extended editors to load (themes will work offline). In this scenario, the application will fallback to the plain editor.

I don't know if there is a technical limitation that makes the internet connection required on mobile, but because it is not required on desktop, I hope there isn't.

Are you planning to make the previously downloaded extensions work on mobile offline? In case of a positive answer, what is the planned release date for that?

And just a quick side question: Is this limitation also true for FileSafe and TokenVault?

**Comment by bryvin** [comment]
We do have plans to implement offline editor support to mobile soon but not timeline on an exact date.

Currently mobile doesn't download the editor at all in the way that the desktop app does. It simply loads it from the internet. So when this feature is released you would have to first have an internet connection for that first time downloading your editors again.

There may be certain editors that do require an internet connection to communicate with the 3rd party services to retrieve the encrypted copies of files. We will have to verify what is possible and what makes sense to store locally on the device. Once we have support for offline editors we will have more information to share on the limitations that come with it.

Thanks for purchasing extended :)

**Comment by johnlund** [comment]
Any updates on the availability of this feature? I use the app in offline mode mostly, so much of the value of extended is not available to me at this time. Thanks!

**Comment by mobitar** [comment]
This will be on @radko93's radar. We're working towards a v3.5 release that focuses on internal architecture, which will be a relatively large effort. We'll likely tackle this issue after that.

**Comment by janmyler** [comment]
Bump this for mobile devices. It’s a really poor UX not being able to use the app offline especially on mobile. What is the point of paying for an extended feature if my task lists or other extended editors fall back to plaintext or I have to read through an HTML source?

**Comment by effieeee** [comment]
Editors now usable offline on new mobile UI
