### ISSUE TITLE
Spellchecker

### ISSUE THREAD

**Issue by TBOTO** [standardnotes/forum#83]
A UK English spellchecker for the desktops would be awesome.
IOS built-in spellchecker works great on my phone, but on my mac and PC the apps do not have this.

**Comment by mobitar** [comment]
Unfortunately we would have to build this from scratch, as the system doesn't provide it for the desktop apps. It's on the long term list. For now you could check out the web app which will provide spell check. I know it's not ideal but hoping to get this fixed soon.

**Comment by guydog** [comment]
this is a crucial feature.
would it be possible to rely on system-wide spellcheckers (such as Aspell in Linux?).
If so, a guide would be appreciated.

**Comment by mobitar** [comment]
Not that I know of. I'd have to look into this. Trust me, I know how important it can be :) For now when I need spell check for a note I switch to the web app real quick.

**Comment by TBOTO** [comment]
Hey Mo,
how to you quickly switch to the web app to check spelling?
Thanks

**Comment by mobitar** [comment]
Just go to app.standardnotes.org.

**Comment by TBOTO** [comment]
Okay. Thanks

**Comment by guydog** [comment]
So far editing notes via app.standardnotes.org is the only way to have spell-check feature at your needs as it is linked to your web browser and not to the program.

**Comment by mobitar** [comment]
The desktop app definitely supports spellcheck now, and has been for a while now.

**Comment by guydog** [comment]
Thank you. 
Maybe I missed that: is it possible to switch between different languages in the spell checker?

**Comment by mobitar** [comment]
No, not currently..

**Comment by jrabensc** [comment]
Do you plan on implementing a switch for different languages? This is quite essential for any non-native English speakers.

**Comment by mobitar** [comment]
Possibly, have not yet investigated what it would take.

**Comment by kiru** [comment]
On McOS app, is the spellchecker used from the system or a custom one?
I am wondering how to add new words.

**Comment by JaspalSuri** [comment]
According to this commit, it uses the system’s spellchecker. https://github.com/standardnotes/desktop/pull/494 :)

**Comment by baptiste-grob** [comment]
This has not yet been released, but yes you'll be able to select your preferred spellchecking languages on Windows and Linux (on macOS the app will refer to your system settings) :)

**Comment by kiru** [comment]
Thank you!

**Comment by effieeee** [comment]
Closing, already implemented :)
