### ISSUE TITLE
Duplicate editors

### ISSUE THREAD

**Issue by bipox** [standardnotes/forum#831]
I opened the webapp but it was disconnected (something about the encryption key missing?). Maybe because I cleaned local storage in Firefox?

I entered my credentials, and it said something about merging notes. I clicked yes, a bit fast. 

Now I have a few duplicated editors. Both versions are working when selected. It happens on all the platforms I use (web app, Linux desktop and Android).

No other issues, editors work normally.

![screenshot](https://cncloud.zaclys.com/index.php/s/68mkqLiZRMRKANz/preview)

**Comment by csk** [comment]
I am experiencing the same issue. Many duplicated editors. I was thinking in uninstalling every extension and then installing them back. Is this the way to to fix this issue? If I uninstall Filesafe and install it back, will i loose all the files I already uploaded? Hope not but I will ask just in case.

**Comment by JaspalSuri** [comment]
> I was thinking in uninstalling every extension and then installing them back. Is this the way to to fix this issue?

I don't know if that will fix the issue (at least I don't think it will). I would just uninstall the conflicting extensions for now. Hopefully with the improvements that 3.5 will bring, this issue will become less frequent. That said, I have noticed multiple users reporting this issue. 

> If I uninstall FileSafe and install it back, will I lose all the files I already uploaded?

You will not. It's completely safe to uninstall. Don't uninstall the Listed extension, though, as you'd have to contact us to regain access to your Listed blog (which would result in valuable time lost on your part).

**Comment by cliftonfoster** [comment]
I'd like to add my experience to this post. Definitely frustrating. Thanks for working on it.
![2020-07-07 10_56_45-Standard Notes](https://user-images.githubusercontent.com/11276737/86823252-7bc2e980-c041-11ea-8676-966e6afea0cb.png)

**Comment by JaspalSuri** [comment]
Thanks for understanding! The dev team is working hard to iron out bugs and create thorough tests to make sure things work smoothly for version 3.5.
