### ISSUE TITLE
TokenVault "please match requested format"

### ISSUE THREAD

**Issue by txcrew** [standardnotes/forum#832]
Hi there, 
I'm getting, "Please match the requested format" message whenever I attempt to enter a "secret" on a new Token, after a fresh install of the extension. It comes up regardless, if I cut and paste the code or manually enter it. It seems like no specific number of characters will satisfy the requirements, so I'd like to ask: what are the requirements?

Alternative workflows aren't working either:
* When I add a QR from the library, nothing happens.
* When I add a QR from the camera on iOS, app crashes (see: #755)

**Comment by mobitar** [comment]
What's the source of the secret? Can you share the secret so we can test it (if it's disposable)?

**Comment by txcrew** [comment]
I'm following the steps located here: https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-setup-auth-app

Once I get to `The Configure mobile app page appears.` I use the 9-digit `code` listed in that screen and StandardNotes throws the formatting error.

I would've liked to use the QR code, but as I mentioned, it wasn't working for me.

**Comment by mobitar** [comment]
I'm not sure if Microsoft Authenticator uses their own format. It says that you can select a different authenticator. Can you share the QR code or 9 digit code? Most services should generate a new one on refresh. You can also email it to me.

**Comment by mobitar** [comment]
The secret should be a a 16-character string, like this:

LC24CY5CL3X323DA

So not 9 digits. Whatever Microsoft is using seems to be a different/proprietary format.

**Comment by txcrew** [comment]
Got it, that makes sense. I’ll dive a little deeper in Microsoft’s side to see if they can offer any insight.
