### ISSUE TITLE
Face unlock on Android?

### ISSUE THREAD

**Issue by mrtnggnn** [standardnotes/forum#833]
I switched from a Pixel 2 to a Pixel 4 XL phone, so no more fingerprint reader, biometric face unlock only. The app is unlockable (and positively unusable) on my new phone. 
Any help is appreciated!

**Comment by bryvin** [comment]
Face unlock on Android is something we have not yet implemented but will be working on in the near future.

In the meantime you will have to clear the local app data so you can relogin to your account. You can do so from your OS settings. Once you clear the App's data you can relaunch the app and sign in to your account using your credentials.

**Comment by mrtnggnn** [comment]
This does it, thanks!
