### ISSUE TITLE
Selfhosting on Google CloudRun

### ISSUE THREAD

**Issue by dslovin** [standardnotes/forum#836]
Hello,
I am trying to selfhost Standard Notes Sync Server on Google Cloud Run. Basically, we need a clean stateless container (without MySQL/SQLite). Ideally, its pretty light weight too. Then, we can configure it with environment variables to point to a CloudSQL server (through a unix socket).

Is it possible to make the SN docker container work statelessly? I would do a PR, but I am not that familiar with Ruby on Rails.

**Comment by mobitar** [comment]
We have a Docker configuration on our syncing server: https://github.com/standardnotes/syncing-server

Anything more custom than that will require personal effort I'm afraid.
