### ISSUE TITLE
Extension: Theming Issue

### ISSUE THREAD

**Issue by iganeshk** [standardnotes/forum#837]
**App**: Web & Desktop Clients
**Syncing Server**: Self-Hosted
**Issue**:

1. After installing the no-distraction theme, it appears that it duplicated it's menu into both Components and Themes.
2. Component-Theming does not unload the existing theme and load the one selected, instead loads the selected theme along with the existing loaded theme. (Note: This does not appear to happening  at the demo page, https://standardnotes.org/demo)

![theme-issue](https://user-images.githubusercontent.com/23004399/72286960-35517c80-3614-11ea-890b-e356ce720cae.gif)

**No-Distraction-Theme**:
```
{
    "identifier": "org.example.no-distraction-theme",
    "name": "No Distraction Theme",
    "content_type": "SN|Component",
    "area": "themes",
    "version": "1.2.2",
    "description": "A distraction-free writing environment for high levels of clarity and focus.",
    "url": "https://domain.com/standardnotes/no-distraction-theme-1.2.2/dist/dist.css",
    "download_url": "https://github.com/sn-extensions/no-distraction-theme/archive/1.2.2.zip",
    "latest_url": "https://domain.com/standardnotes/no-distraction-theme.json",
    "thumbnail_url": ""
}
```

**Comment by bryvin** [comment]
I am a little confused, are you hosting your own extensions as well? If not how are you installing these on your account? The metadata you show for the No-Distraction Theme is not accurate.

**Comment by iganeshk** [comment]
@bryvin Yes! I am hosting the extensions myself. There seems to be no documentation on json metadata, I adapted it by following the documentation. Could you please point me in the right direction for the correct metadata? If I understand correctly, no distraction theme seems to be the only theme which targets the "Components" in the area type due to it's nature (hiding components of the web).

**Comment by bryvin** [comment]
All themes should target the content_type of `SN|Theme`. For themes that can be stacked on top of one another (so you can theme the UI and still turn on No Distraction) there is an additional attribute called `layerable` which should be set to `true`.

You should be able to un-install that theme. Change your JSON file to add and reinstall:
```layerable: true```

**Comment by iganeshk** [comment]
Now that makes sense, Thanks for quick response!

**Comment by iganeshk** [comment]
@bryvin Off-topic question, I noticed the official web-app has "Repository" under extensions, would it be possible to add a personal repository to it?

**Comment by bryvin** [comment]
There certainly is the option for you to do that yes. There is an `SN|Repo` content_type. You would make a json file hosted just as you did for your extensions with the content_Type for `SN|Repo` and a packages array of the JSON data from your extensions (your individual extension JSON file but all listed under the packages array).

Hope this helps!
