### ISSUE TITLE
Feature request: mobile version - dark theme

### ISSUE THREAD

**Issue by guydog** [standardnotes/forum#84]
I love the simplicity of SN and I second the idea that it does not have to become too bloated, but I think that a dark theme for the mobile app would not be just a fancy optional but an essential feature for people who prefer, or have to, write / read on a dark background.
The sole possibility to set a dark / grey bg would be enough (and it should not be so difficult, I hope).

**Comment by guydog** [comment]
just realised it's the same request as #68 , sorry for the duplication

**Comment by mobitar** [comment]
> This is coming with the new mobile app :) Putting the finishing touches on it now. Join the Slack if you want to be a part of the beta.

**Comment by mobitar** [comment]
Now available in v2.
