### ISSUE TITLE
Spreadsheets are not scrollable on iOS

### ISSUE THREAD

**Issue by dvor** [standardnotes/forum#843]
As the title says. Both vertical and horizontal scrolls aren't working. I was able to scroll vertically several times, however it is very unreliable and hard to reproduce - I had to swipe up, down and diagonally multiple times until it worked.

Standard Notes v3.0.18
iPhone 11 Pro
iOS 13.3

**Comment by bryvin** [comment]
Transferred to the forum as this is likely an issue with the editor and not the mobile app.

Thanks for the heads up though; can confirm this behavior! I found clicking on a cell to bring up the keyboard allows vertical scrolling but not horizontal.

**Comment by sambosek** [comment]
Bumping this as I have the same issue which unfortunately makes the spreadsheet pretty unusable on mobile

**Comment by JaspalSuri** [comment]
I’m sorry to hear that, especially as a fellow iOS user. It’s still in beta (but may not indicate it, due to a bug) and the team tries to apply any fixes that they can with respect to their other duties.

**Comment by Git3893** [comment]
I've just paid for the extended plan and disappointed to find the same issue - no scrolling on iOS (ipad / iphone) in the spreadsheet editor - the reason I paid for the plan was to secure my simple spreadsheets. Also cannot select a spreadsheet cell to edit on the ipad. 
Grateful if you could fix this piece of functionality.

**Comment by mobitar** [comment]
This is indeed frustrating. The developers of this extension have fixed this internally but have not yet released the fix. I asked for an update but no response yet: https://github.com/telerik/kendo-ui-core/issues/5303 Please feel free to add your voice to that thread as well.
