### ISSUE TITLE
Add Markdown Plus editor

### ISSUE THREAD

**Issue by dreamflasher** [standardnotes/forum#846]
It would be great if you could add the Markdown Plus editor: https://mdp.tylingsoft.com/
Because it supports:
* Emoji
* Fontawesome
* Tables
* Task list
* Footnote
* Math
* mermaid charts: As requested in https://github.com/standardnotes/forum/issues/202 and https://github.com/standardnotes/forum/issues/445

**Comment by mobitar** [comment]
Looks powerful, but not actively maintained, which is unfortunate. Last commit was in 2017.

**Comment by dreamflasher** [comment]
Sad, but true :( 
I tried to understand how they do the mermaid parsing (was thinking of making a PR for one of the editors SN already has), but I don't get it. I can't find mermaid in the dependencies, nor being used anywhere in the code: https://github.com/tylingsoft/markdown-plus/search?q=mermaid&unscoped_q=mermaid
