### ISSUE TITLE
Exact Match Search

### ISSUE THREAD

**Issue by joshcsullivan** [standardnotes/forum#848]
Is there anyway to do an exact match search on the desktop/web version of SN?

Ex. `"Test1"` will return only Test1 and not Test101

If not possible, I would like to have this recorded as a feature request.

**Comment by mobitar** [comment]
Not possible currently, but something we hope to add in the future 👍

**Comment by bschlagel** [comment]
I'd love this. As a more general suggestion, could tie in with better default search weighting — i.e. may not even have to be a separate setting, just prioritize exact match + show fuzzy match below or something. Also prioritize title match > text body match. Not sure the current search algo but anecdotally I often search a phrase and get like 20 results with more exact-seeming matches lower down the list and harder to find.

**Comment by mobitar** [comment]
Actually this was added in v3.3, which is available on the web app now, and shipping to desktop sometime this week hopefully.
