### ISSUE TITLE
Trying To Empty My Blog

### ISSUE THREAD

**Issue by LWFlouisa** [standardnotes/forum#849]
Trying to empty my blog so I can re purpose it for my web comic. But it seems like it keeps holding on to certain posts, even after I've deleted everything from my cache.

Steps to reproduce the problem: Empty out your book. The every file should be empty. But it's not, it stills holds up to the last five to six posts. you've made in October.

**Comment by LWFlouisa** [comment]
Thanks will check it out to see if it works, was having some trouble as they were present after deletion.

**Comment by LWFlouisa** [comment]
Going to retest, and see if the bug continues, in the mean time what specific things are you looking for to help the issue?

**Comment by mobitar** [comment]
Be sure that you're deleting the posts from the Listed settings. If you delete the notes directly from the SN app, this will not affect any Listed posts. Or you can Unpublish from Listed first, then delete the note in SN.

**Comment by LWFlouisa** [comment]
Thanks figured it out!
