### ISSUE TITLE
Still expired subscription after paying through Bitcoin

### ISSUE THREAD

**Issue by hwakwo** [standardnotes/forum#85]
I paid subscription ($5/month) via Bitcoin (Coinbase). Waiting for two hours, I still see that my subscription is expired, despite I use same email address. Is there a way to resolve the issue?

**Comment by mobitar** [comment]
Hi, sometimes it takes a couple hours for the transaction to clear. Do you know how many confirmations the transaction has? If you used a low transaction fee it will take more than 2 hours.

**Comment by hwakwo** [comment]
It said completed. No confirmations or anything. My order number is 5TT95SVH.

**Comment by hwakwo** [comment]
Any update?

**Comment by mobitar** [comment]
Can you email me with the email you used with Stripe, as well as the Bitcoin transaction on the blockchain — mo@standardnotes.org. Your transaction needs to have at least 2 confirmations and an adequate fee.

**Comment by hwakwo** [comment]
It appears that the transaction bounced back. I am going to pay with credit card. Thank you for checking with me.
