### ISSUE TITLE
usability: Tags - rename/delete

### ISSUE THREAD

**Issue by supermensa** [standardnotes/forum#850]
When clicking to select a tag in the left side menu, it's easy to click rename or delete by accident.
:Why not make the option to rename and delete available by right-clicking on the selected tag instead

**Comment by mobitar** [comment]
We don't currently have right-clickability in the desktop app. Once we do though, you're right that this would be a better flow.

**Comment by Barraguesh** [comment]
I came here to say exactly this. I am glad there's a confirmation menu but damn it's just a couple of mm away...

**Comment by JaspalSuri** [comment]
Hi @Barraguesh,

I find it pretty difficult to easily rename tags on the [web](https://app.standardnotes.org)/desktop apps as I have to double-click them to edit them and I don't see a confirmation menu. Which app and/or platform are you referring to? 

You might be able to reduce the double click speed for your mouse based on the settings provided by your OS.

**Comment by Barraguesh** [comment]
I mean for deleting sorry. I am in desktop. Like I misclicked a note tag and I clicked delete, but the confirmation menu saved my mistake.

**Comment by JaspalSuri** [comment]
Hi @Barraguesh, thank you for clarifying and for your feedback. I'll take note of this issue for the team to review.

**Comment by effieeee** [comment]
Right click menu implemented
