### ISSUE TITLE
feature request: indent selected block of text

### ISSUE THREAD

**Issue by supermensa** [standardnotes/forum#851]
When selecting a block of text and using tab key to indent it, the selected text is deleted.

This might be default behavior, but I think it would be very helpful to be able to indent at block of selected text, especially when using lists etc.

**Comment by mobitar** [comment]
Indeed, a good feature to have. Some of our specialized editors do this, like the Code Editor. Our plain editor right now doesn't have any custom behavior, and is just a simple textarea, but if we decide to build a better plain editor in the future, this would be a feature we would add.

**Comment by aaantoszek** [comment]
@supermensa https://github.com/MaxLap/standard-notes-indent-editor check this one out

**Comment by myreli** [comment]
This is now available trough the [Super editor](https://www.youtube.com/watch?v=bkp6nrGqjUM&t=370s).
