### ISSUE TITLE
[Feature Re-Request]: Collapsible Folders (Folders Extension)

### ISSUE THREAD

**Issue by JimmyUX** [standardnotes/forum#852]
[I just noticed that this was asked about in 2018 and received favorable feedback, so I wanted to re-request it and I have included my notes]

I just wanted to request the ability to collapse nested folders with the folders extension. Some of my folders are rarely used but have lots of sub-folders and broadly my list of folders/notes is getting out of hand. This kind of ties in to another feature I requested, which would be for StandardNotes to remember where you are after the app gets locked/unlocked. So preferably the app would also remember which folders were collapsed or not.

I understand that folders in SN are really a visual representation of tags, so there are limitations on it. Perhaps this could be overcome with metadata, or a separate locked/hidden note which keeps track of the state of things within your app.

Also I know there is quite a long/undefined timeline for bringing these features to mobile but it would be really awesome if we get that at some point, so I just wanted to include thanks and encouragement on that front as well.

Jimmy

**Comment by mobitar** [comment]
You can do this already by clicking on the circle of each folder to toggle collapse state :)

**Comment by JimmyUX** [comment]
Awesome, thank you

**Comment by nuke807** [comment]
This was SUCH a point of frustration for me with SN. THANK YOU for pointing out how to collapse the tags!

**Comment by RonanCodes** [comment]
I've been wanting this feature for a very long time.
Perhaps changing the circle to a carat icon might be more intuitive?

**Comment by RonanCodes** [comment]
Also, a collapse/expand all icon at the top like in VSCode would be really nice.

**Comment by JaspalSuri** [comment]
>Perhaps changing the circle to a carat icon might be more intuitive?

Thanks for the feedback! I'll pass it along to the team. :) 

>Also, a collapse/expand all icon at the top like in VSCode would be really nice.

While it does require an extra click at the moment, you can click on the circles beside the `View` and `All` tags in order to collapse each section.
