### ISSUE TITLE
How do I rename folders/subfolders?

### ISSUE THREAD

**Issue by zakiaziz** [standardnotes/forum#854]
Hi, I'm using this extension here: https://standardnotes.org/extensions/folders

I can't figure out how to rename a folder or a sub folder. Right clicking doesn't open a "right click" menu, and  there doesn't seem to be any functionality within the app to do this. Is this possible?

**Comment by johnny243** [comment]
Hey @zakiaziz try double clicking the folder, like so:

![Peek 2020-01-29 17-07](https://user-images.githubusercontent.com/5891646/73397579-393ef900-42ba-11ea-8702-9e091a4627a0.gif)

**Comment by zakiaziz** [comment]
Thanks!  I would like to point out I've tried this before with no luck. It did work this time and it seems like the area in which I need to double click in is pretty small
