### ISSUE TITLE
Custom Fonts as Override of Normal and Monospace Fonts?

### ISSUE THREAD

**Issue by hl2guide** [standardnotes/forum#856]
Please consider adding the ability to set a custom font for both **normal** and **monospace** text.

By custom font I mean the ability to set and override the default and theme's fonts.

I personally would love to set it as:

normal font: Iosevka Thin
monospace font: Iosevka Light

The same for font size might be useful too 💃

**Comment by jsilvela** [comment]
Adding an up-vote to this. Would love to be able to change the default of Menlo... too lazy to develop a theme just for that one tweak.
Other than that, big fan of the app, keep it up!
