### ISSUE TITLE
Request: outdent list item keyboard shortcut

### ISSUE THREAD

**Issue by plantfansam** [standardnotes/forum#858]
👋 I have been using the **Bold** Editor and its lists functionality, and I love it! In the bold editor, when you're manipulating a list item, you can hit tab to indent it. I'd like to use the keyboard shortcut `shift + tab` to outdent (aka "unindent") the list item. I think this is pretty standard in WYSIWYG text editors (Google Docs, Apple Pages), so it would be great to have in the bold editor.

**Comment by robbielink** [comment]
I'm using the Plus Editor and there shift/ctrl/7 toggles list on and off. Ctrl/[ indents and Ctrl/] outdents when you're in a list - handy for sub-items. Don't know if that works in Bold Editor.

**Comment by JaspalSuri** [comment]
> Ctrl/[ indents and Ctrl/] outdents when you're in a list - handy for sub-items. Don't know if that works in Bold Editor.

It works for the Bold Editor! Thanks for your input!

(For macOS users, substitute the `control` key with the `command` key.)
