### ISSUE TITLE
How do you exit the insert mode in VIM for iOS?

### ISSUE THREAD

**Issue by okane786** [standardnotes/forum#859]
I love the VIM editor but am having one problem:  To exit insert mode in VI/VIM is the ESC key, but there is also no ESC key on the iOS keyboard, and the ESC key on my bluetooth keyboard doesn't work either.  Is there another key to exit insert mode?  As it is now, once I'm in insert mode, I can't get out.

**Comment by mobitar** [comment]
Not that I know of. I don't think the Vim editor will be mobile friendly ;) This is just a CodeMirror editor with Vim key bindings package.

**Comment by okane786** [comment]
Hi, thanks for the quick reply and the info on where the editor comes from.
I checked codebase and the vim bindings from the website and found other keys that also bind to the same function but none of them work on iOS.  They worked fine on Android though, so I think it's an iOS keyboard issue instead of a codebase issue.  If this could be addressed in a future release it would be great.  I'm trying to look for something that can edit my text files securely on all of my PC, Android, and iOS devices and this one issue is what's holding me back on snotes.  Thanks!
