### ISSUE TITLE
[Request] In-Note Search

### ISSUE THREAD

**Issue by pshelly** [standardnotes/forum#861]
Global search is really good in SN but in-note search is lacking. I have some workflows that heavily depend on the in-note functionality. I tried using global search but found it very annoying because of the following:

* I am using Plus Editor
- Highlight all behavior (out of focus)
- No next match behavior (dedicated button)
- No dedicated shortcut

Something like firefox's would be ideal. Everything accessible through graphical interaction and through shortcuts.

![image](https://user-images.githubusercontent.com/43761801/73935616-ed3e1680-48ae-11ea-9d46-e7d13b367690.png)

I find the found one on Minimal markdown editor is good but missing the buttons.

Idealy every editor would support it.

**Comment by mobitar** [comment]
This is very hard to do given our multi-editor approach. However, most likely the stance we will take in the future is that we will built out these features for 3 editors only: plain, 1 markdown, and 1 rich text. Which those would be is TBD. This is definitely something we want to build, and we realize it's important, but it's going to take time.

**Comment by bschlagel** [comment]
Strong agree, this would be extremely useful. Even just for plaintext + one markdown editor for example, that would be awesome :) 

Based on my experience I'd go so far as to say that if it's too hard to get this right for all editors, that's a *very* compelling reason to focus resources on a smaller # of editors, and perhaps even deprecate some of them going forward. Personally I would *much* much rather have one really great native-feeling markdown editor (long term, perhaps a custom base implementation that's easier for devs to extend / override) than the current situation of four different ones based on third party packages that all feel different and incomplete in random ways.

**Comment by adambyrtek** [comment]
Agreed, as a new user I found the number of Markdown editors really confusing. In the end I settled on Markdown Pro and uninstalled the other ones. I would much rather see one editor that integrates well and is officially supported for each use case (plain-text, HTML, Markdown, etc.)

**Comment by baptiste-grob** [comment]
I've wondered myself about the clarity of our editor choices too! We'll definitely be keeping this in mind 🙂 Also while there currently are many editors available it doesn't mean we're investing an equal amount of resources into each of them

**Comment by leafcutterant** [comment]
> most likely the stance we will take in the future is that we will built out these features for 3 editors only: plain, 1 markdown, and 1 rich text.

When choosing editors, I think it would make sense to select Minimal Markdown as the markdown one. Those who rely on in-note searching already migrated to this editor.

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/1770
