### ISSUE TITLE
FileSafe Arrow Direction Question

### ISSUE THREAD

**Issue by joshcsullivan** [standardnotes/forum#862]
Not a bug, but a design question; Why does the FileSafe arrow point down? In my mind, it should point up to show you need to click it to expand the FileSafe area up to see more options.

![image](https://user-images.githubusercontent.com/5774100/73991761-24e2a800-491b-11ea-8ba4-2ff75ac080a5.png)

**Comment by mobitar** [comment]
Not really sure. Would have to find examples of how other apps/sites treat this.

**Comment by joshcsullivan** [comment]
@mobitar Trying to find them is a bit tricky, but for example in Github replies (in the box I'm typing this reply in), the far right option (Replies) has the reply arrow then an arrow pointing down, if I click on it, the panel appears below it.

Similarly, on any Discourse site, when posting a reply there is a down arrow in the upper right of the slide up panel that when you click on it, will send the panel down and out of view.

![image](https://user-images.githubusercontent.com/5774100/74045804-674bc980-499b-11ea-804f-f3a68fbf93d3.png)

**Comment by baptiste-grob** [comment]
Right now the app's UI is essentially frozen because we've started thinking about v4 and files are for sure going to be handled very differently 👍 thanks for the feedback!

**Comment by effieeee** [comment]
FileSafe deprecated
