### ISSUE TITLE
Selecting text, then closing the keyboard in the Android app deletes the selected text

### ISSUE THREAD

**Issue by ardentmusician** [standardnotes/forum#864]
As the description shows, I was trying to scroll when it selected the text instead and popped up the keyboard.  When I closed the keyboard, it deleted all the text.  As I cannot find any way whatsoever to undo actions in the Android App, a bunch of work was lost.

So, this is 2 issues:

1.  Closing the keyboard should never delete text.  This is ridiculous.
2.  Why isn't there a basic undo in the Android app?  (or if it is there, why is it impossible to find?) This is also ridiculous.

**Comment by mobitar** [comment]
Hmm, that's strange. I've never heard of this happening before. So closing the keyboard by pressing the hardware back button? Or by which mechanism? And is this replicable all the time?

As for undo support, we're working our way right now towards making the codebase ready for our Session History feature which we support on desktop/web currently. There's a bit of refactoring that we need to do before this is possible, but it's definitely a priority!

cc @bryvin

**Comment by ardentmusician** [comment]
I haven't been able to duplicate the deletion since that first incident (repeated it several times then), so I am going to blame the keyboard. Being unable to undo was shocking.

-------- Original Message --------
