### ISSUE TITLE
Zoom of notes

### ISSUE THREAD

**Issue by ferfhcnd** [standardnotes/forum#866]
Hi there,

is it possible or planed to add 
an ability to zoom (at least 3 options, large, medium, small) notes on mobile version like pc (ctrl+-)? Is this function possible in Standard (not Extended) notes?

Best wishes

**Comment by mobitar** [comment]
I think we might explore font size settings in mobile at some point. Perhaps v4, but I agree this would be useful.

**Comment by effieeee** [comment]
Some font size options are now available for plain text notes
