### ISSUE TITLE
[DEMO] only Plain Editor available

### ISSUE THREAD

**Issue by jaklan** [standardnotes/forum#867]
Hi, I wanted to test some extensions of Standard Notes, but demo offers only Plain Editor - although all extensions should be available:
> Below is a fully featured Standard Notes demo that includes all editors. Note that in the demo, changes you make are not saved. If the demo does not display, please open the full screen demo.

**Comment by mobitar** [comment]
Sorry about that, there is a regression here preventing the web app from auto-signing into the demo account. @baptiste-grob is aware of this and we hope to have it fixed soon.

**Comment by TheodoreChu** [comment]
Hi @jaklan, I think the [demo](https://standardnotes.org/demo) is working for me now on my Windows computer with non-private Firefox and private Chrome. Please try again and let us know if you still have any issues 😀

**Comment by jaklan** [comment]
@TheodoreChu seems to work :) Thanks!

**Comment by oliveconstant** [comment]
Still happening with Firefox 89.0 on Fedora 34

**Comment by JaspalSuri** [comment]
Hi @oliveconstant, while the demo currently doesn't include all of the extensions by default, you can install & activate additional extensions from the **Extensions** menu.
