### ISSUE TITLE
Possible to modify subscription?

### ISSUE THREAD

**Issue by mprobson** [standardnotes/forum#87]
I signed up for the extended plan about a month ago and would like to change my subscription from monthly to yearly. Is that possible? When I log in to the extended dashboard I only see the option to cancel my subscription (it also shows when it will renew).

**Comment by mobitar** [comment]
Hey Michael, you can hit cancel on the subscription, which will keep your account active until the end of your subscription period, and also gives you the option to renew at a different tier. That should do what you want. If you upgrade immediately and want a partial refund on the number of days remaining in your monthly cycle, please email me (mo@standardnotes.org) and I'll be happy to get that returned to you.
