### ISSUE TITLE
Simple Task Editor stopped working on Android version

### ISSUE THREAD

**Issue by Shadallark** [standardnotes/forum#872]
Good day to all of you!

Something changed in a recent update to the Android version of the App that is preventing the Simple Task editor from displaying the tasks.  It still shows the field to enter new tasks and it shows the headings for the **Open Tasks** and **Completed Tasks** but none of the tasks in either section are displayed.  The tasks show up correctly in the iOS version of the app.

We tried switching editors on the Android device and all the items are there with either **-[]** or **-[x]** in front of them.  Switching back to Simple Task Editor still only shows the headings.  We also deleted the app from the device and reinstalled it but it still only shows the headings.

Any assistance you can provide is appreciated.

Shadallark

**Comment by mobitar** [comment]
Hey Shadallark, sorry about that. We're still investigating the cause of this, but what we do know so far is it has to do with an invalid theme being activated. Could you try deactivating any themes and see if that helps?

cc @bryvin

**Comment by Shadallark** [comment]
Thanks @mobitar !

Switched the theme (to Midnight I think) and it is working correctly now. 

Thanks for the quick response and work around.
