### ISSUE TITLE
Removing tasks in Simple Task Editor

### ISSUE THREAD

**Issue by adambyrtek** [standardnotes/forum#873]
Maybe I'm missing something really obvious, but I don't see a way to remove an item in Simple Task Editor. I can only mark items as completed or completely remove the name, but this still leaves an empty checkbox. Is there some keyboard shortcut for that?

More generally, it would be great if `Enter` at the end of an existing item added a new one, and `Backspace` at the beginning of an empty one removed the checkbox.

**Comment by mobitar** [comment]
If you delete a task's text, then press enter, it will delete the task :)

**Comment by adambyrtek** [comment]
Brilliant, seems to work, but obviously it's not very discoverable. I'm happy to contribute some improvements to that editor if you're open to PRs?

**Comment by mobitar** [comment]
What do you have in mind? PRs are good for bugs but not UX changes without first discussing ;)

**Comment by adambyrtek** [comment]
Something like what I mentioned above: "More generally, it would be great if Enter at the end of an existing item added a new one, and Backspace at the beginning of an empty one removed the checkbox."

**Comment by mobitar** [comment]
Yeah that would be welcome 👍
