### ISSUE TITLE
Evernote Notes preview in the sidebar panel not useful

### ISSUE THREAD

**Issue by andreamoro** [standardnotes/forum#874]
I guess that a picture is worth thousand words. 

I have imported some notes from Evernote, and - despite the plus editor installed (which does its tricks on the right side) - the preview doesn't  seem to be useful enough.

![image](https://user-images.githubusercontent.com/5256583/74315664-da748780-4d6f-11ea-81da-f6e5e651da97.png)

It would be worth if the preview pane could follow suit the behaviour of the editor attached to a particular note or the default one.

**Comment by mobitar** [comment]
I believe you'd have to trigger an edit with the Plus Editor so that it generates previews. The converter doesn't do this. Although I suppose it should now that I consider it (would have to see if that's even possible).
