### ISSUE TITLE
Account pop-up opens every single launch

### ISSUE THREAD

**Issue by udf2457** [standardnotes/forum#875]
OS X 10.14.6
SN 3.3.1

Unless I'm missing some setting somewhere, the account popup opens every single time Standard Notes is launched.

<img width="397" alt="Screenshot 2020-02-12 at 14 06 07" src="https://user-images.githubusercontent.com/6958684/74342179-00665000-4da1-11ea-9189-bfec3a4d9857.png">

**Comment by mobitar** [comment]
Only if you have 0 notes and no account.

**Comment by udf2457** [comment]
@mobitar 0 notes I understand.  But no account ?  Nagware ? Forcing people into an account ?  What if people want to use it locally without sync ?

**Comment by mobitar** [comment]
0 notes AND no account.

**Comment by udf2457** [comment]
Well, the app creates a first note by default. But once strlen(txt) > 0  on the default note then that fixes it. 

But ok, you win. ;-)

**Comment by mds08011** [comment]
> But ok, you win. ;-)

Can this issue be closed?
