### ISSUE TITLE
Sync-Conflics when writing while internet is enabled

### ISSUE THREAD

**Issue by ChargingBulle** [standardnotes/forum#881]
As a user I am greatly annoyed by the constant sycn conflicts which happen when the app is used while connected to the internet.
Typing while wi fi connected results almost always in having the note duplicated and/or being synced improperly.

Known Workaround: only use the app offline.

Used version: 3.0.17 via FDroid on `lineage_mata-userdebug 9 PQ3A.190801.002 8aed3ae715`.

**Comment by mobitar** [comment]
Not something we can easily replicate I'm afraid. Seems to happen to only a subset of users. Does it happen consistently, and if so, can you provide replication steps?

**Comment by mds08011** [comment]
I have run into this issue while switching internet connections.  For example, typing a note while walking out of a building and my phone switches from WiFi to cellular.  

But I have not encountered it while on a consistent internet connection.
