### ISSUE TITLE
Spell checker for all editors?

### ISSUE THREAD

**Issue by MichalMichalak** [standardnotes/forum#885]
Hello. Correct me please if I'm wrong but spell checking works only in plain text editor, now. At least from what I see while looking at my extensions list. Would that be possible to check spelling in all editors? It would a lot from people from jumping between editors or simply not being aware they've made a mistake.

**Comment by mobitar** [comment]
Correct, spellcheck on Desktop only works in the plain editor. With the web app, it should work with most editors.

On desktop it's a security restriction that prevents us from offering spellcheck across all editors.

**Comment by MichalMichalak** [comment]
Hm, isn't there any option for user to relax the security in such cases. Like, maybe there are some permissions user could give to the app? It's common on mobile, not sure about the desktop.

Good use case would be: when user enters editor you could show pop-up with description of a problem, user could enable SN to be able to show spellchecking (or not if he doesn't wish so.) Not sure this is possible, though.

**Comment by baptiste-grob** [comment]
Hey @MichalMichalak, we're in the process of upgrading our tech stack for the desktop app and it might offer us better way to implement spellchecking… Maybe we'll come out with a better solution, though at present it is still full of uncertainty so no promises 😅 in any case your comments are certainly not falling on deaf ears 👍

**Comment by MichalMichalak** [comment]
Well, then, let's hope it can be done in the future. Thanks for all your efforts!
