### ISSUE TITLE
Feature request: Logout on close

### ISSUE THREAD

**Issue by tvarsis** [standardnotes/forum#89]
Since this application has a large focus on privacy and encryption, I think there should be a setting for automatically logout when closing the application. Right now, once I have logged in it remembers my credentials unless I do the "Sign out and clear local data options". Which will not work if for example the power is cut on the computer, application is killed/closed etc.

**Comment by mobitar** [comment]
Yup, definitely. This is coming soon. See here: https://github.com/standardnotes/desktop/issues/93#issuecomment-328835481

**Comment by mobitar** [comment]
Available in v2.
