### ISSUE TITLE
"Error while trying to save..." "Contact support and..."

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#891]
For 32-bit Linux Mint, most current version of the (Chrome based) Vivaldi browser .

Yesterday I received this error pop-up from the SN web client:

![2020-02-26 08 30 07_Notes · Standard Notes_08_30_07](https://user-images.githubusercontent.com/3333327/75487668-af8b5580-5963-11ea-8a5f-f1334724c05b.png)

1. This occurred about five minutes after the web client indicated that it completely downloaded all my notes and had been sitting idle in a browser tab.
2. The message was modal and totally unresponsive. So I ended up having to reload the tab to make it go away.
3. After reloading SN loaded a few additional notes.
4. After that second download, the web client seemed content. No more error messages.

I doubt any troubleshooting can be done. Simply following instructions to **Please contact support and share this message**...

Cheers & hope this helps,
Riley
SFO

**Comment by johnny243** [comment]
Hi @WritingSolutions2020!

It would be difficult to troubleshoot without more information. The error object was not displayed properly and instead was shown as a string representation of an object. We'll improve this so that it is displayed properly.

Thanks for reporting! :smile:

**Comment by WritingSolutions2020** [comment]
Another similar error message this evening:

![2020-03-03 17 39 09_Notes · Standard Notes_17_39_09](https://user-images.githubusercontent.com/3333327/75839654-2e2a2d80-5d7e-11ea-83b2-1c160da402fe.png)

As was the case in the first instance, the SN web client informed me that it had fully synced my notes. Having left the browser tab idle for less than five minutes, the SN web client displayed the aforementioned -- and wholly not interactive-- error message. Nothing, including trying to refresh the browser tab, could restore SN. I ended up closing the unresponsive browser tab, then using Chrome-based Vivaldi to re-open the tab. At which point SN became re-functional and no further error messages occurred in more than 10 minutes...

**Comment by baptiste-grob** [comment]
Thanks for bringing this up, I've referenced this thread in another issue so I can properly look at what could be going on when I get around to this!

**Comment by WritingSolutions2020** [comment]
Per the attached PNG screenshot, another popup along the same general lines:

![2020-03-16 12 13 40_Notes · Standard Notes_12_13_40](https://user-images.githubusercontent.com/3333327/76792242-daf1ab00-677f-11ea-97d0-ce942848b4be.png)

In all instances, I log in to the SN web client. The bottom-edge status bar informs me that it's downloading my notes. After the syncing / downloading has completed, I'll create or edit a note, then let the browser tab remain open but sit idle for 5 to 10 minutes or so.

It is while sitting idle that the web client displays one or another popup. Not sure what's going on or why...

Cheers & hope this helps,
Riley
SFO

**Comment by JaspalSuri** [comment]
Hi Riley, what browser extensions are you using in Vivaldi? Feel free to message me on Slack if you don't want to disclose them here (the extensions you use can serve as a unique ID for ad-related purposes).

**Comment by WritingSolutions2020** [comment]
@JaspalSuri Here are the extensions I have installed. Note that the one that I would most suspect, uBlock Origin, is disabled for SN:

![2020-03-16 19 38 27_Notes · Standard Notes_19_38_27](https://user-images.githubusercontent.com/3333327/76816676-0f845780-67be-11ea-8568-ac91b3faeb9f.png)

Privacy Badger doesn't detect anything to block. Cookie Autodelete doesn't delete cookies until i close the SN browser tab. Similarly, neither Disconnect nor Ad Block detect anything on the SN web client page to interact with...

**Comment by baptiste-grob** [comment]
Definitely sounds like there's some communication issue there… Have you tried running the web app in a different (perhaps less customized) browser? It could help us determine if it's an account or browser-based issue 🙂

**Comment by baptiste-grob** [comment]
Also what's your network status in general? Is your internet stable or can it get jumpy at times?

**Comment by WritingSolutions2020** [comment]
No network problems. AND I'm not experiencing this sort of problem with any other browser tab or web site. It's a Standard Notes thing...

**Comment by baptiste-grob** [comment]
Thanks for the report and sorry you're experiencing this… please let us know if you encounter anything else!
Does this happen on the desktop app as well? You can download it here: https://github.com/standardnotes/desktop/releases/download/v3.3.3/Standard-Notes-3.3.3-i386.AppImage

**Comment by WritingSolutions2020** [comment]
Haven't experienced this particular behavior in the client. But that doesn't mean much because I don't run the desktop application that often. Primarily because I'm running Linux with the MATE desktop on an old 32-bit laptop -- so I try to minimize the number of open applications...

This isn't a show stopper. But per my initial post, the first of these sorts of pop-ups asked me to contact support. So I have.

But in lieu of anyone else having this problem I wouldn't spend too much time and energy on this issue -- I suspect there are more important things to focus on...

**Comment by baptiste-grob** [comment]
Building software is indeed a constant balancing act and thank you for being so understanding about this 😊 it's still useful information though! Thanks again for sharing 👍
