### ISSUE TITLE
iOS dark themes are..light?

### ISSUE THREAD

**Issue by dgraziotin** [standardnotes/forum#892]
No matter what theme I choose, the result is the following:

![IMG_78D231474C54-1](https://user-images.githubusercontent.com/153179/75556867-4842d380-5a3f-11ea-8a36-182cecc1e679.jpeg)

These are the themes I tried (Muted Dark was selected at the time of screenshot).

![IMG_45191563D6CC-1](https://user-images.githubusercontent.com/153179/75556960-77594500-5a3f-11ea-85f6-a2509f8e6df6.jpeg)

These themes all work well on macOS. I tried uninstalling the app on iOS, no success.

**Comment by bryvin** [comment]
Can you try long pressing on the themes that cause this and choosing "Redownload". Then report back with the results?

**Comment by dgraziotin** [comment]
@bryvin was about to report that the "Redownload" option (which I discovered only thanks to #613, it is not intuitive to long press on those items) fixes the issue.

**Comment by bryvin** [comment]
Glad to hear that worked for you. Thanks for reporting back!

**Comment by dgraziotin** [comment]
@bryvin thanks for the quick help! Feel free to close this in case the issue is already reported elsewhere and I could not find it.
