### ISSUE TITLE
[Feature Request] Created a Dark Theme Extension for y'all

### ISSUE THREAD

**Issue by jakecza** [standardnotes/forum#894]
Hey guys,

If this isn't allowed, let me know and delete the thread...but I created a dark theme w/ pastel colors for Standard Notes, since I didn't fancy any of the original ones.

[jakecza/dark-hybrid-theme-sn](https://github.com/jakecza/dark-hybrid-theme-sn)

If any developers are interested, I wouldn't mind making a few more theme variants if they get packaged with the Extended upgrade.

Best,
Jake

**Comment by jakecza** [comment]
Also I've found an issue to where my theme does not work on the app.standardnotes.org web application, any hints on why that is? It does not let me import the extension JSON link either through the web app.

**Comment by mobitar** [comment]
Looks cool! You should post this in our Slack group; there's a repository that collects all Standard Notes community projects https://github.com/jonhadfield/awesome-standard-notes

As for web app, you should open the inspector and see what issues it's reporting.
