### ISSUE TITLE
[Feature request] - Bold editor - option to hide editor icons

### ISSUE THREAD

**Issue by mangomadness** [standardnotes/forum#895]
I'm enjoying Standard Note, and like writing notes with some rich text (bold, italics, lists, etc.) so I have been using the "Bold Editor". 

Most of the common rich text features are easily usable through simple and well known keyboard shortcuts. 

When using the "No Distraction" theme, all of the rich text icons still show up. 

Is there any way to toggle/turn them on and off while in the No Distraction theme?

**Comment by mobitar** [comment]
There's no way to do this presently I'm afraid..

**Comment by effieeee** [comment]
Bold editor is now deprecated and moved to the community plugins
