### ISSUE TITLE
Email back ups are being sent twice

### ISSUE THREAD

**Issue by redpay** [standardnotes/forum#897]
This is mostly an informative post in case you are not aware of this. 

I have backups set to be send by email and sometimes they are being sent twice, this has happened on the 29th January, 01st March and 2nd March, on the 03rd March it returned to normal. I recall happening before last month but I dismissed the issue as a temporary glitch. I am now reporting it because it is happening again.

Looking at the email timestamps I see that there is only one minute of difference in between both emails with the same backup. 6:07am and 6:08am

**Comment by mobitar** [comment]
Yup, sorry about that. This issue was fixed yesterday.

**Comment by redpay** [comment]
Support reply in less than 30 seconds, I dont think it gets quicker than that! Well I will close the issue, thank you.
