### ISSUE TITLE
exporting all data from Standard Note to SimpleNote

### ISSUE THREAD

**Issue by vitoslawski** [standardnotes/forum#898]
I just moved my data to Standard Notes from SimpleNote.

While I like very much the Standard Notes experience, 
I am concerned if I can move my data to any other service.

The Decripted Backup - while in plane txt format is in one file and with some stuff in it.

Is it / will it 
be possible to export all data to INDIVIDUAL txt files, the way SimpleNote does,
so it could be migrated to SimpleNote or elsewhere - if a desire arises?

For that matter I don't see any help / FAQ  on how to migrate OUT of Standard Notes.
I see it as essential to see the way out of place I move into.
I hope it makes sense.

**Comment by joshcsullivan** [comment]
If you use the export decrypted from a web browser (not the apps), it also downloads a ZIP file with individual text files.

**Comment by baptiste-grob** [comment]
I believe the intended behavior is for it to work in the apps as well, so really there's a bug :)

**Comment by baptiste-grob** [comment]
I've just checked and when downloading a decrypted backup on the desktop app you get _two_ save prompts: one for a `.txt` file which contains all your information, and another for a `.zip` file which contains that same information but spread out as individual files and folders. I believe this answers your question @vitoslawski? :)
