### ISSUE TITLE
[desktop, themes] Midnight theme: "all changhes saved" missing

### ISSUE THREAD

**Issue by guydog** [standardnotes/forum#90]
I noticed that the indication "All changes saved" on the top right corner of the desktop program (in my case ) is missing, whilst other themes (Futura, Focused, Titanium, Dynamic) do show it correctly.
This is annoying  and should be fixed, as it is essential checking whether the note has been synced or not (meanwhile I switch to another dark theme).
Thank you

**Comment by mobitar** [comment]
This has been fixed.
