### ISSUE TITLE
passcode vs account number

### ISSUE THREAD

**Issue by stoneydog** [standardnotes/forum#902]
I want to be able to start and enter the app without using any number/code (always unlocked) but still be able to protect some sensitive, individual notes with a passcode (not my account number). Is this scenario possible?

**Comment by mobitar** [comment]
You can protect notes individually using Options > Protect. Note that this protection is superficial, in that it's only UI protection. If the app is unlocked, this means the underlying note is sitting in memory in an unencrypted state. Protection doesn't change that. Protection will protect you from nosy co-workers, etc, but not from a hacker who has access to your unlocked application.

**Comment by stoneydog** [comment]
Ok thank. That's good to know.
