### ISSUE TITLE
Can't create new note after creating new folder

### ISSUE THREAD

**Issue by dig12345** [standardnotes/forum#903]
Often after creating a new subfolder folder on the windows client I cannot type in the default "Note 1" note. I also can't create new notes in the new folder. Sometimes if I click around to other folders I will be able to come back and edit "Note 1" but not always. I'm on version 3.3.3 and this bug has been present since I started using SN a few months ago.

**Comment by JaspalSuri** [comment]
I'm sorry that you've had to deal with this issue for months now; hopefully we can get to the root of this issue. 

Unfortunately, I'm not able to reproduce this on macOS but I'll try it on Windows later today! 

I can't create a note until Note 1's title/body has been edited. It's odd that it doesn't let you type into it. Can you try deactivating and reactivating the extension?
