### ISSUE TITLE
WebDAV and OneDrive with Filesafe

### ISSUE THREAD

**Issue by nuke807** [standardnotes/forum#904]
I have been trying to find instructions on how to use OneDrive (through WebDAV) with Filesafe, but I have come up empty handed in my searches.

Can anyone provide me with where to find the credentials that I need to set up WebDAV and Onedrive?

Thanks,

**Comment by JaspalSuri** [comment]
I don't think it's currently possible, with how FileSafe works as it doesn't interact with files stored on your computer (unless I've overlooked something). Have you heard of anyone else getting it to work?

**Comment by nuke807** [comment]
No, I have my SN backups going to OneDrive and I want to store my attachments in there as well. Been trying lots of different combos for credentials and haven't found the magic key for it.

Thanks,

**Comment by JaspalSuri** [comment]
I apologize for misunderstanding. I thought there was an option to connect to OneDrive directly instead of a WebDAV option and I should have tried it out sooner. I did take note of it, though! I will get in touch with the team for further assistance.

**Comment by effieeee** [comment]
Closing since FileSafe has been deprecated
