### ISSUE TITLE
Unable to login / register on the self-hosted app

### ISSUE THREAD

**Issue by DarkScientist** [standardnotes/forum#908]
Hi,
I've installed the Standard Notes app on my raspberry pi through Syncloud.

However, I get the error "A server error occurred while trying to sign in. Please try again."
The web app works, but I get this error on the desktop apps. 
Here is the developer console :
https://i.imgur.com/Hm9nWNw.png

Thanks for your help !

**Comment by JaspalSuri** [comment]
I'm sorry that you're unable to login to the desktop app on your Raspberry Pi. 😞 

Could you let us know which OS you've chosen to run (in case it's not the default one) and elaborate a bit more on what Syncloud is? 

I've passed this along to the team for further review!

**Comment by DarkScientist** [comment]
Thanks for your answer ! 
Syncloud is an OS ran on your Raspberry Pi. It offers you many apps to install on your pi through a Web panel, and each app is installed in something we can compare to a docker container and is reachable in a subdomain.

However I've found an issue to fix that : when I was on the Web App of my raspberry pi, I saw that the sync server was set on "api". So, on all my mobile and desktop apps, I've added the "/api" endpoint to my server's URL and that worked !

**Comment by Intensity** [comment]
@DarkScientist : Just curious, did you specify a port (like `:3000`) in the Server URL? And do you know if the sync server setup for Syncloud was likely derived from the docker-compose from the `standardnotes/syncing-server` repository?

I'm asking for myself, and for any others who get blocked in the way I seem to be blocked now. At the moment, I see the same error that you saw, but I don't know what to even specify for Server URL (or `SF_DEFAULT_SERVER`, for that matter, if different) when the syncing server appears to only listen on port 3000.

**Comment by johnny243** [comment]
> And do you know if the sync server setup for Syncloud was likely derived from the docker-compose from the standardnotes/syncing-server repository?

Looks like they are using a [Go implementation](https://github.com/tectiv3/standardfile) as the syncing server.

The following is mentioned in their readme:

> You may require to add /api to the url of your server if you plan to use this server with https://standardnotes.org/

Try something like: `https://your-domain/api`

> the syncing server appears to only listen on port 3000.

Their implementation seems to be running on [port `8888` by default](https://github.com/tectiv3/standardfile/blob/1981630c3000b98927ad519b7198600894fa8acb/standardfile.json#L2).
