### ISSUE TITLE
Search searches within notes as well as titles

### ISSUE THREAD

**Issue by lucasrothman** [standardnotes/forum#914]
Searching currently searches the content of notes as well as the title. Suggest making a setting to turn this off at least for protected notes and making searching within a note possible only when that note is already opened.

**Comment by JaspalSuri** [comment]
Thanks for your feedback, I'll pass it along to the team!

The protected notes currently have UI protection, so that's probably why they show up in the search results. I'll put in a request for more granular search options with the features you've mentioned.

**Comment by effieeee** [comment]
Closing, already implemented!
