### ISSUE TITLE
Dark Theme inverting on android

### ISSUE THREAD

**Issue by iedd** [standardnotes/forum#918]
On a Moto X4 phone, with night mode set to 'always on' (in developer options), and theme set to dark, standard notes appears to invert all dark themes and present all white backgrounds. I haven't been able to recover the dark theme appearance since this happened several weeks ago. Themes continue to work on desktop. 
Please let me know any workaround or advice to try and further debug.

**Comment by JaspalSuri** [comment]
Hi, I’m sorry to hear that. Can too long-press individual dark themes within the Android app to redownload them and see if that fixes things?

**Comment by iedd** [comment]
Ah, that suggestion seems to work!! Thanks for the tip, and all your efforts!

**Comment by iedd** [comment]
Ah, that suggestion seems to work!! Thanks for the tip, and all your efforts!
