### ISSUE TITLE
Delete multiple notes?

### ISSUE THREAD

**Issue by uiai** [standardnotes/forum#92]
Hi! Is there any way to delete multiple notes? The ENEX I've imported from Evernote had a lot of duplicates,
 and it's tiresome to delete them one by one...

**Comment by mobitar** [comment]
No I'm afraid not. You can look at the Data Dashboard via Account -> Advanced -> Data Dashboard, but that only shows encrypted content. This might be something we roll out in the future.

**Comment by uiai** [comment]
Oh, bummer. I guess I'll just do it one by one for now.

**Comment by george0abitbol** [comment]
I cannot see the Account => Advanced => Data Dashboard menu in the Desktop App
![standard notes_2018-02-19_13-38-43](https://user-images.githubusercontent.com/9820806/36378212-3f2086a0-157a-11e8-8830-ea7ef1547fe2.png)

**Comment by mobitar** [comment]
This has been removed in v2 in favor of an upcoming "bulk management" extension. Sorry for the inconvenience. In the meantime, if you'd like your data deleted, either delete your account via standardnotes.org/reset, or shoot me an email at mo@standardnotes.org.

**Comment by mobitar** [comment]
Update: You can now use the Batch Manager extension for this.

Extensions -> Batch Manager -> Open.

(Only on web as of 2/28/18, coming to desktop soon.)
