### ISSUE TITLE
SN lags and reacts slowly to input after unlocking

### ISSUE THREAD

**Issue by jrabensc** [standardnotes/forum#920]
For a few weeks now SN **sometimes** start to lag and reacts slowly to input after I unlock it.

Here's a screenshot of the console:

![image](https://user-images.githubusercontent.com/6616405/78053612-2364b780-7381-11ea-9c0e-1a0d72e7a7a1.png)

As you can see, the tag is missing too. I cannot screenshot it but the cursor is switching fast between the on-link cursor and the standard pointer.

Running the latest SN on latest Windows 10 Pro.

**Comment by JaspalSuri** [comment]
I'm sorry to hear that. I'm afraid this issue doesn't affect my Windows 10 Home machine. 

The console says that a slow network is detected. What are your download/upload speeds from your ISP? Can you check with [Fast.com](https://www.fast.com)? Are you using a VPN?

Can you expand on the `objects` in the console, blur out any sensitive information, and provide an updated screenshot? Please refer to the image below, thanks!

![CleanShot 2020-03-31 at 21 27 40](https://user-images.githubusercontent.com/44656000/78099362-8280f700-7396-11ea-95ca-76dd86b1cd35.png)

Which Windows 10 Pro features are you currently using? (e.g. Remote Desktop, BitLocker, disabling certain Group Policies (you don't have to specify which ones yet), etc.) 

How many notes do you have on your account and how "large" are they on average?

What extensions do you have installed?

Thanks for letting us know about this! I'm sorry about the inconveniences this is causing.

**Comment by jrabensc** [comment]
The new screenshot is from a different state of the app since I killed the process yesterday. But probably the errors are the same?

![image](https://user-images.githubusercontent.com/6616405/78143915-3209a800-742f-11ea-88e5-9480bd9819dc.png)

I am not using a VPN, here is my speedtest:

![speed](https://user-images.githubusercontent.com/6616405/78144010-52396700-742f-11ea-8779-ff64c91fdec1.png)

This problem sometimes occurs at my office using a Gigabit line.

I am using no Windows 10 Pro features except for full disk Bitlocker encryption.

I have around 211 notes stored in SN, most of them are just some links. The biggest one has about 1000 lines of text.

Installed extensions: Midnight, No Distraction, 2FA, Action Bar, Batch Manager, Cloud Link, Extensions, FileSafe, Folders, Quick Tags, Advanced Markdown Editor, Code Editor, Indent Editor, Standard Sheets, Listed, Note History Action Menu, Google Drive Sync, Note History Server Extension

I can send you the whole log in Slack if needed.

**Comment by mobitar** [comment]
I believe the upcoming release should address this issue. It has to do with starting SN while you have extensions enabled. Please look out for 3.3.4 and let us know if that fixes your issue.
