### ISSUE TITLE
AppImage hashes still broken/unverifiable ?

### ISSUE THREAD

**Issue by codenow77** [standardnotes/forum#921]
Hi,

I've been following this thread (about not being able to verify Linux AppImage hashes) for over a month now. Will this be resolved anytime soon ?

https://github.com/standardnotes/desktop/pull/474

Thanks

**Comment by mobitar** [comment]
Sorry no action on this one yet. For now make sure your AppImage file name matches the name in the sums file.

**Comment by baptiste-grob** [comment]
Should be good now: https://github.com/standardnotes/desktop/releases/tag/v3.4.2-beta1
