### ISSUE TITLE
close a note manually

### ISSUE THREAD

**Issue by namsuh** [standardnotes/forum#924]
Hello

How I can close a note manually? 
When i am ready with a note, then it remains open and readable in the right window. Only when i open another note, it is closed. Some ‚sensitive‘ notes should be closed immediately.

**Comment by baptiste-grob** [comment]
Can you describe your use-case some more ? We already have quite a few UI options like protecting notes, hiding note preview, passcode-lock for the app… All of that on top of strong encryption 🙂

**Comment by namsuh** [comment]
I will try it: :-)
- After opening a -protected- Note, i write something, one, two lines. That‘s all. 
- I change then to another app, e.g. safari,
- again another app, and so on
- after that I return to Standardnotes. When I open it, the previous text is still visible and readable, although he is protected.  
- And the same behaviour can be seen with new created notes.  After creating a new note which is immediately protected, the text is still visible after working with other apps and then returning to standardnotes.
 
I hope it was understandable, my english is not so good  :)

**Comment by baptiste-grob** [comment]
Yes, I got what you meant! While that is currently not the case, the timer for protected notes should probably start when focus is lost. Tagging @mobitar to correct me if this is intended behavior :)

**Comment by mobitar** [comment]
The only way to truly protect sensitive notes locally is to lock the app after you are done using it. You can set Passcode Lock to lock "Immediately" when it loses focus.
