### ISSUE TITLE
Self-Signed certificates

### ISSUE THREAD

**Issue by git-noise** [standardnotes/forum#925]
Hello,

I hope that you are well.
I wanted to know if there is a way for the desktop application to trust self-signed certificates in cases of self-hosted deployment.

Many thanks,

Best,

**Comment by baptiste-grob** [comment]
(Transferring to the forum, maybe some people have tried this before)

**Comment by git-noise** [comment]
Hello,

Thanks for the transfer. So I did a few checks and it seems that on debian-like OSes at least, having the certificate in the OS trust-store if not enough. If anyone knows where the trust-store is taken from, would be much appreciated.

Many thanks,

Best,

**Comment by baptiste-grob** [comment]
You could fork the desktop app and look into this API: https://www.electronjs.org/docs/api/session#sessetcertificateverifyprocproc

**Comment by git-noise** [comment]
Thanks a lot for the pointer, I will look into that! Closing for now, will update if needed. Thanks!
