### ISSUE TITLE
Add TouchID support for macOS?

### ISSUE THREAD

**Issue by Marcopohlo** [standardnotes/forum#927]
Hi,

Awesome project, thank you for that!

I was just wondering if you are considering adding touchId support for macOS. Electron supports it from version 6. 

Thank you

**Comment by Marcopohlo** [comment]
Yes, I meant exactly that :) It's great on iOS (with TouchID/FaceID) would be great on macOS as well.

**Comment by baptiste-grob** [comment]
Duly noted!

**Comment by RonanCodes** [comment]
I would also really appreciate this feature.

**Comment by m-Aurelius** [comment]
I would also like to see this. Most other notes apps with "secure notes" include this.

**Comment by jackhannigan** [comment]
Just wanted to add another comment supporting this idea.

**Comment by myreli** [comment]
Duplicates https://github.com/standardnotes/forum/discussions/2524
