### ISSUE TITLE
iOS Simple Task Editor doesn't display the stored tasks

### ISSUE THREAD

**Issue by gabor-meszaros** [standardnotes/forum#929]
I have a note with tasks managed by the Standard Notes desktop client (3.3.5) with Simple Task Editor. 

When I want to read and manage these tasks on my iPhone Standard Notes (3.0.21), the Simple Task Editor doesn't display the tasks but only the light grayed "Open Tasks" and "Completed Tasks" texts. If I switch to the Plain Editor the tasks are there with the usual syntax ("- [ ] Lorem ipsum...").

I tried to delete all the tasks (i.e. an empty note), but even in that case the iOS Simple Task Editor doesn't have the input field to add a new task.

I have a subscription since ~4-5 months, and it worked at the beginning. I don't know when did it go wrong. Feel free to ask more information about the environment. iOS version is 13.3.1

**Comment by bryvin** [comment]
Do you have any theme in use other than the Blue or Red theme on the iOS app? If so can you try long-pressing on the theme name in the Settings menu and choose the "Redownload" option? At the very least try switching themes.

Also do you experience issues with any other editors or just the Simple Task Editor?

**Comment by gabor-meszaros** [comment]
@bryvin I don't have any themes other than the Blue and the Red ones. I was on the Red one (actually I don't know why, I liked the Blue better and I think that was what I selected at the beginning), but switching the theme to the Blue made the Simple Task Editor work. I switched back to the Red just to see if that was the issue, but now it also works with the Red. Anyhow, I am going to use the Blue.

Thank you for the help, I am amazed by the speed of the support. I wish you a nice long weekend!

**Comment by bryvin** [comment]
Perfect, thank you for getting back and letting us know. There was an issue that shipped in the latest version that did a bit of conversions of the stored theme data. This caused Editors to not load in some circumstances; switching overwrites the saved theme data and thus fixes the loading issue. 

Enjoy your weekend as well and stay safe!
