### ISSUE TITLE
feature request: find (and replace) functionality

### ISSUE THREAD

**Issue by guydog** [standardnotes/forum#93]
Hi, a feature I think SN should have is a "find" (at least) and replace" dialogue within the text of a single note, associated with a keyboard shortcut (possibly the usual CTRL+F).
Thank you
G

**Comment by mobitar** [comment]
Search and replace might be encroaching onto "advanced text processor" functionality, but I agree note text search would be nice for the desktop app. For now you could use the web app which will use your browser's built in search functionality.

**Comment by lucasgonze** [comment]
I also would like a find feature. Not having it forces me out of SN.

**Comment by mahyar** [comment]
Even TextEdit can find in place ;)

**Comment by effieeee** [comment]
See here: https://github.com/standardnotes/forum/issues/102
