### ISSUE TITLE
Can't restore to a given revision when using Simple Markdown Editor

### ISSUE THREAD

**Issue by x80486** [standardnotes/forum#931]
The `Simple Markdown Editor` is in the spot for me :wink:

If I make changes on a given note, several times, so you have different revisions, any time I try to revert the note in question to a previous revision I get a message like:

> The extension Simple Markdown Editor is trying to save, but it is in a locked state and cannot accept changes.

...followed by this stacktrace on the Console (`Developer Tools` toggled):

```javascript
  | MarkdownIt.parse | @ | index.js:518
-- | -- | -- | --
  | MarkdownIt.render | @ | index.js:543
  | (anonymous) | @ | Home.js:209
  | (anonymous) | @ | dist.js:253
  | handleMessage | @ | dist.js:95
  | messageHandler | @ | dist.js:45
  | (anonymous) | @ | dist.js:64
```

I'm under Arch Linux `Linux uplink 5.4.31-1-lts #1 SMP Wed, 08 Apr 2020 08:29:49 +0000 x86_64 GNU/Linux` and using the version `3.3.3` of the AppImage.

**Comment by baptiste-grob** [comment]
Hey @x80486, thanks for the report. I can't reproduce this I'm afraid, does this behavior occur with every editor, only non-plain text editors or only the Simple Markdown Editor?

**Comment by x80486** [comment]
It looks like, in my case, it happens with both, Simple Markdown Editor and the default one: https://streamable.com/0b9v5l

**Comment by baptiste-grob** [comment]
Thank you so much for the video! I think this issue may be related to this one: https://github.com/standardnotes/web/issues/394
Does that sound right?

**Comment by x80486** [comment]
Looks like it's very similar, if not the same.

By the way, I removed the `Simple Markdown Editor` and I don't see it when I try to install it again. Is that a glitch or was it removed?
