### ISSUE TITLE
tags do not sync correctly from linux to android

### ISSUE THREAD

**Issue by ugobob99** [standardnotes/forum#933]
Added notes with tags in desktop app (3.3.5 on linux): the notes do show up in the android version (3.0.21), but untagged (although the tags appear in the list of tags).
Added notes in android version with new tag, sync-ed ok with correct tags.
After further use, linux version keeps reading the correct tags, android version does not.

**Comment by JaspalSuri** [comment]
Hi, may I ask what Linux distro you're using?

**Comment by ugobob99** [comment]
using Linux Mint 19.3 Tricia 64 bit (cinnamon edition), which is based on Ubuntu 18.04 LTS.
However today I found all tags to be correct in both android and desktop.
A simple note/tag creation test worked. Two days ago however I did a few work on some tags (cancelled some, changed other, renamed, added), maybe that caused the issue.

**Comment by JaspalSuri** [comment]
That's good to hear! Thanks for the details! I'll try it once more on Ubuntu 18.04 LTS.
