### ISSUE TITLE
Headings ghosting in Fancy Markdown mode

### ISSUE THREAD

**Issue by jbm9** [standardnotes/forum#934]
When adding a heading in Fancy Markdown mode, I get weird ghosting of the text, as seen here:

![image](https://user-images.githubusercontent.com/87954/79081076-ed073080-7cce-11ea-9f56-d9079f2e47f5.png)

When I zoom in a bunch, it seems to "go away."  Though the text looks weird, with a strange blue/black "border" thing going on:

![image](https://user-images.githubusercontent.com/87954/79081109-335c8f80-7ccf-11ea-9691-9bbf8db8b36c.png)

I can't seem to find this in my browser's developer tools, so I can't see what's actually happening there.  My guess is that there's some annoying font rendering difference when it tries to overlay the color on top of the text?

This is on Linux (Ubuntu 18.04 LTS), with Chrome Version 81.0.4044.92 (Official Build) (64-bit).  All packages on my system are up-to-date, so I don't think this is a particularly weird corner case or anything.

Let me know if there's anything I can do to help troubleshoot this further, and thanks for making a product that is intended to last (and also lets me keep my stuff)!

**Comment by JaspalSuri** [comment]
I can reproduce this issue within the desktop and web apps on macOS and Ubuntu 19.10 for the Markdown Math editor. Thanks for your feedback! I'll pass it along to the team. :) 

> Let me know if there's anything I can do to help troubleshoot this further, and thanks for making a product that is intended to last (and also lets me keep my stuff)!

Thanks for the kind words! Let us know if you have any questions!

**Comment by effieeee** [comment]
Math Markdown/Fancy Markdown is now deprecated :( Though you may still find it here: https://github.com/standardnotes/plugins
