### ISSUE TITLE
Keyboard shortcuts generally not working under GNU/Linux

### ISSUE THREAD

**Issue by hyphone** [standardnotes/forum#937]
Hello and good day,

the keyboard shurtcuts defined in the notes.js controller (like ctrl+n and ctrl+f) are not working on GNU/Linux. The genereal Electron shortcuts (like ctrl+w) are working.

I use the Snap-version but also tried the current master.

**Comment by marcolaux** [comment]
does closing the ticket mean that there won't be keyboard shortcuts? :)

**Comment by effieeee** [comment]
Hi @hyphone while we haven't really firmly said "no" to keyboard shortcuts just yet, I can at least say that it's definitely not part of the immediate development goals or roadmap right now :(

However, I'm also keeping keyboard shortcut requests tracked on this particular thread: https://github.com/standardnotes/forum/issues/1511

**Comment by marcolaux** [comment]
thank you very much for the clarification

**Comment by steel-steven-87** [comment]
It is a pity that a modern text editor doesn't have the basic shortcuts. This is one of the reasons I'm looking for alternatives because while I like the idea of Standard Notes, the lack of shortcuts make the work terribly inefficient

**Comment by marcolaux** [comment]
> It is a pity that a modern text editor doesn't have the basic shortcuts. This is one of the reasons I'm looking for alternatives because while I like the idea of Standard Notes, the lack of shortcuts make the work terribly inefficient

please don't double rant. the other issue clearly states that this feature is implemented now.
