### ISSUE TITLE
Linux no longer offering to integrate AppImage since 3.0.20

### ISSUE THREAD

**Issue by phipolis** [standardnotes/forum#939]
[Gnome 3.32.2 on Fedora 30] 

With every version through 3.0.19, I would download the -x86_64.AppImage build and mark it executable. Launching it in the Gnome file browser would then display a dialog asking if I want to integrate the new version with the system. Answering yes would cause the app to show up in system App lists.

Starting with 3.0.20, Standard Notes opens without displaying the integrate with system prompt. This is inconvenient, because it no longer shows up in the system launcher.

I don't see a code change in 3.0.20 that seems likely to be responsible. I assume it was a change to the building/packaging process. I notice the -x86_64 is dropped from the file name starting with the same release.

**Comment by geragio** [comment]
Any update on this issue?
The problem persists using Standard Notes 3.4.1 on Gnome 3.36(Fedora 32)

**Comment by phipolis** [comment]
@geragio This behavior was very convenient, but it was provided by electron-builder. Electron-builder no longer bundles the integration dialog, and their position is that the project [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/) should be installed on the system instead.
The

**Comment by phipolis** [comment]
[continued] One can:

- Install AppImageLauncher themselves,
- Petition their Linux distribution to include AppImageLauncher or similar functionality, or
- Petition electron-builder to reconsider their change

I don't believe there's anything StandardNotes can do here.
