### ISSUE TITLE
[URGENT] accidentally merged notes - restore previous version  

### ISSUE THREAD

**Issue by guydog** [standardnotes/forum#94]
I did a big mistake accessing SN form the browser as I let "merge local notes": now I end up with duplicated notes and I have the feeling I lost some content (or is it impossible?).

I did not installed previously the "notes history" extension, nor the auto-sync with Dropbox extension (don't know why, stupid guy): is there a possibility to restore or to have access to the previous version of the note (e.g via Dropbox)?

I hope you can help me (maybe I am too tired).
Thank you
G

**Comment by mobitar** [comment]
Hey @guydog, I had initially thought that merging local wouldn't overwrite remote notes. But I wanted to confirm before responding so I just tested it out, and indeed, merging local will overwrite notes coming in. This must be some sort of regression as it wasn't designed to do this.

Very sorry about this. I can restore your notes from our nightly database backups. Please email me at mo@standardnotes.org from your account email to get started. Also mention that last date and time where all your notes were intact.
