### ISSUE TITLE
FileSafe component installed twice

### ISSUE THREAD

**Issue by leglock** [standardnotes/forum#943]
I am using Standard Notes v3.3.5 on Windows 10 Pro (1909). I'm not sure if this is a defect or I somehow have a bad configuration.

When I view installed extensions, FileSafe is listed twice:
![image](https://user-images.githubusercontent.com/5297922/79587052-90719000-8097-11ea-98c8-01f51a5053f5.png)

Also when on a note, I see two FileSafe buttons at the bottom:
![image](https://user-images.githubusercontent.com/5297922/79587108-a2ebc980-8097-11ea-996c-7a461096df40.png)

I can't figure out anything that differentiates the two FileSafes I have installed. I have uploaded some files already, so am reluctant to just uninstall one - I don't want to accidentally lose the link to those files.

**Comment by JaspalSuri** [comment]
Thank you so much for reporting this and for the helpful screenshots! I'm sorry about the confusion that it's causing. 

Do you see this when you log into the [web app](https://app.standardnotes.org) as well?

I uninstalled the FileSafe extension, reinstalled it, deactivated and reactivated it initially, and finally restarted the app; it's working well so it _should_ be safe to uninstall one of the extensions. However, I would recommend waiting until we figure out what's going on. 

Can you open the inspector tools by pressing `ctrl+shift+i` and going to the console, clearing it, and then opening the extensions menu to deactivate and reactivate each FileSafe extension separately? If it produces anything in the console, please share a screenshot of it with us here.

**Comment by leglock** [comment]
Thanks for the quick reply @JaspalSuri. 

> Do you see this when you log into the web app as well?

I just tried from the web app and am seeing the exact same behaviour.

> Can you open the inspector tools by pressing ctrl+shift+i and going to the console, clearing it, and then opening the extensions menu to deactivate and reactivate each FileSafe extension separately?

Nothing appears in the console when deactivating / reactivating either of the extensions. 

One thing I did just notice that may be telling is when I expand both FileSafe windows at the bottom of a note, they both appear to reflect the exact same data:
![image](https://user-images.githubusercontent.com/5297922/79622749-1fa19680-80de-11ea-8c27-3e296aafde16.png)

**Comment by JaspalSuri** [comment]
Ok, thanks for confirming that. I would suggest going ahead and uninstalling one of them. If they were to both disappear somehow, then reinstall the extension and restart the desktop app.

**Comment by leglock** [comment]
> In that case I would suggest going ahead by uninstalling one of them. If they were to both disappear somehow, then reinstall the extension and restart the desktop app.

I just deactivated and uninstalled one of them, then restarted the desktop app for good measure. I confirmed that the remaining FileSafe still has the same connection and files, and those files still display properly on the note. 

All seems well in the world now. Thank you!
