### ISSUE TITLE
How to merge tags 

### ISSUE THREAD

**Issue by Doidalsas** [standardnotes/forum#944]
I have two tags, each with numerous notes in that group. 

I'd like merge them together so that they're all under the one tag/group. 

However, I can't seem to figure out a way to do this except by re-tagging each individual note. 

Is there a way to batch re-tag all of the notes?

**Comment by JaspalSuri** [comment]
I’m afraid that we currently don’t have a way to batch re-tag notes, but it’s on our roadmap! 

While using the desktop app, you could try dragging one tag underneath the other tag so that they’re physically closer together. 

To separate them, drag the nested tag to the All “tag”.

**Comment by Doidalsas** [comment]
Thanks Jaspal. Good to know I wasn't missing something. Cheers
