### ISSUE TITLE
Merge Markdown Math into Markdown Pro?

### ISSUE THREAD

**Issue by AlJohri** [standardnotes/forum#946]
I would really like to have basic latex functionality via `$$` in Markdown Pro. Is there any chance we can make this happen? I'm using Markdown Math right now but it's just not as full featured as Markdown Pro. It requires split screen which doesn't work great on mobile, for example and doesn't have a way to switch to only edit mode or only preview mode.

**Comment by mobitar** [comment]
We don't have any plans for this I'm afraid, as these two editors are two completely different setups and architectures. But I hear you that it would be great to have one perfect MD editor rather than a collection. We're not quite an editor-building company (yet, I suppose), but if we ever have the capacity to develop our own editor, these are the kinds of things we'd take into consideration.

**Comment by AlJohri** [comment]
That's really unfortunate. Can you re-use existing open source editors like [MarkText](https://github.com/marktext/marktext)?

![image](https://user-images.githubusercontent.com/2790092/79990809-81b42000-847f-11ea-96e7-8b739d2afa46.png)

**Comment by AlJohri** [comment]
@mobitar where is the repo for the markdown pro extension? I only see the following:

https://github.com/sn-extensions/math-editor
https://github.com/sn-extensions/markdown-basic
https://github.com/sn-extensions/minimal-markdown-editor

**Comment by JaspalSuri** [comment]
It's located [here](https://github.com/standardnotes/advanced-markdown-editor): https://github.com/standardnotes/advanced-markdown-editor

**Comment by 17prime** [comment]
It seems like https://github.com/marktext/muya was extracted from marktext to serve as a browser based markdown editor component apart from electron --- but the muya repository appears essentially dead while the active muya codebase still resides within the marktext repository. Be interesting if someone wrapped muya  with the sn bridge ...

**Comment by effieeee** [comment]
Not sure if this will still be worked on since Markdown Math is now deprecated :(
