### ISSUE TITLE
Editor window not full width

### ISSUE THREAD

**Issue by AlJohri** [standardnotes/forum#947]
I somehow keep running into situations where the editor window becomes not full width. I can of course, drag it to fix the issue.

![image](https://user-images.githubusercontent.com/2790092/80003985-c778e480-848f-11ea-9a7e-dfc26e8e5c25.png)

I'm not entirely sure how it happens yet... but I make frequent use of "Windows Left arrow" to move the window to the left side of my screen and the "distraction free mode" button on the bottom right hand corner. Could be related.

I'll post more details if I am able to more consistently reproduce the issue.

**Comment by JaspalSuri** [comment]
Hi @AlJohri,

Please drag it to the right side until it snaps into place and then go to Options and click on Margin Resizers to turn it off. 

Let us know if you still run into the same issue after that!

**Comment by AlJohri** [comment]
@JaspalSuri I can definitely drag it back into place but I found it occasionally happens again.

How do disable the "Margin Resizers" option? I don't see an "Options" button.

**Comment by 17prime** [comment]
> @JaspalSuri I can definitely drag it back into place but I found it occasionally happens again.
> 
> How do disable the "Margin Resizers" option? I don't see an "Options" button.

At the top of the editor area (Options, Editor, Actions, Session Hisory), The Options menu has the "Margin Resizers" down under the Global Display section.

**Comment by AlJohri** [comment]
Wow, that was so simple! Thanks!
