### ISSUE TITLE
[Feature Request] Allowing Drag and Drop of notes into folders/subfolders.

### ISSUE THREAD

**Issue by Dreykku** [standardnotes/forum#949]
Hi,

Let's say I have something to write down fast. I open standard notes, click new notes in All notes, write the thing down. Once done, i have an untagged note that i have to classify. Correct me if i'm wrong, but right now we only have two ways of classifying individual notes. Either choose **beforehand** in which category to write it, or after writing it, add the same corresponding tag. So i would have to manually find the corresponding tag and/or possibly subtags and write them down one by one to classify my note every time i write a new untagged note. 

Having a drag and drop system would make the whole process of creating rapidly and then classify much easier and smoothly. Also if we have many untagged notes, in Untagged notes category, we could easily create one or several new folders fitting the theme of the notes (basically, the reverse process of what we are supposed to do right now), and then D&D the notes into the freshly created folder (or even older folders, our choice) to quickly tidy up the "Untagged" folder.  
 
Also, this idea combines very well with [my other feature request](https://github.com/standardnotes/forum/issues/948), since dragging to a color (once we know our color code) is so much faster than having to read and find a file name in a list, it would make us gain a substantial amount of time in the long run. We could classify notes without really having to look at the list of folders. 

Thank you for your attention.

**Comment by JaspalSuri** [comment]
Thanks for the feedback! I've passed it along to the team for review. :)
