### ISSUE TITLE
Mac Menu Bar

### ISSUE THREAD

**Issue by wychwood-digital** [standardnotes/forum#950]
Hi

I currently use Apple Notes + NoteFile (which runs in the menu bar on Mac for quick notes).

I have recently moved to Windows 10 as well as Mac and so need a new notes solution.

I have found Standard Notes and really love it - but the only thing is putting Standard Notes in the menu bar like NoteFile works.  Is there any way of doing this - or can it be added as a feature request?  

You have the ability to run Standard Notes on Windows in the tray so its the same idea.

Had a quick look and seems that Electron apps can run in the menu bar.  https://github.com/maxogden/menubar

Thanks

**Comment by christianhans** [comment]
Note quite the solution you're looking for, but one thing you can do with apps such as Alfred or Bettertouchtool is you can assign a key combination to toggle Standard Notes:

<img width="431" alt="Screen Shot 2020-04-25 at 6 35 34 AM" src="https://user-images.githubusercontent.com/355541/80277723-f9bc5900-86be-11ea-8a00-7c85f4dc19dc.png">

For me this even works better as I can just press the key combination to take or look up a quick note (and then press that same key combo again to hide SN). No mouse interaction required to pull up SN.

**Comment by JaspalSuri** [comment]
Hi, I'll put in a feature request for a shortcut that's accessible via the icon tray on Windows and menu bar on macOS. :)

To add onto what @christianhans suggested, you can use the Windows/Super key + the number where Standard Notes sits on Windows 10's taskbar. So if it's the fourth one from the left of the Start Menu, press `Super + 4`.
