### ISSUE TITLE
plus editor theming bug with midnight theme extension - chrome web client only

### ISSUE THREAD

**Issue by david-coneff** [standardnotes/forum#954]
I use the "midnight" theme extension for dark colors. When using the chrome webclient version of standard notes and switching to the "plus" editor that supports markup/formatting, the background of the editor on the screen turns white (the default color for the app) only in that segment of the screen - the rest of the app is themed correctly.

This doesn't affect the Windows 10 desktop app but does affect viewing notes in the web client in chrome.

video demonstration of this bug:
https://photos.app.goo.gl/wutFponAXYgdqdod6

**Comment by baptiste-grob** [comment]
Hey David, thanks for the video and supporting us with Extended :) Judging by the way the chrome window looks I'm assuming you're on windows? I can't seem to replicate the behavior you're describing but we have had cases of browser add-ons interfering with the extensions and themes 🤔 Have you tried disabling some of them (specifically ones that changes the app's CSS) for the web app?
