### ISSUE TITLE
Image Embedding and Encrypted Attachments

### ISSUE THREAD

**Issue by SuperKinh** [standardnotes/forum#96]
_Editor's note: This issue was originally posted to address a workaround to functionality that is no longer supported. The issue then spurred a discussion around the feasibility of encrypted attachments in Standard Notes._

October 2018 Update: [FileSafe](https://standardnotes.org/filesafe) is now available, and allows encrypted attachments. (No inline image support yet though.)

<details>
  <summary>Original Issue</summary>
Sooo.... I am not sure if there are any plans to improve implementation of embedding images but I figured a not so simple work around with the Markdown Editors that could be implemeneted as an extension or integrated into the file attacher extension.

1) Attach the the desired image to the documents with the file attacher extension

2) From the action bar, drop down to Manage Attachements and copy the link of the opened page

3) From this link you need to replace some parts of the link to navigate to your attached image

https://standardnotes.org/ext/file_attacher/b14e81ca-fa45-4a9e-abda-f9dfe567ab78/files?key=*******************your_personal_encryption_key********************&item_uuid=***********specific_document***********

to

https://standardnotes.org/ext/file_attacher/b14e81ca-fa45-4a9e-abda-f9dfe567ab78/download?key=*******************your_personal_encryption_key********************&file_path=/file_attacher/***********specific_document***********/name_of_image.png

(I figured this out by using action to download the file I attached to the document and quickly copying the link from the tab that it opens in my Chrome Browser, so that method also works)
Then input this link to the desired format for embedding images

The resulting code will look like
<
img src = "https://standardnotes.org/ext/file_attacher/b14e81ca-fa45-4a9e-abda-f9dfe567ab78/download?key=*******************your_personal_encryption_key********************&file_path=/file_attacher/***********specific_document***********/name_of_image.png">

Anyways, I am posting this hoping to see this tedious work around that already utilizes existing features to embed your own images to your documents.

I would try to send a push myself but I am not very experience at making and designing software

Loving this product by the way. So glad I bought a sub.
</details>

**Comment by mobitar** [comment]
@PopMachine wow, hell of a workaround :) Trust me, there's nothing I want more than to have inline attachments and a built-in attachments interface, but that stuff's hard and would detract from the main product right now, so it's postponed into the future. But, glad to see you have an interim solution.

**Comment by fluffymadness** [comment]
I really hope inline images e.g via drag and drop gets added in the near future.  I love to have my notes at one place. And right now if I want to write bigger notes with embedded images and tables, eg when I write some documention of something, I still have to use word or libre office and save it someplace else then my other notes.

**Comment by DreamFlasher** [comment]
@mobitar What's your estimate on the probability that this feature (inline images) will be implemented during this year (2018)? 
To me this is a crucial feature and currently blocking me from switching to standard notes.

**Comment by mobitar** [comment]
Very low chance of this year. Probably 2019.

**Comment by willc** [comment]
I too would like to add my voice in support of supporting inline images. This is the crucial feature preventing me from switching to Standard Notes.

**Comment by gelviis** [comment]
Really hope this this feature is not implemented. SN to me is a simple note taking app not another place I have photos hanging around. Inline images is feature bloat IMO.

**Comment by DreamFlasher** [comment]
@gelviis You fundamentally don't understand the design and principles of standard notes. Did you have a look at extensions and how features are added optionally? I'd recommend reading up on it.

**Comment by gelviis** [comment]
@DreamFlasher that's a bit harsh...

**Comment by willc** [comment]
A bit harsh, perhaps, but not entirely incorrect.
I don't think anyone is intending this to be a photo storage app, as there are plenty of better solutions for that. Rather, being able to take screenshots and embed them inline would be invaluable for many people, including developers, designers, pentesters, or engineers.

You get out of SN what you put into it, so if you don't want photos "hanging around," don't put them in there.

**Comment by mobitar** [comment]
All valid points :) It would definitely be an extension if it were to happen, and not native. Here's why I'm resisting working on this for now:

1. Encryption. Photos would need to be encrypted. There's no mechanism right now to share your encryption keys with extensions. So somehow, the extension would need to encrypt photos. This would probably require you inputting a custom key. Then, what about if you want to change the key? What about if you forget the key? A really challenging problem.
2. Mobile. Extensions are not available on mobile. We already get a barrage of "when will editors make it to mobile?" I would not be able to handle another barrage of "why can't I view my attachments on mobile?".
3. Storage and limits. Where would the files be stored? What limitations would we have to put in place? Would it be another paid tier on top of Extended, or part of the current offering? Most likely, this will involve a whole other level of costs, meaning we'd have to modify Extended to add storage tiers. A very hard problem.
4. Support. Given the engineering feats required for this problem, bugs and issues are bound to occur. I can't currently afford more problems. Focus helps keep a more peaceful life and business.

With all these reasons combined, you can see why I'm not rushing to create this. I still want to focus on the fundamentals. We're a very, very far way from this.

**Comment by gelviis** [comment]
@mobitar spot on. Thanks for clarifying.

**Comment by fqure** [comment]
Maybe we could consider a survey on your above 4 points. On item #1, I for one wouldn't need the photo/image itself encrypted, just the link (which by being inside the note itself would be encrypted). So maybe this beta v 0.1 extension would have a disclaimer that the standard server images folder is not encrypted?

**Comment by willc** [comment]
I don't care about mobile, personally, though I can see that others might. Since images don't work well in mobile, leave them out of it. Support them in the browser/desktop. I don't need them to be encrypted either. I just need to drop images into my notes -- especially screenshots. I don't care where they are stored, though if they are stored in my Google Drive by association, that'd be fine. And they'd inherit encryption that way, no?

**Comment by fqure** [comment]
Agree about simplicity. There are 2 models for assets (images/video) to consider:

1. Encapsulated- The entire asset would need to be encrypted. I think you explained this above clearly
2. Externally linked– An extension:
    a) The main SN text area would need to be a drag and drop that creates a link.
    b) An external API call for write storage (Google Drive, Dropbox, Box, AWS etc) to then externally store the asset
    c) Stating the obvious, but the transport would need to be SSL

If the debate is 'everything needs to be encrypted' then option 1 would incur very large files or sql blobs-- a bloated SN. Large sizes also reduces portability and transport. Item 2. is currently already in the core as text only links.

Both scenarios would write the API as long string files names. Option 1 could leave it unencrypted and consider a script to post encrypt at a later stage of development (we're just re-ordering bits assigned to a key pair). In Option 2 scenario, encryption would be left to the external storage service, not Standard Server.

So this is really a debate of what system services a user's privacy. Is SN _part_ of a user's overall privacy or does it need to be the _entire_ stack for privacy? Also, if there were a breach of an external storage system, is the concern that SN would be blamed?

**Comment by willc** [comment]
> If users turn away from SN because it doesn't support images, it's not a huge issue. We select for users who want simplicity anyway.

As a user who appreciates simplicity, this seems like a simple feature. Drag/drop or copy/paste an image into your note. The complexity is on the back end, it would seem.

**Comment by mobitar** [comment]
>  would incur very large files or sql blobs-- a bloated SN

We usually refer to bloat in terms of experience and feature-set, not necessarily file sizes. If we were to use your Dropbox/Google Drive, and you wanted the images to be embedded in the editor, you would have to make the attachments publicly accessible via that link. It's just a privacy nightmare. Again, would rather do it right, than do it at all.

> this seems like a simple feature

There's no such thing as a simple feature ;)

Every feature is a marriage proposal.

**Comment by DreamFlasher** [comment]
My expectation from a user's perspective is that everything I put in SN is encrypted. So I think encrypted attachments is a necessary precondition.

**Comment by rrggrr** [comment]
@mobitar 

Sensitive to your concerns and with an eye toward making this as painless to implement as possible... perhaps the simple approach is this:

1. Pass the image/attachment - unencrypted - to MYSQL on insert.
2. Encrypt using mysql's AES_ENCRYPT() function, and store as a longblob.
3. Offer the service only to users hosting their own DB (eg. Heroku is dead simple to implement).

For users who need images or other attachments its trivial to implement. I can't see much impact on your infrastructure, but I admit I've not carefully reviewed the architecture.

Hope this helps.

**Comment by mobitar** [comment]
If we were to offer this, we definitely wouldn't alter our server infrastructure for it. We like to go in the way of extensions, not altering our sacred, working code ;)

But, I think I've already decided the architecture we'll be going with is offering encrypted attachments hosted by the user's own cloud provider (Dropbox, Google Drive, etc), rather than creating our own cloud/file infrastructure, which gives me anxiety just thinking about.

**Comment by DreamFlasher** [comment]
That's very reasonable. I've been thinking about that in more general terms before: Why do you actually want to handle the whole device syncing infrastructure and encryption at all (even for text notes)? Wouldn't it have saved you a lot of work if you would have built upon https://nextcloud.com/endtoend/ ?

**Comment by mobitar** [comment]
Just simplicity of use. It's not that bad. Would also rather not depend on another company.

**Comment by DreamFlasher** [comment]
Inventing your own crypto sounds not that simple at all... This always rings for me bells; "shouldn't there already be something which gives me end to end encryption for files?" (needn't be a cloud hosting service, could also have been something like truecrypt, there are for sure encrypted file system frameworks out there)
I mean, you depend on other software anyways (packages, your os...).

**Comment by mobitar** [comment]
It's already built..what are we even debating ;)

**Comment by DreamFlasher** [comment]
That's not an argument. And I am not debating ;) I was just curious -- because it doesn't make sense to me :) And even if it's already built: That's called refactoring ;)

**Comment by timmyomahony** [comment]
I would love to move over to SN but no image support is a deal breaker. I use Quiver on Mac to take notes and the ability to drop images into notes is one of its best feature. I'd recommend checking it out to see how it deals with note taking. It allows you to add section to a note, with each section having a different type: image, markdown, code, rich text etc. This allows you to build notes up with different data types.

**Comment by mllanes** [comment]
+1

**Comment by WTurunen** [comment]
Only thing holding me back from Standard Notes is attaching encrypted images/files to notes, so +1 from here.

**Comment by DreamFlasher** [comment]
This could actually be solved via Data URIs: http://en.wikipedia.org/wiki/Data_URI_scheme
This wouldn't require any additional encryption for files and for images I think this would actually be fairly clean. 

It can also be used for including any file, but the problem with it is that it's a lot harder to implement a feature of "open the file, edit the file, on save update the note with the updated file". But it's possible to include any file:
https://stackoverflow.com/questions/3916191/download-data-url-file

I would consider it fair to let users pay for storage above a threshold.

**Comment by mobitar** [comment]
This is not very practical with any image larger than a small icon. You'll quickly run into syncing bottlenecks and app performance issues.

**Comment by DreamFlasher** [comment]
That's unfortunate. Do you sync deltas? Then I don't see the syncing issues.

**Comment by mobitar** [comment]
No, tough (infeasible?) to do encrypted deltas.

**Comment by rrggrr** [comment]
How about this... Perhaps SN becomes a [Heroku Ecosystem Partner](https://www.heroku.com/elements/partner). The exponential benefit being the following:

- Encrypted file attachments via mySQL longblob AES encryption at database.
- Extension-based revenue model remains untouched.
- New user adoption/exposure by embracing the Heroku platform.
- Ease of integration with other ecosystem components.

**Comment by mobitar** [comment]
The important thing to remember is that there's a very clear distinction between Standard Notes the app, and Standard File the server. SF is the backend, and has a very simple and stringent protocol whose main tenet is simplicity and lack of growth. And SF has hardly changed at all over the last two years. We like to look at SF as "not ours to change", so, there are no custom server elements with Standard Notes. Any extension we build, even server side functionality like Dropbox backups, do not modify our server, but create separate architectures elsewhere that communicate with the base, unmodified server. 

All that to say, this won't be as simple as "creating a database column that allows longblob encrypted storage." Instead, we'd have to create an entirely separate server architecture that communicates using the SF protocol of simple object-based items. Anything is possible with this architecture, but it must be done in certain ways.

SF deals with items that carry arbitrary data. For encrypted attachments, here's the steps we would need to take:

1. Create a UI modal extension (similar to CloudLink) for Standard Notes that allows the user to sign up for a separate file-hosting account (by Standard Notes, but using a different server than the one used for your SN data). This component would need to also allow setting up an encryption key.
2. Create another UI component extension that sits in the editor area (similar to the Action Bar) that allows dragging and dropping files, and retrieving and displaying associated files for that note. This extension would handle encrypting/and decrypting, and would thus need to find a way to communicate with the first extension to retrieve the keys.
3. Create an independent server architecture that can retrieve and upload files to external cloud providers like Dropbox, Google Drive, OneDrive, NextCloud, etc (we wouldn't be offering our own storage; way too complex and out of scope for us.).

So, it's not impossible, but also not trivial. I'm open to it, but timing is important. I'm in no rush here. We're trying to be a sane, healthy company that is never in over our heads ;)

**Comment by DreamFlasher** [comment]
Well, if you are thinking about creating a new server architecture anyways, I still believe that standard notes should leave the whole syncing and encryption part to other software that is specialized on it. And instead focus on the notes part of it. 
One simple way of organizing things would be to have all notes in single files (or in a db, whatever is more convenient) and let https://librevault.com/ or https://nextcloud.com/ handle syncing and encryption. (Or reuse some of their code, or https://turtlapp.com) Funnily enough while searching for solutions to this I found: https://joplin.cozic.net/ -- they do the e2e and leave the sync to external services, which is kinda nice because then people can use dropbox etc. (but still I wouldn't like to do the e2e myself and leave that for an external software too).

**Comment by RemiDesgrange** [comment]
Don't want to re-start a flame war but all I can see here are complicated solutions : 
* external products
* blob in db (I though this debate was closed since S3 but I was wrong).

What I was thinking about is much much simpler : storing image as base64. It already work with markdown editor:

```
![Hello World](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAAAUCAAAAAAVAxSkAAABrUlEQVQ4y+3TPUvDQBgH8OdDOGa+oUMgk2MpdHIIgpSUiqC0OKirgxYX8QVFRQRpBRF8KShqLbgIYkUEteCgFVuqUEVxEIkvJFhae3m8S2KbSkcFBw9yHP88+eXucgH8kQZ/jSm4VDaIy9RKCpKac9NKgU4uEJNwhHhK3qvPBVO8rxRWmFXPF+NSM1KVMbwriAMwhDgVcrxeMZm85GR0PhvGJAAmyozJsbsxgNEir4iEjIK0SYqGd8sOR3rJAGN2BCEkOxhxMhpd8Mk0CXtZacxi1hr20mI/rzgnxayoidevcGuHXTC/q6QuYSMt1jC+gBIiMg12v2vb5NlklChiWnhmFZpwvxDGzuUzV8kOg+N8UUvNBp64vy9q3UN7gDXhwWLY2nMC3zRDibfsY7wjEkY79CdMZhrxSqqzxf4ZRPXwzWJirMicDa5KwiPeARygHXKNMQHEy3rMopDR20XNZGbJzUtrwDC/KshlLDWyqdmhxZzCsdYmf2fWZPoxCEDyfIvdtNQH0PRkH6Q51g8rFO3Qzxh2LbItcDCOpmuOsV7ntNaERe3v/lP/zO8yn4N+yNPrekmPAAAAAElFTkSuQmCC)
```

and should work with plus editor (just replace the markdown with HTML). The problem here is readability. I don't know if standard notes have a size limit for notes ? because with this solution it can be a problem. 

Here are though about integrating base64 images:
* we'll need an image converter, you import/drag'n'drop image in standard notes and it convert it in base64 (not hard)
* you can use footnotes to regain readability like:

```
 some text

![Hello World][helloworld]

some text

[helloworld]: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAAAUCAAAAAAVAxSkAAABrUlEQVQ4y+3TPUvDQBgH8OdDOGa+oUMgk2MpdHIIgpSUiqC0OKirgxYX8QVFRQRpBRF8KShqLbgIYkUEteCgFVuqUEVxEIkvJFhae3m8S2KbSkcFBw9yHP88+eXucgH8kQZ/jSm4VDaIy9RKCpKac9NKgU4uEJNwhHhK3qvPBVO8rxRWmFXPF+NSM1KVMbwriAMwhDgVcrxeMZm85GR0PhvGJAAmyozJsbsxgNEir4iEjIK0SYqGd8sOR3rJAGN2BCEkOxhxMhpd8Mk0CXtZacxi1hr20mI/rzgnxayoidevcGuHXTC/q6QuYSMt1jC+gBIiMg12v2vb5NlklChiWnhmFZpwvxDGzuUzV8kOg+N8UUvNBp64vy9q3UN7gDXhwWLY2nMC3zRDibfsY7wjEkY79CdMZhrxSqqzxf4ZRPXwzWJirMicDa5KwiPeARygHXKNMQHEy3rMopDR20XNZGbJzUtrwDC/KshlLDWyqdmhxZzCsdYmf2fWZPoxCEDyfIvdtNQH0PRkH6Q51g8rFO3Qzxh2LbItcDCOpmuOsV7ntNaERe3v/lP/zO8yn4N+yNPrekmPAAAAAElFTkSuQmCC Hello World base image
```


I think that this solution might be the simplest one _at first_. We can iterate on it but this will render nicely in list.standardnotes.org, be encrypted out of the box and does not require any changes to standard files server.

I can try making a PR on a test branch in https://github.com/sn-extensions/simple-markdown-editor (or minimal, or whatever markdown editor) to make drag'n'drop images convert to base64 (this mean file with mime-type of image/jp(e)g or image/png)

**Comment by DreamFlasher** [comment]
This has been proposed and discussed in this thread (https://github.com/standardnotes/forum/issues/96#issuecomment-386204043) before. I am still in favor of this.

**Comment by RemiDesgrange** [comment]
Oh... sorry didn't see it, I read to quickly...

**Comment by DreamFlasher** [comment]
Well I guess a PR would be very welcome, in the end nobody *has* to use the feature, if they don't like the downsides.

**Comment by JohJohOneThousand** [comment]
Here to add a little weight to the requests for inline/embedded images. It would be a killer feature and mean I could ditch Evernote.
Thanks for the great work on a great tool.

**Comment by mobitar** [comment]
Working on a prototype of this as we speak :) Now, it would only be attachments, like email attachments, and not inline. So you'd have to actually download them to preview them. Would that be sufficient for your use case?

**Comment by RemiDesgrange** [comment]
@mobitar Maybe make a PR as soon as possible, this way we could comment on the feature !

**Comment by mobitar** [comment]
It would be a separate extension. Basically it will be in the same position as the Action Bar, but will display your attachments (encrypted) and allow you to drag and drop and download the attachments to decrypt them. The attachments would be stored encrypted in your own cloud provider (Dropbox and Google Drive initially, with more options to follow).

**Comment by JohJohOneThousand** [comment]
This will be a great improvement, thank you! Inline, one day :)

**Comment by technicalguy** [comment]
When this extension is complete will you add support to your Evernote ENEX → Standard Notes Tool for images? I'm trying to decide if I should hold out a bit longer so that I can migrate all in one go, or if I should just ditch evernote now and try to get my images/attachments later...

**Comment by mobitar** [comment]
Because of the nature of the extension, it would be difficult to link the import process to the attachments extension. So I don't think this will be possible initially. You'd likely need to manually import attachments one by one. Hopefully as we expand the attachments product over time we can find solutions for incoming Evernote users.

**Comment by technicalguy** [comment]
Ah right, it's an extra layer of indirection. I also remembered that the mobile app does not support the extensions. Alas, after evaluating almost everything (except Keep and OneNote), I am still struggling to rid myself of Evernote. :'(

**Comment by kaushalmodi** [comment]
@mobitar Looking forward to inline or not image support. I want to port my Google Keep notes to here, but at the moment, I am losing all the media from there.

**Comment by mobitar** [comment]
Encrypted attachments are now available through FileSafe: https://standardnotes.org/extensions/filesafe

**Comment by technicalguy** [comment]
@mobitar does FileSafe work on mobile?

**Comment by mobitar** [comment]
Components like FileSafe in general are not present on mobile, but this is something we hope to get to in the near future.

**Comment by jdotjdot** [comment]
Would it be possible to build/fork a Markdown editor that makes image attachments _appear_ to be inline through some indirection?

What I'm imagining is a special Markdown image reference to an encrypted FileSafe image&mdash;this could either use a special URI (`![Cool Image](filesafe://path-to-my-image.png)`) or be granted some special syntax in a Markdown extension. The editor, when displaying the note, would fetch the attachment from FileSafe, decrypt it, and then temporarily base64-inline it in the rendered version of the Markdown.  The base64 inline would _not_ be saved with the raw text of the note, hopefully avoiding the note size bloat referenced above.   The primary reason to inline rather than just save the file locally and display with a local file reference is to handle concerns about the security of the image cache.

**Comment by mobitar** [comment]
Hmm..interesting idea. I think that might be possible, but would have to explore it more. What's the use case for inlining, in your opinion? I don't want to give the impression that these articles would be publishable to anywhere, because the displayed image is private and only exists in the current context. Though I suppose we can probably call that out so there's no confusion. But what kind of notes would you compose that would require inline images for private use?

**Comment by jdotjdot** [comment]
Notes, journal entries&mdash;I'll often take small screenshots of things I want to remember or keep an image of, insert them into the note inline, and then write commentary about them.

Is Standard Notes just not the right tool for my use case? Should I use Joplin or Crypt.ee instead?

**Comment by depelteau** [comment]
Screenshots inline are a must have. Honestly it is the only feature keeping me back from using SN fully.

**Comment by jdotjdot** [comment]
Frankly, I'd even be okay with the images inlined and saved to the note, even if it balloons the note sizes.  If it was a big issue for the shared service, I'd run my own SN server--or, maybe there's a way to have all notes backed by storage like S3 or Dropbox, like FileSafe offers.

**Comment by technicalguy** [comment]
@jdotjdot this was suggested above: https://github.com/standardnotes/forum/issues/96#issuecomment-409115541

**Comment by ajvsol** [comment]
For balancing image embedding UX with FileSafe's security I think this could be achieved with a similar UX to what I've seen done in [another app (video)](https://i.imgur.com/ThHKgK7.mp4). 

It uses a small button with an icon for the filetype and text for the filename ![](http://i.imgur.com/2pUfdRD.png) and on hover or mouse click it shows the image in a preview box. 

The attachment itself is formatted as a simple embedded image in Markdown  e.g. `![caption](http://i.imgur.com/GMfCpZB.png)`, but for FileSafe it could be something like `![caption](../attachments/GMfCpZB.png)`

Having the inline attachment button is in itself is a great upgrade and one step closer to image embedding. This can then be incrementally extended in the future to have preview extensions which display those attachments on mouse click, whether it be images, PDFs or whatever.

**Comment by zorglups** [comment]
I would really be your next Extended supporter but screenshot insertion inline (on all platforms) is the minimal requirement.
Seeing my use for technical notes, brainstorming notes, documentation, words only are no more enough.
I was soo happy to find a platform that allowed so many things (publishing as blog included) until I had to face the fact that I can't make the move without easy image support.

Sad, I'll have to stick to OneNote for now... and I hate it, really.

**Comment by mobitar** [comment]
The Bold Editor supports image insertion inline. This was released a few weeks ago.

**Comment by dreamflasher** [comment]
I love the speed in which you are developing @mobitar and that you are so close to the community/customers! Sounds like we can close this ticket‽ :)

**Comment by jdotjdot** [comment]
Strongly recommend highlighting this somewhere!  I am a long-time user who
has felt this pain and I had no idea it was released

**Comment by zorglups** [comment]
Hello. 

Thank you for getting back to us.

This is a good step in the right direction.
No brainer publication (Listed.to) is a big part of the reason I would migrate all my notes to StandardNotes.

The publication is not having the images (https://listed.to/V1EVdZpoAn).
Will you address this ?

I had a look at my Filesafe on Google Drive. The inline images are rather small json files.
This let me wish you may embed those json within the note itself.
You could do this for small inline images and use the Filesafe for larger images or files.

You would address the need of probably a vast majority of your users that only want to paste screenshots or small images to illustrate their notes/articles.
This would also let us view the images when offline (which is not the case with the Filesafe stored on another storage).

I really don't care about having yet another storage app. 

I want a Notes app that:
- Respects my data - SN does it.
- Is clean and simple - SN does it.
- Allows me to paste inline screenshots (cropped) and small images to enrich my articles/documents - SN somehow allow this to some extent.
- Is based on tags, with possibility of nested tags - SN allows this.
- Publish articles to a blog - SN does this.
- Publish articles privately - SN does this.
- Features Markdown editors - SN does this.
- Is multi-platform - SN does it.
- ...

What SN currently misses:
- Export of the images when publishing to listed.to.
- Offline access to images (not asking this for attachements or big images).
- Inline images in other editors (Markdown ones).

The export of the images being the most important one.

Thank you,

Pierre

**Comment by mobitar** [comment]
Appreciate the feedback @zorglups!

**Comment by CharlesCage** [comment]
I get the feeling that I'm missing something about inserting FileSafe images into notes. I see the copy, but when I insert the text I don't see any way to easily get back to the image.

**Comment by mobitar** [comment]
You can only paste the insertion link into the Bold Editor. Other editors do not support FileSafe previews inline.

**Comment by nblumoe** [comment]
Thanks for the great work on Standard Notes and making it Open Source.

@mobitar do you have any plans to add features that @zorglups mentioned above (https://github.com/standardnotes/forum/issues/96#issuecomment-502310021)?

**Comment by mobitar** [comment]
@nblumoe nothing concrete yet, but definitely want to head in this direction.

**Comment by nblumoe** [comment]
> @nblumoe nothing concrete yet, but definitely want to head in this direction.

Having images published to Listed would be amazing and my personal priority from that list. Looking forward to it, keep up the great work on Standard Notes! Thanks!  🙏

**Comment by effieeee** [comment]
Tracking further here: https://github.com/standardnotes/forum/issues/1762
