### ISSUE TITLE
Help on keyboard shortcuts

### ISSUE THREAD

**Issue by nsclong** [standardnotes/forum#961]
There are some keyboard shortcuts available, but it is unclear what they are. At the very least they should be detailed on the StandardNotes website.

I currently have a problem because of this. I have hidden the menu bar, and I don't know what the shortcut is to get it back again, so I now can't use the menu.

**Comment by mobitar** [comment]
Alt + M to toggle menu bar :) 

@TheodoreChu perhaps we can document whatever few shortcuts are available on docs?

**Comment by restructor1** [comment]
Alt+M is not working.

**Comment by TheodoreChu** [comment]
Alt + M only works when you are not using the theme menu bar. You can check this in View > Use Themed Menu Bar 

We have some keyboard shortcuts documented here: https://docs.standardnotes.org/editing and will be adding more :)

**Comment by jnials** [comment]
Yeah, that link to the shortcuts doesn't work.

**Comment by TheodoreChu** [comment]
Oops! We had just changed it. Here's the new one: https://docs.standardnotes.org/usage
