### ISSUE TITLE
[Feature Request] FileSafe thumbnails

### ISSUE THREAD

**Issue by tracyboehrer** [standardnotes/forum#962]
It would be helpful to have thumbnails when using "Show".  Probably since I use copy/paste to insert an image a lot, most of the filenames are "image.png".  So any chance of reuse is not really feasible.

That or allow changing the filenames.  I would assume deleting a note with an attachment does not delete the file in FileSafe?  If so, how does one manage the storage given the duplicate filenames?

**Comment by JaspalSuri** [comment]
Currently managing files in FileSafe is difficult and something the team would like to improve for version 4 of the app. I'll be sure to take note of your feedback regarding the file thumbnails!

**Comment by effieeee** [comment]
Attachments still not shown as thumbnail previews, but it's possible to rename files on the new native file attachment feature!
