### ISSUE TITLE
Markdown Pro Editor and checkboxes

### ISSUE THREAD

**Issue by tracyboehrer** [standardnotes/forum#964]
When I enter something like:

```
Items
- [ ] Item 1
- [ ] Item 2
```

In preview mode, the checkbox items are displayed with both a bullet and a checkbox.  Additionally, the checkboxes can't be checked/unchecked in preview mode (possibly this ability hasn't been added).

**Comment by JaspalSuri** [comment]
I apologize for the improper rendering and missing features. I'll pass it along to the team!

Currently the dev team is working on several things under the hood, so it will take some time before we can iron issues with the editors.

**Comment by mobitar** [comment]
Pull requests also accepted as well :) https://github.com/standardnotes/advanced-markdown-editor

**Comment by tracyboehrer** [comment]
Well if it helps, the EasyMDE also does it.  See demo at https://easymde.tk/

**Comment by tracyboehrer** [comment]
Here ya have it:  https://github.com/Ionaru/easy-markdown-editor/issues/136

**Comment by tracyboehrer** [comment]
Opened:  https://github.com/markedjs/marked/issues/1667

**Comment by tracyboehrer** [comment]
Check out https://easymde.tk/next
