### ISSUE TITLE
Customising Markdown Minimalist editor

### ISSUE THREAD

**Issue by Mooie** [standardnotes/forum#966]
Is it possible to customise the Markdown Minimalist editor? Specifically, I'd like to change the font to a monospace variety and to keep all headings the same point size as the text.

**Comment by JaspalSuri** [comment]
Currently this isn't possible, but we've noted requests for this in the past, so I will add your +1 to it. :)

**Comment by Mooie** [comment]
Thank you. Appreciated.

**Comment by mobitar** [comment]
You can do this with a custom theme btw: https://docs.standardnotes.org/extensions/themes
