### ISSUE TITLE
I copy/pasted a single Evernote research note w/ dozens of hyperlinks into Standard Notes

### ISSUE THREAD

**Issue by DDub2020** [standardnotes/forum#967]
However, the hyperlinks from my EN note did not transfer in an "active" state into my Standard note document. 

I've toggled between editors to try and activate the links in my Standard Note, but I can't seem to get the links to transition from a text-only "https://string-of-blahblah-text" to an actual live hyperlink.

When I _add_ new hyperlinks to this Standard note (currently using the Plus Editor), the hyperlinks _do_ populate in an active/live status. Unfortunately, I can't seem to get the dozens of links I copy/pasted from my original Evernote note to become active hyperlinks in this new Standard note. 

Does anyone have suggestions? 

Apologies for any super noob points this question earns me. I'm not a developer or a coder and realize the answer may just be a seemingly obvious setting or other simple action I'm not taking.j I've tried to resolve this but I'm stumped.

FWIW, I love the mission, focus and approach of Standard Notes, and I'm an Extended/5 Year pre-pay user.  

Thanks in advance for any help.

**Comment by johnny243** [comment]
Hey @DDub2020 thanks for reaching out!

I was not able to reproduce your issue. Perhaps you could provide a sample of the text you are pasting into Standard Notes? (Feel free to remove any sensitive information :wink:)

![image](https://user-images.githubusercontent.com/5891646/81458500-a808d980-9168-11ea-9ea0-85e91895c4d9.png)

Thanks for using Standard Notes! :heart:

**Comment by DDub2020** [comment]
HI Johnny 243,

Thanks for your help. So, I tried to reproduce the issue as well. However, in my mini-test, I can't reproduce the issue either.

Granted, the document I copy/pasted from EN probably has over 100 hyperlinks, and my mini-test only included some dummy text and two different hyperlinks from two different sources.

Here are the original steps in my initial attempt to copy/paste my original research notes from EN to Standard:

1) Copied 3 to 4 large series of text/links/research notes from within one large EN note.
2) Pasted of these 3 to 4 large series of EN text/links/research notes into Standard Notes one at a time.
3) While the pastes of information into Standard Notes transferred all of my EN text information properly, all of the hyperlinks are dead within this new Standard Note.
4) When I past new hyperlinks into this new Standard Note that were not part of my original EN transfer, they *do* appear active and clickable.

I'm hoping my only option isn't to manually copy/paste over each dead link in my new Standard Notes and activate them by inserting a "new" live link using the hyperlink icon in the tool bar. However, I'm not sure what else to try. Might a different Editor might help? Or, perhaps the volume of information I was trying to transfer from EN to Standard caused an issue?

My original EN note has over 23k words and is around 15 MB to give you an idea of the size of the data.

Thanks again for your help. Much appreciated.

**Comment by johnny243** [comment]
Hi @DDub2020,

It seems that the auto-linking feature for pasted content is not available on the Plus Editor.

A workaround would be to switch your note to the Markdown Pro editor. You will then need to toggle the Preview to be able to click on your links.

![image](https://user-images.githubusercontent.com/5891646/81782593-0ebf2780-94c8-11ea-800a-4b6e8e9ed044.png)

Let me know if that helps, thanks!

**Comment by DDub2020** [comment]
Belated thanks for your help. I recopied the entire original EN note and repasted it in several different segments into a new Standard Note. This new Standard note seems to have retained all of the hyperlinks. 

However, trying to edit this new Standard note with the correct hyperlinks over the past few days is almost impossible. The note goes blank every minute for 45 seconds while saving. Then, the "saved" note is actually left blank...

I see there is a 35 reply post regarding saving conflicts from the past few days. I'll check that out to see if there are any resolutions to this new issue. 

Thanks.

**Comment by JaspalSuri** [comment]
Hi @DDub2020, what OS are your running Standard Notes on? Is it the desktop, mobile, or web app? Are you using the Markdown Pro Editor or another Markdown editor (I'm asking just in case).

> I see there is a 35 reply post regarding saving conflicts from the past few days. I'll check that out to see if there are any resolutions to this new issue.

Thank you for doing that. Do you have a link to said post?

**Comment by mobitar** [comment]
> The note goes blank every minute for 45 seconds while saving.

Hmm..can you elaborate on this? Any chance you can capture a video of this happening? That would be very valuable.
