### ISSUE TITLE
Warning: Missing Undo or Session History on Mobile

### ISSUE THREAD

**Issue by otozyon** [standardnotes/forum#968]
Unfortunately there is (still) no proper undo or session history function on mobile.

This is a real deal breaker for serious note taking, actually I'd say for any note taking at all. It means you cannot use Standard Notes' mobile clients to write anything down that you cannot afford to lose. It could be just a simple editing mistake inside the note and whoops, everything's gone, no chance of getting hours or days of writing back.

You'd hope that your lost version(s) should have been synchronized to the web from time to time while you were writing meaning that you could restore them there but nope, as it seems for every note (I went through all of mine) only the last version gets stored on the servers and is available through the session history.

This now happened several times to a friend of mine whom I recommended the app to because I thought this was a solid piece of software. I now won't recommend it to anyone else anymore and will also myself switch tools. It's a pity. I loved the idea of finally having an encrypted note taking app where I could write down stuff that's important to me but with my notes being always on the edge of losing them, they are more properly encrypted in my memory where I at least won't lose them with a simple editing mistake.

I don't understand why this feature hasn't long been implemented on mobile. It's so very basic for a note taking app …

**Comment by JaspalSuri** [comment]
Hi, I'm sorry that this feature has not been available on the mobile apps. I've tested it out on my end and was able to reproduce the issue. I've added a feature request for this for our mobile dev (who joined us in late April) to review. Thanks for bringing this to our attention!

**Comment by JaspalSuri** [comment]
Hello again, 

I'm sorry for having left out an important piece of information - through the Extended plan, we offer the ability to record the history of changes made to a note with the [Note History Action Menu](https://standardnotes.org/help/26/how-do-i-enable-note-version-history) extension. 

Once installed, the note history will be available in the Actions menu. It's located underneath the field where you can add tags to a note. 

Changes that are made and saved on a mobile device will be accessible through this menu on the desktop app.

**Comment by radko93** [comment]
Unfortunately, we will have to add undo to Android, but if you have iOS you can use system undo feature - e.g. by shaking your device.

**Comment by JaspalSuri** [comment]
Hi @otozyon,

This feature was implemented into the stable versions of the mobile apps as of early November of last year (2020). I'm closing this thread, but feel free to let us know if you have any questions.
