### ISSUE TITLE
Entries NOT saved/info lost/unstable 1st time for long time user.

### ISSUE THREAD

**Issue by ccchan234** [standardnotes/forum#970]
hi~

I've been using STD notes for long time and think it's stable.

HOWEVER, today for repeated times (> 3 times),
the pasted text of > 2 notes are NOT saved.

I am not dumb and I am not new, this must be the software's problem.
And as a free user I cant complain much,
just make an issue entry here for others.
Thank you.

platform:
lenovo T580,
win10, home, 64bit, 1903,
STDnotes ver: 3.4.1

**Comment by ccchan234** [comment]
no joke,

the system is unstable,

for an entry even I type in macdonald's,

then i go to another notes and back,
that line become "m" only.

texts are missing.

**Comment by ccchan234** [comment]
![01 - Copy](https://user-images.githubusercontent.com/37549409/81736942-f223ef00-94c9-11ea-9a99-1e61914ed66c.jpg)
![02 - Copy](https://user-images.githubusercontent.com/37549409/81736946-f3551c00-94c9-11ea-8565-0db68ae4fa48.jpg)
![03 - Copy](https://user-images.githubusercontent.com/37549409/81736949-f3edb280-94c9-11ea-99c6-1d4a34cc0478.jpg)
![04 - Copy](https://user-images.githubusercontent.com/37549409/81736952-f4864900-94c9-11ea-9d16-97852b9e4205.jpg)

hi~
in 01, i only got 2 lines of entry, with time stamp.

in 02, i added a new line,

then in 03, i simply go to another note.

then in 04, when back into the 1st note,
the new added line disappeared.

in the PAST, that line is automatically saved.

now it sucks.
i lost hours of work.

**Comment by ccchan234** [comment]
no joke,

from using STD note everyday to now I cant even type a plan for tomorrow.

after typing and click to another note,
the firstnote's entry simply have not saved.
crazy.

**Comment by JaspalSuri** [comment]
Hi, I’m sorry to hear about what you’re currently experiencing. I have notified the team to look into this. 

Can you reproduce this on the [web app](https://app.standardnotes.org) or on the mobile app?

And if you don’t mind, please send an email to help@standardnotes.org just in case with a link to this thread.

**Comment by mobitar** [comment]
Note that after you paste text, you must wait about 500-750 milliseconds (half of a second) before a save event is triggered. So if you type something then switch notes really quickly, the save will not be triggered. Can you confirm that you see "Saving..."/"All changes saved" after you make your paste?

**Comment by ccchan234** [comment]
i can try record screen provided that i can hide my notes.

i am using desktop, not the web app.

will do soon.
thx

**Comment by mobitar** [comment]
Yes that would be great! You can create a "dummy" tag and create some dummy notes in there for the purpose of recording.

**Comment by ccchan234** [comment]
i say i am not a dumb,
i used std n for long time.

who the hell will paste and switch notes within 1 second? or 1000ms as u
mentioned.

**Comment by mobitar** [comment]
> who the hell will paste and switch notes within 1 second? 

Lol, well, can't rule anything out until we do. So the save request starts within 1000ms, which then begins a disk save. The disk save should take no more than 250ms. However, if your disk is full, or approaching full, you might encounter issues (but should be alerted of it). After the disk save is complete, the app will then save to the server, which should take no more than 1s. Does your hard drive have a healthy amount of space?

**Comment by ccchan234** [comment]
hi~

today i went out and shutdown and re-open the system.

the error seems NO longer present.

so i'll close this issue and thank you for the help.
thanks.

**Comment by ccchan234** [comment]
hi~ This just a 1.3MB video mp4 recorded the problem.

At the lower left of screen i opened a clock widget to show the time.
At then end after "text not entered issue", i demo-ed that
my PC can connect to wikipedia and browse.

As said, i am not a new user and i am not dumb.
I didn't experience this in the last year and
i experience this SUDDENLY without new install of windows or 
else etc.

thanks


[bandicam 2020-05-20 01-48-04-232.zip](https://github.com/standardnotes/forum/files/4652281/bandicam.2020-05-20.01-48-04-232.zip)

**Comment by mobitar** [comment]
Is this only happening with pasted text? Does it happen if you were to manually type characters?

**Comment by ccchan234** [comment]
> Is this only happening with pasted text? Does it happen if you were to manually type characters?

same thing if i directly type text using keybaord.

btw, i mostly ENTER text using PC's desktop programme, and READ-back thru android....

**Comment by mobitar** [comment]
It looks like the app is not recognizing that you typed anything. The right part of the editor is cut off, where it should say "Saving..."/"All changes saved" in the upper right corner. Can you confirm that you do not see this text when you are encountering this issue?

Can you also click Help > Toggle Error Console, and see if there are any errors being shown in the Console when you are typing?

**Comment by ccchan234** [comment]
the last screen is made using my Left LCD, which I put in portrait mode for reading PDF, i think nothing is cut...

I can made a 2nd using my 24" horizontal LCD, pls wait. 

and for the error console, i need to click "console" at the top?

**Comment by mobitar** [comment]
> and for the error console, i need to click "console" at the top?

First click the "hamburger" menu in the top left corner of the app. Then Help, then Toggle Error Console. This will display a multi-tab developer tools, and you should ensure the Console tab is open. Then begin typing in the note, and see if the console prints anything.

**Comment by ccchan234** [comment]
hey the console have some error but that display my username,
possible to teach me how to hide it?
how to make a window say notepad that make it always on and thus shade things behind? thx

**Comment by mobitar** [comment]
Hmm, you can clear the console so it removes any previous inputs that may reference file paths via this button:

<img width="798" alt="Screen Shot 2020-05-19 at 1 18 34 PM" src="https://user-images.githubusercontent.com/3277844/82363370-56b3e200-99d3-11ea-84a0-a66e3dd06c25.png">

**Comment by ccchan234** [comment]
[bandicam 2020-05-20 02-22-28-225.zip](https://github.com/standardnotes/forum/files/4652419/bandicam.2020-05-20.02-22-28-225.zip)

hi, i demo-ed i can browse internet at first,
forget to include the clock.

anyway it sucks the same way.

thanks

**Comment by ccchan234** [comment]
thanks for comment and pls leave any notice for me if i can help.

i have some jobs on the side so will response to help later. thanks.

STDnote is a good software and i almost have paid for it, yet the free
one is enough for me. thank you again.

**Comment by ccchan234** [comment]
it could have been my problem as i am an experienced PC user,
playing around with "multi keyboard macros" software and authotkey.

let me try add a virtualbox and try, if it's my PC's problem.

**Comment by mobitar** [comment]
Very strange. The app is not detecting that you typed something for some reason. You can confirm this by the lack of the "Saving..." indicator in the top right corner. Can you capture a screenshot of the Console to see if it throws any errors?

> playing around with "multi keyboard macros" software and authotkey.

Hmm, this is very interesting. Can you share more on your set up? Perhaps we can try to emulate these settings on our end as well to see if we get the same results.

**Comment by ccchan234** [comment]
> Very strange. The app is not detecting that you typed something for some reason. You can confirm this by the lack of the "Saving..." indicator in the top right corner. Can you capture a screenshot of the Console to see if it throws any errors?
> 
> > playing around with "multi keyboard macros" software and authotkey.
> 
> Hmm, this is very interesting. Can you share more on your set up? Perhaps we can try to emulate these settings on our end as well to see if we get the same results.

1. isn't the file bandicam 2020-05-20 02-22-28-225 have "error console" 
u wanted?

or else how should i do? thanks

2. MKM is a software by "mediachance", it got FULL function demo,
just the settings are not saved. u can dnld and try it free of charge.
the other is autohotkey, u shd have heard that, it's open source...
they help to map say ctrl+shift+a into a single key button etc.

**Comment by mobitar** [comment]
> the file bandicam 2020-05-20 02-22-28-225 have "error console"
u wanted?

No I'm not seeing the console in that video..

> MKM is a software by "mediachance"

Can you try disabling this program and any similar programs from your system and see if that affects the behavior inside the Standard Notes app?

**Comment by ccchan234** [comment]
hey the web-app is working normally,
i will use that at the moment.

let me know if the desktop program.exe need any trouble shooting,
thanks.

**Comment by ccchan234** [comment]
> > the file bandicam 2020-05-20 02-22-28-225 have "error console"
> > u wanted?
> 
> No I'm not seeing the console in that video..
> 
> > MKM is a software by "mediachance"
> 
> Can you try disabling this program and any similar programs from your system and see if that affects the behavior inside the Standard Notes app?

in my 2ND video, with file name bandicam 2020-05-20 02-22-28-225,
at 0:00:19, there is a black part in the right side.... did I sent wrong?
btw, it's empty.
thanks

**Comment by ccchan234** [comment]
> > the file bandicam 2020-05-20 02-22-28-225 have "error console"
> > u wanted?
> 
> No I'm not seeing the console in that video..
> 
> > MKM is a software by "mediachance"
> 
> Can you try disabling this program and any similar programs from your system and see if that affects the behavior inside the Standard Notes app?

the file end in "225".zip...

**Comment by mobitar** [comment]
> there is a black part in the right side

Ohh..totally missed that. You're right. I expected it to be at the bottom :)

Hmm, indeed, no errors being thrown. In that case it might be at the system level. Some sort of interference with keyboard events. I'd be intrigued to see what would happen if you disabled any 3rd party programs that interfere with keyboard events + disable any macros, etc.

**Comment by ccchan234** [comment]
> > the file bandicam 2020-05-20 02-22-28-225 have "error console"
> > u wanted?
> 
> No I'm not seeing the console in that video..
> 
> > MKM is a software by "mediachance"
> 
> Can you try disabling this program and any similar programs from your system and see if that affects the behavior inside the Standard Notes app?

^--try shutdown MKM and AHK, didn't help in the desktop.exe,

anyway i am using webapp now, it works.

**Comment by mobitar** [comment]
And if you quit the desktop app and restart it? Does it start working then? (Be sure to quit from tray as well)

**Comment by mobitar** [comment]
If you would be up for a screen sharing session please let me know. Your app being in this state would be very valuable for us to poke around on. Would be happy to compensate your time with some BTC/LTC :) But totally up to you. I understand if you care about privacy you wouldn't want someone poking around. I'm just very intrigued by your situation. If you would be up for it please email me at mo@standardnotes.org or find me on our [Slack group](https://standardnotes.org/slack). Thank you!

**Comment by ccchan234** [comment]
> If you would be up for a screen sharing session please let me know. Your app being in this state would be very valuable for us to poke around on. Would be happy to compensate your time with some BTC/LTC :) But totally up to you. I understand if you care about privacy you wouldn't want someone poking around. I'm just very intrigued by your situation. If you would be up for it please email me at [mo@standardnotes.org](mailto:mo@standardnotes.org) or find me on our [Slack group](https://standardnotes.org/slack). Thank you!

err..

i am trying to make some new VM with the same settings,
/w mkm and AHK which I use (indeed MKM is added only last month).
let me see if the VMs suck or not and could tell you if there is problem instead.
thanks

**Comment by cyb3rz3us** [comment]
Personally, I would be curious to know 2 things:

1. Is there any firewall, malware, AV, IDS\IPS, etc. software being used on the PC?
2. Did the macro app (I think it was MKM) exist back when things worked fine or is it a new addition to the system after which things started acting up?

**Comment by ccchan234** [comment]
> Personally, I would be curious to know 2 things:
> 
> 1. Is there any firewall or IDS\IPS software being used on the PC?
> 2. It looks like the macro app (I think it was MKM) was added within the last month --- so correct in saying the issues started after this new application was installed?

1. only win10's firewall and windows defender is used, no 3rd party anti virus.

2. possible, probably, but i cant sure. becoz BOTH mkm and AHK are low level programs that deal with keyboard......let me tell more later when i setup new VMs and install THEM, i use them everyday now.

**Comment by ccchan234** [comment]
to make it more complex,
i did use "KM cable", you can google on net,
again it interact with keyboard and mouse, sharing them over network ><

forgive me pls.
