### ISSUE TITLE
[Help Wanted] Turn off automatic window pane resizing?

### ISSUE THREAD

**Issue by NikNew234** [standardnotes/forum#972]
**Describe the issue**
The panes in the left of the notes windows automatically expand and collapse upon hover, even when there is lots of screen space

**To Reproduce**
1. Open Standard Notes on Windows 10 desktop.
2. Move mouse from left to right
3. Panes automatically expand and collapse, even when there is lots of unused screen space

**Expected behavior**
Ability to turn off auto resize? Or resize stops if there is sufficient width available?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A.
 - Version 3.4.1

**Additional context**
N/A

**Comment by JaspalSuri** [comment]
Hi, do you perchance have the Dynamic extension activated? Please go to Extensions > Installed Extensions > Themes > `Dynamic` and click on <KBD>Deactivate</KBD> if needed. 

If not, please let me know!

**Comment by NikNew234** [comment]
Awesome thanks, that works. I thought it might be somewhere but couldn't remember anything!
