### ISSUE TITLE
External images not rendering in Mobile App, but fine on Desktop

### ISSUE THREAD

**Issue by MNicholas73** [standardnotes/forum#975]
Images (externally-hosted and _not added with FileSafe_) are only rendering on Desktop and Web apps, but they fail to load - and have a crossed-out line - on Android mobile app.

 - Android
 - Device: Samsung Galaxy A70
 - Android 10 (Samsung One UI v.2.0)
 - Browser n/a (images *do* load successfully in Android Chrome browser)
 - 3.0.21

**Comment by JaspalSuri** [comment]
Hi, I'm sorry that you're experiencing this issue. 

I'm afraid that I can't reproduce this on a Pixel 3a, but I can on macOS. I'll pass this along to the team.

**Comment by MNicholas73** [comment]
Thanks! Just got a paid sub. to this app and really loving it - seemed to take an age to find it but glad I did, in the end.

**Comment by JaspalSuri** [comment]
Thanks for supporting us by subscribing to Extended! I'm glad that you finally found it. :) 

Hey @radko93, sorry for not mentioning you here earlier. Are you able to reproduce this on any of your Android devices?

**Comment by MNicholas73** [comment]
n/p! Btw, I've noticed the bug above is also in Markdown Pro editor.

**Comment by mobitar** [comment]
> I'm afraid that I can't reproduce this on a Pixel 3a, but I can on macOS

@JaspalSuri can you elaborate?

**Comment by JaspalSuri** [comment]
> Btw, I've noticed the bug above is also in Markdown Pro editor.

Thanks! I can confirm this as well.

> @JaspalSuri can you elaborate?

Yeah, the image renders on Android for me, but on macOS, it has the default thumbnail that's provided when an image exists but doesn't render. I see the same thing when toggling the preview on the Markdown Pro editor.

This is the HTML that appear in the Plain Editor:
`<figure><img src="https://i.imgur.com/F80xTBu.png" data-image="xdrpfmxfkr74"></figure>`

![CleanShot 2020-05-19 at 15 02 32 PM](https://user-images.githubusercontent.com/44656000/82382997-d9dc3480-99e1-11ea-91fb-fd192a395011.png)

**Comment by JaspalSuri** [comment]
Just to double check, @MNicholas73, you're not hosting the images on Imgur, correct?

**Comment by MNicholas73** [comment]
Nope! These are images are hosted on a personal domain (non-https).

**Comment by JaspalSuri** [comment]
Thanks for letting me know! I'll be sure to update our internal note to say that they're self-hosted.

**Comment by MNicholas73** [comment]
Thanks!

**Comment by radko93** [comment]
Android currently does not allow fetching non-https content in apps, that's why your self-hosted images won't work, unfortunately. More details on this: https://developer.android.com/training/articles/security-config

**Comment by MNicholas73** [comment]
Ah, ok, that makes sense. I've been meaning to buy an SSL certificate for my site anyway. One more reason to!
