### ISSUE TITLE
Pasting images with FileVault and Bold Editor ignores caret position

### ISSUE THREAD

**Issue by nabati** [standardnotes/forum#976]
**Describe the bug**
Using FileVault and Bold Editor, the image is not pasted at the caret but at the top of the note. 

I'd expect the image to be pasted at the caret instead.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version 3.4.1

**Comment by csk** [comment]
FYI, this bug is already reported here: https://github.com/standardnotes/bold-editor/issues/17
