### ISSUE TITLE
[Help Wanted]-Installer fails to complete

### ISSUE THREAD

**Issue by dogugotw** [standardnotes/forum#977]
**Describe the issue**
I updated Win 10 to 1909 yesterday.
Today Standard Notes is gone. The file structure remains but the actual files are missing (no exe, no dlls, nada).
I downloaded the current Windows installer for 3.4.1.

**To Reproduce**
Double click installer.
Some pop-up displays and disappears before I can read it.
'Installing Please Wait' dialog is displayed.
The green bar goes about 25% across the panel and hangs there.
I let it run for 3 hours, no joy.
I tried running the installer as an admin and the only difference is I get an initial 'Do you want to allow this app to make changes'. I answer 'Yes' and get the same 25% green bar and nothing else.
I tried running with and without my VPN thinking that maybe the installer was calling home and the VPN was being blocked; no joy.

**Expected behavior**
I expect the app to install. I've been running Standard Notes for several years without issue.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Win 10 Pro version 1909
 - Browser Firefox (shouldn't relate to the issue)
 - Version 3.4.1 - <update> I paid for the 'Extended' option back in 2018.

<update 2>
I was poking around in the directory tree used for Standard-Notes and found:
C:\Users\<myName>\AppData\Local\standard-notes-updater\installer.exe
Double clicked and the client is installed version 3.3.5
The Date Modified on the file is 3.Apr.2020.
In the client hamburger 'Updates' menu, the option to 'install pending update' exists so I clicked that and 3.4.1 installed.

No clue but it's working again.

**Comment by mwcarlsn** [comment]
Had a similar problem.  Windows had updates and SN stopped working.  In face the icon on the desktop couldn't find the program.   I followed your steps above and had exact same result.   Client installed and then saw an update was ready to install.  Once the update installed SN started working again.  THANK-YOU!!

**Comment by dogugotw** [comment]
Glad I'm not the only one.

**Comment by JaspalSuri** [comment]
I'm sorry to hear that. Thank you for sharing the solution that worked for you!

Our desktop dev (@baptiste-grob) has been working hard on the next release to address multiple bugs. It's currently in beta and available [here](https://github.com/standardnotes/desktop/releases/tag/v3.4.2-beta1). :)

**Comment by dogugotw** [comment]
No worries. I'm not convinced this wasn't something that happened during
the Windows update; this last big update had a number of problems and the
timing is suspicious. Good luck on the next update!

**Comment by JaspalSuri** [comment]
We'll need all the luck that we can get! The issues I've seen on BleepingComputer can be pretty bad. 😂 

Thanks for the kind words. 😄
