### ISSUE TITLE
Unpublish listed notes that are deleted

### ISSUE THREAD

**Issue by deadlyhifi** [standardnotes/forum#98]
I've was playing around with listing notes and published 2, then deleted them out of Standard Notes. The 2 notes are still on my listed page and I don’t appear to be able to delete them.

See https://listed.standardnotes.org/@deadlyhifi

Expected behaviour would be to either:
* Warn that the note is listed and will be unpublished as part of deletion.
* Disallow deletion until it's been unpublished.

**Comment by mobitar** [comment]
Hmm that's an interesting edge case. The two systems don't really communicate unless explicitly directed to do so by you.

I think in this case the solution would be to allow deleting a post from your Listed dashboard or the post page. I've made a note of this. Thanks!

**Comment by fschrofner** [comment]
Same goes for notes published to private links. Once you've deleted the note in the standard notes app, there is no way to delete the published page (afaik).

**Comment by janvaniperen** [comment]
And... I now encounter this same with custom css on listed... deleted an active css, created a new one... yet no reflection of [change on the listed site](https://listed.standardnotes.org/@jan).

**Comment by janvaniperen** [comment]
@mobitar Appreciated!

**Comment by effieeee** [comment]
Deleting published posts is now possible on the blog settings page
