### ISSUE TITLE
Android sync - unable to load item

### ISSUE THREAD

**Issue by baldgzr** [standardnotes/forum#981]
Seems I have a note that won't always sync in the morning:
![Screenshot_20200519-130523](https://user-images.githubusercontent.com/49796379/82480345-90681400-9acb-11ea-96d1-e4fe502769f7.png)

device ram average 2.0Gb or 3.7Gb and storage 20 Gb free of 64Gb S.Notes 3.0.21 is using 80.88 Mb so the sync should work OK.

Couldn't find a simple way to locate this note by item number (uuid?), so I can work out how to fix it?

Cheers

**Comment by JaspalSuri** [comment]
Hi, please go to our [web app](https://app.standardnotes.org) to sign in and open the Batch Manager via the Extensions menu. Scroll down all of the way to make sure that all of the notes have "loaded". 

From there, press <KBD>cmd</KBD>-<KBD>F</KBD> (macOS) or <KBD>ctrl</KBD>-<KBD>F</KBD> (Windows) on your keyboard. Paste in the Identifier, `0bec2e7d-d64b-4343-b833-de364d6`, to locate the note. Read the contents of the note's title and body to then relocate it via the app's search feature as you typically would with any note.

I will mention our mobile dev, @radko93 so they can add this to their todo list. 😄

**Comment by baldgzr** [comment]
Thank you, your advice worked and I found the note with maybe too many encoded images copy+pasted in. All fixed now.

It would be good if the Android app could handle large notes if the local resources are available.

Cheers.

**Comment by mobitar** [comment]
Btw you can also type identifiers in the desktop/web search box now and it will bring up that note :)

**Comment by baldgzr** [comment]
That will make it easy to find the notes if I get the issue again.
Thank you. :D

**Comment by JaspalSuri** [comment]
That's good to know! Thanks for doing that! I'll go ahead and close this issue.

**Comment by TheMany172** [comment]
Hey - I have this same issue

App syncs great on dektop and web

But on android it fails with the same message and then lists 3 items

However Searching in the web app for the item codes does not show anything at all for me

**Comment by dedfft** [comment]
> Btw you can also type identifiers in the desktop/web search box now and it will bring up that note :)

Does it still work? Doesn't work for me, have the same problem
