### ISSUE TITLE
[Help Wanted] folders extension repository

### ISSUE THREAD

**Issue by wasifhossain** [standardnotes/forum#982]
Hi,

I was searching for the `folders` extension repository at https://github.com/sn-extensions, but unfortunately could not find so. Is it intentional to keep it private, or is it developed by some 3rd party entity?

Thanks!

**Comment by JaspalSuri** [comment]
Hi @wasifhossain! I believe [this might be the repo](https://github.com/standardnotes/folders-component) that you're looking for. 

From what I recall, it was developed in-house. :)

**Comment by wasifhossain** [comment]
thanks so much!
