### ISSUE TITLE
Autolock times

### ISSUE THREAD

**Issue by mrdoornbos** [standardnotes/forum#983]
5 minutes is a tad too short and 1 hour is a tad too long for my day to day. Seems like a small thing, but usability would improve greatly for me with either a 15 or 30 minute option in between the 5 minutes and an hour. 

Thanks for all the hard work!

**Comment by baptiste-grob** [comment]
Yes, this has been discussed a couple of times before and we agree that letting you set a custom time would be best, to cover all use-cases :) we want to get around to it at some point.

**Comment by tiddesk** [comment]
We really need a user-definable timer. Also useful would be a toggle to enable autolocking when the desktop is locked (by user intervention or screensaver).

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/1674
