### ISSUE TITLE
Automatic Dark/Light mode switching

### ISSUE THREAD

**Issue by theontho** [standardnotes/forum#986]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
yes

**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
**Describe alternatives you've considered**
I would like automatic light theme / dark theme switching in standard notes according to the OS setting.  I put my iOS & macOS devices on auto, so it's light during the day and dark during the night.  Having to manually switch my theme in macOS & iOS is annoying and makes standard notes hard to read when I'm outside during the day time or blinding during the night time.

I've been a paying customer for a few years.

**Comment by mobitar** [comment]
On mobile you can already do this by long pressing on a theme to select it as your default dark theme. On desktop/web this is a todo.

cc @baptiste-grob

**Comment by effieeee** [comment]
Further implemented as an actual setting under General > Appearance
