### ISSUE TITLE
Protected PIN don't work

### ISSUE THREAD

**Issue by rajeshisnepali** [standardnotes/forum#988]
![standard_note_protected_issue](https://user-images.githubusercontent.com/23610013/82867421-9128fc00-9f4a-11ea-90b8-37a94cf11043.png)

Let me explain to you.
The first card (_broadway_con_) is set to "Ignore PIN for 1 week ".
If I'm protecting other cards, it doesn't prompt with how long the PIN should be ignored. All the other cards take the same config as the first one. 

The config (Don't ask PIN) should be different on every card, isn't it?

**Comment by mobitar** [comment]
The "Remember for" option is global, and not particular per note.

**Comment by cyb3rz3us** [comment]
**Question**: Is there such a feature to "Ignore a pin"?  I thought the pin is either enabled or disabled and if enabled, then we can tune for how long it is remembered.

I am unaware of any "ignore pin" option so curious if it exists?

**Comment by JaspalSuri** [comment]
I don't think this feature exists based on what I know and have tried out, but @baptiste-grob would know for sure.

When going to Account > Manage Privileges, that option doesn't appear to be there.

**Comment by rajeshisnepali** [comment]
> The "Remember for" option is global, and not particular per note.

@mobitar Are there any plans for "Remember for" on a particular note in the future?
