### ISSUE TITLE
Invalid passcode pop-up doesn't dismiss properly

### ISSUE THREAD

**Issue by sethmad** [standardnotes/forum#990]
The pop-up that appears when the user enters an invalid passcode behaves unexpectedly if the user types return to dismiss it.

Repro steps:

1) Enable Passcode Lock
2) Relaunch app
3) Type incorrect passcode and click "unlock" or press return
4) Press return to dismiss error pop-up
5) Pop-up closes and immediately reappears

**Comment by JaspalSuri** [comment]
Hi, is this in the desktop or web app? If the latter, what browser are you using? What OS is it running on?

Try relaunching the app again to see if the error goes away. (I'll still report it, of course!)

I haven't run into any issues with unlocking the web or desktop app in the past few days when using macOS.

**Comment by sethmad** [comment]
Desktop app 3.0.23 on Mac OS 10.15.4. This bug has persisted for me for weeks if not months.

**Comment by JaspalSuri** [comment]
Would you be able to update to [version 3.4.1](https://standardnotes.org/download/mac)? Let us know if you run into any issues or if the bug still persists. Thanks so much for that information!

**Comment by sethmad** [comment]
Fixed! Sorry, I didn't realize that I'd disabled autoupdates when I reinstalled the desktop app recently.

**Comment by JaspalSuri** [comment]
Glad to hear it; that was pretty fast! Have a great day!
