### ISSUE TITLE
TokenVault: Can't add new

### ISSUE THREAD

**Issue by kslstn** [standardnotes/forum#993]
The required 'Secret' field can't be empty. With every string I've tried, a tool tip appears saying 'Please match the format requested' when I click 'Create'.

Reproducible in the [demo setup](https://standardnotes.org/demo):

1. Create new note
2. Select TokenVault editor
3. 'Add new'
4. Fill 'Service' field
5. Fill 'Secret' or 'Note' field
6. 'Create'

**Comment by kslstn** [comment]
The real problem is that with every secret a tool tip appears saying 'Please match the format requested' and the field is marked as invalid. 

As a workaround I tried keeping it empty too.

**Comment by mobitar** [comment]
Secrets need to be a specific 16 character TOTP-based string. They're not arbitrary and can only be derived from a generator.

**Comment by kslstn** [comment]
Ah okay. I completely misunderstood the purpose of the feature. I was looking for a solution to store the backup codes of 2FA protected services. I found this and just didn't read the text on the page about it. Sorry!
