### ISSUE TITLE
[Feature Request] Allow diffrent editors between devices

### ISSUE THREAD

**Issue by BeeFox-sys** [standardnotes/forum#995]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yep!

**Is your feature request related to a problem? Please describe.**
Many may love the fact that what editor you switch to stays consistent between devices, I however get a tad annoyed at it as I prefer to use different editors on different devices. Now admittedly this may only effect Markdown editors however I still think it can be an issue especially with outdated devices where some editors aren't very compatible with it due to missing features of the device (for example html5 editors not being very functional on android 7 and lower)

**Describe the solution you'd like**
I propose some sort of setting that allows you to not sync the editors a note is using, so that changing it on one device doesn't effect another device. Sadly this might not be possible but it would be an amazing QoL feature if it was. 

**Describe alternatives you've considered**
Another option would be rather then just not syncing the editor, to change editors when loading notes with this setting enabled automatically. It wouldn't be as clean as the other solution. And of course there is the solution of I can stop being as lazy and just change the editor manually when opening notes on different devices, which is my current solution.

**Comment by JaspalSuri** [comment]
Hi, thank you for taking the time to provide us with your feedback!

If you're satisfied with using just one editor on that device, you can press and hold it to set it as the default editor for all of your notes there. Let me know if that's not enough and I'll go ahead and forward the feedback for review!

**Comment by BeeFox-sys** [comment]
Yep! Thank you! I misunderstood how the defaults worked across devices and have no issue! Thanks again!

**Comment by JaspalSuri** [comment]
You're welcome! I'm happy to hear that it works as expected!
