### ISSUE TITLE
[Feature Request] Streamline "Pinned" indicator

### ISSUE THREAD

**Issue by chikinn** [standardnotes/forum#996]
**Have you read the Longevity Statement?**
Yes.

**Is your feature request related to a problem? Please describe.**
The "Pinned" indicator takes up a lot of vertical space, both on web (sidebar) and on Android.  See attachment 1 (Android screenshot).

**Describe the solution you'd like**
Streamline how the indicator is displayed (e.g., to the side of instead of above the note title).  You could take inspiration from Simplenote's indicator (attachment 2, from Simplenote web).

**Describe alternatives you've considered**
Add an option to hide the indicator.  I'd be just as happy with that.

**Additional context**
![image](https://user-images.githubusercontent.com/16523426/83358077-d0c65e00-a325-11ea-836a-03c2a4c970d4.png)
![image](https://user-images.githubusercontent.com/16523426/83358218-ee47f780-a326-11ea-900a-bc6c3042980d.png)

**Comment by mobitar** [comment]
The vertical space used by the Pin flag is also used for other flags, like Locked, Protected, Archived, and Deleted. Sometimes you can have up to 3-4 flags on a note. In any case, this is something we are keeping in mind for larger design refactors.

cc @zsoltszilvai

**Comment by effieeee** [comment]
The pinned indicator is now a minimal "pin" icon on the top right!
